### ISSUE TITLE
Device "Domains"

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#1]
Use the VTP Domain or another field to assign devices to zones or domains of some kind.

Use this information either globally in searches etc (using drop-down selector in navbar) or simply to filter the layer 2 netmap image.

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/1](https://sourceforge.net/p/netdisco/nd2-features/1)

**Comment by ollyg** [comment]
Moved to Wishlist page in wiki

**Comment by ollyg** [comment]
tenancies are now implemented https://github.com/netdisco/netdisco/wiki/Configuration#tenant_databases
