### ISSUE TITLE
Printer Statistics

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#10]
Most printers have SNMP statistics that can be groked. 

From: Jeff Carpio &lt;jcarpio@ric.org&gt;                   

Date: Tue, 19 Jul 2005 04:23:42 -0500                 

Subject: \[Netdisco\] Printers                          

To: netdisco-users@lists.sourceforge.net              

Well I just want to say I have Netdisco and FreeBSD
cohabitating
beautifully ... but I would like to know if there is a
way to
incorporate printer info \(i.e. page counts, maintenance
reminders,
etc...\) into the netdisco webpage statistics.

Jeff

Reported by: maxslug-placeholder

Original Ticket: [netdisco/nd2-features/10](https://sourceforge.net/p/netdisco/nd2-features/10)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki
