### ISSUE TITLE
fqdn node search

### ISSUE THREAD

**Issue by jouluz** [netdisco/netdisco#1001]
## Expected Behavior

When doing node fqdn search, the search should do DNS query and use IP received in DNS response as search term. For example search for computer.domain.tld should translate computer name to IP and use that to perform the search.

## Current Behavior

When the search is done with fqdn or netbios name the search returns nothing. Search with IP or mac-address is working as expected.

If I inspect device ports, netdisco correctly displays hosts mac and ip-address and fqdn

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Context

This used to work just fine, but it has been broken for a while

## Your Environment

App::Netdisco	2.60.10
SNMP::Info	3.92
DB Schema	78
PostgreSQL	15.00.2
Perl	5.16.3

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
Hi @jouluz have you set domain_suffix configuration ? Then you should drop it from the search so it's just the hostname, not fully qualified. You can also add * or % to the end for wildcard.

If this doesn't help, please can you provide examples of your device or node names and what you are searching for?

**Comment by jouluz** [comment]
We have couple of domains. One for networking devices and one for end users devices. Domain A has networking devices and B end user stuff.

I reconfigured my domain suffix configuration from 

domain_suffix: '.a.domain.tld'

to (YAML list)

domain_suffix:
  - '.a.domain.tld'
  - '.b.domain.tld'


Here are the results now.
  
In this first example I'm doing fqdn search. Netdisco does not find a match
![1](https://user-images.githubusercontent.com/32631332/225535265-e303b7dd-98bb-4902-b6b1-bcec3fdc082c.png)

In the second example I'm doing hostname search without domain. Netdisco does find the match
![2](https://user-images.githubusercontent.com/32631332/225535441-ff45b473-a5fe-4cc5-96c3-ab0356cf1f65.png)

In the third example I'm inspecting port of the switch. Netdisco shows both hostname and fqdn
![3](https://user-images.githubusercontent.com/32631332/225535630-31e4f232-b421-463f-a853-7b0edb60f880.png)

And in this final example I'm doing wildard search for fqdn. Netdisco displays correct results
![4](https://user-images.githubusercontent.com/32631332/225535825-fa0d517b-6d9c-4ca8-9923-d8be44b487bb.png)

So I guess this is kind a working now as long as we remember to put * if we are using fqdn search.

**Comment by ollyg** [comment]
@jouluz its not very intuitive though is it. I'll leave this issue open to see if we can implement something a bit smarter.

Thanks for confirming all is OK.

**Comment by jouluz** [comment]
Thank you for your help @ollyg !

**Comment by ollyg** [comment]
implemented in 6586815f
