### ISSUE TITLE
Feature request: add "deletion" event to hooks functionnality

### ISSUE THREAD

**Issue by Rodjeur70** [netdisco/netdisco#1006]
Hi buddies,

Using Netdisco for a long time, hooks are great features. Question is: is it possible to add deletion event to it ?

Regards.

Rodjeur

**Comment by ollyg** [comment]
Hi Rodjeur

Sure, this is not too difficult to implement. I would like to check the use
case:

There is a manual device delete job which can be run at CLI, and there is
also expiry of devices and nodes after a while. Is it these features you
wish to hook into or some other thing?

Also for expiry would you like one event per “thing” such as node or
device? Or all the data attached to one hook event.

Please let me know

Regards
Oliver.

**Comment by Rodjeur70** [comment]
Hi Ollyg,

My use case is that I want to remove from my NMS via an http request to an external webservice a Netdisco deleted device (an existing hook is already used for create/update it in my NMS after a discover). So my wish is to can trigger an hook when a deletion event occurs into Netdisco (manually from GUI or from internal scheduler).

Rodjeur

**Comment by ollyg** [comment]
published in release 2.062000, many thanks for the feature suggestion!
