### ISSUE TITLE
Mac input does not show on which port it is connected to

### ISSUE THREAD

**Issue by Palerm0** [netdisco/netdisco#1007]
I have a Mac address. When I search for it it gives me the following information:
![image](https://user-images.githubusercontent.com/56974925/226934346-d7db9f7c-7254-46a5-a892-95ffd07513e5.png)

What am i doing wrong,

How can I find the connected port number and switch name. 

## Expected Behavior
It would be great if you search for a mac address that you also find the switch and port. 

## Current Behavior
Dont know if it is a Bug (Verry likely it is a user problem/expectation)

## Steps to Reproduce (for bugs)
Searching for any mac address I have.

## Context
When I have an issue with a PC. I would like to know on witch switch an port this PC is. So I can troubleshoot the network side

## Your Environment
![image](https://user-images.githubusercontent.com/56974925/226936675-9a80d879-89f2-4a3e-9c61-9a957687016d.png)

**Comment by rc9000** [comment]
Hi! Netdisco tries to find two different kinds of mappings:

 * ip -> mac: this is essentially recording the output of "show arp", in Netdisco lingo it's called `arpnip`
 * mac -> port: this is "show mac-address table", Netdisco calls it `macsuck`

Finding the both these mappings allows to indirectly answer "the node with ip 1.2.3.4 is plugged in on switch5 Gi1/8".

In your example, only the ip -> mac mapping for the mac address was found, but no mac -> port mapping. Either your switch is not discovered by Netdisco, or the macsuck operation fails.

I'd try:

    # make sure the switch is in Netdisco and responds to SNMP
    netdisco-do -D -d <switch ip> discover

    # manually macsuck and see if anything goes wrong
    netdisco-do -D -d <switch ip> macsuck

The -D flag will add some debug output, so you should see errors or messages that tell you what's happening or failing. For even more details, you can use -DISQ
