### ISSUE TITLE
hello,How to set up scheduled scans  : ~/bin/netdisco-do discover -d

### ISSUE THREAD

**Issue by wanqingfeng** [netdisco/netdisco#1008]
## Config info 
How long is the SNMP scan interval and where to set the scan time, such as every 24 hours。

READ THIS FIRST!
----------------

STOP! If your ticket is about a device not being detected correctly,
see SNMP::Info: https://github.com/netdisco/snmp-info/issues/new

STOP! If you have new MIBs to submit,
see netdisco-mibs: https://github.com/netdisco/netdisco-mibs/issues/new

STOP! If you are running a netdisco docker setup,
see netdisco-docker: https://github.com/netdisco/netdisco-docker/issues/new

everything else about Netdisco's behaviour is good, here :-D

the more info you can provide, the easier it is for us the help you, so please
fill out as many of the items below as possible.

Provide a general summary of the issue in the Title above

when including netdisco config snippets, whitespace matters since it's a yaml file
for github issues it really helps if you include the relevant config parts in a codeblock (code fencing)
see the "code" subject on https://guides.github.com/features/mastering-markdown/ for that)
this should preserve spaces in the issue tracker and make troubleshooting quicker

-->

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by rc9000** [comment]
The netdisco-backend process will check the `schedule:` section of the configuration:

https://github.com/netdisco/netdisco/wiki/Configuration#schedule

The example from above link will discover your devices once a day, at five minutes past seven:

```
schedule:
  discoverall:
    when: '5 7 * * *'
```

To start netdisco automatically on system startup, see: https://github.com/netdisco/netdisco/wiki/Install-Tips#init-and-run-control-scripts
