### ISSUE TITLE
Feature-request: neighbour map depth and/or until end of lldp chains

### ISSUE THREAD

**Issue by haugsvar** [netdisco/netdisco#1009]
irstsly, thank you guys for the awesome effort you've put in to make netdisco. My apologies if this is not the way correct way to make a feature request.

Neighbouring maps has currently options to map "All devices" or "Only neighbours". In many cases All devices are just too much. 

I'd like suggest an option for showing "depth from device" and/or until lldp chain ends. A third possibly useful option is to graph any device with  device ip and/or device alias within the same ip subnet as your starting device

Sincerly

Vidar Haugsvær

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
color root node
hide options if large number of devices
store positions

**Comment by ollyg** [comment]
implemented in e52f789
