### ISSUE TITLE
Inventory by Platform reports in tenancy setup does not work

### ISSUE THREAD

**Issue by d1etmar** [netdisco/netdisco#1014]
we have tenancy netdisco install with 3 instances(+ACI plugin). This works very well, we just have had a problem with the Inventory by Platform reports if generate it from a "non Default" instance (Inventory by Software Platform seems to work ok ) . We used 2.6.04 and upgraded now to 2.6.10 . As reading thru the changes i thought "* #979 tenancy awareness for generic reports" should fix it ? It did not in our install .. It seems that if the GUI is in "tenancy mode", then the URL misses the "model=" to be able to search correctly ?

**Comment by ollyg** [comment]
please would you test whether the problem appears for "By Software Release" links as well?

So at the moment you report that in the Inventory page, the "By Platform" links to each model are not working. What about the "By Software Release" links to each OS version?

**Comment by d1etmar** [comment]
No this seems to work. For me it looks that the Software Search uses some sort of global serach. The Platform Uses model= and it looks it should "hand it over" to the search filter on the dest. page. But this seems not to work ? .

**Comment by ollyg** [comment]
Hi @d1etmar I have another thing you can try for me please. We need to separate the tenancy from the content of the tenant database (it could be a data issue, I mean).

In your Netdisco config you have the database: setting and also the tenant_databases: setting. Please can you swap entries in the two and see if the issue still manifests? Perhaps try a few combinations.

Many thanks.

**Comment by d1etmar** [comment]
We have following Config.

database:
  name: 'netdisco'
  user: 'netdisco'
  pass: 'xxxxx'

tenant_databases:
- tag: 'XXX'
  displayname: 'XXX'
  name: 'netdisco'
  host: '127.0.0.1'
  user: 'netdisco'
  pass: 'xxxxx'
- tag: 'YYY'
  displayname: 'YYY'
  name: 'netdisco'
  host: 'x.x.x.x'
  user: 'netdisco'
  pass: 'xxxxxx'
- tag: 'ZZZ'
  displayname: 'ZZZ'
  name: 'netdisco_aci'
  host: '127.0.0.1'
  user: 'netdisco_aci'
  pass: 'xxxxxx'

I swapped the order of the tenant config, but no change .  The Database Config is equal to the tenant XXX . The Reports by Platform or Software do work in (Default) GUI Settings, but not in XXX. Both have the same config to access the same DB.

I think it is not a Database ( source) issue . I think in /t/ Mode it looks that the "search anywhere" (q=) is used instead of the model=,os_ver= and so on,  in the Post Processing. But i am not a programmer at all.

Example : The Model=1941 search in /t/ finds another host with an Serial Number containing 1941 . If i then filter in the resulting GUI on Model=1941 i got correct results. So DB Source seems very fine to me.

thx for checking .

**Comment by ollyg** [comment]
@d1etmar thanks for making the tests, it helps a lot!

**Comment by ollyg** [comment]
@d1etmar I still cannot reproduce this :-(

I wonder if you could run the web frontend with debugging and tracing and share? If not here then oliver at cpan dot org.

`STARMAN_DEBUG=1 DBIC_TRACE=1 starman bin/netdisco-web-fg --workers=1 --disable-keepalive`

**Comment by d1etmar** [comment]
I will do the debugging.

Again i think the problem in /t/ Mode on the Inventory Page is if the "global Search - find anywhere " find's a result this will be shown. If there are no entries found it shows the correct Model. I have tried this with following .

global Search - find anywhere for 1941 in "Default Mode" will find a Device containing 1941 in the Serial Number -> same result as in /t/ Mode on the Inventory Page for Model=1941 . -> wrong.

global Search - find anywhere for 1841 in "Default Mode" will find the correct Device -> same result as /t/ Mode on the Inventory Page for Model=1841 . -> correct .

So the results showing in /t/ Mode for the Inventory Page is equal to the "find anywhere" in default Mode .

For your tests you could possible fake a Serial Number containing a Model in your DB , and give it a try . 
( S/N : ABCE1941DEFA  , Model=1941 )

**Comment by d1etmar** [comment]
Hi,

I have tried to do tracing. Got the SQL which is used. It looks that the query to the DB differs a lot between /t/ and the Default Mode . Default Mode uses a much more simple sql with model= and gives the correct result . In /t/ it tries to find "anything" but should only find model= .... 

hope this helps. , thx. Dietmar

[netdisco_trace.txt](https://github.com/netdisco/netdisco/files/11150652/netdisco_trace.txt)

**Comment by ollyg** [comment]
Thanks @d1etmar are you able to share also the other lines in the debug -- the web requests handled by the server?

The SQL you shared is correct for the general search and the model search, so the big question is why is the web code causing the wrong route in the server. I do not know. It is very difficult to understand and I cannot reproduce the error.

**Comment by d1etmar** [comment]
Hi ,

Find attached the web requests - but they just show that the model= is missing in the request if a request comes from /t/ Mode , and therefore goes for a global search



[netdisco_trace1.txt](https://github.com/netdisco/netdisco/files/11152368/netdisco_trace1.txt)
