### ISSUE TITLE
Feature Request: API call to delete from SNMP Connect Failures

### ISSUE THREAD

**Issue by fenner** [netdisco/netdisco#1015]
In the IETF meeting network, we have a funny situation where a switch boots up for ZTP, and at that point it is discovered as an LLDP neighbor of the switch that it's plugged into.  However, since it's getting its initial configuration, it doesn't have SNMP configured, so netdisco can't talk to it.  Because of the aggressive timers, and the length of the ZTP process, netdisco has often failed to connect 10 times and the switch goes into the SNMP Connect Failures table.

I'd like to request an API call to delete from the SNMP Connect Failures (and trigger a discover), that we can call when a switch has finished its ZTP process.

**Comment by ollyg** [comment]
I think the best approach is to implement an API call to run a Discover job, because that (like any user submitted action) should override any skip list.

**Comment by ollyg** [comment]
feature merged in 1031

**Comment by ollyg** [comment]
https://github.com/netdisco/netdisco/wiki/API#submit-one-or-more-jobs-to-the-queue

**Comment by ollyg** [comment]
or call https://github.com/netdisco/netdisco/wiki/API#remove-jobs-for-a-specific-device
