### ISSUE TITLE
FR: vlan inventory keyed by VLAN ID only

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#1018]
The VLAN inventory is very usfeul, but at the moment it considers the name to be a unique property as well as the VLAN ID, so 

VLAN 20 name "foo"
VLAN 20 name "bar"
VLAN 20 name "quux" 

will appear as three separate list entries.

This is definitely correct behavior and I'm not advocating changing it -- however it would be handy if there was another report that had a VLAN inventory that was keyed ONLY by vlan ID, so would return one line

VLAN 20 names "foo" "bar" "quux" 

and that had an additional column "number of names" which counted the number of different names that vlan was using.

Both reports would be of use to us, as we have two situations:

First (less common) - the same VLAN ID has been used for different functions
Second (far more common) - the same function has been configured with disparate names, eg "eudroam" "Eduroam" "EDUROAM" "eurodam" etc.

Long term we aim to normalise the vlan names but at the moment we're not there yet.

This is only worth considering if it's comparatively minor to implement as core functionality is available by just looking at the info for a particular vlan - this new report would just make a certain situation a little easier to visualise.

Thanks!

**Comment by ollyg** [comment]
implemented in 122daf81 (as VLANs with Multiple Names report)
