### ISSUE TITLE
NetDisco API 404 Errors

### ISSUE THREAD

**Issue by netdisco-csiro** [netdisco/netdisco#1035]
Obtaining an API key works and return a HTTP 200 code:

$ curl -D - -X POST -H "Accept: application/json" http://127.0.0.1:5000/login -u USER
Enter host password for user 'USER':
HTTP/1.1 200 OK
Server: Perl Dancer 1.3513
Content-Length: 46
Content-Type: application/json; charset=utf-8
Set-Cookie: dancer.session=REDACTED; path=/; HttpOnly
X-Powered-By: Perl Dancer 1.3513
Content-Security-Policy: frame-ancestors none;
X-Frame-Options: DENY
Date: Thu, 11 May 2023 01:14:02 GMT
Connection: close

{"api_key":"KEY"}

## Expected Behavior
Searching for devices returns a HTTP code 200 and devices

## Current Behavior
Netdisco returns 404 for the API URL api/v1/search/device

curl -D - -X POST -H "Accept: application/json" -H "Authorization: KEY" "http://127.0.0.1:5000/api/v1/search/device?dns=test.csiro.au" | head
HTTP/1.1 404 Not Found

## Environment
Software	Version
App::Netdisco	2.60.10
SNMP::Info	3.92
DB Schema	78
PostgreSQL	10.00.23
Perl	5.26.1

## Device information
The device I am searching for exists:

$ netdisco-do show -d test.csiro.au  | more
[73293] 2023-05-11 01:12:44  info App::Netdisco version 2.060010 loaded.
[73293] 2023-05-11 01:12:44  info show: [1.1.1.1]/interfaces started at Thu May 11 11:12:44 2023
\ {
    1   "lo",
    2   "VMware VMXNET3 Ethernet Controller (2)",
    3   "VMware VMXNET3 Ethernet Controller (3)"
}
[73293] 2023-05-11 01:12:45  info show: finished at Thu May 11 11:12:45 2023
[73293] 2023-05-11 01:12:45  info show: status done: Showed interfaces response from 1.1.1.1

**Comment by ollyg** [comment]
Hi @netdisco-csiro I can see that the cURL command has extra parameters: `-D -`:
```
curl -D - -X POST ....
```

Please can you try the exact command as in the docs:
```
curl -X POST \
-H "Accept: application/json" \
-H "Authorization: 9d8ff4b68dbedb804c90e9b375eea48a" \
"http://localhost:5000/api/v1/search/device?dns=mydevice.example.com"
```

**Comment by netdisco-csiro** [comment]
I get the same result, which is the contect of the NetDisco homepage
NB: the "-D -" just gets curl to print out the received headers revealing the 404 response from the Perl Dancer webserver that NetDisco uses.

 `curl -X POST -H "Accept: application/json" -H "Authorization: REDACTED" "http://localhost:5000/api/v1/search/device?dns=mydevice.example.com"
 
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-type" content="text/html; charset=" />
  <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
  <title>Netdisco</title>`

**Comment by netdisco-csiro** [comment]
I got this working by upgrading from 2.60.10 to 2.61.1
