### ISSUE TITLE
API /login do not pass a user when external (trust_x_remote_user) method is used

### ISSUE THREAD

**Issue by jnovak-netsystemcz** [netdisco/netdisco#1036]
Hi,

I'm quite new to netdisco API, but I got familar with it. I have several netdisco installations where it works fine, but I found one exceptional system. The issue is that even I provide correct user and password, I receive "authentication failed" all the time.
I checked the system and the difference is that netdisco is behind reverse proxy and the reverse proxy verifies used/password in LDAP and just pass authenticated used name in trust_x_remote_user variable. It looks it works fine for UI, but not for the API.

I checked source code (https://metacpan.org/release/OLIVER/App-Netdisco-2.061001/source/lib/App/Netdisco/Web/Auth/Provider/DBIC.pm) and I think that the issue is in match_with_local_pass() where it do not check existence trust_x_remote_user and tries to verify password which fails every time.
get_user_details() takes trust_x_remote_user into account already.

## Expected Behavior
API /login should pass any user which was verified with external proxy and passed in trust_x_remote_user

Note: I use trust_x_remote_user variable, but it should work for trust_remote_user too and it should follow no_auth variable.

## Current Behavior
API returns {"error":"authentication failed"} all the time.

## Possible Solution
Modify source code, see proposal above.

## Steps to Reproduce (for bugs)
1. Create environment where reverse proxy with any authentications stays before netdisco-web and passes variable trust_x_remote_user to netdisco-web
2. Configure netdisco deployment.yml with trust_x_remote_user: true
3.  Try to use API /login with correct user/password

## Context
See above.

## Your Environment
* Netdisco version used: Tested with several older versions up to latest 2.061001

## Config info (deployment.yml)
See above.

**Comment by ollyg** [comment]
Many thanks for the bug report @jnovak-netsystemcz

**Comment by ollyg** [comment]
implemented in 65a908dc

**Comment by jnovak-netsystemcz** [comment]
Hi. I'm sorry, but it still doesn't work. The issue is that /login do not provide api_key answer.
I tried to track why, but I don't understand the code enough. I just found that:
* in lib/App/Netdisco/Web/AuthN.pm:login_sub() is not able to authenticate the user in authenticate_user(), but I think it is correct because there is no such user when trust_x_remote_user is used
*  /login is handled somehow in the code on many places, but I can't find how to change it to make it running

I'm open to test and troubleshoot code changes.

**Comment by ollyg** [comment]
Have reopened and will look into it @jnovak-netsystemcz

**Comment by jnovak-netsystemcz** [comment]
Thank you

**Comment by ollyg** [comment]
Hi @jnovak-netsystemcz I realised there is a confusion here. You do not need to log in.

This is what trust_x_remote_user does. It bypasses all login because it assumes you have controlled access via Apache or another proxy. The user is taken from the header but that is all.

Now, swagger-ui might not work properly because it doesn't submit the X-REMOTE_USER header, but the cURL commands will work fine:

```
curl -L -X GET "http://localhost:5000/api/v1/object/device/1.2.3.4" -H "accept: application/json" -H "X-REMOTE_USER: anyusername"
````

**Comment by ollyg** [comment]
@jnovak-netsystemcz I am looking into whether the swagger-ui can be made to work with the header, but not sure yet

**Comment by jnovak-netsystemcz** [comment]
I'm not sure whether I expressed correctly whole context of the issue...

API documentation says that client should start with /login, then they receive key and the key is used for later API calls.

I think that a client should not care whether server is used with local user database, LDAP, X-REMOTE_USER or so. Therefore it should use /login and then other calls in every case.

The issue is (as I see it) that when I call /login with correct user name and password to authenticate to WWW server, I pass WWW server authentication and it fills x_remote_user and calls Netdisco/API, but API /login never returns a key. It tries to authenticate provided user by Netdisco internals and it fails. Therefore /login responds with "authentication failed" which is technically correct, but should not happen.

My idea is that /login should bypass authentication when x_remote_user (and similar variables) is provided and should respond with a key. On the other hand I see in the code that there must be stored some user info during login so /login should do so too.
