### ISSUE TITLE
Subnet utilisation / IP inventory may not include all known subnets

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#1039]
I have some Dell OS10 switches that are configured as VLT pairs. The switch's 'main' management address is an SVI, and the dedicated management ports of each switch are connected directly to each other.

For some reason the IP range that I'm using for the dedicated management interfaces (192.168.111.0/24) doesn't show up in the IP Inventory or Subnet Utilization search fields.

ND is aware of the device's IP and subnet, because they are shown properly in the device's addresses tab:

address: 192.168.111.2
interface: mgmt1/1/1
description: mgmt1/1/1
Prefox: 192.168.111.0/24

On this view, the entry for prefix is a link

/search?tab=device&matchall=checked&q=192.168.111.0%2F24&ip=192.168.111.0%2F24

and this returns a correctly populated list of the devices that have IP addresses assigned in this range.

netdisco-do confirms that it can see the IP and subnet details:

$ netdisco-do show -e ip_netmask -d switchname
[2754914] 2023-05-24 13:34:25  info App::Netdisco version 2.061001 loaded.
[2754914] 2023-05-24 13:34:25  info show: [172.16.224.21]/ip_netmask started at Wed May 24 14:34:25 2023
{
    127.0.0.1       "255.0.0.0" (dualvar: 255),
    172.16.224.21   "255.255.0.0" (dualvar: 255.255),
    192.168.111.2   "255.255.255.0" (dualvar: 255.255)
}

not a huge problem, but it would be nice if the subnet utilization could see this 192.168.111.0/24 range, as I'd like to be able to be sure I don't accidentally reuse addresses across multiple devices!

Many thanks!

**Comment by ollyg** [comment]
Hi @kingtrw can you send me a snapshot of this device? I think I know how to fix it but I can't reproduce in my install here.

**Comment by kingtrw** [comment]
I can't either! It's working fine now. Perhaps was fixed in an update? Either way, seems fine now.
