### ISSUE TITLE
FR: extract map data, custom fields shown in map objects

### ISSUE THREAD

**Issue by rohanrajnv** [netdisco/netdisco#1043]
Hi Everyone,
We want to have a feature request done so that we an integrate the Netdisco Integrated with Our SOC and NOC Application.
Is there any offical channal or person that we can talk or meet to discuss the same.

**Comment by rohanrajnv** [comment]
Hi Ollyg,
We would like to extract the Map from the Net disco and display it on our application. We would like to add 4 Fields to the Map object so that once the customer clicks we can redirect to our application.
We would lik to sponcer this feature.

**Comment by rohanrajnv** [comment]
is there any way i can talk to someone as to explain the requirement and sponsoring the feature request?
The Web Link can be just a descripting column in the Host or the device.

**Comment by rc9000** [comment]
Hi @rohanrajnv, it might be better if you can specify here what you need, so everybody is on the same page.

Can you show how such a link would look like, and what dynamic parts like hostname or ip need to come from the object in the map?

I could see adding a URL template to the config, e.g. `map_device_url: https://example.org/inventory?hostname=[device.dns]`, then the part in `[]` is substituted in the actual map object. Would that work for your case? 

If you need any information that is not yet in Netdisco (like an asset tag or inventory number), we'd propose storing it in a [custom_field](https://github.com/netdisco/netdisco/wiki/Configuration#custom_fields) and our map url could also access that.

**Comment by rohanrajnv** [comment]
Hi Everyone,
We have the following feature to be added to the 
http://<IPAddress>/custom.php?action=host.dashboard.view&hostid=<HostID>&dashboardid=<DashboardID>
The IP Address, HostID and Dashboard can be placed in the netdisco database using our application.
Each Host ID showing a host we Monitor in our application. Each Host has a set of Dashboards for specific condition.
We also want the map to be displayed in the Grafana as our NOC and SOC software uses Grafana as the frontend.

**Comment by rohanrajnv** [comment]
Guys any help on this?

**Comment by ollyg** [comment]
there is now API endpoint to get the map data
