### ISSUE TITLE
PortVLANMismatch SQL materialises the WITH clause

### ISSUE THREAD

**Issue by barinet** [netdisco/netdisco#1044]
Virtual::PortVLANMismatch uses a chunky SQL query with a WITH clause.

It looks like adding "NOT MATERIALIZED" to this clause gives a ~ 30x speedup, enough to prevent the report timing out in the web UI in large environments.

**Comment by barinet** [comment]
looks like this requires PostgreSQL 12 or newer

**Comment by barinet** [comment]
Another way might be to make all_vlans into a VIEW; perhaps not as elegant as the locally-scoped WITH .. AS NOT MATERIALIZED but might be tolerable in order to support the older pgsql releases.

**Comment by ollyg** [comment]
at the moment Netdisco doesn't install any VIEWs into postgresql (which might be weird but it is what it is)

**Comment by rc9000** [comment]
I gave this a try and can get "not materialized" performance by using four different subselects instead. It would be ugly in pure SQL but since we have a Perl string we can just use a variable. Maybe somebody else can try the PR, seems to work fine here.

**Comment by ollyg** [comment]
brute force solution ♥️♥️♥️

**Comment by ollyg** [comment]
As mentioned on IRC, I plan to change the report anyway to display only the diff of the VLAN on each side, and this might change the query (for the better).

**Comment by ollyg** [comment]
I don't know that this is fully correct just yet, but can you let me know if it is slow or fast (relatively) on your system, please? 

https://gist.github.com/ollyg/81efd8b332a07d023c9915b566fb8f35
