### ISSUE TITLE
Wishlist: Add proper network map

### ISSUE THREAD

**Issue by dokh** [netdisco/netdisco#1049]
Appart from the irritating bouncy effect, the neighbor map is somewhat OK as long as it is limited to the neighbors of the device one is looking at.
The 'All devices network' view, however, is useless. The stars in a nightsky are easier to interpret than the mess created on that all devices neighbors map.
And if only a saved map would be available to all devices. Pretty painfull to redraw that map for all devices!

So my wish is for a network map that is consistant across devices and where the only dynamic action would be to center the device one is looking at.

**Comment by kingtrw** [comment]
I think this is a very big thing to ask for, especially given that ND's development is done by a small number of individuals in their spare time.

By default the map is pretty chaotic - but you reposition devices and then save the layout. Once saved, the map view will persist across all devices.

Drawing sane network topology maps is pretty complicated and I haven't yet seen an NMS that does it in a way I'd cosider 'perfect' - even the expensive and very expensive ones have some pretty major UX issues. 

I'm not a developer (of ND or anything else) but my understanding is that the network map is a third-party component that was put in as a relatively quick value add -- useful to some (I use it a lot) but not a core function.

You mention "And if only a saved map would be available to all devices. Pretty painfull to redraw that map for all devices!" -- a saved map is absolutely visible the same way across all my devices - so you only need to do the positioning once. If your positions aren't saving properly, perhaps you have a config issue (permissions maybe)?

**Comment by ollyg** [comment]
Hi @DokH please see the documentation here: https://github.com/netdisco/netdisco/wiki/Network-Map

I am not sure what you are asking for, as the things you mention are covered in the docs, so I will close this. Please comment if you can describe a specific behaviour or functionality missing. Many thanks!

**Comment by DokH** [comment]
Hmmm, I must be doing something wrong as saving the All Devices map is not consistant across all devices.

I'd like to see that a All Devices map is saved without a single host group selected as the default network, a.k.a. top level map, from which host group maps are shown by just filtering that top level map on the devices whithin the selected host group(s).

Now I'm creating a saved All devices map for each host group in turn.

It also appears that sometimes the savd position of all or some devices on a map are lost and they start bouncing all over the place again.

If the above is supposed to be the default behaviour, then there is something wrong in my setup.
