### ISSUE TITLE
Manual Topology feature requests

### ISSUE THREAD

**Issue by gizu** [netdisco/netdisco#1051]
not errors, but feature request/suggestions 

i was playing with topology, trying to 'connect' all orphaned networks. few thoughts below:

* using manual topology - I cannot create link between device connected via portchannel to pair of cisco nexus 
switches in vpc portchannel. probably there is limitation to one device on one port only. 

* it will be nice to have an admin page containing predicted/proposed connections to manual topology to accept, 
  based on Layer3 analysis (arp, ports in the same network/mask for small prefixes like from /28 to /31, ospf/bgp neighbours).

* it will be helpful to create virtual devices (virtual firewalls - vdoms/vsys/vrouters) configured as subset of interfeaces 
   from main device - to use in topology, for clearer graphs.

**Comment by ollyg** [comment]
moved to wishlist page
