### ISSUE TITLE
FR: RFC1918 report

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#1052]
Hopefully this would be relatively easy to implement - would it be possible to get an IP report for just RFC1918 ranges?

We have a situation where over our campus, we provide private vlans for labs/reserach groups to connect equipment. The majority of these use 192.168 self-assigned IPs. 

Ideally I'd like to keep the ranges seperate for sanity reasons, but it requires a little bit of extra thinking at the moment.

If there was a report pre-configured to say these are the RFC1918 networks that have been spotted -- it would be very useful!

**Comment by ollyg** [comment]
implemented in 59f3ab17
as duplicate private networks report
