### ISSUE TITLE
 Can't connect to TCP port 5000 on :: [Invalid argument]

### ISSUE THREAD

**Issue by DebianGuru** [netdisco/netdisco#1068]
## Expected Behavior
Netdisco should be be reachable on port 5000

## Current Behavior
Web interface is not working.  Log excerpt:
2023/07/14-11:35:59 Starman::Server (type Net::Server::PreFork) starting! pid(53738)
Resolved [*]:5000 to [::]:5000, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to TCP port 5000 on host :: with IPv6
2023/07/14-11:35:59 Can't connect to TCP port 5000 on :: [Invalid argument]
  at line 66 in file /home/netdisco/perl5/lib/perl5/Net/Server/Proto/TCP.pm

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Upgraded my OS to Debian12 (bookworm)
Followed steps on https://metacpan.org/pod/App::Netdisco to upgrade because Netdisco was not working.

## Context
Netdisco is not usable.

## Config info (deployment.yml)
Nothing has changed in this file.  I'm not posting the details as it contains usernames/passwords and SNMP credentials.  There's nothing else in here that has changed to break the system.

**Comment by ollyg** [comment]
Hi @DebianGuru sometimes we see an issue with IPv6 listening. Please can you try setting environment variable IPV=4 and starting the web frontend?

**Comment by DebianGuru** [comment]
You nailed it!  I put "export IPV=4" in /home/netdisco/.bash_profile so it should persist across reboots.
