### ISSUE TITLE
Minor FR: amendment to last seen column in IP inventory

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#1071]
In the IP inventory report, there's a column called "last used"

This contains a datestamp which is relative rather than absolute -- e.g. if it says 00:01:00 this means it was last seen an hour ago -- not that it was last seen at 1 am.

However, this distinction isn't entirely clear at first glance. If the column title was something like "Time since last seen" I think it would be slightly more intuitive. You could also acheive this by suffixing the word 'ago' to the end of every entry in the column.

There is also a slight incongruity in the time formats listed - if the time is less than a day it will list the time as HH:MM:SS but if it's longer then it prefixes the years/months/days in wordsin eg "A months B days HH:MM:SS"

The seconds (SS) value seems to be largely unecesscary as it always seems to be 00.

I think it would be a bit more intuitive if this format was consistent, with "C hours D minutes" and seconds ommitted entirely, so entries would change slightly:

"1 month 30 days 14:24:00" would become "1 month 30 days 14 hours 24 minutes"
"08:09;00" would become "8 hours 9 minutes".

This is very minor, I'm just mentioning it because I spend a lot of time in the IP inventory as it's our most authorative source for ip address management :D

**Comment by ollyg** [comment]
thanks @kingtrw the column presentation is changed in 39121343
Unfortunately I can't change the way it flips presentation at the one-day boundary, as that is baked into PostgreSQL behaviour for the data type.
