### ISSUE TITLE
move ethernetCsmacd+notPresent ports from ignore_deviceports to hide_deviceports

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#1081]

**Comment by ollyg** [comment]
note to self: look into Po1 on .204 to see if there is any strange reporting issue causing this

**Comment by inphobia** [comment]
cludge was added initially for ciscosb devices, don't think a lot of others make use of it.

**Comment by ollyg** [comment]
changed in a0f4bbfb
