### ISSUE TITLE
Can't login after Upgrade 2.064001

### ISSUE THREAD

**Issue by dtuecks** [netdisco/netdisco#1085]
## Expected Behavior

Users can login.

## Current Behavior

Users (local / ldap) can't login. 

## Context
We did an Upgrade from 2.060004 to 2.064001. Since then, logins to netdisco do not work anymore (Local / LDAP). 

Local Accounts (admin):
I've tried to reset the admin password (deleted all admin users an re-ran netdisco-deploy) but that didn't help. 

Remote Accounts:
I can see LDAP Traffic requests an responses in the netdisco-web.log (can't show because of unencrypted traffic). ldapsearch on the shell is working fine.

 Netdisco itself is running fine. Only Logins (GUI / API) are not possible anymore. 

A Dancer DBITrace looks like this:

```
DBI 1.643-ithread default trace level set to 0x100/1 (pid 2563812 pi 556cd8b9e2a0) at DBITrace.pm line 23 via Base.pm line 17
--
<- prepare_cached('SELECT me.username, me.password, me.token, me.token_from, me.creation, me.last_on, me.port_control, me.portctl_role, me.ldap, me.radius, me.tacacs, me.admin, me.fullname, me.note FROM users me WHERE ( me.username ILIKE ? )', HASH(0x556cdef049a0), ...)= ( DBI::st=HASH(0x556cdeeac410) ) [1 items] at DBI.pm line 1972
<- bind_param(1, "admin", ...)= ( 1 ) [1 items] at DBI.pm line 2013
EXECUTE dbdpg_p2563812_1 (
$1: admin
);
 
<- execute= ( 1 ) [1 items] at DBI.pm line 1958
<- fetchrow_array= ( "admin" "{CRYPT}$2a$07$87FxdepCoGIEGUDO44vsN.51pF76adsfsgcAPP4I8qjSyVSr5iMU2C" "025ab2c0f6073732618252bcee4255d" 1691656551 "2023-08-10 10:24:20.670223" "2023-08-10 10:36:31.652271" 1 undef 0 0 0 1 undef undef ) [14 items] row1 at DBI.pm line 2762
<- fetchrow_array= ( ) [0 items] row1 at DBI.pm line 2763
<- finish= ( 1 ) [1 items] at DBI.pm line 2768
<- prepare_cached('INSERT INTO user_log ( details, event, userip, username) VALUES ( ?, ?, ?, ? )', HASH(0x556cdf592078), ...)= ( DBI::st=HASH(0x556cdeeb5b30) ) [1 items] at DBI.pm line 1972
<- bind_param(1, "/netdisco/login", ...)= ( 1 ) [1 items] at DBI.pm line 2013
<- bind_param(2, 'Login Failure (WebUI)', ...)= ( 1 ) [1 items] at DBI.pm line 2013
<- bind_param(3, '::ffff:192.168.12.9', ...)= ( 1 ) [1 items] at DBI.pm line 2013
<- bind_param(4, "admin", ...)= ( 1 ) [1 items] at DBI.pm line 2013
EXECUTE dbdpg_p2563812_2 (
$1: /netdisco/login
$2: Login Failure (WebUI)
$3: ::ffff:192.168.12.9
$4: admin
);
 
<- execute= ( 1 ) [1 items] at DBI.pm line 1958

```

## Your Environment

Software	Version
App::Netdisco	2.64.1
SNMP::Info	3.94
DB Schema	81
PostgreSQL	15.00.3
Perl	5.36.0

OS: Debian 12

## Config info (deployment.yml)
#
# NETDISCO 2 CONFIGURATION FILE
#
# Settings in this file override share/config.yml
# See App::Netdisco::Manual::Configuration for more info.

# ------------------
# ESSENTIAL SETTINGS
# ------------------

database:
  name: 'x'
  user: 'x'
  pass: 'x'
  host: 'x'

tenant_databases:
  - tag: y
    displayname: y
    name: 'y'
    user: 'y'
    pass: 'y'
    host: 'y'

path: '/netdisco'
trust_x_remote_user: true
trust_remote_user: true

# --------------------
# RECOMMENDED SETTINGS
# --------------------
#no_auth: true
ldap:
  servers:
    - '10.10.10.1'
    - '10.10.10.2'
  proxy_user: 'CN=X,OU=Y,DC=Z'
  proxy_pass: 'x'
  base: 'OU=Y,DC=Z'
  user_string: 'sAMAccountName=%USER%'
  opts:
     debug: 3

**Comment by ollyg** [comment]
Hi @dtuecks sorry to hear this. 
Around release 2.62 there was a lot of refactoring of the login code, especially for the settings trust_remote_user, trust_x_remote_user, no_auth.

I can see that you are using these settings. Is that intentional? Usually Netdisco would run behind an AuthN proxy and use these settings and not do local/ldap auth, or else is not behind an AuthN proxy and is doing local/ldap auth.
