### ISSUE TITLE
{Feature Request} Display the ports that are used to interconnect the switches on the Network Map

### ISSUE THREAD

**Issue by hornet007** [netdisco/netdisco#1097]
When the Network Map is drawn, I can toggle whether the "Management IP" and "Link Speed" is drawn on the map.  I would like to be able to toggle "Ports" that will show me the port that is used to interconnect the switches.   Currently, when I move the mouse over the black line, there is a popup that shows the port that is used to interconnect the switches.

When I print out the network map and go to the data centre to troubleshoot networking issues, having the ports displayed will facilitate easier troubleshooting.

![nd2-shot-2](https://github.com/netdisco/netdisco/assets/143001856/67ceedd9-4583-4cad-ab8d-21bfba5a8887)

**Comment by ollyg** [comment]
I realised the reason this is not implemented is that the visual link may be multiple links between devices, if it's an aggregate (port channel, etherchannel). So there are multiple ports at each end.

Still, I'll have a look into the code and see if there's a way to do it.

**Comment by hornet007** [comment]
If there are multiple ports, I would like them all displayed as well.

**Comment by ollyg** [comment]
closed and moved to the wishlist wiki page
