### ISSUE TITLE
Port Report - Ports turned on outside Netdisco

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#11]
From conversation with Brian Wilson :

&gt;I like the idea for that other search, "ports that
dont have an  
&gt;enabled log
&gt;entry but have been enabled"

Yeah, exactly.  It might help people keep up with
situations where the
port has been re-enabled by hand \(or via another
script\) other than
with netdisco.

Reported by: maxslug-placeholder

Original Ticket: [netdisco/nd2-features/11](https://sourceforge.net/p/netdisco/nd2-features/11)

**Comment by ollyg** [comment]
This could very easily be done with a custom report, were someone inclined to work out the SQL :-).
