### ISSUE TITLE
API Search node and see the switch and port it's connected to

### ISSUE THREAD

**Issue by michelbragaguimaraes** [netdisco/netdisco#1102]
Dear Netdisco Administrators,

First and foremost, I express my sincere gratitude for providing us with the incredible Netdisco tool. It has proven to be an invaluable asset in managing our network infrastructure.

I recently had a question regarding the capabilities of the Netdisco API. This may not be a pressing issue but rather a query to understand the platform's capabilities better.

Through the Netdisco API, is it possible to retrieve information about a specific node by querying its IP address? Specifically, I am interested in finding where the node is connected within our network and on which port of the connecting device it is currently attached. This functionality is something I've been able to achieve through the web interface, and I wanted to know if a similar feature exists programmatically.

This capability through the API would be extremely beneficial for our network management processes and greatly enhance our operations' efficiency.

Once again, I want to express my appreciation for the amazing work you and the Netdisco team have put into this tool. It has made our network management tasks much more manageable and streamlined.

Thank you for your time, and I look forward to hearing from you whenever you get a chance.

Best regards,

**Comment by ollyg** [comment]
Hi @michelbragaguimaraes 
My understanding is that the [/api/v1/search/node](https://netdisco2-demo.herokuapp.com/swagger-ui/?url=/swagger.json#/Search/get_api_v1_search_node) endpoint can take the IP of the node and returns in the response a reference to the port. However the response data structure isn't clear in the documentation. So I will test and confirm later.
regards
Oliver

**Comment by ollyg** [comment]
Hi again @michelbragaguimaraes 
I have run a test on our demo site at netdisco.org and the info is available but you need to do two API calls, not one.

The first call to `/api/v1/search/node` is with the IP and that will get you the MAC address of the node using the IP.
```
https://netdisco2-demo.herokuapp.com/api/v1/search/node?q=172.16.1.101
{
  "macs": [
    {
      "active": 1,
      "time_first": "2018-03-24 11:50:38.03315",
      "time_first_stamp": "2018-03-24 11:50",
      "time_last_stamp": "2018-03-24 11:50",
      "time_last": "2018-03-24 11:50:39.580287",
      "mac": "00:03:00:11:11:01",
      "oui": {
        "abbrev": "BarracudaNetworks",
        "company": "Barracuda Networks, Inc."
      },
      "ip": "172.16.1.101",
      "dns": "server01"
    }
  ]
}
```

The second call to the same endpoint `/api/v1/search/node` is with the MAC address and that will get you the switch and port (under the "sightings" key in the JSON dictionary returned.
```
https://netdisco2-demo.herokuapp.com/api/v1/search/node?q=00%3A03%3A00%3A11%3A11%3A01
{
  "sightings": [
    {
      "switch": "192.168.0.12",
      "vlan": "1",
      "active": 1,
      "device": {
        "dns": "leaf02",
        "name": "leaf02"
      },
      "time_last_stamp": "2018-03-24 12:20",
      "port": "server1",
      "time_first_stamp": "2018-03-24 12:20",
      "oui": "00:03:00",
      "time_first": "2018-03-24 12:20:08.375207",
      "time_last": "2018-03-24 12:20:08.61725",
      "mac": "00:03:00:11:11:01",
      "time_recent": "2018-03-24 12:20:08.61725"
    }
  ],
  "wireless": [],
  "netbios": [],
  "ports": [],
  "ips": [
    {
      "time_last_stamp": "2018-03-24 11:50",
      "time_first_stamp": "2018-03-24 11:50",
      "time_first": "2018-03-24 11:50:38.03315",
      "active": 1,
      "dns": "server01",
      "oui": {
        "company": "Barracuda Networks, Inc.",
        "abbrev": "BarracudaNetworks"
      },
      "ip": "172.16.1.101",
      "mac": "00:03:00:11:11:01",
      "time_last": "2018-03-24 11:50:39.580287"
    },
    {
      "time_last": "2018-03-24 11:50:39.580287",
      "dns": null,
      "ip": "fe80::203:ff:fe11:1101",
      "oui": {
        "abbrev": "BarracudaNetworks",
        "company": "Barracuda Networks, Inc."
      },
      "mac": "00:03:00:11:11:01",
      "time_first": "2018-03-24 11:50:38.117519",
      "active": 1,
      "time_first_stamp": "2018-03-24 11:50",
      "time_last_stamp": "2018-03-24 11:50"
    }
  ]
}
```

Hope that helps! and thank you for the very kind words about how useful Netdisco is to you 😊 

regards
Oliver

**Comment by michelbragaguimaraes** [comment]
Thank you for the quick response.

I was able to get the results I wanted.

Thank you, and keep up with this fantastic software. I've been using it for the past eight years and implement it everywhere I go.
