### ISSUE TITLE
Install issue on Rocky Linux 9.0

### ISSUE THREAD

**Issue by JensVeha** [netdisco/netdisco#1105]
## Expected Behavior
curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco should work

## Current Behavior
The installation fails because of a prerequired package fails:

--> Working on Cpanel::JSON::XS
Fetching http://www.cpan.org/authors/id/R/RU/RURBAN/Cpanel-JSON-XS-4.37.tar.gz ... OK
Read error on tarfile (missing data) 'Cpanel-JSON-XS-4.37/README' at offset unknown at - line 119.
Configuring Cpanel-JSON-XS-4.37 ... N/A
! The distribution doesn't have a proper Makefile.PL/Build.PL See /home/netdisco/.cpanm/work/1695758833.82758/build.log for details.

**Comment by ollyg** [comment]
Hi @JensVeha 
I regret that we're not able to provide support on third party dependencies. It looks like you can open a ticket for Cpanel::JSON::XS here: https://github.com/rurban/Cpanel-JSON-XS/issues
(furthermore this is not a direct dependency of Netdisco ... I'm not sure what depends on this. also I was not able to reproduce on my macOS system, sorry)
regards
Oliver.

**Comment by JensVeha** [comment]
Hi Oliver,

thanks for the fast reply. I'll try and contact them. The package is not a
direct dependency but a dependency of a dependency. (Plack IIRC)


Kind regards

Jens Van Heuverswijn
***@***.***



Op wo 27 sep 2023 om 13:02 schreef Oliver Gorwits ***@***.***

**Comment by JensVeha** [comment]
For those that would find this issue through google and encounter the same problem.

I solved the problem by installing the dependency through another way, if you're following the installguide do the following before you run the install command enter the following commands:

`cpan Cpanel::JSON::XS`

If this is a fresh linux isntall, he'll ask if you want to configure as much automatically [Press enter to select Yes] and then he'll ask what approach you want [Press enter to select the default local::lib].

Once the command has run and there are no errors you can run the install command `curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco` without issue.
