### ISSUE TITLE
API method for device neighbors

### ISSUE THREAD

**Issue by semirke** [netdisco/netdisco#1112]
Hi,
 is it possible to get the neighbour list (ajax/data/device/netmap?q=leaf01&dynamicsize=on&mapshow=neighbors&vlan=&colorby=speed&tab=netmap ) like an api call?

Thanks!
Semirke

**Comment by ollyg** [comment]
thanks for the suggestion @semirke !
implemented in b5c0cd58
at endpoint '/api/v1/object/device/{ip}/neighbors'

**Comment by semirke** [comment]
Wow, thanks :)
