### ISSUE TITLE
Clearing Job Queue via Web UI also clears the device_skip table

### ISSUE THREAD

**Issue by janthon1** [netdisco/netdisco#1129]
Release 2.70.1

After clearing the job queue from WebUI (clicking the trashcan in Admin > Job Queue) the device_skip table is also cleared.  The system behaves as though the skiplist has not been populated and scheduled jobs begin to queue with a status of "skipped: have not yet primed skiplist"

## Expected Behavior

device_skip table should not be cleared during housekeeping of the Job Queue.

## Current Behavior
Both the device_skip and admin tables are cleared.

## Possible Solution
Only delete entries from the admin table when clearing the job queue, and leave the device_skip table unchanged.  Or, re-prime the skpilist when clearing the job queue.  Also, adding an option to re-create the skip list from the Admin menu (like Discover All) could be helpful.

## Steps to Reproduce
After a fresh restart of the backend, navigate to Admin > Job Queue.  Select clear Job Queue.

Job queue is emptied.

Select Discover All from the Admin menu.  This job will enter a skipped state due to device_skip not being completed.

## Your Environment
The current main/latest release of 2.70.1.  

REPOSITORY                  TAG                 IMAGE ID       CREATED         SIZE
netdisco/netdisco           latest-backend      bf5948191634   5 days ago      639MB
netdisco/netdisco           latest-web          479bbd1020f7   5 days ago      129MB
netdisco/netdisco           latest-postgresql   03fe1d20c479   5 days ago      199MB

cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"

**Comment by ollyg** [comment]
Many thanks @janthon1 for the bug report!
fixed in 8ea19f32
