### ISSUE TITLE
Netdisco Distributed Monitoring

### ISSUE THREAD

**Issue by rohanrajnv** [netdisco/netdisco#1135]
## Expected Behavior
The Backend should be displayed as 2

## Current Behavior
Only One Backend.

## Your Environment:
App::Netdisco 	2.70.3
SNMP::Info 	3.95
DB Schema 	85
PostgreSQL 	14.00.10
Perl 	5.34.0

I have installed the Netdisco on 2 Server and Wanted to distribute the Load to 2 Servers
I have the Following configuration to Servers.
Server 1:
# backend 1:
discover_only: [ '192.168.6.0/24' ]
macsuck_only: [ '192.168.6.0/24' ]
arpnip_only: [ '192.168.6.0/24' ]

Server 2:
# backend 2:
discover_only: [ '192.168.7.0/24' ]
macsuck_only: [ '192.168.7.0/24' ]
arpnip_only: [ '192.168.7.0/24' ]

But in the Job Queue I can only see 1 backed.

I have created the 1 Server and cloned it but hostname is same.

Is there any configuration mistake I have done?

**Comment by rc9000** [comment]
Hi! You should definitely change the hostname, as it is used to identify the backends. Afterwards restart both netdisco-backend processes, clear the admin queue (thrash icon in /admin/jobqueue) and start some new jobs to see if it works better.
