### ISSUE TITLE
General Setup Question

### ISSUE THREAD

**Issue by rohanrajnv** [netdisco/netdisco#1136]
Question 1:
What is the difference between an orphan device and an orphan network-sized device?

Question 2:
I have 3 backends created, and I would like to add the 4th backend to perform only the device discovery of the complete network.
The reason for this question is that we have a large network with sensors and access points.
We are unable to list all the networks where the devices are connected, so we planned to build one automartic scanner where all the nodes are added to the database.
Is this a good idea?

**Comment by ollyg** [comment]
Hi @rohanrajnv 
An orphan device is a device where Netdisco cannot see any link to other devices. For an orphan network it is like an island of devices not seen to connect to any others.

For your second question, yes I think this will work fine but I'm not sure I understand fully! :-)

You can set `schedule: null` in your config which disables the automatic scheduling of discover/arpnip/etc. You can use cron to run a discoverall at the command line if you want (with --enqueue option recommended here).
