### ISSUE TITLE
deleting from /admin/duplicatedevices fails

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#1140]
## Expected Behavior

being able to delete from admin - duplicate devices. noticed it stopped working a few months ago.

## Current Behavior

when using the delete button on either of the entries:
![image](https://github.com/netdisco/netdisco/assets/39005454/2e68bd1a-97ce-4a0f-b2bd-50ff65b75e01)

you get
![image](https://github.com/netdisco/netdisco/assets/39005454/3ddda75a-6c6d-4698-b08f-b693eea7b415)

nothing shows in backend or web log.
if you click through on the device it is possible to delete it from the device's page.

## Possible Solution

has always worked for me up until a few months ago, don't have a specific release when it stopped regretfully.

## Steps to Reproduce (for bugs)

1. have duplicate devices
2. go to admin - duplicate devices
3. try the delete button, get an error
4. can be deleted from device itself

getting duplicates has become quite rare in the latest releases, but these steps seem to trigger it (ips given as example) :
* start with a single router (x.x.x.1/24 lan side) on a site connected to a switch. run cdp or lldp on both.
* use x.x.x.1/24 in initial netdisco-do discover
* install backup router on site (x.x.x.254/24)
* renumber primary router from x.x.x.1/24 to x.x.x.253/24
* add x.x.x.1/24 again but as vrrp or hsrp address.

neighbor info on the switch will then give you something like this:
![image](https://github.com/netdisco/netdisco/assets/39005454/12b14e1f-5392-464d-8dfd-c619c9cced4e)

another option is to have a router with 2 vrf's, lldp or cdp enabled, connected to 2 different switches which are not interconnected. which makes creative configs like

![image](https://github.com/netdisco/netdisco/assets/39005454/fb6a2988-ffa2-464a-a6dd-025282df2476)

(gi8 & it's subinterfaces are to the connection to the provider core, gi1&2 are each connected to different switches)

extra info: we see this almost only on the managed mpls part of our network, which is quite complicated. some sites get extra routers for redundancy, some sites consolidate multiple routers into 1 router using vrfs. our snmp read access does not allow us to query the management vrf from the provider (and we also exclude their ip ranges from discovery).

## Your Environment

* Netdisco version used: 2.071001 
* SNMP::Info version used: 

## Config info (deployment.yml)

perhaps the relevant part is that we disabled serial protection, we have devices replaced on an almost daily basis so this keeps our inventory easier up to date.
```
snmp_field_protection:
  device:
    serial: ['!group:__ANY__']
```

## Device information

https://github.com/netdisco/netdisco/wiki/Snapshot#share-a-snapshot

**Comment by ollyg** [comment]
thanks for the report! managed to fix a couple other things while I was looking.
fix implemented in 8c4cf138
