### ISSUE TITLE
Large backlog of queued jobs - Is this normal? 

### ISSUE THREAD

**Issue by taylor5042** [netdisco/netdisco#1143]
I'm in the process of rebuilding my netdisco server on a new VM. 
Running RHEL 9 
Software 	Version
[App::Netdisco]  2.71.1
[SNMP::Info]      3.95
[DB Schema] 	   85
[PostgreSQL]     15.00.3
[Perl]                  5.32.1

Both my old server and new server are now running 2.71.1 and both show thousands of backlog jobs once the running jobs gets to 0. 
Is this normal or is there something preventing these jobs from running and clearing out of the backlog? 

  Backends: 1 / Workers: 32 / Running: 0 / Backlog: 3,853 / Done: 50,269 / Errored: 336 / Stale: 0 / Total: 55,563 
 
I tried changing the min_runtime: to 2 based on some searching in the documentation/issues but that doesn't seem to make a difference. 

If I delete all the jobs and then run a discover all and let that process all the running jobs then the numbers start out on the smaller end. 
  Backends: 1 / Workers: 32 / Running: 0 / Backlog: 72 / Done: 754 / Errored: 5 / Stale: 0 / Total: 831

**Comment by ollyg** [comment]
Hi @taylor5042 I would not worry about this. Sometimes too much information is not helpful ;-).
Is Netdisco doing what you expect and is everything discovered? If the answer is yes, then it's fine.
There are many many reasons a job can be queued and not ever run (this is what backlog means).

**Comment by taylor5042** [comment]
Yeah, I kinda wondered the same thing. 
That is a nice feature for helping to see the job queue progressing visually. 
Thanks for the reassurance.
