### ISSUE TITLE
Orphan Device API

### ISSUE THREAD

**Issue by rohanrajnv** [netdisco/netdisco#1144]
Hi Everyone,

Is there anyway we can get the orphan device using the API?

**Comment by rc9000** [comment]
Hi! This doesn't seem to be in the API currently. But for a quick solution you can take the SQL from [here](https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/DB/Result/Virtual/OrphanedDevices.pm), put in a [custom report](https://github.com/netdisco/netdisco/wiki/Configuration#reports) and [fetch that via the API](https://github.com/netdisco/netdisco/wiki/API#run-a-report).

**Comment by rohanrajnv** [comment]
Thanks for your response. Do we have to update all the deployment.yaml for the custom report?  i have 6 backend

**Comment by ollyg** [comment]
Hi no it’s just in the web front end config only.

**Comment by rohanrajnv** [comment]
Thanks for your response. Yes, but in my case, all the backend is hosting the web, so I updated all the deployment.yml.
I can see that the orphan list shows an IP that does not even have a device. Like the IP 192.168.55.10 is not a used ip in my network, I am still able to see it in the orphan list. i have changed the query to include devices with ports but i dont think this is the correct way. any suggessions please?

Is there any way to run the discovery, arpnip macsuck, snapshot, and nbtstat from the API?

**Comment by rohanrajnv** [comment]
Some devices are still showing as orphans even when they have a connected port.
Like Device 192.168.35.11, it is on switch port 1 of switch 10 as per the Neighbors tab and still in the orphan list.
