### ISSUE TITLE
Netdisco update issue Updating OUI... Undefined subroutine 

### ISSUE THREAD

**Issue by jouluz** [netdisco/netdisco#1151]
## Expected Behavior
Update should go flawlesly

## Current Behavior

Update is interrupted by the following

Download and update vendor MAC prefixes (OUI data)? [y/N]: y

Updating OUI... Undefined subroutine &main::csv called at /usr/local/netdisco/perl5/bin/ieee-oui-import line 60.

## Steps to Reproduce (for bugs)
Download earlier version of netdisco and run update process

~/bin/localenv cpanm --notest App::Netdisco

ln -sf ~/perl5/bin/{localenv,netdisco-*} ~/bin/
 
~/bin/netdisco-deploy

**Comment by ollyg** [comment]
Hi @jouluz sorry about this bug.

If you run the following command then run the deploy again, it will work:

~netdisco/bin/localenv cpanm Text::CSV

regards
Oliver.

**Comment by ollyg** [comment]
this will be fixed in the next release of Netdisco
