### ISSUE TITLE
Dependency failed during install

### ISSUE THREAD

**Issue by eric859** [netdisco/netdisco#1152]
Trying to install Netdisco on Ubuntu 22.0.4.  When running the install command, everything gets installed except for some type of Archiver.  This is the error I get at the end:  ! Installing the dependencies failed: Module 'Archive::Extract' is not installed

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

https://github.com/netdisco/netdisco/wiki/Snapshot#share-a-snapshot

**Comment by ollyg** [comment]
I cannot reproduce this, as the following works fine for me:
`cpanm --verbose --reinstall Archive::Extract`
