### ISSUE TITLE
Show device info on MAC addresses

### ISSUE THREAD

**Issue by FabioPedretti** [netdisco/netdisco#1154]
It would be nice to be able to show device info for MAC addresses (for example inside the Node tab).

The info could be shown by Netdisco itself, using the MAC address database (as done by nmap, the DB file is at https://github.com/nmap/nmap/blob/master/nmap-mac-prefixes).
Otherwise (privacy concerns?) the MAC could be a link to a site like https://www.macvendorlookup.com/ using its API.

Thanks.

**Comment by ollyg** [comment]
Hi @FabioPedretti 

Have you ticked the box "Vendor" on the right hand side panel of the Node tab? Then you can search again and it will show the Vendor (this information is all loaded into Netdisco already).

If this works, I can show you how to make this a default for all searches if you wish.

If this doesn't work, please let me know! Make sure you have loaded "OUI" information as part of netdisco-deploy step.

regards
Oliver

**Comment by ollyg** [comment]
It's not a default just because for most people it's not that useful/interesting information :-) (a lot of network interface components are not the same as the device vendor any more, so it's just listing a meaningless chip company)

I'm glad it's working for you :-) and thanks for the feedback!
