### ISSUE TITLE
[ Feature Request ] - Allow access to the map from homepage

### ISSUE THREAD

**Issue by Rodjeur70** [netdisco/netdisco#1155]
## Expected Behavior
Allow access to the map from homepage

## Current Behavior
Need to go to a device page and then click on "Neighbors" button

## Possible Solution
Using a configuration parameter defining a "root map" device, propose a map global link from homepage

## Your Environment
* Netdisco version used: 2.70.3
* SNMP::Info version used: 3.95

**Comment by ollyg** [comment]
Thanks for the suggestion @Rodjeur70 

This is not trivial to implement because the map always requires a "central" node to start from (even when displaying all nodes). So it will need a bit of thought.

You can of course create a bookmark to something like:
```
.../device?tab=netmap&q=centraldevice.example.com&mapshow=all&depth=1&vlan=&colorby=speed&dynamicsize=on
```

**Comment by Rodjeur70** [comment]
Hi @ollyg 

Yes, I've noticed that maps are relevant to a specific node, that's why I've proposed for this feature to define a default root node via configuration file. Administrator can set it by example with his central core router or firewall if any.

Regards.

**Comment by ollyg** [comment]
clsoing and moving to wishlist
