### ISSUE TITLE
[Feature Request] Custom Fields - Nodes

### ISSUE THREAD

**Issue by kairandles** [netdisco/netdisco#1159]
Heya, would it be possible to add a custom field for a node. We would like to be able to name the IP / node rather than port so if this is moved the name would move with it. This is for devices that don't report a NetBIOS name (i.e non windows machines)

**Comment by kairandles** [comment]
Mac Address would make a lot more sense! - Most of our bits are static but Mac would be the happy medium for everyone I think!

**Comment by kairandles** [comment]
When this is surfaced can we show this data on the device view too? As well as when you click into the node / search for it :)

**Comment by ollyg** [comment]
Hi, yes, imagine you mean the Device Ports tab, when you tick "Connected Nodes" as an extra node property (like the NetBIOS is displayed) ... sure 👍 
I'll need to have a think about how and where the field is edited so as not to make it too cumbersome, plus the time to develop, so can't promise any timeline yet sorry.

**Comment by ollyg** [comment]
closing and moving to wishlist
