### ISSUE TITLE
Upgrade to latest not possible

### ISSUE THREAD

**Issue by Rodjeur70** [netdisco/netdisco#1160]
## Expected Behavior
Upgrade netdisco app to latest 2.072002 via standard procedure

![image](https://github.com/netdisco/netdisco/assets/109161601/9f0f7ac1-967c-4f73-9f35-100753a451b7)

## Current Behavior
Previous version seen as up to date

![image](https://github.com/netdisco/netdisco/assets/109161601/83ba0230-2b70-4066-a489-37444314f6e3)

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
~/bin/localenv cpanm --notest App::Netdisco

## Context
Debian 11 installation

## Your Environment
* Netdisco version used: 2.072001
* SNMP::Info version used: 3.95

## Config info (deployment.yml)
Not relevant

## Device information
Not relevant

**Comment by ollyg** [comment]
Hi @Rodjeur70 yes another user reported this, I'm not sure why the metacpan mirrors or their metadata are not updated. Normally it's quick within an hour or two of release.

As a workaround you can replace "App::Netdisco" with the file URL in the update command: https://cpan.metacpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.072002.tar.gz

**Comment by inphobia** [comment]
also had this today.
downloaded https://github.com/netdisco/netdisco/archive/refs/tags/2.072002.tar.gz and ran

localenv bash
cpanm ./2.072002.tar.gz


metacpan.org has been giving me 503's all day, could be on their end , cpants is also acting up
