### ISSUE TITLE
'Can't call method "username" on an undefined value' when trying to portcontrol from commandline

### ISSUE THREAD

**Issue by NMCPaul** [netdisco/netdisco#1167]
## Expected Behavior
The port is shutdown

## Current Behavior
```
netdisco@netdisco:~/bin$ ./netdisco-do portcontrol -d 10.0.0.25 -p GigabitEthernet1/0/37 -e down
[139812] 2024-02-13 14:33:51  info App::Netdisco version 2.072001 loaded.
[139812] 2024-02-13 14:33:51  info portcontrol: [10.0.0.25] started at Tue Feb 13 14:33:51 2024
[139812] 2024-02-13 14:33:51  info portcontrol: finished at Tue Feb 13 14:33:51 2024
[139812] 2024-02-13 14:33:51  info portcontrol: status error: Can't call method "username" on an undefined value at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Port.pm line 55.
```

## Possible Solution
Unsure.

## Steps to Reproduce (for bugs)
1. See above

## Context
Trying to script the deactivation of many ports at once.  Being able to deactivate one is the first step, really.

## Your Environment
* Netdisco version used: `2.072001`
* SNMP::Info version used: `NET-SNMP version: 5.9.1`

**Comment by ollyg** [comment]
Thanks @NMCPaul I will take a look!

**Comment by ollyg** [comment]
Hi again, I have spotted the bug but in doing so I uncovered another bug. Work in progress and fix hopefully released today.

**Comment by ollyg** [comment]
fixed in bf66e0b5

**Comment by ollyg** [comment]
Hi @NMCPaul this is fixed in the new release of Netdisco. Do let us know if you have any issues.

**Comment by ollyg** [comment]
Hi @NMCPaul have you checked the port is eligible for status change per the config defaults? I accept the error message doesn't give a hint. That error indicates one of the portctl* settings might need adding: https://github.com/netdisco/netdisco/wiki/Configuration#portctl_by_role

**Comment by NMCPaul** [comment]
The only items in my `deployment.yaml` file are:
```
portctl_nowaps: false
portctl_uplinks: true
```
I'll look at that link that you sent since it seems that I may need to add some elements, but just to throw another detail out there - it works just fine through the web interface.  Is that behavior as intended?

And as an aside - I changed a couple non-trunk ports last night and just today looked in the switch config:
```
 switchport access vlan 800
 switchport trunk native vlan 800
```
Is it supposed to change the trunk native VLAN as well?  I thought it would just do the access VLAN.

Either way, thanks for the assistance.

**Comment by NMCPaul** [comment]
That did the trick.  Created a dummy "netdisco" user in the webUI and now things are working.
