### ISSUE TITLE
control characters in netdisco-backend.log

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#1168]
## Expected Behavior

control characters should be stripped out of the log. this string seems to be propagated from somewhere in the dbix stack as far as i can tell. 

## Current Behavior

```
[1905] 2024-01-27 22:07:47 error bless( {'msg' => 'DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect(\'dbname=netdisco;host=1.1.1.1\',\'netdisco\',...) failed: connection to server at "1.1.1.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections? at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 265
'}, 'DBIx::Class::Exception' )
        (in cleanup) à<93>+KðU^@^@anup)  at /home/netdisco/perl5/lib/perl5/DBIx/Class/Exception.pm line 77 during global destruction.
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
error running job: DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco;host=1.1.1.1','netdisco',...) failed: connection to server at "1.1.1.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections? at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Device.pm line 65
```

note the: ` (in cleanup) à<93>+KðU^@^@anup)`

## Steps to Reproduce (for bugs)

1. run netdisco and database on different hosts, connect using tcp
2. reboot machine which runs database with netdisco-backend still running.
3. 
4. 

## Your Environment

* Netdisco version used: 2.072002
dbix:class 0.082843

## Device information

https://github.com/netdisco/netdisco/wiki/Snapshot#share-a-snapshot

**Comment by inphobia** [comment]
at first glance it seems to be trying to print "cleanup" twice, but the second one gets corrupted somehow.

also found them in netdisco-web.log

```
2024/01/28-23:35:21 Server closing!
        (in cleanup) 300UtY`U^@^@anup)  at /home/netdisco/perl5/lib/perl5/DBIx/Class/Exception.pm line 77 during global destruction.
        (in cleanup) `343346Z`U^@^@anup)  at /home/netdisco/perl5/lib/perl5/DBIx/Class/Exception.pm line 77 during global destruction.
        (in cleanup) P337)[`U^@^@anup)  at /home/netdisco/perl5/lib/perl5/DBIx/Class/Exception.pm line 77 during global destruction.
        (in cleanup) Ю305Z`U^@^@anup)  at /home/netdisco/perl5/lib/perl5/DBIx/Class/Exception.pm line 77 during global destruction.
        (in cleanup) ^PS327Z`U^@^@anup)  at /home/netdisco/perl5/lib/perl5/DBIx/Class/Exception.pm line 77 during global destruction.
```


netdisco get's started with the following `locale` environment should that be relevant:


```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by ollyg** [comment]
will close as I can't debug inside DBIx:Class (which is no longer maintained anyway afaict!)

**Comment by inphobia** [comment]
you have a way better understanding in perlguts as me, so this is an open question:

however...
since these show up in netdisco-backend.log there should have been a redirect set up the stderr and/or stdout somewhere. if so, couldn't control characters be filtered there?

it's hard to make a good case for this since:
 * the error is not produced by netdisco, merely redirected
 * dbix is where it should be fixed
 * code for writing to the terminal is either
   * popular enough to disable them by default
   * old enough to handle/ignore or put them to good use

i have only 1 counter argument:
 * netdisco-backend.log has control characters in it

i'll not bore you as on the why controlchars in files are a bad idea, but it's preferably they aren't there.

i'm fine with leaving this closed, as well as this should be fixed in dbix. but netdisco is the reason the file exists, and there are control charaters in it.
