### ISSUE TITLE
have more logging status codes 

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#1169]
## Expected Behavior

map severity of problem on status code.

## Current Behavior

when netdisco returns a status it might be defaulting to error to quickly.

## Possible Solution

define flowchart a bit more strict + add a few more levels, perhaps based on syslog:
 * error: fundamental issue that needs to be manually resolved
   * `return Status->error('missing cmd parameter to exec Hook')`
 * warning (new): errors from the perl interpreter, startup messages;
   * `Use of uninitialized value $proto in numeric eq (==) at /home/netdisco/perl5/lib/perl5/SNMP/Info/LLDP.pm line 461.`
   * `[20421] 2024-02-14 13:23:55  warn App::Netdisco 2.072002 web`
 * notification (new): transient in nature
   * `[17471] 2024-02-16 18:36:42 error  [10.40.254.33] interfaces - Error! Failed to get uptime from device!`
 * info: unchanged
 * debug: unchanged

we could be bound to whatever Dancer::Logger::Capture provides as logging levels. moving to something like https://metacpan.org/pod/Log::Report (comes with dancer hooks) might be overkill (see context for _issue_ i'm trying to solve)

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Context

don't have log level defined so using the default `log: 'warning'` from config.yml

the messages i'm most interested in seem to be getting drowned out by repeated items, for example:

```
wc -l logs/netdisco-backend.log.x
34272 logs/netdisco-backend.log.x

grep -i uptime logs/netdisco-backend.log.x | wc -l
4740

grep -i lldp logs/netdisco-backend.log.x | wc -l
29232
```

`uptime` and `lldp` are from these lines:
```
Use of uninitialized value $proto in numeric eq (==) at /home/netdisco/perl5/lib/perl5/SNMP/Info/LLDP.pm line 461.
[18069] 2024-01-13 22:38:16 error  [10.93.13.1] interfaces - Error! Failed to get uptime from device!
```

since those are 98% of the logfile it's easy to overlook thinkgs as
`[30544] 2024-01-16 23:14:06 error  [1.1.1.1] ssh connection error [unable to establish master SSH connection: master process exited unexpectedly]`

or the dbix errors from netdisco/netdisco#1168

`grep -v` can be of assistance ofcourse, if it wouldn't choke on the control characters mentioned in above issue.

## Your Environment

* Netdisco version used: 2.072002
* SNMP::Info version used:

**Comment by ollyg** [comment]
closing and moving to wishlist
