### ISSUE TITLE
Issue with displaying thousands of subnets 0.0.0.0/0

### ISSUE THREAD

**Issue by alcatron** [netdisco/netdisco#1173]
I have a rather large network, and doing Reports > IP > Subnet Utilisation in the newer version forces to display the first page all subnets with [0.0.0.0/0](http://0.0.0.0/0)
Because its so large, the page cant actually display all the subnets as there are thousands and thousands, so it never ends up displaying them and comes up as
“Search failed! Please contact your site administrator (server error)”.
 
If I look up manually smaller subnets this is fine, its just the huge networks it cant seem to handle to display them, is there a fix for this or work around?

**Comment by ollyg** [comment]
fixed in 37796ecb (reverted #830)
