### ISSUE TITLE
proper sorting of numbers / IP

### ISSUE THREAD

**Issue by FabioPedretti** [netdisco/netdisco#1175]
Hi, and Thanks for developing netdisco! ️🙂

In Reports -> IP -> Subnet Uilization if I sort by size, the sorting is done by alphabet and not numeric (in the image 16 should be the first, followed by the 256, then 1.024 and at last the 1.048.576):
![nd-size](https://github.com/netdisco/netdisco/assets/3390837/b2520a4c-24eb-404e-9f22-55dcc04e42b8)

The same issue happens when sorting by IP (e.g. it shows 10.1.0.0 followed by 10.10.0.0 and then 10.2.0.0, while I would expect it should be 10.1.0.0 followed by 10.2.0.0 and then 10.10.0.0).

Thanks.

**Comment by ollyg** [comment]
Hi @FabioPedretti 
These issues are fixed in the next release, thanks for the bug report!

**Comment by inphobia** [comment]
seems to 2 commits:
https://github.com/netdisco/netdisco/commit/c1a052637c421bbeecdb153f206915ef6f531eef
https://github.com/netdisco/netdisco/commit/b0773b2d5489493444e500e79ddd8c509a18a296
