### ISSUE TITLE
discover prefers file over ip for -d option

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#1176]
## Expected Behavior

trying to import snapshot via netdisco-do as detailed in:
https://github.com/netdisco/netdisco/wiki/Snapshot#develop-with-a-snapshot

## Current Behavior

if you are unlucky and run discover when in the ~/logs/snapshots directory, where you placed the snapshot file to be imported, the `-d` option gets confused if you want it to use the file or if it should connect to an ip.µ

most likely added in:
https://github.com/netdisco/netdisco/commit/7ba080c0dc66fb7d0a5a2c155adeaf3ced06ba11

## Possible Solution

* don't use -d parameter for files
* refuse to load files from ~/logs/snapshots
* make snapshot file start with some kind of header (netdisco & net-snmp versions come to mind) and don't load discover files which start with this header
* use different file naming for snapshot files (perhaps as simple as prefixing the file with _)

none of these are very elegant but should get the job done. i personally like the idea of adding some kind of header to snapshot files.

## Steps to Reproduce (for bugs)

1. create snmp snapshot either via netdisco-do or webinterface
2. copy file to ~/logs/snapshots and name it something like 10.1.1.2 (as requested in the wiki)
3. run `netdisco-do discover -d 10.1.1.2 -DI` in ~/logs/snapshots
```
[22287] 2024-02-26 15:12:54  info App::Netdisco version 2.072003 loaded.
[22287] 2024-02-26 15:12:54 error unable to understand as host, IP, or prefix: BQoZAAAACIwFAgAAACJfTExEUF9NSUJfX2xsZHBTdGF0c1JlbVRhYmxlc0Ryb3BzBQIAAAAsX0RP
```

## Your Environment

* Netdisco version used: 2.072003
* SNMP::Info version used: 

## Device information

https://github.com/netdisco/netdisco/wiki/Snapshot#share-a-snapshot

**Comment by ollyg** [comment]
Hi @inphobia this is going to be a wontfix, I'm afraid, as I think the corner case of doing this is not balanced with the code required. However I have added a debug message in 7d7c1ad2 to inform user that the file is being read, which they will see if enabling debug after encountering the issue, hopefully saving time.
