### ISSUE TITLE
feature req: export data from snmp snapshot for use with snmp::info regression testing

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#1178]
writing test for snmp::info is not really popular, and adding in huge mib mockups by hand isn't helping. it eats up time and can be errorprone in the manual steps.

kudos to whoever wrote the mib mockup for https://github.com/netdisco/snmp-info/blob/master/xt/lib/Test/SNMP/Info/Layer3/Juniper.pm

since netdisco now has this fancy mib snapshot i was wondering if this could be extended to export it's data, bonus points if it can be limited to certain leafs and format it so it can be pasted in an snmp::info test directly.

could also open up way the start an archive of exports from different models and/or os versions that use the same class. like a stacked cisco 3750x on ios 12 and an 6504-e on ios 15. being able to check for breakage on older os versions after code changes could come cheaply then.

i haven't looked at how it interacts with netdisco-mibs in detail, perhaps using it to test mib updates could also be achieved?

**Comment by ollyg** [comment]
implemented in bd60a7f9
