### ISSUE TITLE
API - Is there a way to search for a MAC address?

### ISSUE THREAD

**Issue by lanhampr** [netdisco/netdisco#1179]
## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

https://github.com/netdisco/netdisco/wiki/Snapshot#share-a-snapshot

**Comment by ollyg** [comment]
Hi @lanhampr 
Yes, it's the Node Search endpoint as documented here in the demo site:
https://netdisco2-demo.herokuapp.com/swagger-ui/?url=/swagger.json#/Search/get_api_v1_search_node
Hope that helps!
oliver.

**Comment by lanhampr** [comment]
I can search MAC on web interface and get results, but when using same MAC I get 0 results via API.  Search device seem to work fine.
