### ISSUE TITLE
Slow discovery of large networks

### ISSUE THREAD

**Issue by hac3ru** [netdisco/netdisco#1183]
Hello,

I just started using NetDisco but there's a huge issue (at least on my side) with it: It's so slow in discovering devices. The setup:
* No custom config files, I just ran the `docker compose up -d` command on the docker-compose.yml file.
* Added a /16 network
* The VM has 16 available cores, that are all at 100%
* In the last 3 hours, this is how the Job queue status looks like: `Backends: 4 / Workers: 128 / Running: 64 / Backlog: 65,522 / Done: 576 / Errored: 50 / Stale: 0 / Total: 66,270`

## Your Environment
* netdisco container versions: 
  * netdisco-postgresql: latest-web
  * netdisco-backend: latest-backend
  * netdisco-web: latest-postgresql
* docker engine version: Docker version 24.0.7, build afdd53b
* docker-compose version: Docker Compose version v2.2.3
* host operating system: Ubuntu 20.04.6 LTS

Am I doing something wrong, do I need to configure anything before discovering large networks?

Thank you!

**Comment by rc9000** [comment]
Moved this to the main repo since it doesn't seem docker-specific. Acutally it think we can close it since #1170 is there now? Let me know otherwise.
