### ISSUE TITLE
error in ping sweep from web submission

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#1189]
```
Protocol for ping must be "icmp", "udp", "tcp", "syn", "stream", or "external" at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/PingSweep.pm line 29
```

**Comment by dev-osuri** [comment]
solved with version 2.074001

**Comment by ncansado** [comment]
Hi, 
Ive been using this new feature and after installing Net::Ping, is working as expected with expection of leaving  thousands defuncts process behind whilist pinging a /16 network ....

**Comment by ollyg** [comment]
Hi @ncansado unfortunately not much we can do about the defunct processes as this is handled outside of Netdisco, and that includes the processes for the ping. I guess the Linux system cleans things up after a while?
I'm closing this ticket as the original issue was resolved (thanks @dev-osuri!) but please open a new one if there is a problem.
