### ISSUE TITLE
node.oui format change in newer versions?

### ISSUE THREAD

**Issue by smurf12345** [netdisco/netdisco#1195]
I just noticed my reports not showing properly and I think I tracked it down to the node.oui format.  Previous versions I show node.oui used "aa:bb:cc" with colons but now it seems it is recording the node.oui without colons.  Is this an expected change?  I was not able to find any docs stating it.

## Expected Behavior
I expected node.oui to contain columns
```
netdisco=> select * from node;
        mac        |     switch     |           port           | vlan | active |  oui   |         time_first         |        time_recent         |         time_last          
-------------------+----------------+--------------------------+------+--------+--------+----------------------------+----------------------------+----------------------------
 a4:97:5c:9b:1d:c4 | 192.168.237.90  | GigabitEthernet0/1       | 211  | t      | a4:97:5c | 2024-03-19 15:26:48.64109  | 2024-03-19 15:26:53.760381 | 2024-03-27 14:25:20.627357
 64:8f:3e:c9:ab:41 | 192.168.128.45  | GigabitEthernet2/0/23    | 132  | f      | 64:8f:3e | 2024-03-25 07:22:30.754826 | 2024-03-25 07:22:37.721011 | 2024-03-25 07:22:30.754826
 90:eb:50:86:b0:0e | 192.168.128.47  | GigabitEthernet2/0/35    | 140  | f      | 90:eb:50 | 2024-03-22 07:28:26.100365 | 2024-03-22 07:28:41.703421 | 2024-03-22 07:28:26.100365
```

## Current Behavior
Currently, if I query node table, it shows without ":".
```
netdisco=> select * from node;
        mac        |     switch     |           port           | vlan | active |  oui   |         time_first         |        time_recent         |         time_last          
-------------------+----------------+--------------------------+------+--------+--------+----------------------------+----------------------------+----------------------------
 a4:97:5c:9b:1d:c4 | 192.168.237.90  | GigabitEthernet0/1       | 211  | t      | a4975c | 2024-03-19 15:26:48.64109  | 2024-03-19 15:26:53.760381 | 2024-03-27 14:25:20.627357
 64:8f:3e:c9:ab:41 | 192.168.128.45  | GigabitEthernet2/0/23    | 132  | f      | 648f3e | 2024-03-25 07:22:30.754826 | 2024-03-25 07:22:37.721011 | 2024-03-25 07:22:30.754826
 90:eb:50:86:b0:0e | 192.168.128.47  | GigabitEthernet2/0/35    | 140  | f      | 90eb50 | 2024-03-22 07:28:26.100365 | 2024-03-22 07:28:41.703421 | 2024-03-22 07:28:26.100365
```

## Context
At the moment, many of my reports stopped reporting oui company names due to the query I am using.  I am able to work around it for now by change my custom reports.

## Your Environment

Software	Version
App::Netdisco	2.72.3
SNMP::Info	3.95
DB Schema	85
PostgreSQL	13.00.4
Perl	5.38.2

**Comment by ollyg** [comment]
Hi @smurf12345! thanks for asking about this and I'm sorry the issue hit you. What happened is that sometime ago the IEEE stopped using just six hex bits for the OUI/manufacturer and now has three different lengths of OUI. So, since version 2.70 of Netdisco the `oui` field has just the OUI without ":" separators as they no longer make sense.

What you can do is SQL JOIN to the `manufacturer` table using `node.oui = manufacturer.base`. Then you can retrieve the fields you want from the manufacturer table.

Do come back to me if you need to know more, but just be aware that OUI length is not universal any more.

**Comment by smurf12345** [comment]
Thanks for the quick response and clarification.  It makes perfect sense.  I can easily adjust based on the info you provided.
