### ISSUE TITLE
Feature request:  pull vtp mode from a switch

### ISSUE THREAD

**Issue by cnoyes72** [netdisco/netdisco#1197]
Hello,

  Just as a feature request, could netdisco pull the VTP mode of a switch (it pulls the VTP domain, but I couldn't see that it was pulling the VTP mode).  The following is from the cisco MIB

.1.3.6.1.4.1.9.9.46.1.2.1.1.3

managementDomainLocalMode OBJECT-TYPE

-- FROM CISCO-VTP-MIB

SYNTAX Integer { client(1), server(2), transparent(3), off(4) }

MAX-ACCESS read-create

STATUS Current

DESCRIPTION "The local VTP mode in this management domain when managementDomainVersionInUse is version1(1) or version2(2).

If managementDomainVersionInUse is version3(4), this object has the same value with vtpDatabaseLocalMode of VLAN database type.

- 'client' indicates that the local system is acting as a VTP client.

- 'server' indicates that the local system is acting as a VTP server.

- 'transparent' indicates that the local system does not generate or listen to VTP messages, but forwards messages. This mode can also be set by the device itself when the amount of VLAN information is too large for it to hold in DRAM.

- 'off' indicates that the local system does not generate, listen to or forward any VTP messages."

**Comment by ollyg** [comment]
Hi @cnoyes72 thanks for the request! should be straightforward to implement

**Comment by ollyg** [comment]
implemented in 369f9b98
