### ISSUE TITLE
PortFast information

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#12]
If a port has its portfast setting enabled, it will
automatically go into
the forwarding state, bypassing the learning and
listening state thus
it would come up quicker than a port set in portfast
disabled mode \(in
terms of spanning tree\).  Consequently, only ports
connected to a
single end stations should be in portfast enabled mode
since their
addition to the tree would not create a loop; we figure
it would be useful
to see if any trunk port is portfast enabled because
this may potentially
create a loop.

CISCO-STACK-MIB has an OID which works for our 4000's
and 5000's
\(1.3.6.1.4.1.9.5.1.4.1.1.12.mod.port\) but its status is
deprecated...I've
yet to look for an OID that's current and will work on
all \(cisco\)
devices, but I'm sure I could find one if you think
this might be a useful
addition to netdisco.

Thanks,

R. Shvarzman

Reported by: maxslug-placeholder

Original Ticket: [netdisco/nd2-features/12](https://sourceforge.net/p/netdisco/nd2-features/12)

**Comment by ollyg** [comment]
Thanks to the snmpwalk from @pioevogel I was able to implement this, too!
