### ISSUE TITLE
Get Queue Jobs via API does not give the same result as via UI

### ISSUE THREAD

**Issue by ubzmrh** [netdisco/netdisco#1206]
Version : 2.76.0

With a cron, we do a pingsweep for each subnet every week.
But each subnet can contain some devices are errored in the job queue.

We want extract a list of these devices, but the API give use the current queue instead of the list we asked for.

We use  python and requests library
GET url = http://MyServer:5000/api/v1/queue/jobs
headers={'Accept': 'application/json', 'Authorization': '6ebe3f5656dd8e6372eb2f00036a6b75'}
params={'limit': 1000, 'action': 'Discover'}

But we don't get any record with "action": "discover" but we can see it in UI.

**Comment by ollyg** [comment]
Hi @ubzmrh ! thanks for the report....
can you just check whether it makes a difference to use "discover" instead of "Discover" in the python requests call?
Many thanks.

**Comment by ubzmrh** [comment]
Hi Ollyg, 
discover or Discover makes no difference, nor also the search for an ip address.

**Comment by ollyg** [comment]
I wonder if this is the issue: 
https://github.com/netdisco/netdisco/blob/3e2660dc3ab1325d01db9761478fb77213e7450b/lib/App/Netdisco/Web/API/Queue.pm#L66-L69

**Comment by ollyg** [comment]
Hi @ubzmrh unfortunately I cannot reproduce this issue.
If I have some jobs in my queue, some are not run and some are completed, then I query the API, it will return the jobs.

Please can you give more detailed description of what you are missing? Can you include screenshots of the data which you say is in the web and also the API call tested through the web: http://localhost:5000/swagger-ui/?url=/swagger.json#/Queue/get_api_v1_queue_jobs

**Comment by ubzmrh** [comment]
Hello @ollyg,
Sorry, I have to apologize for wasting your time.
I just forgot to add the parameters to the post function.

I needed a few days of vacation.
