### ISSUE TITLE
Problem with Port report "Blocked - Error Disabled"

### ISSUE THREAD

**Issue by ubzmrh** [netdisco/netdisco#1207]
The report works fine, but … 
When we use API or click on "Download as CSV" the field device contain html code 
`<a href="/search?q=1.2.3.4">1.2.3.4</a>`
instead of the ip address alone.
All other fields are correct

It seems that all reports with ip address have the same defect, for instance the report IPs on multiple devices

**Comment by ollyg** [comment]
fixed in 2a6d5849
many thanks for the bug report @ubzmrh !
