### ISSUE TITLE
Issue with platform detection

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#1215]
I may be going mad, but I was trying to query the platform info for a Fortigate (to work out what platform type to use in the SSH connection info) and got the following:

`$ ~/bin/netdisco-do show -d 172.16.225.1 -e c_platform
[2172539] 2024-05-28 15:06:32  info App::Netdisco version 2.076002 loaded.
[2172539] 2024-05-28 15:06:32  info show: [172.16.225.1]/c_platform started at Tue May 28 15:06:32 2024
{
    114043059.31.1   "Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.12.7, RELEASE SOFTWARE (fc2)Technical Support: http://www.cisco.com/techsupportCopyright (c) 1986-2022 by Cisco Systems, Inc.Compiled Wed 02-Feb-22 07:28 ",
    114043059.32.2   "Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.12.7, RELEASE SOFTWARE (fc2)Technical Support: http://www.cisco.com/techsupportCopyright (c) 1986-2022 by Cisco Systems, Inc.Compiled Wed 02-Feb-22 07:28 ",
    114043059.33.3   "Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.12.7, RELEASE SOFTWARE (fc2)Technical Support: http://www.cisco.com/techsupportCopyright (c) 1986-2022 by Cisco Systems, Inc.Compiled Wed 02-Feb-22 07:28 ",
    114043059.34.4   "Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.12.7, RELEASE SOFTWARE (fc2)Technical Support: http://www.cisco.com/techsupportCopyright (c) 1986-2022 by Cisco Systems, Inc.Compiled Wed 02-Feb-22 07:28 "
}
[2172539] 2024-05-28 15:06:33  info show: finished at Tue May 28 15:06:33 2024
[2172539] 2024-05-28 15:06:33  info show: status done: Showed c_platform response from 172.16.225.1
`

The IP address is copied directly from the netdisco device details page for the fortigate.

**Comment by ollyg** [comment]
That info should not be cached, but if you want to be really sure, call c_platform_raw instead of c_platform
In any case, I think this was discussed in IRC and resolved?

**Comment by kingtrw** [comment]
My bad - I didn't realise that c_platform was for info on connected platforms, so this is entirely expected behaviour.
