### ISSUE TITLE
IP inventory not offering all known L3 interface IP Prefixes 

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#1217]
We're moving to a new set of internal vlans that are routed by our Fortigates (rather than by the Cisco distribution switches that handle routing for the old vlans)

Netdisco is aware of nodes using the new IP addresses -- but the IP inventory and subnet utilization reports aren't aware of the ranges.

running netdisco-do arpnip -D against the firewall pulls in the expected list of ARP entries, so I'm not sure what's missing!

**Comment by ollyg** [comment]
So the fortigate is a router. Is it being discovered as a router and showing the Addresses tab populated with L3 interface IP prefixes?

**Comment by kingtrw** [comment]
That is correct -- the addresses tab is showing prefix ranges that do not appear to be selectable as options in the IP inventory or subnet report.

**Comment by ollyg** [comment]
Fascinating. I will look into it. As you may know/guess, the workings of the IP Inventory report are a bit of a dark art.

**Comment by ollyg** [comment]
many thanks, should be fixed in 9da43dc6
