### ISSUE TITLE
Datatable error, and shifted data in device/ports page

### ISSUE THREAD

**Issue by DanielGeerts** [netdisco/netdisco#1219]
In /share/views/ajax/device/ports.tt, the "External links" header is displayed using this condition:
[% NEXT IF item.name == 'c_links' AND settings.external_links.device_port.empty %]

but its data is displayed using this condition:
[% IF params.c_links AND settings.external_links.device_port.size > 0 %]

I'm getting datatable-errors about a missing column, and making these conditions match fixes it. Apparently it's returning an array with zero elements, causing a header to be displayed but no data. This also causes all other columns to shift under the wrong header.

**Comment by ollyg** [comment]
Thanks for the bug report @DanielGeerts ! I will look into this asap

**Comment by ollyg** [comment]
fixed in 1cfbe6d7

**Comment by DanielGeerts** [comment]
Confirmed fixed. Thanks!
