### ISSUE TITLE
Device Discovery not possible in edge routed fabric with isolated underlay network

### ISSUE THREAD

**Issue by ComicZockt** [netdisco/netdisco#1223]
## Environment
Our Datacenter employs an Edge Routed Fabric (IP Clos Fabric) using Juniper QFX devices in Spine and Leaf roles respectively
The Underlay network uses isolated IPv4 point-to-point networks (/31 netmask), that are not accessible from anywhere except the underlay. The Underlay network uses an internally reserved IP space that does not collide with any other routed links in the datacenter.
We do have an established Out-Of-Band network accessible to Netdisco and all devices in the in-band network are set to provide their out-of-band management IP to LLDP neighbors.

## Current Behavior
Currently, with the links from leaf to spine having an ip address assigned, Netdisco correctly assumes this to be routed links.
The way the Underlay is designed, however, results in Netdisco properly grabbing the neighbor IP and then failing to discover said device.

## Expected Behavior
On failure of Discovery using the discovered IP address, I would like Netdisco to fall back to the LLDP learned IP address of the neighbor,
or a setting to skip to the LLDP learned IP address directly.

## Possible Solution
Perfect for this scenario would most likely be a configuration setting that allows me to set IP ranges for which Netdisco ignores the link and neighbor IP and immediately uses the LLDP learned IP address to discover the neighbor.

## Possible Workaround
A possible workaround would be to pingsweep the entire Out-Of-Band network, which I am hesitant about due to changes in topology occuring pretty frequently, so Netdisco wouldn't be able to play it's auto-discovery strength.

## Software versions
* Netdisco version used:  2.76.5
* SNMP::Info version used: 3.970.1

## Config info (deployment.yml)
I've already tried setting the "discover_routed_neighbors" toggle to FALSE, which just (understandably) breaks discovery for Routers and Firewalls.
Also, to keep Netdisco from snooping too far into payload networks, I set "discover_only" to our Out-Of-Band networks and, as a test, the underlay networks as well, without improvement.

## Device information
Affected devices in my scenario are QFX5120 series.

**Comment by ollyg** [comment]
Hi @ComicZockt many thanks for the report! I'm motivated to address this issue as it is one I've encountered myself.

One thing which puzzles me, and I may be misunderstanding: Netdisco should queue a job for any neighbor candidate, whatever the source. So a job gets queued to discover the LLDP neighbor (good) and the /31 neighbor (bad). The LLDP neighbor job should succeed in a new device appearing, and the /31 neighbor will, I guess, timeout on discovery.

And yet you say that "On failure of Discovery using the discovered IP address, I would like Netdisco to fall back to the LLDP learned IP address of the neighbor" which implies the two are not so independent.

Please can you confirm what you see? For example, what you can do on a clean slate install, is stop the backend, run a discover on a device, and then look at the queue to see what jobs are waiting. I would expect one job for each neighbor candidate, whether good or bad.

Second thing which puzzles me, related to this, is that discover_only set to the out-of-band range should be the fix, but only if there are indeed multiple jobs and then Netdisco has a hint to ignore one and go for the other.

**Comment by ComicZockt** [comment]
@ollyg thank you for the swift reply, i did not notice any additional jobs being placed in queue whenever i started a discovery job for one of the affected switches.
I will try again later today with the backend stopped and report back to you.

**Comment by ComicZockt** [comment]
@ollyg i just now did a manual discover for one of the affected devices.
Juniper by default announces the IP address assigned to the dedicated Out-Of-Band Ethernet port via LLDP.
There is however a difference between SRX devices and EX/QFX devices when clustered.
On SRX devices, you assign an IP address to the pfx0 interface and it'll assign addresses to the cluster members depending on the device role.
EX and QFX devices effectively shut down the routing engine on all non-primary devices and use em0 as default. There is however the option to use another interface: VME. This interfaces is designed to be used in Virtual-Chassis (Device Stacking) scenarios, however on QFX5110, QFX5120 and QFX5200 series devices there seems to be an issue with the Virtual Chassis Port redirection, according to [This Knowledgebase Entry](https://www.juniper.net/documentation/us/en/software/junos/virtual-chassis-qfx/topics/concept/virtual-chassis-ex4200-global-management.html) (last edited Nov 2023 as of writing) [WayBack Capture 2024-01-12](https://web.archive.org/web/20240112122336/https://www.juniper.net/documentation/us/en/software/junos/virtual-chassis-qfx/topics/concept/virtual-chassis-ex4200-global-management.html)
If the VME port is used in a non-clustered environment, the information is not properly passed to LLDP.

Upon reconfiguring one of the affected devices for this, (and a short discussion between me and my colleagues about killing our monitoring of said device for a couple minutes in the process) the discovery now properly displays all IPs: The Underlay Link IPs and the LLDP-learned neighbor IPs.

I will roll out the changes in our networks and watch netdisco do its thing.
Thank you for the assistance!

**Comment by ollyg** [comment]
Hi @ComicZockt hurrah! 🎉 I'm so glad you managed to find a solution, thanks for sharing the details 💟
