### ISSUE TITLE
ARPNIP ALL - Not Analyzing all the devices

### ISSUE THREAD

**Issue by cesacal** [netdisco/netdisco#1226]
Hello,

We have 16 devices included on the section "arpnip_only".
10 of them are Cisco multilayer switches.
6 of them are PaloAlto devices.

Everything was working fine, until some days ago we changed the snmp version of the PaloAltos from v2 to v3.
On these PaloAltos the discover works fine, and the individual ARPNIP works fine.
However, while doing the ARPWALK (or ARPNIP all), these 6 PaloAlto devices are not included.

![imagen](https://github.com/netdisco/netdisco-docker/assets/97600299/a9687d44-8951-4f68-99e9-daf13af4d17d)

**Comment by ollyg** [comment]
Hi @cesacal most likely the device is returning a different "layers" result on SNMPv3, I don't know why. The reason it works when running standalone arpnip is that this usually ignores the layers and forces a run.
Try using the ignore_layers or force_arpnip ACL settings: https://github.com/netdisco/netdisco/wiki/Configuration
