### ISSUE TITLE
Discover - arpnip fails on devices with IPv6 that share same IP link-local in routed ports

### ISSUE THREAD

**Issue by elbuit** [netdisco/netdisco#1232]
Hello.
I've some cisco catalyst 9500 that netdisco is not able to discover correctly.

These routers have some interfaces configured in IPv6 only and all of them share the same IPv6 link-local address.

## Current Behavior

That makes netdisco fail because it uses ip(device IP) and alias (port IPv6) and netdisco uses link-local address as alias (router have also a  global unicast address on those ports).

device_ip table have a "device_ip_pkey" PRIMARY KEY, btree (ip, alias) and netdisco crashes when it try to update table:
```
2024-07-10 07:10:37 UTC [806670] debug ⮕ worker Discover::Hooks p0
2024-07-10 07:10:37 UTC [806670] debug ⬅ (info)  [192.XXX.YYY.ZZZ] hooks - skipping due to incomplete job
2024-07-10 07:10:37 UTC [806670] debug ⮕ worker Discover::Snapshot p0
2024-07-10 07:10:37 UTC [806670]  info discover: finished at Wed Jul 10 09:10:37 2024
2024-07-10 07:10:37 UTC [806670]  info discover: status error: DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(): execute_for_fetch() aborted with 'ERROR:  llave duplicada viola restricción de unicidad «device_ip_pkey»
DETAIL:  Ya existe la llave (ip, alias)=(192.XXX.YYY.ZZZ, fe80::a618:bbff:fef8:98ff).' at populate slice:
{
  alias => "fe80:0:0:0:a618:bbff:fef8:98ff",
  dns => undef,
  ip => "192.XXX.YYY.ZZZ",
  port => "HundredGigE1/0/2",
  subnet => undef,
} at /usr/local/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Properties.pm line 208
```

## Possible Solution

Probably change PRIMARY KEY to more values ie: (ip, alias, port) or use first unicast global address instead of link-local.

## Steps to Reproduce (for bugs)
1.  on a cisco catalyst 9500 IOSXE Version 17.12.1 (probably on more devices)
2. this router should have more than one interface configured only with IPv6
3. ~/bin/netdisco-do discover  -d IP -D 

## Context

 It avoids to get IPv6 neighbours table

## Your Environment
Debian GNU/Linux 12 (bookworm)
Netdisco 	2.76.5
SNMP::Info 	3.970.1 
DB Schema 	87
PostgreSQL 	11.00.17
Perl 	5.36.0

**Comment by ollyg** [comment]
Hi @elbuit I have had to implement a rather sledgehammer solution to this, which is to skip the IP Aliases which are within:

- `['fe80::/64','169.254.0.0/16']`

This is because Netdisco 2 has this DB schema limitation you discovered where the primary keys are vulnerable to duplicate IPs (same affects duplicate device IPs, like for clustered devices). We have known for a long time of this issue but it'll only be fixed in Netdisco 3 (someday...). Seems fair to have the same limitation here as it's not new.

Implemented in 9223439e
