### ISSUE TITLE
Prefix mask less than 16 crashes web application.

### ISSUE THREAD

**Issue by tran-christian** [netdisco/netdisco#1238]
## Expected Behavior
Enter a subnet with mask lower than 16. For example, 10.0.0.0/8 or 10.0.0.0/15

## Current Behavior
The web application crashes. This is seen with the [demo app](https://netdisco2-demo.herokuapp.com/) too. Masks that are 16 and up seem to work fine such as 10.0.0.0/16. This error also displays in the web application's logs.

`error request to POST /admin/discodevs crashed: netmask error: overrange or spurious bits at /home/netdisco/perl5/lib/perl5/App/Netdisco/Web/AdminTask.pm line 18.`

## Steps to Reproduce (for bugs)
1.  Go to front page of the web application.
2.  Enter a prefix with a mask lower than 16.
3.  Web application crashes.

This is reproducible on the [demo web app](https://netdisco2-demo.herokuapp.com/)

**Comment by ollyg** [comment]
many thanks for the bug report!
