### ISSUE TITLE
Exporting from "Node Vendor Inventory" as CSV: VLAN column missing

### ISSUE THREAD

**Issue by ralv3967** [netdisco/netdisco#1239]
When exporting nodes from a manufacturer from the "Node Vendor Inventory" report, the "VLAN" column is not included in the export.

Netdisco 2.76.5
SNMP::Info 3.970.1
DB Schema 87
PostgreSQL 15.00.7
Perl 5.36.0

**Comment by ollyg** [comment]
thanks for the bug report!
