### ISSUE TITLE
columns appear at wrong positions in "Ports"-View if "PoE" is also selected

### ISSUE THREAD

**Issue by kkesper** [netdisco/netdisco#1242]
## Expected Behavior
When the "Ports"-View of a device is selected, the values for "Native VLAN", VLAN Membership" and "PoE" shoud appear in the correct columns when all of them are enabled in "Display Columns".

## Current Behavior
The columns are correct, as long as "PoE" is not enabled. 

When "PoE" is enabled, the contents of the columns are shifted to the left so that they are schown under the wrong Headline. 

## Steps to Reproduce (for bugs)
1.
Select "Ports"-view of a device (in my case Cisco with PoE-Ports)

2.
enable "Native VLAN" and "VLAN Membership" in the "Display Columns"-Tab at the right side.
---> everything is ok.

3.
enable  "Native VLAN" and "VLAN Membership" and "PoE"
---> columns are at the wrong positions (wrong headlines).

## Your Environment
* Netdisco version used: 2.76.5
* SNMP::Info version used: 3.970.1

**Comment by ollyg** [comment]
Hi @kkesper unfortunately I can't reproduce this :-(
Are you able to make sure your web frontend is fully restarted, and also browser cache is emptied, and take a screenshot?

**Comment by kkesper** [comment]
![Screenshot-without-PoE](https://github.com/user-attachments/assets/edb5b129-91da-4d0c-9084-d0f8a48c304b)
![Screenshot-with-PoE](https://github.com/user-attachments/assets/1db4671c-56ad-4d7f-857d-13bd56a5ae03)

Hi @ollyg, i found this behaviour at different client PCs with windows and linux.

**Comment by ollyg** [comment]
Hi @kkesper I think somehting is not right in your installation. If you look in the sidebar, the order of the options is also wrong.

It goes speed (running, configured), then duplex (configured, running). But it should be (configured, running) for both as in the configuration file: https://github.com/netdisco/netdisco/blob/master/share/config.yml#L130

This probably explains why I can't reproduce the problem, but I've no idea why your local install has this error. Are you able to try with a clean install and minimal config to see what happens?

**Comment by kkesper** [comment]
Hello ollyg,

many thanks for your comment. Now i  found the mistake:

Some time ago i wanted to change the default-checks in the "Ports"-View. I added to deployment.yml:

sidebar_defaults:
  search_port:
    uplink:      { default: checked }
  device_ports:
    c_lastchange:   { label: 'Last Change', default: checked, idx: 6 }
    c_speed:        { label: 'Speed (running)', default: checked, idx: 9 }
    c_power:        { label: 'PoE', default: checked, idx: 17 }
    c_nodes:        { label: 'Connected Nodes', default: checked, idx: 20 }

At some point in time since that it seems that the indices have changed (or it is also possible that they were wrong from the bedinning). I looked them up again in perl5/lib/perl5/auto/share/dist/App-Netdisco/config.yml and corrected them:

sidebar_defaults:
  search_port:
    uplink:      { default: checked }
  device_ports:
    c_lastchange:   { label: 'Last Change', default: checked, idx: 6 }
    c_speed:        { label: 'Speed (running)', default: checked, idx: 11 }
    c_power:        { label: 'PoE', default: checked, idx: 19 }
    c_nodes:        { label: 'Connected Nodes', default: checked, idx: 22 }

Now everything looks as intended. The columns and the sidebar are correct.
Sorry for wasting your time - this was my fault.

Best regards 
Kurt

**Comment by ollyg** [comment]
Hi @kkesper many thanks for the update! I'm so glad you found the cause of the issue.
I'll make sure always to add a note in Release Notes if we ever change the indexing again, and sorry it's such a fragile design!
