### ISSUE TITLE
Alien::poetry fails to install, aborts NetDisco Install

### ISSUE THREAD

**Issue by HowieDewin** [netdisco/netdisco#1249]
Hi, I'm not sure if this is the correct place for this, please remove/notify me if it isn't.

I am attempting to install NetDisco and everything seems to go well after running the install script, until it hits the Alien::poetry module. At which point the install fails.

By install script I mean:
> curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco

I am attempting a clean install on a freshly installed copy of Ubuntu 22. Below are the log files, I apologize if I missed anything, this is my first issue submission.

[Build.log](https://github.com/user-attachments/files/16944288/Build.log)

**Comment by HowieDewin** [comment]
Seems to be a result of pip not being installed by default with Python3.

I used the following to resolve the issue:
> sudo apt-get install python3.10-venv

After this, the Alien::poetry module installed.

**Comment by ollyg** [comment]
Hi @HowieDewin nevertheless, THANK YOU for the ticket and contributing the solution! I'll add the package to the install docs guidance.

**Comment by alcatron** [comment]
I have the same problem on AlmaLinux(aka redhat) i checked python and its installed along with that yum command

Unpacking Alien-poetry-1.000006.tar.gz
Entering Alien-poetry-1.000006
Checking configure dependencies from META.json
Checking if you have Alien::Build::MM 0.25 ... Yes (2.83)
Checking if you have Alien::Build 2.83 ... Yes (2.83)
Configuring Alien-poetry-1.000006
Running Makefile.PL
Alien::Build::CommandSequence> +  sh -c 'exit 127'
Alien::Build> error in probe (will do a share install): external command failed at /home/netdisco/perl5/lib/perl5/Alien/Build/CommandSequence.pm line 88.
Alien::Build> Don't panic, we will attempt a share build from source if possible.
Alien::Build> Do not file a bug unless you expected a system install to succeed.
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Alien::poetry
Writing MYMETA.yml and MYMETA.json
-> OK

/home/netdisco/perl5/lib/perl5/x86_64-linux-thread-multi/auto/share/dist/Alien-poetry/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.8.3)
Installing Poetry (1.8.3): Creating environment
Installing Poetry (1.8.3): Installing Poetry
Installing Poetry (1.8.3): An error occurred. Removing partial environment.
Poetry installation failed.
See /home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/poetry-installer-error-ictnf70d.log for error logs.
external command failed at /home/netdisco/perl5/lib/perl5/Alien/Build/CommandSequence.pm line 72.
make: *** [Makefile:957: _alien/mm/build] Error 1
-> FAIL Installing Alien::poetry failed. See /home/netdisco/.cpanm/work/1726474436.74607/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Alien::poetry' is not installed
-> FAIL Bailing out the installation for App-Netdisco-2.079001.

**Comment by ollyg** [comment]
Hi @alcatron, very sorry to hear of your trouble installing Netdisco.

Have you managed to take a look into the log file which is referenced in the output?
/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/poetry-installer-error-ictnf70d.log

I guess it's a missing package. For example on Debian we found that python3-venv is needed, as well as python3. Not sure on RPM based distro.

kind regards
Oliver.

**Comment by alcatron** [comment]
I tried to install it in my test lab, before trying the latest netdisco onto a redhat production box, lucky I didn’t attempt the production one first.

 

Ive got all the pythons installed I ran with yum command. 

 

This is the error in that file

 

ERROR: Could not find a version that satisfies the requirement poetry==1.8.3 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.0.post1, 0.4.1, 0.4.2, 0.5.0b1, 0.5.0b2, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3b1, 0.6.3b2, 0.6.3b3, 0.6.3b4, 0.6.3b5, 0.6.3b6, 0.6.3b7, 0.6.3, 0.6.4b1, 0.6.4, 0.6.5, 0.7.0b1, 0.7.0b2, 0.7.0b3, 0.7.0b4, 0.7.0, 0.7.1, 0.8.0a0, 0.8.0a1, 0.8.0a2, 0.8.0a3, 0.8.0a4, 0.8.0, 0.8.1a0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5a0, 0.8.5, 0.8.6, 0.9.0a0, 0.9.0a1, 0.9.0a2, 0.9.0a3, 0.9.0, 0.9.1, 0.10.0a0, 0.10.0a1, 0.10.0a2, 0.10.0a3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0a0, 0.11.0a1, 0.11.0a2, 0.11.0a3, 0.11.0a4, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.12.0a0, 0.12.0a1, 0.12.0a2, 0.12.0a3, 0.12.0a4, 0.12.0a5, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10, 0.12.11, 0.12.12, 0.12.13, 0.12.14, 0.12.15, 0.12.16, 0.12.17, 1.0.0a0, 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a5, 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5, 1.0.0b6, 1.0.0b7, 1.0.0b8, 1.0.0b9, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.1.0a1, 1.1.0a2, 1.1.0a3, 1.1.0b1, 1.1.0b2, 1.1.0b3, 1.1.0b4, 1.1.0rc1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.2.0a1, 1.2.0a2)

ERROR: No matching distribution found for poetry==1.8.3

 

Traceback:

 

  File "/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py", line 923, in main

    return installer.run()

  File "/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py", line 560, in run

    self.install(version)

  File "/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py", line 582, in install

    self.install_poetry(version, env)

  File "/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py", line 685, in install_poetry

    env.pip("install", specification)

  File "/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py", line 375, in pip

    return self.python("-m", "pip", *args, **kwargs)

  File "/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py", line 372, in python

    return self.run(self._python, *args, **kwargs)

  File "/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py", line 367, in run

    log=completed_process.stdout.decode(),

 

From: Oliver Gorwits ***@***.***>
Reply to: netdisco/netdisco ***@***.***>
Date: Monday 16 September 2024 at 18:04
To: netdisco/netdisco ***@***.***>
Cc: Muris ***@***.***>, Mention ***@***.***>
Subject: Re: [netdisco/netdisco] Alien::poetry fails to install, aborts NetDisco Install (Issue #1249)

 

Hi @alcatron, very sorry to hear of your trouble installing Netdisco.

Have you managed to take a look into the log file which is referenced in the output?
/home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/poetry-installer-error-ictnf70d.log

I guess it's a missing package. For example on Debian we found that python3-venv is needed, as well as python3. Not sure on RPM based distro.

kind regards
Oliver.

**Comment by ollyg** [comment]
Thanks, how about the content of the file /home/netdisco/.cpanm/work/1726474436.74607/build.log ?

**Comment by alcatron** [comment]
Fetching http://www.cpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.079001.tar.gz
-> OK
Unpacking App-Netdisco-2.079001.tar.gz
Entering App-Netdisco-2.079001
Checking configure dependencies from META.json
Checking if you have ExtUtils::Install 1.46 ... Yes (2.14)
Checking if you have DBIx::Class 0.082810 ... Yes (0.082843)
Checking if you have Module::Build 0.42 ... Yes (0.4224)
Checking if you have File::Spec 0 ... Yes (3.74)
Configuring App-Netdisco-2.079001
Running Build.PL
Checking prerequisites...
  requires:
    !  Alien::poetry is not installed
  build_requires:
    !  Alien::poetry is not installed
  test_requires:
    !  Env::Path is not installed
    !  Test::Compile is not installed
  recommends:
    *  Alien::SNMP is not installed
    *  Graph is not installed
    *  GraphViz is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'App-Netdisco' version '2.079001'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have HTTP::Tiny 0.029 ... Yes (0.074)
Checking if you have DBD::Pg 0 ... Yes (3.7.4)
Checking if you have List::MoreUtils 0.428 ... Yes (0.430)
Checking if you have Plack 1.0023 ... Yes (1.0050)
Checking if you have Role::Tiny 1.002005 ... Yes (2.002004)
Checking if you have Alien::poetry 1.000006 ... No
Checking if you have Data::Visitor::Tiny 0 ... Yes (0.001)
Checking if you have Starman 0.4008 ... Yes (0.4016)
Checking if you have Term::ReadLine 0 ... Yes (1.17)
Checking if you have Dancer 1.3132 ... Yes (1.3513)
Checking if you have Net::LDAP 0 ... Yes (0.68)
Checking if you have Plack::Middleware::ReverseProxy 0.15 ... Yes (0.16)
Checking if you have Module::Load 0.32 ... Yes (0.32)
Checking if you have IO::Socket::SSL 2.048 ... Yes (2.066)
Checking if you have ExtUtils::InstallPaths 0 ... Yes (0.012)
Checking if you have AnyEvent 7.05 ... Yes (7.17)
Checking if you have Term::ANSIColor 5.01 ... Yes (5.01)
Checking if you have Algorithm::Cron 0.07 ... Yes (0.10)
Checking if you have Path::Class 0.32 ... Yes (0.37)
Checking if you have File::Spec::Functions 0 ... Yes (3.74)
Checking if you have URI 0 ... Yes (1.73)
Checking if you have SQL::Abstract 1.85 ... Yes (2.000001)
Checking if you have YAML 0.84 ... Yes (1.30)
Checking if you have Template 2.24 ... Yes (3.101)
Checking if you have aliased 0 ... Yes (0.34)
Checking if you have Socket6 0.23 ... Yes (0.29)
Checking if you have Session::Storage::Secure 1.000 ... Yes (1.000)
Checking if you have ExtUtils::Helpers 0 ... Yes (0.026)
Checking if you have Text::CSV_XS 1.53 ... Yes (1.53)
Checking if you have IO::Socket::INET6 2.72 ... Yes (2.73)
Checking if you have Plack::Middleware::Debug 0 ... Yes (0.18)
Checking if you have Opcode 1.07 ... Yes (1.39)
Checking if you have Dancer::Plugin::Swagger 0 ... Yes (0.3.0)
Checking if you have Expect 0 ... Yes (1.35)
Checking if you have JSON 2.90 ... Yes (2.97001)
Checking if you have Template::AutoFilter 0 ... Yes (0.143050)
Checking if you have Package::DeprecationManager 0 ... Yes (0.17)
Checking if you have version 0.9902 ... Yes (0.9924)
Checking if you have Try::Tiny 0 ... Yes (0.30)
Checking if you have Net::Ping::External 0.15 ... Yes (0.15)
Checking if you have URL::Encode::XS 0 ... Yes (0.03)
Checking if you have Term::UI 0 ... Yes (0.50)
Checking if you have Plack::Handler::Twiggy 0 ... Yes (undef)
Checking if you have Plack::Middleware::Expires 0.03 ... Yes (0.06)
Checking if you have CGI::Expand 2.05 ... Yes (2.05)
Checking if you have EV 0 ... Yes (4.33)
Checking if you have autovivification 0 ... Yes (0.18)
Checking if you have File::Slurper 0.009 ... Yes (0.014)
Checking if you have DBIx::Class::Helpers 2.033006 ... Yes (2.036000)
Checking if you have URI::Based 0 ... Yes (1.03)
Checking if you have Archive::Extract 0 ... Yes (0.88)
Checking if you have MCE 1.866 ... Yes (1.882)
Checking if you have Plack::Middleware::Headers 0 ... Yes (0.11)
Checking if you have Net::Ping 2.75 ... Yes (2.75)
Checking if you have Daemon::Control 0.001006 ... Yes (0.001010)
Checking if you have Storable 0 ... Yes (3.11)
Checking if you have DBIx::Class 0.082841 ... Yes (0.082843)
Checking if you have Scope::Guard 0 ... Yes (0.21)
Checking if you have App::local::lib::helper 0.07 ... Yes (0.07)
Checking if you have MIME::Base64 3.13 ... Yes (3.15)
Checking if you have Net::DNS 0.72 ... Yes (1.35)
Checking if you have Dancer::Plugin::DBIC 0.2001 ... Yes (0.2104)
Checking if you have AnyEvent::DNS::EtcHosts 0 ... Yes (0.0103)
Checking if you have File::Path 0 ... Yes (2.15)
Checking if you have Template::Plugin::CSV 0.04 ... Yes (0.04)
Checking if you have Regexp::Common 2017060201 ... Yes (2017060201)
Checking if you have Dancer::Session::Cookie 0.27 ... Yes (0.30)
Checking if you have Proc::ProcessTable 0.636 ... Yes (0.636)
Checking if you have Guard 1.022 ... Yes (1.023)
Checking if you have List::Util 1.49 ... Yes (1.63)
Checking if you have Dancer::Plugin::Passphrase v2.0.1 ... Yes (2.0.1)
Checking if you have App::cpanminus 1.6108 ... Yes (1.7046)
Checking if you have Net::Domain 1.23 ... Yes (3.11)
Checking if you have Sereal 0 ... Yes (5.001)
Checking if you have Sys::SigAction 0 ... Yes (0.23)
Checking if you have Pod::Usage 0 ... Yes (1.69)
Checking if you have YAML::XS 0.41 ... Yes (0.85)
Checking if you have Data::Printer 0 ... Yes (1.001000)
Checking if you have File::ShareDir 1.03 ... Yes (1.118)
Checking if you have Dancer::Plugin::Auth::Extensible 0.30 ... Yes (1.00)
Checking if you have URL::Encode 0.03 ... Yes (0.03)
Checking if you have Template::Plugin::Number::Format 1.02 ... Yes (1.06)
Checking if you have HTML::Parser 3.70 ... Yes (3.72)
Checking if you have SQL::Translator 0.11024 ... Yes (1.62)
Checking if you have SNMP::Info 3.972000 ... Yes (3.972000)
Checking if you have JSON::XS 3.01 ... Yes (4.03)
Checking if you have Text::CSV 2.04 ... Yes (2.04)
Checking if you have ExtUtils::Config 0 ... Yes (0.008)
Checking if you have Net::OpenSSH 0 ... Yes (0.82)
Checking if you have NetAddr::MAC 0.93 ... Yes (0.98)
Checking if you have Authen::TacacsPlus 0 ... Yes (0.28)
Checking if you have Regexp::Common::net::CIDR 0 ... Yes (0.03)
Checking if you have NetAddr::IP 4.068 ... Yes (4.079)
Checking if you have Command::Runner 0 ... Yes (0.200)
Checking if you have namespace::clean 0.24 ... Yes (0.27)
Checking if you have Moo 1.001000 ... Yes (2.005004)
Checking if you have JSON::PP 0 ... Yes (2.97001)
Checking if you have Authen::Radius 0 ... Yes (0.32)
Checking if you have Sub::Util 1.40 ... Yes (1.63)
==> Found dependencies: Alien::poetry
Searching Alien::poetry (1.000006) on cpanmetadb ...
--> Working on Alien::poetry
Fetching http://www.cpan.org/authors/id/O/OL/OLIVER/Alien-poetry-1.000006.tar.gz
-> OK
Unpacking Alien-poetry-1.000006.tar.gz
Entering Alien-poetry-1.000006
Checking configure dependencies from META.json
Checking if you have Alien::Build::MM 0.25 ... Yes (2.83)
Checking if you have Alien::Build 2.83 ... Yes (2.83)
Configuring Alien-poetry-1.000006
Running Makefile.PL
Alien::Build::CommandSequence> +  sh -c 'exit 127' 
Alien::Build> error in probe (will do a share install): external command failed at /home/netdisco/perl5/lib/perl5/Alien/Build/CommandSequence.pm line 88.
Alien::Build> Don't panic, we will attempt a share build from source if possible.
Alien::Build> Do not file a bug unless you expected a system install to succeed.
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Alien::poetry
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Net::SSLeay 1.49 ... Yes (1.88)
Checking if you have URI 0 ... Yes (1.73)
Checking if you have File::ShareDir::Dist 0.07 ... Yes (0.07)
Checking if you have Path::Tiny 0.144 ... Yes (0.144)
Checking if you have Mozilla::CA 0 ... Yes (20160104)
Checking if you have IO::Socket::SSL 1.56 ... Yes (2.066)
Checking if you have Alien::Build::MM 0.25 ... Yes (2.83)
Checking if you have Alien::Build 2.83 ... Yes (2.83)
Checking if you have HTTP::Tiny 0.044 ... Yes (0.074)
Building Alien-poetry-1.000006
cp lib/Alien/poetry.pm blib/lib/Alien/poetry.pm
"/usr/bin/perl" -MAlien::Build::MM=cmd -e prefix site /home/netdisco/perl5/lib/perl5/x86_64-linux-thread-multi /home/netdisco/perl5/lib/perl5/x86_64-linux-thread-multi /home/netdisco/perl5/lib/perl5/x86_64-linux-thread-multi
main> prefix /home/netdisco/perl5/lib/perl5/x86_64-linux-thread-multi/auto/share/dist/Alien-poetry
"/usr/bin/perl" -MAlien::Build::MM=cmd -e version 1.000006
"/usr/bin/perl" -MAlien::Build::MM=cmd -e download
Alien::Build::Plugin::Core::Download> downloaded install-poetry.py
"/usr/bin/perl" -MAlien::Build::MM=cmd -e build
Alien::Build::Plugin::Extract::File> extracting /home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/download_UyX0 => /home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q
Alien::Build::Util> cp /home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/download_UyX0/install-poetry.py /home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py
Alien::Build::CommandSequence> +  sed -i -e 's/symlinks=False/symlinks=True/' \
Alien::Build::CommandSequence>            /home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py 
Alien::Build::CommandSequence> +  POETRY_HOME=/home/netdisco/perl5/lib/perl5/x86_64-linux-thread-multi/auto/share/dist/Alien-poetry \
Alien::Build::CommandSequence>            python3 /home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/install-poetry.py 
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/netdisco/perl5/lib/perl5/x86_64-linux-thread-multi/auto/share/dist/Alien-poetry/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.8.3)
Installing Poetry (1.8.3): Creating environment
Installing Poetry (1.8.3): Installing Poetry
Installing Poetry (1.8.3): An error occurred. Removing partial environment.
Poetry installation failed.
See /home/netdisco/.cpanm/work/1726474436.74607/Alien-poetry-1.000006/_alien/build_5M6q/poetry-installer-error-ictnf70d.log for error logs.
external command failed at /home/netdisco/perl5/lib/perl5/Alien/Build/CommandSequence.pm line 72.
make: *** [Makefile:957: _alien/mm/build] Error 1
-> FAIL Installing Alien::poetry failed. See /home/netdisco/.cpanm/work/1726474436.74607/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Alien::poetry' is not installed
-> FAIL Bailing out the installation for App-Netdisco-2.079001.

**Comment by ollyg** [comment]
Hi @alcatron what version of Python are you running?
you can run `python3 --version` to see it

**Comment by ollyg** [comment]
Hi! As mentioned in the release notes and install and upgrade docs, the
required version of Python is 3.9. Please upgrade and then it should work
fine.

Oliver.

**Comment by alcatron** [comment]
Installed:
  python39-3.9.19-7.module_el8.10.0+3885+d986a391.x86_64                              python39-libs-3.9.19-7.module_el8.10.0+3885+d986a391.x86_64                            
  python39-pip-20.2.4-9.module_el8.10.0+3765+2f9a457d.noarch                          python39-pip-wheel-20.2.4-9.module_el8.10.0+3765+2f9a457d.noarch                       
  python39-setuptools-50.3.2-6.module_el8.10.0+3885+d986a391.noarch                   python39-setuptools-wheel-50.3.2-6.module_el8.10.0+3885+d986a391.noarch                
  python39-wheel-wheel-1:0.35.1-4.module_el8.6.0+2780+a40f65e1.noarch                

Complete!

I upgraded to python 3.9 but it made no difference

[netdisco@almalinux8 ~]$ python3 --version
Python 3.6.8
[netdisco@almalinux8 ~]$ python3.9 --version
Python 3.9.19

 Still the same issue

Building Alien-poetry-1.000006 ... FAIL
! Installing Alien::poetry failed. See /home/netdisco/.cpanm/work/1726484029.85128/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Alien::poetry' is not installed
! Bailing out the installation for App-Netdisco-2.079001.

**Comment by psoppe** [comment]
As mentioned before (thanks ollyg) you need python >=3.9
On Oracle Linux I was able to do this with 

```shell
[root@server ~]# yum -y  install python3.12 
...
[root@server ~]# alternatives --config python3

There are 2 programs which provide 'python3'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/bin/python3.6
   2           /usr/bin/python3.12

Enter to keep the current selection[+], or type selection number: 2

``` 
one done this, the command

```shell
[netdisco@server ~]# ~/bin/localenv cpanm --notest App::Netdisco
``` 
completed successfully

**Comment by ollyg** [comment]
Many thanks @psoppe! I've added this to the install tips doc https://github.com/netdisco/netdisco/wiki/Install-Tips#python
