### ISSUE TITLE
Job queue filters empty

### ISSUE THREAD

**Issue by ralv3967** [netdisco/netdisco#1254]
The job queue filter fields are empty, the dropdown menu has no function (except for devices). Shouldn't the other fields also be filled with default values ​​via the menu?

Version: 
App::Netdisco 2.79.1
SNMP::Info 3.972.0
DB Schema 88
PostgreSQL 15.00.8
Perl / Python 5.36.0 / 3.11.2

**Comment by ollyg** [comment]
I cannot reproduce this bug. I suspect setting navbar_autocomplete may be disabled, which is a bug as it should not affect these autocomplete. I will address that.
