### ISSUE TITLE
Hook error on a specific device

### ISSUE THREAD

**Issue by Rodjeur70** [netdisco/netdisco#1259]
## Expected Behavior
Execute hook task after a discover action like for other same type devices.

## Current Behavior
Hook fails just for one device, no difference with other devices

## Possible Solution
No ided

## Steps to Reproduce (for bugs)
Trigger a discover action on the device, hook fails each time; on job queue, only this information is available:

"HTTP Hook: 599 Internal Exception "

Actually, no HTTP request is sent from server running Netdisco engine. No idea how to debug that further. Activate log in conf file does not provide more info.

## Context
Launch a external webservice task for a discovered device. Works fine with other device of same type and model.

## Your Environment
* Netdisco version used: 2.79.1
* SNMP::Info version used: 3.972.0

## Config info (deployment.yml)
hooks:
  - type: 'http'
    event: 'discover'
    with:
      url: 'https://XXX/webservice.php?ip=[% ip %]&os=[% os %]&engineid=[% snmp_engineid %]&action=discover'

## Device information
Extreme Networks 5520 under FabricEngine; same task works well with other identical devices

**Comment by ollyg** [comment]
hi @Rodjeur70 I would guess that one of the query string params which is substituted in the template is making the HTTP request explode. So that is the IP (unlikely), OS, and/or the SNMP Engine ID.

Perhaps try testing by changing the query to exclude those parameters? Or take a look at the values in the database and see if they're likely to make it die?

Or else share the data and I'll give an opinion.

**Comment by Rodjeur70** [comment]
Hi Ollyg,

Thx for your feedback. I've already checked values in database, nothing seems weired to me:
![image](https://github.com/user-attachments/assets/e1bfae78-dbd2-4462-80c2-1d5b53d1254a)
You can see here three identical switches just after well performed "discover" action. Following hook will fail only for one of these device, the second one in the list...

Rodjeur

**Comment by ollyg** [comment]
Hi again @Rodjeur70 
OK I don't have more ideas. While I suspect that "599 Internal Exception" comes from a remote server, if you're sure that no HTTP request is made, then I guess it comes from the HTTP library. You could set "log: 'debug'" in the config file and run the backend with just the hook job?

**Comment by Rodjeur70** [comment]
Ollyg,

I confirm that this specific hook does not throw from netdisco host whereas other http discover hook works well for same device. Activating log and restarting backend generate attached logs. I can't see something specific, but perhaps will you detect problem's cause.
[netdisco_backend_hook_error.txt](https://github.com/user-attachments/files/17569316/netdisco_backend_hook_error.txt)

Regards.

**Comment by ollyg** [comment]
Thanks @Rodjeur70. Looks like code 599 comes from the HTTP::Tiny Perl library and there's some info on it in the docs https://metacpan.org/pod/HTTP::Tiny. I could patch Netdisco to output the "content" field if it receives this error. Will update the ticket when done.

**Comment by ollyg** [comment]
Hi @Rodjeur70 please update to Netdisco 2.080002 when you can, and it should log the additional content field in the error log. Please share what it says.

**Comment by Rodjeur70** [comment]
Ho Ollyg,

Just updated my instance. Error is now:
[3567610] 2024-10-30 12:41:29 debug ⬅ (error) HTTP Hook: 599 Internal Exception (Wide character in request message body
)

Any suggestion to resolve this ?

**Comment by Rodjeur70** [comment]
I've just made some test, and forcing encoding of body into the HTTP request works:

$body = encode("UTF-8", $body);
my $response = $http->request(
   ($action_conf->{'method'} || 'POST'), $url,
   { headers => $action_conf->{'custom_headers'},
     content => $body },
);

in file /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Hook/HTTP.pm.

**Comment by ollyg** [comment]
Thanks! I'll put that in a patch soon as I can.

(What I realised is that the default body is the metadata of the Event, so it's got lots of stuff in there to go wrong!)

**Comment by Rodjeur70** [comment]
Yes indeed. Thanks for the top level support, as usual on this project !

Regards.

**Comment by ollyg** [comment]
Hi @Rodjeur70 I've just released version 2.080003 with this patch. I'll close the ticket but let me know if any further issues.
