### ISSUE TITLE
OID database

### ISSUE THREAD

**Issue by cnoyes72** [netdisco/netdisco#1261]
Hello,

  Is there a way to manually load the oid files into netdisco?  The automatic download method isn't working for me (our cybersecurity folks are being a bit over protective and won't whitelist the URL for the three OID files from github).

**Comment by ollyg** [comment]
Hi! yes the info I think you need is here:
https://github.com/netdisco/netdisco/wiki/Headless-Update

**Comment by cnoyes72** [comment]
Hello and thanks for the reply.  I see it loaded into manufacturer but oui is still empty (when I do a \d+ oui there are no entries).  Is there some other file I need to load?

**Comment by cnoyes72** [comment]
OK, I think I was mis-reading things.  All good now.  Thanks again for the help!

**Comment by ollyg** [comment]
Thanks for letting us know, glad all is well!

Yes it’s a bit confusing that the oui table is defunct, sorry it was a
distraction!
