### ISSUE TITLE
Columns in device port view CSV export are incorrectly aligned when "External Links" checked

### ISSUE THREAD

**Issue by rkerr** [netdisco/netdisco#1264]
When using the CSV export option in the device port view with "External Links" selected as a visible column the resulting CSV file has columns that are incorrectly aligned with the headings. It appears the heading for "External Links" is being added in a different place to the column containing that data. Probably depends what other columns you have set to display - but I'm seeing the column header for External Links appearing before the header for the VLAN related data, but the column containing that data being added after the columns containing VLAN related data.

**Comment by ollyg** [comment]
Hi @rkerr ! thanks for the bug report. This is fixed in 41d262b by not including any external links in the csv report.
