### ISSUE TITLE
Finding a Node in realtime.

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#13]
The ability to try and find a node on live data by
macsucking and walking the topology until a problem
node is found.

The motivation is that problem nodes may spring up
between mac sucks and can't be found by netdisco.

See thread at
http://sourceforge.net/mailarchive/message.php?msg\_id=10815928

Start off with a backend feature and maybe migrate to
front too?

-m

Reported by: maxslug-placeholder

Original Ticket: [netdisco/nd2-features/13](https://sourceforge.net/p/netdisco/nd2-features/13)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki
