### ISSUE TITLE
new statistics table

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#15]
I wanted to be able to view the stats information over time, number of devices, number of ports,etc.

I added a statistics table and moved some code around to add rows to it from a cron job with

\# do statistics at 1 minute after midnight
1 0 \* \* \*       /usr/local/netdisco/netdisco --statistics

Once I have enough data I'll work on adding more support for it in the frontend, perhaps with graphs.

Reported by: justin_a

Original Ticket: [netdisco/nd2-features/15](https://sourceforge.net/p/netdisco/nd2-features/15)

**Comment by ollyg** [comment]
Consider taking the opportunity to 'register' and lock backends in the DB, to get data on what they are doing and to prevent multiple instances per host.

**Comment by ollyg** [comment]
Implemented in commit 47bf385.
