### ISSUE TITLE
Commit switch changes to NVRAM 

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#16]
When netdisco makes a change to a port or device, such
as turns off the port or changes its VLAN the change is
not then commited to the NVRAM of the device.

Requires that SNMP::Info can issue the correct command
to tell the device to commit changes to NVRAM.

Some discussion and device support already done, need
to dig that up...

Reported by: maxslug-placeholder

Original Ticket: [netdisco/nd2-features/16](https://sourceforge.net/p/netdisco/nd2-features/16)

**Comment by ollyg** [comment]
Moved to wishlist page in the wiki
