### ISSUE TITLE
PING from workers / queue / poller enhancements

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#17]
Perhaps a good idea to show admins a little icon in the navbar that workers are online and doing/waiting-for jobs.

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/17](https://sourceforge.net/p/netdisco/nd2-features/17)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki

**Comment by ollyg** [comment]
ICMP scan of a prefix for discovery is now implemented
