### ISSUE TITLE
Native vlan display on untagged ports

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#172]
We have here H3C 55XX switchs ( hpA550052CEI).
On the port description in netdisco2 we have the column native VLAN which differs from vlan membership column on untagged ports.
We think for untagged port this information should be the same.

Details :
Switch version    : HP A5500-48G
Comware version   : 5.20.99 Release 2221P05
Netdisco2 SNMP:Info version : 3.18

Thks for your help

Reported by: lozair

Original Ticket: [netdisco/netdisco2/153](https://sourceforge.net/p/netdisco/netdisco2/153)

**Comment by ollyg** [comment]
Closing as user never replied, so unable to reproduce/fix.
