### ISSUE TITLE
Need to fake topology for thin AP on non-CDP device

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#179]
Thin AP's in a mixed environment Cisco AP only transmitting CDP to a non-CDP capable switches get picked up as a possible uplink because the AP's Ethernet MAC address is used as a controller port MAC address.

Possible fix is to flag controller port MAC's and fake L2 topology information so they are handled like thin AP's with usable L2 topology information.

This [mailing list discussion](https://sourceforge.net/p/netdisco/mailman/message/30232361/) provides the background on the use of the AP Ethernet MAC as a port MAC on the controller.

Reported by: jeneric-placeholder

Original Ticket: [netdisco/netdisco2/163](https://sourceforge.net/p/netdisco/netdisco2/163)

**Comment by ollyg** [comment]
The idea to flag Controller's port MAC is good, but Netdisco needs some metadata to be able to do that. Currently i_mac() doesn't let Netdisco know whether the interface MACs are genuine or synthesised. If Netdisco does get the metadata, it would be trivial to add a column to `device_port_properties` and then act on that in Macsuck::Nodes when setting is_uplink.

Of course all this comes about from a switch not running CDP/LLDP having an AP running CDP/LLDP. How likely is that?

**Comment by inphobia** [comment]
> Of course all this comes about from a switch not running CDP/LLDP having an AP running CDP/LLDP. How likely is that?

side note, perhaps relevant, perhaps not:
how does this work in mixed environments?

a very specific example:
aerohive access points transmit only lldp, but they can receive cdp & lldp. so it shows the switch as a cdp & lldp neighbour (our switches are running both cdp/lldp as send/receive) but on the switch side it only shows up as an lldp neighbour, it's nowhere to be found in the cdp neighbour table.

(also, aerohive access points currently don't have a defining layer3 mac address, perhaps that part of the issue)

**Comment by inphobia** [comment]
how much does #436 fix this & what is still missing?
