### ISSUE TITLE
Add SNMP trap-receiver

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#18]
A port that comes up might trigger a discovery for other devices attached to that port (maybe with a certain delay?).
In this context it might also make sense to have some message-pane / log-window that will show which port came up/went down, with crosslinks to the device/port etc.

Reported by: neufeind

Original Ticket: [netdisco/nd2-features/18](https://sourceforge.net/p/netdisco/nd2-features/18)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki

**Comment by olex777** [comment]
Are this case about snmp-traps was solved any of the ways? Where could I see it? Will be very thankfull for replay.

**Comment by JeroenvIS** [comment]
This case isn't about a bug, it's a suggestion to extend current functionality. Therefore the suggestion has been added to the "wishlist" page on the wiki. As far as I know, there is nobody working on this wish.

**Comment by djzort** [comment]
Perhaps create a script for SNMPTT -> http://snmptt.sourceforge.net/docs/snmptt.shtml#Executing-an-external-program

**Comment by olex777** [comment]
Thank you, I think it will be usefull!
