### ISSUE TITLE
Separate Web and Daemon dependencies somehow

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#19]
Would be nice to install Netdisco as web app only, or Poller Daemon only. One use case is where we don't have net-snmp around for compiling the perl bindings (e.g. have this problem on the Heroku demo site).

One way would be to use the cpanminus+Module::Install "features" feature. It's disliked by some, but seems to work well. Another way would be to have a set of metadata-only packages which specified different sets of dependencies.

What I think important is that the simplest thing does the most obvious - i.e. Installing App::Netdisco gives the whole shebang. Then there is some way to explicitly say "web" or "daemon".

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/21](https://sourceforge.net/p/netdisco/nd2-features/21)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki
