### ISSUE TITLE
netdisco-rancid-export grouplist

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#194]
Attached is a diff of my rancid-export script compared to the newest (netdisco 2.029014) version. I broke mine doing the update, but of course had backups. I also included a wrapper that I wrote that runs as root a few times a day

There are 2 main things and one minor thing here, one I'm not quite sure how to handle, but the others should be fairly straightforward. I have split this into three tickets
1) The most complex -- i have rancid.conf setup to set the rancid groups = `cat /home/rancid/var/netdiscogrouplist`
This allows rancid to always know which groups should exist based on the netdisco-rancid-export script (if you notice it writes a file with all the groups). Furthermore, i write another file in the same directory 'netdiscohostlist', which is appended to the /etc/hosts file. This allows netdisco to fully control what rancid sees and expects. I have attached my wrapper script that runs a few times a day to update the list. My hope is that this behavior can be handled by a config option (hostlist and grouplist with a default of rancidhome and the option to put elsewhere)

Reported by: mowlesta

Original Ticket: [netdisco/netdisco2/185](https://sourceforge.net/p/netdisco/netdisco2/185)

**Comment by ollyg** [comment]
Fixed in 2.038034 and https://metacpan.org/pod/App::Netdisco::Worker::Plugin::MakeRancidConf
