### ISSUE TITLE
netdisco-rancid-export name split mapping

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#195]
Attached is a diff of my rancid-export script compared to the newest (netdisco 2.029014) version. I broke mine doing the update, but of course had backups. I also included a wrapper that I wrote that runs as root a few times a day

There are 2 main things and one minor thing here, one I'm not quite sure how to handle, but the others should be fairly straightforward. I have split this into three tickets

2) Medium difficulty -- i have a 'namemap' that mimics the 'vendormap' that is now part of the config. I would like the namemap to be included as a config option. Basically, all of our network devices have 'devicetype-XXXXX' so that rancid can know what credentials to use for the device. Some of them work just fine, but we have edgerouters and vyatta/VyOS in production that do not report a proper vendor via SNMP. My solution was to just use the first part of the hostname, split by '-'. I would imagine a config option to list the mappings as well as the delimitor(s) would be sufficient. Might require a bit of extra code in the loop so that warnings don't get spit out... which somewhat leads me to part 3

Reported by: mowlesta

Original Ticket: [netdisco/netdisco2/186](https://sourceforge.net/p/netdisco/netdisco2/186)

**Comment by ollyg** [comment]
Fixed in 2.038034 and https://metacpan.org/pod/App::Netdisco::Worker::Plugin::MakeRancidConf
