### ISSUE TITLE
netdisco-rancid-export missing vendor behavior

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#196]
Attached is a diff of my rancid-export script compared to the newest (netdisco 2.029014) version. I broke mine doing the update, but of course had backups. I also included a wrapper that I wrote that runs as root a few times a day

There are 2 main things and one minor thing here, one I'm not quite sure how to handle, but the others should be fairly straightforward. I have split this into three tickets

3) easy -- i have fully embraced netdisco / rancid, and am using it in places that we probably shouldn't, but it works so damn well. We host our own phone systems (built on asterisk), and they are setup to do snmp, and I've built a rancid script to pull their *.conf files. The issue with this is similar to the edgerouters, etc, except they don't report a vendor at all. This makes it tricky to find / match for a vendor value so that rancid can do its thing. It might just be as simple as a default vendor value for devices that report nothing, but that is a bit short-sighted. For now i have a line that just says if their name is like 'RaTel', then it's a RaTel (the name we give to our phone systems) device. I'd love to know what your suggestion / solution is, as I can't figure a clean way to do it. Perhaps it is as simple as gettign the asterisk mibs loaded into netdisco?

Reported by: mowlesta

Original Ticket: [netdisco/netdisco2/187](https://sourceforge.net/p/netdisco/netdisco2/187)

**Comment by ollyg** [comment]
Fixed in 2.038034 and https://metacpan.org/pod/App::Netdisco::Worker::Plugin::MakeRancidConf
