### ISSUE TITLE
App::NetdiscoX::Web::Plugin::RANCID ignores by_ip directive in rancid configuration

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#197]
App::NetdiscoX::Web::Plugin::RANCID ignores by_ip directive in rancid configuration.

Expected behavior: %DEVICE% is replaced by the device's IP address
Actual behavior: %DEVICE% is replaced by the device's name

Example configuration snippet:
    extra_web_plugins:
      - X::RANCID
    plugin_rancid:
      location: 'http://path_to_websvn/%DEVICE%'
    rancid:
      by_ip: [ '.*' ]

Reported by: sthebig

Original Ticket: [netdisco/netdisco2/188](https://sourceforge.net/p/netdisco/netdisco2/188)

**Comment by ollyg** [comment]
Fixed in 2.038034 and https://metacpan.org/pod/App::Netdisco::Worker::Plugin::MakeRancidConf
