### ISSUE TITLE
Role Based Access Control

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#2]
It would be extremely useful to be able to add users to a groups, and then control what devices that group is able to view / alter through port control and device control. Personally, specifying devices by subnets would be most useful, and each user being able to exist within multiple groups.

Reported by: nobody

Original Ticket: [netdisco/nd2-features/2](https://sourceforge.net/p/netdisco/nd2-features/2)

**Comment by ollyg** [comment]
Moved to Wishlist page in wiki
