### ISSUE TITLE
Establish policy for timestamps in the DB

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#20]
18:05 < hotdogs> oliver: so I looked into the PG timestamp thing.  The default for timestamp is without timezone, so any dates put in are stored verbatim.  ND2 uses epoch time mostly (I found two calls to localtime that are for job times that can be fixed), so the queries get epoch time back out

18:09 < hotdogs> there's two ways to make it come back out in a timezone.  To make the DB do it, set a timezone in the DB/on  the DB session and change the selects to convert to the timestamp with timezone type.  For example, "select time_recent from node;" gets UTC times.  "select time_recent at time zone 'UTC' from node;" will convert it to  localtime in the DB

18:09 < hotdogs> alternatively, there's a DBIx::Class::InflateColumn::DateTime class that could do the timezone change in DBIC  instead

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/22](https://sourceforge.net/p/netdisco/nd2-features/22)

**Comment by ollyg** [comment]
Closed and moved to https://github.com/netdisco/netdisco/wiki/Wishlist
