### ISSUE TITLE
Tag to reference a list of subnets/IPs

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#22]
It would be nice if there was a way to create a list of IP addresses/subnets, add it a tag and use it in the configuration just by referencing that tag.

Reported by: fefa2k

Original Ticket: [netdisco/nd2-features/27](https://sourceforge.net/p/netdisco/nd2-features/27)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki

**Comment by ollyg** [comment]
This is now done! There are host_groups and host_group_displaynames settings, and ACLs support 'group:groupname'.
