### ISSUE TITLE
search devices by age

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#24]
In ND1 in report:inventory section you can select devices by age. 
[first discovered]
[last update]
[that have been up for at least]

I use those options quite often.
It could be useful if we can filter devices in [Device Search Options] using that fields
or
having age reports sorted by [first discovered] [last update] [that have been up for at least]

Reported by: marcom11

Original Ticket: [netdisco/nd2-features/25](https://sourceforge.net/p/netdisco/nd2-features/25)

**Comment by ollyg** [comment]
Implemented
