### ISSUE TITLE
change access vlan instead of native vlan

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#244]
when trying to change the vlan on a port I only see the ability to change the native vlan.  When we execute that from the web portal it sends the command "switchport trunk native vlan [vlan]" to our switches.  The ports I want to change are access ports. Can you point me in the direction of where this command is being generated from?  If I could just change this command to "switch access vlan [vlan]" it would be extremely helpful.

Reported by: jmihalow

Original Ticket: [netdisco/netdisco2/242](https://sourceforge.net/p/netdisco/netdisco2/242)

**Comment by dgeo** [comment]
Go for github ;)
still here to report more or testing. Sorry I'm missing Net::SNMP skills to PR here…

**Comment by ollyg** [comment]
So off the top of my head, what SNMP::Info could do is check whether the Cisco port is in access or trunk mode (and what about dynamic?), then set one or the other OID as appropriate.

**Comment by ollyg** [comment]
Hi @dgeo I hope you are still there :-)... at the moment Netdisco 2 will set *both* pvid and vlan (that is, native and access) when instructed to set a vlan ID on a port. Are you able to confirm this works?

Alternatively we have a less brute force method which is "set_i_untagged()" that attempts to work out whether to set pvid or vlan. We could try that instead.

**Comment by dgeo** [comment]
still there :)
Using netdisco 2.39.15 / SNMP::Info 3.49
I tested on IOS  15.2(2a)E1 and 12.2(55)SE12 on 2960G and 2960S devices
It seems working, though a bit dirty… I'll try to look at set_i_untagged() (if ever I understand something in…)
