### ISSUE TITLE
sidebar selections are not remembered

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#249]
Hi,

When searching on the device ports page there is a default set of selections checked in the sidebar. Unchecking a checkbox of de default selections is not remembered when searching a different switches device ports page. If you select more checkboxes in the sidebar they are remembered.
So if I uncheck for example the sidebar -> node properties -> ipv6 addresses then search for a different switch and go to the device ports page ipv6 addresses are checked again.
When I add a selection other then what is selected when at first then it is still checked when I look at at different devices ports page.
I noticed that a cookie is being stored at the client but maybe with wrong contents or it is not parsed.

Regards,

Frederik Reenders

Reported by: reendersf

Original Ticket: [netdisco/netdisco2/248](https://sourceforge.net/p/netdisco/netdisco2/248)

**Comment by alcatron** [comment]
anyone able to work on this , pretty please? :)

**Comment by ollyg** [comment]
Fixed! refactored all the sidebar params handling and it now seems to work. You can test git HEAD or wait for the next release.
