### ISSUE TITLE
Very high memory usage of netdisco-web-fg processes

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#253]
Hi,

I started using this a month ago.

It is a big network, but not a very big one. Here are the stats for this installation

327 devices with 22,233 interfaces using 1,443 IPs
4,668 layer 2 links between devices
12,853 nodes in 28,857 entries
12,298 IPs in 14,427 entries
Statistics took 1 seconds to process.

And here is the SW packages

Software	Version
App::Netdisco	2.033002
DB Schema	v40
Dancer	1.3142
Bootstrap	2.3.1
PostgreSQL	PostgreSQL 9.2.13 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit.
 DBI 1.634, DBD::Pg 2.19.3
SNMP::Info	3.28
Perl	5.016003

The application was working fine and very fast on a dual socket 6-core Xeon  E5-2620 v2 with 16 GB RAM.
But with time I noticed it was slowing down. And know it's sluggish.

For example if I click the port Tab for core switch with 415 interfaces with the following fields checkd
- Port
- Name
- Native Vlan
- Vlan Membership
- Connected Nodes
- Connected Devices
it takes more than 20 seconds.

When I started to debug the issue, I observed the following
- first there is a DB intensive stage which was reading aprox 18 MB/s (DB is on an Intel S3700 DC SSD)
- second, there is a CPU intensive stage of one the process named netdisco-web-fg

I realized that there is some sort of  history been stored which is causing the application to slow down with time. But what I found unacceptable is the very high memory consumption

When I fresh start the web front-end
$ ~/bin/netdisco-web restart
There are 6 proceses, 5 of which takes 43228 kB of RAM (RSS, Resident Set Size)

netdisco 30200  0.6  0.0 159892 10300 ?        S    18:19   0:00 starman master --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 30201  2.7  0.2 242628 43228 ?        S    18:19   0:00 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 30202  2.6  0.2 242628 43228 ?        S    18:19   0:00 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 30203  2.7  0.2 242628 43232 ?        S    18:19   0:00 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 30204  2.6  0.2 242628 43228 ?        S    18:19   0:00 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 30205  2.7  0.2 242628 43232 ?        S    18:19   0:00 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg

After querying the ports of the core switch I mentioned (with 415 interfaces) I noticed one which took 3640908 kB, which translates to 3555 MB !!!
If I repeat the query, some times another process responds and there goes anothe 3 GB of RAM

netdisco 28645  0.0  0.0 159892 10300 ?        S    18:00   0:00 starman master --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 28646  2.4 22.5 3909916 3640908 ?     S    18:00   0:19 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 28647  0.1  0.4 334188 67540 ?        S    18:00   0:00 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 28648  0.1  0.4 336380 69896 ?        S    18:00   0:01 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 28649  0.1  0.4 349952 74432 ?        S    18:00   0:01 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg
netdisco 28650  0.1  0.4 336664 70080 ?        S    18:00   0:01 starman worker --disable-keepalive --user 1003 --group 1003 /home/netdisco/perl5/bin/netdisco-web-fg

Am I doing something wrong? or this high memory consumption behaviour is to be expected?

Regards, Nicolás

Reported by: nmatsunaga

Original Ticket: [netdisco/netdisco2/252](https://sourceforge.net/p/netdisco/netdisco2/252)

**Comment by zito** [comment]
Hi, I'm playing with Netdisco for two weeks and it looks very promising
nice application.

    App::Netdisco 2.034002
    DB Schema 	v41
    Dancer	1.3202
    Bootstrap 	2.3.1
    PostgreSQL 	PostgreSQL 9.6.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-6) 6.3.0 20170205, 64-bit. DBI 1.636, DBD::Pg 3.5.3
    SNMP::Info 	3.34
    Perl	5.024001

I did an upgrade of system to Debian GNU/Linux Stretch (testing) to get newer
packages. Network stat:

    61 devices with 4,078 interfaces using 490 IPs
    251 layer 2 links between devices
    3,063 nodes in 11,165 entries
    4,138 IPs in 6,279 entries
    Statistics took 0 seconds to process.

We have replaced many hardware in our network last year. There are many HA
devices and many redundant links.
Problem is displaying ports of devices. I had OOM killer many times in action
and end up with 8GiB RAM for VM running Netdisco to not end with out of memory.
To be more precise the device with many up-links has this problem.

The query for displaying ports result set is really the issue. Postgresql
logged the query:

    SELECT me.ip, me.port, me.creation, me.descr, me.up, me.up_admin, me.type, me.duplex, me.duplex_admin, me.speed, me.name,
		me.mac, me.mtu, me.stp, me.remote_ip, me.remote_port, me.remote_type, me.remote_id, me.is_master, me.slave_of,
		me.manual_topo, me.is_uplink, me.vlan, me.pvid, me.lastchange,
		me.up != 'up' and age(now(), to_timestamp(extract(epoch from device.last_discover) - (device.uptime - me.lastchange)/100)) > '3 mons'::interval,
		(SELECT COUNT( * ) FROM device_port_vlan dpv WHERE ( ( dpv.ip = me.ip AND dpv.port = me.port ) )),
		agg_master.up_admin, agg_master.up, all_port_vlans.ip, all_port_vlans.port, all_port_vlans.vlan,
		all_port_vlans.native, all_port_vlans.creation, all_port_vlans.last_discover, all_port_vlans.vlantype,
		active_nodes.mac, active_nodes.switch, active_nodes.port, active_nodes.active, active_nodes.oui,
		active_nodes.time_first, active_nodes.time_recent, active_nodes.time_last, active_nodes.vlan, ips.mac,
		ips.ip, ips.dns, ips.active, ips.time_first, ips.time_last, wireless.mac, wireless.uptime, wireless.maxrate,
		wireless.txrate, wireless.sigstrength, wireless.sigqual, wireless.rxpkt, wireless.txpkt, wireless.rxbyte,
		wireless.txbyte, wireless.time_last, wireless.ssid, netbios.mac, netbios.ip, netbios.nbname, netbios.domain,
		netbios.server, netbios.nbuser, netbios.active, netbios.time_first, netbios.time_last, neighbor_alias.ip,
		neighbor_alias.alias, neighbor_alias.subnet, neighbor_alias.port, neighbor_alias.dns, neighbor_alias.creation,
		device_2.ip, device_2.creation, device_2.dns, device_2.description, device_2.uptime, device_2.contact,
		device_2.name, device_2.location, device_2.layers, device_2.ports, device_2.mac, device_2.serial,
		device_2.model, device_2.ps1_type, device_2.ps2_type, device_2.ps1_status, device_2.ps2_status, device_2.fan,
		device_2.slots, device_2.vendor, device_2.os, device_2.os_ver, device_2.log, device_2.snmp_ver, device_2.snmp_comm,
		device_2.snmp_class, device_2.vtp_domain, device_2.last_discover, device_2.last_macsuck, device_2.last_arpnip
	FROM device_port me
		JOIN device device ON device.ip = me.ip
		LEFT JOIN device_port agg_master ON ( agg_master.ip = me.ip AND agg_master.port = me.slave_of )
		LEFT JOIN device_port_vlan all_port_vlans ON ( all_port_vlans.ip = me.ip AND all_port_vlans.port = me.port )
		LEFT JOIN (
	          SELECT * FROM node WHERE active
		        ) active_nodes ON ( active_nodes.port = me.port AND active_nodes.switch = me.ip )
		LEFT JOIN node_ip ips ON ( ips.active = active_nodes.active AND ips.mac = active_nodes.mac )
		LEFT JOIN node_wireless wireless ON wireless.mac = active_nodes.mac
		LEFT JOIN node_nbt netbios ON netbios.mac = active_nodes.mac
		LEFT JOIN device_ip neighbor_alias ON neighbor_alias.ip = (SELECT devipsub.ip FROM device_ip devipsub WHERE ( alias = me.remote_ip ) LIMIT 1)
		LEFT JOIN device device_2 ON device_2.ip = neighbor_alias.ip
	WHERE ( me.ip = '<IPADDRESS>' )
	ORDER BY active_nodes.vlan, active_nodes.mac, ips.ip;

and the result set after minute had 608463 rows :-/. The web application end
with error. I ran it by hand from psql into text file:

  netdisco@netdisco:~$ ll -h sw-prg-srv02.ports.res.txt
  -rw-r--r-- 1 netdisco netdisco 805M Mar 23 17:02 sw-prg-srv02.ports.res.txt

I know nothing about application abstraction layers for sql query construction,
but this query is probably noway :(.

Regards 
Zito

**Comment by kenfire** [comment]
I had the same issue (CPU load at 100% used by netdisco-web process & web page inaccessible) and this command resolve it:
```bash
~netdisco/bin/localenv cpanm --notest Dancer::Debug
```

I found it here: https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Troubleshooting.pod#Debug-HTTP-Requests-and-Configuration

From what I saw, I think it has downloaded perl depencecies that were not installed

HTH

**Comment by ollyg** [comment]
@kenfire which dependencies did it download that were not installed? Do you have the log from the command line when you installed Dancer::Debug?

**Comment by kenfire** [comment]
@ollyg I searched for logs in netdisco-web.log and found multiple errors:

> Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: Can't locate Plack/Middleware/Debug.pm in @INC (you may need to install the Plack::Middleware::Debug module) (@INC contains: /home/netdisco/site_plug
ins /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /home/netdisco/perl5/lib /home/netdisco/perl5/bin/lib /home/netdisco/perl5/lib/perl5/5.18.2/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/
lib/perl5/5.18.2 /home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr
/lib/perl/5.18 /usr/share/perl/5.18 /home/netdisco/perl5/lib/perl5/5.18.1 /usr/local/lib/site_perl .) at /home/netdisco/perl5/lib/perl5/Plack/Util.pm line 26.
[8928] 2017-09-20 14:07:44  warn App::Netdisco 2.036009 web
Child process 8826 exited with status 2

> Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: Can't locate Plack/Middleware/Debug.pm in @INC (you may need to install the Plack::Middleware::Debug module) (@INC contains: /home/netdisco/site_plug
ins /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /home/netdisco/perl5/lib /home/netdisco/perl5/bin/lib /home/netdisco/perl5/lib/perl5/5.18.2/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/
lib/perl5/5.18.2 /home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr
/lib/perl/5.18 /usr/share/perl/5.18 /home/netdisco/perl5/lib/perl5/5.18.1 /usr/local/lib/site_perl .) at /home/netdisco/perl5/lib/perl5/Plack/Util.pm line 26.
Child process 8866 exited with status 2

>Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: Can't locate Plack/Middleware/Debug/Dancer/Settings.pm in @INC (you may need to install the Plack::Middleware::Debug::Dancer::Settings module) (@INC 
contains: /home/netdisco/site_plugins /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /home/netdisco/perl5/lib /home/netdisco/perl5/bin/lib /home/netdisco/perl5/lib/perl5/5.18.2/x86_64-linux-gnu-
thread-multi /home/netdisco/perl5/lib/perl5/5.18.2 /home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /u
sr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /home/netdisco/perl5/lib/perl5/5.18.1 /usr/local/lib/site_perl .) at /home/netdisco/perl5/lib/perl5/Plack/Util.pm line 26.

From what I remember I suspect the first error: Plack::Middleware::Debug module

**Comment by ollyg** [comment]
I've added the missing dependencies, thanks.

**Comment by kenfire** [comment]
Glad that helped :)
