### ISSUE TITLE
Add functionality to color nodes by device layer.

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#28]
We have enhanced the frontend to be able to color nodes by its layer. So it is possible to give layer-2 devices a different color than layer-3 devices.
For example: 
node\_map       = devlayer:110$:fillcolor:peru:dev-cat:Router
node\_map       = devlayer:011$:fillcolor:limegreen:dev-cat:Switching Hub

See attached patch.

Reported by: mborgelt

Original Ticket: [netdisco/nd2-features/30](https://sourceforge.net/p/netdisco/nd2-features/30)

**Comment by ollyg** [comment]
It is now possible to do this using host groups config and the new netmap.
