### ISSUE TITLE
Sidebar support for report plugins

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#29]
Reported by: ollyg

Original Ticket: [netdisco/nd2-features/31](https://sourceforge.net/p/netdisco/nd2-features/31)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki

**Comment by ollyg** [comment]
use the bind params option and create fields from it

**Comment by ollyg** [comment]
implemented in 653ea75
