### ISSUE TITLE
Problem with port numbering on Avaya 49xx

### ISSUE THREAD

**Issue by erics69** [netdisco/netdisco#292]
The discover of new Avaya ERS49xx's stacks results in wrong port numbering: unit 1 has 1.x port number format, but unit #2 has 3.x, unit #3 has 5.x, and so on.

## Your Environment

* Netdisco version used: 2.034002
* SNMP::Info version used: 3.34
* Avaya ERS4950GTS-PWR+: fw 7.2.0.5, sw 7.2.0.213

**Comment by jl84** [comment]
Hi,

This is probably due to Avaya releasing the ERS 59100GTS switch model with 100 ports so the port indexing   gets wierd but yeah I have the same issue which is quite annoying and I already made a config mistake because of it :)

/Johan
