### ISSUE TITLE
Heroku Demo is broken

### ISSUE THREAD

**Issue by djzort** [netdisco/netdisco#293]
http://netdisco2-demo.herokuapp.com/ 

seems broken.

**Comment by ollyg** [comment]
I got a message from Heroku about changes to the PostgreSQL setup, that I should probably go and act on. I suspect the DB has gone away and needs restoring.

**Comment by djzort** [comment]
perhaps we can just set up a demo on cloudatcost.com cloud?

**Comment by ollyg** [comment]
It's back up and running!
