### ISSUE TITLE
Access Point Client Count report gets empty when macsuck is run by WWW GUI for Cisco WLC

### ISSUE THREAD

**Issue by jnovak-netsystemcz** [netdisco/netdisco#296]
I use Netdisco 2 and it collected whole network without any problems.
  We use Cisco Wireless Controller (WLC) (reported as cisco/AIR-CT2504-K9,
SNMP::Info::Layer2::Airespace) in network. I found that Access Point
Client Count report is empty all the time even WLC shows connected clients.

## Expected Behavior
  I expect that system will collect correct list of clients on WLC every run.

## Current Behavior
  I checked it and found that when I run ~/bin/netdisco-do macsuck -d
<WLC_IP> from command line, report is filled correctly. But records
disappears when scheduler runs macsuck for same host. When I run macsuck
with WWW GUI for host, records disappear too. I can put records back
when I run macsuck from CLI again.
  I checked netdisco-daemon.log and I see that when macsuck runs for WLC
host, it reports 0 found addresses. But when I run it with netdisco-do
-D from CLI, it reports correct count of found addresses.
  I checked snmp communication for both cases and I see that WLC
responds same way with same list of connected clients for both runs.

  Later I found that when I restart netdisco-daemon, clients are shown for a few subsequent macsuck runs (manually initiated by GUI or scheduled). But later it again starts to collect 0 clients.

  I debug code up to:
App/Netdisco/Core/Macsuck.pm
  -> _walk_fwtable()
    -> $fw_mac = $snmp->fw_mac
  -> SNMP/Info/Airespace.pm: sub fw_mac ...

  and found that when I see 0 clients, fw_mac() call returns empty list even SNMP response from WLC was including values.
  As mentioned above, when I restart netdisco-daemon, a few runs of code above returns correct list and then it starts to return empty list again.

## Possible Solution
  I have no idea why it behaves as I see it. But behaving was confirmed on every my system with WLC and was confirmed by other users in netdisco-users list (see thread 'Access Point Client Count report gets empty when macsuck is run by WWW GUI').
  One of my ideas is that SNMP code caches responses from SNMP for a thread/process - when same thread/process asks for same SNMP host, it doesn't process it fully. The reason for this idea is that when I have system with more CPUs/cores, netdisco starts more workers and I see correct outputs for longer time/count of macsuck runs. The count of correct runs after netdisco-daemon restarts is higher on systems with more CPUs/cores. But it might be a coincidence.

## Steps to Reproduce (for bugs)
1. Configure netdisco to discover WLC (or restart netdisco-daemon when WLC is already there)
2. Check that WLC was queried for MAC adresses
3. Run Reports->Wireless->Access Point Client Count
4. You should see one or more lines where (only relevant columns are mentioned):
Device: WLC name
Port: One of APs controlled by WLC
SSID: One of SSIDs configured on WLC/AP
Node Count: Count of clients on AP connected with SSID
5. Show device WLC in netdisco (by clicking on it or by search of its IP address)
6. Run Macsuck from GUI many times (probably more times than count of workers)
7. Check same report - it is empty (do not contain any line for WLC)

Note: When you have WLC and standalone APs in system, report will show standalone AP related lines. The issue is with WLC related lines only.

## Context
See above.

I can provide more logs/debugs when requested.

## Your Environment
Software 	Version
App::Netdisco 	2.034002
DB Schema 	v41
Dancer 	1.3202
Bootstrap 	2.3.1
PostgreSQL 	PostgreSQL 9.2.18 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit.
 DBI 1.636, DBD::Pg 2.19.3
SNMP::Info 	3.34
Perl 	5.016003

**Comment by ollyg** [comment]
The poller workers in the daemon should restart at sometime between one and two days of life:
https://github.com/netdisco/netdisco/blob/master/Netdisco/lib/App/Netdisco/Daemon/Worker/Common.pm#L43
This is because we had memory leaks before that we could never track down. Restarting is a lazy fix.

I wonder whether editing this to exit() at each poll would be a good test, to see where the issue lies. Could also switch to exiting after a number of poll jobs if we can cache that count in the worker itself.

(Obviously, the amount of work a poller does during its lifetime is dependent on the size of the network being polled - it might be busy or not.)

**Comment by ollyg** [comment]
... do we get "recycling worker X" messages in the logs? could this feature be broken and the error reported related to running out of memory?

**Comment by rc9000** [comment]
I'm trying an exit() after every poll now, I'll let you guys know in a few days if it changed anything.

It could very well be a memory issue. The tables coming from our Airespace devices are huge, so it would make sense that this is the first class of devices we notice it on.

**Comment by rc9000** [comment]
So I had this running for a bit and can confirm that it makes the problem go away. The exact change I used is:

    -- diff Common.pm Common.pm.dist
    44c44,51
    <       $self->exit(0, "aggressively recycling worker $wid");
    ---
    >       # restart worker once a day.
    >       my $hour = [localtime()]->[2];
    >       if ($wid) {
    >           if ((time >= ($self->{started} + 86400) and $hour == ($wid % 24))
    >                or (time > ($self->{started} + 172800))) {
    >               $self->exit(0, "recycling worker $wid");
    >           }
    >       }

In our environment, the average worker jobs seems to take around 20 seconds (from macsuck/arpnip/discover combined), so I wouldn't lose sleep about using this as the final solution - doesn't seem like an unreasonably short process lifetime. But of course if someone is able to find the effective cause that would be even better.

**Comment by jnovak-netsystemcz** [comment]
Hello,

> So I had this running for a bit and can confirm that it makes the
> problem go away. The exact change I used is:

  I monitored our system with similar patch and I confirm it as workaround.

						Sincerely yours,

							Jirka Novak

**Comment by ollyg** [comment]
Thanks both @jnovak-netsystemcz and @rc9000 I really appreciate the testing!

I have applied a small patch to restart the worker after each poll job, and this will be in the next release. I don't think it will reduce performance much (the process is network-io bound over everything else).

**Comment by jnovak-netsystemcz** [comment]
Hello,

  I found one my system with patch applied overloaded. The reason was
that one worker was planned round and round and was killed by patch.
  Therefore I propose attached patch. It has two advantages:
1) dies only macsucks process where we identified the issue
2) there is emergency sleep just for a case

					Sincerely yours,

							Jirka Novak

**Comment by ollyg** [comment]
Hi Jirka, I don't think the email attachment arrived in Github. I guess you have to log in and drop it into the comments field, or you can email the file to me (oliver at cpan dot org).

**Comment by jnovak-netsystemcz** [comment]
Hello,

there is patch. Sleep for 2s included in patch is based on my experience. 1s was too low on my system...

Sincerely yours,

Jirka Novak

[Common.pm.diff.txt](https://github.com/netdisco/netdisco/files/816309/Common.pm.diff.txt)

**Comment by ollyg** [comment]
Hi Jirka,

I don't fully understand the need for your patch. The aggressive exit() only applies to poller jobs (macsuck, arpnip, discover, expiry, NBTstat) and these jobs can run once then die. The long lived workers (scheduler and manager) are unaffected.

What is the two second sleep achieving? Do you have another type of custom poller which you want to be protected?

Thanks, Oliver.

**Comment by jnovak-netsystemcz** [comment]
Hi Oliver,

> I don't fully understand the need for your patch. The aggressive exit()
> only applies to poller jobs (macsuck, arpnip, discover, expiry, NBTstat)
> and these jobs can run once then die. The long lived workers (scheduler
> and manager) are unaffected.
> 
> What is the two second sleep achieving? Do you have another type of
> custom poller which you want to be protected?

There are two points:
1) Limit aggressive exit to only case we found - macsuck
This is reason why I added "if" branch

2) I found that one of my systems with netdisco is overloaded (100% CPU
load) by netdisco when I applied original patch. I found that reason is
that process is exit() at mentioned place, then created, exit() etc. I'm
afraid it is some misconfiguration or other reason. On the other hand
sleep() solved it.
So my idea is to "share" this experience. But sleep() is probably
useless for others.

Does it make sense to you?

						Sincerely yours,

							Jirka Novak

**Comment by ollyg** [comment]
Hi Jirka, thanks for taking the time to explain.

I've implemented the sleep as a configuration option, so you can set the time to 2 seconds on your system but it will default to 0. The setting you'll need is:

    workers:
      min_runtime: 2

regards,
oliver.
