### ISSUE TITLE
Users management unusable when utf-8 character in fullname

### ISSUE THREAD

**Issue by jas01** [netdisco/netdisco#299]
## Expected Behavior

Make the web gui working when some one enter a fullname with UTF-8 character.

## Current Behavior

When entering a fullname with UTF-8 character the submenu

    Admin --> User Management

crashes with this error message:

    Search failed! Please contact your site administrator.

We find this message inside the log:

    [12473] 2017-03-01 17:11:20 error request to GET /ajax/content/admin/users crashed: core - template - undef error - Malformed UTF-8 character (fatal) at /usr/local/lib/perl5/site_perl/mach/5.24/HTML/Entities.pm line 462.

and

    error running job: DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(): Unexpected populate error: Wide character in subroutine entry at /usr/local/lib/perl5/site_perl/mach/5.24/DBI.pm line 2020, <__ANONIO__> line 5. at /usr/local/lib/perl5/site_perl/App/Netdisco/Core/Discover.pm line 646

## Steps to Reproduce (for bugs)

1. Create a user with a fullname with utf-8 character (example: Benoît Martin)
2. Click on the menu « Admin --> User Management »

## Your Environment

App::Netdisco 	2.034002
DB Schema 	v41
Dancer 	1.3202
Bootstrap 	2.3.1
PostgreSQL 	PostgreSQL 9.3.16 on amd64-portbld-freebsd11.0, compiled by FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0), 64-bit.
 DBI 1.636, DBD::Pg 3.5.3
SNMP::Info 	3.34
Perl 	5.024001

We use the freebsd port package.

**Comment by ollyg** [comment]
Hi, I have been unable to reproduce this error, sorry.

I wonder whether it's an issue with the BSD port. Would you be willing to create a user on your system and run through the local install from our docs, to see if that works? You can point it at the same database and not start the backend.

https://metacpan.org/pod/App::Netdisco

    =# select fullname from users where fullname is not null; 
    fullname    
    ---------------
    Benoît Martin  
    (1 row)

Many thanks,
Oliver.
