### ISSUE TITLE
Pinnaces/Patch-Bay System Integration

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#3]
Would be awesome to have a standardized way to integrate external patch bay systems such as the famous Pinnacles (or the Brother P-Touch thingy used at ECMWF).

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/3](https://sourceforge.net/p/netdisco/nd2-features/3)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki.
