### ISSUE TITLE
Enhancement: Would like to be able to modify the Module Inventory report to add a column (IP Address of Module host)

### ISSUE THREAD

**Issue by ThatOneRoadie** [netdisco/netdisco#300]
## Possible Solution

Addition of a custom column, or editing the report file to add a column for Module IP address

## Context

In performing an inventory of physical switch hardware on multiple stacked devices, we can either get hostnames and IP addresses of logical devices (Stacks) via the devices report, or the report of physical switches in the environment (via module inventory report), but not both at the same time. Would like the ability to audit all switch hardware by module while still showing IP address.

## Your Environment

* Netdisco version used: 2.034002
* SNMP::Info version used: 3.34

Thanks Oliver (and others) for the help!

**Comment by ollyg** [comment]
Off the top of my head, the simplest approach is to modify the template for the existing report to include an IP address column. This could be done by:

1. tell netdisco to look in a new path for templates
2. copy the existing template for the report, and add the column
3. put the modified template in the path from step (1)

The downside is that step (1) is a bit of a faff, and it's a bit of a hack, but less effort than a completely new report.

How does that sound? I can fill in the details if you confirm.

**Comment by ThatOneRoadie** [comment]
A bit of a hack works, we're just looking for an easier inventory report for just this audit (nothing permanent). Let me know what needs to be changed and where.

**Comment by ollyg** [comment]
okay, let's do this...

1. create a directory `~netdisco/site_plugins/App/NetdiscoX/Web/Plugin`
1. create a file in that directory called `LocalModuleInventory.pm` with the following content:
    `package App::NetdiscoX::Web::Plugin::LocalModuleInventory;`
    `use App::Netdisco::Web::Plugin;`
    `register_template_path('/home/netdisco/templates');`
    `1;`
1. create a directory `~netdisco/templates/share/views/ajax/report`
1. Copy [this file](https://raw.githubusercontent.com/netdisco/netdisco/master/Netdisco/share/views/ajax/report/moduleinventory.tt) to the "report" directory created in the previous step.
1. Edit `moduleinventory.tt` (see discussion below)
1. Add the following to your `~/environments/deployment.yml` (where `<space>` is whitespace):
    `extra_web_plugins:`
    `<space><space>  - 'X::LocalModuleInventory'`

OK, so take a look at `moduleinventory.tt` and you can edit the existing "Device" column to force it to be the IP address (see [this line](https://github.com/netdisco/netdisco/blob/master/Netdisco/share/views/ajax/report/moduleinventory.tt#L42)).

Or you could add a new IP column after the Device column by adding a `thead` entry at the top and the DataTables entry further down for the rows (give it a unique "data" name).

Good luck!
