### ISSUE TITLE
implement full text search

### ISSUE THREAD

**Issue by bhuddah** [netdisco/netdisco#302]
The search field states "Find Anything".

## Expected Behavior
When you enter a piece of information in the search bar all available data is searched and results are found.

## Current Behavior
several types of information are simply not searchable.
e.g. serial numbers of modules and sfp's

## Possible Solution
implement general full text search

## Steps to Reproduce (for bugs)

1. search for serial number
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 2.034002
* SNMP::Info version used: 3.34

**Comment by ollyg** [comment]
Hello, and thanks for the report! Unfortunately a true full text search on the many fields of data that Netdisco stores would be too expensive for the database (we do not have anything like elasticsearch).

However, I took your mention of the search for module/component search numbers and implemented that, which will be in the next release.Thank you!

Oliver.
