### ISSUE TITLE
Display ip inventory

### ISSUE THREAD

**Issue by kpal38** [netdisco/netdisco#304]
App::Netdisco: 	2.034001
DB Schema: v41
Dancer: 1.3202
Bootstrap: 2.3.1
PostgreSQL 9.4.11
SNMP info: 3.34
Perl: 5.016003

I do IP inventory on my subnet: 172.30.114.0/24 with List IP's Never Seen checked.

In inventory I don't see all IP.
Example:  On screenshot, IP 172.30.112.99 ; 172.30.112.104 ; 172.30.112.105 ; 172.30.112.106 ; 172.30.112.107 ; 172.30.112.108 ; 172.30.112.111   does not appears.

![2017-04-12 11_29_42-sans titre - paint](https://cloud.githubusercontent.com/assets/15361791/24951251/0cde8248-1f74-11e7-9f3e-4b7ce948ddbd.png)

It's a bug ?

Thank you for response

**Comment by ollyg** [comment]
Hi, do you have a date filter set? The missing IPs might have been seen but outside of the date filter. Try ticking the "not within" box to see if they appear.

**Comment by kpal38** [comment]
Thank you for response, it's ok now, it was effectively date filter.

**Comment by ollyg** [comment]
Super, thanks for the confirmation.
