### ISSUE TITLE
Not an ARRAY reference at SNMP.pm module when netdisco-do -D discover is issued

### ISSUE THREAD

**Issue by ageld** [netdisco/netdisco#305]
~/bin/netdisco-do -D discover -d 192.168.5.1 command

fails with the following error: 

[16259] 2017-04-19 19:18:07  info discover: started at Wed Apr 19 19:18:07 2017
[16259] 2017-04-19 19:18:07  info discover: finished at Wed Apr 19 19:18:07 2017
[16259] 2017-04-19 19:18:07  info discover: status error: error running job: Not an ARRAY reference at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/SNMP.pm line 278.

By utilizing tcpdump, I can see that the command triggers no SNMP communication with the target.

How can I fix the issue?

Thanks a lot for your help!

## Context

I am trying to replace a very old version of Netdisco installed on the different system.

## Your Environment
I am running Ubuntu 14.04.  

I followed the installation procedure outlined here:

https://metacpan.org/pod/App::Netdisco#Installation

SNMP related packages on the system:

dpkg -l | grep -i snmp
ii  erlang-snmp                               1:16.b.3-dfsg-1ubuntu2.1                   i386         Erlang/OTP SNMP applications
ii  libnet-snmp-perl                          6.0.1-2                                    all          Script SNMP connections
ii  libsnmp-base                              5.7.2~dfsg-8.1ubuntu3.2                    all          SNMP configuration script, MIBs and documentation
ii  libsnmp-info-perl                         3.11-1                                     all          Object Oriented Perl5 Interface to Network devices and MIBs through SNMP
ii  libsnmp-perl                              5.7.2~dfsg-8.1ubuntu3.2                    i386         SNMP (Simple Network Management Protocol) Perl5 support
ii  libsnmp-session-perl                      1.13-1.1                                   all          Perl support for accessing SNMP-aware devices
rc  libsnmp15                                 5.4.3~dfsg-2.4ubuntu1.3                    i386         SNMP (Simple Network Management Protocol) library
ii  libsnmp30:i386                            5.7.2~dfsg-8.1ubuntu3.2                    i386         SNMP (Simple Network Management Protocol) library
ii  nagios-snmp-plugins                       1.1.1-8                                    all          SNMP Plugins for nagios
ii  snmp                                      5.7.2~dfsg-8.1ubuntu3.2                    i386         SNMP (Simple Network Management Protocol) applications

**Comment by ollyg** [comment]
Hi, this is probably caused by a configuration file (deployment.yml) syntax error. The snmp config needs to be a list. Are you able to paste it here or on pastie.org without sharing secrets? Thanks.

**Comment by ageld** [comment]
Thanks a lot for your fast reply.

This is how SNMP defined in deployment.yml (strings are bogus)

# SNMP community string(s)
# ````````````````````````
snmp_auth:
  community: "teststring"
  community_rw: "teststring-write"

**Comment by ageld** [comment]
I also tried the following configuration as it was shown as an example in the file itself:

snmp_auth:
  - tag: 'readonly'
   community: 'teststring'
   read: true
   write: false

but when executing ~/bin/netdisco-do -D discover -d 192.168.5.1 command  it gave me compilation errors:

Unable to parse the configuration file: /home/netdisco/environments/deployment.yml: YAML::XS::Load Error: The problem:

    did not find expected '-' indicator

was found at document: 1, line: 35, column: 4
while parsing a block collection at line: 34, column: 3
 at /home/netdisco/perl5/lib/perl5/Dancer/Config.pm line 231.
        Dancer::Config::load_settings_from_yaml('/home/netdisco/environments/deployment.yml') called at /home/netdisco/perl5/lib/perl5/Dancer/Config.pm line 209
        Dancer::Config::load('Dancer::Config') called at /home/netdisco/perl5/lib/perl5/Dancer.pm line 274
        Dancer::import('Dancer', ':script') called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Configuration.pm line 4
        App::Netdisco::Configuration::BEGIN() called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Configuration.pm line 4
        eval {...} called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Configuration.pm line 4
        require App/Netdisco/Configuration.pm called at /home/netdisco/perl5/lib/perl5/App/Netdisco.pm line 8
        App::Netdisco::BEGIN() called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Configuration.pm line 4
        eval {...} called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Configuration.pm line 4
        require App/Netdisco.pm called at /home/netdisco/bin/netdisco-do line 37
        main::BEGIN() called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Configuration.pm line 4
        eval {...} called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Configuration.pm line 4
BEGIN failed--compilation aborted at /home/netdisco/perl5/lib/perl5/App/Netdisco/Configuration.pm line 4.
Compilation failed in require at /home/netdisco/perl5/lib/perl5/App/Netdisco.pm line 8.
BEGIN failed--compilation aborted at /home/netdisco/perl5/lib/perl5/App/Netdisco.pm line 8.
Compilation failed in require at /home/netdisco/bin/netdisco-do line 37.
BEGIN failed--compilation aborted at /home/netdisco/bin/netdisco-do line 37.

**Comment by ageld** [comment]
I think I figured it out.  Thanks a lot for pointing me to the right direction.  The final config is:
#snmp_auth:
community:
- teststring
community_rw:
- teststring-write

It seemed to be working now.

**Comment by ollyg** [comment]
Super, thanks for the confirmation!
