### ISSUE TITLE
Ability to disable switch ports via Netdisco

### ISSUE THREAD

**Issue by ageld** [netdisco/netdisco#308]
The previous incarnation of Netdisco provided me with an ability to remotely shutdown ports.  

I do not see this option in this version of the software

## Expected Behavior

Find the host in question -> track it to specific switch/port -> browse the port status -> click on disable port -> input log entry about the reason the port is being administratively shutdown

## Current Behavior

Find the host in question -> track it to specific switch/port -> browse the port status -> (There is no option to disable /administratively shutdown/ a port

## Possible Solution

Is this feature no longer offered?

## Context

Our help desk utilized previous incarnation of Netdisco to remotely disconnect computers possibly infected with malware

## Your Environment

* Netdisco version used:  Latest
* SNMP::Info version used:  Latest (I have just installed the software)
* Operating system: Ubuntu 14.04

**Comment by ollyg** [comment]
Hi, if you assign the user "Port Control" rights in Admin -> User Management, and then in the right hand sidebar of Device Ports page you tick "Port Control" box, there will be icons to disable/enable switchports.
