### ISSUE TITLE
csv download of vlan mismatch report broken

### ISSUE THREAD

**Issue by bhuddah** [netdisco/netdisco#309]
When clicking on the csv download button on the portvlanmismatch page you download something that looks like a slice of html page and not a csv file

## Steps to Reproduce (for bugs)

1. go to /report/portvlanmismatch
2. click csv button
3. see broken download

## Your Environment

* Netdisco version used: 2.035
* SNMP::Info version used: reported as "n/a"

**Comment by ollyg** [comment]
Thanks for the bug report! This is fixed in commit netdisco@d0472a9d.
