### ISSUE TITLE
Configurable Free Time in Port Utilization Report

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#31]
From mailing list:

A very useful report for me is the Port Utilisation Report.

Regarding this report I have a question:
When is a port marked as free in this report and am I able to change this value?
As an idea for a future ND2 release it would be great to have also for
the report the option to choose when a port is marked as free, like
you can do in the port overview already currently :)

Reported by: jeneric-placeholder

Original Ticket: [netdisco/nd2-features/33](https://sourceforge.net/p/netdisco/nd2-features/33)

**Comment by ollyg** [comment]
Done!
