### ISSUE TITLE
Allow SSHCollector to perfom per-protocol actions

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#32]
It's relatively common for IPv6 MIBs to lag behind IPv4. It would be nice to be able to use SSHCollector for IPv6 neighbours, but SNMP MIBs for IPv4 for some devices.

Reported by: rkerr

Original Ticket: [netdisco/nd2-features/34](https://sourceforge.net/p/netdisco/nd2-features/34)

**Comment by ollyg** [comment]
As far as I recall, the current architecture in Netdisco Core is updating the node_ip all at once, atomically. So two processes updating the data partially would overwrite each other.

Closing and moving to wishlist page in wiki.

**Comment by inphobia** [comment]
steps are being taken: #489

**Comment by ollyg** [comment]
SSH collector is impelemented and with #1244 we should be able to do this, it's very easily close
