### ISSUE TITLE
Missing device BACKEND param

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#321]
```
DETAIL:  Failing row contains (null, 10.10.133.4, {}, 0, null). [for Statement "INSERT INTO device_skip ( backend, device) VALUES ( ?, ? ) RETURNING backend" with ParamValues: 1=undef, 2=\'10.10.133.4\'] at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 231
'}, 'DBIx::Class::Exception' )
```

However user confirms that the following produces the host fqdn:
`~netdisco/bin/localenv perl -MNet::Domain -E 'say Net::Domain::hostfqdn'`
So it must be getting squashed after initialisation in `Configuration.pm`.

**Comment by bhuddah** [comment]
+

**Comment by ollyg** [comment]
Possibly related to running the old and new backend at the same time (not confirmed yet).

**Comment by ollyg** [comment]
Assume this is related to docs not being clear on upgrade .... have amended text and committed in fa6eac41.
