### ISSUE TITLE
Add IP address underneath sysname/dns in the net map

### ISSUE THREAD

**Issue by alcatron** [netdisco/netdisco#326]
In the netmap i see it now falls to showing the sysname which is really good (when it doesnt pickup from dns), however is it possible to add the IP address of the device underneath.. this way the map has got a nice view of the device/ip of its neighbors and connections.

**Comment by ollyg** [comment]
I can't find out how to do this in a clean and easy way in SVG. I'm going to close this ticket as I can't see any of the existing devs having a go, and I don't like tickets to remain open forever. I would be happy to accept a patch if anyone steps up.

I think the display of IPs should be an option with a tickbox in the sidebar, but that's fairly easy to do once we have the SVG working.
