### ISSUE TITLE
Unable to use Netdisco after Debian dist-upgrade from Jessie to Stretch

### ISSUE THREAD

**Issue by rodjeur** [netdisco/netdisco#327]
## Expected Behavior

netdisco-backend should start.

## Current Behavior

netdisco-backend doesn-t start, with error:
"perl: symbol lookup error: /home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/YAML/XS/LibYAML/LibYAML.so: undefined symbol: Perl_xs_apiversion_bootcheck"

## Possible Solution

Replacing LibYAML.so by one installed via apt solves the problem: backend starts. But nestdisco-do faces same problem with other libraries.

## Steps to Reproduce (for bugs)

1. Migrate from Debian Jessie to Debian Stretch

## Your Environment

* Netdisco version used: 2.036006
* SNMP::Info version used: 3.36

**Comment by ollyg** [comment]
Hi @rodjeur 

This is covered in our troubleshooting page:
https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Troubleshooting.pod#After-OS-update-or-upgrade,-Netdisco-fails

regards,
oliver.

**Comment by rodjeur** [comment]
Hi Oliver,

Thanks, I missed this entry in the troubleshooting page, sorry. Works great now !

Best regards,

Rodjeur

**Comment by martinsnygg** [comment]
Got the same issue but [https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Troubleshooting.pod#After-OS-update-or-upgrade,-Netdisco-fails](https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Troubleshooting.pod#After-OS-update-or-upgrade,-Netdisco-fails) is not found :(

**Comment by martinsnygg** [comment]
Found it here [https://github.com/netdisco/netdisco/wiki/Troubleshooting#after-os-update-or-upgrade-netdisco-fails](https://github.com/netdisco/netdisco/wiki/Troubleshooting#after-os-update-or-upgrade-netdisco-fails)
