### ISSUE TITLE
Right hand netdisco menu "update view" not saving properly

### ISSUE THREAD

**Issue by alcatron** [netdisco/netdisco#328]
The view settings menu on the right hand side can loose its settings after clicking update view, so have to continusly keep checking the box, then clicking update view. 

Can it be investigated to make sure the user view settings locks in after clicking update view?

 It's probably combination of url paramaters, cookie, and browser data store,web code / javascript / etc on that for someone to look into..

**Comment by ollyg** [comment]
Same as #249 I reckon.
