### ISSUE TITLE
Display IP in Netmap

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#33]
Is it possible to display the name and IP address of a device in the topology map?  Most of my crew are more familiar with the IP, mostly because our names are confusing, so I'd like to be able to display both.  I saw someone in the archives had made it work but I couldn't find how he did it.

Jim Kirby

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/35](https://sourceforge.net/p/netdisco/nd2-features/35)

**Comment by ollyg** [comment]
These two features are now in place with the new network map!
