### ISSUE TITLE
not collect mac addresses DLINK DES-3200

### ISSUE THREAD

**Issue by reabiliti** [netdisco/netdisco#330]
Good afternoon,
Installed 2.036008, when attempting to interrogate the dlink switch DES-3200-26 / C1 or DES-3526, does not collect mac addresses, it writes an error in the logs:

Can not find module (DES-1210-28-AX): At line 1 in (none)
Can not find module (DES-1210-28-AX): At line 1 in (none)
Can not find module (DES-1210-28-AX): At line 1 in (none)

Installing:
curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco

![clipboard01](https://user-images.githubusercontent.com/30253042/28303009-71f4a2fe-6b99-11e7-97c5-22242a4aecbf.jpg)
![clipboard02](https://user-images.githubusercontent.com/30253042/28303008-71f23b40-6b99-11e7-86a7-020812b5fc2c.jpg)

**Comment by JeroenvIS** [comment]
I've worked with a few of these D-Link switches in a past job; IIRC certain parts of the vendor specific MIBs have a dynamic location, ie the exact OIDs to poll are different for every model. I'm not sure if that's something we can easily deal with.

**Comment by edo1** [comment]
I have the same issue with DGS-1510-52 and DGS-3120-24TC models.
Previous version (2.035006) seems to has no such issue.

**Comment by ollyg** [comment]
That's a bit strange, because the changes since 2.036006 are mostly in the web frontend, not the device poller. Also, this is more likely to be something to fix in SNMP::Info or netdisco-mibs, so this ticket should be closed.

We have another ticket at netdisco/netdisco-mibs/issues/19 which has some comments, so you could add to that the output of:

```
~netdisco/bin/netdisco-do show -DI -d 1.2.3.4 -e ip
~netdisco/bin/netdisco-do show -DI -d 1.2.3.4 -e description
~netdisco/bin/netdisco-do show -DI -d 1.2.3.4 -e layers
```

Many thanks
Oliver.

**Comment by reabiliti** [comment]
Good afternoon,
Received the following conclusion:

[netdisco@zabbixmysql ~]$ ~netdisco/bin/netdisco-do show -DI -d 10.152.16.44 -e ip
[7463] 2017-08-08 05:07:28  info show: [10.152.16.44]/ip started at Tue Aug  8 08:07:28 2017
[7463] 2017-08-08 05:07:28 debug [10.152.16.44] try_connect with ver: 2, class: SNMP::Info, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.37
SNMP::Info::device_type() layers:00000011 id:171 sysDescr:"DES-3200-26/C1 Fast Ethernet Switch"
SNMP::Info 3.37
SNMP::Info::device_type() layers:00000011 id:171 sysDescr:"DES-3200-26/C1 Fast Ethernet Switch"
[7463] 2017-08-08 05:07:29 debug [10.152.16.44] try_connect with ver: 2, new class: SNMP::Info::Layer3::DLink, comm: <hidden>
MIB search path: /home/netdisco/netdisco-mibs/3com:/home/netdisco/netdisco-mibs/aerohive:/home/netdisco/netdisco-mibs/alcatel:/home/netdisco/netdisco-mibs/allied:/home/netdisco/netdisco-mibs/apc:/home/netdisco/netdisco-mibs/arista:/home/netdisco/netdisco-mibs/aruba:/home/netdisco/netdisco-mibs/asante:/home/netdisco/netdisco-mibs/avaya:/home/netdisco/netdisco-mibs/bluecoat:/home/netdisco/netdisco-mibs/bluesocket:/home/netdisco/netdisco-mibs/cabletron:/home/netdisco/netdisco-mibs/checkpoint:/home/netdisco/netdisco-mibs/cisco:/home/netdisco/netdisco-mibs/ciscosb:/home/netdisco/netdisco-mibs/citrix:/home/netdisco/netdisco-mibs/colubris:/home/netdisco/netdisco-mibs/cyclades:/home/netdisco/netdisco-mibs/d-link:/home/netdisco/netdisco-mibs/dell:/home/netdisco/netdisco-mibs/enterasys:/home/netdisco/netdisco-mibs/EXTRAS:/home/netdisco/netdisco-mibs/extreme:/home/netdisco/netdisco-mibs/extricom:/home/netdisco/netdisco-mibs/f5:/home/netdisco/netdisco-mibs/force10:/home/netdisco/netdisco-mibs/fortinet:/home/netdisco/netdisco-mibs/foundry:/home/netdisco/netdisco-mibs/gigamon:/home/netdisco/netdisco-mibs/h3c:/home/netdisco/netdisco-mibs/hp:/home/netdisco/netdisco-mibs/huawei:/home/netdisco/netdisco-mibs/ibm:/home/netdisco/netdisco-mibs/juniper:/home/netdisco/netdisco-mibs/lantronix:/home/netdisco/netdisco-mibs/meraki:/home/netdisco/netdisco-mibs/meru:/home/netdisco/netdisco-mibs/mikrotik:/home/netdisco/netdisco-mibs/moser-baer:/home/netdisco/netdisco-mibs/motorola:/home/netdisco/netdisco-mibs/net-snmp:/home/netdisco/netdisco-mibs/netapp:/home/netdisco/netdisco-mibs/netgear:/home/netdisco/netdisco-mibs/netscreen:/home/netdisco/netdisco-mibs/nexans:/home/netdisco/netdisco-mibs/nortel:/home/netdisco/netdisco-mibs/northerndesign:/home/netdisco/netdisco-mibs/opengear:/home/netdisco/netdisco-mibs/packetfront:/home/netdisco/netdisco-mibs/paloalto:/home/netdisco/netdisco-mibs/pica8:/home/netdisco/netdisco-mibs/rad:/home/netdisco/netdisco-mibs/rfc:/home/netdisco/netdisco-mibs/riverbed:/home/netdisco/netdisco-mibs/ruckus:/home/netdisco/netdisco-mibs/schleifenbauer:/home/netdisco/netdisco-mibs/sentry:/home/netdisco/netdisco-mibs/sixnet:/home/netdisco/netdisco-mibs/sonicwall:/home/netdisco/netdisco-mibs/tplink:/home/netdisco/netdisco-mibs/trapeze:/home/netdisco/netdisco-mibs/vmware:/home/netdisco/netdisco-mibs/xirrus
Cannot find module (DES-1210-28-AX): At line 1 in (none)
[7463] 2017-08-08 05:07:29 debug The DES-1210-28-AX did not load. See README for SNMP::Info::Layer3::DLink
 at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/SNMP.pm line 166.
SNMP::Info::_global ip : IP-MIB::ip.0 : .1.3.6.1.2.1.4.0
SNMP::Info::_global(ip) NOSUCHOBJECT at /home/netdisco/bin/netdisco-do line 142.
[7463] 2017-08-08 05:07:29  info show: finished at Tue Aug  8 08:07:29 2017
[7463] 2017-08-08 05:07:29  info show: status error: error running job: When calling p() without prototypes, please pass arguments as references at /home/netdisco/bin/netdisco-do line 142.
[netdisco@zabbixmysql ~]$


[netdisco@zabbixmysql ~]$ ~netdisco/bin/netdisco-do show -DI -d 10.152.16.44 -e description
[7473] 2017-08-08 05:08:18  info show: [10.152.16.44]/description started at Tue Aug  8 08:08:18 2017
[7473] 2017-08-08 05:08:18 debug [10.152.16.44] try_connect with ver: 2, class: SNMP::Info, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.37
SNMP::Info::device_type() layers:00000011 id:171 sysDescr:"DES-3200-26/C1 Fast Ethernet Switch"
SNMP::Info 3.37
SNMP::Info::device_type() layers:00000011 id:171 sysDescr:"DES-3200-26/C1 Fast Ethernet Switch"
[7473] 2017-08-08 05:08:19 debug [10.152.16.44] try_connect with ver: 2, new class: SNMP::Info::Layer3::DLink, comm: <hidden>
MIB search path: /home/netdisco/netdisco-mibs/3com:/home/netdisco/netdisco-mibs/aerohive:/home/netdisco/netdisco-mibs/alcatel:/home/netdisco/netdisco-mibs/allied:/home/netdisco/netdisco-mibs/apc:/home/netdisco/netdisco-mibs/arista:/home/netdisco/netdisco-mibs/aruba:/home/netdisco/netdisco-mibs/asante:/home/netdisco/netdisco-mibs/avaya:/home/netdisco/netdisco-mibs/bluecoat:/home/netdisco/netdisco-mibs/bluesocket:/home/netdisco/netdisco-mibs/cabletron:/home/netdisco/netdisco-mibs/checkpoint:/home/netdisco/netdisco-mibs/cisco:/home/netdisco/netdisco-mibs/ciscosb:/home/netdisco/netdisco-mibs/citrix:/home/netdisco/netdisco-mibs/colubris:/home/netdisco/netdisco-mibs/cyclades:/home/netdisco/netdisco-mibs/d-link:/home/netdisco/netdisco-mibs/dell:/home/netdisco/netdisco-mibs/enterasys:/home/netdisco/netdisco-mibs/EXTRAS:/home/netdisco/netdisco-mibs/extreme:/home/netdisco/netdisco-mibs/extricom:/home/netdisco/netdisco-mibs/f5:/home/netdisco/netdisco-mibs/force10:/home/netdisco/netdisco-mibs/fortinet:/home/netdisco/netdisco-mibs/foundry:/home/netdisco/netdisco-mibs/gigamon:/home/netdisco/netdisco-mibs/h3c:/home/netdisco/netdisco-mibs/hp:/home/netdisco/netdisco-mibs/huawei:/home/netdisco/netdisco-mibs/ibm:/home/netdisco/netdisco-mibs/juniper:/home/netdisco/netdisco-mibs/lantronix:/home/netdisco/netdisco-mibs/meraki:/home/netdisco/netdisco-mibs/meru:/home/netdisco/netdisco-mibs/mikrotik:/home/netdisco/netdisco-mibs/moser-baer:/home/netdisco/netdisco-mibs/motorola:/home/netdisco/netdisco-mibs/net-snmp:/home/netdisco/netdisco-mibs/netapp:/home/netdisco/netdisco-mibs/netgear:/home/netdisco/netdisco-mibs/netscreen:/home/netdisco/netdisco-mibs/nexans:/home/netdisco/netdisco-mibs/nortel:/home/netdisco/netdisco-mibs/northerndesign:/home/netdisco/netdisco-mibs/opengear:/home/netdisco/netdisco-mibs/packetfront:/home/netdisco/netdisco-mibs/paloalto:/home/netdisco/netdisco-mibs/pica8:/home/netdisco/netdisco-mibs/rad:/home/netdisco/netdisco-mibs/rfc:/home/netdisco/netdisco-mibs/riverbed:/home/netdisco/netdisco-mibs/ruckus:/home/netdisco/netdisco-mibs/schleifenbauer:/home/netdisco/netdisco-mibs/sentry:/home/netdisco/netdisco-mibs/sixnet:/home/netdisco/netdisco-mibs/sonicwall:/home/netdisco/netdisco-mibs/tplink:/home/netdisco/netdisco-mibs/trapeze:/home/netdisco/netdisco-mibs/vmware:/home/netdisco/netdisco-mibs/xirrus
Cannot find module (DES-1210-28-AX): At line 1 in (none)
[7473] 2017-08-08 05:08:19 debug The DES-1210-28-AX did not load. See README for SNMP::Info::Layer3::DLink
 at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/SNMP.pm line 166.
"DES-3200-26/C1 Fast Ethernet Switch"
[7473] 2017-08-08 05:08:19  info show: finished at Tue Aug  8 08:08:19 2017
[7473] 2017-08-08 05:08:19  info show: status done: Showed description response from 10.152.16.44.
[netdisco@zabbixmysql ~]$


[netdisco@zabbixmysql ~]$ ~netdisco/bin/netdisco-do show -DI -d 10.152.16.44 -e layers
[7489] 2017-08-08 05:09:08  info show: [10.152.16.44]/layers started at Tue Aug  8 08:09:08 2017
[7489] 2017-08-08 05:09:08 debug [10.152.16.44] try_connect with ver: 2, class: SNMP::Info, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.37
SNMP::Info::device_type() layers:00000011 id:171 sysDescr:"DES-3200-26/C1 Fast Ethernet Switch"
SNMP::Info 3.37
SNMP::Info::device_type() layers:00000011 id:171 sysDescr:"DES-3200-26/C1 Fast Ethernet Switch"
[7489] 2017-08-08 05:09:08 debug [10.152.16.44] try_connect with ver: 2, new class: SNMP::Info::Layer3::DLink, comm: <hidden>
MIB search path: /home/netdisco/netdisco-mibs/3com:/home/netdisco/netdisco-mibs/aerohive:/home/netdisco/netdisco-mibs/alcatel:/home/netdisco/netdisco-mibs/allied:/home/netdisco/netdisco-mibs/apc:/home/netdisco/netdisco-mibs/arista:/home/netdisco/netdisco-mibs/aruba:/home/netdisco/netdisco-mibs/asante:/home/netdisco/netdisco-mibs/avaya:/home/netdisco/netdisco-mibs/bluecoat:/home/netdisco/netdisco-mibs/bluesocket:/home/netdisco/netdisco-mibs/cabletron:/home/netdisco/netdisco-mibs/checkpoint:/home/netdisco/netdisco-mibs/cisco:/home/netdisco/netdisco-mibs/ciscosb:/home/netdisco/netdisco-mibs/citrix:/home/netdisco/netdisco-mibs/colubris:/home/netdisco/netdisco-mibs/cyclades:/home/netdisco/netdisco-mibs/d-link:/home/netdisco/netdisco-mibs/dell:/home/netdisco/netdisco-mibs/enterasys:/home/netdisco/netdisco-mibs/EXTRAS:/home/netdisco/netdisco-mibs/extreme:/home/netdisco/netdisco-mibs/extricom:/home/netdisco/netdisco-mibs/f5:/home/netdisco/netdisco-mibs/force10:/home/netdisco/netdisco-mibs/fortinet:/home/netdisco/netdisco-mibs/foundry:/home/netdisco/netdisco-mibs/gigamon:/home/netdisco/netdisco-mibs/h3c:/home/netdisco/netdisco-mibs/hp:/home/netdisco/netdisco-mibs/huawei:/home/netdisco/netdisco-mibs/ibm:/home/netdisco/netdisco-mibs/juniper:/home/netdisco/netdisco-mibs/lantronix:/home/netdisco/netdisco-mibs/meraki:/home/netdisco/netdisco-mibs/meru:/home/netdisco/netdisco-mibs/mikrotik:/home/netdisco/netdisco-mibs/moser-baer:/home/netdisco/netdisco-mibs/motorola:/home/netdisco/netdisco-mibs/net-snmp:/home/netdisco/netdisco-mibs/netapp:/home/netdisco/netdisco-mibs/netgear:/home/netdisco/netdisco-mibs/netscreen:/home/netdisco/netdisco-mibs/nexans:/home/netdisco/netdisco-mibs/nortel:/home/netdisco/netdisco-mibs/northerndesign:/home/netdisco/netdisco-mibs/opengear:/home/netdisco/netdisco-mibs/packetfront:/home/netdisco/netdisco-mibs/paloalto:/home/netdisco/netdisco-mibs/pica8:/home/netdisco/netdisco-mibs/rad:/home/netdisco/netdisco-mibs/rfc:/home/netdisco/netdisco-mibs/riverbed:/home/netdisco/netdisco-mibs/ruckus:/home/netdisco/netdisco-mibs/schleifenbauer:/home/netdisco/netdisco-mibs/sentry:/home/netdisco/netdisco-mibs/sixnet:/home/netdisco/netdisco-mibs/sonicwall:/home/netdisco/netdisco-mibs/tplink:/home/netdisco/netdisco-mibs/trapeze:/home/netdisco/netdisco-mibs/vmware:/home/netdisco/netdisco-mibs/xirrus
Cannot find module (DES-1210-28-AX): At line 1 in (none)
[7489] 2017-08-08 05:09:08 debug The DES-1210-28-AX did not load. See README for SNMP::Info::Layer3::DLink
 at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/SNMP.pm line 166.
"00000011"
[7489] 2017-08-08 05:09:08  info show: finished at Tue Aug  8 08:09:08 2017
[7489] 2017-08-08 05:09:08  info show: status done: Showed layers response from 10.152.16.44.
[netdisco@zabbixmysql ~]$

**Comment by ollyg** [comment]
Closing, as I assume netdisco-mibs#19 updated the MIBs and it looks better now.
