### ISSUE TITLE
Autodiscovery via BGP-MIB

### ISSUE THREAD

**Issue by fabled** [netdisco/netdisco#332]
In addition to L2 protocols, it would be helpful to do autodiscovery from L3 type resources. Especially BGP-MIB would be useful for me. While the information cannot be associated to specific device port, it would help on discovering the whole network without need to 'seed' discovery in each physically separated site (but which are connected logically via tunnels, VPN or similar).

In practice this makes sense do only for routers (L3 capable). Basic idea is to walk BGP peer table, and just queue discover jobs for the remote IP (if that IP does not exist in the devices table).

**Comment by fabled** [comment]
Example of `bgpRemoteAddr` table contents:

<pre>
[14950] 2017-07-20 10:51:16  info App::Netdisco version 2.036008 loaded.
[14950] 2017-07-20 10:51:17  info show: started at Thu Jul 20 10:51:17 2017
\ {
    10.6.1.1      "10.6.1.1",
    10.6.1.2      "10.6.1.2",
    10.12.1.2     "10.12.1.2",
    10.12.1.3     "10.12.1.3",
    10.12.1.4     "10.12.1.4",
    10.12.1.101   "10.12.1.101"
}
[14950] 2017-07-20 10:51:17  info show: finished at Thu Jul 20 10:51:17 2017
[14950] 2017-07-20 10:51:17  info show: status done: Showed bgpPeerRemoteAddr response from 10.12.1.1.
</pre>

**Comment by LBegnaud** [comment]
Pretty cool idea. I vote for OSPF as well. That would be amazing for autodiscovering the whole topology starting from one node.

**Comment by ollyg** [comment]
Not tested but blind coding produces this, which looks good!

https://github.com/netdisco/netdisco/wiki/Worker-Cookbook#a-more-realistic-plugin-example

**Comment by ollyg** [comment]
SNMP::Info::Layer3 already has `bgp_peer_addr()` and `ospf_peers()`.

**Comment by LBegnaud** [comment]
```
[39006] 2018-01-31 20:54:27 debug  [10.141.1.1] neigh - setting manual topology links
SNMP::Info::_global lldp_sys_cap : LLDP-MIB::lldpLocSysCapEnabled.0 : .1.0.8802.1.1.2.1.3.6.0
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_global(lldp_sys_cap) NOSUCHOBJECT at /netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm line 107.
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_validate_autoload_method(hasCDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
[39006] 2018-01-31 20:54:27 debug  [10.141.1.1] neigh - neighbor protocols are not enabled
[39006] 2018-01-31 20:54:27 debug  [10.141.1.1] neigh - processed 0 neighbors
```

Is there something I'm missing to get ospf to be used for discovery? Does the device need to support lldp for ospf to attempt discovery?

**Comment by ollyg** [comment]
Hi @LBegnaud - the OSPF and BGP support isn't included in Netdisco yet, it's only in SNMP::Info.

We need to write a new worker plugin, which I've given a sketch of here (untested!):
https://github.com/netdisco/netdisco/wiki/Worker-Cookbook#a-more-realistic-plugin-example

Should be easy, but I'm waiting on a rebuild of one of my test servers so I can verify the code. And yes, it'll be independent of LLDP - just queueing more IPs as @fabled suggested above.

**Comment by LBegnaud** [comment]
oh i misinterpreted the conversation. My mistake!

Looking forward to this, then.

**Comment by ollyg** [comment]
note to self: should also check layer3 support in device before doing this

**Comment by ollyg** [comment]
It's in! will be in the next release:
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Discover/Neighbors/Routed.pm

**Comment by ollyg** [comment]
log looks like:
````
[42445] 2018-02-01 11:13:47 debug -> run worker main/neighbors/100
[42445] 2018-02-01 11:13:47 debug  [10.a.b.35] queued discovery of routing peer x.x.x.157
[42445] 2018-02-01 11:13:47 debug  [10.a.b.35] queued discovery of routing peer y.y.y.40
[42445] 2018-02-01 11:13:47 debug  [10.a.b.35] Routing peers added to discover queue.
````

**Comment by LBegnaud** [comment]
So neat!

**Comment by LBegnaud** [comment]
I'm finally getting around to using this, and it looks like this only references the peer IP directly. Would it be possible to have some way to discover the ospf router ID instead of the peer IP (peer IP isn't routable from our netdisco server, but the Router ID is:

![image](https://user-images.githubusercontent.com/15981748/50367674-77aaa600-0547-11e9-962d-269b1de5e3ed.png)

currently the discovery hits the 172 addresses, but I would like it to hit the 10.222 addresses:

![image](https://user-images.githubusercontent.com/15981748/50367707-9e68dc80-0547-11e9-9566-0f57dba58f0f.png)
