### ISSUE TITLE
DB schema Issue after update 2.36.4 to 2.36.8

### ISSUE THREAD

**Issue by romale** [netdisco/netdisco#334]
## Expected Behavior

No error messages and fully worked

## Current Behavior
1. DBIx::Class::Schema::Versioned::_on_connect(): Versions out of sync. This is 44, your database contains version 40, please call upgrade on your Schema. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95

2. "Sorry, no such device is known." on neighbors map

3. No links when mouse over device in neighbors map

## Your Environment

* Netdisco version used: 2.36.8
* SNMP::Info version used: 3.36

I've tried re-deploy schema, but no succes:

netdisco=> drop table dbix_class_schema_versions;
DROP TABLE
netdisco=> \q

 ~/bin/localenv cpanm --notest App::Netdisco
App::Netdisco is up to date. (2.036008)

 ~/bin/netdisco-deploy
This is the Netdisco II deployment script.

Before we continue, the following prerequisites must be in place:
 * Database added to PostgreSQL for Netdisco
 * User added to PostgreSQL with rights to the Netdisco Database
 * "~/environments/deployment.yml" file configured with Database dsn/user/pass
 * A full backup of any existing Netdisco database data
 * Internet access (for OUIs and MIBs)

You will be asked to confirm all changes to your system.

So, is all the above in place? [y/N]: y

Would you like to deploy the database schema? [y/N]: y
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "dbix_class_schema_versions_pkey" for table "dbix_class_schema_versions"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (2) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (3) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (4) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (5) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (6) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (7) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (8) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (9) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (10) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (11) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (12) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (13) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (14) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (15) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (16) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (17) is lower than the schema version (44). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "admin_pkey" for table "admin"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (18) is lower than the schema version (44). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "node_pkey" for table "node"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (19) is lower than the schema version (44). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "node_wireless_pkey" for table "node_wireless"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (20) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (21) is lower than the schema version (44). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD UNIQUE will create implicit index "topology_dev1_port1" for table "topology"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (22) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (23) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (24) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (25) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (26) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (27) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (28) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (29) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (30) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (31) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (32) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (33) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (34) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (35) is lower than the schema version (44). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "device_port_vlan_pkey" for table "device_port_vlan"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (36) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (37) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (38) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (39) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (40) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (41) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (42) is lower than the schema version (44). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (43) is lower than the schema version (44). Attempting upgrade.
DB schema update complete.
DBIx::Class::Schema::Versioned::_on_connect(): Versions out of sync. This is 44, your database contains version 40, please call upgrade on your Schema. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95

 ~/bin/netdisco-web restart
config watcher: sending TERM to the server (pid:31444)...
Netdisco Web                                                  [Stopped]
Netdisco Web                                                  [Started]
config watcher: watching /home/netdisco/environments for updates.

 ~/bin/netdisco-daemon stop
config watcher: sending TERM to the server (pid:31473)...
Netdisco Backend                                              [Stopped]

 ~/bin/netdisco-backend restart
Netdisco Backend                                              [Started]
config watcher: watching /home/netdisco/environments for updates.

netdisco=> select * from dbix_class_schema_versions;
 version |      installed
---------+----------------------
 1       | v20170724_094823.779
 2       | v20170724_094823.788
 13      | v20170724_094823.812
 14      | v20170724_094823.814
 18      | v20170724_094823.827
 19      | v20170724_094823.891
 20      | v20170724_094823.895
 21      | v20170724_094823.900
 26      | v20170724_094823.907
 27      | v20170724_094823.908
 28      | v20170724_094823.910
 29      | v20170724_094823.913
 31      | v20170724_094823.917
 32      | v20170724_094823.920
 34      | v20170724_094823.925
 36      | v20170724_094824.009
 39      | v20170724_094824.014
 40      | v20170724_094824.018
(18 rows)

tailf logs/netdisco-backend.log
DBIx::Class::Schema::Versioned::_on_connect(): Versions out of sync. This is 44, your database contains version 40, please call upgrade on your Schema. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95
DBIx::Class::Schema::Versioned::_on_connect(): Versions out of sync. This is 44, your database contains version 40, please call upgrade on your Schema. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95

**Comment by ollyg** [comment]
Hi Romale

Please would you run the netdisco-deploy script again, but add "`DBIC_TRACE=1`" to the start of the command (so that the environment variable is set). You will get a log showing the DB commands issued, and can then paste that to here or https://privatebin.net/ if you prefer.

Many thanks
Oliver.

**Comment by romale** [comment]
Hi Oliver,

Logs:
```
DBIC_TRACE=1 ~netdisco/bin/netdisco-deploy
This is the Netdisco II deployment script.

Before we continue, the following prerequisites must be in place:
 * Database added to PostgreSQL for Netdisco
 * User added to PostgreSQL with rights to the Netdisco Database
 * "~/environments/deployment.yml" file configured with Database dsn/user/pass
 * A full backup of any existing Netdisco database data
 * Internet access (for OUIs and MIBs)

You will be asked to confirm all changes to your system.

So, is all the above in place? [y/N]: y

Would you like to deploy the database schema? [y/N]: y
SELECT me.version, me.installed
  FROM dbix_class_schema_versions me
WHERE 1 = 0
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
DBIx::Class::Schema::Versioned::_on_connect(): Versions out of sync. This is 44, your database contains version 40, please call upgrade on your Schema. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (40) is lower than the schema version (44). Attempting upgrade.
BEGIN WORK
ALTER TABLE community RENAME COLUMN snmp_auth_tag TO snmp_auth_tag_read
ROLLBACK
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (41) is lower than the schema version (44). Attempting upgrade.
BEGIN WORK
CREATE TABLE "device_skip"( "backend" text, NOT NULL, "device" inet NOT NULL, "actionset" text[] DEFAULT '{}', "deferrals" integer DEFAULT 0, PRIMARY KEY( "backend", "device" ) )
ROLLBACK
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (42) is lower than the schema version (44). Attempting upgrade.
BEGIN WORK
ALTER TABLE "device_skip" ADD "last_defer" timestamp
ROLLBACK
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (43) is lower than the schema version (44). Attempting upgrade.
BEGIN WORK
CREATE TABLE "statistics"( "day" date, NOT NULL, DEFAULT CURRENT_DATE, "device_count" integer NOT NULL, "device_ip_count" integer NOT NULL, "device_link_count" integer NOT NULL, "device_port_count" integer NOT NULL, "device_port_up_count" integer NOT NULL, "ip_table_count" integer NOT NULL, "ip_active_count" integer NOT NULL, "node_table_count" integer NOT NULL, "node_active_count" integer NOT NULL, "netdisco_ver" text, "snmpinfo_ver" text, "schema_ver" text, "perl_ver" text, "pg_ver" text, PRIMARY KEY( "day" ) )
ROLLBACK
DB schema update complete.
SELECT me.version, me.installed
  FROM dbix_class_schema_versions me
WHERE 1 = 0
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
DBIx::Class::Schema::Versioned::_on_connect(): Versions out of sync. This is 44, your database contains version 40, please call upgrade on your Schema. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95
SELECT COUNT( * )
  FROM users me
WHERE admin
SELECT me.id, me.creation, me.a_session
  FROM sessions me
WHERE me.id = 'dancer_session_cookie_key'

Download and update vendor MAC prefixes (OUI data)? [y/N]:

Download and update MIB files? [y/N]:
[netdisco@mon ~]$
```

**Comment by ollyg** [comment]
Hi @romale 

Thanks for the log, this does help. We can see the ROLLBACK being issued after each SQL command, but we cannot see the reason. Perhaps you could try:

```
~netdisco/bin/netdisco-do psql
dbname=# ALTER TABLE community RENAME COLUMN snmp_auth_tag TO snmp_auth_tag_read;
```

And let us know what happened?
thanks,
Oliver.

**Comment by romale** [comment]
```
[netdisco@mon ~]$ ~netdisco/bin/netdisco-do psql dbname=# ALTER TABLE community RENAME COLUMN snmp_auth_tag TO snmp_auth_tag_read;
[30803] 2017-07-31 10:39:50  info psql: started at Mon Jul 31 13:39:50 2017
psql (9.2.18)
Type "help" for help.

netdisco=>
```

**Comment by ollyg** [comment]
Hi @romale 

Sorry I meant to run that as two commands. Let me be more specific:

run `~netdisco/bin/netdisco-do psql`

and then you will have an SQL prompt. enter `ALTER TABLE community RENAME COLUMN snmp_auth_tag TO snmp_auth_tag_read;` and press return.

I would like to see the output after that.

thanks, and sorry for the confusion.

**Comment by romale** [comment]
```
 ~]$ ~netdisco/bin/netdisco-do psql
[26643] 2017-07-31 15:34:05  info psql: started at Mon Jul 31 18:34:05 2017
psql (9.2.18)
Type "help" for help.

netdisco=> ALTER TABLE community RENAME COLUMN snmp_auth_tag TO snmp_auth_tag_read;
ERROR:  column "snmp_auth_tag_read" of relation "community" already exists
netdisco=>
```

**Comment by ollyg** [comment]
Many thanks @romale 

I have fixed this in commit d7f6dcc which will be in the next release.

(for the record this bug relates to schema version not being written if all schema patches fail due to having been previously applied, so now we force-set the version on rollback)

**Comment by ollyg** [comment]
Please test version 2.036009 which is now on CPAN and let me know how it goes.

**Comment by romale** [comment]
Hi @ollyg ,
now it's looks good

```
netdisco=>  select * from dbix_class_schema_versions;
 version |      installed
---------+----------------------
 1       | v20170724_094823.779
 2       | v20170724_094823.788
 13      | v20170724_094823.812
 14      | v20170724_094823.814
 18      | v20170724_094823.827
 19      | v20170724_094823.891
 20      | v20170724_094823.895
 21      | v20170724_094823.900
 26      | v20170724_094823.907
 27      | v20170724_094823.908
 28      | v20170724_094823.910
 29      | v20170724_094823.913
 31      | v20170724_094823.917
 32      | v20170724_094823.920
 34      | v20170724_094823.925
 36      | v20170724_094824.009
 39      | v20170724_094824.014
 40      | v20170724_094824.018
 41      | v20170801_110541.322
 42      | v20170801_110541.361
 43      | v20170801_110541.364
 44      | v20170801_110541.368
(22 rows)
```

**Comment by ollyg** [comment]
Super! Many thanks :-)
