### ISSUE TITLE
Motorola (now Extreme Networks) AP 6532 not correctly detected

### ISSUE THREAD

**Issue by gabbiere** [netdisco/netdisco#340]
Dear all,

I have a fresh and updated installation of netdisco ( version 2.036009 with SNMP::Info 3.37 )  deployed on a CentOS 6.9.
I have also some Motorola AP 6532 access points (WiNG 5.8.4.0-034R with CDP and SNMP v2 with our usual RO community enabled ).
I have also commented out the line
`- '(?i)(?:wap|wireless)'`
 in /home/netdisco/environments/deployment.yml, so I would expect to see  my acces points as nodes with their neighbors, but netdisco presently identifies the device only as  `unknown / enterprises.388.50.1.1.4` 
and doesn't report any neighbor.

This the discovery debug output: 

`>[netdisco@netmon ~]$ ./bin/netdisco-do discover -d ap01 -DQI
SELECT me.version, me.installed
  FROM dbix_class_schema_versions me
WHERE 1 = 0
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.ip, me.alias, me.subnet, me.port, me.dns, me.creation
  FROM device_ip me
WHERE me.alias = '10.118.106.231' AND me.ip = '10.118.106.231'
SELECT me.ip, me.creation, me.dns, me.description, me.uptime, me.contact, me.name, me.location, me.layers, me.ports, me.mac, me.serial, me.model, me.ps1_type, me.ps2_type, me.ps1_status, me.ps2_status, me.fan, me.slots, me.vendor, me.os, me.os_ver, me.log, me.snmp_ver, me.snmp_comm, me.snmp_class, me.vtp_domain, me.last_discover, me.last_macsuck, me.last_arpnip, to_char( last_arpnip, 'YYYY-MM-DD HH24:MI' ), to_char( last_discover, 'YYYY-MM-DD HH24:MI' ), to_char( last_macsuck, 'YYYY-MM-DD HH24:MI' ), extract( epoch
      FROM age( now(  ), last_arpnip ) ), extract( epoch
      FROM age( now(  ), last_discover ) ), extract( epoch
      FROM age( now(  ), last_macsuck ) ), replace( age( timestamp 'epoch' + uptime / 100 * interval '1 second', timestamp '1970-01-01 00:00:00-00' ) ::text, 'mon', 'month' )
  FROM device me
WHERE me.ip = '10.118.106.231'
[9457] 2017-08-18 13:46:26  info discover: [10.118.106.231] started at Fri Aug 18 15:46:26 2017
SELECT me.ip, me.snmp_comm_rw, me.snmp_auth_tag_read, me.snmp_auth_tag_write
  FROM community me
WHERE me.ip = '10.118.106.231'
[9457] 2017-08-18 13:46:26 debug [10.118.106.231] try_connect with ver: 2, class: SNMP::Info::Layer3, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
BEGIN WORK
COMMIT
BEGIN WORK
COMMIT
SELECT me.ip, me.snmp_comm_rw, me.snmp_auth_tag_read, me.snmp_auth_tag_write
  FROM community me
WHERE me.ip = '10.118.106.231'
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.37
SNMP::Info::device_type() layers:01001111 id:388 sysDescr:"AP6532 Access Point, Version 5.8.4.0-034R MIB=01a"
SNMP::Info::_load_attr ip_index : IP-MIB::ipAdEntIfIndex : .1.3.6.1.2.1.4.20.1.2
SNMP::Info::_load_attr i_index : IF-MIB::ifIndex : .1.3.6.1.2.1.2.2.1.1
SNMP::Info::_load_attr i_description : IF-MIB::ifDescr : .1.3.6.1.2.1.2.2.1.2
SNMP::Info::_load_attr ip_netmask : IP-MIB::ipAdEntNetMask : .1.3.6.1.2.1.4.20.1.3
[9457] 2017-08-18 13:46:42 debug  [10.118.106.231] device - aliased as 169.254.200.44
[9457] 2017-08-18 13:46:42 debug  [10.118.106.231] device - aliased as 10.118.118.250
[9457] 2017-08-18 13:46:42 debug  [10.118.106.231] device - aliased as 10.118.106.231
[9457] 2017-08-18 13:46:42 debug  [10.118.106.231] device - aliased as 10.118.120.250
[9457] 2017-08-18 13:46:42 debug  [10.118.106.231] device - aliased as 10.118.0.231
[9457] 2017-08-18 13:46:42 debug  [10.118.106.231] device - aliased as 10.118.119.250
[9457] 2017-08-18 13:46:42 debug  resolving 6 aliases with max 50 outstanding requests
SNMP::Info::_validate_autoload_method(vtp_d_name) Unable to resolve method.
SNMP::Info::_global name : SNMPv2-MIB::sysName.0 : .1.3.6.1.2.1.1.5.0
SNMP::Info::_global ports : IF-MIB::ifNumber.0 : .1.3.6.1.2.1.2.1.0
SNMP::Info::_global mac : IF-MIB::ifPhysAddress.1 : .1.3.6.1.2.1.2.2.1.6.1
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_global(mac) NOSUCHINSTANCE at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 186.
SNMP::Info::_validate_autoload_method(ps1_type) Unable to resolve method.
SNMP::Info::_validate_autoload_method(ps2_type) Unable to resolve method.
SNMP::Info::_validate_autoload_method(ps1_status) Unable to resolve method.
SNMP::Info::_validate_autoload_method(ps2_status) Unable to resolve method.
SNMP::Info::_validate_autoload_method(fan) Unable to resolve method.
SNMP::Info::_validate_autoload_method(slots) Unable to resolve method.
SNMP::Info::_validate_autoload_method(os) Unable to resolve method.
SNMP::Info::_validate_autoload_method(os_ver) Unable to resolve method.
SNMP::Info::_global serial1 : CISCO-SMI::temporary.6.3.0 : .1.3.6.1.4.1.9.3.6.3.0
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_global(serial1) NOSUCHOBJECT at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 190.
SNMP::Info::_load_attr e_parent : ENTITY-MIB::entPhysicalContainedIn : .1.3.6.1.2.1.47.1.1.1.1.4
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 190.
SNMP::Info::_global contact : SNMPv2-MIB::sysContact.0 : .1.3.6.1.2.1.1.4.0
SNMP::Info::_global location : SNMPv2-MIB::sysLocation.0 : .1.3.6.1.2.1.1.6.0
BEGIN WORK
DELETE FROM device_ip
WHERE ip = '10.118.106.231'
[9457] 2017-08-18 13:46:48 debug  [10.118.106.231] device - removed 6 aliases
SAVEPOINT savepoint_0
UPDATE device
  SET last_discover = now(  ), uptime = '1779366100'
WHERE ip = '10.118.106.231'
RELEASE SAVEPOINT savepoint_0
SAVEPOINT savepoint_0
INSERT INTO device_ip( alias, dns, ip, port, subnet )
  VALUES( ?, ?, ?, ?, ? ) : '__BULK_INSERT__'
RELEASE SAVEPOINT savepoint_0
[9457] 2017-08-18 13:46:48 debug  [10.118.106.231] device - added 6 new aliases
COMMIT
SNMP::Info::_load_attr i_type : IF-MIB::ifType : .1.3.6.1.2.1.2.2.1.3
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 223.
SNMP::Info::_validate_autoload_method(i_ignore) Unable to resolve method.
SNMP::Info::_load_attr i_mtu : IF-MIB::ifMtu : .1.3.6.1.2.1.2.2.1.4
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 226.
SNMP::Info::_load_attr orig_i_speed : IF-MIB::ifSpeed : .1.3.6.1.2.1.2.2.1.5
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 227.
SNMP::Info::_load_attr i_mac : IF-MIB::ifPhysAddress : .1.3.6.1.2.1.2.2.1.6
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 228.
SNMP::Info::_load_attr i_up : IF-MIB::ifOperStatus : .1.3.6.1.2.1.2.2.1.8
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 229.
SNMP::Info::_load_attr i_up_admin : IF-MIB::ifAdminStatus : .1.3.6.1.2.1.2.2.1.7
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 230.
SNMP::Info::_load_attr i_alias : IF-MIB::ifAlias : .1.3.6.1.2.1.31.1.1.1.18
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 231.
SNMP::Info::_load_attr orig_i_name : IF-MIB::ifName : .1.3.6.1.2.1.31.1.1.1.1
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 231.
SNMP::Info::_load_attr el_index : EtherLike-MIB::dot3StatsIndex : .1.3.6.1.2.1.10.7.2.1.1
SNMP::Info::_load_attr el_duplex : EtherLike-MIB::dot3StatsDuplexStatus : .1.3.6.1.2.1.10.7.2.1.19
SNMP::Info::_validate_autoload_method(i_duplex_admin) Unable to resolve method.
SNMP::Info::_load_attr bp_index : BRIDGE-MIB::dot1dBasePortIfIndex : .1.3.6.1.2.1.17.1.4.1.2
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 234.
SNMP::Info::_load_attr stp_p_state : BRIDGE-MIB::dot1dStpPortState : .1.3.6.1.2.1.17.2.15.1.3
SNMP::Info::_load_attr bp_index : BRIDGE-MIB::dot1dBasePortIfIndex : .1.3.6.1.2.1.17.1.4.1.2
SNMP::Info::_load_attr qb_i_vlan : Q-BRIDGE-MIB::dot1qPvid : .1.3.6.1.2.1.17.7.1.4.5.1.1
SNMP::Info::_load_attr i_lastchange : IF-MIB::ifLastChange : .1.3.6.1.2.1.2.2.1.9
SNMP::Info::_validate_autoload_method(agg_ports) Unable to resolve method.
SNMP::Info::_global load_uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global snmpEngineTime : SNMP-FRAMEWORK-MIB::snmpEngineTime.0 : .1.3.6.1.6.3.10.2.1.3.0
BEGIN WORK
DELETE FROM device_port_power
WHERE ip IN (
    SELECT me.ip
      FROM device_port me
    WHERE me.ip = '10.118.106.231'
   )
DELETE FROM device_port_vlan
WHERE ip IN (
    SELECT me.ip
      FROM device_port me
    WHERE me.ip = '10.118.106.231'
   )
DELETE FROM device_port_wireless
WHERE ip IN (
    SELECT me.ip
      FROM device_port me
    WHERE me.ip = '10.118.106.231'
   )
DELETE FROM device_port_ssid
WHERE ip IN (
    SELECT me.ip
      FROM device_port me
    WHERE me.ip = '10.118.106.231'
   )
DELETE FROM device_port
WHERE ip = '10.118.106.231'
[9457] 2017-08-18 13:47:23 debug  [10.118.106.231] interfaces - removed 0 interfaces
SAVEPOINT savepoint_0
RELEASE SAVEPOINT savepoint_0
SAVEPOINT savepoint_0
INSERT INTO device_port( descr, duplex, duplex_admin, ip, is_master, lastchange, mac, mtu, name, port, pvid, slave_of, speed, stp, type, up, up_admin, vlan )
  VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) : '__BULK_INSERT__'
RELEASE SAVEPOINT savepoint_0
[9457] 2017-08-18 13:47:23 debug  [10.118.106.231] interfaces - added 9 new interfaces
COMMIT
SNMP::Info::_validate_autoload_method(i_ssidlist) Unable to resolve method.
SNMP::Info::_load_attr v_name : Q-BRIDGE-MIB::dot1qVlanStaticName : .1.3.6.1.2.1.17.7.1.4.3.1.1
SNMP::Info::_load_attr v_name : Q-BRIDGE-MIB::dot1qVlanStaticName : .1.3.6.1.2.1.17.7.1.4.3.1.1
SNMP::Info::_load_attr qb_i_vlan : Q-BRIDGE-MIB::dot1qPvid : .1.3.6.1.2.1.17.7.1.4.5.1.1
SNMP::Info::_load_attr qb_cv_egress : Q-BRIDGE-MIB::dot1qVlanCurrentEgressPorts : .1.3.6.1.2.1.17.7.1.4.2.1.4
SNMP::Info::_load_attr qb_v_egress : Q-BRIDGE-MIB::dot1qVlanStaticEgressPorts : .1.3.6.1.2.1.17.7.1.4.3.1.2
SNMP::Info::_validate_autoload_method(i_vlan_type) Unable to resolve method.
BEGIN WORK
DELETE FROM device_vlan
WHERE ip = '10.118.106.231'
[9457] 2017-08-18 13:47:33 debug  [10.118.106.231] vlans - removed 0 device VLANs
[9457] 2017-08-18 13:47:33 debug  [10.118.106.231] vlans - added 0 new device VLANs
COMMIT
BEGIN WORK
DELETE FROM device_port_vlan
WHERE ip = '10.118.106.231'
[9457] 2017-08-18 13:47:33 debug  [10.118.106.231] vlans - removed 0 port VLANs
[9457] 2017-08-18 13:47:33 debug  [10.118.106.231] vlans - added 0 new port VLANs
COMMIT
SNMP::Info::_load_attr peth_power_watts : POWER-ETHERNET-MIB::pethMainPsePower : .1.3.6.1.2.1.105.1.3.1.1.2
SNMP::Info::_load_attr peth_power_status : POWER-ETHERNET-MIB::pethMainPseOperStatus : .1.3.6.1.2.1.105.1.3.1.1.3
[9457] 2017-08-18 13:47:33 debug  [10.118.106.231] power - 0 power modules
SNMP::Info::_load_attr entPhysicalDescr : ENTITY-MIB::entPhysicalDescr : .1.3.6.1.2.1.47.1.1.1.1.2
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 610.
BEGIN WORK
DELETE FROM device_module
WHERE ip = '10.118.106.231'
[9457] 2017-08-18 13:47:36 debug  [10.118.106.231] modules - removed 1 chassis modules
SELECT me.ip, me.index, me.description, me.type, me.parent, me.name, me.class, me.pos, me.hw_ver, me.fw_ver, me.sw_ver, me.serial, me.model, me.fru, me.creation, me.last_discover
  FROM device_module me
WHERE me.index = '1' AND me.ip = '10.118.106.231'
INSERT INTO device_module( class, fru, index, ip, last_discover, model, name, parent, pos, serial, sw_ver )
  VALUES( 'chassis', false, '1', '10.118.106.231', now(  ), 'enterprises.388.50.1.1.4', 'chassis', '0', '-1', NULL, NULL )
COMMIT
[9457] 2017-08-18 13:47:36 debug  [10.118.106.231] modules - 0 chassis components (added one pseudo for chassis)
BEGIN WORK
UPDATE device_port
  SET manual_topo = false
WHERE ip = '10.118.106.231'
[9457] 2017-08-18 13:47:36 debug  [10.118.106.231] neigh - setting manual topology links
SELECT me.dev1, me.port1, me.dev2, me.port2
  FROM topology me
WHERE dev1 = '10.118.106.231' OR dev2 = '10.118.106.231'
COMMIT
SNMP::Info::_global lldp_sys_cap : LLDP-MIB::lldpLocSysCapEnabled.0 : .1.0.8802.1.1.2.1.3.6.0
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_global(lldp_sys_cap) NOSUCHOBJECT at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 710.
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 710.
SNMP::Info::_validate_autoload_method(hasCDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
[9457] 2017-08-18 13:47:39 debug  [10.118.106.231] neigh - neighbor protocols are not enabled
[9457] 2017-08-18 13:47:39  info discover: finished at Fri Aug 18 15:47:39 2017
[9457] 2017-08-18 13:47:39  info discover: status done: Ended discover for 10.118.106.231
`

**Comment by crossonrose** [comment]
Thankd dad.
