### ISSUE TITLE
Job Queue Add Hostname or FQDN 

### ISSUE THREAD

**Issue by michaelcrandolph** [netdisco/netdisco#342]
## Expected Behavior
It would be nice to show the hostname or FQDN of the device being scanned

## Current Behavior
Current devices in the Job Queue only show the IP address that's be scanned

## Possible Solution
* Add addition column or option to toggle on/off to see other fields in the Job Queue table
* Add a filter or search for looking through a large job queue
* Add option to select multiple jobs to delete, pause, or re-run

## Your Environment
* Netdisco version used: 2.36.9
* SNMP::Info version used: 3.37

**Comment by rc9000** [comment]
+1 it would be really nice to have a better job queue with filters etc, the current page is not very helpful in large networks. 

Also some queue overview would be nice, e.g. show the slowest jobs from admin:


```
with dur as (
    select device, action, entered, started, finished, finished - started as duration from admin where status = 'done' order by 6 desc
)
select dur.*, d.dns, d.model from dur 
join device d on dur.device = d.ip
```

Or number of open jobs in queue by type 

```
netdisco=> select status, action, count(*) from admin where status = 'queued' group by status, action;
 status |  action  | count
--------+----------+-------
 queued | discover |  1199
 queued | arpnip   |   844
 queued | macsuck  |  1013
```

**Comment by ollyg** [comment]
Hi @rc9000 - note that there is the "Poller Performance" report which sort-of shows the slowest jobs. You can find this under the admin menu or at `/admin/performance`.

**Comment by ollyg** [comment]
I think one of the reasons I never developed the job queue further is that on many installations it has a very very high rate of churn. By the time you see a job and do something with it... the job has changed status! (completed)

**Comment by rc9000** [comment]
Thanks I've never noticed this Poller Performance report before!

**Comment by michaelcrandolph** [comment]
Thanks OllyG

**Comment by ollyg** [comment]
implemented "Job Queue Add Hostname or FQDN" for the next release
