### ISSUE TITLE
Update Developers Manual

### ISSUE THREAD

**Issue by michaelcrandolph** [netdisco/netdisco#345]
Is there any documentation for migrating a live install from https://metacpan.org/pod/App::Netdisco to the https://github.com/netdisco/netdisco repository. I'd prefer to have the flexibility to grab some of the latest commits easily using git pull.

## Your Environment
* Netdisco version used: 2.36.9
* SNMP::Info version used: 3.37

**Comment by ollyg** [comment]
Yeah, sort of:

https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Developing.pod#TLDR;-I-want-to-clone-git-and-run-the-web-server.

**Comment by ollyg** [comment]
That page needs updating for:
* new files layout in repo
* new git repo url

**Comment by ollyg** [comment]
Now done:
https://github.com/netdisco/netdisco/wiki/Developing#tldr-i-just-want-to-clone-the-repo-and-get-started
