### ISSUE TITLE
Questions about installation

### ISSUE THREAD

**Issue by S0t0nN3rdS** [netdisco/netdisco#347]
Im a noodbto linux and this sort of config, but have installed Ubuntu on VMware, lamp server etc.. then all of the required dependencies.  Ran into a few issues along the way but was able to overcome them, and the install appeared to all go ok.

Started up netdisco and backend.. but not entirely sure how to now access the frontend!  If I connect to localhost, I just get the apache2 homepage...

Ive looked in the netdisco dir, but cant find anything...

Sorry for this dumb quesiton, but having spent about 4 hours setting it up, I would like to at least see the website!

Thanks

**Comment by ollyg** [comment]
The service is at localhost on TCP port 5000.

So you usually put something like `http://localhost:5000/` into your web browser.

There is no need for Apache initially as the application has its own web server. You can add Apache as a reverse proxy according to the instructions linked online.

I hope that helps!

**Comment by S0t0nN3rdS** [comment]
Nope.. that didnt work.. think Ill have to go over the setup guide again... maybe start afresh!

Thanks for your prompt respons though!

**Comment by ollyg** [comment]
Hi @S0t0nN3rdS can I check you are following the instructions at https://metacpan.org/pod/App::Netdisco ?

**Comment by LBegnaud** [comment]
I see a few docker images in the wild for netdisco.

@ollyg any chance we get an official build from you guys? :)

**Comment by S0t0nN3rdS** [comment]
Hi, hitting a few brick walls agian.. could I query a few of the instructions:

root:~# useradd -m -p x -s /bin/bash netdisco
Should the x here be a user defined password?

mkdir ~/environments
cp ~/perl5/lib/perl5/auto/share/dist/App-Netdisco/environments/deployment.yml ~/environments
chmod 600 ~/environments/deployment.yml

Despite doing this, im not able to edit the file.  

When running through some of the commands, I seem to be getting asked for passwords which I dont recall setting up.  Perhaps I am trying to run some of the commands when under the wrong account in the terminal. 

Im  not familiar with linux, so its a lot of trial and error!

Thanks

**Comment by ollyg** [comment]
@LBegnaud unfortunately I have no time (or skill!) for docker images or VM images, but I would welcome someone to work on it and hang out in the IRC channel to allow us to help make it a success.

**Comment by ollyg** [comment]
@S0t0nN3rdS glad you are making progress.

The x is a literal x and has the effect of preventing any password login to the account (see "man useradd" and "man shadow" for details). You can sudo to the account from root, or assign a password.

Commands in the instructions where the command prompt has "#" should be run as root user. All other commands should be run as the netdisco user. Perhaps the issue you had is that you ran the commands as root user instead of netdisco?

**Comment by S0t0nN3rdS** [comment]
Thanks for the help.. really appreciated!  I was able to figure most bits out and have now got things up and running!  

I have set up 2 test switches, one a L3 router (Cisco 3850X), the other L2 switch (Cisco 2960X), and configured snmpv2..  whilst I can see snmp info, Im not seeing any info about connected devices.  Is there anything else I need to do to read mac address/arp info?

I was hoping/expecting to be able to see the mac/ip of end devices, regardless of what vlans they may be on.

Thanks again!

**Comment by S0t0nN3rdS** [comment]
I am making some progress... have now got v3 working, but did struggle for a while until I found another article...  Info on your site suggests this format for snmp_auth config:

snmp_auth:
   - community: public
   - community: publictwo
   - community: mycommunity
     write: true
   - community: mycommunity2
     read: false
     write: true
   - tag: v3example
     user: netdisco
     auth:
       pass: netdiscokey
       proto: MD5
     priv:
       pass: netdiscokey2
       proto: DES
   - tag: v3aclexample
     user: netdisco2
     only:
       - 192.0.2.0/30
       - 172.20.10.0/24
   - tag: v2aclexample
     community: s3kr1t
     read: false
     write: true
     only:
       - 2001:db8::/32

But couldnt get it working so started looking about then spotted somewhere else that the passwords needed to be wrappen in a single quote.. which seemed to work...

snmp_auth:
   - tag: v3example
     user: myusername
     auth:
       pass: 'password1'
       proto: SHA
     priv:
       pass: 'secret2'
       proto: AES128

However, still dont seem to be getting any mac/ip/arp info for connected devices.. should I be able to see this info the PC's, printers etc.. that are connected to the ports, regardless of vlan?
