### ISSUE TITLE
Unused port reporting

### ISSUE THREAD

**Issue by S0t0nN3rdS** [netdisco/netdisco#349]
Is it possible to query or produce any reports that identify unused ports and when they were last used, so they can be re-allocated to minimize port wastage?

Viewing the last input/output stats on switches isnt always accurate, but as this db is building up historical data, is it possible to then view ports where devices have not been seen on the interfaces, or have simply been down for a certain period?

Thanks

**Comment by JeroenvIS** [comment]
As a start, please check out the report under Reports -> Device -> Port Utilization. It reports the number of free ports per switch. IIRC in this report, a port is "free" is the switch has been up for more than 3 months and the "last change" of the port (so last time the switch recorded an event for the link going up or down) is more than 3 months ago.

**Comment by JeroenvIS** [comment]
That's mostly for a global view; you can get a more fine-grained view on each switch in the Ports tab. For example, when viewing the ports:
- Make sure that the column for last change is shown (tick the box); consider also sorting by the values of that column
- Have it display neighbor information, but by MAC addr only (no NetBIOS, IPv4 or IPv6 addresses), and have Netdisco display the timestamp when that MAC was last seen
- You can limit the view by displaying only ports that are free, or both free and down
- In this view, the time period that a port has been down before it's marked as free is configurable

**Comment by S0t0nN3rdS** [comment]
Thanks!  Only got ND up and running yesterday, so still fumbling my way through.. but its a fantastic tool, and does exactly what we were looking for!
