### ISSUE TITLE
User Reports should create DBIC Result Classes properly

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#35]
Currently it's a great dirty hack.

lib/App/Netdisco/Web/GenericReport.pm

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/37](https://sourceforge.net/p/netdisco/nd2-features/37)

**Comment by ollyg** [comment]
Yeah, but the dirty hack works well, @ollyg. Closing and moving to wishlist page in wiki.
