### ISSUE TITLE
Docker implementation

### ISSUE THREAD

**Issue by LBegnaud** [netdisco/netdisco#350]
I'm interested in building a docker image for this project. We use it extensively and I'd like to make it simpler to manage and update. Would you like me to do it in my own repo until I get it cleaned up, or would you like to make a repo for me to push changes to?

I've done a couple automated builds in https://hub.docker.com/ and think that might be a good way to go about this.

We can setup multiple tags or branches that build separately.

I can't guarantee a timely setup of this, but I'd like to assist in making it an official build (as opposed to the various unofficial docker images of this project).

**Comment by ollyg** [comment]
Hi, I've created https://github.com/netdisco/netdisco-docker

And invited you to the developers group for the project. Welcome on board! :-)

**Comment by alanbuxey** [comment]
Nice :)
