### ISSUE TITLE
macsuck & artnip on old switches

### ISSUE THREAD

**Issue by S0t0nN3rdS** [netdisco/netdisco#351]
Im assuming that these switches may just be a little too old for netdisco to be able to obtain these results, so not really an application issue, but just wondered if any other way for ND to obtain the info?

Vendor / Model	cisco / 295024
OS / Version	ios / 12.1(22)EA14

The snmpv3 context vlan commands dont work, and Ive also set up v2c wondering if this method may yield the results, but no...  

Im aware how old these devices are, and we are refreshing them, but for now, would be good to know whats plugged into the interfaces.

Cheers

**Comment by JeroenvIS** [comment]
I'd expect 2950's to work, at least with SNMP v2c or v1...
Could be worth to run a discover and macsuck for one of these from the command line, with debugging on.
eg 'netdisco-do discover -d <device> -DI'

**Comment by S0t0nN3rdS** [comment]
Ill give this a go thanks...  

Can I modify the command to just rediscover a single device, rather than full discovery?

**Comment by JeroenvIS** [comment]
Oh, you're right, I forgot something: following the '-d' argument, you can specify a device IP or FQDN (or even a known device name iirc) to discover just one device.
eg 'netdisco-do discover -d <device> -DI' for discover, and 'netdisco-do macsuck -d <device> -DI' for macsuck.

**Comment by S0t0nN3rdS** [comment]
receiving this error:

netdisco-db: command not found
 
Running the command via termianl from netdisco acc..  please excuse my noobness if Im doing something wrong, as ive little experience with linux!

**Comment by ollyg** [comment]
So as netdisco user:
```
~/bin/netdisco-do discover -d 1.2.3.4 -DI
```
(and that is do not db). Where 1.2.3.4 is the device IP.

**Comment by S0t0nN3rdS** [comment]
That nailed it, thanks!

Im seeing a lot of "unable to resolve method" messages.. although it does look like its pullling some info, so comms seem to be ok...

[47156] 2017-10-03 08:24:26  info discover: [1.2.3.4] started at Tue Oct  3 04:24:26 2017
[47156] 2017-10-03 08:24:26 debug [1.2.3.4] try_connect with ver: 3, class: SNMP::Info::Layer2::C2900, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.37
SNMP::Info::device_type() layers:00000010 id:9 sysDescr:"Cisco Internetwork Operating System Software  IOS (tm) C2950 Software (C2950-I6K2L2Q4-M), Version 12.1(22)EA14, RELEASE SOFTWARE (fc1) Technical Support: http://www.cisco.com/techsupport Copyright (c) 1986-2010 by cisco Systems, Inc. Compiled Tue 26-O"
SNMP::Info::_load_attr ip_index : IP-MIB::ipAdEntIfIndex : .1.3.6.1.2.1.4.20.1.2
SNMP::Info::_load_attr i_index : IF-MIB::ifIndex : .1.3.6.1.2.1.2.2.1.1
SNMP::Info::_load_attr i_description : IF-MIB::ifDescr : .1.3.6.1.2.1.2.2.1.2
SNMP::Info::_load_attr ip_netmask : IP-MIB::ipAdEntNetMask : .1.3.6.1.2.1.4.20.1.3
[47156] 2017-10-03 08:24:28 debug  [1.2.3.4] device - aliased as 1.2.3.4
[47156] 2017-10-03 08:24:28 debug  resolving 1 aliases with max 50 outstanding requests
SNMP::Info::_load_attr vtp_d_name : CISCO-VTP-MIB::managementDomainName : .1.3.6.1.4.1.9.9.46.1.2.1.1.2
SNMP::Info::_global name : SNMPv2-MIB::sysName.0 : .1.3.6.1.2.1.1.5.0
SNMP::Info::_global ports : IF-MIB::ifNumber.0 : .1.3.6.1.2.1.2.1.0
SNMP::Info::_validate_autoload_method(mac) Unable to resolve method.
SNMP::Info::_validate_autoload_method(ps1_type) Unable to resolve method.
SNMP::Info::_validate_autoload_method(ps2_type) Unable to resolve method.
SNMP::Info::_validate_autoload_method(ps1_status) Unable to resolve method.
SNMP::Info::_validate_autoload_method(ps2_status) Unable to resolve method.
SNMP::Info::_validate_autoload_method(fan) Unable to resolve method.
SNMP::Info::_validate_autoload_method(slots) Unable to resolve method.
SNMP::Info::_global serial1 : CISCO-SMI::temporary.6.3.0 : .1.3.6.1.4.1.9.3.6.3.0
SNMP::Info::_load_attr e_descr : ENTITY-MIB::entPhysicalDescr : .1.3.6.1.2.1.47.1.1.1.1.2
SNMP::Info::_load_attr e_serial : ENTITY-MIB::entPhysicalSerialNum : .1.3.6.1.2.1.47.1.1.1.1.11
SNMP::Info::_global contact : SNMPv2-MIB::sysContact.0 : .1.3.6.1.2.1.1.4.0
SNMP::Info::_global location : SNMPv2-MIB::sysLocation.0 : .1.3.6.1.2.1.1.6.0
[47156] 2017-10-03 08:24:29 debug  [1.2.3.4] device - removed 1 aliases
[47156] 2017-10-03 08:24:29 debug  [1.2.3.4] device - added 1 new aliases
SNMP::Info::_load_attr i_type : IF-MIB::ifType : .1.3.6.1.2.1.2.2.1.3
SNMP::Info::_validate_autoload_method(i_ignore) Unable to resolve method.
SNMP::Info::_load_attr i_mtu : IF-MIB::ifMtu : .1.3.6.1.2.1.2.2.1.4
SNMP::Info::_load_attr orig_i_speed : IF-MIB::ifSpeed : .1.3.6.1.2.1.2.2.1.5
SNMP::Info::_load_attr i_speed_high : IF-MIB::ifHighSpeed : .1.3.6.1.2.1.31.1.1.1.15
SNMP::Info::_load_attr i_mac : IF-MIB::ifPhysAddress : .1.3.6.1.2.1.2.2.1.6
SNMP::Info::_load_attr i_up : IF-MIB::ifOperStatus : .1.3.6.1.2.1.2.2.1.8
SNMP::Info::_load_attr i_up_admin : IF-MIB::ifAdminStatus : .1.3.6.1.2.1.2.2.1.7
SNMP::Info::_load_attr i_name : IF-MIB::ifAlias : .1.3.6.1.2.1.31.1.1.1.18
SNMP::Info::_load_attr c2900_p_index : CISCO-C2900-MIB::c2900PortIfIndex : .1.3.6.1.4.1.9.9.87.1.4.1.1.25
SNMP::Info::_load_attr c2900_p_duplex : CISCO-C2900-MIB::c2900PortDuplexStatus : .1.3.6.1.4.1.9.9.87.1.4.1.1.32
SNMP::Info::_load_attr c2900_p_duplex_admin : CISCO-C2900-MIB::c2900PortDuplexState : .1.3.6.1.4.1.9.9.87.1.4.1.1.31
SNMP::Info::_load_attr bp_index : BRIDGE-MIB::dot1dBasePortIfIndex : .1.3.6.1.2.1.17.1.4.1.2
SNMP::Info::_load_attr stp_p_state : BRIDGE-MIB::dot1dStpPortState : .1.3.6.1.2.1.17.2.15.1.3
SNMP::Info::_load_attr vtp_trunk_native : CISCO-VTP-MIB::vlanTrunkPortNativeVlan : .1.3.6.1.4.1.9.9.46.1.6.1.1.5
SNMP::Info::_load_attr i_vlan2 : CISCO-VLAN-MEMBERSHIP-MIB::vmVlan : .1.3.6.1.4.1.9.9.68.1.2.2.1.2
SNMP::Info::_load_attr vtp_trunk_dyn : CISCO-VTP-MIB::vlanTrunkPortDynamicState : .1.3.6.1.4.1.9.9.46.1.6.1.1.13
SNMP::Info::_load_attr vtp_trunk_dyn_stat : CISCO-VTP-MIB::vlanTrunkPortDynamicStatus : .1.3.6.1.4.1.9.9.46.1.6.1.1.14
SNMP::Info::_load_attr v_cvi_if : CISCO-VLAN-IFTABLE-RELATIONSHIP-MIB::cviRoutedVlanIfIndex : .1.3.6.1.4.1.9.9.128.1.1.1.1.3
SNMP::Info::_load_attr i_lastchange : IF-MIB::ifLastChange : .1.3.6.1.2.1.2.2.1.9
SNMP::Info::_load_attr pagpGroupIfIndex : CISCO-PAGP-MIB::pagpGroupIfIndex : .1.3.6.1.4.1.9.9.98.1.1.1.1.8
SNMP::Info::_load_attr dot3adAggActorOperKey : IEEE8023-LAG-MIB::dot3adAggActorOperKey : .1.2.840.10006.300.43.1.1.1.1.7
SNMP::Info::_load_attr dot3adAggPortActorOperKey : IEEE8023-LAG-MIB::dot3adAggPortActorOperKey : .1.2.840.10006.300.43.1.2.1.1.5
SNMP::Info::_global load_uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global snmpEngineTime : SNMP-FRAMEWORK-MIB::snmpEngineTime.0 : .1.3.6.1.6.3.10.2.1.3.0
[47156] 2017-10-03 08:24:32  info  [1.2.3.4] interfaces - device uptime wrapped (FastEthernet0/19) - correcting
[47156] 2017-10-03 08:24:32 debug  [1.2.3.4] interfaces - correcting LastChange for FastEthernet0/10, assuming sysUptime wrap
[47156] 2017-10-03 08:24:32 debug  [1.2.3.4] interfaces - correcting LastChange for FastEthernet0/11, assuming sysUptime wrap
[47156] 2017-10-03 08:24:32 debug  [1.2.3.4] interfaces - correcting LastChange for FastEthernet0/13, assuming sysUptime wrap
[47156] 2017-10-03 08:24:32 debug  [1.2.3.4] interfaces - correcting LastChange for FastEthernet0/16, assuming sysUptime wrap
[47156] 2017-10-03 08:24:32 debug  [1.2.3.4] interfaces - removed 27 interfaces
[47156] 2017-10-03 08:24:32 debug  [1.2.3.4] interfaces - added 27 new interfaces
SNMP::Info::_validate_autoload_method(i_ssidlist) Unable to resolve method.
SNMP::Info::_load_attr v_name : CISCO-VTP-MIB::vtpVlanName : .1.3.6.1.4.1.9.9.46.1.3.1.1.4
SNMP::Info::_load_attr v_cvi_if : CISCO-VLAN-IFTABLE-RELATIONSHIP-MIB::cviRoutedVlanIfIndex : .1.3.6.1.4.1.9.9.128.1.1.1.1.3
SNMP::Info::_load_attr vtp_trunk_vlans : CISCO-VTP-MIB::vlanTrunkPortVlansEnabled : .1.3.6.1.4.1.9.9.46.1.6.1.1.4
SNMP::Info::_load_attr vtp_trunk_vlans_2k : CISCO-VTP-MIB::vlanTrunkPortVlansEnabled2k : .1.3.6.1.4.1.9.9.46.1.6.1.1.17
SNMP::Info::_load_attr vtp_trunk_vlans_3k : CISCO-VTP-MIB::vlanTrunkPortVlansEnabled3k : .1.3.6.1.4.1.9.9.46.1.6.1.1.18
SNMP::Info::_load_attr vtp_trunk_vlans_4k : CISCO-VTP-MIB::vlanTrunkPortVlansEnabled4k : .1.3.6.1.4.1.9.9.46.1.6.1.1.19
SNMP::Info::_load_attr v_state : CISCO-VTP-MIB::vtpVlanState : .1.3.6.1.4.1.9.9.46.1.3.1.1.2
SNMP::Info::_load_attr i_voice_vlan : CISCO-VLAN-MEMBERSHIP-MIB::vmVoiceVlanId : .1.3.6.1.4.1.9.9.68.1.5.1.1.1
SNMP::Info::_load_attr i_vlan_type : CISCO-VLAN-MEMBERSHIP-MIB::vmVlanType : .1.3.6.1.4.1.9.9.68.1.2.2.1.1
[47156] 2017-10-03 08:24:34 debug  [1.2.3.4] vlans - removed 6 device VLANs
[47156] 2017-10-03 08:24:34 debug  [1.2.3.4] vlans - added 6 new device VLANs
[47156] 2017-10-03 08:24:34 debug  [1.2.3.4] vlans - removed 0 port VLANs
[47156] 2017-10-03 08:24:34 debug  [1.2.3.4] vlans - added 24 new port VLANs
SNMP::Info::_load_attr peth_power_watts : POWER-ETHERNET-MIB::pethMainPsePower : .1.3.6.1.2.1.105.1.3.1.1.2
SNMP::Info::_load_attr peth_power_status : POWER-ETHERNET-MIB::pethMainPseOperStatus : .1.3.6.1.2.1.105.1.3.1.1.3
[47156] 2017-10-03 08:24:34 debug  [1.2.3.4] power - 0 power modules
SNMP::Info::_load_attr entPhysicalDescr : ENTITY-MIB::entPhysicalDescr : .1.3.6.1.2.1.47.1.1.1.1.2
SNMP::Info::_load_attr e_type : ENTITY-MIB::entPhysicalVendorType : .1.3.6.1.2.1.47.1.1.1.1.3
SNMP::Info::_load_attr e_parent : ENTITY-MIB::entPhysicalContainedIn : .1.3.6.1.2.1.47.1.1.1.1.4
SNMP::Info::_load_attr e_name : ENTITY-MIB::entPhysicalName : .1.3.6.1.2.1.47.1.1.1.1.7
SNMP::Info::_load_attr e_class : ENTITY-MIB::entPhysicalClass : .1.3.6.1.2.1.47.1.1.1.1.5
SNMP::Info::_load_attr e_pos : ENTITY-MIB::entPhysicalParentRelPos : .1.3.6.1.2.1.47.1.1.1.1.6
SNMP::Info::_load_attr e_hwver : ENTITY-MIB::entPhysicalHardwareRev : .1.3.6.1.2.1.47.1.1.1.1.8
SNMP::Info::_load_attr e_fwver : ENTITY-MIB::entPhysicalFirmwareRev : .1.3.6.1.2.1.47.1.1.1.1.9
SNMP::Info::_load_attr e_swver : ENTITY-MIB::entPhysicalSoftwareRev : .1.3.6.1.2.1.47.1.1.1.1.10
SNMP::Info::_load_attr e_model : ENTITY-MIB::entPhysicalModelName : .1.3.6.1.2.1.47.1.1.1.1.13
SNMP::Info::_load_attr e_fru : ENTITY-MIB::entPhysicalIsFRU : .1.3.6.1.2.1.47.1.1.1.1.16
[47156] 2017-10-03 08:24:35 debug  [1.2.3.4] modules - removed 25 chassis modules
[47156] 2017-10-03 08:24:35 debug  [1.2.3.4] modules - added 25 new chassis modules
[47156] 2017-10-03 08:24:35 debug  [1.2.3.4] neigh - setting manual topology links
SNMP::Info::_global lldp_sys_cap : LLDP-MIB::lldpLocSysCapEnabled.0 : .1.0.8802.1.1.2.1.3.6.0
SNMP::Info::_validate_autoload_method(CARP_TRACE) Unable to resolve method.
SNMP::Info::_global(lldp_sys_cap) NOSUCHOBJECT at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Discover.pm line 710.
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_global cdp_run : CISCO-CDP-MIB::cdpGlobalRun.0 : .1.3.6.1.4.1.9.9.23.1.3.1.0
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(cdp_index : .1.3.6.1.4.1.9.9.23.1.2.1.1.1) Not accessable for requested operation.
SNMP::Info::_load_attr cdp_addr : CISCO-CDP-MIB::cdpCacheAddress : .1.3.6.1.4.1.9.9.23.1.2.1.1.4
SNMP::Info::_load_attr cdp_proto : CISCO-CDP-MIB::cdpCacheAddressType : .1.3.6.1.4.1.9.9.23.1.2.1.1.3
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr cdp_port : CISCO-CDP-MIB::cdpCacheDevicePort : .1.3.6.1.4.1.9.9.23.1.2.1.1.7
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr cdp_dev_id : CISCO-CDP-MIB::cdpCacheDeviceId : .1.3.6.1.4.1.9.9.23.1.2.1.1.6
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr cdp_platform : CISCO-CDP-MIB::cdpCachePlatform : .1.3.6.1.4.1.9.9.23.1.2.1.1.8
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr cdp_capabilities_raw : CISCO-CDP-MIB::cdpCacheCapabilities : .1.3.6.1.4.1.9.9.23.1.2.1.1.9
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
[47156] 2017-10-03 08:24:36 debug  [1.2.3.4] neigh - adding neighbor 1.2.3.1, type [cisco WS-C3750-24P], on FastEthernet0/24 to discovery queue
[47156] 2017-10-03 08:24:36  info discover: finished at Tue Oct  3 04:24:36 2017
[47156] 2017-10-03 08:24:36  info discover: status done: Ended discover for 1.2.3.4
netdisco@osboxes:/$
