### ISSUE TITLE
domain_suffix not stripping domains

### ISSUE THREAD

**Issue by S0t0nN3rdS** [netdisco/netdisco#352]
I have added our domain suffix (including the leading '.' in the hope it will remove the domain appended to the host name in the webui, but it doesn't seem to make any difference.  

domain_suffix: 'quite.a.long.internal.domain'

so seeing device.quite.a.long.internal.domain for all of our switches.

Any ideas?  Removing this would make a huge difference as it takes up alot of space!

**Comment by ollyg** [comment]
What I think is happening is that the domain_suffix is really only stripped in a few places in the interface, and I guess you still see it in many places. The one place to check is the neighbors tab of the device view - the neighbor names should not have the suffix.

We could certainly accept a patch for other templates, for example the port connected nodes in the Device Ports view. Most of the templates are in `share/views/ajax`, for example `share/views/ajax/device/ports.tt`.
