### ISSUE TITLE
Unplugged Devices for a long time are still visible

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#353]
Dear netdisco Developers,

I have got an issue with netdisco, some old unused devices are still visible even if they are no longer there.

The only way to remove them is to delete them manually.

I would like to know if there is some way to automatically remove then without human intervention.

Thank you,
Best Regards.

**Comment by JeroenvIS** [comment]
Yes, there is. By default, devices that can't be discovered/refreshed anymore are deleted ("expired") after 60 days. You can change this default in the config file, deployment.yml.

Please see https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Configuration.pod#expire_devices .

**Comment by def-bs** [comment]
Thank you!
