### ISSUE TITLE
Is it possible to customise the inventory screen?

### ISSUE THREAD

**Issue by S0t0nN3rdS** [netdisco/netdisco#354]
Just wondered if its possible to customize the way devices are displayed on the main inventory screen?

Currently, the default is By Platform and By Software Release, but I would love to have by SNMP Location, VTP domain (or other), so we can group all switches that reside in the same rack.

Thanks

**Comment by ollyg** [comment]
Hi, under the Reports menu and then Device, you can find a "By Location" report.

To add new reports, you can work out the SQL command and then put it into the deployment.yml file. So you run "netdisco-do psql" and then work out the SQL, and then use the "reports" feature:

https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Configuration.pod#reports

I appreciate this is not exactly trivial, but it's the best way once you get the hang of it.

**Comment by S0t0nN3rdS** [comment]
Thanks.. ill check it out!... 

I did find the location report, but it does display every device, rather than grouped, like the devices on the inventory page...  

Maybe I can get one of our dev team to look at the sql stuff!

Cheers!
