### ISSUE TITLE
Installing 2.036010 fails - missing perl module

### ISSUE THREAD

**Issue by jouluz** [netdisco/netdisco#355]
After installing 2.036010~/bin/netdisco-do does not work. Command gives me following error: 

Can't locate App/Netdisco/Util/Statistics.pm in @INC (@INC contains: /usr/local/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /usr/local/netdisco/perl5/lib /usr/local/netdisco/perl5/bin/lib /usr/local/netdisco/perl5/lib/perl5/x86_64-linux-thread-multi /usr/local/netdisco/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/netdisco/bin/netdisco-do line 127.
BEGIN failed--compilation aborted at /usr/local/netdisco/bin/netdisco-do line 127.

## Steps to Reproduce (for bugs)

1. ~/bin/localenv cpanm --notest App::Netdisco
2. ln -sf ~/perl5/bin/{localenv,netdisco-*} ~/bin/
3. ~/bin/netdisco-deploy (Answer y to all questions)
4. ~/bin/netdisco-do stats

-> Can't locate App/Netdisco/Util/Statistics.pm

## Your Environment

* Netdisco version used: 2.036010
* CentOS Linux release 7.4.1708 (Core)
* Perl v5.16.3

**Comment by ollyg** [comment]
Hi @jouluz 

Sorry about that - I have just released version 2.036011 to CPAN. If your local mirror does not have the file you can run this alternate command:

~netdisco/bin/localenv cpanm https://cpan.metacpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.036011.tar.gz

The error is that the MANIFEST file shipped was not updated. I'll look to see that we don't skip this in future.

regards,
Oliver.
