### ISSUE TITLE
expire_devices does not work

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#356]
Dear netdisco,

Some times ago I opened a request here asking how to remove faster the unused devices on netdisco, the solution was to add the option expire_devices 14 in deployment.yml.

In this way I hoped that every 14 days all the unplugged devices will be automatically removed, instead of the standard 60 days.

But it does not seem to work, Did i do something wrong with the configuration?

Thanks you.

Best Regards.

**Comment by ollyg** [comment]
Hi @def-bs please can you confirm that the last_discover date on the devices is not updating?

**Comment by ollyg** [comment]
...also that you are running the expire job in your backend? it should be included in the config.

**Comment by def-bs** [comment]
Could you please clarify? I am using the default configuration

**Comment by def-bs** [comment]
the last discover is updating. What i want is that devices that are no longer connected after some days, 14 days are automacally removed. I asked this question some time ago and they told me that they are removed after 60 days.

If I wanted the deviced deleted before I need to add expire_devices. But That didn't work.

**Comment by ollyg** [comment]
Hi. If the last_discover date for the device is updating then the device is still connected to your network and is being contacted by Netdisco. This date/time is shown in the Device Details tab of the Device view.

Yes, teh default configuration should run the expire job. You can also run this from the command line:
`~netdisco/bin/netdisco-do expire -D`

**Comment by def-bs** [comment]
Hi, Sorry I mean that the last_discover is working as a feature, on a disconnected device it is not updated.

**Comment by def-bs** [comment]
I have run ~netdisco/bin/netdisco-do expire -D  but nothig changed...

You know we run a very large network with thousands of devices, having some hanging devices that are no longer there is a issue for us. My boss asked a why to remove these unplugged devices.

If you could help I would be very grateful!

**Comment by ollyg** [comment]
Well you can delete the device manually using this command at the CLI:
https://metacpan.org/pod/distribution/App-Netdisco/bin/netdisco-do#delete

However it would be good for me to see the logs from running the expire command if possible, so I can try to see if this issue can be reproduced. Send the output here or to oliver@cpan.org if you prefer privacy:
`~netdisco/bin/netdisco-do expire -DQ`

**Comment by def-bs** [comment]
But perhaps I am doing something wrong in the config, the documentation about it is very simply. Where Should i put the "deployment.yml" and how should I write it. perhaps I have written it in the wrong place.

**Comment by ollyg** [comment]
I'm sure your deployment.yml is in the right place otherwise your Netdisco would not be able to connect to the database :-) however you can check - it should be in ~netdisco/environments/deployment.yml

**Comment by def-bs** [comment]
I mean where should i put the option expire_devices

**Comment by ollyg** [comment]
in the same deployment.yml file. something like:

`expire_devices: 14`

**Comment by def-bs** [comment]
My doubt was that I wrote it wrong because other configuration options are nested, for example: 

discover_no_type:
  - '(?i)phone'
  - '(?i)(?:wap|wireless)'


workers:
  tasks: 'AUTO * 2'

**Comment by ollyg** [comment]
Yes, these other options are lists, and the expire_devices is a single value. You can see a summary of the YAML format, here:
https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Configuration.pod#YAML-GUIDANCE

**Comment by def-bs** [comment]
Hi, I see that you put the ticket as closed.

I managed to make it work with the following:

expire_devices: 14
expire_nodes: 14
expire_nodes_archive: 14

Now, all the unplugged devices disappeared.

Thank you for your time. Best regards.

**Comment by taylor5042** [comment]
I have never been able to get netdisco to expire anything.
I have an sql query built where I delete anything old, but it would be nice
if the expire routines worked.

[removed ~]$ ~netdisco/bin/netdisco-do expire -DQ
[19727] 2017-11-17 03:11:36  info expire:  started at Thu Nov 16 20:11:36
2017
SELECT me.version, me.installed
  FROM dbix_class_schema_versions me
WHERE 1 = 0
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
BEGIN WORK
DELETE FROM device_ip
WHERE ip IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM device_vlan
WHERE ip IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM device_power
WHERE ip IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM device_module
WHERE ip IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM community
WHERE ip IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM admin
WHERE device IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM device_skip
WHERE device IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM topology
WHERE dev1 IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   ) OR dev2 IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM device_port_power
WHERE ip IN (
    SELECT me.ip
      FROM device_port me
    WHERE ip IN (
        SELECT me.ip
          FROM device me
        WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover
< ( now(  ) - '5184000' ::interval )
       )
   )
DELETE FROM device_port_vlan
WHERE ip IN (
    SELECT me.ip
      FROM device_port me
    WHERE ip IN (
        SELECT me.ip
          FROM device me
        WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover
< ( now(  ) - '5184000' ::interval )
       )
   )
DELETE FROM device_port_wireless
WHERE ip IN (
    SELECT me.ip
      FROM device_port me
    WHERE ip IN (
        SELECT me.ip
          FROM device me
        WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover
< ( now(  ) - '5184000' ::interval )
       )
   )
DELETE FROM device_port_ssid
WHERE ip IN (
    SELECT me.ip
      FROM device_port me
    WHERE ip IN (
        SELECT me.ip
          FROM device me
        WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover
< ( now(  ) - '5184000' ::interval )
       )
   )
DELETE FROM node_ip
WHERE mac IN (
    SELECT me.mac
      FROM node_ip me
      LEFT JOIN node nodes
        ON nodes.mac = me.mac
    WHERE nodes.active AND me.mac IN (
        SELECT me.mac
          FROM node me
        WHERE switch IN (
            SELECT me.ip
              FROM device_port me
            WHERE ip IN (
                SELECT me.ip
                  FROM device me
                WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND
last_discover < ( now(  ) - '5184000' ::interval )
               )
           )
       )
    GROUP BY me.mac
    HAVING count( nodes.mac ) = 0
   )
DELETE FROM node_nbt
WHERE mac IN (
    SELECT me.mac
      FROM node_nbt me
      LEFT JOIN node nodes
        ON nodes.mac = me.mac
    WHERE nodes.active AND me.mac IN (
        SELECT me.mac
          FROM node me
        WHERE switch IN (
            SELECT me.ip
              FROM device_port me
            WHERE ip IN (
                SELECT me.ip
                  FROM device me
                WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND
last_discover < ( now(  ) - '5184000' ::interval )
               )
           )
       )
    GROUP BY me.mac
    HAVING count( nodes.mac ) = 0
   )
DELETE FROM node_monitor
WHERE mac IN (
    SELECT me.mac
      FROM node me
    WHERE switch IN (
        SELECT me.ip
          FROM device_port me
        WHERE ip IN (
            SELECT me.ip
              FROM device me
            WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND
last_discover < ( now(  ) - '5184000' ::interval )
           )
       )
   )
DELETE FROM node_wireless
WHERE mac IN (
    SELECT me.mac
      FROM node me
    WHERE switch IN (
        SELECT me.ip
          FROM device_port me
        WHERE ip IN (
            SELECT me.ip
              FROM device me
            WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND
last_discover < ( now(  ) - '5184000' ::interval )
           )
       )
   )
DELETE FROM node
WHERE switch IN (
    SELECT me.ip
      FROM device_port me
    WHERE ip IN (
        SELECT me.ip
          FROM device me
        WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover
< ( now(  ) - '5184000' ::interval )
       )
   )
DELETE FROM device_port
WHERE ip IN (
    SELECT me.ip
      FROM device me
    WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
   )
DELETE FROM device
WHERE ( vendor IS NULL OR vendor != 'netdisco' ) AND last_discover < (
now(  ) - '5184000' ::interval )
COMMIT
BEGIN WORK
DELETE FROM node_ip
WHERE mac IN (
    SELECT me.mac
      FROM node_ip me
      LEFT JOIN node nodes
        ON nodes.mac = me.mac
    WHERE nodes.active AND me.mac IN (
        SELECT me.mac
          FROM node me
        WHERE time_last < ( now(  ) - '5184000' ::interval )
       )
    GROUP BY me.mac
    HAVING count( nodes.mac ) = 0
   )
DELETE FROM node_nbt
WHERE mac IN (
    SELECT me.mac
      FROM node_nbt me
      LEFT JOIN node nodes
        ON nodes.mac = me.mac
    WHERE nodes.active AND me.mac IN (
        SELECT me.mac
          FROM node me
        WHERE time_last < ( now(  ) - '5184000' ::interval )
       )
    GROUP BY me.mac
    HAVING count( nodes.mac ) = 0
   )
DELETE FROM node_monitor
WHERE mac IN (
    SELECT me.mac
      FROM node me
    WHERE time_last < ( now(  ) - '5184000' ::interval )
   )
DELETE FROM node_wireless
WHERE mac IN (
    SELECT me.mac
      FROM node me
    WHERE time_last < ( now(  ) - '5184000' ::interval )
   )
DELETE FROM node
WHERE time_last < ( now(  ) - '5184000' ::interval )
COMMIT
BEGIN WORK
DELETE FROM node_ip
WHERE mac IN (
    SELECT me.mac
      FROM node_ip me
      LEFT JOIN node nodes
        ON nodes.mac = me.mac
    WHERE nodes.active AND me.mac IN (
        SELECT me.mac
          FROM node me
        WHERE ( NOT active ) AND time_last < ( now(  ) - '5184000'
::interval )
       )
    GROUP BY me.mac
    HAVING count( nodes.mac ) = 0
   )
DELETE FROM node_nbt
WHERE mac IN (
    SELECT me.mac
      FROM node_nbt me
      LEFT JOIN node nodes
        ON nodes.mac = me.mac
    WHERE nodes.active AND me.mac IN (
        SELECT me.mac
          FROM node me
        WHERE ( NOT active ) AND time_last < ( now(  ) - '5184000'
::interval )
       )
    GROUP BY me.mac
    HAVING count( nodes.mac ) = 0
   )
DELETE FROM node_monitor
WHERE mac IN (
    SELECT me.mac
      FROM node me
    WHERE ( NOT active ) AND time_last < ( now(  ) - '5184000' ::interval )
   )
DELETE FROM node_wireless
WHERE mac IN (
    SELECT me.mac
      FROM node me
    WHERE ( NOT active ) AND time_last < ( now(  ) - '5184000' ::interval )
   )
DELETE FROM node
WHERE ( NOT active ) AND time_last < ( now(  ) - '5184000' ::interval )
COMMIT
BEGIN WORK
DELETE FROM admin
WHERE entered < ( now(  ) - '1209600' ::interval )
COMMIT
BEGIN WORK
SELECT me.day, me.device_count, me.device_ip_count, me.device_link_count,
me.device_port_count, me.device_port_up_count, me.ip_table_count,
me.ip_active_count, me.node_table_count, me.node_active_count,
me.netdisco_ver, me.snmpinfo_ver, me.schema_ver, me.perl_ver, me.pg_ver
  FROM statistics me
WHERE me.day = '2017-11-16'
UPDATE statistics
  SET device_count = (
    SELECT COUNT( * )
      FROM device me
   ), device_ip_count = (
    SELECT COUNT( * )
      FROM device_ip me
   ), device_link_count = (
    SELECT COUNT( * )
      FROM (
        SELECT dp.ip AS left_ip, dp.port AS left_port, di.ip AS right_ip,
dp.remote_port AS right_port
          FROM (
            SELECT device_port.ip, device_port.port, device_port.remote_ip,
device_port.remote_port
              FROM device_port
            WHERE device_port.remote_port IS NOT NULL
            GROUP BY device_port.ip, device_port.port,
device_port.remote_ip, device_port.remote_port
            ORDER BY device_port.ip
           ) dp
          LEFT JOIN device_ip di
            ON dp.remote_ip = di.alias
        WHERE di.ip IS NOT NULL
        ORDER BY dp.ip
       ) me
    WHERE me.left_ip > me.right_ip
   ), device_port_count = (
    SELECT COUNT( * )
      FROM device_port me
   ), device_port_up_count = (
    SELECT COUNT( * )
      FROM device_port me
    WHERE up = 'up'
   ), ip_active_count = (
    SELECT COUNT( * )
      FROM (
        SELECT me.ip
          FROM node_ip me
        WHERE active
        GROUP BY me.ip
       ) me
   ), ip_table_count = (
    SELECT COUNT( * )
      FROM node_ip me
   ), node_active_count = (
    SELECT COUNT( * )
      FROM (
        SELECT me.mac
          FROM node me
        WHERE active
        GROUP BY me.mac
       ) me
   ), node_table_count = (
    SELECT COUNT( * )
      FROM node me
   )
WHERE day = '2017-11-16'
COMMIT

**Comment by alanbuxey** [comment]
looks like your expiry is set to 60 days - so, do you have any devices that
arent being removed that have been offline for LONGER than 60 days?
those that have been offline for eg 45 days or 31 days etc will still be
present...they need to have not been contacted for more than $expire_days
before they go

alan

**Comment by taylor5042** [comment]
Right, and wouldn't entries from before September 17th be removed from the
table?

netdisco=> select * from node_ip order by time_last;
        mac        |       ip        | active |         time_first
 |         time_last          |
              dns
-------------------+-----------------+--------+----------------------------+----------------------------+---------------------
-----------------------------------------------------
 98:f1:70:9a:f5:19 | removed | f      | 2017-09-01 10:00:31.357359 |
2017-09-01 10:00:31.245542 |

netdisco=> select count(*) from node_ip where time_last::text like
'2017-09-0%';
 count
-------
 17551
(1 row)

**Comment by alanbuxey** [comment]
Devices , not nodes.

alan

**Comment by ollyg** [comment]
@taylor5042 https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Troubleshooting.pod#Understanding-Nodes-and-Devices

**Comment by JeroenvIS** [comment]
@taylor5042 ...adding to the thread: nodes are aged after 90 days by default; please see the manual here for the config directives to change that:
https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Configuration.pod#expire_nodes

**Comment by taylor5042** [comment]
I am running two different instances of netdisco, and neither of them remove node entries from the database.

**Comment by JeroenvIS** [comment]
@taylor5042: According to the 'netdisco-do expire' log that you posted, node expiry is set to 60 days ( '5184000' ::interval)...
I just tried on my own install, with the following two lines in environments/deployment.yml:
expire_nodes: 59
expire_nodes_archive: 58

... and I see SQL statements in the expire logging like these:
DELETE FROM node_ip
WHERE mac IN (
    SELECT me.mac
      FROM node_ip me
      LEFT JOIN node nodes
        ON nodes.mac = me.mac
    WHERE nodes.active AND me.mac IN (
        SELECT me.mac
          FROM node me
        WHERE time_last < ( now(  ) - '5097600' ::interval )
       )
    GROUP BY me.mac
    HAVING count( nodes.mac ) = 0
   )

and

DELETE FROM node_ip
WHERE mac IN (
    SELECT me.mac
      FROM node_ip me
      LEFT JOIN node nodes
        ON nodes.mac = me.mac
    WHERE nodes.active AND me.mac IN (
        SELECT me.mac
          FROM node me
        WHERE ( NOT active ) AND time_last < ( now(  ) - '5011200' ::interval )
       )
    GROUP BY me.mac
    HAVING count( nodes.mac ) = 0
   )

So the intervals here correspond with the 59 and 58 days that I set in deployment.yml

**Comment by taylor5042** [comment]
I also noticed that the corresponding days in the deployment file is correct. But as I have shown before, the cleanup doesn’t work. I’ve just ended up writing my own database cleanup methods.
