### ISSUE TITLE
Partial search not always working

### ISSUE THREAD

**Issue by pioevogel** [netdisco/netdisco#357]
When searching for some hosts, the partial search does not list them. Neither does a wildcardsearch. When searching for the exact hostname it does show up.

An example of a hostname that doesn't work is S-DESX1.

## Expected Behavior
When searching for "esx" with partial match checked I expect the host S-DESX1 to show up along with some others. The same when searching for \*esx\*

## Current Behavior
When searching (in the black title bar) for ESX with partial seach checked I get some hosts (switches actually), but not the host.
When searching for \*esx\* I get more hosts, but still not the host I am looking for. This just occurs with some hosts, not all.
When searching, the logs do not show anything related.

## Possible Solution
None found so far, except for typing the exact hostname.

## Steps to Reproduce (for bugs)
1. type partial hostname
2. check partial match

## Context
Our hostnames reflect their function. So a partial search for say "web" would list all webservers.

## Your Environment

* Netdisco version used: 2.36.11
* SNMP::Info version used: 3.37
* DB Schema: 44
* PostgreSQL: 9.1.14
* Perl: 5.18.2

**Comment by ollyg** [comment]
Hi @pioevogel, thanks for the report, but I am having trouble reproducing the issue. I will explain a little about how the search works in case it's a misunderstanding:

When you enter a search term into the black titlebar, and hit Enter or click the search button, Netdisco guesses what you want to search for. If it is wrong, you can click the Node tab to re-do the search for Nodes. Or, you can ask for a Node Search the first time around by clicking the little down-arrow and selecting Search Nodes from the list.

Partial Search is not enabled by default (and in the current version of Netdisco you cannot change the default, although I will be addressing this soon so you can). If you use wildcard characters in the search, Netdisco will enable partial search, or you can select the Partial checkbox.

In either case, I was able to search for hosts (Nodes) in Netdisco using wildcards and partial search. Note that this requires that DNS is working and Netdisco has been able to resolve host IP addresses to names during arpnip.

I'll close this ticket and re-open if you still have an issue and let me know.
