### ISSUE TITLE
Missing file in ExtUtils-MakeMaker-7.30 - Netdisco installation aborts

### ISSUE THREAD

**Issue by carcarx** [netdisco/netdisco#358]
After issuing
 curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco

I see

Can't locate ExtUtils/Manifest.pm in @INC (@INC contains: FatPacked::6540168=HASH(0x63cb88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at - line 132.

and the installation script aborts

Looking into the directory

/usr/share/perl5/ExtUtils

[root@itprdipam05 paul]# cd /usr/share/perl5/ExtUtils
[root@itprdipam05 ExtUtils]# ls -al
total 52
drwxr-xr-x.  3 root root    93 Sep 14 11:47 .
drwxr-xr-x. 46 root root  4096 Sep 14 11:47 ..
-rw-r--r--   1 root root  7467 Mar  2  2017 Command.pm
drwxr-xr-x.  2 root root    70 Sep 14 11:47 Constant
-rw-r--r--   1 root root 14938 Mar  2  2017 Constant.pm
-rw-r--r--   1 root root  7633 Mar  2  2017 Miniperl.pm
-rw-r--r--   1 root root  9741 Mar  2  2017 typemap

Installation script aborts.
## Steps to Reproduce (for bugs)

The host OS is RedHel Enterprise Linux 7
[root@itprdipam05 ~]# su - netdisco
[netdisco@itprdipam05 ~]$ curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco

## Context

Can't install Netdisco

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

Latest version of Netdisco
SNMP::info version unknown since the installation hasn't completed

**Comment by ollyg** [comment]
Hi @carcarx did you follow the instruction to install the perl-core package and others?

`root:~# yum install perl-core perl-DBD-Pg net-snmp-perl net-snmp-devel openssl-devel make automake gcc`

I am not able to reproduce this error. Please could you try on another system and perhaps another operating system?

**Comment by carcarx** [comment]
Thanks, Oliver,
Our infrastructure group standardizes on RHEL 7 VMs, so trying a different operating system would be a difficult option.

I've passed your message along to our infrastructure group.

**Comment by LBegnaud** [comment]
you could use [docker](https://github.com/netdisco/netdisco-docker) ...

I'll push what I've done so far into that repo, but I'll need @ollyg to build a docker cloud organization so we can setup automated builds (hint hint). Until then you can use the automated build from my fork.

I've been testing a few weeks and things seem to run smoothly.

easiest way to get it going is to bring up a user-defined network and a postgres container:
```
docker network create netdisco
docker run -d --name=postgres --network=netdisco postgres
```

then bring up the netdisco container connected to the same network, and expose port 5000
```
docker run -d --name=netdisco --network=netdisco lbegnaud/netdisco-docker
```

that `lbegnaud/netdisco-docker` image is not the official image, but it's a build that I've been testing with and once we get the build on the netdisco org, it shouldn't be a problem to leave the db intact and rebuild the netdisco container with the new image
