### ISSUE TITLE
Netdisco select wrong device

### ISSUE THREAD

**Issue by romale** [netdisco/netdisco#359]
## Expected Behavior

Right device selection

## Current Behavior

Wrong device selection

## Possible Solution

May be, "Management IP"s or device Name checking when clicking on device

## Steps to Reproduce (for bugs)

1. Example. "switch1" is current core L3 switch and has SVI IP = 10.1.1.1 (VLAN111) with management IP = 10.1.1.1, "switch2" is L2 switch and has management IP = 10.1.1.5
2. After network architecture change, "switch1" is L2 switch with management IP = 10.1.1.7 and VLAN111 is just Admin Shutdown (while IP config of VLAN111 is not removed), "switch2" is current core L3 and has SVI IP = 10.1.1.1 (VLAN111) with management IP = 10.1.1.1.
3. When I search in WEB interface by IP 10.1.1.1, ND2 show me two devices: "switch1" and "switch2". In "Management IP" column it has switch1=10.1.1.7, switch2=10.1.1.1. Ok.
4. I click on "switch2", but ND2 open "switch1"
5. I can't remove IP config of VLAN111 on "switch1", because moratirium for network changes.

## Context

Now, I can't select switch2 from example above. I need firstly delete switch1

## Your Environment

* Netdisco version used: App::Netdisco	2.36.11
* SNMP::Info version used: SNMP::Info	3.38

Centos 7

**Comment by ollyg** [comment]
Hi @romale 

I think I understand what you describe, but there is not a lot we can do... the primary key of a device in Netdisco is an IP address so sometimes it is not a unique key 😢 .

Having said that, we do make Netdisco search for the "management" IP first, and only then for an alias interface, when retrieving details. So you can help Netdisco by making it use the correct management IP. How to do that...? use the `device_identity` configuration:

https://github.com/netdisco/netdisco/wiki/Configuration#code-device_identity-code

This will "steer" netdisco to using the correct address on your devices all the time (for example by selecting one interface name). There are examples in the documentation.

In case this is still not working, you should check what the HTML hyperlink (A tag) under the device name is, when you search for "1.1.1.1" - this is the key that Netdisco is searching for.

I hope this helps,

regards,
Oliver.
