### ISSUE TITLE
Gather and store LLDP capabilities on switchport neighbor hardware

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#36]
Neighbor might not be a device but can report via LLDP some capabilities such as telephone.

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/38](https://sourceforge.net/p/netdisco/nd2-features/38)

**Comment by JeroenvIS** [comment]
With SNMP::Info commit f5c5ec20 (suggested to be included with 3.35 release), the SNMP::Info::LLDP class includes LLDP-EXT-MED-MIB.

Let's start collecting the following information with the Netdisco poller:

lldpXMedRemInventoryTable:
- lldpXMedRemHardwareRev
- lldpXMedRemFirmwareRev
- lldpXMedRemSoftwareRev
- lldpXMedRemSerialNum
- lldpXMedRemMfgName
- lldpXMedRemModelName
- lldpXMedRemAssetID

**Comment by JeroenvIS** [comment]
With SNMP::Info commit f5c5ec20 (suggested to be included with 3.35 release), the SNMP::Info::LLDP class includes LLDP-EXT-MED-MIB.

Let's start collecting the following information with the Netdisco poller:

lldpXMedRemInventoryTable:
- lldpXMedRemHardwareRev
- lldpXMedRemFirmwareRev
- lldpXMedRemSoftwareRev
- lldpXMedRemSerialNum
- lldpXMedRemMfgName
- lldpXMedRemModelName
- lldpXMedRemAssetID

**Comment by ollyg** [comment]
As regards CDP versus LLDP, IRC channel spake thus:

"_We decided to leave out CDP for the time being, as most vendors are actively supporting LLDP_"

and "_all in favor of supporting CDP,LLDP and other protocols and treating them equally for general topology, but for endpoint inventory (mainly focusing on phones etc) we can get away with doing LLDP extensions only_".

**Comment by ollyg** [comment]
Stalling this until someone can send me an snmpwalk from .1 of a device supporting lldpXMedRemInventoryTable.

````
snmpwalk -v 2c -c <community> -ObentU <device> .1
````

Mine only support lldpXMedRemCapabilitiesTable, lldpXMedRemXPoETable and lldpXMedRemXPoEPDTable :-(.

**Comment by JeroenvIS** [comment]
@ollyg Looks like I have an snmpwalk for you with several entries in lldpXMedRemInventoryTable. Will send it by e-mail.

**Comment by ollyg** [comment]
Going well. I have updated SNMP::Info to 3.47 with support for LLDP-MIB::lldpXMedRemInventoryTable.

You can call:
* lldp_media_cap (c.f. lldp_cap)
* lldp_rem_media_cap
* lldp_rem_media_cap_spt
* lldp_rem_hw_rev
* lldp_rem_fw_rev
* lldp_rem_sw_rev
* lldp_rem_serial
* lldp_rem_vendor
* lldp_rem_model
* lldp_rem_asset

Which of course all map back through lldp_if to the interface.

**Comment by ollyg** [comment]
So on Netdisco:

1. call lldp_media_cap
2. check that inventory is listed for the port
3. gather lldp_rem_xxxxx
4. store in device_port_properties table (in what form?? individual fields or stringified JSON hash?)

**Comment by ollyg** [comment]
Now implemented as of 6bd34ce0 and will be in the next release.
