### ISSUE TITLE
ip range exception for discovery (regex)

### ISSUE THREAD

**Issue by dabeani** [netdisco/netdisco#360]
Hi,

i want to limit ND to DO NOT discover following IP-Adresses...

10.*.*.130 - 10.*.*.140

with following Configuration declaration.

discover_no:
 - !!perl/regexp ^10\.(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){2}(1(3[0-9]|40))$

that will now work :( - is there some bug? 
is it possible to limit IP-Addresses with regex like i need?

br
Bernhard

**Comment by ollyg** [comment]
Hi Bernhard

Wow, that's a good question :-)

A YAML regexp can only be used to match the DNS name of the device. I think you probably want to match the "ip" field instead, so:

```
discover_no:
  - 'ip:10.(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){2}(1(3[0-9]|40))'
```
More documentation on ACL options is here:
https://github.com/netdisco/netdisco/wiki/Configuration#access-control-lists

Good luck!
Oliver.
