### ISSUE TITLE
buttons in the neighbourmap have an incorrect height

### ISSUE THREAD

**Issue by pioevogel** [netdisco/netdisco#367]
Hi,

the buttons in the neighbourmap have an incorrect height at startup (see https://imgur.com/a/uEZx3). Once a node on the map is doubleclicked they are normal.

I see this behaviour on Mozilla Firefox 58.0 on Kubuntu linux.

**Comment by ollyg** [comment]
Ah, yeah I have seen this. It's odd! Thanks for the confirmation it's not just me :-).
