### ISSUE TITLE
AP and IP Phone ports excluded from "ports with multiple nodes" report

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#37]
Under "device search -&gt; devices with multiple nodes attached" give an option to not show radios and IP phones. Many times phones have PCs behind them and APs always have multiple PCs.

Reported by: antacus

Original Ticket: [netdisco/nd2-features/39](https://sourceforge.net/p/netdisco/nd2-features/39)

**Comment by ollyg** [comment]
I think this is already the case. The SQL selects for ports where the remote_ip field is NULL. There should not be any AP or Phone ports selected *if* the remote device is sending LLDP.

However if there's a Phone not sending LLDP and having a PC behind it, then we might still show them. I'm not sure how we could address that without some uncertain match on MAC (?).
