### ISSUE TITLE
Backend broken

### ISSUE THREAD

**Issue by pioevogel** [netdisco/netdisco#375]
## Expected Behavior

Expecting normal discovery, arpwalk and macwalk.

## Current Behavior
Doing nothing of that, but filling backendlog with:

DBIx::Class::Storage::DBI::_resolve_bindattrs(): You must supply a datatype/bindtype (see DBIx::Class::ResultSet/DBIC BIND VALUES) for non-scalar value  [ "location", "contact", "portcontrol", "portname", "vlan", "power" ] at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 97

## Possible Solution
No clue, but @ollyg suggested in #netdisco he knew what was up here.

## Steps to Reproduce (for bugs)
Just restart daemon

## Context
Normal operation. Doesn't work right now.

## Your Environment
Software 	Version
App::Netdisco 	2.39.4
SNMP::Info 	3.45
DB Schema 	46
PostgreSQL 	9.1.14
Perl 	5.18.2
DBIx::Class version 999 required--this is only version 0.082810.
SQL::Abstract version 999 required--this is only version 1.81.

## Additional info
I ran DBIC_TRACE=1 ND2_SINGLE_WORKER=1 /home/netdisco/bin/localenv netdisco-backend-fg and will attach the output.

**Comment by pioevogel** [comment]
[debuglog.txt](https://github.com/netdisco/netdisco/files/1727198/debuglog.txt)

**Comment by postilion** [comment]
I have the same problem.
App-Netdisco-2.039004
SNMP::Info 3.44
DB Schema 46
PostgreSQL 10.2
Perl 5.22.1

I'm not sure how to collect the version numbers from DBIx:Class or SQL::Abstract.  They were brought in during installation of netdisco2 from CPAN, just a couple of days ago.

The DB was migrated from an existing Netdisco2 2.36.11 with schema 44, which was upgraded via netdisco-deploy.

Attached is output of DBIC_TRACE run, as @pioevogel included, above.
[netdisco-log.txt](https://github.com/netdisco/netdisco/files/1728502/netdisco-log.txt)

**Comment by ollyg** [comment]
Hi @pioevogel and @postilion 
You can fix this immediately by running:
`~netdisco/perl5/bin/localenv cpanm DBIx::Class`

Or release 2.039005 of Netdisco is on its way to CPAN which specifies the updated dependency. We need a newer DBIx::Class than is apparently on your system, to get things working.
Thanks for the clear and helpful bug reports and logs!

Oliver.

**Comment by avoidingthesubject** [comment]
Came across this issue too - Jobs were stuck - thanks for the fix @ollyg !  Boogie time
