### ISSUE TITLE
Improve Netbios collection procedures

### ISSUE THREAD

**Issue by JeroenvIS** [netdisco/netdisco#376]
## Expected Behavior
Netdisco nbtwalk / nbtstat jobs are expected to yield a significant number of Netbios name <-> node mappings.

## Current Behavior
Very few recent Netbios entries exist in our database, only one that was updated in the last week (while we have 36k unique IPv4 addresses in node_ip table that have been updated in the last week, and I know that a lot of them run Windows and/or support Netbios).

## Possible Solution
Not much debugging done yet, so unclear as to possible solutions.
Running the Linux CLI tool "nbtscan" on our Netdisco server gives ~ 1860 lines of output when scanning our /16 of public space, well within a minute. So at least that tool does collect a significant number of Netbios node names.
The Nbtstat code in Netdisco is not easy to understand, it uses a socket to send requests to UDP/137 and unpacks/interprets the raw responses. Maybe that code is not up-to-date, or maybe the protocol decoding itself is roughly OK but the scheduling of the requests and/or error handling of async responses results in very few replies being decoded and stored in the database. More debugging is required, and comparing packet dumps for "nbtscan" runs with Netdisco Nbtstat jobs could give more insight.

## Context

Personally I don't use Netbios inventory a lot, but an IRC user asked about it, and then I saw the low number of collected results in our environment.

## Your Environment

* Netdisco version used: 2.039001
* SNMP::Info version used: 3.43

**Comment by JeroenvIS** [comment]
Also, possibly worth looking at: the Net::NBName module on CPAN.

**Comment by ollyg** [comment]
NBTStat may have been crashing due to a nasty little bug in check_mac(). Ive just pushed a new version of Netdisco with a fix.

**Comment by jeneric** [comment]
@JeroenvIS am interested if you've seen any improvement with the bugfix @ollyg mentioned.

**Comment by kingtrw** [comment]
@JeroenvIS I had a similar problem, resulting from the fact that I was not able to monitor my router with Netdisco as it was operated by an external party.

[I've written a wiki page on how I worked around this](https://github.com/netdisco/netdisco/wiki/Node-names---NetBIOS) -- NetBIOS report is now fully populated as expected.

Hope this helps!
