### ISSUE TITLE
Manage host_groups and displaynames from webui 

### ISSUE THREAD

**Issue by rokkhan** [netdisco/netdisco#377]
Hi,

This is wish more than an issue. Could it be possible to manage host_groups ande host_groups and displaynames from netdisco-web?

Greetings.

**Comment by ollyg** [comment]
It would be nice, but there are a couple of reasons why I never tried to:

- the backend might be running on a different host with a different config and this would not be modified by the web
- modifications in the web would not be pushed back to the yml config file, so it may be confusing that the two become out of sync

Perhaps I worry too much! Also getting a nice clean user interface would be hard work. However, patches are welcome if someone wants to try this!

**Comment by ollyg** [comment]
Closed and moved to https://github.com/netdisco/netdisco/wiki/Wishlist
