### ISSUE TITLE
Auto creating Hub device when switch port mac address table has multiple MACs

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#38]
The idea is, when ND2 discovery process see on switch port (not uplink/trunk port) interface multiple MACs, then ND2 creates Hub/Repeater model/object (you know, it has no any MAC or IP data) with name for example Hub1, then this hub auto connects to switch port and to any IP and SNMP devices that listen on switch port. Hub device just has name and links to hosts/servers connected to it. So, we will have like screenshot in attachment.

Before host connecting to Hub or to switch/router, I think there needed to develop a new functionality in ND2:
1. Host/Server with no SNMP agent installed(or unknown SNMP community). It should be pingable host/model/object.
    Pros1: we will see any active IP hosts (if ICMP isn't blocked by local firewall) and host with incorrect SNMP community (while datacenter discovering, not users PC). Here may be discovery config option like: create_icmp_hosts (it's hosts, that reply by ICMP but not SNMP).

Pros2: we will see complex infrastructure with detail information about connections on topology/netmap.

Reported by: rom-ale

Original Ticket: [netdisco/nd2-features/40](https://sourceforge.net/p/netdisco/nd2-features/40)

**Comment by ollyg** [comment]
Unfortunately whichever way I think about this I can't come up with a solution I'm comfortable with. The sticking point is that this will cause Netdisco to at best hide information from the user, or at worst to lie to the user about the real situation. As far as the network reports, the nodes are on that port. Moving them to another device's port (even a pseudo device) is going to give a different version of the real network.

Furthermore, there seems no way to do this automatically which wouldn't in the end get a false positive and undo the benefit of the feature (erroneous reporting is worst of all).

Sorry, closing.
