### ISSUE TITLE
LLDP uses different remote port names than netdisco's local port

### ISSUE THREAD

**Issue by Linwood-F** [netdisco/netdisco#380]
It was suggested I report this issue under SNMP but I really believe it lies in NetDisco proper.

The core issue is that using LLDP I am unable to match some devices (maybe all devices). 

I noticed this between a Cisco and DLink, but it is most easily illustrated between two Ciscos since I can compare to CDP there.  I think it does not usually show up as CDP is most often used there not LLDP.   

Scenario: 
Cisco 3650 at 192.168.1.1 connected on port 1/0/8 to a Cisco 3650 at 192.168.6.1 on port  1/0/4

First what CDP shows: 

```
cisco1#show cdp neigh det
-------------------------
Device ID: cisco2.domain.stuff
Entry address(es):
  IP address: 172.31.31.6
Platform: cisco WS-C3650-24TD,  Capabilities: Router Switch IGMP
Interface: GigabitEthernet1/0/8,  Port ID (outgoing port): GigabitEthernet1/0/4
```

Notice the ports have the full name GigabitEthernet.  This data also propagates to the SNMP query for CDP info.  Now look at LLDP for the same neighbor:

```
cisco1#show lldp neigh det
Local Intf: Gi1/0/8
Chassis id: 4001.7ac5.fc00
Port id: Gi1/0/4
Port Description: Legacy Link to xxxxx (to be removed)
System Name: cisco2.domain.stuff
```

What happens is that when LLDP is used to determine connectivity, the remote port is this truncated name, but the local port (determined I presume from the IfDesc discovery) is the full name, and they do not match, and no link is drawn.

This appears to be because CDP uses ifDescr for report ports, but LLDP uses ifName for the port names.  See here: 

```
$ snmpwalk -v2c -c 1k2hf5c7 192.168.1.1 | grep "1/0/8"
IF-MIB::ifDescr.15 = STRING: GigabitEthernet1/0/8
IF-MIB::ifName.15 = STRING: Gi1/0/8
$ snmpwalk -v2c -c 1k2hf5c7 192.168.1.1 IF-MIB::ifAlias.25
IF-MIB::ifAlias.25 = STRING: Connection to head in switch
```

This is further complicated (for humans anyway) because some terminology in Netdisco uses a port "name" but is drawn from ifAlias.

## Expected Behavior
Ultimately the data is what the data is.  I think it would be wrong to munge the SNMP LLDP data to try to force it into the ifDescr format.

But somehow the links need to show.

## Current Behavior
Because it is matching the port name from two different SNMP fields (because the remote port for CDP and LLDP are coming from different fields), there is no link found.

## Possible Solution
My suggestion is that the port match needs to also compare against the port's ifName field, and use either one that matches (or maybe the first).  A problem here is that the only place I see the name field appears to be in device_module which appears to lack a tight tie to actual interfaces or port names.  Is ifName readily available somewhere? 

## Steps to Reproduce (for bugs)
I have not tried it between two Cisco's, but I think (emphasis on THINK) that they would not work with LLDP.  I know that DLink and Cisco do not work with LLDP, though there are also other issues there (port name spaces reported elsewhere.

## Context
I want map links to show. 

## Your Environment
SNMP::Info version used: 3.49
Netdisco version (if used): 2.39.15
On Ubuntu Linux 16.04.6.
The Cisco was a 3650 running IOS-XE version 3.07.05E FC1.
The DLink was a DGS-3120-48PC running B1.0.1.1 (likely quite old)

**Comment by Linwood-F** [comment]
Please wait on this... there's a bit more to the story and I need to research further.

**Comment by Linwood-F** [comment]
I have mine working with some kludges, and it takes three separate things. 

1) Change two SQL queries to exclude ethernetCsmacd as a requirement.  It is necessary to change both the neighbor and the speed one mentioned elsewhere. (I think already addressed 1, the other is open and I suspect about to be).

2) Change the neighbor sql query to ignore blanks (I have not put in your change to the regex, but I think that's equivalent).  (I think already addressed by you).

3) In my case for cisco to dlink, it was necessary to allow "Gi" and "GigabitEthernet" to match (I did it by just removing both).  The Dlinks to Dlinks and to Netgear appear to work properly to each other, but Cisco to Dlink did not work because of this.  I think related to some of the output above.

With those three changes right now I have all three vendors' devices (at least that support LLDP) showing neighbors on the maps.

I tried looking at (3) and got rather lost in the LLDP code, as there's a lot of vendor specific stuff in there, and I am very slow to read Perl, unfortunately, plus am not really familiar with the MIB(s) used.  While not pretty fixing it in the SQL Neighbor query actually worked fine for me, and it MAY be that the Cisco issue is more a Cisco issue than something wrong in your LLDP returns, as it looks to me like Cisco is inconsistent between the more commonly used CDP and LLDP which is going to get used between 3rd party vendors and it.  Putting in a series of REPLACE statements on the "ON" clause is a bit ugly, but it may be better than trying to kludge the cached data.  A more thorough approach might be to stash the ifName and ifDescription both, and allow matches against either, but that's a much more involved change (unless both are available now, which i did not see).

**Comment by ollyg** [comment]
Hi @Linwood-F many thanks for the update.

It looks to me like (1) and (2) are now addressed in the current release of Netdisco. Are you able to update and test?

For (3) I can point out that this is an issue for more than just the network map. In the Device Ports table, the Connected Devices column _will not contain a working link_ to the remote device port if the port name does not match. **We need to get a fix that is independent of the network map.**

The inconsistency in CDP and LLDP advertisements is not surprising (a lot of work goes on inside SNMP::Info to normalise port names, and see also this link for the horrifying mess of vendor implementations we need to deal with: http://www.irobert.info/display/IRINFO/Understanding+ifDescr,+ifName+and+ifAlias).

I would appreciate the input of @JeroenvIS on the value of storing additional interface table fields in Netdisco (if*) for this matching, or to do something else. It is an interesting case that CDP and LLDP advertise different data!

**Comment by Linwood-F** [comment]
@ollyg yes, I can test... probably this evening, tied up now.

**Comment by Linwood-F** [comment]
A long way from extensively tested, but I upgraded and poked around in it and found it was OK, but lots of links missing.  I added this: 

/home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/Virtual# diff DeviceLinks.pm DeviceLinks.pm.original2
30c30
<  INNER JOIN device_port dp2 ON (di.ip = dp2.ip AND replace(dp.remote_port,'GigabitEthernet','Gi') = replace(dp2.port,'GigabitEthernet','Gi'))
---
>  INNER JOIN device_port dp2 ON (di.ip = dp2.ip AND dp.remote_port = dp2.port)

And most (maybe all) came back.  It's that interface name discrepancy, I just forced all to be GigabitEthernet to be Gi.

I recognize as you mentioned elsewhere that this breaks the port links in the port display (i.e. I click on Dlink's Gi1/0/18 and it can't take me to the Cisco that shows GigabitEthernet1/0/18), but that's a small price to pay for the links to appear.

I also get lots of new information on the ports display (looks right, haven't explored), different color nodes on the map (instead of all blue, some green, some orange), is there anything that describes what the colors mean?

But to the original point -- I do think the issue title here is on point, I have to override the names in the neighbor query to make it work still, but the speed and ethernet type issues appear resolved.  At least in my scenarios.  Thank you.

And to others that need more links even if it breaks some things, at the moment, at least for me, the above line is all it takes (well, I then do a restart of the web server, back end, and discover all - -not sure any of those are necessary, but they work).

**Comment by dgeo** [comment]
Same here, with a mix of comware7 devices and cisco:
I think the problem can be explained whis this sql request: (10.2.0.22 is the cisco device, whose link seems lost in the graph but appears OK in the ports list of both devices)

These lins where ok some monthes ago, now using 2.39.20
```
netdisco=> select ip,remote_ip,port,remote_port from device_port where remote_port is not null and ip='10.2.0.22' or remote_ip='10.2.0.22';
    ip     | remote_ip |           port            |        remote_port        
-----------+-----------+---------------------------+---------------------------
 10.2.0.22 | 10.2.0.1  | GigabitEthernet0/45       | Ten-GigabitEthernet1/0/20
 10.2.0.1  | 10.2.0.22 | Ten-GigabitEthernet1/0/20 | Gi0/45
```

**Comment by Linwood-F** [comment]
@dgeo hoping for a more permanent solution, but if you are willing to tolerate the side effects, the one liner above will put the link up (essentially by changing GigabitEthernet to Gi.  It does break the ability to click on a port's remote connection and end up at the same port, but I prefer that downside to losing links on the map.

**Comment by ollyg** [comment]
Hello @dgeo and @Linwood-F please would you test the current release of Netdisco and let me know if things are improved?

**Comment by ollyg** [comment]
Thanks @dgeo that's great news :-)

**Comment by ollyg** [comment]
Oh, well spotted - this is me getting confused about column and SNMP leaf names, which happens. Thank you for the bug report - will be fixed in the next release.
