### ISSUE TITLE
LLDP port name is space compressed (DLink?  others?)

### ISSUE THREAD

**Issue by Linwood-F** [netdisco/netdisco#381]
This was originally opened under SNMP by request (249 there), but they closed it there as being a Netdisco issue, so entering it here with additional data they requested.

I have a Cisco 3650 at 192.168.1.1, and a DLink DGS-3120-48PC at 10.162.0.10, connected from Gi1/0/18 to port 41.

When queried on the DLink for the port 41 I see: 

```
$ snmpwalk -v2c -c 1k2hf5c7 10.162.0.10  IF-MIB::ifDescr.41
IF-MIB::ifDescr.41 = STRING: D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1
```

When the Cisco is queried for the LLDP neighbor I see the following (note I looked ahead of time to see it was index 6): 

```
$ snmpwalk -v2c -c 1k2hf5c7 192.168.1.1 1.0.8802.1.1.2.1.4.1.1 | grep -P "\.6\s"
iso.0.8802.1.1.2.1.4.1.1.4.0.18.6 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.5.0.18.6 = Hex-STRING: 84 C9 B2 19 51 68
iso.0.8802.1.1.2.1.4.1.1.6.0.18.6 = INTEGER: 7
iso.0.8802.1.1.2.1.4.1.1.7.0.18.6 = Hex-STRING: 31 2F 34 31 00
iso.0.8802.1.1.2.1.4.1.1.8.0.18.6 = STRING: "D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1"
iso.0.8802.1.1.2.1.4.1.1.9.0.18.6 = STRING: "ETSBH-SW"
iso.0.8802.1.1.2.1.4.1.1.10.0.18.6 = STRING: "Gigabit Ethernet Switch"
iso.0.8802.1.1.2.1.4.1.1.11.0.18.6 = Hex-STRING: 60 00
iso.0.8802.1.1.2.1.4.1.1.12.0.18.6 = Hex-STRING: 60 00
```
Both of the above look correct to me.   How however when I look in Netdisco 

```
select ip, port, remote_ip, remote_port from device_port dp where dp.ip = '192.168.1.1' and remote_port like 'D-Link%'
"192.168.1.1"	"GigabitEthernet1/0/18"	"10.162.0.10"	"D-LinkDGS-3120-48PCR1.02.013Port41onUnit1"

```

Note the lack of spaces in the remote port name.

Something (I presume the SNMP module?) is space-compressing these, but not the other port name, causing a mis-match when comparing a port to remote port.

Note in the issue under SNMP this was requested and seemed to indicate it was in Netdisco not SNMP (they also saw the same results in Netdisco BTW).

```
netdisco@xxxxx:~$ netdisco-do show -d 192.168.1.1 -e lldp_port
[3092] 2018-03-19 15:41:52 info App::Netdisco version 2.039015 loaded.
[3092] 2018-03-19 15:41:52 info show: [192.168.1.1]/lldp_port started at Mon Mar 19 10:41:52 2018
\ {
0.4.2 "Gi0/1",
0.8.1 "Gi1/0/4",
0.16.4 "Port 1",
0.18.7 "D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1"
}
[3092] 2018-03-19 15:41:52 info show: finished at Mon Mar 19 10:41:52 2018
[3092] 2018-03-19 15:41:52 info show: status done: Showed lldp_port response from 192.168.1.1
```

## Expected Behavior
Same port name -- I think with spaces as that's what is coming from the device,

## Current Behavior
One side (the remote port) is space compressed, the other (port) is not.

## Possible Solution
I think it's best to have the actual port names be used in the associated fields, and if some kind of more flexible comparison is needed to match, that it be done (only) in the comparison, not by munging the data.

## Steps to Reproduce (for bugs)

This would require a DLink (possibly with similar firmware, not clear if this is firmware specific as I have only a few), and a Cisco.  I've tried to provide the actual SNMP results above; I am happy to provide more queries against the devices or database, and/or test patched Netdisco for them.

## Context
Maps do not show links.

## Your Environment
* SNMP::Info version used: 3.49
* Netdisco version (if used):  2.39.15
On Ubuntu Linux 16.04.6.
The Cisco was a 3650 running IOS-XE version 3.07.05E FC1.
The DLink was a DGS-3120-48PC running B1.0.1.1 (likely quite old)

**Comment by JeroenvIS** [comment]
@Linwood-F thanks for re-reporting here.

@ollyg Possible culprit at https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm#L249 ? A space would be a valid character here... and in general, I think we should be careful with this kind of data "cleaning" in the application layer.

**Comment by Linwood-F** [comment]
@JeroenvIS thanks.  I personally agree, cleaning data that's stored seems likely to cause issues later.  I think it may be better to allow for "fuzzy" matches rather than making the data itself fuzzy.  Thanks for finding this.

**Comment by JeroenvIS** [comment]
@Linwood-F You could try a local edit by the way: see if adding "\s" into that regex (and then rediscover the devices) fixes it for you.

**Comment by Linwood-F** [comment]
I will, though I think I offset that issue in the SQL that matches for neighbors. My issue now is that I have that SQL actually finding a match -- but the match doesn't appear on the map (in fact the matched node, the one that appears on the left, disappears from the map).  I'm trying now to figure out how to put debugging statements in the web code and find its output somewhere to try to figure out why the node disappears.

I think the missing matches actually involved two different things (why I've entered two bugs), one is how LLDP is getting a different port name, and one the above name compression.  But I've gotten past those and have a third issue somewhere (unless it's a side effect of these where I do not see it).

**Comment by ollyg** [comment]
🤢 yeah I'm not sure where that "weird characters" filter comes from. I've added a space character to the permitted list, for the next release, pending further discussion.
