### ISSUE TITLE
Issue on 	2.39.16 in Neighbors.pm

### ISSUE THREAD

**Issue by lune001** [netdisco/netdisco#382]
Error message running a Discover All: 
 Failed Job : error running job invalid<empty> range ":-" in regex; marked by <-- HERE in [...] at netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm line 250, etc ....

## Steps to Reproduce (for bugs)
1. uptate to 2.39.16
2 run a discover All

## Your Environment

* Netdisco version used: 2.39.16
* SNMP::Info version used: 2_c

**Comment by ollyg** [comment]
Sorry about that ... I will fix right now.

**Comment by ollyg** [comment]
2.039017 will be on CPAN shortly. Sorry again!
