### ISSUE TITLE
build/upgrade issues (EL6)

### ISSUE THREAD

**Issue by Stoatwblr** [netdisco/netdisco#389]
nothing terribly major here.

Netdisco broke after stripping out a mountain of orphan and leaf packages from dead repos out of my EL6 box (oh dear how sad...)

I ended up having to delete ~/perl5/* and reinstall from scratch so that cpanm could figure out the missing dependencies and build them.

At least Package::DeprecationManager is missing from the build list - this had to be manually added using cpanm to allow netdisco-deploy to run.

Also: Whilst doing all the above, I found that whilst "~/bin/localenv cpanm --notest App::Netdisco" upgrades netdisco ok, the locally downloaded/compiled dependencies pulled in during the original installation and placed under ~/perl5 are _not_ being checked and a lot of them were significantly out of date.

You can't just rerun the installation script over the top of an installed netdisco - this won't check for updates either. ~/perl5/* has to be deleted.

A better update procedure is probably required in order to ensure the dependencies are kept up to date and to recheck for missing dependencies, given what may be happening elsewhere on a system where system deb or rpm packages may be removed or simply end up wildly out of date.  (I'm pretty sure this will apply across all distros)

**Comment by ollyg** [comment]
Thanks, I've included the missing package.
