### ISSUE TITLE
EoL, EoS info for devices

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#39]
hi,

would be good if NetDISCO 2 could provide stats/info on EoL/EoS etc of the switches being managed/detected by it.   I would envision that the EoS/EoL/EoW etc information would need to be collected from eg cisco, HP, etc sites and then some form of XML file created that could
be imported.   the user of NetDISCO2 would then be able to check via inventory etc what switches are EoL.

thats hardware - the software could also be done - eg safeharbor releases or insecure versions noted.

alan

Reported by: alanbuxey

Original Ticket: [netdisco/nd2-features/41](https://sourceforge.net/p/netdisco/nd2-features/41)

**Comment by ollyg** [comment]
Arista cloudvision does this for their kit, I believe :-). Moving to wishlist page in wiki.

**Comment by ollyg** [comment]
You can add and automate this using the custom fields feature
