### ISSUE TITLE
1ba1ea2 breaks heuristic neighbour detection

### ISSUE THREAD

**Issue by rkerr** [netdisco/netdisco#392]
In the store_neighbours function in netdisco/lib/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm from line 180 there is a section of heuristics for determining a correct neighbour IP in the case that the initially detected IP is 0.0.0.0. 1ba1ea2 adds new code at line 234 that takes the result of this process and throws it away again...

eg 
> [6467] 2018-04-11 16:08:33  info  [y.y.y.y] neigh - bad address 0.0.0.0 on port 24, searching for xx:xx:xx:xx:xx:xx instead
> [6467] 2018-04-11 16:08:33  info  [y.y.y.y] neigh - found xx:xx:xx:xx:xx:xx with IP z.z.z.z
> [6467] 2018-04-11 16:08:33  info  [y.y.y.y] neigh - discrepancy in IP on 24: using 0.0.0.0 instead of z.z.z.z

This is obviously undesirable. I think the block at line 234 wants moving up before the block at line 180 but I can't quite follow what the code was trying to achieve...

**Comment by ollyg** [comment]
Thanks for the bug report and very sorry this broke! I have applied a fix a long the lines of your suggestion, for the next release.
