### ISSUE TITLE
Customizable landing page

### ISSUE THREAD

**Issue by bldewolf** [netdisco/netdisco#395]
The current landing page is good for the initial setup but not much else. Are there plans to improve the page or make it customizable?  Even a duplicate of the Find Anything bar would be helpful, I think.

**Comment by ollyg** [comment]
This is a really good idea... when it's not so sunny here I will implement :-)

**Comment by ollyg** [comment]
I've implemented the suggestion to have the Find Anything bar on the main landing page.
