### ISSUE TITLE
Store IP Phone data

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#4]
Dustin Heywood suggested that it might be possible to try SNMP against IP phones even when CDP and LLDP are not enabled, using IP prefix matching (in config). Gather things like phone number, name, vlan.

Reported by: ollyg

Original Ticket: [netdisco/nd2-features/4](https://sourceforge.net/p/netdisco/nd2-features/4)

**Comment by ollyg** [comment]
Need some vendor specific examples - most phones don't run SNMP anyway?

_Could perhaps get phone capability to known device via LLDP then fire off another job to gather the SNMP details from the phones._
