### ISSUE TITLE
way to run netdisco-deploy unattended

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#40]
At present netdisco-deploy does not provided an easy way to do an unattended install. The use of Term::Readline means you can't even pipe to stdin without patching the code, see:

http://www.perlmonks.org/?node_id=542848

It would be nice to either have a way to signal netdisco-deploy to read stdin or CLI options for the various questions asked by Term::Readline. I appreciate there is also netdisco-db-deploy for unattended schema upgrades and the MIB download is pretty simple but there doesn't appear to be a way to do the OUI update unattended. I think netdisco 1 used to have a CLI option for this?

Reported by: rkerr

Original Ticket: [netdisco/nd2-features/42](https://sourceforge.net/p/netdisco/nd2-features/42)

**Comment by ollyg** [comment]
Moving to wishlist page in wiki.

**Comment by ollyg** [comment]
Here is an example of this working with pipe to stdin:
https://github.com/irasnyd/netdisco/blob/master/docker/init#L105
