### ISSUE TITLE
netdisco not discovering non-directly connected neighbors

### ISSUE THREAD

**Issue by imoimo32** [netdisco/netdisco#401]
Netdisco doesn't seem to be discovering non-directly connected Cisco neighbors.  Specifically, devices that are connected via wireless ptp or mtp bridges, or dmvpn gre tunnels.

## Expected Behavior

DMVPN has 12+ eigrp neighbors across gre tunnels, 3 eigrp on directly connected interface.
## Current Behavior

Only the 3 directly connected eigrp neighors are automatically discovered in netdisco.
## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Context

Attached is the snmpwalk file from one of our DMVPN hubs
[snmpwalk.out.txt](https://github.com/netdisco/netdisco/files/1926216/snmpwalk.out.txt)

## Your Environment

* Netdisco version used:   2.39.21
* SNMP::Info version used: 3.54

**Comment by jeneric** [comment]
The method to collect the EIGRP peers already existed in the underlying SNMP library, and the walk you provided had 16 peers in the table. It has been added to the neighbor collection process, should be available in next release.
