### ISSUE TITLE
The device name is not correctly placed, but is shown far away from the dot

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#402]
## Expected Behavior
The device name should be near the dot.

## Current Behavior
Since 2.39.22 the device name is not longer visible in the right place. It can be see far away from the dot

## Your Environment
App::Netdisco	2.39.22
SNMP::Info	3.54
DB Schema	52
PostgreSQL	9.6.7
Perl	5.24.1

**Comment by ollyg** [comment]
Hi @def-bs sorry about that - I have implemented an alternate fix for the Management IPs bug which I think works better, and is in release 2.039023.
