### ISSUE TITLE
Update Statistics doesn't always work.

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#403]
## Expected Behavior
When I complete an update I expect the release to be moved to the current version, but sometimes it is shown the old version, even though the update has been completed.

## Current Behavior
Sometimes it is shown the old version instead of the new version.

Even trying the "Update Statistics". But in some previous versions using the option"Update Statistics" I was able to obtain the correct version.

## Your Environment
App::Netdisco	2.39.22
SNMP::Info	3.54
DB Schema	52
PostgreSQL	9.6.7
Perl	5.24.1

**Comment by ollyg** [comment]
This is known behaviour. The version in the stats table comes from the DB which is only updated once a day (by the 'expire' job). As you discovered, you can run stats job manually to fix the error.

I think the solution will be to enqueue the stats job from within netdisco-deploy so it gets run after each upgrade. I will apply this patch for the next release. Thanks for your report!

**Comment by ollyg** [comment]
This is already the case. If you run netdisco-deploy then the stats are updated and you will see the new Netdisco version in the web. This is the code:

https://github.com/netdisco/netdisco/blob/master/bin/netdisco-deploy#L143
