### ISSUE TITLE
Spanning Tree Map identifying port states

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#41]
It would be really nice to have a Spanning Tree Map identifying the different port states:

disabled 
The port is disabled. 
 
  
blocking 
The Spanning Tree algorithm has set this port's state to "block," meaning that it is enabled but not passing traffic 
  
listening 
The port is in a transitional state, waiting for the Spanning Tree algorithm to determine whether it should block or forward traffic 
 
  
forwarding 
The port has been selected by the Spanning Tree algorithm to forward traffic, and is forwarding traffic currently 

Currently, there is a report identifying blocking ports.

Reported by: kingpinjl

Original Ticket: [netdisco/nd2-features/43](https://sourceforge.net/p/netdisco/nd2-features/43)

**Comment by ollyg** [comment]
Moving to wishlist page in wiki
