### ISSUE TITLE
Enhancement suggestion: Comments on undiscovered neighbors

### ISSUE THREAD

**Issue by Linwood-F** [netdisco/netdisco#410]
I frequently review the undiscovered neighbor report to fix issues.  Some are cases of finding a new device and needing to get SNMP access to it, but some are devices from other entities where there will never be SNMP access.

Sometimes it takes a bit of research as IP's and names may not be obvious.  It would be nice to be able to put a comment like "Edge router for XXXXX at YYYYYY not accessible from us." to commemorate what we do know about these, so as not to research again a few months later if memory is poor (or someone else looks). 

Not a big deal but a nice to have (he said after about the 3rd time I tracked one down.  

## Expected Behavior

A blank text field in the gui that persists in the database for user entered text.

**Comment by rkerr** [comment]
I would love if this report also differentiated between devices that weren't discovered due to configuration and those not discovered due to them not being reachable/bad community. Ideally there would be an option to hide all neighbours that weren't discovered due to discover_no settings.

**Comment by Linwood-F** [comment]
@ollyg yes. For someone who never even turned on the port control features it was a bit obscure getting there, but once I found it that would be easy and work fine I think, if it could carry out to the undiscovered line.  With that said, carrying the name over (which is really the description from most things I think, so maybe we need name and description to be complete?).   That way if there's a saved purpose of the port in the device it becomes visible as well, and may obviate even needing to add something, e.g. if the port said "Connection to ISP provided router" then seeing it show up as undiscovered may self-explanatory.  But being able to enter a comment also would be great.

**Comment by ollyg** [comment]
A much improved undiscovered neigbors report will be in the 2.40 release. It shows the port description and last comment, and also removes all neighbors that are not discoverable through config.
