### ISSUE TITLE
manual retrigger of discovery does not work

### ISSUE THREAD

**Issue by bhuddah** [netdisco/netdisco#413]
when you manually retrigger discovery sometimes you get
"fresh discovery canceled: XXX already known"

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used:

**Comment by ollyg** [comment]
In Discover.pm the code is rejecting web submitted discover jobs if the device already exists. In line with other parts of Netdisco, jobs manually submitted at web or CLI must always be run, and with high priority.

**Comment by ollyg** [comment]
Thanks for the bug report! Fixed in fa6f70ac.
