### ISSUE TITLE
Neighbors map display is blank on 2.39.28

### ISSUE THREAD

**Issue by DaveS118** [netdisco/netdisco#415]
## Current Behavior

When selecting the Neighbors tab, no map is displayed.  

This is from the netdisco-web.log:

[8011] 2018-05-08 13:14:08 error request to GET /ajax/data/device/netmap crashed: DBIx::Class::Storage::DBI::_dbh_execute
(): DBI Exception: DBD::Pg::st execute failed: ERROR:  column me.device does not exist
LINE 1: SELECT me.id, me.device, me.host_groups, me.locations, me.vl...
                      ^ [for Statement "SELECT me.id, me.device, me.host_groups, me.locations, me.vlan, me.positions FROM
 netmap_positions me WHERE ( ( me.device = ? AND me.host_groups = ? AND me.locations = ? AND me.vlan = ? ) )" with ParamV
alues: 1='10.44.100.12', 2='{}', 3='{}', 4='0'] at /home/netdisco1/perl5/lib/perl5/App/Netdisco/Web/Plugin/Device/Neighbo
rs.pm line 207

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 2.39.28
* SNMP::Info version used: 3.60
* DB Schema: 52
* PostgreSQL: 8.4.20
* Perl: 5.10.1
* CentOS 6.9 Final
* Kernel 2.6.32-696.23.1

All packages are up to date and I did a complete rebuild of Netdisco with a new user per the troubleshooting steps and linked to the existing database.

**Comment by ollyg** [comment]
Hi @DaveS118 please can you try running the following command and then try again?

`~netdisco/bin/netdisco-db-deploy --redeploy-all`

Many thanks,

**Comment by DaveS118** [comment]
Hi Oliver,

I ran the redeploy, still no map displayed.

Here is the output
netdisco1@kalnetdisco01 ~]$ ~/bin/netdisco-db-deploy  --redeploy-all
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "dbix_class_schema_versions_pkey" for table "dbix_class_sc
hema_versions"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (2) is lower than the schema version (52). Attempting u
pgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (3) is lower than the schema version (52). Attempting u
pgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (4) is lower than the schema version (52). Attempting u
pgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (5) is lower than the schema version (52). Attempting u
pgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (6) is lower than the schema version (52). Attempting u
pgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (7) is lower than the schema version (52). Attempting u
pgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (8) is lower than the schema version (52). Attempting u
pgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (9) is lower than the schema version (52). Attempting u
pgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (10) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (11) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (12) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (13) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (14) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (15) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (16) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (17) is lower than the schema version (52). Attempting
upgrade.
Error: DBIx::Class::Schema::Versioned::apply_statement(): DBI Exception: DBD::Pg::db do failed: ERROR:  syntax error at o
r near "EXISTS"
LINE 1: ALTER TABLE admin DROP CONSTRAINT IF EXISTS admin_pkey
                                             ^ at /home/netdisco1/bin/netdisco-db-deploy line 131
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (18) is lower than the schema version (52). Attempting
upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "node_pkey" for table "node"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (19) is lower than the schema version (52). Attempting
upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "node_wireless_pkey" for table "node_wireless"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (20) is lower than the schema version (52). Attempting
upgrade.
Error: DBIx::Class::Schema::Versioned::apply_statement(): DBI Exception: DBD::Pg::db do failed: ERROR:  could not create
unique index "jobs_queued"
DETAIL:  Table contains duplicated values. at /home/netdisco1/bin/netdisco-db-deploy line 131
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (21) is lower than the schema version (52). Attempting
upgrade.
NOTICE:  ALTER TABLE / ADD UNIQUE will create implicit index "topology_dev1_port1" for table "topology"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (22) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (23) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (24) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (25) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (26) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (27) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (28) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (29) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (30) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (31) is lower than the schema version (52). Attempting
upgrade.
NOTICE:  index "jobs_queued" does not exist, skipping
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (32) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (33) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (34) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (35) is lower than the schema version (52). Attempting
upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "device_port_vlan_pkey" for table "device_port_vlan"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (36) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (37) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (38) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (39) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (40) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (41) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (42) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (43) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (44) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (45) is lower than the schema version (52). Attempting
upgrade.
NOTICE:  CREATE TABLE will create implicit sequence "netmap_positions_id_seq1" for serial column "netmap_positions.id"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (46) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (47) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (48) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (49) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (50) is lower than the schema version (52). Attempting
upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (51) is lower than the schema version (52). Attempting
upgrade.

Thanks,
Dave.

**Comment by ollyg** [comment]
Hi @DaveS118 sorry to hear that didn't fix it, and you still have a problem. Can you run the following and share the output?

`~netdisco/bin/netdisco-do psql -e '\d netmap_positions'`

For some reason the schema isn't updating. If you need a quick fix, entering the following should work:

`~netdisco/bin/netdisco-do psql`

then paste the SQL:

````
ALTER TABLE netmap_positions DROP CONSTRAINT "netmap_positions_device_groups_vlan_key";
ALTER TABLE netmap_positions RENAME COLUMN device_groups TO host_groups;
ALTER TABLE netmap_positions ALTER COLUMN host_groups SET DEFAULT '{}';
ALTER TABLE netmap_positions ADD COLUMN "device" inet;
ALTER TABLE netmap_positions ADD COLUMN "locations" text[] DEFAULT '{}' NOT NULL;
````

The output of those commands might be interesting / useful, too!

Thanks,
oliver.

**Comment by ollyg** [comment]
Alternatively try an upgrade to 2.039029 which has just been released with (hopefully) a fix.

**Comment by DaveS118** [comment]
Hi Oliver,

Upgrading to 2.039030 did the trick, maps now display.

Thank you!

**Comment by ollyg** [comment]
Phew :-) Thanks for the confirmation.
