### ISSUE TITLE
"neigh - discrepancy in IP" due to differences in IPv6 formatting

### ISSUE THREAD

**Issue by fenner** [netdisco/netdisco#419]
I happened to be watching some discoveries against Arista devices going, and saw log messages like:

`[8097] 2018-05-29 20:20:21  info  [172.16.1.11] neigh - discrepancy in IP on Ethernet32: using fd7a:629f:52a4:dc63:ec4:7aff:fe9a:d81c instead of fd7a:629f:52a4:dc63:0ec4:7aff:fe9a:d81c`

To make the difference more clear:
`fd7a:629f:52a4:dc63:ec4:7aff:fe9a:d81c`
`fd7a:629f:52a4:dc63:0ec4:7aff:fe9a:d81c`

They're the same address, the second one is just non-canonical with a leading '0'.

## Your Environment
* Netdisco version used: 2.039030
* SNMP::Info version used: 3.61

**Comment by ollyg** [comment]
I left the code logic as is but improved the log message. Thanks for the report!
