### ISSUE TITLE
Option to show device sysname in web interface instead of DNS

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#42]
requesting a configurable setting to allow one to name devices as their system name (snmp sysName) instead fo the PTR of the IP it discovers it as. We typically have PTR's setup with interface names in them, so all discovered devices have this name as well. The sysname is sane/standard.

Reported by: falz

Original Ticket: [netdisco/nd2-features/44](https://sourceforge.net/p/netdisco/nd2-features/44)

**Comment by ollyg** [comment]
I think this is possible instead (and much better) by setting a loopback on the device and giving that a sensible name, and then using that in device_identity (assuming that the loopback is reachable).
