### ISSUE TITLE
Network map positions will not save

### ISSUE THREAD

**Issue by chris-elkin** [netdisco/netdisco#422]
Calls to /ajax/data/device/netmappositions  result in an Error 400

## Expected Behavior
Should update database with current device positions

## Current Behavior
<html>
<head>
<title>Error 400</title>
<link rel="stylesheet" href="/css/style.css" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
</head>
<body>
<h1>Error 400</h1>
<div id="content">
<h2>Unable to process your query</h2>The page you requested is not available
</div>
<div id="footer">
Powered by <a href="http://perldancer.org/">Dancer</a> 1.3202
</div>
</body>
</html>

![image](https://user-images.githubusercontent.com/40239297/41355406-14ec9f74-6ee7-11e8-9d8d-6f9c73074cba.png)

## Steps to Reproduce (for bugs)

1.  Go to a device neighbor view
2.  click the save button
3. 
4. 

## Context
Unable to create persistent layouts of  network devices in the neighbors view

## Your Environment

* Netdisco version used: 2.039030 Clean Install

**Comment by onlinehupe** [comment]
seems to be an issue that in view ~/perl5/lib/perl5/auto/share/dist/App-Netdisco/views/ajax/device/netmap.tt the `saveMapPositions()` function post an array due to that `input[name='q']` returns an array. That can not be hadnled by `search_for_device` function in Neighbors.pm  I fixed it by replacing `input[name='q']` with `#nq`

**Comment by hrv231** [comment]
Agree with this issue, it's happening the same thing for me, network maps will not save. I go to an specific device, move the neighbors around and click save, go back to the main page and click over the same device, when I go to view maps, the maps reorder dynamically again.

**Comment by ollyg** [comment]
Thanks! @onlinehupe and @hrv231 and @chris-elkin for the bug report

Code added in:
[master b4e5dc7a] #422 Network map positions will not save (onlinehupe)
