### ISSUE TITLE
Minor: Display issue with port overview

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#424]
If looking at the port overview for a switch, there is potential confusion in that if you enable the "Connected Nodes" display column, the node data appears in the "Connected Devices" column without any change of column name.

We spent a few minutes trying to work out why a colleague wasn't seeing the same view as me, despite seemingly having the same display columns!

I believe a simple fix for this could be if, when 'Connected Nodes' was enabled alongside 'Connected Devices', the column name becomes "Connected Devices & Nodes".

**Comment by ollyg** [comment]
Fixed in:
[master b3f6ffe0] #424 column name is "Connected Nodes & Devices" when both are shown

Many thanks for the report!
