### ISSUE TITLE
view: restrict users to specified subnet(s)

### ISSUE THREAD

**Issue by dabeani** [netdisco/netdisco#425]
hi,

is it possible to create for a specified user (ldap) an specified view to only see some of specified subnets?
e.g: i want to give for some countries to each user which depends to a country only the view of their subnets.

thank you.

br
Bernhard

**Comment by ollyg** [comment]
Hi @dabeani no this is not a current feature. It has been requested before and remains on our wishlist until we have the time or someone volunteers to add the feature!
https://github.com/netdisco/netdisco/wiki/Wishlist
