### ISSUE TITLE
Multiple Site

### ISSUE THREAD

**Issue by esersolmaz** [netdisco/netdisco#426]
Hi, 

If there are multiple regions, the network map is very complicated. Can multiple zone support be added?

Thank you also for your wonderful project.

Have a nice day.

**Comment by ollyg** [comment]
Hi @esersolmaz the best way to do this is to use the device groups feature and to create groups for each of your regional zones. This is described here: https://github.com/netdisco/netdisco/wiki/Network-Map#configuring-host-groups-and-display-names
