### ISSUE TITLE
No devices show on connected ports

### ISSUE THREAD

**Issue by hrv231** [netdisco/netdisco#429]
Mac addresses not shown on the ports

So, I'm having exactly the same issue as described in here:
https://sourceforge.net/p/netdisco/netdisco2/124/

I installed netdisco on a brand new VM - Debian 8 - kernel 3.16.0-6-amd64 , lldp and cdp devices are showing on the ports but no mac address for devices like printers or computers are shown.
This is an extremely important part of my use with Netdisco.

## Expected Behavior

Generally netdisco with arpnip gets the mac address for each port connected, making it easier to search for mac address on the search box and knowing where the device is connected.

## Current Behavior

Since the beginning of my installation netdisco is not showing that, everything else works like showing lldp and cdp devices, the versions, system and model, but is not showing the rest of devices connected like computers.
## Possible Solution

I'm ready to test whatever command Oliver send me, or if you guys needs something else for me. This is extremely important.
## Steps to Reproduce (for bugs)

1. Installed Debian 8 kernel 3.16.0-6-amd64 and netdisco.
2. Follow all the steps on the netdisco page
3. Start scanning one device on your network and the error will appear
4. 

## Context

Thank you very much for all the developers for their great work!!
![netdisco system](https://user-images.githubusercontent.com/41212308/43480827-375f0ca2-94b9-11e8-9a73-dbf2981170de.png)

## Your Environment

* Netdisco version used: 2.39.31
* SNMP::Info version used: 3.61

**Comment by ollyg** [comment]
Hi @hrv231 

Sorry for the delay responding. I realise this is an important issue to you!

Can you send the output of this command:

`~/bin/netdisco-do macsuck -d <IP-OF-SWITCH> -DI`

Thanks,
Oliver.

**Comment by hrv231** [comment]
Thank you Oliver!

[switch1.txt](https://github.com/netdisco/netdisco/files/2734261/switch1.txt)
[switch2.txt](https://github.com/netdisco/netdisco/files/2734263/switch2.txt)

**Comment by inphobia** [comment]
interesting issue, what does the following query return?

```SQL
SELECT * FROM public.node
WHERE switch = '164.116.2.14'
    AND active = true
ORDER BY time_last DESC, switch ASC, port ASC, vlan ASC LIMIT 150
```

can also be used as:
`netdisco-do psql -e "SELECT * FROM node WHERE switch = '164.116.2.14' AND active = true ORDER BY time_last DESC, switch ASC, port ASC, vlan ASC LIMIT 150"`

**Comment by hrv231** [comment]
![netdisco1](https://user-images.githubusercontent.com/41212308/52082975-11a43c00-2553-11e9-8adb-aab063b33fe2.png)

**Comment by inphobia** [comment]
it seems netdisco actually detects clients & assigns them to the right device, so perhaps the portnames don't match with the ones from the device. could you run:

netdisco-do psql -e "SELECT * FROM device_port WHERE ip = '164.116.2.14' ORDER BY ip ASC, port ASC LIMIT 100"

thx

**Comment by inphobia** [comment]
hm, if that's to wide to fit on your terminal i think this will do too:

`netdisco-do psql -e "SELECT ip,port,creation,descr,up,up_admin,type,speed,name,mac,remote_id,vlan,pvid,manual_topo,is_uplink,slave_of,is_master FROM device_port WHERE ip = '164.116.2.14' ORDER BY ip ASC, port ASC LIMIT 100"`

**Comment by hrv231** [comment]
`
      ip      |                 port                  |          creation          |                 descr                 |  up  | up_admin |       type       |  speed   |              name               |        mac        |     remote_id     | vlan | pvid | manual_topo | is_uplink | slave_of | is_master 
--------------+---------------------------------------+----------------------------+---------------------------------------+------+----------+------------------+----------+---------------------------------+-------------------+-------------------+------+------+-------------+-----------+----------+-----------
 164.116.2.14 | 1                                     | 2019-01-31 09:00:38.755504 | 1                                     | up   | up       | ethernetCsmacd   | 1.0 Gbps | uplink to Firewall              | 68:b5:99:0e:e8:ff |                   | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 10                                    | 2019-01-31 09:00:38.755504 | 10                                    | up   | up       | ethernetCsmacd   | 100 Mbps | NetRack APC UPS                 | 68:b5:99:0e:e8:f6 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 11                                    | 2019-01-31 09:00:38.755504 | 11                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to Tele-HP253048G-1    | 68:b5:99:0e:e8:f5 | 30:8d:99:0b:7f:40 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 12                                    | 2019-01-31 09:00:38.755504 | 12                                    | down | up       | ethernetCsmacd   | 10 Mbps  | Tim Office                      | 68:b5:99:0e:e8:f4 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 13                                    | 2019-01-31 09:00:38.755504 | 13                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | Sonus                           | 68:b5:99:0e:e8:f3 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 14                                    | 2019-01-31 09:00:38.755504 | 14                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | Lync Gateway2                   | 68:b5:99:0e:e8:f2 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 15                                    | 2019-01-31 09:00:38.755504 | 15                                    | up   | up       | ethernetCsmacd   | 100 Mbps | downlink to OPS-HP2524 Printers | 68:b5:99:0e:e8:f1 | 00:0a:57:e5:73:c0 | 31   |   31 | f           | t         |          | f
 164.116.2.14 | 16                                    | 2019-01-31 09:00:38.755504 | 16                                    | up   | up       | ethernetCsmacd   | 100 Mbps | WSIPC-OPS Firewall Trust        | 68:b5:99:0e:e8:f0 |                   | 31   |   31 | f           |           |          | f
 164.116.2.14 | 17                                    | 2019-01-31 09:00:38.755504 | 17                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | FW port 8 - WSIPC               | 68:b5:99:0e:e8:ef |                   | 31   |   31 | f           | t         |          | f
 164.116.2.14 | 18                                    | 2019-01-31 09:00:38.755504 | 18                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:ee |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 19                                    | 2019-01-31 09:00:38.755504 | 19                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to Tele-HP2910al24G    | 68:b5:99:0e:e8:ed | 00:23:47:bf:7c:00 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 2                                     | 2019-01-31 09:00:38.755504 | 2                                     | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to NOC-HP5406zl        | 68:b5:99:0e:e8:fe | 2c:59:e5:25:88:00 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 20                                    | 2019-01-31 09:00:38.755504 | 20                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:ec | �t                | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 21                                    | 2019-01-31 09:00:38.755504 | 21                                    | down | up       | ethernetCsmacd   | 10 Mbps  | AVAILABLE                       | 68:b5:99:0e:e8:eb |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 22                                    | 2019-01-31 09:00:38.755504 | 22                                    | down | up       | ethernetCsmacd   | 10 Mbps  | AVAILABLE                       | 68:b5:99:0e:e8:ea |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 23                                    | 2019-01-31 09:00:38.755504 | 23                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | Port 23                         | 68:b5:99:0e:e8:e9 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 24                                    | 2019-01-31 09:00:38.755504 | 24                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | Omnipeek mgmt                   | 68:b5:99:0e:e8:e8 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 25                                    | 2019-01-31 09:00:38.755504 | 25                                    | down | up       | ethernetCsmacd   | 10 Mbps  | AVAILABLE                       | 68:b5:99:0e:e8:e7 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 26                                    | 2019-01-31 09:00:38.755504 | 26                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to SANSwitchHP2920-48G | 68:b5:99:0e:e8:e6 | 6c:c2:17:02:17:c0 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 27                                    | 2019-01-31 09:00:38.755504 | 27                                    | up   | up       | ethernetCsmacd   | 100 Mbps | 2500 S2 connector               | 68:b5:99:0e:e8:e5 | ec:24:b8:a5:1c:29 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 28                                    | 2019-01-31 09:00:38.755504 | 28                                    | up   | up       | ethernetCsmacd   | 100 Mbps | downlink to NOC-Print HP2524    | 68:b5:99:0e:e8:e4 | 00:0a:57:e2:1a:c0 | 112  |  112 | f           | t         |          | f
 164.116.2.14 | 29                                    | 2019-01-31 09:00:38.755504 | 29                                    | up   | up       | ethernetCsmacd   | 100 Mbps | Port 29                         | 68:b5:99:0e:e8:e3 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 3                                     | 2019-01-31 09:00:38.755504 | 3                                     | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to ServerSwitch HP2900 | 68:b5:99:0e:e8:fd | 00:1f:fe:1f:fb:80 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 30                                    | 2019-01-31 09:00:38.755504 | 30                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | iBoss Management                | 68:b5:99:0e:e8:e2 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 31                                    | 2019-01-31 09:00:38.755504 | 31                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | S2 Controller                   | 68:b5:99:0e:e8:e1 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 32                                    | 2019-01-31 09:00:38.755504 | 32                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:e0 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 33                                    | 2019-01-31 09:00:38.755504 | 33                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to ServerHP2920        | 68:b5:99:0e:e8:df | 2c:59:e5:07:21:00 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 34                                    | 2019-01-31 09:00:38.755504 | 34                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:de | 94:b4:0f:cd:44:ce | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 35                                    | 2019-01-31 09:00:38.755504 | 35                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:dd | 94:b4:0f:cd:45:1a | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 36                                    | 2019-01-31 09:00:38.755504 | 36                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:dc | d8:c7:c8:ca:95:cb | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 37                                    | 2019-01-31 09:00:38.755504 | 37                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:db | d8:c7:c8:ca:9e:11 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 38                                    | 2019-01-31 09:00:38.755504 | 38                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:da | d8:c7:c8:ca:92:ed | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 39                                    | 2019-01-31 09:00:38.755504 | 39                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:d9 | d8:c7:c8:ca:9f:82 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 4                                     | 2019-01-31 09:00:38.755504 | 4                                     | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to Tele-HP5406zl       | 68:b5:99:0e:e8:fc | d4:c9:ef:93:c5:00 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 40                                    | 2019-01-31 09:00:38.755504 | 40                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:d8 | d8:c7:c8:ca:d3:49 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 41                                    | 2019-01-31 09:00:38.755504 | 41                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:d7 | d8:c7:c8:c2:a4:99 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 42                                    | 2019-01-31 09:00:38.755504 | 42                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:d6 | d8:c7:c8:ca:9f:57 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 43                                    | 2019-01-31 09:00:38.755504 | 43                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:d5 | d8:c7:c8:ca:9d:d9 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 44                                    | 2019-01-31 09:00:38.755504 | 44                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | USER DHCP                       | 68:b5:99:0e:e8:d4 | d8:c7:c8:ca:9f:4f | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 45                                    | 2019-01-31 09:00:38.755504 | 45                                    | down | up       | ethernetCsmacd   | 1.0 Gbps | Port 45                         | 68:b5:99:0e:e8:d3 |                   | 1    |    1 | f           |           |          | f
 164.116.2.14 | 46                                    | 2019-01-31 09:00:38.755504 | 46                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to 2200-HP2920         | 68:b5:99:0e:e8:d2 | 04:09:73:b3:34:40 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 47                                    | 2019-01-31 09:00:38.755504 | 47                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | uplink to fw port 5             | 68:b5:99:0e:e8:d1 |                   | 112  |  112 | f           | t         |          | f
 164.116.2.14 | 48                                    | 2019-01-31 09:00:38.755504 | 48                                    | up   | up       | ethernetCsmacd   | 1.0 Gbps | uplink to HP3500 port 15        | 68:b5:99:0e:e8:d0 | 00:23:47:be:11:80 | 2    |    2 | f           | t         |          | f
 164.116.2.14 | 5                                     | 2019-01-31 09:00:38.755504 | 5                                     | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to HP5308xl            | 68:b5:99:0e:e8:fb | 00:0a:57:c4:72:00 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 6                                     | 2019-01-31 09:00:38.755504 | 6                                     | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to NOC2540-48G         | 68:b5:99:0e:e8:fa | 00:fd:45:01:74:00 | 1    |    1 | f           | t         |          | f
 164.116.2.14 | 7                                     | 2019-01-31 09:00:38.755504 | 7                                     | up   | up       | ethernetCsmacd   | 1.0 Gbps | Port 7                          | 68:b5:99:0e:e8:f9 |                   | 1    |    1 | t           | t         |          | f
 164.116.2.14 | 8                                     | 2019-01-31 09:00:38.755504 | 8                                     | up   | up       | ethernetCsmacd   | 1.0 Gbps | downlink to Tele-HP253024G-2    | 68:b5:99:0e:e8:f8 | 14:02:ec:a8:a4:20 | 1    |   :`

**Comment by hrv231** [comment]
Hi @inphobia ,
Let me know if you would like a picture to make it easier to the eyes.

**Comment by inphobia** [comment]
nothing a regular expression and some markdown can't fix :)

 ip | port | creation | descr | up | up_admin | type | speed | name | mac | remote_id | vlan | pvid | manual_topo | is_uplink | slave_of | is_master
-------------- | --------------------------------------- | ---------------------------- | --------------------------------------- | ------ | ---------- | ------------------ | ---------- | --------------------------------- | ------------------- | ------------------- | ------ | ------ | ------------- | ----------- | ---------- | -----------
164.116.2.14 | 1 | 2019-01-31 09:00:38.755504 | 1 | up | up | ethernetCsmacd | 1.0 Gbps | uplink to Firewall | 68:b5:99:0e:e8:ff | | 1 | 1 | f | t | | f 
164.116.2.14 | 10 | 2019-01-31 09:00:38.755504 | 10 | up | up | ethernetCsmacd | 100 Mbps | NetRack APC UPS | 68:b5:99:0e:e8:f6 | | 1 | 1 | f | | | f 
164.116.2.14 | 11 | 2019-01-31 09:00:38.755504 | 11 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to Tele-HP253048G-1 | 68:b5:99:0e:e8:f5 | 30:8d:99:0b:7f:40 | 1 | 1 | f | t | | f 
164.116.2.14 | 12 | 2019-01-31 09:00:38.755504 | 12 | down | up | ethernetCsmacd | 10 Mbps | Tim Office | 68:b5:99:0e:e8:f4 | | 1 | 1 | f | | | f 
164.116.2.14 | 13 | 2019-01-31 09:00:38.755504 | 13 | up | up | ethernetCsmacd | 1.0 Gbps | Sonus | 68:b5:99:0e:e8:f3 | | 1 | 1 | f | | | f 
164.116.2.14 | 14 | 2019-01-31 09:00:38.755504 | 14 | up | up | ethernetCsmacd | 1.0 Gbps | Lync Gateway2 | 68:b5:99:0e:e8:f2 | | 1 | 1 | f | | | f 
164.116.2.14 | 15 | 2019-01-31 09:00:38.755504 | 15 | up | up | ethernetCsmacd | 100 Mbps | downlink to OPS-HP2524 Printers | 68:b5:99:0e:e8:f1 | 00:0a:57:e5:73:c0 | 31 | 31 | f | t | | f 
164.116.2.14 | 16 | 2019-01-31 09:00:38.755504 | 16 | up | up | ethernetCsmacd | 100 Mbps | WSIPC-OPS Firewall Trust | 68:b5:99:0e:e8:f0 | | 31 | 31 | f | | | f 
164.116.2.14 | 17 | 2019-01-31 09:00:38.755504 | 17 | up | up | ethernetCsmacd | 1.0 Gbps | FW port 8 - WSIPC | 68:b5:99:0e:e8:ef | | 31 | 31 | f | t | | f 
164.116.2.14 | 18 | 2019-01-31 09:00:38.755504 | 18 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:ee | | 1 | 1 | f | | | f 
164.116.2.14 | 19 | 2019-01-31 09:00:38.755504 | 19 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to Tele-HP2910al24G | 68:b5:99:0e:e8:ed | 00:23:47:bf:7c:00 | 1 | 1 | f | t | | f 
164.116.2.14 | 2 | 2019-01-31 09:00:38.755504 | 2 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to NOC-HP5406zl | 68:b5:99:0e:e8:fe | 2c:59:e5:25:88:00 | 1 | 1 | f | t | | f 
164.116.2.14 | 20 | 2019-01-31 09:00:38.755504 | 20 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:ec | �t | 1 | 1 | f | t | | f 
164.116.2.14 | 21 | 2019-01-31 09:00:38.755504 | 21 | down | up | ethernetCsmacd | 10 Mbps | AVAILABLE | 68:b5:99:0e:e8:eb | | 1 | 1 | f | | | f 
164.116.2.14 | 22 | 2019-01-31 09:00:38.755504 | 22 | down | up | ethernetCsmacd | 10 Mbps | AVAILABLE | 68:b5:99:0e:e8:ea | | 1 | 1 | f | | | f 
164.116.2.14 | 23 | 2019-01-31 09:00:38.755504 | 23 | up | up | ethernetCsmacd | 1.0 Gbps | Port 23 | 68:b5:99:0e:e8:e9 | | 1 | 1 | f | | | f 
164.116.2.14 | 24 | 2019-01-31 09:00:38.755504 | 24 | up | up | ethernetCsmacd | 1.0 Gbps | Omnipeek mgmt | 68:b5:99:0e:e8:e8 | | 1 | 1 | f | | | f 
164.116.2.14 | 25 | 2019-01-31 09:00:38.755504 | 25 | down | up | ethernetCsmacd | 10 Mbps | AVAILABLE | 68:b5:99:0e:e8:e7 | | 1 | 1 | f | | | f 
164.116.2.14 | 26 | 2019-01-31 09:00:38.755504 | 26 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to SANSwitchHP2920-48G | 68:b5:99:0e:e8:e6 | 6c:c2:17:02:17:c0 | 1 | 1 | f | t | | f 
164.116.2.14 | 27 | 2019-01-31 09:00:38.755504 | 27 | up | up | ethernetCsmacd | 100 Mbps | 2500 S2 connector | 68:b5:99:0e:e8:e5 | ec:24:b8:a5:1c:29 | 1 | 1 | f | t | | f 
164.116.2.14 | 28 | 2019-01-31 09:00:38.755504 | 28 | up | up | ethernetCsmacd | 100 Mbps | downlink to NOC-Print HP2524 | 68:b5:99:0e:e8:e4 | 00:0a:57:e2:1a:c0 | 112 | 112 | f | t | | f 
164.116.2.14 | 29 | 2019-01-31 09:00:38.755504 | 29 | up | up | ethernetCsmacd | 100 Mbps | Port 29 | 68:b5:99:0e:e8:e3 | | 1 | 1 | f | | | f 
164.116.2.14 | 3 | 2019-01-31 09:00:38.755504 | 3 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to ServerSwitch HP2900 | 68:b5:99:0e:e8:fd | 00:1f:fe:1f:fb:80 | 1 | 1 | f | t | | f 
164.116.2.14 | 30 | 2019-01-31 09:00:38.755504 | 30 | up | up | ethernetCsmacd | 1.0 Gbps | iBoss Management | 68:b5:99:0e:e8:e2 | | 1 | 1 | f | | | f 
164.116.2.14 | 31 | 2019-01-31 09:00:38.755504 | 31 | up | up | ethernetCsmacd | 1.0 Gbps | S2 Controller | 68:b5:99:0e:e8:e1 | | 1 | 1 | f | | | f 
164.116.2.14 | 32 | 2019-01-31 09:00:38.755504 | 32 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:e0 | | 1 | 1 | f | | | f 
164.116.2.14 | 33 | 2019-01-31 09:00:38.755504 | 33 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to ServerHP2920 | 68:b5:99:0e:e8:df | 2c:59:e5:07:21:00 | 1 | 1 | f | t | | f 
164.116.2.14 | 34 | 2019-01-31 09:00:38.755504 | 34 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:de | 94:b4:0f:cd:44:ce | 1 | 1 | f | t | | f 
164.116.2.14 | 35 | 2019-01-31 09:00:38.755504 | 35 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:dd | 94:b4:0f:cd:45:1a | 1 | 1 | f | t | | f 
164.116.2.14 | 36 | 2019-01-31 09:00:38.755504 | 36 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:dc | d8:c7:c8:ca:95:cb | 1 | 1 | f | t | | f 
164.116.2.14 | 37 | 2019-01-31 09:00:38.755504 | 37 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:db | d8:c7:c8:ca:9e:11 | 1 | 1 | f | t | | f 
164.116.2.14 | 38 | 2019-01-31 09:00:38.755504 | 38 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:da | d8:c7:c8:ca:92:ed | 1 | 1 | f | t | | f 
164.116.2.14 | 39 | 2019-01-31 09:00:38.755504 | 39 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:d9 | d8:c7:c8:ca:9f:82 | 1 | 1 | f | t | | f 
164.116.2.14 | 4 | 2019-01-31 09:00:38.755504 | 4 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to Tele-HP5406zl | 68:b5:99:0e:e8:fc | d4:c9:ef:93:c5:00 | 1 | 1 | f | t | | f 
164.116.2.14 | 40 | 2019-01-31 09:00:38.755504 | 40 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:d8 | d8:c7:c8:ca:d3:49 | 1 | 1 | f | t | | f 
164.116.2.14 | 41 | 2019-01-31 09:00:38.755504 | 41 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:d7 | d8:c7:c8:c2:a4:99 | 1 | 1 | f | t | | f 
164.116.2.14 | 42 | 2019-01-31 09:00:38.755504 | 42 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:d6 | d8:c7:c8:ca:9f:57 | 1 | 1 | f | t | | f 
164.116.2.14 | 43 | 2019-01-31 09:00:38.755504 | 43 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:d5 | d8:c7:c8:ca:9d:d9 | 1 | 1 | f | t | | f 
164.116.2.14 | 44 | 2019-01-31 09:00:38.755504 | 44 | up | up | ethernetCsmacd | 1.0 Gbps | USER DHCP | 68:b5:99:0e:e8:d4 | d8:c7:c8:ca:9f:4f | 1 | 1 | f | t | | f 
164.116.2.14 | 45 | 2019-01-31 09:00:38.755504 | 45 | down | up | ethernetCsmacd | 1.0 Gbps | Port 45 | 68:b5:99:0e:e8:d3 | | 1 | 1 | f | | | f 
164.116.2.14 | 46 | 2019-01-31 09:00:38.755504 | 46 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to 2200-HP2920 | 68:b5:99:0e:e8:d2 | 04:09:73:b3:34:40 | 1 | 1 | f | t | | f 
164.116.2.14 | 47 | 2019-01-31 09:00:38.755504 | 47 | up | up | ethernetCsmacd | 1.0 Gbps | uplink to fw port 5 | 68:b5:99:0e:e8:d1 | | 112 | 112 | f | t | | f 
164.116.2.14 | 48 | 2019-01-31 09:00:38.755504 | 48 | up | up | ethernetCsmacd | 1.0 Gbps | uplink to HP3500 port 15 | 68:b5:99:0e:e8:d0 | 00:23:47:be:11:80 | 2 | 2 | f | t | | f 
164.116.2.14 | 5 | 2019-01-31 09:00:38.755504 | 5 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to HP5308xl | 68:b5:99:0e:e8:fb | 00:0a:57:c4:72:00 | 1 | 1 | f | t | | f 
164.116.2.14 | 6 | 2019-01-31 09:00:38.755504 | 6 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to NOC2540-48G | 68:b5:99:0e:e8:fa | 00:fd:45:01:74:00 | 1 | 1 | f | t | | f 
164.116.2.14 | 7 | 2019-01-31 09:00:38.755504 | 7 | up | up | ethernetCsmacd | 1.0 Gbps | Port 7 | 68:b5:99:0e:e8:f9 | | 1 | 1 | t | t | | f 
164.116.2.14 | 8 | 2019-01-31 09:00:38.755504 | 8 | up | up | ethernetCsmacd | 1.0 Gbps | downlink to Tele-HP253024G-2 | 68:b5:99:0e:e8:f8 | 14:02:ec:a8:a4:20 | 1 | :

**Comment by hrv231** [comment]
Awesome.
Any clue about this issue?

**Comment by inphobia** [comment]
regretfully, no...

your nodes are discovered & indexed. and according to the last post they should also point to the correct device & port. i had a look at the hp module, the only thing i can even remotely think of is that it might use other methods to identify ports.

thats why i would like you to try 2 things.
port 30 seems to have only 1 device attached to it.

could you do the following:
currently the name of that port is "iBoss Management". could you remote that (just a blank entry), then rerun discovery on the device (wait until discovery is complete) then arpnip & macsuck & check if port 30 now shows an attached device.

if not, make the name of port 30 just "30" instead of "iBoss Management", then go throught the discovery etc step again & check if a device shows up then.

just for a bit more information, make sure you select the highlighted items from the sidebar, you can leave the other options blank (was to lazy to click em all 😄 , highlighted options need to be selected, rest can be blank).
![image](https://user-images.githubusercontent.com/39005454/52085571-142f8180-25a5-11e9-8f43-ad2066896ab6.png)

**Comment by inphobia** [comment]
ok, you lost me...

i thought the issue was you saw no mac addresses for the connected devices, but looking at the screenshot it seems to show a connected device on port 30 with mac address "0c:c4:7a:0e:11:05".

what am i missing?

**Comment by hrv231** [comment]
Sorry for the confusion.
Right now it shows.. I don't know if specifically port 30 was showing before, but the issue is that some computers when they are connected they were not shown on the GUI.
When I placed this ticket I was on another version, maybe something changed.
Even before I wasn't able to see a mac address of a device like a PC connected to the back of the phone, and then the phone connected to the wall.
Before it wasn't showing, right now I ran a discovery and it shows.

![netdisco3](https://user-images.githubusercontent.com/41212308/52087376-13273180-255e-11e9-9642-8dd73e771a66.png)

**Comment by inphobia** [comment]
yeah, we had issues with that for various reasons. oliver did an overhaul around 2.040000 which made most of them go away.
it might have been related to the fact we did each discovery step individually instead of looking at it as a whole. for example: if you had an some ignore_interfaces defined the main discover step would respect that but substeps of the discover process would not.

so, is everything working as expected again now?

**Comment by hrv231** [comment]
It seems that it is. 👍 
Thank you Nick, and thank you Oliver!

**Comment by inphobia** [comment]
wickedness, and thank you for going through all the troubleshooting steps with is.

if you have any other issues, you know where to find us.



note for later reference: might have been related to #475 #479 and all their related commits
