### ISSUE TITLE
shuffle input array for sshcollector

### ISSUE THREAD

**Issue by stromsoe** [netdisco/netdisco#434]
Shuffle the input array for netdisco-sshcollector.  This helps to make it less likely when running multiple collectors on different devices targeting diffrent devices that they will end up stepping on each other.

```
sub main {
    my @input = @{ setting('sshcollector') };

    #one-line Fisher-Yates from https://www.perlmonks.org/index.pl?node=Array%20One-Liners
    my ($i,$j) = (0);
    @input[-$i,$j] = @input[$j,-$i] while $j = rand(@input - $i), ++$i < @input;
```

**Comment by ollyg** [comment]
thanks! patch applied in 0e927446
