### ISSUE TITLE
Add a Cisco error-disable report

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#44]
Hello,

For people that have cisco infrastructur, it will be very nice to have a report (like port blocking or administratively disabled) with informations about error-disabled ports.
I don't think it will take you a lot of time like you have already create a report with others status like disabled ports.

Best Regards,

Nicolas

Reported by: lattanzio

Original Ticket: [netdisco/nd2-features/46](https://sourceforge.net/p/netdisco/nd2-features/46)

**Comment by nicox** [comment]
Is there any plan to implement this?
Can i be of any assistance to get this forward?

**Comment by ollyg** [comment]
Hi @nicox 
What's in the "up" column of your Device Port table in the DB? Anything useful for these err-disabled ports? What I mean is, do we already have the info in the DB or is there more SNMP required?

**Comment by JeroenvIS** [comment]
FWIW: I believe that reporting "err-disabled" ports is usually done in a vendor-specific method. I don't have any err-disabled ports in my network right now (and no Cisco access switch to quickly test with), but at least the configuration for this feature on a Cisco lives in CISCO-ERR-DISABLE-MIB.

Looks like the exact cause for err-disabled interfaces on Cisco is also available via SNMP:

```
snmptranslate -Td CISCO-ERR-DISABLE-MIB::cErrDisableIfStatusTable
CISCO-ERR-DISABLE-MIB::cErrDisableIfStatusTable
cErrDisableIfStatusTable OBJECT-TYPE
  -- FROM	CISCO-ERR-DISABLE-MIB
  MAX-ACCESS	not-accessible
  STATUS	current
  DESCRIPTION	"This table provides interface (port) specific
        error-disable status information. Each conceptual row
        provides status information about a {interface, vlan}
        disabled by a feature.

        On a trunk or multi-vlan access interface, a given vlan on
        the interface can be error-disabled. In this case, the row is
        indexed by the ifIndex for the interface and the vlan
        index corresponding to the vlan in question.

        If the interface is carrying only 1 vlan or the entire
        trunk interface is error-disabled (due to link flaps, for
        example) then the vlan index portion of the row index is
        0."
::= { iso(1) org(3) dod(6) internet(1) private(4) enterprises(1) cisco(9) ciscoMgmt(9) ciscoErrDisableMIB(548) ciscoErrDisableMIBObjects(1) cErrDisableIfObjects(3) 1 }

```

**Comment by JeroenvIS** [comment]
To check whether anything useful is already in the database, it would be interesting to know what combinations of values are already in the device_port table in the database.
Executing the following command would nicely who that:

`netdisco-do psql -e 'select up, up_admin, count(*) from device_port group by up, up_admin order by 3 asc'`

Example output on my server, without any (known) err-disabled ports:
```
netdisco-do psql -e 'select up, up_admin, count(*) from device_port group by up, up_admin order by 3 asc'
[52185] 2017-06-07 12:10:44  info psql: started at Wed Jun  7 14:10:44 2017
  up  | up_admin | count
------+----------+-------
 down | disable  |    38
      |          |   139
 up   | enable   |  1815
 down | down     |  2643
 up   | up       | 16447
 down | up       | 17285
(6 rows)

[52185] 2017-06-07 12:10:44  info psql: finished at Wed Jun  7 14:10:44 2017
[52185] 2017-06-07 12:10:44  info psql: status done: psql session closed.

```

**Comment by nicox** [comment]
netdisco-do psql -e 'select up, up_admin, count(*) from device_port group by up, up_admin order by 3 asc'
[7969] 2017-06-07 14:27:13  info psql: started at Wed Jun  7 16:27:13 2017
   up    | up_admin | count
---------+----------+-------
 up      |          |    15
 dormant | up       |    63
 down    |          |   149
 down    | down     |   615
 up      | up       |  2773
 down    | up       |  3402
(6 rows)

But i also do not know at the time if there is any err-disabled port.

**Comment by pskovajsa** [comment]
Hello,
I would be interested in this functionality as well. Here is output from our DB, we have about 10K Cisco devices, and I am pretty sure some of them have err-disabled ports as well.

bin/netdisco-do psql -e 'select up, up_admin, count(*) from device_port group by up, up_admin order by 3 asc' 
[10109] 2017-08-23 20:09:04  info psql:  started at Wed Aug 23 16:09:04 2017
`       up       | up_admin | count  
----------------+----------+--------
 down           | disable  |     33
 lowerLayerDown | up       |     38
                | testing  |    171
                | down     |    184
 dormant        | down     |    222
 dormant        |          |    283
 down           | enable   |    309
 unknown        |          |   1265
 up             |          |   2145
                | up       |   4618
                |          |   4733
 down           |          |   5017
 up             | enable   |   5746
 dormant        | up       |  25717
 unknown        | testing  |  49475
 down           | down     |  55383
 up             | up       | 207393
 down           | up       | 259152`

**Comment by pioevogel** [comment]
This would really be a very nice feature! Would love this.

**Comment by ollyg** [comment]
Hi @pioevogel 
As I have no Cisco kit, I cannot develop this "live". However if you have a device with a port in err-disable state (or can force this), then if you send me the output of this command, I will try:
`snmpwalk -v 2c -c {community} -ObentU {device} .1`
(send to oliver@cpan.org)
Thanks

**Comment by ollyg** [comment]
...and if the device has a port in portfast mode, it could help with a solution for #12 as well

**Comment by JeroenvIS** [comment]
We'll probably need the output from CISCO-ERR-DISABLE-MIB::cErrDisableIfStatusTable:

> .1.3.6.1.4.1.9.9.548.1.3.1
>cErrDisableIfStatusTable OBJECT-TYPE
>  -- FROM       CISCO-ERR-DISABLE-MIB
>  MAX-ACCESS    not-accessible
>  STATUS        current
>  DESCRIPTION   "This table provides interface (port) specific
>        error-disable status information. Each conceptual row
>        provides status information about a {interface, vlan}
>        disabled by a feature.
>
>        On a trunk or multi-vlan access interface, a given vlan on
>        the interface can be error-disabled. In this case, the row is
>        indexed by the ifIndex for the interface and the vlan
>        index corresponding to the vlan in question.
>
>        If the interface is carrying only 1 vlan or the entire
>        trunk interface is error-disabled (due to link flaps, for
>        example) then the vlan index portion of the row index is
>        0."
>::= { iso(1) org(3) dod(6) internet(1) private(4) enterprises(1) cisco(9) ciscoMgmt(9) ciscoErrDisableMIB(548) ciscoErrDisableMIBObjects(1) cErrDisableIfObjects(3) 1 }

**Comment by JeroenvIS** [comment]
Looks like there is no indication in the collected data (yet) about err-disabled ports, so for Cisco devices, it would be interesting to get an snmpwalk that includes CISCO-ERR-DISABLE-MIB::cErrDisableIfStatusTable (.1.3.6.1.4.1.9.9.548.1.3.1).

**Comment by pioevogel** [comment]
I've put one interface in err-disabled (Cisco 6509-E):
iso.3.6.1.4.1.9.9.548.1.3.1.1.2.144.0 = INTEGER: 9
iso.3.6.1.4.1.9.9.548.1.3.1.1.3.144.0 = Gauge32: 230

When I clear the err-disabled state I get:

iso.3.6.1.4.1.9.9.548.1.3.1 = No Such Object available on this agent at this OID

So that seems to work.

**Comment by JeroenvIS** [comment]
Ah, it was disabled because of a port-security violation and would be re-enabled 230 secs after you did this SNMP poll, is that right?

**Comment by JeroenvIS** [comment]
For HP/Aruba (the former ProCurve product line), it looks like there is no equivalent table; for some features (eg Loop Protect) the switch will show whether or not that feature is triggered on the port.

Two ports that I just looped together and are admin down because Loop Protect auto-disabled them, and the next port has no loop (and never had one):

HP-ICF-BRIDGE::hpicfBridgeLoopProtectPortLoopDetected.161 = INTEGER: true(1)
HP-ICF-BRIDGE::hpicfBridgeLoopProtectPortLoopDetected.162 = INTEGER: true(1)
HP-ICF-BRIDGE::hpicfBridgeLoopProtectPortLoopDetected.163 = INTEGER: false(2)
HP-ICF-BRIDGE::hpicfBridgeLoopProtectPortLastLoopTime.161 = Timeticks: (1449656905) 167 days, 18:49:29.05
HP-ICF-BRIDGE::hpicfBridgeLoopProtectPortLastLoopTime.162 = Timeticks: (1449656905) 167 days, 18:49:29.05
HP-ICF-BRIDGE::hpicfBridgeLoopProtectPortLastLoopTime.163 = Timeticks: (0) 0:00:00.00

...but after the loop is gone and the port is re-enabled, hpicfBridgeLoopProtectPortLoopDetected will stay "true" :-( So that's not really useful. The only way to reset the flag is by temporarily disabling the Loop Protect feature on the port.

**Comment by JeroenvIS** [comment]
Suggested SNMP::Info implementation is in a new branch on Github: https://github.com/netdisco/snmp-info/tree/jvi-cisco-errdisable.

**Comment by ollyg** [comment]
I need the snmpwalk from .1 to simulate and test this feature, so I cannot implement it yet.

**Comment by pioevogel** [comment]
Here's the requested output. Port 24 of this switch is in error dsabled state:
Fa0/24                       err-disabled 1            auto   auto 10/100BaseTX

[netdisco-errdis-walk-2960.log](https://github.com/netdisco/netdisco/files/1736892/netdisco-errdis-walk-2960.log)

**Comment by ollyg** [comment]
As of current Netdisco this is an included feature (see Reports -> Ports menu). Thanks all for your help and input!
