### ISSUE TITLE
feature: merge/append config items 

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#440]
the config docs state:
https://github.com/netdisco/netdisco/wiki/Configuration#introduction

> The config.yml file includes defaults for every setting, and should be left alone. Any time you want to set an option, use only the deployment.yml file. The two are merged when Netdisco starts, with your settings in deployment.yml overriding the defaults from config.yml.

well, i'm quite happy with the default config, but it would be nice if it could append instead of overwrite.

for example, i want to ignore an additional interface. ( https://github.com/netdisco/netdisco/wiki/Configuration#code-ignore_interfaces-code ), i would have to copy the complete block, then add my interface and on each upgrade compare my own interface list with the one that's distributed. being able to append to the list would be a nice alternative.

yaml does not seem to make this easy without some additional code however, so i would like to ask if such a feature can be considered.

thx

(the wiki says to close this ticket & link it on https://github.com/netdisco/netdisco/wiki/Wishlist , but alrdy got flagged twice this week for making edits on the netdisco wiki so perhaps someone else can take care of the linking)

**Comment by ollyg** [comment]
yes, just to be clear on what YAML config loader does:

- lists are replaced/overwritten
- dictionaries (hashes) are merged but only at the top level (so a duplicate key name is overwritten)

so you would like list merging, but I'm not sure that's even possible in a sane way (too many ways to do it, never mind that we use a third party module for YAML config loading anyway).

however for the example you give, we could create something which works for *additional* items for any list, and let's assume they go at the start.

IDEA: any list config item extra_FOO is prepended to the config item FOO on app load.

**Comment by inphobia** [comment]
moved to wishlish wiki page.
