### ISSUE TITLE
Enhancement, Vlan and Switch IP on the NodeVendor Report ... new code included.

### ISSUE THREAD

**Issue by swannie2** [netdisco/netdisco#442]
## Expected Behavior

Hello, I have modified the nodevendor report to provide the VLAN ID and the provide a hover-over of the switch IP address that the device is on.  We use this report to find things that are on the wrong vlan and the extra columns save us some clicking.  I thought it might be useful to the community, so here's the changes I made if you want to integrate them.

## Possible Solution

Here's a diff on ~/perl5/lib/perl5/auto/share/dist/App-Netdisco/views/ajax/report/nodevendor.tt

```
9d8
<         <th>Vlan ID</th>
52,57c51
<           return '<abbr title="' + he.encode(row.switch) + '"><a href="[% device_ports %]&q=' + encodeURIComponent(row.switch) + '&f=' + encodeURIComponent(data) + '&c_nodes=on&n_ssid=on"> ' + he.encode(row.device.dns || row.device.name || row.switch) + '(' + he.encode(data) + ')</a></abbr>';
<         }
<       }, {
<         "data": 'vlan',
<         "render": function(data, type, row, meta) {
<           return he.encode(data);
---
>           return '<a href="[% device_ports %]&q=' + encodeURIComponent(row.switch) + '&f=' + encodeURIComponent(data) + '&c_nodes=on&n_ssid=on">' + he.encode(row.device.dns || row.device.name || row.switch) + '(' + he.encode(data) + ')</a>';
```

## Your Environment

* Netdisco version used: 2.39.31
* SNMP::Info version used: 3.61

**Comment by swannie2** [comment]
... although now that I've used it a few days it looks like I'm getting duplicate records for MAC addresses, so perhaps the query isn't quite right.  I seem to be getting history data for the vlan tags.

**Comment by ollyg** [comment]
thanks, I have implemented this in
[master 654799e8] #442 add device ip, port and vlan to the node vendor report results

**Comment by zoeloe** [comment]
Nice feature, I appreciate. IMHO there is a side-effect with this enhancement.
We have several "(Unknown Vendor)" devices is seems,... when selecting this "Manufacturer" in the node vender inventory, the reports page tries to load, but hangs with a "Processing..." wait placeholder.
IMHO. If the vendor can't be mapped,... there's a problem.... Thanks for any advice..

**Comment by ollyg** [comment]
fixed in
[master 0ae6ea9d] #442 remove Unknown Vendor from sidebar option as it does not work
