### ISSUE TITLE
Excluding IP phones from discovery

### ISSUE THREAD

**Issue by rkerr** [netdisco/netdisco#444]
We have some VoIP handsets that support LLDP but supply very little info (eg lldpRemSysName and lldpRemSysDesc are blank). In the past we were able to exclude these from discovery by having "IP Phone" in discover_no_type - but lately it seems this no longer works.

Looking at the code I think how this worked was store_modules checked the LLDP capabilities and added "IP Phone:" to remote_type if the device was a phone. It looks like 94da566 removed that code.

I guess my question is - is there a new/different way to exclude devices from discovery based on LLDP capabilities? and if not is it possible to add one or to reinstate the old behaviour?

**Comment by ollyg** [comment]
Hi - I believe that commit did not alter the discover_no_type behaviour. The added code does introduce remote_is_phone, but that is not yet used for filtering discoveries.

However the step where discover_no_type is used is only on new discovery of a device. If the device is already in the queue or database then it's too late. netdisco will try to discover it.

Try deleting any such devices in the system and see what happens?

**Comment by rkerr** [comment]
It would help if I linked the correct commit - I meant e1b9f2225eeac5952d0199d7e6b6bce4a8dc57d8 - particularly the changes to lib/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm

This code originally looked through the CDP/LLDP neighbours of the device and adds "IP Phone:" before the worker evaluated whether it was discoverable. Now it doesn't.
