### ISSUE TITLE
feature: polling alarm or last poll status in titlebar

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#445]
> I ran into a situation where something went south on the server and NetDisco stopped scraping MAC addresses.  I noticed it about a week later when looking for a MAC address. A restart of the server seemed to resolve it.
> 
> Would it be possible to add a field in the menu bar that has the date/time of the last MAC entry update and possibly throw an alarm of some sort if there have been no changes in the last xx days or something?  I’m thinking either looking at the last_macsuck column in the device table or doing a query on the node table for the newest entry in the time_last column and throwing an error if its greater then 1 day or something.  I think option 2 is the best option because not having a mac change SOMEWHERE in the network within a day or so probably means that something isn’t working right.
>

**Comment by inphobia** [comment]
when our network is particularly stormy i've seen arpnip & macsuck runs not end for some reason even though new runs are started. as you can see we run them every 2 hours, but after an incident a few days ago all our jobs (discover, arpnip & macsuck) ran for 16hours or longer until we restarted the backend.

no errors were reported in the backend log, but when we restarted the backend these appeared. i was however looking in the jobqueue at that time & also deleted 1 device, so i'm not certain if this is related to the jobs which didn't end or my actions:
 * [3960] 2018-11-26 22:31:51 error bless( {'msg' => '{UNKNOWN}: Can\'t call method "update" on an undefined value at /home/testdisc/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 223, <__ANONIO__> line 1. at /home/testdisc/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 226'}, 'DBIx::Class::Exception' )
 * [3962] 2018-11-26 22:31:52 error bless( {'msg' => '{UNKNOWN}: Can\'t call method "update" on an undefined value at /home/testdisc/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 223, <__ANONIO__> line 1. at /home/testdisc/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 226'}, 'DBIx::Class::Exception' )

(note: we are in Europe/Brussels. i need to doublecheck but it seems the webinterface displays localtime but the logfiles seem to be in gmt)

netdisco 2.39.31, postgres 9.3.6


relevant config:

* workers:
   * tasks: 10
   * timeout: 600

 * schedule:
   * discoverall:
      * when: '5 7 * * *'
   * macwalk:
      * when:
         * min: 20
         * hour: '*/2'
   * arpwalk:
      * when:
        * min: 50
        * hour: '*/2'
   * nbtwalk: null
   * expire:
      * when: '30 23 * * *'

**Comment by ollyg** [comment]
note to self: use DateTimeX::Format::Ago

**Comment by ollyg** [comment]
Moved to wishlist
