### ISSUE TITLE
Netdisco 2.039033 database schema error

### ISSUE THREAD

**Issue by milieucentrum** [netdisco/netdisco#450]
Would you like to deploy the database schema? [y/N]: y
DB schema update complete.
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  relation "statistics" does not exist
LINE 1: ...o_ver, me.schema_ver, me.perl_ver, me.pg_ver FROM statistics...
                                                             ^ [for Statement "SELECT me.day, me.device_count, me.device_ip_count, me.device_link_count, me.device_port_count, me.device_port_up_count, me.ip_table_count, me.ip_active_count, me.node_table_count, me.node_active_count, me.netdisco_ver, me.snmpinfo_ver, me.schema_ver, me.perl_ver, me.pg_ver FROM statistics me WHERE ( me.day = ? )" with ParamValues: 1='2018-11-03'] at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Statistics.pm line 74

**Comment by milieucentrum** [comment]
Does anyone have an SQL dump of the schema to be imported into postgres?

**Comment by JeroenvIS** [comment]
I made a schema dump from our 2.039.031 install. Here it is: [netdisco_2_039_031.dump.gz](https://github.com/netdisco/netdisco/files/2552146/netdisco_2_039_031.dump.gz)

It's somewhat polluted with local extensions, but you can simply copy/paste the "statistics" table definition. For your convenience, I extracted the relevant bits from the schema dump.

Just as a workaround of course, this needs further investigation. Did you do a clean install or did you get this error while upgrading? If upgrading, from what version?



```
-- Name: statistics; Type: TABLE; Schema: public; Owner: netdisco
--
CREATE TABLE public.statistics (
    day date DEFAULT ('now'::text)::date NOT NULL,
    device_count integer NOT NULL,
    device_ip_count integer NOT NULL,
    device_link_count integer NOT NULL,
    device_port_count integer NOT NULL,
    device_port_up_count integer NOT NULL,
    ip_table_count integer NOT NULL,
    ip_active_count integer NOT NULL,
    node_table_count integer NOT NULL,
    node_active_count integer NOT NULL,
    netdisco_ver text,
    snmpinfo_ver text,
    schema_ver text,
    perl_ver text,
    pg_ver text
);
ALTER TABLE public.statistics OWNER TO netdisco;
--
-- Name: statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: netdisco
--
ALTER TABLE ONLY public.statistics
    ADD CONSTRAINT statistics_pkey PRIMARY KEY (day);
-- Name: TABLE statistics; Type: ACL; Schema: public; Owner: netdisco
--
REVOKE ALL ON TABLE public.statistics FROM PUBLIC;
REVOKE ALL ON TABLE public.statistics FROM netdisco;
GRANT ALL ON TABLE public.statistics TO netdisco;

```

**Comment by milieucentrum** [comment]
Hi,

Thank you very much. I am not able to check the install with the provided schema addition before next monday when at the customer, but will let you know. I attempted a clean install on a fresh Ubuntu 18.04 machine and and a prestine postgresql database. You should be able to reproduce that, as I was able to reproduce the fresh install issue on another Debian box too.

On 11/6/18 9:13 AM, Jeroen van Ingen Schenau wrote:

I made a schema dump from our 2.039.031 install. Here it is: netdisco_2_039_031.dump.gz<https://github.com/netdisco/netdisco/files/2552146/netdisco_2_039_031.dump.gz>

It's somewhat polluted with local extensions, but you can simply copy/paste the "statistics" table definition. For your convenience, I extracted the relevant bits from the schema dump.

Just as a workaround of course, this needs further investigation. Did you do a clean install or did you get this error while upgrading? If upgrading, from what version?

-- Name: statistics; Type: TABLE; Schema: public; Owner: netdisco
--
CREATE TABLE public.statistics (
    day date DEFAULT ('now'::text)::date NOT NULL,
    device_count integer NOT NULL,
    device_ip_count integer NOT NULL,
    device_link_count integer NOT NULL,
    device_port_count integer NOT NULL,
    device_port_up_count integer NOT NULL,
    ip_table_count integer NOT NULL,
    ip_active_count integer NOT NULL,
    node_table_count integer NOT NULL,
    node_active_count integer NOT NULL,
    netdisco_ver text,
    snmpinfo_ver text,
    schema_ver text,
    perl_ver text,
    pg_ver text
);
ALTER TABLE public.statistics OWNER TO netdisco;
--
-- Name: statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: netdisco
--
ALTER TABLE ONLY public.statistics
    ADD CONSTRAINT statistics_pkey PRIMARY KEY (day);
-- Name: TABLE statistics; Type: ACL; Schema: public; Owner: netdisco
--
REVOKE ALL ON TABLE public.statistics FROM PUBLIC;
REVOKE ALL ON TABLE public.statistics FROM netdisco;
GRANT ALL ON TABLE public.statistics TO netdisco;

**Comment by milieucentrum** [comment]
Does the trick, thanks!


Britt Rodriguez
Office Management
Milieucentrum Utrecht



________________________________

**Comment by inphobia** [comment]
would it be possible to elaborate on the error?

thx

// nick
