### ISSUE TITLE
Network Map is lagging a lot

### ISSUE THREAD

**Issue by MarcusCaepio** [netdisco/netdisco#453]
Hi All,
my server has 4 CPUs and 8 GB Ram. Nevertheless, the automap starts lagging a lot, when I show all devices and there are not really many devices. 
What could be the reason and fix for this?

Thanks in advance!

**Comment by inphobia** [comment]
what version of netdisco are you running & which graphviz version?

for me it's surprisingly fast, the following takes about 5 seconds in my browser to render (524 layer2 links). on the server side it seems to take less than 3 seconds, and this is on ancient xeon 5150's:
![image](https://user-images.githubusercontent.com/39005454/49119476-c185d080-f2a8-11e8-91a3-f1cd643c18a3.png)

yes, it's unreadably small to obfuscate details. also, most of this is through managed mpls, so the logical links are not present between all devices. as a workaround i'm planning to add a few psuedo devices to make those links visible as well.

**Comment by ollyg** [comment]
Hi @MarcusCaepio, the map is rendered completely in the client browser. Are you able to try on a more powerful workstation? Thanks.
