### ISSUE TITLE
Hostname in Report -> port utilization

### ISSUE THREAD

**Issue by Noname2244** [netdisco/netdisco#455]
When viewing the port utilization the Devices shows as IPs instead of hostname

![image](https://user-images.githubusercontent.com/34089487/48903825-e4eded00-ee5c-11e8-8def-048d4e889e1b.png)

How can I get the hostnames there?

Clicking on a device and looking at details netdisco has the hostname in the database.

**Comment by Noname2244** [comment]
Is reverse dns the only way?

**Comment by ollyg** [comment]
Hi, yes reverse DNS is the only way (or perhaps an /etc/hosts file but I don't recommend that)

The reason why you see a name for the device is that either the DNS is working, or else Netdisco will take the device sysName field from SNMP and display that in the web instead. This cannot be done for nodes.
