### ISSUE TITLE
device address sorting not working for "interface" field

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#457]
device address sorting not working for "interface" field, but only on specific devices.

## Expected Behavior

when clicking on a device, then going to "addresses" and the clicking on the "interface" table header, netdisco should sort the interfaces.

## Current Behavior

when doing this on a cisco nexus 9332pq switch for some reason my browser doesnt sort & just shows "processing" when using the interface table header to sort. other table headers like address or dns work fine, and on other devices "interface" also sorts as expected.
citrix netscalers also seem to have this issue.

## Steps to Reproduce (for bugs)

1. have access to a nexus switch or netscaler load balancer
1. click on device in netdisco
1. go to addresses
1. sort on interfaces by clicking on the table header
1. notice "processing" overlay in browser but no sorting happens
1. other headers sort just fine

i've gone over other device types as well but only netscaler & nx-os seem to have this issue. when trying to find a correlation i came up with the following:

for both the netscalers & nexus 9332s i notice:
* we have multiple addresses
* all ip addresses are shown correctly ("address" field)
* for netscaler all prefixes are shown, for nexus 1 prefix is missing
* at least 2 ports do not have dns entries (which is correct since some addresses dont have reverse dns)
* at least 2 ports dont have dont have their interface filled in. for the nexus these are ports that belong to different vrf's, netscalers dont have any interfaces filled in.
* the lack of interface names for __at least 2 ports__ seems to be the key here, we also have fortinet devices where only 1 interface is not filled in, and these sort correctly.

so, you need a device that has multiple interfaces, where at least 2 interfaces do not have an interface name and also lack dns entries (perhaps description too), then sorting will fail.

![image](https://user-images.githubusercontent.com/39005454/49108120-a3f43f00-f287-11e8-985b-2cfeefe882b7.png)

## Your Environment

* Netdisco version used: 2.39.33 & 2.39.31
* SNMP::Info version used: 3.63 & 3.61

**Comment by inphobia** [comment]
right, tested with:
* firefox 63.0.3 x64 on windows 10
* chrome 70.0.3538.102 & 70.0.3538.110 x64 on windows 10
* w3m 0.5.3-36+b1, ELinks 0.12pre6 & lynx 2.8.9rel.1 on debian testing, which are console based browsers. regretfully they dont work with netdisco, most likely since most of them have been unmaintainced for the last 10 years
* dillo 3.0.5 on debian testing, refuses to log in. most likely user or program error.

**Comment by inphobia** [comment]
well, my firefox throws an error: "TypeError: a is null" for portsort.js. sometimes also "b is null".

added a hack in #465 that fixes the issue for me.

**Comment by ollyg** [comment]
I didnt' apply that fix, in the end, apologies. We would need to look into this more

**Comment by inphobia** [comment]
yeah, i had a quick look at this again earlier today. for some reason both the a and/or b parameters given to portsort are either null or empty strings, which seems plausible since none of the interface names are filled in. it seems that one null entry for device_ip.port is enough to reproduce this issue.

when checking our the device_ip table we have 36 rows where port = null from a total of 2700 rows, so it seems to be rare.

a quick check pointed out that for some reason an ip address is mapped to a nonexisting interface (ip 10.10.10.1 to interface index 0):

```
netdisco-do show -d 10.91.90.1
[26520] 2019-01-02 20:20:34  info App::Netdisco version 2.040002 loaded.
[26520] 2019-01-02 20:20:34  info show: [10.91.90.1]/interfaces started at Wed Jan  2 21:20:34 2019
\ {
    1    "FastEthernet4",
    2    "FastEthernet0",
    3    "FastEthernet1",
    4    "FastEthernet2",
    5    "FastEthernet3",
    6    "VoIP-Null0",
    7    "Null0",
    8    "Vlan1",
    9    "Cellular0",
    10   "Cellular1",
    11   "Loopback0"
}
[26520] 2019-01-02 20:20:34  info show: finished at Wed Jan  2 21:20:34 2019
[26520] 2019-01-02 20:20:34  info show: status done: Showed interfaces response from 10.91.90.1

netdisco-do show -d 10.91.90.1 -e i_name
[26537] 2019-01-02 20:21:39  info App::Netdisco version 2.040002 loaded.
[26537] 2019-01-02 20:21:39  info show: [10.91.90.1]/i_name started at Wed Jan  2 21:21:39 2019
\ {
    1    "Fa4",
    2    "Fa0",
    3    "Fa1",
    4    "Fa2",
    5    "Fa3",
    6    "Vo0",
    7    "Nu0",
    8    "Vl1",
    9    "*** WAN interface ***",
    10   "Ce1",
    11   "Lo0"
}
[26537] 2019-01-02 20:21:40  info show: finished at Wed Jan  2 21:21:40 2019
[26537] 2019-01-02 20:21:40  info show: status done: Showed i_name response from 10.91.90.1

netdisco-do show -d 10.91.90.1 -e i_alias
[26542] 2019-01-02 20:21:46  info App::Netdisco version 2.040002 loaded.
[26542] 2019-01-02 20:21:46  info show: [10.91.90.1]/i_alias started at Wed Jan  2 21:21:46 2019
\ {
    1    "",
    2    "",
    3    "",
    4    "",
    5    "",
    6    "",
    7    "",
    8    "",
    9    "*** WAN interface ***",
    10   "",
    11   ""
}
[26542] 2019-01-02 20:21:47  info show: finished at Wed Jan  2 21:21:47 2019
[26542] 2019-01-02 20:21:47  info show: status done: Showed i_alias response from 10.91.90.1

netdisco-do show -d 10.91.90.1 -e ip_index
[26549] 2019-01-02 20:21:59  info App::Netdisco version 2.040002 loaded.
[26549] 2019-01-02 20:21:59  info show: [10.91.90.1]/ip_index started at Wed Jan  2 21:21:59 2019
\ {
    10.10.10.1      0,
    10.91.90.1      8,
    22.107.158.61   9,
    22.108.17.127   11
}
[26549] 2019-01-02 20:22:00  info show: finished at Wed Jan  2 21:22:00 2019
[26549] 2019-01-02 20:22:00  info show: status done: Showed ip_index response from 10.91.90.1

netdisco-do psql -e "select * from device_ip where ip = '10.91.90.1'"
[26760] 2019-01-02 20:34:39  info App::Netdisco version 2.040002 loaded.
[26760] 2019-01-02 20:34:39  info psql:  started at Wed Jan  2 21:34:39 2019
     ip     |     alias     |      subnet      |   port    | dns |          creation
------------+---------------+------------------+-----------+-----+----------------------------
 10.91.90.1 | 10.10.10.1    | 10.10.10.0/30    |           |     | 2019-01-02 19:12:47.010145
 10.91.90.1 | 22.107.158.61 | 22.107.158.61/32 | Cellular0 |     | 2019-01-02 19:12:47.010145
 10.91.90.1 | 10.91.90.1    | 10.91.90.0/24    | Vlan1     |     | 2019-01-02 19:12:47.010145
 10.91.90.1 | 22.108.17.127 | 22.108.17.127/32 | Loopback0 |     | 2019-01-02 19:12:47.010145
(4 rows)
```

here's an snmpwalk grepped on "10.10.10.1"

```
SNMPv2-SMI::mib-2.3.1.1.1.0.1.10.10.10.1 = INTEGER: 0
SNMPv2-SMI::mib-2.3.1.1.2.0.1.10.10.10.1 = Hex-STRING: 84 3D C6 8A 63 78
SNMPv2-SMI::mib-2.3.1.1.3.0.1.10.10.10.1 = IpAddress: 10.10.10.1
IP-MIB::ipAdEntAddr.10.10.10.1 = IpAddress: 10.10.10.1
IP-MIB::ipAdEntIfIndex.10.10.10.1 = INTEGER: 0
IP-MIB::ipAdEntNetMask.10.10.10.1 = IpAddress: 255.255.255.252
IP-MIB::ipAdEntBcastAddr.10.10.10.1 = INTEGER: 1
IP-MIB::ipAdEntReasmMaxSize.10.10.10.1 = INTEGER: 18024
SNMPv2-SMI::enterprises.9.2.4.1.1.1.10.10.10.1 = STRING: "unknown means"
SNMPv2-SMI::enterprises.9.2.4.1.1.2.10.10.10.1 = IpAddress: 0.0.0.0
SNMPv2-SMI::enterprises.9.2.4.1.1.3.10.10.10.1 = IpAddress: 0.0.0.0
SNMPv2-SMI::enterprises.9.2.4.1.1.4.10.10.10.1 = INTEGER: 0
SNMPv2-SMI::enterprises.9.2.4.1.1.5.10.10.10.1 = INTEGER: 1
SNMPv2-SMI::enterprises.9.2.4.1.1.6.10.10.10.1 = INTEGER: 1
```

but that ofcourse still does not fix portsort :)

**Comment by inphobia** [comment]
i think there are 2 solutions to this:
1. fixing portsort.js to cope with a and/or b being null
2. making sure portsort doesnt get fed null for a and/or b
   1. making sure the database does not contain null for parameters used in portsort
   2. validating all portsort callers

i went for option 2.ii, sorting on interface field now seems to work. also went through all other changed items & did not notice any regressions.

but would like some more testing.
