### ISSUE TITLE
cisco nexus 9332pq reports incorrect uptime

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#458]
netdisco reports incorrect system uptime for nexus 9332pq switches (nxos 7.0(3)I7(5) )

## Expected Behavior

report system uptime as reported by snmpget.

## Current Behavior

for some reason netdisco reports uptime incorrectly for 2 of 4 cisco 9332pq switches. there is 1 important difference: the switches where netdisco reports uptime incorrectly have been upgraded via enhanced in service system upgrade (lxc mode in cisco jargon). the ones where the uptime is reported correctly have been power cycled in recently (config is identical, they are also in lxc mode, but we had a ups failure and as such they were powercycled)

it seems both snmp::info & snmpget report the correct value but for some reason the netdisco webinterface reports something completely different.

we have tested this on our current production setup running netdisco 2.39.31 (which we have been upgrading for 2 years) and our test setup running netdisco 2.39.33 running a clean install with empty database, so we dont think we are running into cached data.

## Steps to Reproduce (for bugs)

__incorrect result, switch not powercycled__
1. netdisco's web interface reports: uptime - 2 years 8 days 11:00:47
2. snmpget reports:  DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (2085356343) 241 days, 8:39:23.43
3. netdisco-do show -e uptime: 
   * SNMP::Info 3.63
   * SNMP::Info::device_type() layers:01000110 id:9 sysDescr:"Cisco NX-OS(tm) nxos.7.0.3.I7.5.bin, Software (nxos), Version 7.0(3)I7(5), RELEASE SOFTWARE Copyrigh t (c) 2002-2018 by Cisco Systems, Inc. Compiled 8/28/2018 0:00:00"
   * 2085361754
4. "sh system uptime" output on switch:
   * System start time:          Sat Mar 31 15:38:03 2018
   * System uptime:              241 days, 8 hours, 44 minutes, 50 seconds
   * Kernel uptime:              241 days, 8 hours, 51 minutes, 46 seconds

__correct result, switch powercycled__
1. netdisco's web interface reports: uptime - 10 days 10:02:32
2. snmpget reports: DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (90078343) 10 days, 10:13:03.43
3. netdisco-do show -e uptime:
   * SNMP::Info 3.61
   * SNMP::Info::device_type() layers:01000110 id:9 sysDescr:"Cisco NX-OS(tm) nxos.7.0.3.I7.5.bin, Software (nxos), Version 7.0(3)I7(5), RELEASE SOFTWARE Copyrigh t (c) 2002-2018 by Cisco Systems, Inc. Compiled 8/28/2018 0:00:00"
   * 90083854
4. "sh system uptime" output on switch:
   * System start time:          Sat Nov 17 13:06:30 2018
   * System uptime:              10 days, 10 hours, 17 minutes, 10 seconds
   * Kernel uptime:              10 days, 10 hours, 19 minutes, 4 seconds

## Your Environment

* Netdisco version used:  2.39.31 & 2.39.33
* SNMP::Info version used: 3.61 & 3.63

**Comment by inphobia** [comment]
upon investigation is seems that this is caused by the discovery code to try & figure out uptime wraps.

* IF-MIB::ifLastChange.533072832 = Timeticks: (4294959600) 497 days, 2:26:36.00
* DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (2141140165) 247 days, 19:36:41.65
* SNMP-FRAMEWORK-MIB::snmpEngineTime.0 = INTEGER: 21411428 seconds

since iflastchange > sysyptimeinstance an uptime wrap is assumed.


after bouncing an interface (shut; no shut) iflastchange is set to the correct value (test done a few days ago):
* IF-MIB::ifLastChange.151061282 = Timeticks: (2123433313) 245 days, 18:25:33.13
* DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (2123567222) 245 days, 18:47:52.22

regretfully bouncing all interfaces isnt really an option. i only used 1 interface in this example but we have around 30 per switch which exhibit this issue.

this seems to be an nx-os bug to me however, since iflastchange > sysuptimeinstance without an uptime wrap. a search through the cisco bug database didnt turn up anything related however.

**Comment by JeroenvIS** [comment]
Indeed, sounds like a bug on the Cisco side. Also, probably not something that many people will notice or report...
Would be nice if there was an alternative way to reset the ifLastChange counter on NX-OS, without bouncing the interface.

**Comment by inphobia** [comment]
we have a disaster testing exercise coming up in 2 weeks. for the 2 switches that do not exhibit the problem i'll be upgrading them from 7.0(3)I7(5) to 7.0(3)I7(5a) & check if they start having the same issue.
the ones that have the issue will be powercycled and see if that solves the issue.

but most likely an nx-os bug, and if so, i'll close this issue & perhaps add a note to the vendor page of the wiki.

**Comment by inphobia** [comment]
seems our citrix netscalers have the same issue:

netdisco-do show -d 10.40.254.135 -e ifLastChange
[7565] 2018-12-10 01:03:30  info App::Netdisco version 2.039033 loaded.
[7565] 2018-12-10 01:03:31  info show: [10.40.254.135]/ifLastChange started at Mon Dec 10 02:03:31 2018
\ {
    1    4294963896,
    2    4294963896,
    3    4294963896,
    4    4294963896,
    5    4294963896,
    6    4294963896,
    7    17500,
    8    17000,
    9    3800,
    10   4294963896,
    11   17400
}


 netdisco-do show -d 10.40.254.135 -e uptime
[7574] 2018-12-10 01:03:43  info App::Netdisco version 2.039033 loaded.
[7574] 2018-12-10 01:03:43  info show: [10.40.254.135]/uptime started at Mon Dec 10 02:03:43 2018
194742110

netdisco-do show -d 10.40.254.135 -e description
[7581] 2018-12-10 01:04:18  info App::Netdisco version 2.039033 loaded.
[7581] 2018-12-10 01:04:18  info show: [10.40.254.135]/description started at Mon Dec 10 02:04:18 2018
"NetScaler NS11.1: Build 58.13.nc, Date: Apr 26 2018, 23:01:48  "


netdisco-do psql -e "SELECT ip, uptime from device where ip = '10.40.254.135'"
[7637] 2018-12-10 01:09:15  info App::Netdisco version 2.039033 loaded.
[7637] 2018-12-10 01:09:15  info psql:  started at Mon Dec 10 02:09:15 2018
      ip       |   uptime
---------------+------------
 10.40.254.135 | 4486494197
(1 row)

netdisco-do psql -e "SELECT ip,port,lastchange from device_port where ip = '10.40.254.135' order by port asc"
[7658] 2018-12-10 01:10:24  info App::Netdisco version 2.039033 loaded.
[7658] 2018-12-10 01:10:24  info psql:  started at Mon Dec 10 02:10:24 2018
      ip       | port | lastchange
---------------+------+------------
 10.40.254.135 | 0/1  |       3900
 10.40.254.135 | 10/1 |      17100
 10.40.254.135 | 10/2 |      17600
 10.40.254.135 | 1/1  | 4294963996
 10.40.254.135 | 1/2  | 4294963996
 10.40.254.135 | 1/3  | 4294963996
 10.40.254.135 | 1/4  | 4294963996
 10.40.254.135 | 1/5  | 4294963996
 10.40.254.135 | 1/6  | 4294963996
 10.40.254.135 | LA/1 |      17500
 10.40.254.135 | LO/1 | 4294963996
(11 rows)

**Comment by ollyg** [comment]
closed as vendor bug
