### ISSUE TITLE
netdisco-web restart fails when used with --port

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#472]
when using netdisco-web restart when netdisco-web has previously been started with the --port option, restart fails even though it says it's succesful.

## Expected Behavior

netdisco-web restart should remember --port option

## Current Behavior

1. restart uses default port option (tcp/5000)
2. restart says it's succesful while failing.

## Possible Solution

1. netdisco-web needs to remember it's argv better
2. could be related to https://github.com/symkat/Daemon-Control/pull/65

the port option would be interesting to add to the netdisco config somewhere, so it's no longer a commandline option only.

## Steps to Reproduce (for bugs)

1. netdisco-web start --port=5555
Netdisco Web                                                  [Started]
config watcher: watching /home/testdisc/environments for updates.
2. netdisco-web restart
config watcher: sending TERM to the server (pid:22564)...
Netdisco Web                                                  [Stopped]
Netdisco Web                                                  [Started]
config watcher: watching /home/testdisc/environments for updates.
3. logs:
2018/12/30-04:03:56 Starman::Server (type Net::Server::PreFork) starting! pid(22564)
Resolved [*]:5555 to [0.0.0.0]:5555, IPv4
Binding to TCP port 5555 on host 0.0.0.0 with IPv4
Setting gid to "100 100"
[22566] 2018-12-30 03:03:56  warn App::Netdisco 2.040000 web
[22567] 2018-12-30 03:03:56  warn App::Netdisco 2.040000 web
[22568] 2018-12-30 03:03:56  warn App::Netdisco 2.040000 web
[22565] 2018-12-30 03:03:56  warn App::Netdisco 2.040000 web
[22569] 2018-12-30 03:03:56  warn App::Netdisco 2.040000 web
2018/12/30-04:04:05 Server closing!
2018/12/30-04:04:06 Starman::Server (type Net::Server::PreFork) starting! pid(22589)
Resolved [*]:5000 to [0.0.0.0]:5000, IPv4
Binding to TCP port 5000 on host 0.0.0.0 with IPv4
2018/12/30-04:04:06 Can't connect to TCP port 5000 on 0.0.0.0 [Address already in use]
  at line 64 in file /home/testdisc/perl5/lib/perl5/Net/Server/Proto/TCP.pm
2018/12/30-04:04:06 Received QUIT. Running a graceful shutdown
2018/12/30-04:04:06 Worker processes cleaned up
2018/12/30-04:04:06 Server closing!

## Context

there are 2 issues here:
1. netdisco-web restart says it's succesfull while it fails.
2. netdisco-web restart does not remember port option.

## Your Environment

* Netdisco version used: 2.040000
* SNMP::Info version used: 3.63
* Daemon::Control 0.001008
* perl 5.26.1

**Comment by ollyg** [comment]
This page:
https://metacpan.org/pod/Dancer::Config#port-(int)

suggests two other ways to set the listening port (the config would go in `deployment.yml`).

However there is a caveat... the `netdisco-web` script does check for a port argument to know whether to set the effective gid/uid (I think so it can drop privileges after spawning to listen on a privileged port), so that might need checking, or ignoring, depending on your situation.
