### ISSUE TITLE
discover plugins dont respect ignore_*settings

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#475]
other as worker/plugin/discover/properties.pm, none of the discover plugins respect ignore_interfaces (and ignore_notpresent_types, most likely ignore_private_nets too)

## Expected Behavior

no interfaces which would qualify under ignore_interfaces/ignore_notpresent_types/ignore_private_nets should show up in the netdisco database.

## Current Behavior

device_port_properties, device_port_power & most likely some other tables include ignored interfaces.

## Possible Solution

we can either duplicate the ignore code for interfaces & notpresent in all discover plugins, which is easy but lazy, or find some other option - perhaps a device_port_ignore table, having $snmp->interfaces return a filtered list since all discover plugins seem to use that function (if_ignore() is part of base snmp::info, which could be a target) or another function to get all ignored interfaces per device (using device_port as basis for port discovery perhaps, but i feel that's not quite in line with the spirit of discover, where you can also run subclasses.) or running a verification after each discover plugin against device_port to clean out not referenced interfaces.

## Steps to Reproduce (for bugs)

1. discover a device which includes ignored interfaces (like cisco 3750series with stackports, cisco ios with bri etc) via `netdisco-do discover -D` , note which interfaces got ignored.
2. get list of ignored interfaces via `netdisco-do dumpconfig -e ignore_interfaces`
3. get list of interfaces, for example: `netdisco-do psql -e "select ip,port from device_port where port ilike 'ii%' and ip = '10.40.72.250';"` . notice no ignored interfaces show up.
4. get list of port properties, for example: `netdisco-do psql -e "select ip,port from device_port_properties where port ilike 'ii%' and ip = '10.40.72.250';"`. notice ignored interfaces do show up.

(example focuses on ignore_interfaces, but same issue goes for ignore_notpresent_types & ignore_private_nets too)

## Context

i guess since most queries go through the DevicePort resultset the current impact is limited to niche usage.

## Your Environment

* Netdisco version used: 2.040002
* SNMP::Info version used: 3.64

**Comment by ollyg** [comment]
Thanks again for this! Very good.

Fixed in:
[master ccb0f0c7] #475 fix discover plugins do not respect ignore* config

Note that the retrieval of SNMP interfaces is still required to get inerface IDs to use in mappings, although normally it's cached so not expensive. I've changed the code to always first check that any port in the interface list is actually in the DB, and during a discover that will be cached from the initial properties phase, for efficiency.

**Comment by inphobia** [comment]
nono, thank you! you did the actual work to get it fixed :-)

**Comment by inphobia** [comment]
it seems this broke neighbor discovery, i no longer have links between devices or lldp/cdp info etc...

```
[10064] 2019-01-03 14:05:08 debug -> DBIx::Class::PK::_ident_values(): Unable to uniquely identify result object with missing PK columns: ip at /home/testdisc/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm line 259
[10064] 2019-01-03 14:05:08 debug bless( {'msg' => 'DBIx::Class::PK::_ident_values(): Unable to uniquely identify result object with missing PK columns: ip at /home/testdisc/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm line 259
'}, 'DBIx::Class::Exception' )
```

running the discover::neighbors worker seperatly works and restores the information until the next discover run.

**Comment by ollyg** [comment]
I hope this is fixed in:
[master 7811c321] fix cached ports list which needs to be complete rows for Neighbors.pm to work
