### ISSUE TITLE
netdisco-do discover cleans all interfaces during discover::properties but fails to mention this

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#476]
using netdisco-do discover -d ip -DQ you will see that during interface discovery all interface references are cleared, but this is not mentioned during this step. in later steps such as portproperties no ports will be cleaned up since they alrdy got deleted, making debugging confusing.

## Expected Behavior

netdisco-do discover -D should mention everything it deletes.

## Current Behavior

no mention of anything other as interfaces is given. other device_port_* tables might even contain more port mappings for the device due to #475 

## Possible Solution

not that easy, not using deviceport resultset and using deviceport result instead could lead to unmatched interfaces. but deleting everything during discover::properties seems like a step to far.
one option is to check all device_port_* tables after a discover::properties for invalid ports, but overhead on this seems painful, more so since discover subtasks are seldom run alone.

## Steps to Reproduce (for bugs)

1. netdisco-do discover -d ip -DQ

> BEGIN WORK
> DELETE FROM device_port_power
> WHERE ip IN (
>     SELECT me.ip
>       FROM device_port me
>     WHERE me.ip = '10.40.72.250'
>    )
> DELETE FROM device_port_properties
> WHERE ip IN (
>     SELECT me.ip
>       FROM device_port me
>     WHERE me.ip = '10.40.72.250'
>    )
> DELETE FROM device_port_vlan
> WHERE ip IN (
>     SELECT me.ip
>       FROM device_port me
>     WHERE me.ip = '10.40.72.250'
>    )
> DELETE FROM device_port_wireless
> WHERE ip IN (
>     SELECT me.ip
>       FROM device_port me
>     WHERE me.ip = '10.40.72.250'
>    )
> DELETE FROM device_port_ssid
> WHERE ip IN (
>     SELECT me.ip
>       FROM device_port me
>     WHERE me.ip = '10.40.72.250'
>    )
> DELETE FROM device_port
> WHERE ip = '10.40.72.250'
> [17187] 2019-01-02 06:17:16 debug  [10.40.72.250] interfaces - removed 112 interfaces
> SAVEPOINT savepoint_0
> UPDATE device
>   SET uptime = '6685615953'
> WHERE ip = '10.40.72.250'
> RELEASE SAVEPOINT savepoint_0
> SAVEPOINT savepoint_0
> INSERT INTO device_port( descr, duplex, duplex_admin, ip, is_master, lastchange, mac, mtu, name, port, pvid, slave_of, speed, stp, type, up, up_admin, vlan )
>   VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) : '__BULK_INSERT__'
> RELEASE SAVEPOINT savepoint_0
> COMMIT
> [17187] 2019-01-02 06:17:16 debug  [10.40.72.250] interfaces - added 112 new interfaces

notice how all references from device_port_* get deleted during discover::properties but no mention of this is made.

2. later steps repeat the delete steps:

> COMMIT
> BEGIN WORK
> DELETE FROM device_port_vlan
> WHERE ip = '10.40.72.250'
> [17187] 2019-01-02 06:17:18 debug  [10.40.72.250] vlans - removed 0 port VLANs
> SAVEPOINT savepoint_0
> INSERT INTO device_port_vlan( ip, last_discover, native, port, vlan, vlantype )
>   VALUES( ?, now(  ), ?, ?, ?, ? ) : '__BULK_INSERT__'
> RELEASE SAVEPOINT savepoint_0
> COMMIT
> [17187] 2019-01-02 06:17:18 debug  [10.40.72.250] vlans - added 762 new port VLANs

## Context

running only discover::properties will delete all other port references for the device as well. no mention of this is made with netdisco-do -D option.

## Your Environment

* Netdisco version used:  2.040002
* SNMP::Info version used: 3.64

**Comment by ollyg** [comment]
Hi, commit 5bc0afa2 implements logging of deleted entries for the table related to devices and device ports, when they are deleted through the related source (a device or a port):

    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/device - removed 2 entries from DeviceIp
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/device - removed 0 entries from DeviceVlan
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/device - removed 0 entries from DevicePower
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/device - removed 0 entries from DeviceModule
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/device - removed 1 entry from Community
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/device - removed 0 manual topology entries
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/ports - removed 0 port entries from  DevicePortPower
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/ports - removed 14 port entries from DevicePortProperties
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/ports - removed 0 port entries from DevicePortVlan
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/ports - removed 0 port entries from DevicePortWireless
    [2953] 2019-01-02 21:43:59 debug  [127.0.0.1] db/ports - removed 0 port entries from DevicePortSsid

Note where this is implented... in the custom delete methods within the Device and DevicePort resultsets. There is also a custom delete() in Node.pm, but for device deletion it actually archives nodes rather than deleting them (that's why we have the override in the first place).
