### ISSUE TITLE
Switch uptime is incorrect

### ISSUE THREAD

**Issue by pedrompcaetano** [netdisco/netdisco#488]
This switch reports incorrect uptime - WS-C3750G-48TS (c3750-ipbase-mz.122-25.SEB4)

## Expected Behavior
The switch should report the correct uptime ( sw_GRAF-3750-01 uptime is 12 years, 48 weeks, 6 days, 17 hours, 54 minutes)

## Current Behavior
It reports 2 years 15 days 21:54:05

## Steps to Reproduce (for bugs)

1. Trigger discovery of the switch

## Context
We'd like to have a correct overview of the switches' global uptime

## Your Environment

* Netdisco version used: 2.40.2
* SNMP::Info version used: 3.64

Thanks in advance

**Comment by pedrompcaetano** [comment]
Hi,

The output is:
[12119] 2019-01-15 19:47:57  info App::Netdisco version 2.040002 loaded.
[12119] 2019-01-15 19:47:57  info show: [x.x.x.x]/snmpEngineTime started at Tue Jan 15 12:47:57 2019
21517554
[12119] 2019-01-15 19:47:58  info show: finished at Tue Jan 15 12:47:58 2019
[12119] 2019-01-15 19:47:58  info show: status done: Showed snmpEngineTime response from 10.200.200.19

Thank you for your help.
PS:
This switch is a great warrior still pushing traffic all this years!
The building where this switch is running will be decomissioned in a few weeks, so I'd like to poll its data correctly for historical reasons.

**Comment by JeroenvIS** [comment]
Aw, too bad... it reports 21517554, which is in seconds; that's just 5977 hours, or 249 days. So maybe the SNMP engine was somehow restarted without restarting the switch, or perhaps there's a bug in snmpEngineTime implementation on the device.

**Comment by JeroenvIS** [comment]
Looks like several Cisco products have had bugs wrt snmpEngineTime implementation... on CatOS, IOS, IOS-XR and NX-OS releases. IOS eg CSCso48499 and CSCeh49492.

So I guess you'll just have to save the relevant "show" output for this device, to brag about its uptime ;-)

**Comment by pedrompcaetano** [comment]
I will follow your suggestion, thank you for the time you spent analyzing this issue.

Best regards,
Pedro Caetano
