### ISSUE TITLE
Send an email when a new device is discovered

### ISSUE THREAD

**Issue by earendilfr** [netdisco/netdisco#495]
## Expected Behavior
When the discover worker show a new device with the neighbor discovery, it could be a good idea to configure the hability to send a mail report after the new discover.

It's could be also 

## Current Behavior
The new device are discover but no report when it's done.

## Possible Solution
Just add a new step at the end of discover to build a report and sent it by email.

## Context
Be warn when other IT user add devices on the netwok to update the record in DNS...

## Your Environment
* Netdisco version used: 2.39.31
* SNMP::Info version used: 3.61

**Comment by ollyg** [comment]
Hi @earendilfr, right now this is not supported and I don't think we'll find the core dev time to implement. Patches are very welcome! Please add an item to the Wishlist wiki page if you wish. Many thanks,
