### ISSUE TITLE
Wrong VLANs on Neighbor Map 

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#497]
Dear netdisco developers team,

The map created by netdisco is not showing the correct layout, some device in a specific VLAN are not shown.

## Expected Behavior
In Neighbor Map, I searched for all the devices on a specific VLAN, but a device is not shown.

## Current Behavior
I searched all the devices on VLAN numbered 357, I get only 3 devices on the map.

But if I make a query for 357 I get 4 devices.

## Your Environment
Software	Version
App::Netdisco	2.40.3
SNMP::Info	3.64
DB Schema	53
PostgreSQL	9.6.10
Perl	                5.24.1

Best Regards.

**Comment by DomenicoDeFelice86** [comment]
Yes, I have selected All Devices and the carrying VLAN.

/netdisco-do psql -e "select * from device_vlan where vlan = 357"
[8740] 2019-02-01 17:28:29  info App::Netdisco version 2.040003 loaded.
[8740] 2019-02-01 17:28:29  info psql:  started at Fri Feb  1 18:28:29 2019
      ip       | vlan | description |          creation          |       last_discover        
---------------+------+-------------+----------------------------+----------------------------
 10.128.250.64 |  357 | OpenStack   | 2019-02-01 07:06:56.860092 | 2019-02-01 07:06:56.860092
 10.23.252.2   |  357 | OpenStack   | 2019-02-01 07:10:01.170672 | 2019-02-01 07:10:01.170672
 10.128.250.19 |  357 | OpenStack   | 2019-02-01 07:05:26.517844 | 2019-02-01 07:05:26.517844
(3 righe)

[8740] 2019-02-01 17:28:29  info psql: finished at Fri Feb  1 18:28:29 2019
[8740] 2019-02-01 17:28:29  info psql: status done: psql session closed.





./netdisco-do psql -e "select * from device_port_vlan where vlan = 357"
[8753] 2019-02-01 17:29:03  info App::Netdisco version 2.040003 loaded.
[8753] 2019-02-01 17:29:03  info psql:  started at Fri Feb  1 18:29:03 2019
      ip       | port  | vlan | native |          creation          |       last_discover        | vlantype 
---------------+-------+------+--------+----------------------------+----------------------------+----------
 10.128.250.19 | D4    |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | E13   |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | C2    |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | D5    |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | E15   |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | C6    |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | E17   |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | Trk20 |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | C5    |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | D1    |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.128.250.19 | C1    |  357 | f      | 2019-02-01 07:05:26.542871 | 2019-02-01 07:05:26.542871 | 
 10.23.252.2   | 26    |  357 | f      | 2019-02-01 07:10:01.186045 | 2019-02-01 07:10:01.186045 | 
 10.23.252.2   | 20    |  357 | f      | 2019-02-01 07:10:01.186045 | 2019-02-01 07:10:01.186045 | 
 10.128.250.64 | Trk1  |  357 | f      | 2019-02-01 07:06:56.866318 | 2019-02-01 07:06:56.866318 | 
 10.128.250.64 | 13    |  357 | t      | 2019-02-01 07:06:56.866318 | 2019-02-01 07:06:56.866318 | 
 10.128.250.64 | 24    |  357 | f      | 2019-02-01 07:06:56.866318 | 2019-02-01 07:06:56.866318 | 
 10.128.250.64 | 15    |  357 | t      | 2019-02-01 07:06:56.866318 | 2019-02-01 07:06:56.866318 | 
 10.128.250.64 | 11    |  357 | t      | 2019-02-01 07:06:56.866318 | 2019-02-01 07:06:56.866318 | 
(18 righe)

[8753] 2019-02-01 17:29:03  info psql: finished at Fri Feb  1 18:29:03 2019
[8753] 2019-02-01 17:29:03  info psql: status done: psql session closed.



Thank you

**Comment by inphobia** [comment]
well, you might have 4 devices with vlan 357, but netdisco only knows of 3.

for the device you are missing, can you run:
`netdisco-do show -d ip_of_device -e specify`

NOTE: this will contain sensitive info like snmp community strings & such. you can cut those parts out if you want.


also, you stated when you query you get 4. what query are you referring to?

**Comment by DomenicoDeFelice86** [comment]
it does look that running netdisco-do fixed it....

Now it is right.. No idea what happened...

**Comment by inphobia** [comment]
either it wasn't completely discovered, perhaps due to snmp timeout or any other reason.

or snmp::info doesn't know what to do with it a flipflops between classes (almost never happens)
