### ISSUE TITLE
Utilize PostgreSQL ip4r contrib module

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#5]
[ip4r](https://github.com/petere/ip4r-cvs/blob/master/README.ip4r) supports index lookups of the form (column >>= parameter), i.e. where you have a table of IP address ranges and wish to find which ones include a given IP address.

The PostgreSQL built-in types 'inet' and 'cidr' do not support index based lookups on ranges, as a result full table sequential scans are performed on many common Netdisco operations.

Use of this module should improve the database performance especially in large deployments.

This would require both installation of the module and modifications to the schema to use the new types and indices.

The module is available for Debian and Ubuntu: postgresql-9.x-ip4r however a quick scan did not indicate ip4r 2.x available as a RPM for CentOS / Redhat.  2.x needed for ipv4 and ipv6 support.

This may be something we consider as a fork or variant for large deployments that need the speed?  

Reported by: jeneric-placeholder

Original Ticket: [netdisco/nd2-features/5](https://sourceforge.net/p/netdisco/nd2-features/5)

**Comment by ollyg** [comment]
Moved to Wishlist page in wiki.
