### ISSUE TITLE
filtering in device/ports on native vlan duplicates entries

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#500]
when using the sidebar to filter on vlan id, ports who's native vlan matches that id get duplicate entries in the ports lists, one entry per vlan membership.

## Expected Behavior

filtering on vlan should show ports who's native vlan or vlan membership matches, but only once.

## Current Behavior

when the native vlan matches, port entries get duplicated once per vlan member.

for example, when looking for "254", a port which has native vlan 254 shows entries for each vlan member:
![image](https://user-images.githubusercontent.com/39005454/52529083-ae04d600-2ceb-11e9-913a-276c353cd32f.png)

## Steps to Reproduce (for bugs)

1. go to device -> ports
2. filter on vlan id, using "1" is easiest.

## Your Environment

* Netdisco version used: 2.40.3
* SNMP::Info version used: HEAD

**Comment by ollyg** [comment]
thanks, fixed in
[master 78e30a79] #500 filtering in device/ports on native vlan duplicates entries
