### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jab375** [netdisco/netdisco#507]
Hello,
I'm not sure if this is the right place to post this.
Is there a way to do a search for ports on all devices (or just a couple) that have been down for 180 days?
I think this is where NETDB has this program beat and since NETDB seems to be dead project it would be nice to see all the NETDB reports integrated on NetDisco.

**Comment by ollyg** [comment]
Hi Joshua (fine to ask here),

A "free port" in Netdisco is a port that has been down for some time. In
the device's ports tab, you can set this time in the sidebar options on the
right hand side. There is also a Port Utilization report under Device,
which allows the same option and shows for all devices.

It's easy to add new reports if you need them, either through SQL in your
own config or open a ticket if you think it's more complex. Many thanks!

**Comment by JeroenvIS** [comment]
By the way, please note that this will only work for devices with uptime higher than the "port down for" period. So if a switch was rebooted eg 30 days ago, Netdisco doesn't know if it was up or down before the switch was rebooted, and will consider it down for 30 days.

**Comment by inphobia** [comment]
another option could also be to add a custom report. regretfully i don't have time atm to finish the example i started (missing the time part of the filter), but this should get you going. this will not provide a handy filtering sidebar however.

```
  - tag: portsdownall
    label: 'ports down for 180days'
    category: Port
    columns:
    - { ip: Device }
    - { dns: DNS }
    - { port: Port }
    - { name: Description }
    - { pstatus: Status }
    query: |
      SELECT dp.ip, d.dns, dp.port, dp.name, dp.up AS pstatus
        FROM device_port dp
        LEFT JOIN device d USING (ip)
      WHERE dp.up = 'down'
      ORDER BY dp.ip, dp.port

```


this should be added to the reports or system_reports key in deployment.yml, not sure which.
