### ISSUE TITLE
extracting device_port ifindex() from ND database? Does it exist?

### ISSUE THREAD

**Issue by Stoatwblr** [netdisco/netdisco#510]
I'm kludging together a script as first pass at demonstrating use of ND as source for GLPI/fusioninventory network inventory, as the existing fusioninventory code is "somewhat broken" (it only really works for Catalyst switches and having multiple sets of software doing polls isn't a good idea anyway as a lot of switches are quite fragile)

This uses OCSinventory XML format - The format is at http://fusioninventory.org/documentation/dev/spec/protocol/netinventory.html (but not well explained)

Unfortunately... (there's always a but isn't there?) I can't find any column in device_port_* or anywhere else which is related to ifindex. 

A lot of third party stuff is pinned on using ifindex numbers so keeping this intact would be preferable to reconstructing it later if feeding to third party software.

**Comment by rc9000** [comment]
Unfortunately currently the ifindex is not stored in the database. You can however display them live from the device with the show command:

     $ bin/netdisco-do show -d 10.5.43.29 -e interfaces 
    [11825] 2019-02-18 10:06:31  info App::Netdisco version 2.040002 loaded.
    [11825] 2019-02-18 10:06:31  info show: [10.5.43.29]/interfaces started at Mon Feb 18 11:06:31 2019
    \ {
        1    "GigabitEthernet0/0",
        2    "Null0",
        3    "GigabitEthernet1/0/1",
        4    "GigabitEthernet1/0/2",
       ....

Maybe you can use this with some scripting as a workaround? Long-term I'd say that this is a worthwhile feature request, we've also been missing the ifindex already when linking Netdisco data to other systems.

**Comment by Stoatwblr** [comment]
I've been discussing this with Oliver and JVI in the IRC channel today. They're agreeable to the idea.

The idea is to avoid adding extra load to the switches. For the moment I'm extracting the ifindex (and in/out octets/errors) from mrtg configfiles and rrd databases - polling them for the ifindex is only a few seconds but the counters can be as much as 4 minutes per pass (Huawei Quidways - they have awful SNMP code and an attitude of "nobody really uses SNMP, do they?", so they farm it out to "low cost Mumbai contractors"....) and I'd prefer to avoid abusing the switches too much as the cpu load goes through the roof.

**Comment by rc9000** [comment]
Ok I'll give it a try to implement that. No promises on an ETA though, might take me a while.

@ollyg @JeroenvIS we just put this into device_port.ifindex, overwriting it on every discovery with whatever the ifindex for the current device_port.port is? Or did you have something else in mind? As the only weird choice, I'd make it a bigint instead of an integer (signed in postgres), since especially with Huawei DSL and FTTH gear we had issues in the past that the ifindex might be out of the range IF-MIB specififes (signed Integer32) - see e.g. [this thread](https://forums.cacti.net/viewtopic.php?f=21&t=53298).

**Comment by Stoatwblr** [comment]
That suits me perfectly. I did think that trying to create a "more stable" pseudoindex (possibly based on ifdescr/ifname hashing?) might be worthwhile but that's probably beyond the scope of the task at hand and would be complicated by things like Cisco sg300s using the same name for _both_ l2vlan and l3vlanif devices.

The rationale for that is that a lot of stuff which relies on ifindex also forgets that ifindex can be unstable and will react to "renumbering" by creating new ports but I think at that point we're moving into the realms of telling people to sort their code out.

That said, the idea of effectively making netdisco into a "massaging snmp proxy" has some appeal :)

**Comment by rc9000** [comment]
@Stoatwblr in the next release (or if you use the code from master), you should now be able to find the ifindex in device_port_properties.ifindex. Let us know if you encounter any issues.

**Comment by tgreway** [comment]
This would be great - I have the same need for the ifindex.  

Not sure if this is the right place to ask this but I was not able to find a release schedule.  Do you know when we can expect this in an official build on cpan?

**Comment by ollyg** [comment]
Hi @tgreway there isn't a published release schedule. Right now I hope we can do one in a few days because there are a few bugs to fix and then some major changes for a later release.  Sorry not to be more specific than that.

**Comment by rc9000** [comment]
@tgreway it's now released in https://github.com/netdisco/netdisco/releases/tag/2.040005

**Comment by tgreway** [comment]
@rc9000 & @ollyg thanks for the quick replies and getting this in so quick!  You guys are running a well oiled machine!
