### ISSUE TITLE
Inquiry/Enhancement:When will LDAPS be supported?

### ISSUE THREAD

**Issue by WillieStevenson** [netdisco/netdisco#511]
Does this project have a chance at seeing ldaps support?

**Comment by dgeo** [comment]
Le 21 février 2019 05:20:05 GMT+01:00, Willie Stevenson <notifications@github.com> a écrit :
>Does this project have a chance at seeing ldaps support?

Here we use nginx or apache with ldaps auth (and netdisco's internal for authz).

My 2cts...

-- 
geoffroy desvernay (mobile)

**Comment by rc9000** [comment]
This was also a recent topic on the mailing list: https://sourceforge.net/p/netdisco/mailman/message/36540615/

Summary: start_tls is, ldaps isn't at the moment. But if people keep asking maybe someone will come along and contribute it :)

**Comment by inphobia** [comment]
yup, bottom line: if you use active directory, ldap + tls should work.

adding ldaps should not be that much work since the underlying layers alrdy support it, but for me it's not in my focus atm.

other alternatives are a frontend proxy that supports ldaps auth like @dgeo mentioned.

**Comment by ollyg** [comment]
Hi @WillieStevenson, in addition to the replies above, I don't think we will find core dev time soon to implement different LDAP support. We welcome patches, or else I suggest START_TLS using the existing LDAP support is the best way to go. Many thanks,
