### ISSUE TITLE
reports->ip->ip inventory inconsistent results

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#514]
reports -> ip -> ip inventory is missing mac addresses for some ip's at random intervals. seems very similar to #274 

## Expected Behavior

show mac address if it's somehow known.

## Current Behavior

well, this one is curious, if you just press "search ips" or refresh the browser page with ctrl+f5 sometimes the mac addresses do show up.
using default settings: 1970-01-01 -> today timerange

i searched for 10.98.17.0/24 3 times, only paused to take the screenshots. i sorted on mac address so the missing addresses would show up on top.

in a span of 10 seconds it first returned 4 blank mac entries, then 2, then 3.

4 macs missing:
![image](https://user-images.githubusercontent.com/39005454/53308183-5f386e00-389f-11e9-9aae-070a47c1ee37.png)

2 macs missing:
![image](https://user-images.githubusercontent.com/39005454/53308185-6495b880-389f-11e9-837a-addb2fe9b031.png)

3 macs missing:
![image](https://user-images.githubusercontent.com/39005454/53308187-68293f80-389f-11e9-8a55-480780659aa8.png)

i did notice that ip's with no macs almost always are devices known in the database. for nodes it always seems to return the mac if it is known.

* it is not limited to 1 devicetype or operating system version. we see this on ios router, ios switches, cisco small business switches, aerohive access points, ...
* operating system versions are divers as well.
* we're also running snmp arpnip & netdisco-sshcollector (testserver is running the version @rc9000 is working on, production server uses the default one)

strangly enough the ip<->mac mapping is in node_ip, so i suspect this report is also sourcing data from other tables. i checked node_ip for 2 of the devices you saw in the screenshots above (10.98.17.200 & 201), they only have 1 entry for their ip & mac, and it's labeled active (so no archived data present)

*** side note: the expire job will completely remove all device entries in node_ip. when the next arpnip runs on the subnet they will be added again.

the mac address stored in node_ip is not present in node, but that makes sense since devices don't have a node entry. since no entry is present in node the expire job will delete 

i also verified that nothing was updating the database at the time i tested:
 * ran discoverall, macwalk & arpwalk - waited for them to complete
 * deleted jobs via webinterface to make sure nothing was stuck
 * shut down & restarted netdisco
 * waited for devices with snmp failures to get deferred again (since after a restart the get another try)

## Possible Solution

as noted in #274 , limiting the timeframe seems to lessen the variations.

## Steps to Reproduce (for bugs)

1. go to ip inventory report
2. search for a range that has devices in them
3. click search a couple of times, notice mac addresses appearing & disappearing

## Your Environment

* Netdisco version used: 2.40.3
* SNMP::Info version used: 3.65

```
relevant settings:
expire_jobs: 5
expire_nodes: 90
expire_nodes_archive: 90

nbtstat_no: "any"

schedule:
  discoverall:
    when: '5 3,7,11,15,19,23 * * *'
  macwalk:
    when:
      min: 55
      hour: '*/4'
  arpwalk:
    when:
      min: 5
      hour: '*/4'
  nbtwalk: null
  expire:
    when: '30 23 * * *'
```

**Comment by inphobia** [comment]
after running some more tests it seems that when no mac address is returned the last_used entry the timestamp of the last discover on the device linked to the ip:
![image](https://user-images.githubusercontent.com/39005454/53311506-784a1a80-38b1-11e9-84be-02a4a874063d.png)

when a mac address is returned the last_used timestamp is the date of the last arpnip for the subnet:
![image](https://user-images.githubusercontent.com/39005454/53311467-55b80180-38b1-11e9-8e71-81b2433e8672.png)

so i guess 2 questions:
 1. why is the result being returned seemingly random?
 2. why is sometimes no mac returned? for the device in this example everything is known in the database.



* node_ip (searched for ip, output not filtered. searching for mac returns the exact same result)

| mac               | ip         | active | time_first                 | time_last                 | dns  |
|-------------------|------------|--------|----------------------------|---------------------------|------|
| 70:79:b3:0a:02:c8 | 10.98.17.1 | True   | 2019-02-25 03:36:06.355547 | 2019-02-25 04:06:29.52628 | NULL |

* device_ip (searched for ip, output not filtered)

| ip         | alias         | subnet           | port                  | dns  | creation                   |
|------------|---------------|------------------|-----------------------|------|----------------------------|
| 10.98.17.1 | 172.22.174.54 | 172.22.174.52/30 | GigabitEthernet8.999  | NULL | 2019-02-25 03:08:28.016776 |
| 10.98.17.1 | 10.91.75.1    | 10.91.75.0/24    | Vlan1                 | NULL | 2019-02-25 03:08:28.016776 |
| 10.98.17.1 | 172.25.193.55 | 172.25.193.55/32 | Loopback0             | NULL | 2019-02-25 03:08:28.016776 |
| 10.98.17.1 | 10.98.17.1    | 10.98.17.0/24    | Vlan2                 | NULL | 2019-02-25 03:08:28.016776 |
| 10.98.17.1 | 10.57.97.197  | 10.57.64.0/18    | GigabitEthernet8.4090 | NULL | 2019-02-25 03:08:28.016776 |
| 10.98.17.1 | 30.30.30.1    | 30.30.30.0/30    | Vlan2                 | NULL | 2019-02-25 03:08:28.016776 |

* device_port (searched on ip && mac)

| ip         | port  | creation                   | descr | up | type        | speed    | name | mac               | vlan | pvid | lastchange |
|------------|-------|----------------------------|-------|----|-------------|----------|------|-------------------|------|------|------------|
| 10.98.17.1 | Vlan2 | 2019-02-25 03:08:28.294879 | Vlan2 | up | propVirtual | 1.0 Gbps | Vl2  | 70:79:b3:0a:02:c8 | 2    | 2    | 8271       |
| 10.98.17.1 | Vlan1 | 2019-02-25 03:08:28.294879 | Vlan1 | up | propVirtual | 1.0 Gbps | Vl1  | 70:79:b3:0a:02:c8 | 1    | 1    | 8270       |

**Comment by inphobia** [comment]
i did notice that the timestamps have changed since a few versions, where it used to be precise to the second `2019-02-25 03:08:28` i'm now seeing highres time information 2019-02-25 `03:08:28.016776`.

ResultSet/Device.pm & & Report/IpInventory.pm have explicit time references to the "00:00:00" format, perhaps that might not expect highres timestamp? i have no idea what the rest of the stack expects. or perhaps the use of date_trunc might be interfering.

is there a way to just run this report standalone somehow with sql tracing active?

**Comment by inphobia** [comment]
so the actual query generated by this report is this according to dbic trace (did use another ip range and ran at a later date)

```sql
SELECT me.ip, me.mac, me.time_first, me.time_last, me.dns, me.active, me.node, me.age
  FROM (
    SELECT DISTINCT
        ON ( ip ) ip, me.mac, me.dns, date_trunc( 'second', time_last ) AS time_last, date_trunc( 'second', time_first ) AS time_first, me.active, me.node, me.age
      FROM ( (
            SELECT me.alias AS ip, NULL::macaddr AS mac, me.creation AS time_first, device.last_discover AS time_last, me.dns, true AS active, false AS node, replace( date_trunc( 'minute', age( now(  ), device.last_discover ) ) ::text, 'mon', 'month' ) AS age
              FROM device_ip me
              JOIN device device
                ON device.ip = me.ip
           ) UNION
        SELECT me.ip, me.mac, me.time_first, me.time_last, me.dns, me.active, true AS node, replace( date_trunc( 'minute', age( now(  ), time_last ) ) ::text, 'mon', 'month' ) AS age
          FROM node_ip me UNION
        SELECT me.ip, me.mac, me.time_first, me.time_last, me.nbname AS dns, me.active, true AS node, replace( date_trunc( 'minute', age( now(  ), time_last ) ) ::text, 'mon', 'month' ) AS age
          FROM node_nbt me ) me
    WHERE ip << '10.6.10.0/16'
    ORDER BY ip ASC, active DESC
   ) me
WHERE ( time_first IS NULL AND time_last IS NULL ) OR ( time_last >= '1970-01-01 00:00:00' AND time_last <= '2019-02-25 23:59:59' )
ORDER BY age DESC, ip ASC
  LIMIT '2048'
```

according to https://www.postgresql.org/docs/10/sql-select.html , the "DISTINCT Clause" part:

> Note that the “first row” of each set is unpredictable unless ORDER BY is used to ensure that the desired row appears first.

(i'm running on postgres 10.6)

didn't find a way to add line numbers with markdown, but the 5th last line: `ORDER BY ip ASC, active DESC` is what seems to govern the DISTINCT clause.

now, since devices can show up in both the device table & the node_ip table, this ORDER BY is not sufficient to return 1 line only.

i think the order should be:
- ip ASC
- active DESC
- node ASC (-> prefer devices over nodes)

i ran my tests with the postgres client, but order seems be defined here? https://github.com/netdisco/netdisco/blob/c2600ac550fb8311818f439a7e527017605f7124/lib/App/Netdisco/Web/Plugin/Report/IpInventory.pm#L113

so this seems to fix the randomness by **prefering device entries over node entries.** (see #517)

this leads to the question, what do we do if the node_ip table knows a mac address but device does not. do we prefer an arp entry we have in node_ip or leave it blank like device reports?


next on the list: investigate why device doesnt return a mac.

**Comment by inphobia** [comment]
@ollyg (or anyone else who speaks dbic/dbix)

so the reason why device doesn't return a mac is because, as far as i can tell, we don't include the right table.
**device_ip** has **ip, alias & port** keys, but not a mac address. for the mac address you need to go to **device_port** and and select on device_ip.ip + device_ip.port to get the mac entry from device_port.mac

https://github.com/netdisco/netdisco/blob/c2600ac550fb8311818f439a7e527017605f7124/lib/App/Netdisco/DB/Result/DevicePort.pm#L400-L402

and

https://github.com/netdisco/netdisco/blob/c2600ac550fb8311818f439a7e527017605f7124/lib/App/Netdisco/DB/Result/DeviceIp.pm#L47-L50

this seems to be the data we need, but i still need to get up to speed on the whole dbic/dbix thing.


even if all this is added, device_port.mac can be NULL. so the question if we prefer no mac address over a node_ip mac address will still be relevant in the end. i'm kinda leaning to a third option: if device returns no mac, but node_ip does, show the node_ip mac but somehow indicate in the output it might not be correct (like the "possible uplink" for ports).

**Comment by ollyg** [comment]
This is awesome work, thank you! 🎉

**Comment by ollyg** [comment]
Well, probably best not to include "possibly not correct" data. Perhaps instead, when there's no MAC entry for an IP, the web render can fall back to something like "on device foo.example.com" which at least indicates where to go to investigate further.

**Comment by inphobia** [comment]
> Well, probably best not to include "possibly not correct" data. Perhaps instead, when there's no MAC entry for an IP, the web render can fall back to something like "on device foo.example.com" which at least indicates where to go to investigate further.

well, after thinking about it some more, if the device is known getting it from device_ip + device_port only makes sense i guess, without any fallback.

there will be one (perhaps major) drawback, since we don't save virtual ip's if they have hsrp, vrrp or other special mac addresses they are not saved. i also don't see, with the current db layout, where they would be saved, since device_port has a primary key on device & port, making duplicate mac addresses for a device/port combo impossible.

perhaps device_ip needs to be extended with the mac addresses. this might have as extra benefit that if  for some reason you have different mac entries for some reason on 1 interface or spoof arp replies for an ip, we'll still have all the info. hsrp/vrrp/other virtual stuff could be saved in there too.

**Comment by JeroenvIS** [comment]
device_port currently stores 1 MAC per port, just like device_ip stores one IP per device ("root" IP).

Perhaps it's an idea to create a device_port_alias where we could store additional port MACs, such as the ones that the (logical) port listens to for FHRP like VRRP/HSRP etc? So basically similar to device_alias table.

**Comment by inphobia** [comment]
excellent question. as someone once said to me, don't try to solve 2 issues at once :)

while both have their merit i'm mostly looking for ip<->mac mapping for devices (not nodes). extending device_ip seems the logical choice at first glance, since a mac can have multiple ip's, but an ip can't be attached to multiple macs (well, unless you're running overlapping vrf ip spaces. perhaps cisco nexus in data center interconnect with fhrp could qualify too).
need to check if there is some way to figure out which interfaces are being used by fhrp stuff, but in my experience most of them don't have the primary ip active on multiple nodes.

the multiple mac thing i do see being a major part of getting a start at complex stuff like mapping link bundles over multiple devices, be they vpc, mlag or whatver.

(side note: i might have screwed something up badly, but my device_ip stores all ip addresses for each device in the "alias" column. since i'm also not finding a device_alias table that might be quite possible.)

**Comment by ollyg** [comment]
inconsistency fixed in:
[master 77decc23] #514 inconsistent results in ip inventory (inphobia)

(if you want to also fix the lack of MAC for a device's IP, then I think open a different ticket. maybe the solution is a synthesized node entry for the device, somewhat like we also do for the device_ip entry for the discovered IP)

**Comment by JeroenvIS** [comment]
(sorry for the confusion that I caused when suddenly introducing a device_alias table - that should have read device_ip)

> while both have their merit i'm mostly looking for ip<->mac mapping for devices (not nodes). extending device_ip seems the logical choice at first glance, since a mac can have multiple ip's, but an ip can't be attached to multiple macs (well, unless you're running overlapping vrf ip spaces. perhaps cisco nexus in data center interconnect with fhrp could qualify too).

I understand that you're looking for MACs that devices consider "local" to themselves, ie MACs that if addressed, the device will pass packets to the next layer of its IP stack (eg for routing or because the device is the final destination).

While device_ip already holds port name, I'm not sure whether that's the best place to add additional MACs as well... but on the other hand, I can't explain why I would prefer one approach over another, in this case.

So maybe you should just go ahead with the change for multiple device MACs in #524 then, and we'll see later on if device_ip was a good choice or not.

> need to check if there is some way to figure out which interfaces are being used by fhrp stuff, but in my experience most of them don't have the primary ip active on multiple nodes.

GLBP can, iirc, but I don't have any experience with that. We're running HSRP and in some cases VRRP in our network, which are always active/standby (unless the peers don't see each other, but then you have a split-brain type of scenario in the network).

> the multiple mac thing i do see being a major part of getting a start at complex stuff like mapping link bundles over multiple devices, be they vpc, mlag or whatver.

I'm not sure how this change will help with MLAG type constructs, but we'll see :)
