### ISSUE TITLE
DB schema update troubles going from 2.032007 to 2.040003

### ISSUE THREAD

**Issue by nycalex** [netdisco/netdisco#518]
Hi, We just attempted to upgrade our netdisco, and experienced a bunch of DB errors. 
We were able to bring up both front end and backend after, but to be safe we rolled back the upgrade using vmware snapshot which we've created prior to upgrade. So before trying to upgrade again, i hope someone can help me make sense of what happened.

For additional context, netdisco is installed in /home/netdisco/ so i had to modify the provided commands to be like this: 

**Original command:** ~/bin/localenv cpanm --notest App::Netdisco
**Command I ran:** perl5/bin/localenv cpanm --notest App::Netdisco

**Original command:** ln -sf ~/perl5/bin/{localenv,netdisco-*} ~/bin/
**Command I ran:** ln -sf perl5/bin/{localenv,netdisco-*} perl5/bin/

**Original command:** ~/bin/netdisco-deploy
**Command I ran:** perl5/bin/netdisco-deploy

## Expected Behavior
Happy database upgrade without any errors

## Current Behavior
Below is the output of the upgrade.

So, is all the above in place? [y/N]: y

Would you like to deploy the database schema? [y/N]: y
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 85
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL:  Ident authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1517. at /home/netdisco/perl5/bin/netdisco-db-deploy line 106 at /home/netdisco/perl5/bin/netdisco-db-deploy line 106
DB schema update complete.
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 85
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL:  Ident authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1517. at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Statistics.pm line 77
Updating statistics... 
[root@netdisco01 netdisco]# 
[root@netdisco01 netdisco]# 

## Context
Unsure how to estimate the impact of the problem. GUI seems to work but being cautious, we rolled back the upgrade.

## Your Environment
Linux version 2.6.32-504.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Wed Oct 15 04:27:16 UTC 2014
* Netdisco version used: 2.032007

**Comment by ollyg** [comment]
Hi @nycalex it looks like your netdisco-deploy lost the ability to read the deployment.yml file, or was reading the wrong instance. You can see this in the line:

> authentication failed for user "changeme"

And I guess changeme isn't your DB password! The rest of the noise comes from that problem - the script cannot connect to the database (so it was probably not upgraded at all).

If you're running in a location other than /home/netdisco, be sure to set NETDISCO_HOME before starting any script or app. Also you should use /home/netdisco/bin and not the perl5 directory.

Hope this helps - I leave it with you to see if you can fix the file access.

**Comment by ollyg** [comment]
Do reopen the ticket if you are still stuck. Forgot to say that, sorry.

**Comment by inphobia** [comment]
> **Original command:** ~/bin/localenv cpanm --notest App::Netdisco
> **Command I ran:** perl5/bin/localenv cpanm --notest App::Netdisco
> 
> **Original command:** ln -sf ~/perl5/bin/{localenv,netdisco-_} ~/bin/ **Command I ran:** ln -sf perl5/bin/{localenv,netdisco-_} perl5/bin/
> 
> **Original command:** ~/bin/netdisco-deploy
> **Command I ran:** perl5/bin/netdisco-deploy

this seems vey wrong, all in all i think your netdisco install is borked with regards to where the binaries are.

save your deployment.yml & backup your database, the erase it all & start from scratch, preferably in a subdir of /home

**Comment by inphobia** [comment]
also don't forget to read the release notes page which documents breaking changes & other attention points.
https://github.com/netdisco/netdisco/wiki/Release-Notes#2-032000
