### ISSUE TITLE
TypeAhead.pm can reference empty data

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#522]
`Use of uninitialized value in sprintf at /home/netdisco/perl5/lib/perl5/App/Netdisco/Web/TypeAhead.pm line 52.`

https://github.com/netdisco/netdisco/blob/3f211650b89e58c80d862632faf6c9529c6f8b27/lib/App/Netdisco/Web/TypeAhead.pm#L51-L54

name can be NULL in the db:
https://github.com/netdisco/netdisco/blob/3f211650b89e58c80d862632faf6c9529c6f8b27/lib/App/Netdisco/DB/Result/DevicePort.pm#L42-L43

and for some devices it is. we see this on citrix netscalers, 2 cisco ios routers, but easiest of all to replicate:
pseudo devices.

## Possible Solution

either:
- set a default in the database (either empty string or copy of port field)
- make sure no null values get into the database
- fix typeahead.pm to deal with null names

## Your Environment

* Netdisco version used: HEAD
* SNMP::Info version used: 3.65

**Comment by ollyg** [comment]
thanks, fixed in:
[master d4c7579c] #522 TypeAhead.pm can reference empty data (inphobia)
