### ISSUE TITLE
ipinventory misses mac address for device ips

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#524]
inconsistency fixed in:
[master 77decc23] #514 inconsistent results in ip inventory (inphobia)

(if you want to also fix the lack of MAC for a device's IP, then I think open a different ticket. maybe the solution is a synthesized node entry for the device, somewhat like we also do for the device_ip entry for the discovered IP)

_Originally posted by @ollyg in https://github.com/netdisco/netdisco/issues/514#issuecomment-468927543_

**Comment by inphobia** [comment]
a bit of back info here:
https://github.com/netdisco/netdisco/issues/514#issuecomment-468591281

also, fhrp -> first hop redundancy protocol (stuff like vrrp, hrsp...)

so, ipinventory does not show mac entries for device ports. this is because device_ip does not contain mac (actually, arp entries, in theory one can use other l2 resolution methods as well) entries. the mac entry is contained in device_port.

i'll just use mac as a catchall term in this post for both mac & arp to not make it confusing.

i see a few solutions:
1. extend device_ip with the mac entry
2. pull in device_port in the query
3. create a new table device_port_alias

they all have their catches, these are what i came up with:

#### extend device_ip with the mac entry
- pro
  - 1 ip per mac (not allowed to have more)
  - like node_ip, easy to query
  - allows us to store fhrp (hsrp, vrrp, whatever, ...) macs.
- con
  - (need to extend database)
  - is mostly redundant data, except for the fhrp case
  - only covers ipinventory use case

#### pull in device_port in the query
- pro
  - most of the data is already there
- con
  - can become complex query or need to make a dbix result thingy for it (at the point where i know what dbix can do but not how it does it :) )
  - doesn't cover fhrp

#### create a new table device_port_alias
suggestion from @JeroenvIS in #514 , perhaps that's also what @ollyg was refering to in the last comment.
- pro
  - no duality between definitions of mac & arp, mac == hardware attached.
  - should not be to hard to alias fhrp addresses on this, without netdisco ignoring them
  - opens options for other features, like mapping virtual portchannels (vpc, amap, etc) across devices.
- con
  - even more complex query: device_ip (ip,portname), device_port(portname, mac), device_port_alias(mac, aliases)
  - not the place to store mac (well, arp) entries, device_ip has a mapping to portname


i seem to prefer extending device_ip, it already handles aliases, and ip->mac lookups should not return more as 1 mac. it also is more logical taken into account what defines an arp entry vs a mac entry.

i have however not taken the full extend of functions/usages into account, like how it interacts with searches in the webinterface (mac, ip, etc...)

**Comment by JeroenvIS** [comment]
Meh, sorry, I should have replied here and not in the previous ticket...

**Comment by JeroenvIS** [comment]
Perhaps indeed extending device_ip with a mac entry is the best way to start. However, I don't agree with the limitation of "1 ip per mac (not allowed to have more)". It's perfectly legal to have secondary IPs on interfaces, which will have the same MAC. And dual-stack interfaces (IPv4 and IPv6) will also have the same MAC for both protocol families.

Also, don't make the mac address a required field - you probably won't get a MAC for eg loopback interfaces, tunnel interfaces and other interfaces which don't use Ethernet encapsulation.

**Comment by inphobia** [comment]
> Perhaps indeed extending device_ip with a mac entry is the best way to start. However, I don't agree with the limitation of "1 ip per mac (not allowed to have more)". It's perfectly legal to have secondary IPs on interfaces, which will have the same MAC. And dual-stack interfaces (IPv4 and IPv6) will also have the same MAC for both protocol families.

hm, should have been "1 mac per ip" ofcourse, with perhaps the exception of glbp as you mentioned in #514.
but perhaps even then we can have device_ip aliases with ip, alias & mac different per device (so the db structure would suffice). the web output however will need work in that case.

> Also, don't make the mac address a required field - you probably won't get a MAC for eg loopback interfaces, tunnel interfaces and other interfaces which don't use Ethernet encapsulation

wasn't planning on that, for at least the reason that layer3 forwarding doesn't mandate macs.

vrrp/hsrp support is harder as expected, since none of the currently used snmp oid's have a fhrp<->mac mapping, so this will require a bit of snmp::info work first. 

finally, wrt mlag (mentioned in #514)
> I'm not sure how this change will help with MLAG type constructs, but we'll see :)
i assumed it used "virtual" macs like vpc, but since arista never even bother to respond to our quote request.... (i have no experience with other multi chassis like link aggregation options).

**Comment by ollyg** [comment]
The data is already there, I realised, by joining device_ip to device_port, which has the MACs.

[master 241ecf33] #524 ipinventory misses mac address for device ips
