### ISSUE TITLE
Discover All does not work any more.

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#526]
## Expected Behavior
Discover All starts a discover process where all devices are "discovered".

## Current Behavior
I get the following error:  error running job: Global symbol "$c_cap" requires explicit package name (did you forget to declare "my $c_cap"?) at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm line 172, <__ANONIO__> line 1.
Type of arg 1 to Try::Tiny::try must be block or sub {} (not reference constructor) at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm line 353, near "};"
Compilation failed in require at /usr/share/perl/5.24/Module/Load.pm line 77, <__ANONIO__> line 1.
Can't locate App/Netdisco/Worker/Plugin/Discover/Neighbors in @INC (@INC contains: /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /home/netdisco/perl5/lib /home/netdisco/perl5/bin/lib /home/netdisco/perl5/lib/perl5/5.24.1/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5/5.24.1 /home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl/5.24/Module/Load.pm line 77, <__ANONIO__> line 1.

## Your Environment
Software	Version
App::Netdisco	2.40.4
SNMP::Info	3.65
DB Schema	54
PostgreSQL	9.6.11
Perl	        5.24.1

**Comment by ollyg** [comment]
Sorry I thought the test suite covered that. Will fix very soon and let you
know.

**Comment by ollyg** [comment]
Fixed in:
[master 0c98318a] #526 fix discover syntax bug

And 2.040005 on its way to CPAN
