### ISSUE TITLE
unnamed vlans not added during discover

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#529]
see #528 

https://github.com/netdisco/netdisco/blob/48857ae3002536b469acb678292981377b960b65/lib/App/Netdisco/Worker/Plugin/Discover/VLANs.pm#L74

unnamed vlans (for how i interpret "unnamed vlan") aren't added to device_vlan & device_port_vlan.

when projected on #528, vlan 999 does not show up in device->vlan webpage. also searching for vlan 999 in the web interface yields no results.

## Possible Solution
#501 had a flawed solution (it also fixes stuff which wasn't broken).

i think the key for both this & #528 is using i_vlan instead of i_vlan_membership as the key in 
https://github.com/netdisco/netdisco/blob/48857ae3002536b469acb678292981377b960b65/lib/App/Netdisco/Worker/Plugin/Discover/VLANs.pm#L47

## Context

intertwined with #528 (and perhaps a solution for it).

## root cause
https://github.com/netdisco/netdisco/blob/48857ae3002536b469acb678292981377b960b65/lib/App/Netdisco/Worker/Plugin/Discover/VLANs.pm#L74

i_vlan_membership has no guarantee to also include i_vlan_membership_untagged.

join i_vlan_membership & i_vlan_membership_untagged?

## Your Environment

* Netdisco version used: 2.40.6
* SNMP::Info version used: 3.65

**Comment by ollyg** [comment]
thanks, this should be fixed in the refactor as part of #528:
[master a6e7943c] #528 record egress untagged vlans in device_port_vlan table

**Comment by inphobia** [comment]
seems even with b22c32a i'm still having duplicate key issues, but not on all devices:

```
[12917] 2019-04-01 21:56:01 debug  [10.40.72.251] vlans - removed 0 port VLANs
[12917] 2019-04-01 21:56:01 debug -> DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(): execute_for_fetch() aborted with 'ERROR:  duplicate key value violates unique constraint "device_port_vlan_pkey"
DETAIL:  Key (ip, port, vlan, native)=(10.40.72.251, Ethernet199/1/35, 1, t) already exists.' at populate slice:
{
  egress_tag => "f",
  ip => "10.40.72.251",
  last_discover => \"now()",
  native => "t",
  port => "Ethernet199/1/35",
  vlan => 1,
  vlantype => "static",
} at /home/testdisc/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/VLANs.pm line 84
[12917] 2019-04-01 21:56:01 debug bless( {'msg' => 'DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(): execute_for_fetch() aborted with \'ERROR:  duplicate key value violates unique constraint "device_port_vlan_pkey"
DETAIL:  Key (ip, port, vlan, native)=(10.40.72.251, Ethernet199/1/35, 1, t) already exists.\' at populate slice:
{
  egress_tag => "f",
  ip => "10.40.72.251",
  last_discover => \\"now()",
  native => "t",
  port => "Ethernet199/1/35",
  vlan => 1,
  vlantype => "static",
} at /home/testdisc/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/VLANs.pm line 84
'}, 'DBIx::Class::Exception' )
```

**Comment by ollyg** [comment]
@inphobia OK thanks for testing! I will take a look....
