### ISSUE TITLE
cant disable auto dsicovery

### ISSUE THREAD

**Issue by tpolim008** [netdisco/netdisco#531]
looking for a way to disable auto-discovery using LLDP, CDP, ISIS or bgp, we have a fairly large network that is divided into regions, I do not want to discover every region routers.. Since we use the same backbone its discovers everywhere. Creating an acl to block is not ideal al we use one container as well... Is there a way we can shut off LLDP/CDP discovery? IF so how can this be done, and how can I purge the current discovered list and start fresh without a new install.

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used:

**Comment by rc9000** [comment]
Hi 

I don't quite understand what you mean by "Creating an acl to block is not ideal al we use one container", maybe you can clarify?

Essentially, Netdisco allows you to either whitelist the devices you want using devices_only, or blacklist devices you don't want using the devices_no options. These are described here:

https://github.com/netdisco/netdisco/wiki/Configuration

To start over after setting these, run

    netdisco-do psql 

Then inside this database prompt

    delete from device;
    delete from admin;

**Comment by tpolim008** [comment]
Is it possible to shut off cdp/lldp node doscovery? Our network is very
large, few thousand routers. The loop back  space is shared in one class a.

I would have a large black list if I had to list every single router. It
would be much easier if there was a way to shut off lldp or cdp discovery
and only discover the nodes I wish manually

**Comment by tpolim008** [comment]
Or if auto discovery from said protocols can’t be turned off, can I
restrict the devices I discover by saying

Discover with host name begins with uer*

Do not discover where host names has
Ar, sur, sr, cr, rer, rur, er, eur,

**Comment by rc9000** [comment]
Unfortunately at discovery time, you can't filter on hostname as only the IP is known to Netdisco. But you could discover all devices (a job that happens typically once a day), and then use the macsuck_only/aprnip_only uer* ACL to run the more frequent jobs only on your desired devices.

Using only Netdisco built-in features, you have to decide whether building a blacklist or a whitelist is easier, and then stick it into devices_only or devices_no.

If you really want to disable CDP/LLDP peers and know some Perl, you could edit the source code around https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm#L47 to make it happen. 

Our team runs Netdisco in similar sized networks with  parts owned by other organizations. What we do is pull a very long list of IPs from our inventory, and then explicitly only give these to Netdisco using a script that outputs:

    devices_only:
        - 10.0.0.1
        - 10.0.0.4
        - 10.0.2.1
        ... # about 2000 more records

**Comment by tpolim008** [comment]
so where would I place the device_only in the config, I tried that and
seems that I either entered it wrong or in wrong place. Do you have to add
the - at the start of each host...

example
- host.host.com

**Comment by rc9000** [comment]
PS here's all the ACL options explained: https://github.com/netdisco/netdisco/wiki/Configuration#access-control-lists

**Comment by rc9000** [comment]
Note it's devices_only, you can place it anywhere in the config. The file is YAML which can be a bit tricky. Valid is either:

    devices_only:
      - x.x.x.x
      - x.x.x.y

or
    devices_only: [x.x.x.x, x.x.x.y]

Watch the indentation and use only one style all over the file (e.g. four spaces for one level of indent). I'm not a 100% if DNS hostnames work to limit discovery, try IPs maybe if it doesn't.

**Comment by tpolim008** [comment]
Last question, is there a way to do a bulk discovery, testing the hostname
list now and see if that works.

**Comment by ollyg** [comment]
Hi @tpolim008 thanks for the question! In addition to the good help from @rc9000 I can add that you can set an ACL for discovery using regular expressions to match DNS names.

So for example:

```
devices_no:
  - !!perl/regexp ^(?:ar|sur|sr|cr|rer|rur|er|eur)
```
or

```
devices_only:
  - !!perl/regexp ^uer
```
This is documented in:

- https://github.com/netdisco/netdisco/wiki/Configuration#devices_no
- https://github.com/netdisco/netdisco/wiki/Configuration#access-control-lists

**Comment by ollyg** [comment]
And you can do bulk discovery on IP prefixes, just pass the prefix (v4 or v6) instead of an IP. If you're at the command line you can use `--enqueue` to avoid waiting on all the discover jobs. Alternatively with a file of hostnames or non-contiguous IPs, then write a script using `netdisco-do` and `--enqueue` to enqueue them all.

Hope that helps. Let us know if you meant something else.

**Comment by tpolim008** [comment]
Thank you for both. So as to the script file as I’m new to this tool. Would
it be a perl script or a bad file.  I was doing the netdiscover all host
name in cli.

With the file would it just be netdisco-do followed by the file name and
location and —enqueue?

**Comment by rc9000** [comment]
You're welcome! You can do bulk discovery in bash just with some simple commands. Create a file with the IPs, one per line, named eg. devices.txt:

     $ cat devices.txt 
    10.0.0.1
    10.0.0.3
    10.0.5.9
    
Then you just run:

     $ for d in $(<devices.txt) ; do netdisco-do discover --enqueue -d $d ; done 

Might not even be necessary though, if all your devices are connected in a way Netdisco can understand, and you have configured the SNMP parameters for all of them, it will find the whole network just from the first device you discover. But if you get gaps the above can't hurt.


PS Thanks @ollyg I didn't know that perl/regexp ACL can be used like that, sweet!

**Comment by tpolim008** [comment]
Do know with the regexp if it can match on items in a FQDN such as
pa.pitt|md.pitt and so forth so it will only discover devices matching with
that exact string in the FQDN when an ip is resolved.

**Comment by ollyg** [comment]
Hi @tpolim008, yes it can match on the full name. You might want to read up a little on regular expressions but here are some tips: the "^" is the start of the complete text and the "$" is the end. So you can use these ("anchors") to match:

```
devices_only:
  - !!perl/regexp ^(?:pa|md)\.pitt$
  - !!perl/regexp ^(?:foo|bar)\.example\.com$
```
Hope that helps.

**Comment by tpolim008** [comment]
Hi Oliver

So I guess I'll return for more of a pain in the ass on this and sorry. I
read a bit and seeing that the ^ means at the start of an expression. which
this pa.pitt md.pitt and so forth is in the FQDN in the middle examples. I
tried to do a /pa.pitt/g and also /b but those don't seem to work. Is there
a site you can point me towards that might be useful in my learning as I'm just
getting into coding/ perl this is a whole new beast for me as I'm trying to
self learn. Something tells me the site im using to test this with
isn't going to be helpful as all the expressions I've tried that say they
work, don't.I guess what my issue is the use of anchors and where they
should be placed and how to use them.

uer01.site.pa.pitt.web.com
uer01.site.md.pitt.web.com
uer01.stite.oh.pitt.web.com

**Comment by ollyg** [comment]
Hi @tpolim008,
I recommend the site https://regexone.com/ for learning about regular expressions.
If you want to match something in the middle, just remove the anchors. Also the /b modifiers and so on will not work the same way within these expressions - they are for code, and not configuration. However you can simply use:

````
 - !!perl/regexp \.(?:pa|md)\.pitt\.
````

Hope this helps. I will close this ticket now, as I think you have the solution?

**Comment by tpolim008** [comment]
Thank you for all the help. Sorry I was huge pain on this one. It does make
better sense now as why my expressions I was trying didn’t work belated off
your explanation.

**Comment by ollyg** [comment]
No worries - we are all beginners at some time :-)
