### ISSUE TITLE
Discover All do not work anymore from 2.041001 

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#542]
## Expected Behavior
For some days netdisco is not scanning correctly the network, since version 2.041001 has been released

Even after sending a "Discover all" request. 

## Current Behavior
The discover process is stuck. The problem was discovered because the CPU usange from 2019-03-15 onwards was cut significantly .

All the workers's poll are in idle.

## Your Environment
App::Netdisco	2.42.0
SNMP::Info	3.65
DB Schema	56
PostgreSQL	9.6.11
Perl	                5.24.1

Thank you for your help.

**Comment by cromra** [comment]
I have the same problem here since i updated to last version. All actions seem stuck : discover, arpnip, macsuck...

App::Netdisco 	2.42.2
SNMP::Info 	3.65
DB Schema 	56
PostgreSQL 	9.6.11
Perl 	5.24.1

**Comment by ollyg** [comment]
Hi @def-bs and @cromra 
Unfortunately I can't reproduce this issue. Would you try the following:

```
bin/netdisco-backend stop
bin/netdisco-do psql -e 'delete from admin'
bin/netdisco-do discoverall
bin/netdisco-backend start
```

and see if you get some activity?

**Comment by def-bs** [comment]
I have ran the commands but nothig changed.

Netdisco is dead.. Discover not working

**Comment by ollyg** [comment]
OK in which case let's try a basic test:

```
bin/netdisco-backend stop
bin/netdisco-do discover -d 1.2.3.4 -D

```
Obviously substitute an IP for that example. See if there are errors or messages. If the error is that there are no credentials for the device, you can run:

`bin/netdisco-do dumpconfig -e device_auth -d 1.2.3.4
`
for the same IP.

**Comment by def-bs** [comment]
bin/netdisco-do discover -d 10.64.0.11 -D
[11349] 2019-03-21 14:43:12  info App::Netdisco version 2.042002 loaded.
[11349] 2019-03-21 14:43:12  info discover: [172.16.252.11] started at Thu Mar 21 15:43:12 2019
[11349] 2019-03-21 14:43:12 debug deferred job with no device creds
[11349] 2019-03-21 14:43:12  info discover: finished at Thu Mar 21 15:43:12 2019
[11349] 2019-03-21 14:43:12  info discover: status defer: deferred job with no device creds
netdisco@netdisco:~$ bin/netdisco-do discover -d 172.16.251.106 -D
[11355] 2019-03-21 14:43:59  info App::Netdisco version 2.042002 loaded.
[11355] 2019-03-21 14:44:00  info discover: [172.16.251.106] started at Thu Mar 21 15:44:00 2019
[11355] 2019-03-21 14:44:00 debug deferred job with no device creds
[11355] 2019-03-21 14:44:00  info discover: finished at Thu Mar 21 15:44:00 2019
[11355] 2019-03-21 14:44:00  info discover: status defer: deferred job with no device creds
netdisco@netdisco:~$

**Comment by ollyg** [comment]
OK thanks. The recent releases did change how some of the credentials are loaded and composed.

But you will need to help us with some digging to find out what is specific to your configuration which causes this - perhaps a particular combination of settings which was not anticipated.

I suggest you run the device_auth command I posted above, and sanitise the output, and use https://nopaste.xyz if you want to share.

You should also read the release notes and in particular the sshcollector deprecation notice if you are using sshcollector config.

I suggest adding and removing config items (sshcollector, snmp_auth, device_auth) and the stanza in them until it works and you can report where the error comes from. You might want to start with a minimal device_auth config and add stanza until it stops working.

(sshcollector and snmp_auth config should not be required nowadays)

**Comment by cromra** [comment]
same here, it comes from my very old configuration file i replaced snmp_auth with device_auth and everything works now

**Comment by ollyg** [comment]
OK thanks @cromra I'm glad it has been resolved for you. Waiting to hear from @def-bs.

**Comment by def-bs** [comment]
Ok now it is working.

I added this in  deployment.yml and I removed snmp_auth 

device_auth:
  - tag: 'default_v2_readonly'
    community: 'public'
    read: true
    write: false


Thank you. I belive it should be written in the documentation or in the Troubleshooting section to help other users that could have the same problem

**Comment by ollyg** [comment]
Yes @def-bs I agree. Sorry for the bother, I'm glad it's fixed for you!
