### ISSUE TITLE
Discover - undefined Symbol memdup

### ISSUE THREAD

**Issue by mikepiko** [netdisco/netdisco#543]
First installation on Debian 9. Want to start first discover but it´s running into Missing Symbols Errors.

## Expected Behavior

Discover Network

## Current Behavior

Error while starting discovery:
`netdisco@utopia:~$ netdisco-do discover -d 192.168.42.11
[8028] 2019-03-21 09:50:05  info App::Netdisco version 2.042002 loaded.
[8028] 2019-03-21 09:50:05  info discover: [192.168.42.11] started at Thu Mar 21 10:50:05 2019
[8028] 2019-03-21 09:50:05  info discover: finished at Thu Mar 21 10:50:05 2019
[8028] 2019-03-21 09:50:05  info discover: status error: error running job: Can't load '/home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/SNMP/SNMP.so' for module SNMP: /home/netdisco/perl5/lib/perl5/x86_64-linu          x-gnu-thread-multi/auto/SNMP/SNMP.so: undefined symbol: memdup at /usr/lib/x86_64-linux-gnu/perl/5.28/DynaLoader.pm line 187.
 at /home/netdisco/perl5/lib/perl5/SNMP/Info.pm line 16.
Compilation failed in require at /home/netdisco/perl5/lib/perl5/SNMP/Info.pm line 16.
BEGIN failed--compilation aborted at /home/netdisco/perl5/lib/perl5/SNMP/Info.pm line 16.
Compilation failed in require at /home/netdisco/perl5/lib/perl5/App/Netdisco/Transport/SNMP.pm line 10.
BEGIN failed--compilation aborted at /home/netdisco/perl5/lib/perl5/App/Netdisco/Transport/SNMP.pm line 10.
Compilation failed in require at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/CanonicalIP.pm line 7.
BEGIN failed--compilation aborted at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/CanonicalIP.pm line 7.
Compilation failed in require at /usr/local/share/perl/5.28.1/Module/Load.pm line 77.
Can't locate App/Netdisco/Worker/Plugin/Discover/CanonicalIP in @INC (@INC contains: /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /home/netdisco/perl5/lib /home/netdisco/perl5/bin/lib /home/netdisco/perl5/lib          /perl5/5.28.1/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5/5.28.1 /home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1           /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /home/netdisco/perl5/lib/perl5/5.28.0 /home/netdisco/perl5/lib/perl5/5.28.0/x86_64-lin          ux-gnu-thread-multi /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/share/perl/5.28.1/Module/Load.pm line 77.

`

## Your Environment

* Netdisco version used: 2.42.2
* SNMP::Info version used: 3.65
* libsnmp version used: 5.7.3+dfsg-5

**Comment by ollyg** [comment]
Hi @mikepiko must admit I've not seen this one before, but anything like symbol errors makes me think that there's a mismatch between compiled libraries and installed libraries somehow.

Also are you following the instructions to use /home/netdisco or trying another location?

Also can you confirm you installed Debian package net-snmp ? Ah, can you also try installing  libnet-snmp-perl ? (perhaps need to delete /home/netdisco/perl5 and do the "curl" step again).

Finally are you able to try on another OS than Debian 9?

Thanks

**Comment by ollyg** [comment]
(sorry I didn;t mean libnet-snmp-perl that is something else)

**Comment by mikepiko** [comment]
thanks for the reply !

removed everything in perl5 directory and reinstalled every snmp component again.
After that running new install with the curl cmd line and now it seems to work. 
No symbol error when running discover.
