### ISSUE TITLE
Log files grow big, worker processes turn zombie when supervisor hangs

### ISSUE THREAD

**Issue by macluka** [netdisco/netdisco#545]
I noticed that NetDisco sometimes doesn't die gracefully. When the main process dies (netdisco-backend, netdisco-web) the workers keep on writing to logs. If there is a problem for example in writing to DB, the logs can grow pretty fast, flooded with messages about inability to write to postgresql. Normally the main process should take care of log rotation, but I received a report that the netdisco-web log file grew up to 12 GB filling the log partition. The users removed the log file but ND kept creating new one and writing to. Killing a single process caused a new process respawn. Even stopping the main services netdisco-web, netdisco-backend didn't help. All processes of netdisco user had to be mas-killed to stop it.

ps aux of netdisco processes:
netdisco  9847  0.0  0.0 152616  5920 ?        S     2018  60:25 perl /var/netdisco/perl5/bin/netdisco-web start --port=7878
netdisco  9848  0.4  0.0 153552  6888 ?        S     2018 618:14  \_ starman master --disable-keepalive --user 501 --group 501 --port=7878 /var/netdisco/perl5/bin/netdisco-web-fg
netdisco 17709  7.0  0.0 176464 15492 ?        R    00:00   0:00      \_ /var/netdisco/perl5/bin/netdisco-web-fg
netdisco 17710  5.0  0.0 175144 14168 ?        R    00:00   0:00      \_ /var/netdisco/perl5/bin/netdisco-web-fg
netdisco 17711  0.0  0.0 171560 12604 ?        R    00:00   0:00      \_ /var/netdisco/perl5/bin/netdisco-web-fg
netdisco 17712  0.0  0.0 162936 10056 ?        R    00:00   0:00      \_ /var/netdisco/perl5/bin/netdisco-web-fg
netdisco 17717  0.0  0.0 163200 10356 ?        R    00:00   0:00      \_ /var/netdisco/perl5/bin/netdisco-web-fg
netdisco  9877  0.0  0.0 152616  6100 ?        S     2018  59:25 netdisco-backend
netdisco 22130  0.0  0.0      0     0 ?        Z    Mar12   0:00  \_ [perl] <defunct>

As you can see, backend was dead - no children, but the netdisco-web kept writing.

netdisco-web.log was filled first with:
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /var/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
Error while loading /var/netdisco/perl5/bin/netdisco-web-fg: DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','netdisco',...) failed: FATAL:  Ident authentication failed for user "net
disco" at /var/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1517. at /var/netdisco/perl5/lib/perl5/App/Netdisco/Web.pm line 70
Compilation failed in require at /var/netdisco/perl5/bin/netdisco-web-fg line 53.
BEGIN failed--compilation aborted at /var/netdisco/perl5/bin/netdisco-web-fg line 53.
Child process 24736 exited with status 255

 and then it turned into:
Error while loading /var/netdisco/perl5/bin/netdisco-web-fg: Unable to parse the configuration file: /var/netdisco/environments/deployment.yml: YAML::XS::Load Error: The problem:

    could not find expected ':'

was found at document: 1, line: 96, column: 1
while scanning a simple key at line: 95, column: 1
 at /var/netdisco/perl5/lib/perl5/Dancer/Config.pm line 234.
        Dancer::Config::load_settings_from_yaml("/var/netdisco/environments/deployment.yml", "YAML") called at /var/netdisco/perl5/lib/perl5/Dancer/Config.pm line 209
        Dancer::Config::load("Dancer::Config") called at /var/netdisco/perl5/lib/perl5/Dancer.pm line 274
...

I'm trying to reproduce the issue in lab environment, as reports from end-users lack information, but it did happened more than once, in different network setups on different servers. Can't confirm that in all cases the error messages were the same, but the symptoms were very alike, with netdisco-web growing huge.

Is there a way to change ND behavior to have main processes and all it's children die gracefully (or sleep for configured period of time) whenever system error is reported (i.e but not limited to: unable to communicate with DB).

## Expected Behavior
The worker process should write to log file that it's unable to communicate with DB and die. The supervisors should die or go sleep (configurable), when critical error (like DB connection issue) is reported by workers, instead of forking new processes which repeat the above.

## Current Behavior
Currently the worker processes keep forking and flooding the log file about inability to communicate with DB.

## Steps to Reproduce (for bugs)

It's hard to provide the steps as it happened quite randomly, and the little info above comes from a single occurrence but similar symptoms were experienced on a few other setups, in each case ND wasn't relatively new, has been running fine for 2+ months with no issues noticed.
## Your Environment

* Netdisco version used: 2.0.390033
* SNMP::Info version used: 3.61
* DB Schema 53
* PostgreSQL 8.4.20
* Perl 5.10.1
--

**Comment by ollyg** [comment]
Hi @macluka I think the quiet response is just because we are thinking about it! Tricky one...

**Comment by ollyg** [comment]
I'm going to close this ticket as I really can't see a good fix which doesn't have unwelcome side effects. It's not unusual for a database to go away and come back, and I wouldn't want the daemons dying like that (we'd just get similar tickets about the daemon silently stopping). I think putting some system monitoring on the postgresql server might be a good approach.

the ticket can be reopened and is still searchable of course, if anyone else reports the same issue
