### ISSUE TITLE
isis neighbor discovery?

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#546]
do we need is-is handling in neighbor discovery?

https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Discover/Neighbors/Routed.pm

netdisco/snmp-info#316 - @pyro3d 

## Your Environment

* Netdisco version used: HEAD
* SNMP::Info version used: HEAD

**Comment by ollyg** [comment]
Hi, I suggested to @pyro3d that a PR be created for this so that Netdisco release isn't blocked on SNMP::Info release.

**Comment by inphobia** [comment]
excellent point. not that we use is-is, but it seemed like a logical step to add discovery if the required info is available.

**Comment by zoeloe** [comment]
We have a mixed avaya/extreme ospf/isis network fo now, switching to full isis in the future. So that would be a welcome feature !.  Would be happy to test stuff ! Great work !.

**Comment by zoeloe** [comment]
Is this feature already supported/integrated in netdisco version  2.042003 ?
I installed SNMP::Info version 3.66 explicitly with "~/bin/localenv cpanm --notest SNMP::Info"
How does one distinguish the discovered "neigbours" if they are seen by OSPF or IS-IS ?
TIA

**Comment by ollyg** [comment]
Hi, we need to release a new Netdisco to go with the new SNMP::Info release.

Hope to do that today...

**Comment by inphobia** [comment]
and done 😃
