### ISSUE TITLE
manual topology after device replacement

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#549]
we noticed that manual topology sometimes becomes inconsistent after a device is replaced. the topology table can point to non existent interfaces.

## Expected Behavior

If devices get replaced (or interfaces deleted) manual topology should be checked to see if the data is still consistent, as to avoid links to non existing interfaces.

## Current Behavior

after replacing a router which had manual topology defined we now have a link to a non existing interface.

note: the device on the other end of the manual topology is a netdisco pseudo device.

## Possible Solution

manual topology should be checked for consistency after interface changes. Plugin::Discover::Neighbors seems to try and do this, so my hunch is that using a pseudo device might be part of the cause since they don't run discover (or most workers for that matter) so they might miss out on a lot of consistency checks...

## Steps to Reproduce (for bugs)

1. create a manual topology between 2 devices 
   - the manual topology was created between a cisco router, interface GigabitEthernet0/1.999 ip 10.98.101.1
   - the second device was a netdisco pseudo device, interface Port101 ip 169.254.255.2
2. replace the router, making sure the that the interface no longer exists but keep the same ip address
   - so in this case the new device can't have an interface named GigabitEthernet0/1.999
   - we actually replaced the cisco with a oneaccess router in this instance.
3. notice:
   - that in the network map a link still remains between both devices
   - when checking the pseudo device Port101 it still mentions it's linked, even if the interface on the second device no longer exist
   - when looking at the replaced router, notice you can't see any link to the pseudo device

verify database content:
```
netdisco-do psql -e "SELECT * FROM public.topology WHERE dev1 = '10.98.101.1';"
    dev1     |         port1          |     dev2      |  port2
-------------+------------------------+---------------+---------
 10.98.101.1 | GigabitEthernet0/1.999 | 169.254.255.2 | Port101
```

```
netdisco-do psql -e "SELECT ip, port, creation, up, remote_ip, remote_port, remote_type, remote_id, lastchange, manual_topo FROM public.device_port WHERE ip = '169.254.255.2'  AND port = 'Port101';"
      ip       |  port   |          creation          | up |  remote_ip  |      remote_port       | remote_type | remote_id | lastchange | manual_topo
---------------+---------+----------------------------+----+-------------+------------------------+-------------+-----------+------------+-------------
 169.254.255.2 | Port101 | 2018-12-12 14:03:57.315567 |    | 10.98.101.1 | GigabitEthernet0/1.999 |             |           |            | t
(1 row)
```

```
netdisco-do psql -e "SELECT ip, port, creation, up, remote_ip, remote_port, remote_type, remote_id, lastchange, manual_topo FROM public.device_port WHERE ip = '10.98.101.1'  AND port = 'GigabitEthernet0/1.999';"
 ip | port | creation | up | remote_ip | remote_port | remote_type | remote_id | lastchange | manual_topo
----+------+----------+----+-----------+-------------+-------------+-----------+------------+-------------
(0 rows)
```

```
netdisco-do psql -e "SELECT ip, port, descr, manual_topo FROM public.device_port WHERE ip = '10.98.101.1';"
     ip      |          port           |          descr          | manual_topo
-------------+-------------------------+-------------------------+-------------
 10.98.101.1 | Bvi3                    | Bvi3                    | f
 10.98.101.1 | GigabitEthernet1/0.4090 | GigabitEthernet1/0.4090 | f
 10.98.101.1 | Loopback0               | Loopback0               | f
 10.98.101.1 | GigabitEthernet0/2      | GigabitEthernet0/2      | f
 10.98.101.1 | GigabitEthernet2/0      | GigabitEthernet2/0      | f
 10.98.101.1 | GigabitEthernet0/3      | GigabitEthernet0/3      | f
 10.98.101.1 | GigabitEthernet1/0      | GigabitEthernet1/0      | f
 10.98.101.1 | GigabitEthernet1/0.999  | GigabitEthernet1/0.999  | f
 10.98.101.1 | GigabitEthernet2/0.4090 | GigabitEthernet2/0.4090 | f
 10.98.101.1 | GigabitEthernet0/1      | GigabitEthernet0/1      | f
 10.98.101.1 | GigabitEthernet0/0      | GigabitEthernet0/0      | t
(11 rows)

```

## Context

we are using a pseudo devices and manual topology quite a bit to work around how our mpls setup works. while we have snmp read access on all on-prem routers we're limited to a a few vrf's.  as such we use pseudo devices to represent the mpls cloud.

## Your Environment

* Netdisco version used: 2.42.3
* SNMP::Info version used: 3.66

**Comment by ollyg** [comment]
Hi, thanks for the report. It seems very likely this isn't yet handled in the device rediscover code (an interface used in manual topology going away). I don't think it has much to do with the pseudo device, as the actions/changes are all at the non-pseudo device end.

Anyway, the thing I'd need to know is: what would we like to happen instead of the current behaviour? For example:

- bomb out (hard die) on device discover if the interface goes away (probably not desirable!)
- pick a random new port to attach to (probably not desirable!)
- delete the manual topology row
- current behaviour but better signalling of the situation in the user interface

As this happens at discover time, which is automated, stopping to ask the user is not an option.

Either of the last two options seems fine. Obviously deleting the topology is easiest to implement. Notification in the UI can be done but it would help to have specific requirement e.g. a screenshot and "HERE is where it should alert to the broken topology".

Thanks,

**Comment by inphobia** [comment]
actually, i'm in favor of just deleting the topo row if the data is known to be bad and perhaps make a note of it in the web or backend log.

another option is to add a column to the manual topo webpage to indicate if a topology is broken, or a report -> port -> broken topo.

as for the signalling thing, something like the job queue web notifications could be an option for this, but i've turned them off. when doing a discoverall on 1000+ devices it just a neverending stream of messages 😈 

in the long run i do see having some kind of log in the webinterface as a welcome addition, somewhere where warnings we send to the now can go to instead or as well. things like when a device changes serial, uptime resets, interface count changes, etc.... can be reviewed. perhaps a bit like #445 .

**Comment by ollyg** [comment]
thanks! fixed in:
[master 8c974fd2] #549 clean manual topology after device ports change

**Comment by inphobia** [comment]
not yet tested on my production setup, but still seems to leave entries in the topology table with pseudodevices.

steps taken:
1. create pseudodev with 15 ports
1. link pseudodev port 2 with a port on any other device
1. change pseudodev to have only 1 port
1. run discoverall
1. topology for non present port stays

```
netdisco-do psql -e "COPY (SELECT * FROM public.topology) TO STDOUT WITH CSV HEADER"
[2723] 2019-04-03 20:55:16  info App::Netdisco version 2.042005 loaded.
[2723] 2019-04-03 20:55:16  info psql:  started at Wed Apr  3 22:55:16 2019
dev1,port1,dev2,port2
169.254.8.8,Port2,10.40.254.35,1/5
[2723] 2019-04-03 20:55:16  info psql: finished at Wed Apr  3 22:55:16 2019
[2723] 2019-04-03 20:55:16  info psql: status done: psql session closed.
```

```
netdisco-do psql -e "COPY (SELECT * FROM public.device_port where ip = '169.254.8.8' ) TO STDOUT WITH CSV HEADER"
[2734] 2019-04-03 20:56:15  info App::Netdisco version 2.042005 loaded.
[2734] 2019-04-03 20:56:15  info psql:  started at Wed Apr  3 22:56:15 2019
ip,port,creation,descr,up,up_admin,type,duplex,duplex_admin,speed,name,mac,mtu,stp,remote_ip,remote_port,remote_type,remote_id,vlan,pvid,lastchange,manual_topo,is_uplink,slave_of,is_master
169.254.8.8,Port1,2019-04-03 17:48:27.289865,,,,other,,,,,,,,,,,,,,,f,,,f
[2734] 2019-04-03 20:56:15  info psql: finished at Wed Apr  3 22:56:15 2019
[2734] 2019-04-03 20:56:15  info psql: status done: psql session closed.
```

risk factors:
1. device 169.254.8.8 is a speudo device
1. device 10.40.254.35 is a citrix netscaler which has no neighbor proto enabled:
```
[2814] 2019-04-03 21:02:30 debug  [10.40.254.35] neigh - removed 0 outdated manual topology links
[2814] 2019-04-03 21:02:30 debug  [10.40.254.35] neigh - setting manual topology links
[2814] 2019-04-03 21:02:30 debug  [10.40.254.35] neigh - neighbor protocols are not enabled
[2814] 2019-04-03 21:02:30 debug  [10.40.254.35] neigh - processed 0 neighbors
```

**Comment by inphobia** [comment]
device 2 being able to run run discover::neighbors makes no difference, non existing topos remain.

**Comment by inphobia** [comment]
changing device 1 & 2 makes no difference:

1. created pseudo device "pseudo3", 10 ports, ip 169.254.10.10
1. linked pseudo3 port4 with loopback0 of device 10.98.100.1
1. changed pseudo3 from 10 ports down to 1 port
1. ran discoverall

```
netdisco-do psql -e "COPY (SELECT * FROM public.topology) TO STDOUT WITH CSV HEADER"
[4479] 2019-04-03 21:11:40  info App::Netdisco version 2.042005 loaded.
[4479] 2019-04-03 21:11:40  info psql:  started at Wed Apr  3 23:11:40 2019
dev1,port1,dev2,port2
169.254.8.8,Port2,10.40.254.35,1/5
169.254.9.9,Port4,10.98.100.1,Loopback0
10.98.100.1,Loopback0,169.254.10.10,Port4
[4479] 2019-04-03 21:11:40  info psql: finished at Wed Apr  3 23:11:40 2019
[4479] 2019-04-03 21:11:40  info psql: status done: psql session closed.
```

```
netdisco-do psql -e "COPY (SELECT * FROM public.device_port where ip = '169.254.10.10' ) TO STDOUT WITH CSV HEADER"
[4431] 2019-04-03 21:11:30  info App::Netdisco version 2.042005 loaded.
[4431] 2019-04-03 21:11:30  info psql:  started at Wed Apr  3 23:11:30 2019
ip,port,creation,descr,up,up_admin,type,duplex,duplex_admin,speed,name,mac,mtu,stp,remote_ip,remote_port,remote_type,remote_id,vlan,pvid,lastchange,manual_topo,is_uplink,slave_of,is_master
169.254.10.10,Port1,2019-04-03 23:09:46.576323,,,,other,,,,,,,,,,,,,,,f,,,f
[4431] 2019-04-03 21:11:31  info psql: finished at Wed Apr  3 23:11:31 2019
[4431] 2019-04-03 21:11:31  info psql: status done: psql session closed.
```

**Comment by ollyg** [comment]
Quite why one would do this I cannot imagine! However it's fixed :-)

[master d369814b] #549 redux - fix for changing pseudo device ports

**Comment by inphobia** [comment]
> Quite why one would do this I cannot imagine! However it's fixed :-)

to test of if topology cleaning was fixed without going through the hasstle of actually configuring it on real devices :-D
