### ISSUE TITLE
Error after migrate from sshcollector to device_auth

### ISSUE THREAD

**Issue by romale** [netdisco/netdisco#550]
I've update ND2 from 2.39.?? to 2.43.3 and I see that legasy sshcollector is deprecated. So, I've config migration by following this link https://github.com/netdisco/netdisco/wiki/sshcollector-Deprecation
After config conversion from "sshcollector:" to "device_auth:" i've errors in netdisco-backend.log

error: both snmp_auth and device_auth are defined! use only device_auth.
Compilation failed in require at /home/netdisco/perl5/lib/perl5/App/Netdisco.pm line 8.
BEGIN failed--compilation aborted at /home/netdisco/perl5/lib/perl5/App/Netdisco.pm line 8.
Compilation failed in require at /home/netdisco/perl5/bin/netdisco-backend-fg line 20.
BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-backend-fg line 20.

## Expected Behavior

ND starts running with new config

## Current Behavior

Error in log

## Possible Solution

Edit docs https://github.com/netdisco/netdisco/wiki/sshcollector-Deprecation ?

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 2.42.3
* SNMP::Info version used: 3.66

**Comment by rc9000** [comment]
Hi! device_auth is the new name of snmp_auth, please just merge what you had in snmp_auth also into device_auth and then delete snmp_auth - afterwards it should work as expected.

**Comment by inphobia** [comment]
tbh, we have not been quite clear on this in the docs imo. release notes mention we prefer device_auth over snmp_auth.

i can update the docs for this to make it more clear, and also mark it as incompatible

**Comment by romale** [comment]
> Hi! device_auth is the new name of snmp_auth, please just merge what you had in snmp_auth also into device_auth and then delete snmp_auth - afterwards it should work as expected.

Thanks, it's works!

**Comment by romale** [comment]
> tbh, we have not been quite clear on this in the docs imo. release notes mention we prefer device_auth over snmp_auth.
> 
> i can update the docs for this to make it more clear, and also mark it as incompatible

And, will helpful to notice about conversion "snmp_auth" to "device_auth" too and provide this link https://github.com/netdisco/netdisco/wiki/Configuration#code-device_auth-code
