### ISSUE TITLE
Wrong switch will be discovered

### ISSUE THREAD

**Issue by toasti2000** [netdisco/netdisco#553]
## Expected Behavior
netdisco-do -D discover -d 10.0.0.17 should discover Cisco switch 10.0.0.17

## Current Behavior
Wrong switch will be discovered!
[1797] 2019-03-26 16:18:38  info show: [10.0.0.11]/interfaces started at Tue Mar 26 16:18:38 2019

## Your Environment
We have Cisco 4500-X, 3850, 2960(-X) in use.
The switch that will not be discovered is a Cisco 2960-X and connected to another 2960. We have other switches that are also not connected directly to the 4500 core and work without any problems.

That the discover is going to 10.0.0.11 is absolutely strange because it is not the switch where 10.0.0.17 is connected to.
10.0.0.17 is connected to 10.0.0.14

* Netdisco version used: 	2.42.3
* SNMP::Info version used: 	3.66

Any idea how I can solve this?

**Comment by ollyg** [comment]
Hi @toasti2000 I wonder whether .17 is an IP alias configured on the .11 device? This will make Netdisco use the .11 device as it's the same one, from its view. You can test by:

`netdisco-do psql -e "select * from device_ip where alias = '10.0.0.17'"
`

**Comment by toasti2000** [comment]
Hi Oliver,
Bingo, that was the problem.
The dedicated management interface on switch .11 had the IP 17.

Now all is perfect!
Thanks for your fast help!
