### ISSUE TITLE
Syntx error - Port VLAN Mismatches

### ISSUE THREAD

**Issue by gmourani** [netdisco/netdisco#557]
Hello,

Going under Reports | Port | Port VLAN Mismatches, to get result if available returns an error message -> Search failed! Please contact your site administrator.

Looking into the "netdisco-web.log" file, you can see the following:

[11495] 2019-04-01 19:29:35 error request to GET /ajax/content/report/portvlanmismatch crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  syntax error at or near "ORDER"
LINE 5:                        ORDER BY vlan ASC ), ', ') AS vlist 
                               ^ [for Statement "SELECT me.left_device, me.left_port, me.left_vlans, me.right_device, me.right_port, me.right_vlans FROM (  WITH all_vlans AS
    (SELECT ip, port,
            array_to_string(array_agg( CASE WHEN native THEN 'n:' || vlan::text
                                        ELSE vlan::text END
                       ORDER BY vlan ASC ), ', ') AS vlist 
     FROM device_port_vlan GROUP BY ip, port)

  SELECT CASE WHEN length(ld.dns) > 0 THEN ld.dns ELSE host(ld.ip) END AS left_device,
         lp.port AS left_port,
         (SELECT vlist FROM all_vlans WHERE ip=lp.ip AND port=lp.port) AS left_vlans,
         CASE WHEN length(rd.dns) > 0 THEN rd.dns ELSE host(rd.ip) END AS right_device,
         rp.port AS right_port,
         (SELECT vlist FROM all_vlans WHERE ip=rp.ip AND port=rp.port) AS right_vlans
  FROM device ld
       JOIN device_port lp USING (ip)
       JOIN device_port rp ON lp.remote_ip=rp.ip AND lp.remote_port=rp.port
       JOIN device rd ON rp.ip=rd.ip
  WHERE ld.ip < rd.ip AND
        (SELECT vlist FROM all_vlans WHERE ip=lp.ip AND port=lp.port)
        !=
        (SELECT vlist FROM all_vlans WHERE ip=rp.ip AND port=rp.port)
  ORDER BY left_device, left_port
) me"] at /home/netdisco/perl5/lib/perl5/App/Netdisco/Web/Plugin/Report/PortVLANMismatch.pm line 19

* Netdisco version used: 2.039030
* SNMP::Info version used: 3.60
* PostgreSQL version used: 8.4.20
* DB Schema: 53

Regards,

**Comment by ollyg** [comment]
Hi,

I think this might be an issue with the version of PostgreSQL you're using.

8.4.x is pretty ancient (last released 2014) and although we've tried
really hard to maintain backwards compatibility for most parts of Netdisco,
there is newer more efficient SQL syntax we sometimes need to use.

Please can you try upgrading to at least 9.4 ?
https://www.postgresql.org/support/versioning/

Many thanks,
oliver.
