### ISSUE TITLE
netdisco-do enqueue and subworkers

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#559]
enqueueing a subjob with netdisco-do --enqueue inserts job into admin table but never gets run.

## Expected Behavior

netdisco-do discover::vlans -d ip --enqueue should run job at some time.

## Current Behavior

job gets scheduled but never run.

## Steps to Reproduce (for bugs)

1. `netdisco-do discover::vlans -DI -d 10.6.10.3 --enqueue`
2. `netdisco-do psql -e "COPY (SELECT * FROM public.admin where device = '10.6.10.3' order by entered DESC) TO STDOUT WITH CSV HEADER"`
```
[2442] 2019-04-03 20:41:29  info App::Netdisco version 2.042005 loaded.
[2442] 2019-04-03 20:41:29  info psql:  started at Wed Apr  3 22:41:29 2019
job,entered,started,finished,device,port,action,subaction,status,username,userip,log,debug,device_key
30298,2019-04-03 22:30:08.099564,2019-04-03 22:30:14,2019-04-03 22:30:14,10.6.10.3,,discover,,done,,,Ended discover for 10.6.10.3,,
30268,2019-04-03 22:14:06.722743,2019-04-03 22:14:57,2019-04-03 22:14:58,10.6.10.3,,discover,,done,testdisc,10.50.128.101,Ended discover for 10.6.10.3,,
30259,2019-04-03 22:11:12.633141,2019-04-03 22:11:13,2019-04-03 22:11:13,10.6.10.3,1,show,interfaces,done,testdisc,,Showed interfaces response from 10.6.10.3,,
30258,2019-04-03 22:10:28.863521,2019-04-03 22:10:29,2019-04-03 22:10:29,10.6.10.3,2,show,i_vlan,done,testdisc,,Showed i_vlan response from 10.6.10.3,,
30257,2019-04-03 22:09:59.160759,2019-04-03 22:10:00,2019-04-03 22:10:00,10.6.10.3,,show,i_vlan,done,testdisc,,Showed i_vlan response from 10.6.10.3,,
30256,2019-04-03 22:08:22.020782,2019-04-03 22:08:22,2019-04-03 22:08:23,10.6.10.3,,discover::vlans,,info,testdisc,, [10.6.10.3] vlans - discovered for ports and device,,
30235,2019-04-03 20:50:09.518404,2019-04-03 20:50:16,2019-04-03 20:50:16,10.6.10.3,,macsuck,,done,,,Ended macsuck for 10.6.10.3,,
30218,2019-04-03 20:10:38.147075,2019-04-03 20:10:38,2019-04-03 20:10:39,10.6.10.3,,arpnip,,done,,,Gathered arp caches from 10.6.10.3,,
30180,2019-04-03 17:02:02.532855,2019-04-03 17:02:04,2019-04-03 17:02:05,10.6.10.3,,discover,,done,,,Ended discover for 10.6.10.3,,
30158,2019-04-03 16:50:24.119578,2019-04-03 16:50:26,2019-04-03 16:50:26,10.6.10.3,,macsuck,,done,,,Ended macsuck for 10.6.10.3,,
30128,2019-04-03 16:10:24.75782,2019-04-03 16:10:31,2019-04-03 16:10:32,10.6.10.3,,arpnip,,done,,,Gathered arp caches from 10.6.10.3,,
30110,2019-04-03 12:50:35.728922,2019-04-03 12:50:36,2019-04-03 12:50:37,10.6.10.3,,macsuck,,done,,,Ended macsuck for 10.6.10.3,,
```
3. discover::vlans never gets run even if visible in jobqueue webinterface
4. tried:
   - discoverall
   - discover::vlans for device
   - add specific discover::vlans schedule worker in deployment.yml

## Your Environment

* Netdisco version used: HEAD
* SNMP::Info version used: 3.66

**Comment by ollyg** [comment]
I'm not sure you're interpreting this correctly.

The job is run but the final status is "info" not "done. OK this is confusing and perhaps buggy but is an artefact of picking one stage of an action. Most stages do not return "done" because the action needs to make an overall decision about whether it is successful and not rely on the status of any single stage.

So the queue and the running seem to run fine. You can test this by enqueueing the job and running:

`ND2_SINGLE_WORKER=1 bin/netdisco-backend-fg`
