### ISSUE TITLE
Timestamp incorrect, using wrong timezone?

### ISSUE THREAD

**Issue by toasti2000** [netdisco/netdisco#560]
## Expected Behavior
Timestamps should be the local time.

## Current Behavior
Timestamps are the "Universal time".

## Context
All timestamps in netdisco are 2 hours too late, because it is obviously using a wrong time zone?

Local time: Thu 2019-04-04 14:42:13 CEST
Universal time: Thu 2019-04-04 12:42:13 UTC
RTC time: Thu 2019-04-04 14:42:13
Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
systemd-timesyncd.service active: yes
RTC in local TZ: yes

## Your Environment
* Netdisco version used: 2.42.3
* SNMP::Info version used: 3.66

**Comment by ollyg** [comment]
Hi @toasti2000, yes timestamps internally to Netdisco are all in UTC.

Some reporting is in localtime, such as the time a job runs, as the poller is talking about is local situation. There is a wishlist item to display times in the web UI in localtime by converting, but we never had the opporutnity to implement that.

Many installations of Netdisco are spread over several timezones (either the installation itself or the devices) so the decision to store in the DB in UTC was taken a long time ago to avoid issues.

Sorry about that.
