### ISSUE TITLE
Feature Req: SNMP Chassis-ID

### ISSUE THREAD

**Issue by rowandavis** [netdisco/netdisco#562]
# Expected Behavior/New Feature
Feature to return the snmp-server chassis-id field on devices (Environment is Cisco)

## Current Behavior
chassis-id field isn't searched for/returned

## Possible Solution
Use the chassis-id field to return the configured value and display for devices discovered in NetDisco

## Context
I have just started using netdisco as an inventory tool. I use the chassis-id field to store the device Asset Number which is the item finance looks for in a stocktake situation. Being able to provide that 

## Your Environment
Software 	Version
App::Netdisco 	2.42.5
SNMP::Info 	3.66
DB Schema 	57
PostgreSQL 	10.00.6
Perl 	5.26.1

**Comment by ollyg** [comment]
Hi @rowandavis thanks for this, I would just like to check whether this is something we already do but for some reason is not working for your model of device.

Is the chassis ID the same as the serial number? We already store that and it is searchable in the main titlebar and will return the device. You can see this by going to any device and selecting the Modules tab and then seeing the Serial of the component. You can click on that to explore the device modules further. The serial can be searched on.

Let me know...
