### ISSUE TITLE
netdisco-do psql no longer works

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#565]
`netdisco-do psql` doesn't work in HEAD/master.

## Expected Behavior

`netdisco-do psql -e 'select * from admin' -DIQ` should return something.

## Current Behavior

`netdisco-do psql -e 'select * from admin' -DIQ` returns:
`[25425] 2019-04-24 19:26:07  info App::Netdisco version 2.042006 loaded.`

also tested with the example from the manual:
`netdisco-do psql -e 'SELECT ip, dns FROM device'` -> returns nothing.

## Steps to Reproduce (for bugs)

1. `netdisco-do psql -e 'select * from admin' -DIQ`

## Context

worked in 2.042006, doesn't work in HEAD/master.

## Your Environment

* Netdisco version used: HEAD
* SNMP::Info version used: 3.67

**Comment by inphobia** [comment]
most likely related to c0f260d36c70a0dbe2dcb0bb2bd3959315dc34de since nothing else was changed, but can't see why...

**Comment by ollyg** [comment]
Thanks! Fixed in
[master af428ddb] #565 fix netdisco-do when no device param needed

**Comment by inphobia** [comment]
@ollyg is on 🔥 :)
