### ISSUE TITLE
different sorting of the same devices Cisco 38xx

### ISSUE THREAD

**Issue by matrix1000** [netdisco/netdisco#567]
Hi,

I have a strange sorting in the inventory. For example I have
multiple Cisco 3850 Catalyst. 

## Expected Behavior
Expected is that all 38xx are in the same category (Model): Cisco 38xx Stack

## Current Behavior
But now one is in: Ca385024
two are in: Ca385024P
and all other are in: Cisco 38xx Stack

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
1. 
2. 
3. 
4. 

## Context
SNMP of the switches are similar:
entPhysicalDescr.1 = STRING: c38xx Stack
entPhysicalName.1 = STRING: c38xx Stack
entPhysicalDescr.1000 = STRING: WS-C3850-24P-L
entPhysicalModelName.1 = STRING: WS-C3850-24P-L

## Your Environment
* Netdisco version used: 2.42.6
* SNMP::Info version used: 3.66

**Comment by JeroenvIS** [comment]
So your report is about the "Model" indication for these devices, right? As shown in the Inventory screen, for example?

One detail to check in your network first: the three models that are currently *not* identified as "Cisco 38xx Stack", do they happen to have **_'no snmp-server sysobjectid type stack-oid'_** configured? That's the command that tells the switch to use the model of one of the stack members to represent the stack; it will probably match the model of the stack master. If so, reconfigure these switches to report the stack-oid, rediscover the switches in Netdisco and they should be reported as stacks.

See https://github.com/netdisco/netdisco/wiki/Vendor-Tips#report-cisco-as-single-device-instead-of-stacked-37xx29xxetc for reference.

**Comment by matrix1000** [comment]
Many thanks, that's it. :-)
