### ISSUE TITLE
cosmetic: access points show client icon

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#568]
close to irrelevant, but here goes: the connected devices column shows the icon for wireless clients next to access points.

## Expected Behavior

either:
* don't show the icon for access points
* have a different icon for access points
* change the wording from "wireless clients" to "wireless clients and access points"

having a separate would be the most elegant imo, but i have no clue where the original icons came from nor what their license is.

![image](https://user-images.githubusercontent.com/39005454/56829729-d28d3a80-6864-11e9-99c4-a5ad1c32463e.png)

this is an aerohive access point connected to a cisco 3750x.

## Your Environment
* Netdisco version used: master
* SNMP::Info version used: master

**Comment by ollyg** [comment]
thanks, fixed in
[master a4d4bf7f] #568 use different icon for WAPs from clients
