### ISSUE TITLE
GET /ajax/content/device/details crashed

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#577]
```
[5509] 2019-05-09 12:53:55 error request to GET /ajax/content/device/details crashed: Can't call method "first" on an undefined value at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/ResultSet/Device.pm line 143.
```
tested on 3 different setups, they all have the issue:
* local dev netdisco with 5 pseudo devices in the database and nothing else, perl 5.28.1
* test server running 2.042008 and around 40 devices, perl 5.26.3
* production server running 2.042006 and +-1000 devices, perl 5.26.3

reproducing the issue is very easy.

## Steps to Reproduce (for bugs)

1. create a pseudo device, name HAS to be `aaa`, ip and portcount don't matter
2. when you've added the pseudodevice, just click on it's name (or go to http-> /device?tab=details&q=aaa&f=
3. see how the webinterface gives an error and the beforementioned line is also written to the netdisco-web.log
4. pseudodevice has to be called `aaa`, i tried with other names like `iii` and `zzz´ but all those work just fine.

after having a quick look at the db/resultset/device query i don't see a reason why that one name would be special. device & device_ip data for the pseudo devices don't have any deviating data.

**Comment by ollyg** [comment]
thanks! nice catch. fixed in:
[master 416cffe5] #577 fix bug related to hostnames comprised a-f only
