### ISSUE TITLE
No devices shown on ports after update from 2.39 to 2.42.8

### ISSUE THREAD

**Issue by hcmuns** [netdisco/netdisco#583]
No devices shown on ports after update from 2.39 to 2.42.8

## Expected Behavior
As in the prior release it should have shown the connected nodes **and** devices.

## Current Behavior
The mac-adresses are detected on the switch-ports and shown, but the names of corresponding devices are not anymore. In the previous version it was shown correctly.
No errors where shown while performing de netdisco-do(debug) commands from the cli.

## Steps to Reproduce (for bugs)
To exclude any self inflicted errors I also performed a new installlation on a different server. It has shown the same results.

1. Take a running Netdisco application version 2.39 on Ubuntu 18.04 LTS
2. Check the mac-addresses and node device names as shown on the switch ports
3. Perform the upgrade to version 2.42.8 according to the update procedure described.
4. After restart the device names are not shown anymore.

## Context
Searching for computer/node names is essential for network administrators. Netdisco proved to be very usefull for that goal among other userfull features

## Your Environment

* Netdisco version used: 2.42.8
* SNMP::Info version used: 3.53

**Comment by inphobia** [comment]
how are you running netdisco 2.42.8 with snmp::info 3.53? you should be running snmp::info 3.68 or later with that:

https://github.com/netdisco/netdisco/blob/c81328d7a324e9f6c031b49cccfef76dc2b740b1/META.json#L85
