### ISSUE TITLE
Error/Bug Changing Native VLAN

### ISSUE THREAD

**Issue by cwoods131** [netdisco/netdisco#584]
## Expected Behavior

Changing the Native VLAN upon typing in the new value and then entering a reason for the change. Job should complete successfully and the VLAN should be changed on the switch.

## Current Behavior

Upon changing the Native VLAN value and entering a reason the Job is Failing with the following error:
`Failed Job:
Can't call method "remote_is_phone" on an undefined value at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Port.pm line 222, <__ANONIO__> line 1.`

## Steps to Reproduce (for bugs)

1. Navigate to Switch Port
2. Type new Native VLAN value
3. Submit Reason
4. Error as follows

## Context

Screenshot of the error:
![NetdiscoError](https://user-images.githubusercontent.com/37700946/57934668-31573a00-788e-11e9-8a11-f9e29cb7797a.png)

Thank you for your time.

## Your Environment

* Netdisco version used: 2.42.8
* SNMP::Info version used: 3.68

**Comment by inphobia** [comment]
any idea when this last worked? it's most likely related to 914e484b335de9348f5b7ff42a542d31f977073a

i guess this might be because device_port_properties remote_is_wap/phone can be NULL?

**Comment by ollyg** [comment]
thanks for the bug report @cwoods131 
this is fixed in the following commit which should be in the next release:
[master 902ab6c5] #584 fix for case where port has no corresponding properties row

**Comment by inphobia** [comment]
@ollyg 
one question: why was this error shown in the first place? according to config.yml & https://github.com/netdisco/netdisco/wiki/Configuration#show_errors we don't show errors by default. or is this not dancer related?

(don't get me wrong, having errors show is the way to go imo)
