### ISSUE TITLE
change userlog notifications default to false

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#585]

**Comment by inphobia** [comment]
should be only a change to config.yml

however, even with https://github.com/netdisco/netdisco/blob/cd2a4b936266b6a67f49ad0f79ae7f58e545f5d4/share/config.yml#L197 set to false there is still 1 popup you'll see.

to reproduce:
set check_userlog to false. restart just to be sure & clear browser cache.
then go to any device with neighbors, click on neighbors tab, wait 5 seconds. now you'll see a popup in the top right corner: "saved map positions".

even better, if you click on the neighbors tab & then quickly on the ports tab, the popup will still appear.

**Comment by ollyg** [comment]
thanks, applied a patch in:
[master 262fa880] #585 make toastr notifications less annoying

this patch changes default to false and also removes the map positions save notify you spotted.

however some things will still raise alerts, to confirm the user has submited requests for some things such as deleting a device in the web, as there is no other indication it's happened.
