### ISSUE TITLE
/admin/performance reports running jobs as completed

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#586]
the admin->poller perf page will list finished times for jobs which are still running.

## Expected Behavior

either display "running" instead of incorrect finished time, or just disregard running jobs.

## Current Behavior

poller performance will list running jobs as finished

## Steps to Reproduce (for bugs)

1. start a long running job (for me macwalk takes 20 minutes, that's where i notice it most)
2. go to admin->poller performance
3. notice the macwalk job you just started has a start AND finished time
4. refresh the admin->poller performance and notice the finished time increasing

when the macwalk job completes the finished timestamp will be correct, but during the run it will keep updating.

the admin table will list it as:
"52717"|"2019-05-21 20:50:08.906472"|"2019-05-21 20:50:09"|"2019-05-21 20:50:10"|||"macwalk"||"done"|||"Queued macsuck job for all devices"||

as you can see it has a start & finish time filled in.

perhaps it's status should be listed as "running" instead of done, but that seems a non trivial change...

## Your Environment

* Netdisco version used: master
* SNMP::Info version used: master

**Comment by ollyg** [comment]
thanks, good suggestion, fixed in:
[master 087ca8e3] #586 do not show poller performance rows for still running jobs

note that the fix removes rows for sets of jobs still running, rather than still showing them with "running" flag or whatever.
