### ISSUE TITLE
[Feature Request] Show which port the device is connected

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#588]
## Feature Request

Dear netdisco developers,

I think a nice feature to be added to netdisco, is to show on which port the device is connected.

For example, in the Neighbor Map Controls, It can be added a new button where this option can be selected.

This feature will be helpful because it will improve a lot the readability of netdisco, in this way the users can have a better understanding of network's topology.

Thank you.

Best Regards.

**Comment by ollyg** [comment]
Hi @def-bs, thanks for the question. In the map you can hover the mouse over the link to show the ports at each end. Does that show what you need?

**Comment by def-bs** [comment]
Oh yes. It is what I was looking for! 
Thank you a lot.

**Comment by def-bs** [comment]
Anyway, the feature could be very useful on map when there are a lot of devices. For example, if you have hundreds of devices, checking one by one can be tedious. I hope it will be reviewed in the future. 
Best Regards.

**Comment by inphobia** [comment]
perhaps an option is to define devices as subgraphs with their ports as elements, something like
![image](https://user-images.githubusercontent.com/39005454/58268325-86f77f00-7d85-11e9-86e2-38d0d4235537.png)

(example from https://renenyffenegger.ch/notes/tools/Graphviz/examples/index )

this does however use graphviz (which is supported with netdisco-do) and is in need of an overhaul. i started working on it but then moved on to something i currently have more use for.

do know that graphviz is not like our web network map, it just produces a flat image, not the interactive thing we have on the web. there are options to do that with graphviz too, but that's not on my scope atm.
