### ISSUE TITLE
feature request: make domain_suffix array

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#591]
due to politics/management/whatever(/even actual technical reasons) we have multiple dns namespaces in our network. as such our hostnames sometimes contain part of the fqdn. it would be nice if domain_suffix accepted an array or regex or whatever so we can strip more unneeded info.

## Possible Solution

make domain_suffix take arrays or regex config.

possible issue: hostnames (not fqdn) might now be duplicate, on the other hand dns allows multiple a records per name & multiple ptr records per reverse (not sure about the multiple ptr records per reverse, but most major resolvers just support it)

## Steps to Reproduce (for bugs)

1. simplest way: create 2 subdomains, for example doma.example.com & domb.example.com
2. have nodes in both subdomains: host1.doma.example.com & host2.domb.example.com
3. set domain suffix to .example.com, now nodes will show up in the web interface as host1.doma & host2.domb

## Your Environment

* Netdisco version used: master
* SNMP::Info version used: master

**Comment by ollyg** [comment]
implemented in:
[master 542837d2] #591 domain_suffix can be list and supports (simple) regexp
