### ISSUE TITLE
swagger api docs

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#592]
from the sourceforge mailinglist, copying it here so the info doesn't get lost.

tagging @pyro3d & @ollyg since they're the brains behind all this.

**Comment by inphobia** [comment]
I was able to figure out where I was mistaken in how I thought this would work. I saw the new features
"Implementation of API authentication and Swagger-UI (pyro3d and ollyg)" in 2.042000 and assumed that mean that an API was available.

The API authentication worked as described. I needed to install a plugin in order to retrieve information. If this isn’t correct please let me know but the following is what I did. Thank you to ollyg and pyro3d for working on Netdisco and the associated plugin.

I used the following command to get an api_key

curl -X POST \
https://<netdiscoserver>/login \
-H 'Accept: application/json' \
-H 'Authorization: Basic <base64encoded username and password username:password>' \
-H 'Cache-Control: no-cache' \
-H 'Connection: keep-alive' \
-H 'Content-Type: application/json' \
-H 'Host: <netdiscoserver>'\
-c '<cookiefile>'

This returned the following.

{"api_key":”<api_key_is_here"}

I assumed after I retrieved the key that I had access to an API. I believe this was incorrect. pyro3d has a REST API Plugin for Netdisco posted on GitHub. https://github.com/pyro3d/netdisco-rest-api

I installed this plugin and then was able to use the cookie I generated above to retrieve json from the REST API Plugin.

The following are the basic steps I used to setup up pyro3d's plugin.

To install the pyro3d's plugin I downloaded the files from github and put them into an API folder under my App::NetdiscoX::Web::Plugin:: namespace. For my server this ended up being

/usr/local/share/perl5/App/NetdiscoX/Web/Plugin/API/

The files in GitHub were named Device.pm and Node.pm. I renamed them based on errors I received in my netdisco-web.log after finishing the plugin setup and how I understood the documentation at https://github.com/netdisco/netdisco/wiki/Web-Plugins Device.pm was renamed to DEVICE.pm and Node.pm was NODEIP.pm .

/usr/local/share/perl5/App/NetdiscoX/Web/Plugin/API/NODEIP.pm
/usr/local/share/perl5/App/NetdiscoX/Web/Plugin/API/DEVICE.pm

After the plugin was installed I added the following to my deployment.yml to enable the plugin.

extra_web_plugins:
- X::API::NODEIP
- X::API::DEVICE

I restarted netdisco-web to make sure the plugin was loaded.

In my web browser once authenticated to netdisco I went to

https://<netdiscoserver>/api/device/all and received back json with all of my devices.

The following curl command then can retrieve this same information if I use a cookie like I generated above.

curl -X GET \
https://<netdiscoserver>/api/device/all \
-H 'Accept: application/json' \
-H 'Cache-Control: no-cache' \
-H 'Connection: keep-alive' \
-H 'Content-Type: application/json' \
-H 'Host: <netdiscoserver>'\
-b '<cookiefile>'

I hope this helps someone else.





On Wed, May 15, 2019 at 10:42 AM Robert Lewis <robert.lewis.m@gmail.com> wrote:
Good morning,

I was wondering if someone could point me to an example on how to use the API? I have been able to retrieve the api_key but I am unable to use it to retrieve anything.

Does anyone have an example of querying the API they would be willing to share? When I load the http://netdisco/swagger-ui there is an error at the bottom saying {"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://netdisco.cgresd.net/swagger.json"}]} . I can view the file successfully.

If I need to do more research please let me know.

Thank you,


--
Robert Lewis



________________________________

Volg Aquafin op Facebook<https://www.facebook.com/AquafinNV> | Twitter<https://twitter.com/aquafinnv> | YouTube<http://www.youtube.com/channel/UCk_4P5BJ-MtEEDCkCsR_KqQ?feature=mhee> | LinkedIN<http://www.linkedin.com/company/aquafin/products> | Instagram<https://www.instagram.com/aquafin_nv/>

In het kader van de uitoefening van onze taken verzamelen we bij Aquafin persoonsgegevens. Hoe we omgaan met deze gegevens en wat de rechten van de betrokkenen zijn, kan je nalezen in onze privacy policy<https://www.aquafin.be/nl-be/privacy-policy>.

  P Denk aan het milieu. Druk deze mail niet onnodig af.

**Comment by dunderrrrrr** [comment]
I'm having a hard time getting this API to start. I'm doing something wrong obviously.

Netdisco v.2.044000

I cloned the repo into `/home/netdisco/perl5/lib/perl5/App/Netdisco/Web/Plugin/API` and renamed the files to DEVICE.pm and NODEIP.pm.

Placed the following in `/home/netdisco/environments/deployment.yml`:

```
extra_web_plugins:
- X::API::NODEIP
- X::API::DEVICE
```
When restarting webservice I'm recieving this error:

`
Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: Can't locate App/NetdiscoX/Web/Plugin/API/NODEIP.pm in @INC (you may need to install the App::NetdiscoX::Web::Plugin::API::NODEIP module) (@INC contains: /home/netdisco/site_plugins /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /home/netdisco/perl5/lib /home/netdisco/perl5/bin/lib /home/netdisco/perl5/lib/perl5/5.22.1/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5/5.22.1 /home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl/5.22/Module/Load.pm line 77.
Can't locate App/NetdiscoX/Web/Plugin/API/NODEIP in @INC (@INC contains: /home/netdisco/site_plugins /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /home/netdisco/perl5/lib /home/netdisco/perl5/bin/lib /home/netdisco/perl5/lib/perl5/5.22.1/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5/5.22.1 /home/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/netdisco/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl/5.22/Module/Load.pm line 77.
Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 53.
BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 53.
`

Any ideas? 
The lack of documentation regarding this topic is... frustrating :)

**Comment by ollyg** [comment]
Hi @dunderrrrrr, sorry to hear this is frustrating, but the documentation is missing precisely because this is only a half developed feature.

Yes the API authentication is done, but due to the old design of Netdisco it's proved very difficult to make a JSON data interface. The Swagger support helps us develop it, but the project doesn't have many people looking at this side of things right now (patches welcome!).

The patch from @pyro3d is indeed very good, but I've not had a close enough look at how we can fold that into the core to make things smoother. Certainly I would wish to avoid any of the file copying/renaming you've done!

Leaving this ticket open as a reminder.

**Comment by ollyg** [comment]
Full API will be in the next release of Netdisco (no need for the plugin any more), see #712 
and see also https://github.com/netdisco/netdisco/wiki/API
