### ISSUE TITLE
device_port_log table does not have a primary key

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#594]
but according to the docs it should have one. fix the docs or change the database?

https://github.com/netdisco/netdisco/blob/065e74df62db74064776b0b40fd65f31a035e1d1/lib/App/Netdisco/DB/Result/DevicePortLog.pm#L43

**Comment by ollyg** [comment]
thanks, applied fix in
[master 744da684] #594 add PK to device_port_log and other tidying
