### ISSUE TITLE
DeviceSkip.pm default value 

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#596]
intellij seems to think that our default value for actionset is incorrect. from what i understand of it it seems to be best practice to cast empty arrays to their actual type; which can have a difference in how `is null` behaves?

for someone who has a better insight as i do.

IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8

```
--- lib/App/Netdisco/DB/Result/DeviceSkip.pm	(revision 28c93709d8849ac6383e3ba1a5981120ed77b332)
+++ lib/App/Netdisco/DB/Result/DeviceSkip.pm	(date 1558899844097)
@@ -14,7 +14,11 @@
   "device",
   { data_type => "inet", is_nullable => 0 },
   "actionset",
-  { data_type => "text[]", is_nullable => 1, default_value => '{}' },
+  {
+    data_type     => "text[]",
+    default_value => \"'{}'::text[]",
+    is_nullable   => 1,
+  },
   "deferrals",
   { data_type => "integer", is_nullable => 1, default_value => '0' },
   "last_defer",
```

**Comment by ollyg** [comment]
thanks, applied patch in
[master 655d2518] #596 fix default value on actionset field
