### ISSUE TITLE
plenv support

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#598]
since starting to use intellij idea as my ide i've gotten to know plenv, which is a perl version manager, somewhere in between perlbrew & local::lib in terms of features. (cpanm support is included)

it's also in active dev so not an old & stale project:
https://github.com/tokuhirom/plenv

it installs a completely local perl version(s), handles xs and a bunch more stuff. it's local::lib support is quite sober however and most of our stuff dies if either localenv or perlbrew can't be found.

```
      die "Sorry, can't find libs required for App::Netdisco.\n"
        if !exists $ENV{PERLBREW_PERL};
```
 
since we kinda support perlbrew i'd like to add support for plenv too, but since it either uses shell functions or a script to set up it's environment it's not as easy as just adding and $ENV check.

so, before i begin work on this, i was wondering if there were any objections?

if so i'll just find a way to work around missing localenv support for my personal environment.

since it relies on a script i was thinking IPC::Cmd->can_run() would be a sufficient check to see if plenv is available:
https://perldoc.perl.org/IPC/Cmd.html

**Comment by inphobia** [comment]
other options could be:
 * also test for $home/perl5 as last resort fallback, but that seems errorprone.
 * just provide an empty localenv, since plenv already did all the perl env setup
 * use plenv-contrib local::lib support, but how many abstraction layers do you need... (https://github.com/miyagawa/plenv-contrib)

**Comment by ollyg** [comment]
I am reluctant, as plenv is incompatible with perlbrew (they cannot both be installed). sorry.
