### ISSUE TITLE
Can't remove wrong DNS name for switch

### ISSUE THREAD

**Issue by StiM-git** [netdisco/netdisco#604]
Expected Behavior
DNS resolution for IPs populates devices, if it can't be resolved remove entry

Current Behavior
There used to be an incorrect entry in our DNS for for a switches IP address, this therefore populated the DNS name in netdisco as expected. I have now removed the entry from the DNS but it wont replace the entry to null (This was 2 weeks ago).

Address | DNS | Interface | Description | Prefix
10.*.*.127 | oldrecord.domain | VLAN2 |   | 10.*.*.0/22

Your Environment
Netdisco version used: 2.42.8
SNMP::Info version used: 3.68

**Comment by ollyg** [comment]
@StiM-git that's very odd! all records are wiped and recreated on device discovery. Are you sure this device has been rediscovered?

Also, can you give a screenshot as well as table data? which table is this from?

**Comment by StiM-git** [comment]
Indeed odd, the DNS entry no longer appears in the 'addresses' section so I know it's gone from our DNS but it still appears under the device. See attached
![2019-06-12_09-42-46](https://user-images.githubusercontent.com/25978763/59336827-37a6cd80-8cf7-11e9-8e5d-9cbb9408b464.png)
![2019-06-12_09-43-00](https://user-images.githubusercontent.com/25978763/59336828-383f6400-8cf7-11e9-9bf0-66ecc55f9ed1.png)

**Comment by ollyg** [comment]
Hi @StiM-git, which report is that in the second screenshot?

**Comment by ollyg** [comment]
Oh, can you check /etc/hosts on your system as well? Thanks.

**Comment by StiM-git** [comment]
Host file only contains its loopback address and it's own ip address.

The report from the second screenshot is Device>By Location.

**Comment by ollyg** [comment]
Then I am at a loss! :-(
The discover code takes the device IP and does a DNS lookup on it and stores in the dns field of the device database table. The DevicesByLocation report simply retrieves the rows from the device table and shows them.

Would be good to double check what's in the device table:
`bin/netdisco-do psql -e 'select dns from device where ip = 1.2.3.4;'`

And also to run `host 1.2.3.4` at the command line on the netdisco server to see what it's picking up via dns.

**Comment by ollyg** [comment]
err, bad sql quoting, instead:
bin/netdisco-do psql -e "select dns from device where ip = '1.2.3.4';"

**Comment by StiM-git** [comment]
Seems the netdisco server is picking up the wrong dns record from somewhere because the host command is resolving the ip address to that erroneous name.

**Comment by ollyg** [comment]
ah, OK, I'll close this as it's a local sysadmin issue
