### ISSUE TITLE
update LICENSE file to work with licensee

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#606]
https://spdx.org/licenses/BSD-3-Clause.html
and
https://github.com/spdx/license-list-XML/blob/bb743abd1f811c4fbf003540ce0173fca1153f5e/src/BSD-3-Clause.xml
and
https://github.com/licensee/licensee/issues/344

**Comment by inphobia** [comment]
side note: our license file is called LICENCE , as correct in en-gb, but en-us seems to prefer it spelled licenSe, i saw some tools stumble on this in the past.

**Comment by ollyg** [comment]
fixed in 0e06e365
