### ISSUE TITLE
Wireless APs Selection Not Working (Nodes discovered through LLDP/CDP)

### ISSUE THREAD

**Issue by avoidingthesubject** [netdisco/netdisco#617]
When selected it shows "No matching records."

```
wap_capabilities:
    - 'wlanAccessPoint'
wap_platforms:
    - '(?i:\bwap\b)'
    - 'cisco\s+AIR-[L|C]?AP'
    - '-K9W8-'

phone_capabilities:
    - '(?i:phone)'
phone_platforms:
    - '(?i:mitel.5\d{3})'

discover_no_type:
#   - 'cisco\s+AIR-'
    - '(?i)Cisco\s+IP\s+Phone'
```

## Expected Behavior

Interestingly, with above config, IP Phones DO show in the CDP list when selected.
APs do not...

The Access Points are visible if I select them in the Node Search Options: Remote Type.

## Your Environment

* Netdisco version used: 
	2.42.3
* SNMP::Info version used: 
	3.65

## Device information

Cisco Access Points

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by dgeo** [comment]
Just reading the regex, did you try replacing '[L|C]?' by '[LC]?', pipe character is not needed here IMHO

**Comment by avoidingthesubject** [comment]
Hey @dgeo - nah that hasn't helped...

**Comment by StewAlexanderACC** [comment]
Have the same issue, wireless section under reports is blank

**Comment by inphobia** [comment]
discover_no_type has been retired, see

* https://github.com/netdisco/netdisco/wiki/Release-Notes#2-040004
* https://github.com/netdisco/netdisco/wiki/Configuration#discover_no_type

can you follow the instructions there and move to discover_waps/phones?

**Comment by StewAlexanderACC** [comment]
@inphobia 
It may take a bit of time, should have a report back by early next week

**Comment by inphobia** [comment]
> It may take a bit of time, should have a report back by early next week

no rush 😄
