### ISSUE TITLE
Question: Is there a way for NetDisco to do routine discoveries of the network?

### ISSUE THREAD

**Issue by StewAlexanderACC** [netdisco/netdisco#618]
Hi @ollyg -

Is there a way for NetDisco to run routine discovery scans of the network? I can do it manually through an admin account using **Admin -> Discover All** etc, but is there a way for NetDisco to do this on its own?

Tried to find instructions to no avail.

Thank you ...

**Comment by rc9000** [comment]
This is done by adding a `discoverall` entry to the schedule, see https://github.com/netdisco/netdisco/wiki/Configuration#schedule

Good luck!

**Comment by ollyg** [comment]
But the default schedule already has a discoverall in. So it would be worth finding out why the default schedule is not run.

@StewAlexanderACC are you using the docker images, or have followed the install instructions at https://metacpan.org/pod/App::Netdisco ?

**Comment by StewAlexanderACC** [comment]
I am running the docker image, plus the docker containers all shutdown last night ... watching them via cockpit

**Comment by StewAlexanderACC** [comment]
When running ```$sudo docker-compose up```, should I run this with a nohup or something?

**Comment by ollyg** [comment]
I'll be honest with you @StewAlexanderACC, the docker versions of Netdisco don't get a lot of love or testing, so I would not be surprised to hear of glitches which are not you just having missed something.

If you can install on a regular system, the instructions at https://metacpan.org/pod/App::Netdisco give a very reliable output. If you wish to use docker, we might need to wait for someone to try to reproduce the issues you're seeing.

Just to be clear the backend daemon should be running (netdisco-backend container) and it should run a discoverall each night.

**Comment by LBegnaud** [comment]
you would want `docker-compose up -d` to make it run in the background

you may also want to set some kind of `restart` policy in the compose file

Note that I'm running the docker images and they appear to run properly with schedules... though I haven't put it into production yet.

**Comment by StewAlexanderACC** [comment]
@ollyg

Other than just guessing if it is running or not, is there a log that shows the "auto discover all" being run or not?

If not, I'd like to add this as a feature request

**Comment by StewAlexanderACC** [comment]
I attempted to read the less than stellar instructions on the website mentioned
```
If you can install on a regular system, the instructions at https://metacpan.org/pod/App::Netdisco give a very reliable output. If you wish to use docker, we might need to wait for someone to try to reproduce the issues you're seeing.
```
But as I am not a developer it was well beyond me, and by the looks of things (reading the internet mumbling) I'm not the only one with issues following those install instructions.

So weird you all don't have a repo where we can curl for a script, which when ran does the install like so many other clients

**Comment by StewAlexanderACC** [comment]
BTW - on the website you mentioned ```https://metacpan.org/pod/App::Netdisco``` the install instructions are not too bad, but boy when I tried to upgrade from 1.x to the latest using the upgrade instructions, I got severely lost.

We however like your container idea, and will muddle through with it, thanks

**Comment by StewAlexanderACC** [comment]
FYI:

Cockpit output:
![image](https://user-images.githubusercontent.com/48565067/60982433-1e00a200-a306-11e9-92de-60ad2f63f73a.png)

**Comment by inphobia** [comment]
> BTW - on the website you mentioned `https://metacpan.org/pod/App::Netdisco` the install instructions are not too bad, but boy when I tried to upgrade from 1.x to the latest using the upgrade instructions, I got severely lost.

care to go into a bit more detail about that so we can improve our docs? thx

**Comment by StewAlexanderACC** [comment]
When I have a moment in the near future I'll add some details.

I should have kept a log when I was trying to upgrade, heh.. lesson learned

**Comment by StewAlexanderACC** [comment]
Closing as I'm not going to be able to get to this in the near future, anyhoo the product is working for me and its quite nice - thanks @ollyg and team
