### ISSUE TITLE
Giving the user the opportunity to change Neighbors depth

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#620]
## Expected Behavior

Dear netdisco team,

Due to large network infrastructure, we have difficulties to analyze the map.

Recently, we added almost 500 APs that now are shown in the map, making even harder to understand network topology.

We would like to have the opportunity to change Neighbors depth.

## Current Behavior

Right now, when you select a device, only the 1-level Neighbors are shown.

It would be nice to select Neighbors depth, in this way, the user can see only the desired Neighbors

## Possible Solution

Adding Neighbors depth.

Thank you.

**Comment by rc9000** [comment]
Hi @def-bs, I do agree that this would be nice. For even slightly bigger networks, showing all devices is completely out of the question. However having two or three hops would be great. I've never looked into the map code so far and I don't know how complicated it would be, but I'd say it's a valid wishlist item worth exploring.

**Comment by inphobia** [comment]
@def-bs this can be a pain, but have a look at:
https://github.com/netdisco/netdisco/wiki/Network-Map#choosing-which-devices-to-show
https://github.com/netdisco/netdisco/wiki/Configuration#host_groups

while this is requires explicit configuration in deployment.yml, i guess there's most likely a logical way these ap's are grouped (building, location, ip range, ...). host_groups is very flexible in how it selects members (see https://github.com/netdisco/netdisco/wiki/Configuration#access-control-lists). groups can also include other groups.

you can combine multiple groups on the network map by holding down the control key on your keyboard & then clicking the wanted groups. this works in combination with "all devices" too if you want to see everything included in all selected host groups

.

**Comment by inphobia** [comment]
> Hi @def-bs, I do agree that this would be nice. For even slightly bigger networks, showing all devices is completely out of the question. However having two or three hops would be great. I've never looked into the map code so far and I don't know how complicated it would be, but I'd say it's a valid wishlist item worth exploring.

it's on the wishlist for a graphing update:
https://github.com/netdisco/netdisco/projects/5#card-22072506

while the focus of that is cli mostly the web part will be looked at too.

**Comment by ollyg** [comment]
I've added this to the wishlist page: https://github.com/netdisco/netdisco/wiki/Wishlist

**Comment by ollyg** [comment]
Is now implemented!
