### ISSUE TITLE
test::compile > 2.1.2 breaks tests

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#622]
see travis for commit f1891be
https://travis-ci.org/netdisco/netdisco/builds/559751868

## Possible Solution

fix xt/00-compile.t to work with newer test::compile or force usage of test::compile 2.1.2 or earlier.

## Steps to Reproduce (for bugs)

1. `cpanm https://cpan.metacpan.org/authors/id/E/EG/EGILES/Test-Compile-v2.2.2.tar.gz`
2. `perl ./Build test --test_files xt/`
3. `cpanm https://cpan.metacpan.org/authors/id/E/EG/EGILES/Test-Compile-v2.1.2.tar.gz`
4. `perl ./Build test --test_files xt/`

## Your Environment

* Netdisco version used: head
* SNMP::Info version used: head
* perl 5.28.2, test::compile 2.2.2

**Comment by inphobia** [comment]
```
perl ./Build test --test_files xt/
xt/00-compile.t .......... 19/? # Path::Tiny paths require defined, positive-length parts at /home/testdisc/perl5/lib/perl5/Dancer/Plugin/Swagger.pm line 84.
# Compilation failed in require at blib/lib/App/Netdisco/Web.pm line 18.
# BEGIN failed--compilation aborted at blib/lib/App/Netdisco/Web.pm line 18.

#   Failed test 'blib/lib/App/Netdisco/Web.pm compiles'
#   at xt/00-compile.t line 30.
xt/00-compile.t .......... 41/? # Can't use an undefined value as a HASH reference at blib/lib/App/Netdisco/JobQueue.pm line 7.
# Compilation failed in require at blib/lib/App/Netdisco/Web/AdminTask.pm line 9.
# BEGIN failed--compilation aborted at blib/lib/App/Netdisco/Web/AdminTask.pm line 9.

#   Failed test 'blib/lib/App/Netdisco/Web/AdminTask.pm compiles'
#   at xt/00-compile.t line 30.
xt/00-compile.t .......... 48/? # Can't use an undefined value as a HASH reference at blib/lib/App/Netdisco/JobQueue.pm line 7.
# Compilation failed in require at blib/lib/App/Netdisco/Web/PortControl.pm line 8.
# BEGIN failed--compilation aborted at blib/lib/App/Netdisco/Web/PortControl.pm line 8.

#   Failed test 'blib/lib/App/Netdisco/Web/PortControl.pm compiles'
#   at xt/00-compile.t line 30.
xt/00-compile.t .......... 55/? ^C
```

**Comment by inphobia** [comment]
https://github.com/netdisco/netdisco/commit/38b800e46f9cad4c92d197eea05590f60eb7a9b4 at least makes it do something again

**Comment by rc9000** [comment]
Test::Compile seems to have undergone some redesign in 2.2. Unfortunately it does not seem to work with our code, e.g. the first failing test `Path::Tiny paths require defined, positive-length parts at /home/testdisc/perl5/lib/perl5/Dancer/Plugin/Swagger.pm line 84` tries to lookup `App/Netdisco.pm` in `%INC`, but the only bits of our module structure in there are:

    'App/Netdisco/Web/AuthN.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Web/AuthN.pm',
    'App/Netdisco/Util/Web.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Util/Web.pm',

While all earlier versions gave a full populated `%INC` with

    'App/Netdisco/Environment.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Environment.pm',
    'App/Netdisco/Util/Web.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Util/Web.pm',
    'App/Netdisco/Web/AuthN.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Web/AuthN.pm',
    'App/Netdisco/Util/DeviceAuth.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Util/DeviceAuth.pm',
    'App/Netdisco.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco.pm',
    'App/Netdisco/Util/DNS.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Util/DNS.pm',
    'App/Netdisco/Web.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Web.pm',
    'App/Netdisco/Configuration.pm' => '/appl/netdisco/netdisco_github_official/lib/App/Netdisco/Configuration.pm',

So then the obvious workaround would just be to `test_requires {'Test::Compile' => '<= 2.1.2'}`, in Build.PL, but I tried some variants of this and they all still installed 2.2.0.

Maybe some resident guru has any ideas why the above things happen?

For now I have added this workaround in .travis.yml:

    install:
      - wget https://github.com/egiles/test-compile/archive/v2.1.2.tar.gz
      - cpanm -v v2.1.2.tar.gz 
      - cpanm --quiet --notest PkgConfig Test::CChecker Alien::zlib::Static Alien::OpenSSL::Static Alien::SNMP

This works but it seems a bit wonky, so better solutions are welcome.

**Comment by ollyg** [comment]
wonky but works is fine for me :-)
