### ISSUE TITLE
device search layers not working as expected

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#624]
## Expected Behavior

i expect that selecting multiple options in the layers dropdown to return devices that match at least 1 of those layers.

this expection is inline with all other selection boxes (os versions, vendors, etc.). if for example you select multiple vendors you get all the devices that match any of those vendors, not ALL of them.

## Current Behavior

selecting multiple layers will only return devices that have have all of the layers.

guess an easier way to explain:
all dropdown boxes seem to use `OR` as condition to select valid values
layers however seems to use `AND` instead.

to make matters ever more complicated, if you only select 1 layer (like layer 3), then the query will return all devices that have that layer present, regardless of which other layers it also claims to support.

## Possible Solution

not sure if this is a bug or as designed, but at least to me it's confusing that layers haves different as the other selection operators.

## Steps to Reproduce (for bugs)

i tested with 3 devices in the db:
* 2 pseudodevices, which now provide layer3 (only)
* 1 cisco sb, providing layer2 only

1. to start, enter an asterix `*` in the "search anything" bar, then search for devices.
   the url string will be `/search?tab=device&q=*&dns=&ip=&name=&location=&description=&matchall=on`
2. the web interface should return "No matching records." (strange, i thought globbing was supported)
3. in the sidebar, select layer2 & search. the ciscosb device will be returned
    url: `search?tab=device&q=*&dns=&ip=&name=&location=&description=&layers=2`
4. now select layer3, the 2 pseudodevices will be returned.
    url: `search?tab=device&q=*&dns=&ip=&name=&location=&description=&layers=3`
5. now select both layer2+3, no devices will be returned
    url: `search?tab=device&q=*&dns=&ip=&name=&location=&description=&layers=2&layers=3`
6. matchall on or off does not make a difference

to verify that only devices that match all selected layer options i also tested on another installation with 2000 or so devices. we have a few oneaccess routers in there which claim to do layers1/2/3/4/7 , a combination unique to them. searching with the following url:
`search?tab=device&q=*&dns=&ip=&name=&location=&description=&layers=1&layers=2&layers=3&layers=4&layers=7&matchall=on`
does indeed only return said oneaccess routers.

## Your Environment

* Netdisco version used: HEAD
* SNMP::Info version used: HEAD

**Comment by inphobia** [comment]
kinda confusing i guess, so to summarize:

search type | selection | result  
------------ | -------- | ------
layer | 3 | all devices that report layer3, regardless of other layers
layer | 2 | all devices that report layer2, regardless of other layers
layer | 2+3 | all devices that report **at least** layers2+3
os ver | 15.3(3)M3 | only devices running 15.3(3)M3
os ver | 15.3(3)M5 | only devices running 15.3(3)M5
os ver | 15.3(3)M3 + 15.3(3)M5 | devices running **either** 15.3(3)M3 or 15.3(3)M5

i guess a point can be made that layers can't be compared to vendor names or os versions, since you can have multiple layers for a device but it can't have multiple vendors.

on the other hand there currently is no way to search for devices that only have 1 layer (like a pseudodev, which only reports layer3). searching for layer3 will return any device that has layer3 services.

i'm not sure if it's really worth the time, or if it's even wanted, to change this. seems someone spent quite some time in `App::Netdisco::DB::ResultSet::Device` to make it behave like it does. regretfully that it does, imo, the complete opposite of any other search option.

**Comment by ollyg** [comment]
Thanks, fixed in [master 1b89d20d] #624 device layers search should be OR (not AND)
