### ISSUE TITLE
Not possible to instal using the install instructions on Ubuntu 18

### ISSUE THREAD

**Issue by Ondjultomte** [netdisco/netdisco#627]
sudo apt-get install libdbd-pg-perl libsnmp-perl libssl-dev libio-socket-ssl-perl curl postgresql build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libsnmp-perl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libdbd-pg-perl
E: Package 'libsnmp-perl' has no installation candidate

The install instructions are dated, or isn't Ubuntu 18 supported?

**Comment by Ondjultomte** [comment]
And if we skip that issue and move on there are more issues.

curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco
results in

uccessfully installed Test-Warn-0.36
! Installing the dependencies failed: Module 'DBD::SQLite' is not installed, Module 'Sub::Name' is not installed, Module 'DBI' is not installed
! Bailing out the installation for DBIx-Class-0.082841.
! Installing the dependencies failed: Module 'DBIx::Class' is not installed
! Bailing out the installation for App-Netdisco-2.042010.
34 distributions installed

**Comment by inphobia** [comment]
the ubuntu thing could be related to outdated packages, did you run 'apt-get update' of something first to make sure your caches are up to date?

**Comment by rc9000** [comment]
I just happened to do an install on 18.04 LTS, and apt-get install was perfectly fine. I ended up with:

    root@lanmgmt02-emea:~# cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=18.04
    DISTRIB_CODENAME=bionic
    DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
    
    root@lanmgmt02-emea:~# uname -m      
    x86_64
    
    root@lanmgmt02-emea:~# apt show libdbd-pg-perl | egrep '(Sources|Package|Version)'
    Package: libdbd-pg-perl
    Version: 3.7.0-1
    APT-Sources: http://ch.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
    
    
    root@lanmgmt02-emea:~# apt show libsnmp-perl | egrep '(Sources|Package|Version)'
    Package: libsnmp-perl
    Version: 5.7.3+dfsg-1.8ubuntu3.1
    APT-Sources: http://ch.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages

@Ondjultomte I'm closing this for since it doesn't seem to be a general issue and the comments here are already pretty old. If it still doesn't work for you, please give us the output of the first two commands above, then we can investigate the specific Ubuntu release and architecture.
