### ISSUE TITLE
Display Full Vendor Name?

### ISSUE THREAD

**Issue by kkniffin** [netdisco/netdisco#630]
Is there a way to expand the Vendor field to include the full name?

For example in my Reports, Node, Node Vendor Inventory I have things like IntelCor, MurataMa, LGElectr, BrocadeC. It seems that the fields are being cut off? Probably just a simple setting I need to change but couldn't find it in searching. If you could point me in the right direction I would appreciate it.

Reason for needing it is I have a couple devices that both start with American and they all show under the same Vendor even though they are not.
#

**Comment by ollyg** [comment]
Yes, I think the DB query should get the company field instead of the abbrev field, from the oui table.

**Comment by kkniffin** [comment]
Thanks for the feedback. I tried crafting a custom report for the interface using the configuration below but due to the overwhelming amount of nodes it takes forever and I have to tell chrome to wait about 10 times before it returns the results. 

Any ideas on a better way? Would love the ability to have it similar to the default Node Inventory report where you can click the Company name to drill down to the actual nodes,  but I did not see in the documentation a way to do that with the reports feature?

  - tag: node_company
    label: 'Node Company Inventory'
    columns:
      - {company: 'Company'}
      - {switch: 'Switch'}
      - {port: 'Port'}
      - {vlan: 'VLAN'}
    query: |
      SELECT n.switch, n.port, n.vlan, o.company
        FROM node n
        LEFT JOIN oui o USING (oui)
        WHERE n.oui != '' AND n.port NOT ILIKE '%Port-Channel%'
      ORDER by o.company

**Comment by ollyg** [comment]
Sorry I meant my comment as a note to devs that we need to change/fix the
built in report 😁

**Comment by inphobia** [comment]
seems mostly straightforward, but why do why have abbrev & fullname both anyway?

**Comment by ollyg** [comment]
thanks, fixed in [master 26dbb714] #630 display full oui vendor
