### ISSUE TITLE
Improve user management / configuring multiple users

### ISSUE THREAD

**Issue by RickdeJager** [netdisco/netdisco#638]
In the user management view, updating the settings for one user will reload the page causing other uncommitted settings to be lost.

## Expected Behavior
Saving should either not reload the view at all, or leave uncommitted settings for other users intact.
## Current Behavior
When the settings are updated for one user, all other unsaved settings are wiped.

## Possible Solution

Two possible improvements would be:  
1. Adding a "Save All" button  
2. Not reloading the view for user updates  
  
The second option can be achieved by not updating the User Management view if the action is save/update.  
  
Adding the following check in share/view/js/admintask.js stops the app from wiping user settings on save:  
```js
//[ . . . ]
// submit the query and put results into the tab pane
      $.ajax({
        type: 'POST'
        ,async: true
        ,dataType: 'html'
        ,url: uri_base + '/ajax/control/admin/' + tab + '/' + mode
        ,data: $(this).closest('tr').find('input[data-form="' + mode + '"]').serializeArray()
        ,beforeSend: function() {
           if (! (mode == 'update' && tab == 'users')) { { //Here
            $(target).html(
              '<div class="span2 alert">Request submitted...</div>'
            );
          }
        }
        ,success: function() {
           if (! (mode == 'update' && tab == 'users')) { { //And here
           $('#' + tab + '_form').trigger('submit');
          }
        }
//[ . . . ]
```
While this solves the issue, it's not very elegant which is why I'm opening an issue instead of a pull request. Maybe there is a better way to solve this?

## Steps to Reproduce (for bugs)

1. Add multiple users
2. Enable some feature for all of them (LDAP for example)
3. Pressing save on the first user will reset all of your settings for the other users.

## Context

I recently set up netdisco in an environment with multiple Sysadmins. I expected to be able to setup all users and save them, but saving the first user wiped all other uncommitted user settings.

## Your Environment

App::Netdisco   2.42.10
SNMP::Info   3.68

**Comment by inphobia** [comment]
i can reprocude this, but not sure if it's a feature or a bug. i do think a "save all" button/option would be welcome,  not just for users but also for pseudodev/manual topo/etc...

**Comment by RickdeJager** [comment]
Cool, I'll open a pull request for the save all button soon-ish

**Comment by ollyg** [comment]
thanks! I actually quite like the smarter approach showed in the patch, so I've implemented it in:
[master bb7801d5] #638 avoid page reload on admintask data updates

(with some toastr notifications)
