### ISSUE TITLE
No option to change vlan on access port

### ISSUE THREAD

**Issue by MickG72** [netdisco/netdisco#643]
HI,

Recently installed Netdisco and I am wrapped with how it works, especially with palo alto arp entries.
I have tested disabling and enabling ports and they work really well.
I was hoping to change a vlan a port, or in HP speak , change a ports untagged vlan.
But I don't see the option to do so in the GUI. 
Only port option I see are " bounce / disable" ports. This is ports tab for the device
How do I enable the vlan change ? 
Everything else is working great.

Running Ubuntu Server.
App::Netdisco | 2.42.10
SNMP::Info | 3.68
DB Schema | 58
PostgreSQL | 10.00.10
Perl | 5.26.1

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
Hi @MickG72 
Make sure the Native VLAN column is displayed, and then also the Port Controls are enabled in the sidebar (click Update if needed). Click into the Native VLAN column to change the number, when you press Enter to complete, you will be asked to confirm the change and give an optional reason.
Hope that helps!
Please reopen this ticket if you have trouble.
