### ISSUE TITLE
reports->device->device name / dns mismatches broken

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#644]
## Expected Behavior

reports->device->device name / dns mismatches should return dns mismatches

## Current Behavior

reports->device->device name / dns mismatches returns "Search failed! Please contact your site administrator."

and:
`[29573] 2019-09-03 23:19:48 error request to GET /ajax/content/report/devicednsmismatch crashed: DBIx::Class::Storage::DBI::_execute(): Cannot bind a reference at /home/testdisc/perl5/lib/perl5/App/Netdisco/Web/Plugin/Report/DeviceDnsMismatch.pm line 22`

## Steps to Reproduce (for bugs)

1. go to reports->device->device name / dns mismatches

## Your Environment

* Netdisco version used: 2.43.000
* SNMP::Info version used: head

## Config info (deployment.yml)

```
domain_suffix:
  - '.aquafinad.aquafin.be'
  - '.aquafin.be'
```

**Comment by ollyg** [comment]
thanks, fixed in
[master d8d2471c] #644 Device DNS Mismatch report broken by domain_suffix change

**Comment by inphobia** [comment]
yup, works like a charm! thx
