### ISSUE TITLE
Store i_speed_admin in database

### ISSUE THREAD

**Issue by rc9000** [netdisco/netdisco#650]
For many classes, SNMP::Info offers i_speed_admin which is the admin setting of the interface speed. Example (using Layer3::C6500::i_speed_admin):

     netdisco-do show -d xxx.yyy.203.143 -e i_speed_admin
    [24177] 2019-09-16 09:18:03  info App::Netdisco version 2.042010 loaded.
    [24177] 2019-09-16 09:18:04  info show: [xxx.yyy.203.143]/i_speed_admin started at Mon Sep 16 11:18:04 2019
     {
        ...,
        10121   "auto",
        10125   "auto",
        10126   "auto",
        10127   "auto",
        10128   "auto",
        10201   "10 Gbps",
        10202   "10 Gbps"
    }

Unfortunately this is not currently stored in Netdisco. Would you guys be open to adding it? And if yes, should we put it into DevicePort or DevicePortProperties?

Cheers
Christian

**Comment by ollyg** [comment]
This would be a very good candidate for DevicePortProperties. Patches
welcome :-)

**Comment by rc9000** [comment]
Ok great, I'll add that soon-ish.

**Comment by rc9000** [comment]
Here's a quick test with 100 random devices from our network, mostly Cisco with some ex-Alu and Checkpoint. Seems to work fine, coverage around 60%:

    select speed_admin, count(*) from device_port_properties 
    where ip in (select ip from device where last_discover > '2019-09-19 14:40'  ) 
    group by speed_admin order by 1;
    
     speed_admin | count 
    -------------+-------
     1.0 Gbps    |    86
     10 Gbps     |    94
     10 Mbps     |     6
     100 Mbps    |    19
     auto        |  2033
                 |  1369
