### ISSUE TITLE
Port list is not sorting numerically, filters don´t find port numbers

### ISSUE THREAD

**Issue by StraussJ11** [netdisco/netdisco#654]
## Expected Behavior

Netdisco sorts the list of device-ports numericalley, like: 1,2,3,4,5,6,7,8,9,10,11,.....
Also, Netdisco shows the port "X" when setting the filter to "X". 

## Current Behavior

When looking at the port-list of a device, the ports are sorted the following way: 1,10,11,12,13,14,15,16,17,18,19,2,20,.... 
Also, when setting the filter to port no. X, the list shows all ports that have VLAN X tagged (what is expected behaviour), but not Port no. X. 

## Context

This issue came up with the new update to version 2.44.0. 

## Your Environment

* Netdisco version used: 2.44.0
* SNMP::Info version used: 3.68
When upgrading, I followed the instructions found at https://metacpan.org/pod/App::Netdisco#Upgrading-from-2.x 

## Config info (deployment.yml)

After the update was finished, I wanted to try the new feature of adding multiple domain-suffixes. 
So my config changed from
domain_suffix: '.my.domain.com'
to 
domain_suffiix: 
  - '.my.domain.com'
  - '.my2nd.domain.com'
  - '.my3rd.domain.com'

## Device information

The issues applies to all devices.

**Comment by ollyg** [comment]
thank you for the bug report! I will take a look at this soon (yes, I can reproduce it)...

**Comment by ollyg** [comment]
Hi @StraussJ11 I have fixed this in release 2.044001 which has just gone to CPAN.
