### ISSUE TITLE
sorting os version strings (feature request)

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#657]
## Expected Behavior

it would be nice if os version strings on the inventory screen and/or the sidebar could be sorted naturally. ideally something like:

- example 1
  - 1.3.5.58
  - 1.4.1.3
  - 1.4.10.6
- example 2
  - 12.4(6)T10
  - 12.4(15)T10
  - 12.4(15)T12

inspired by recent #654

## Current Behavior

right now we seem to be sorting alphabetically

- example 1
  - 1.3.5.58
  - 1.4.10.6
  - 1.4.1.3
- example 2
  - 12.4(15)T10
  - 12.4(15)T12
  - 12.4(6)T10

## Possible Solution

postgres can handle this natively with the `string_to_array` and a construct like `ORDER BY string_to_array(version_string, '.', '')::int[]`.  this is only for strings containing only dots and numbers however.

as soon as letters or special characters need to be taken into account it gets complicated quick. thus far i've come up empty handed when trying to find something that can be implemented without using postgres extensions. (this seems to complicate things and make them less portable, feel free to correct me on irc if i'm mistaken on this).
one reference that was popular however was http://www.rhodiumtoad.org.uk/junk/naturalsort.sql , but it states being c locale only, while we use utf-8 for our db encodings.

## Context

it's mostly a nice to have thing (and pet peeve of mine), and seems to be more complex as i anticipated. perhaps someone alrdy tackled this in other projects or has a better idea of how to handle this.

## Your Environment

* Netdisco version used: 2.044001
* SNMP::Info version used: head

**Comment by rc9000** [comment]
Hi Nick

In similar situations, I have used the following regex method successfully:

1. Take the version string, and pad every number with a whole bunch of zeroes, let's say about 10. So 8 will turn into 00000000008 and 12 into 000000000012.
1. Now in the next step, make all the numbers the same length, let's say 5 rightmost digits. Now you have 00008 and 00012 which will correctly sort lexicographic.

This can all be done with regexp_replace in a normal query and is reasonably fast:


    with padded as ( select distinct os_ver , 
        regexp_replace(os_ver, '([\d]+)', E'0000000000\\1', 'g') as padded_ver from device )
    select os_ver, 
        regexp_replace(padded_ver, '[\d]+([\d]{5})', E'\\1', 'g') as sortable_ver, 
        padded_ver 
    from padded order by 2

The first column then looks like this for me:

    2.6.18-92cp / Net-SNMP 5.4.2.1
    2.6.18-92cpx86_64 / Net-SNMP 5.4.2.1
    03.04.01.SG
    03.07.04E
    5.2(1)N1(9)
    6.2(12)
    7.0(3)I5(2)
    7.0(3)I7(2)
    7.3(0)D1(1)
    8.0.115.0
    8.0.133.0
    12.0(5)WC3b
    12.1(22)EA3
    12.1(22)EA8a
    12.2(18)SXF6
    12.2(18)SXF8
    12.2(20)SE3
    12.2(25)S9
    12.2(25)SEB1
    12.2(35)SE1
    12.2(35)SE2
    12.2(40)
    12.2(44)SE2
    12.2(50)SE2
    12.2(55)SE1
    12.2(55)SE3
    12.2(55)SE5
    12.2(55)SE8
    12.2(58)SE2
    12.4(3)
    12.4(10)
    12.4(17)
    12.4(23)
    12.4(24)T5
    12.4(25a)
    14.1(1j)
    15.0(1)SE2
    15.0(2)EX4
    15.0(2)SE
    15.0(2)SE2
    15.0(2)SE4
    15.0(2)SE6
    15.1(4)M12a
    15.2(2)S
    15.2(3)E1
    15.2(4)E3
    15.2(4)M11
    15.2(4)S
    15.2(4)S5
    15.4(3)M3
    15.4(3)M6a
    15.5(1)S
    15.5(1)SY2
    15.5(3)S4a
    16.3.6
    16.3.8
    16.3.9
    16.6.4
    16.9.4
    B-10.0.R4
    B-16.0.R8
    C-16.0.R8

To make stuff faster and to not have this clunky query in a bunch of places, I could see a trigger just adding sortable_ver at discovery time.

Also work pretty well for interfaces if no ifindex is available to sort on.

**Comment by inphobia** [comment]
seems to be an interesting approach. it does require all versions strings to be somewhat the same format for a given os.

so oneaccess with their:
* 6.2.2m6
* 6.1.rc1patch06
* V5.2R1C12
need not apply 👋 

all kidding aside, i guess it's the job of snmp::info to provide somewhat consistent output for that. wonder how gnu sort does it, at least my version 8.29 has a -V option for version sorting, and does a decent job. adding to the above list with some made up things:
```
6.2.2m6
6.1.1.rc2patch04
6.2.2m7
V5.2R1C11
6.1.rc1patch06
V5.2R1C12
6.2.t4
```

produces:
```
6.1.rc1patch06
6.1.1.rc2patch04
6.2.t4
6.2.2m6
6.2.2m7
V5.2R1C11
V5.2R1C12
```

need to think about this some more...

**Comment by LBegnaud** [comment]
conceptually, the simplest way to sanely sort is to just split on every non-integer, then treat each group as a sub-version. Padding zeros into each of the sub-versions then doing lexicographic sort seems the simplest way to get things done at that point.

**Comment by ollyg** [comment]
If we are sorting in the web UI then it would be implemented in javascript as an add-on function, which is what we already do for port names (sortport, it is called). Is there another context where you'd like to sort the version?

**Comment by ollyg** [comment]
Oh I see yes, the list of OS versions in the sidebar would be sorted, I get you 👍

**Comment by ollyg** [comment]
I have started a branch, here https://github.com/netdisco/netdisco/pull/663

two thirds done, and remaining is the javascript column sorter
