### ISSUE TITLE
netdisco-db-deploy schema version error

### ISSUE THREAD

**Issue by jacobghattas** [netdisco/netdisco#658]
Greetings :) 
First thing first, let me Thank you for a great project and job done.

Netdisco-db-deploy give a version error... 
The output is here below :)

----------------------------
I also ran as per historical posts:
~netdisco/bin/netdisco-do psql
ALTER TABLE community RENAME COLUMN snmp_auth_tag TO snmp_auth_tag_read;[3306] 2019-10-04 13:41:23  info App::Netdisco version 2.044002 loaded.
[3306] 2019-10-04 13:41:23  info psql:  started at Fri Oct  4 16:41:23 2019
psql (9.2.24)
Type "help" for help.

netdisco=> ALTER TABLE community RENAME COLUMN snmp_auth_tag TO snmp_auth_tag_read;
ERROR:  column "snmp_auth_tag_read" of relation "community" already exists

----------------

[netdisco@netlogdbgsrv ~]$ ~netdisco/bin/netdisco-db-deploy --redeploy-all
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "dbix_class_schema_versions_pkey" for table "dbix_class_schema_versions"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (2) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (3) is lower than the schema version (60). Attempting upgrade.
NOTICE:  CREATE TABLE will create implicit sequence "user_log_entry_seq1" for serial column "user_log.entry"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (4) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (5) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (6) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (7) is lower than the schema version (60). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "node_pkey" for table "node"
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "node_wireless_pkey" for table "node_wireless"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (8) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (9) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (10) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (11) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (12) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (13) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (14) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (15) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (16) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (17) is lower than the schema version (60). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "admin_pkey" for table "admin"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (18) is lower than the schema version (60). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "node_pkey" for table "node"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (19) is lower than the schema version (60). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "node_wireless_pkey" for table "node_wireless"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (20) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (21) is lower than the schema version (60). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD UNIQUE will create implicit index "topology_dev1_port1" for table "topology"
NOTICE:  ALTER TABLE / ADD UNIQUE will create implicit index "topology_dev2_port2" for table "topology"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (22) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (23) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (24) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (25) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (26) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (27) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (28) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (29) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (30) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (31) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (32) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (33) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (34) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (35) is lower than the schema version (60). Attempting upgrade.
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "device_port_vlan_pkey" for table "device_port_vlan"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (36) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (37) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (38) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (39) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (40) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (41) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (42) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (43) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (44) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (45) is lower than the schema version (60). Attempting upgrade.
NOTICE:  CREATE TABLE will create implicit sequence "netmap_positions_id_seq1" for serial column "netmap_positions.id"
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (46) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (47) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (48) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (49) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (50) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (51) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (52) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (53) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (54) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (55) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (56) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (57) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (58) is lower than the schema version (60). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (59) is lower than the schema version (60). Attempting upgrade.

**Comment by LBegnaud** [comment]
not sure i see an error here. Looks like the schema upgrade did what it needed to?

**Comment by jacobghattas** [comment]
I havevno idea infact... But if i re-run it, i get the same output...

**Comment by jacobghattas** [comment]
I havevno idea infact... But if i re-run it, i get the same output...

**Comment by ollyg** [comment]
Hi @jacobghattas I cannot see the error either, in the output of netdisco-db-upgrade that you provide. So, I guess everything is OK? I will close this ticket. Please let us know if you think there is still a problem.

**Comment by inphobia** [comment]
side note: i do notice you are using postgres 9.2. we recently switched to 9.4 as minimum required version.

**Comment by jacobghattas** [comment]
Thank you Nick. will upgrade.
