### ISSUE TITLE
Can we speed up Macsuck::Nodes while using $snmp->cisco_comm_indexing?

### ISSUE THREAD

**Issue by rc9000** [netdisco/netdisco#659]
So in https://github.com/netdisco/snmp-info/pull/371, we propose to look at cisco_comm_index and not use Q-BRIDGE-MIB for community-indexed Cisco devices. Essentially:

    unless ($bridge->can('cisco_comm_indexing') && $bridge->cisco_comm_indexing()){
        my $qb = $bridge->qb_fw_port();
        return $qb if (ref {} eq ref $qb and scalar keys %$qb);
    }
    return $bridge->SUPER::fw_mac(); 

I did some testing with the code in this PR and noticed the following on e.g. Cisco 2911 and other devices that do not support Q-BRIDGE-MIB at all:

 * the first walk_fwtable will not try to call qb_fw_port, as expected
 * however then the snmp object gets reindexed to the found vlans/contexts, and in later evaluations of cisco_comm_indexing via Layer3::Cisco the code is ` my $vtp = $cisco->vtp_version() || '0'; return $vtp ? 1 : 0; `
 * however vtp_version on many IOS is only available in the default context, so eg. `snmpwalk -v2c -c topsecret@121 -On mydevice 1.3.6.1.4.1.9.9.46.1.1.1.0` will fail
 * as a result, subsequent walk_fwtable will still try to call qb_fw_port on the now no longer cisco_comm_index'ed object which produces a SNMP timeout, times the number of vlans
 * on devices with many vlans, this can delay macusck times by minutes

@ollyg / @JeroenvIS  and others, do you see any good way to fix this? Not quite sure if snmp-info or netdisco is the right place, somehow we'd need to preserve the default vlan vtp_version() response

**Comment by ollyg** [comment]
@rc9000 can you take a look at https://github.com/netdisco/netdisco/pull/661 ?

**Comment by rc9000** [comment]
Thanks @ollyg, I did some tests and this seems to work great. I've added an additional check before reading qb_fw_vlan in walk_fwtable (this will also fail whenever cisco_comm_indexing is active). Together with the snmp-info patch this seems to roughly double our macsuck throughput in our most Cisco-heavy network, check out the exciting new peaks in our Nagios perfdata :)

![scr 2019-10-13 at 18 48 29](https://user-images.githubusercontent.com/1247031/66718985-465ad980-edea-11e9-9582-e1827ca4ea35.png)

**Comment by ollyg** [comment]
awesome! 🌟

**Comment by rc9000** [comment]
It is! Thanks for your help, I imagined it to be way more complicated somehow :)

I have merged the branch and am closing this issue.
