### ISSUE TITLE
Rudimentary TACACS+ Authentication support

### ISSUE THREAD

**Issue by jpvelders** [netdisco/netdisco#660]
Similar to how Radius authentication is provided, I was hoping TACACS+ could be implemented; I was able to get stuff to work through Authen::TacacsPlus with the attached diff.

Perhaps this could be reworked and included into future versions ?

Limits of the diff:
* I manually added the "tacacs" column to the "users" table
* did not edit Build-files

Scenarios tested:
* Single TACACS+ server
* initial connection setup failure (TCP timeout or invalid key): user not authenticated
* Credentials valid: login success
* Credentials invalid: user not authenticated

[JPV-2.44-TACACS.patch.txt](https://github.com/netdisco/netdisco/files/3719327/JPV-2.44-TACACS.patch.txt)

**Comment by ollyg** [comment]
Thanks! I have created a branch with the patch, a few amendments (addressing your noted limitations), and this pull request:
https://github.com/netdisco/netdisco/pull/662

**Comment by jpvelders** [comment]
Cool, I will see if for a future update I can rework the check & config to support multiple servers. But for now this makes life a whole lot easier and gives Netdisco another plus for us. ;)
