### ISSUE TITLE
IP Inventory Report: Real Time Reverse DNS and columns

### ISSUE THREAD

**Issue by mkesoulis** [netdisco/netdisco#666]
1) It would be very useful if in IP Inventory Report (Sidebar) there was an option to perform real time reverse DNS lookup (DNS column) of the IPs in IP Address Column.
The way netdisco 2 works is to fetch DNS Names from the database but this is not the best choice in some situations. I think in netdisco 1 there was such an option.
For example, when a device/node is not discoverable by netdisco, even though it has a DNS name, this name would never show up in IP Inventory Report Table (List IPs Never Seen). Also, if we perform massive changes in DNS names of our devices this info will delay to show up in netdisco 2 and causes confusion.

2) It would very useful if in IP Inventory Report we had the option to select some more columns or deselect some of them. For example we could select to appear the columns "Time First Seen" and "Time Last Seen" and NOT only "Last Used".

**Comment by ollyg** [comment]
Hi @mkesoulis thanks for the suggestions! Very good ones.

On the topic of real-time DNS, yes ND1 did work like that and the dominant feedback was that it made web render too slow, as it had to wait to resolve potentially hundreds of addresses to show the page. However, I take your point, it could be useful. We could make it optional, and we do also have a much faster resolver now in ND2.

**Comment by ollyg** [comment]
I've added this to the wishlist page: https://github.com/netdisco/netdisco/wiki/Wishlist
