### ISSUE TITLE
db error during upgrade to 2.044003

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#668]
due to unforseen & unrelated issues i regretfully lost the exact log message, but i think i pieced enough of it back together to make a usefull report.

action: i upgraded from 2.044001 to 2.044003, using the cpan instructions. after running through them i reviewed my logs, and noticed 3 errors. as stated, i don't have the exact error message, but it was something about not being able to update something undefined.

now for the somewhat less vague info.
i'm 100% certain that the error message pointed to line 236 of the following file:
https://github.com/netdisco/netdisco/blob/0e8f9ad19473ea576913dbd995a0adefbf30fb1c/lib/App/Netdisco/JobQueue/PostgreSQL.pm#L235-L239

this is part of jq_defer().

the error was repeated 3 times, and strangly enough i also have 3 devices which are somehow queued for reasons unknown (screenshot from web jobqueue):
![image](https://user-images.githubusercontent.com/39005454/67732799-d5780c00-f9fc-11e9-9ec7-77d9e055dadf.png)
i have no idea why these devices are even in the queue since they also have reached their max snmp failures:
![image](https://user-images.githubusercontent.com/39005454/67733725-72d43f80-f9ff-11e9-91b2-cac3f063bcaa.png)

after doing some searching this seems the same as something i saw last year:
https://github.com/netdisco/netdisco/issues/445#issuecomment-442272623

> [3960] 2018-11-26 22:31:51 error bless( {'msg' => '{UNKNOWN}: Can't call method "update" on an undefined value at /home/testdisc/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 223, <ANONIO> line 1. at /home/testdisc/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 226'}, 'DBIx::Class::Exception' )

when looking at JobQueue/PostgreSQL.pm from 2018-11-26 it matches the same part of the code:
https://github.com/netdisco/netdisco/blob/ea592c6b28a1ae83686a99a1d55801fb01cfc949/lib/App/Netdisco/JobQueue/PostgreSQL.pm#L222-L225

thing is, i can't reproduce this. restarting, running netdisco-deploy again, the error no longer shows up. it also doesn't seem to cause any issues at first glance, other than those 3 devices that don't want to get dequeued.

as reported in #445 we do still see idiotoc high runtimes which i can't explain:
![image](https://user-images.githubusercontent.com/39005454/67733273-35bb7d80-f9fe-11e9-89e4-cf0716fabebb.png)

#466 could also be related, since also there i saw both job runtimes of over 2 days and things not being deferred.

**Comment by inphobia** [comment]
perhaps some relevant database output. i took 10.104.50.3 as testcase:

`SELECT * FROM public.device_skip WHERE device = '10.104.50.3'`


"backend"|"device"|"actionset"|"deferrals"|"last_defer"
----------|--------|-----------|----------|------------
"linux002.aquafin.be"|"10.104.50.3"|"{arpnip,macsuck,nbtstat}"|"10"|"2019-10-29 02:25:04.540239"


`SELECT * FROM public.admin WHERE device = '10.104.50.3' ORDER BY job DESC`

"job"|"entered"|"started"|"finished"|"device"|"port"|"action"|"subaction"|"status"|"username"|"userip"|"log"|"debug"|"device_key"
-----|---------|---------|----------|--------|------|--------|-----------|--------|----------|--------|-----|-------|------------
"4830129"|"2019-10-29 03:13:18.614235"|||"10.104.50.3"||"discover"|"with-nodes"|"queued"|||||"aquafi-antw06-10"
"4829217"|"2019-10-29 02:08:47.595291"|||"10.104.50.3"||"discover"|"with-nodes"|"queued"|||||"aquafi-antw06-10"
"4825148"|"2019-10-28 23:08:59.246452"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4824238"|"2019-10-28 21:18:02.941953"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4821794"|"2019-10-28 19:09:41.042573"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4819361"|"2019-10-28 15:06:59.100858"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4816915"|"2019-10-28 11:09:22.13533"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4814467"|"2019-10-28 07:11:03.586787"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4812012"|"2019-10-28 03:10:02.752269"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4809550"|"2019-10-27 23:09:23.328067"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4807092"|"2019-10-27 19:07:45.573633"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4804636"|"2019-10-27 15:10:46.690102"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4802181"|"2019-10-27 11:08:55.395472"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4799725"|"2019-10-27 07:12:40.991663"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4797268"|"2019-10-27 03:07:12.586893"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4794796"|"2019-10-26 23:10:51.4647"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4792340"|"2019-10-26 19:11:41.718692"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4789880"|"2019-10-26 15:07:40.450585"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4787422"|"2019-10-26 11:11:54.786873"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4784963"|"2019-10-26 07:11:13.534499"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4825148"||"aquafi-antw06-10"
"4782503"|"2019-10-26 03:11:23.205304"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4780037"|"2019-10-25 23:11:14.336828"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4777579"|"2019-10-25 19:10:46.832623"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4775116"|"2019-10-25 15:06:42.81123"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4772659"|"2019-10-25 11:13:46.507339"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4770200"|"2019-10-25 07:07:53.813737"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4767752"|"2019-10-25 03:12:30.025971"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4765299"|"2019-10-24 23:09:08.804364"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4762849"|"2019-10-24 19:08:07.889896"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4760397"|"2019-10-24 15:08:42.114865"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4757944"|"2019-10-24 11:12:55.996216"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4755492"|"2019-10-24 07:11:34.534413"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"
"4753041"|"2019-10-24 03:12:32.143944"|||"10.104.50.3"||"discover"|"with-nodes"|"error"|||"duplicate of 4784963"||"aquafi-antw06-10"

## 2 remarks
* device_skip says nbtstat is skipped, however we have both "nbtstat_no: "any"" in our config and the schedule for nbtwalk is set to null, so i wonder how it got in there in the first place
* if you look at the top 2 lines of the admin table the device is queued twice, is that normal?

**Comment by ollyg** [comment]
yes, this happens from time to time, and is a subtle race condition, but I think fairly harmless (the job quitting means it either restarts or is replaced in due course)
