### ISSUE TITLE
devices_only setting can cause infinite queue

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#672]
## Expected Behavior

devices which are known but not allowed due to acl settings should not be able to queue any action.

## Current Behavior

if known devices somehow become excluded from all actions, bulk actions will still be queued for them once. single actions (arpnic, macwalk) can be queued ad infinitum via the web interface.

i have not yet had the chance to see if `expire_jobs` or `jobs_stale_after` somehow affect this.

## Possible Solution

checking acl's before even queuing an action?

## Steps to Reproduce (for bugs)

1. firstly, use `devices_only` setting. add several devices
```yaml
devices_only:
  - 10.40.254.12
  - 10.40.254.16
  - 10.40.254.26
  - 10.40.254.35
  - 10.40.254.40
  - 10.40.254.41
  - 10.40.254.42
  - 10.40.254.64
  - 10.40.254.65
  - 10.40.254.112
  - 10.40.254.150
  - 10.40.252.19
  - 10.40.252.25
  - 10.40.252.26
  - 10.40.252.36
  - 10.40.252.38
  - 10.45.12.250
  - 10.45.12.251
  - 10.6.10.3
  - 10.50.102.1
```
2. run a discovery on all those devices
3. remove devices from the list:
```yaml
devices_only:
#  - 10.40.254.12
#  - 10.40.254.16
#  - 10.40.254.26
#  - 10.40.254.35
#  - 10.40.254.40
#  - 10.40.254.41
#  - 10.40.254.42
#  - 10.40.254.64
#  - 10.40.254.65
#  - 10.40.254.112
#  - 10.40.254.150
#  - 10.40.252.19
#  - 10.40.252.25
#  - 10.40.252.26
#  - 10.40.252.36
#  - 10.40.252.38
#  - 10.45.12.250
#  - 10.45.12.251
  - 10.6.10.3
#  - 10.50.102.1
```
4. run discover all in the webinterface, notice how the devices you no longer allow still get queued, but the queued actions never run.
![image](https://user-images.githubusercontent.com/39005454/67900217-4c7be480-fb64-11e9-9077-3f72e1ca2b65.png)
5. arpwalk & macwalk have the same issue
6. any device+action combo will only be queued once by bulk actions, so this will not lead to an explosion of queued tasks (if an arpnip is scheduled for a device, no second arpnip will be queued when running the next arpwalk).
7. however! if you use the web interface arpnip etc option even more actions will be queued and never run.
![image](https://user-images.githubusercontent.com/39005454/67900161-25251780-fb64-11e9-9fdf-df23fdf11f58.png)

the devices will get added to device_skip for all actions but defer count will always remain 0:
![image](https://user-images.githubusercontent.com/39005454/67900488-dc219300-fb64-11e9-8817-4b686b3b8903.png)

since the jobs aren't run they will also not get any snmp_connect_failures.

unlike #669 restarting netdisco does not fix this, the actions will remain queued.

## Context

i noticed this on my test setup where i don't want netdisco going around trying to discover everything and add/remove devices when relevant for testing. i don't think this will often be seen in production usage. 

## Your Environment

* Netdisco version used: 2.044004
* SNMP::Info version used: 3.70

## Config info (deployment.yml)

other as `devices_only` mentioned i have not done any other tests yet which can exclude devices from running actions. settings like, arpwalk_only, macsuck_no, devices_no.

**Comment by inphobia** [comment]
side note:
after readding those device again to `devices_only` and restarting netdisco most queued jobs will get run and device_skip will be clean again:
![image](https://user-images.githubusercontent.com/39005454/67902118-b9917900-fb68-11e9-813a-899870c38c65.png)

as you might notice, 2 devices still have arpnip excluded and their jobs still remain in the queue:
![image](https://user-images.githubusercontent.com/39005454/67902181-e6de2700-fb68-11e9-99f3-ba6a268b53d1.png)

#673 for that.

**Comment by pyro3d** [comment]
What I believe is happening here is that at startup, the devices **not** in `devices_only` are added to the `device_skip` here: 

https://github.com/netdisco/netdisco/blob/b211c7c7e20c812319f407f348eeb044297c54eb/lib/App/Netdisco/JobQueue/PostgreSQL.pm#L76

From there, a similar issue to #669 happens, where the job is enqueued, either directly, or through a *all job (this occurs with discover, macwalk, arpnip, and nbtstat jobs), but because it also exists in `device_skip` it is ignored when new jobs are polled. 

Best fix here I think would be to refuse to enqueue invalid jobs, which obviously isn't happening.

**Comment by ollyg** [comment]
Nice idea but doesn't work with multiple backend pollers with different config. The queue action is not aware of the ACLs on the different backends.

I suppose something smart could be that all backends registered (which can be inferred from `device_skip` column) could be checked and then queue is skipped.

However, the principle is that the ACL is local to the backend poller, so the queue action has been designed to be dumb and then the poller is selecting jobs it can do, and the rest are cleaned up by the `expire` job.

**Comment by inphobia** [comment]
> Nice idea but doesn't work with multiple backend pollers with different config. The queue action is not aware of the ACLs on the different backends.

right, didn't take take into consideration. tbh haven't run a multiple poller config.

perhaps a master config that say `nbtstat_no: "any"` could disallow these jobs running on any poller, but it seems this bug report is actually working as designed.

**Comment by ollyg** [comment]
setting `nbtwalk: null` in your `schedule` config will turn off nbtstat.
