### ISSUE TITLE
can queue arpnip on non layer2 devices

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#673]
i'll keep this one brief:

if you have a layer2 device (like a ciscosb switch):
![image](https://user-images.githubusercontent.com/39005454/67902658-f9a52b80-fb69-11e9-9c2e-809142069918.png)

and click arpnip in the web interface, netdisco will in fact queue an arpnip job for this which will not get run:
![image](https://user-images.githubusercontent.com/39005454/67902689-0d509200-fb6a-11e9-9797-43fee6374d78.png)

the arpnip action will get added to device_skip, but never deferred:
![image](https://user-images.githubusercontent.com/39005454/67902752-383ae600-fb6a-11e9-9d85-67b1f8787743.png)

could be related to #672 since i noticed it after enabling my devices again.

## solution
don't do dumb stuff [😁 

## Your Environment

* Netdisco version used: 2.044004
* SNMP::Info version used: 3.70

**Comment by inphobia** [comment]
this might also be the result of the state my database was in after all testing, i'll check in depth in a few days.

**Comment by ollyg** [comment]
in any case the UI button should be greyed out when no matching layer

**Comment by inphobia** [comment]
> in any case the UI button should be greyed out when no matching layer

now that we have l3 for pseudo this could be an interesting feature.

**Comment by ollyg** [comment]
thanks! UI fixed in
[master 17da397c] #673 disallow clicking arpnip/macsuck buttons for devices not supporting those layers
