### ISSUE TITLE
skipped actions should have their own status

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#675]
as discussed on irc, if an action is skipped or disallowed it should have it's own status instead of "Done".

steps to reproduce:
config -> nbtstat_no: "any"
click nbtstat on any device in the webinterface
check jobqueue, job says "Done" while it wasn't allowed to run.

**Comment by ollyg** [comment]
Ah, this is a common misunderstanding about what `nbtstat_no` does.

`nbtstat` is run against Nodes, as it's looking for the windows system name of the end station. the list of Nodes is taken from the ones in the `NodeIp` table connected to a Device. the `nbtstat_no` setting only refers to the Nodes, not the Device.

Weirdly the only way to suppress `nbtstat` is to use the `macsuck_no` setting. Suggestions welcome as to how to do this better (but this design dates back to Netdisco 1).

**Comment by ollyg** [comment]
Oh, the general principle of the title of this issue is still sound, though, so it can stay open.

**Comment by inphobia** [comment]
ofcourse i didn't take into account the multiple backend option:
https://github.com/netdisco/netdisco/issues/672#issuecomment-548503411

this complicated the request, but in general the `skipped actions should have their own status` question still remains open, just a lot harder will multiple pollers.

**Comment by ollyg** [comment]
I actually don't think this is possible with multiple pollers. all that happens is that a poller skips tasks it cannot do, but leaves them for other pollers which may be running. so the job has to stay in the queue and the device_skip table is suppressing it from being selected by a poller.
