### ISSUE TITLE
Add href link to a device in a report

### ISSUE THREAD

**Issue by SharonYeuda** [netdisco/netdisco#681]
Hi,

How can add an href link to device when creating a report at deployment.yml?

Here is my report test
reports:
  - tag: power_inventory_test
    label: 'Power Supply Inventory Testing'
    category: Device
    columns:
      - {name: 'Name'}
      - {ip: 'IP'}
      - {ps1_type: 'PS1 Type'}
      - {ps1_status: 'PS1 Status'}
      - {ps2_type: 'PS2 Type'}
      - {ps2_status: 'PS2 Status'}
    query: |
      SELECT d.name,d.ip, d.ps1_type, d.ps1_status, d.ps2_type, d.ps2_status
        FROM device d
      ORDER BY name

**Comment by SharonYeuda** [comment]
Can someone help me with this?

**Comment by rc9000** [comment]
AFAICT this is currently not possible with just a `reports:` entry, but you can do it by overriding the generic_report HTML template. Here's a quick example:


In deplyoment.yml, enable site_local_files and put the value you need to create the link into e.g. the "lnk" column:

    site_local_files: true
    reports:
      - tag: power_inventory
        label: 'Test Href'
        category: Device
        columns:
          - {name: 'Name'}
          - {lnk: 'Link to somewhere'}
          - {ps1_type: 'PS1 Type'}
          - {ps1_status: 'PS1 Status'}
        query: |
          SELECT d.name, d.ps1_type, d.ps1_status, d.ip as lnk
            FROM device d
          ORDER BY name limit 10

Now create a file called `generic_report.tt` in `$NETDISCO_HOME/nd-site-local/share/views/ajax/report` with this content:

    <table id="rg-data-table" class="table table-bordered table-condensed table-striped" width="100%" cellspacing="0">
      <thead>
        <tr>
          [% FOREACH hdr IN headings %]
            <th>[% hdr | html_entity %]</th>
          [% END %]
        </tr>
      </thead>
      <tbody>
        [% FOREACH row IN results %]
        <tr>
          [% FOREACH col IN columns %]
            [% IF col == "lnk" %]
            <td><a href="http://whatever.com?ip=[% row.item(col) %]">link</a></td>
            [% ELSE %]
            <td>[% row.item(col) %] | html_entity </td>
            [% END %]
          [% END %]
        </tr>
        [% END %]
      </tbody>
    </table>
    
    <script>
    $(document).ready(function() {
      $('#rg-data-table').dataTable({
        "order": [],
    [% INCLUDE 'ajax/datatabledefaults.tt' -%]
      } );
    } );
    </script>

Then restart the netdisco-web process just to be sure, and that should be it. Just note that this template is used for all reports defined that way, so if you need a second link make sure to use a new column name, and don't use "lnk" as column name for other stuff that is not supposed to be a link. Hope that helps!

**Comment by rc9000** [comment]
BTW alternatively you can also create a full custom report in which you can specify the whole HTML individually. That might be better if you have a large amount of links in different reports, or if you don't want to lose updates to the generic_report.tt file that might come with new versions of Netdisco. This is described here: https://github.com/netdisco/netdisco/wiki/Web-Plugins

**Comment by ollyg** [comment]
thanks @SharonYeuda for the suggestion!
I have implemented a feature where you can specify a column is searchable (so will work for device names, IPs, MAC, etc) by adding a `_searchable: true` hint to the `columns` config. It will be in the next release of netdisco.

[master 4268fff7] #681 Add href link to a device in a report
