### ISSUE TITLE
Github sponsors

### ISSUE THREAD

**Issue by djzort** [netdisco/netdisco#682]
Just a suggestion to check out the Github Sponsors program

https://github.com/sponsors

it is what it is, but could be a way to help people contribute

**Comment by inphobia** [comment]
cool idea, but for me personally time is the biggest issue. :(

**Comment by ollyg** [comment]
I have applied to the waiting list, thanks @djzort

**Comment by ollyg** [comment]
(oh, and the project doesn't have a bank account so I didn't apply for Netdisco project to join)
