### ISSUE TITLE
Map links colored by link speed

### ISSUE THREAD

**Issue by DerPhlipsi** [netdisco/netdisco#683]
## Expected Behavior

There should be an option to display the link speed on a map either as a label on the line or as the line's color with a second legend in the bottom right of the canvas. E.g. a 100M link is dark red, a 1G link is black, a 10G link is dark green and for every iteration upward the green gets brighter. Also, the cable type could be indicated by different colored endings of the line (e.g. black = copper, blue = SX-fiber, etc.).

## Current Behavior

Currently, the link speed is only shown as a label.

## Possible Solution

I can remember to have read somewhere that the graphing system should be reworked, so this would probably a task to append to that list.

## Context

Our infrastructure is huge. Making maps of a single location already requires a lot of space, so the map will have to be zommed into and panned, because text is not readable when the entire externd is shown. Displaying the link speed as labels would make the maps even larger and bulkier.

**Comment by ollyg** [comment]
Hi @DerPhlipsi thanks for the good suggestion!

Couple of points to note:
- links are actually total of all bandwidth between devices, not the link speed, so if you have 4x1G connecting two devices it will show as 4G, so there may be many more colours than just the 1,10,25,100 etc...
- also, are you using the host_groups and host_group_displaynames features? they can help a lot with large topologies to focus on what you want to see.

**Comment by DerPhlipsi** [comment]
Hi @ollyg,

> links are actually total of all bandwidth between devices, not the link speed, so if you have 4x1G connecting two devices it will show as 4G, so there may be many more colours than just the 1,10,25,100 etc...

I know. 😄 I gave the example with 10G, this does not mean it should only apply to that. Ofc this is also applicable to multiple 1G or even 100G links (we have some 2x/4x 100G LACP-Channels). It was just as an example, since it simplifies implementation. Have one color per "speed-class" and use the brightness-channel of the color as indicator for bonds/channels. Sorry for being imprecise with my description. ^^

> also, are you using the host_groups and host_group_displaynames features? they can help a lot with large topologies to focus on what you want to see.

Yes, plenty of them. Every site has one, if applicable every building of a site, every datacenter and even every fire protection section of a data center has its own `host_group` and a corresponding name mapping in `host_group_displaynames`. There are actually so many groups, that going through the list in the map UI is a bit tedious. We already thought about running multiple instances of the WebUI, each for a different geographical region with the appropriate groups because of that. (Might be another feature-request: search function in the hosts groups list.)
But the problem is, for most troubleshooting we need the entire site's view, since in most cases the person on location is not tech-savy or has no access to tech-rooms, so we have to use clues of the building structure instead of simply being told an IP-address. Or, for example, we have multiple interconnects, where having a site-global view is necessary to see where a spanning-tree-loop could be coming from.

**Comment by inphobia** [comment]
> I can remember to have read somewhere that the graphing system should be reworked, so this would probably a task to append to that list.

you might be referring to this: https://github.com/netdisco/netdisco/projects/5 , which is about moving us to graphviz2. online graphs, which use d3 js, could also use some love. 

i do like the idea of being able to customize:
> E.g. a 100M link is dark red, a 1G link is black, a 10G link is dark green and for every iteration upward the green gets brighter. Also, the cable type could be indicated by different colored endings of the line (e.g. black = copper, blue = SX-fiber, etc.).

so i added it to the the wishlist for graphviz2, but i don't think i'll be able to work on that any time soon...

**Comment by ollyg** [comment]
I don't think the current component we use for the graph can display two legends. So the colours might just be assigned and not labelled (I think device throughput coloring does this already?).

**Comment by ollyg** [comment]
I've added this to the wishlist page: https://github.com/netdisco/netdisco/wiki/Wishlist
