### ISSUE TITLE
Add an option to set main page after logging in

### ISSUE THREAD

**Issue by Rei-Tw** [netdisco/netdisco#687]
Hi,

We actually wanted to redirect the user to the main page instead of `http://netdisco/inventory`.
It could be good if an option is available for changing the current main page after pressing the login button.

**Comment by ollyg** [comment]
thanks @Rei-Tw for the suggestion
I have implemented the web_home config setting which will be in the next release
set it to "/" to have the effect you want.

[master 4030000b] #687 Add an option to set main page after logging in
