### ISSUE TITLE
help reset admin pw

### ISSUE THREAD

**Issue by hrv231** [netdisco/netdisco#689]
## Current Behavior

Made a mistake and changed the admin password of my netdisco system, but my password manager didn't save the password, so now I'm stuck.
Any way to reset that admin password?

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by rc9000** [comment]
Hi!

You can run:

    netdisco-do psql

then in there set a new password with

    update users set password = '{CRYPT}$2a$07$87FxdepCoGzQOp7O44vsN.51pFxcReasgcAPP4I8qjSyVSr5iMU2C' where username = 'admin';

The shown value is **foo**. To generate another, you can use http://www.passwordtool.hu/blowfish-password-hash-generator or more trustworthy local variants like htpasswd - just make sure you create a /etc/shadow-style blowfish password (type 2a, as indicated between $$) and add the {CRYPT} string.

**Comment by ollyg** [comment]
Hi @hrv231 there's another option:

````
netdisco-do psql -e 'delete from user where admin'
````

then re-run `netdisco-deploy`. It will prompt for new admin account creds.

**Comment by inphobia** [comment]
> `netdisco-do psql -e 'delete from user where admin'`

slight correction (table is "users, not "user"):
`netdisco-do psql -e 'delete from users where admin'`
