### ISSUE TITLE
discovery all - only mac addresses for nodes no ip adresses

### ISSUE THREAD

**Issue by josefstr** [netdisco/netdisco#691]
When I run discovery all and later Arpwalk, netdisco seems to find devices and nodes.
It only displays the mac address to a node an on which port on the switch the node is connected. It never displays any IP address.

Match | Device or Node | First Seen | Last Seen
-- | -- | -- | --
MAC: f8:b1:56:xx:xx:xx
Switch Port | 192.50.50.50 - C1             on vlan 50 | 2020-01-02 11:49 | 2020-01-02 13:20

```
Built using Open Source
Software 	Version
App::Netdisco 	2.44.4
SNMP::Info 	3.70
DB Schema 	61
PostgreSQL 	10.00.10
Perl 	5.26.1
```

```
Statistics for this installation
20 devices with 10 IPs
300 interfaces of which 100 are up
11 layer 2 links between devices
50 nodes logged, of which 30 are active
0 IPs logged, of which 0 are active
Statistics last generated on 2020-01-02
```

Any idea how I can get the ip addresses from all the mac addresses?

**Comment by ollyg** [comment]
Hi @josefstr it seems that Netdisco is not collecting ARP table data from a device.

Have you pointed Netdisco at the device which is the router or gateway for your network? It is the one that has the mapping of IP to MAC and then Netdisco can stitch that to the MAC tables from the switches.

If you've already done this, then it might be a router platform which is not supporting SNMP fully or has a strange implementation. We have an SSH based system for working around this, which covers these platforms:
App::Netdisco::SSHCollector::Platform::ACE
App::Netdisco::SSHCollector::Platform::ASA
App::Netdisco::SSHCollector::Platform::BigIP
App::Netdisco::SSHCollector::Platform::CPVSX
App::Netdisco::SSHCollector::Platform::FreeBSD
App::Netdisco::SSHCollector::Platform::GAIAEmbedded
App::Netdisco::SSHCollector::Platform::IOS
App::Netdisco::SSHCollector::Platform::IOSXR
App::Netdisco::SSHCollector::Platform::Linux
App::Netdisco::SSHCollector::Platform::NXOS
App::Netdisco::SSHCollector::Platform::PaloAlto

Let me know if it's one of them
