### ISSUE TITLE
Netdisco install script for Ubuntu 18.04 server

### ISSUE THREAD

**Issue by bvirgin-solidifydb** [netdisco/netdisco#692]
I am not sure where to post this script so I am trying this location. I am not a programmer so the script is not elegant but it seems to work well.

The script is designed to install Netdisco on a fresh install of Ubuntu 18.04 server.

It is designed to be used by network engineers who are not that familiar with Linux.

I have tested it on a VM running Ubuntu 18.04 server with the nic in bridge mode (I have not tested nat.

In order for the script to work, your VM must be able to reach the internet and the routers/network devices that you want to discover.

After you first install Ubuntu 18.04 server, it will automatically begin the upgrade/update process. This must be complete or the script will fail.

If you receive an error similar to below, the upgrade process is not complete.
"Started Daily apt download activities."
Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)

You will need the SNMP RO for your devices and (optionally) the domain suffix for your network.

1.) ssh to IP address of the VM where you are going to install the script so that you can use copy and paste.

Do the following:

2.) sudo su root
3.) curl -O https://raw.githubusercontent.com/netdisco/upstream-sources/master/contrib/ubuntu-install-script-692/netdisco_install_script.sh
4) chmod +x ./netdisco_install_script.sh
5.) ./netdisco_install_script.sh

[netdiscoInstallScript.txt](https://github.com/netdisco/netdisco/files/4050276/netdiscoInstallScript.txt)

**Comment by ollyg** [comment]
I have uploaded the script here:
https://raw.githubusercontent.com/netdisco/upstream-sources/master/contrib/ubuntu-install-script-692/netdisco_install_script.sh

**Comment by ollyg** [comment]
Thanks, I have updated our install guide to link to this:
https://github.com/netdisco/netdisco/wiki/Install-Tips#easy-install-script-on-ubuntu
