### ISSUE TITLE
JS TypeError vlan search view

### ISSUE THREAD

**Issue by fkaempfer** [netdisco/netdisco#696]
I'm not sure what the reason behind is, but in my fresh installation with a couple of devices with VLAN in it, the VLAN search view (/search?tab=vlan&q=MyVLAN) causes a JS TypeError on load causing the datatable to be stuck on "Processing".

A bit of debugging shows that it is caused by the pcount column which does not exist in the result set (thus is undefined): toString() called on undefined data. As a workaround I changed share/views/ajax/search/vlan.tt line 39 data.toString() to (data || '?').toString()

Probably it would be best to make sure the pcount column is returned in lib/App/Netdisco/Web/Plugin/Search/VLAN.pm but as I said I do not know what is supposed to be returned here or what causes it to be missing.

**Comment by ollyg** [comment]
Hi @fkaempfer thanks for the bug report! Actually this was caused by adding a feature in the previous release but not taking enough care. Sorry about that. I have fixed and issued a new version of Netdisco.

[master db6e8960] #696 complete implementation of #688

**Comment by fkaempfer** [comment]
Thanks, it's working fine with the latest release.

**Comment by ollyg** [comment]
super, thanks for the confirmation!
