### ISSUE TITLE
Wishlist - using Host Groups to do discovery, run reports and better way to access Maps

### ISSUE THREAD

**Issue by hrv231** [netdisco/netdisco#697]
## Expected Behavior

_Run Discover:_
Hello, I use netdisco extensible, most part of my use is to create maps, and to use the maps option.

I have manually configured different Host Groups per the documentation, but sometimes netdisco stop discovering some of my networks and that's when I have to go and do copy-and-paste for each of my network subnets, go to the main page and click over Discover.

It would be useful to have a way to choose a Host Group, and then do a discovery on all the networks under that Host Group.

_Also.. a better way to go to the maps [Neighbors]:_
Every time I go to view my neighbors on an specific Host Group, I have to at least type the name of one of the switches on the search bar, click over it and go to the neighbors of that switch, then choose my Host Group, click all-devices and view my full map of neighbors for that Host Group.

Would be great have a better way to access these neighbors maps instead of doing that.

_Reports:_
I wanted a report the other day based on the Host Groups, since the host groups have their networks [generally each group have more than one], I wanted to have a list of all devices based on each Host Group.
There is no way to do that.

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
Agreed, but there are challenges to using "only" in the "schedule" config. These are good suggestions added to the wishlist page https://github.com/netdisco/netdisco/wiki/Wishlist

**Comment by ollyg** [comment]
ACLs in schedule are now supported https://github.com/netdisco/netdisco/wiki/Configuration#schedule
