### ISSUE TITLE
Wishlist - Report of "slower" ports..

### ISSUE THREAD

**Issue by mirktmirkt** [netdisco/netdisco#698]
It would be really nice having a report of ports running at slower speed that they are capable/configured, for example, if switch port is capable/configured 1Gbps but is running at 100Mbps – there might be some kind of issue there..

Our "nodes" are mainly workstations and I have noticed that in sleep/hibernate mode they (might) drop to 10 Mbps, so possibility to filter by speed would be really useful..

I do have a little python script which generates a list of "slow ports" from netdisco DB for me, but it would be really to have a built in report. Would it be useful to others?

**Comment by ollyg** [comment]
Hi @mirktmirkt have you looked at the custom reports feature already?

Yes it would be good to include this in Netdisco. If you work out the SQL query then it will probably happen soon :-)

For example, the following config in your `deployment.yml` file will add a report on port speeds:

````
reports:
  - tag: port_speeds
    label: 'Port Speeds'
    columns:
      - {total: 'Count'}
      - {speed: 'Speed'}
    query: |
      SELECT count(*) AS total, speed
        FROM device_port
        WHERE up = 'up'
      GROUP BY speed
      ORDER BY total
````

Further config guidance here: https://github.com/netdisco/netdisco/wiki/Configuration#reports

**Comment by ollyg** [comment]
I guess you can compare the `speed` to `speed_admin` columns.

**Comment by mirktmirkt** [comment]
> Hi @mirktmirkt have you looked at the custom reports feature already?

No, I haven't :) Thank you, I will try to do it :) (and come back here then..)

**Comment by inphobia** [comment]
> I guess you can compare the `speed` to `speed_admin` columns.

not sure about this, i hope speed_admin is set to `auto`, and for several of my devices it's just set to null. matching it against the actual hardware from device_module is better i think, but also a much more complicated query.

or if you want it quick & dirty match against interface name/description. most, but certainly not all, switches indicate their speed in the port name.

**Comment by ollyg** [comment]
we store the raw number that the speed is running at in device_port_properties, but I don't think we store the admin in a friendlier way, so it would not be any easier

I was imaging a pretty dumb 1G vs. 100M compare, is all
