### ISSUE TITLE
Centos 8 Install fails

### ISSUE THREAD

**Issue by tpolim008** [netdisco/netdisco#701]
Recently got a new server running centos8 and trying to get netdisco running int falling the install https://metacpan.org/pod/App::Netdisco when getting to the point to install snmp::info it finds the dependency and then fails at the install.

`[root@netengsrv01 ~]# su netdisco
[netdisco@netengsrv01 root]$ cd
[netdisco@netengsrv01 ~]$ curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  295k  100  295k    0     0   950k      0 --:--:-- --:--:-- --:--:--  950k
--> Working on App::Netdisco
Fetching http://www.cpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.044015.tar.gz ... OK
Configuring App-Netdisco-2.044015 ... OK
==> Found dependencies: SNMP::Info
--> Working on SNMP::Info
Fetching http://www.cpan.org/authors/id/O/OL/OLIVER/SNMP-Info-3.70.tar.gz ... OK
Configuring SNMP-Info-3.70 ... OK
==> Found dependencies: SNMP
--> Working on SNMP
Fetching http://www.cpan.org/authors/id/H/HA/HARDAKER/SNMP-5.0404.tar.gz ... OK
Configuring SNMP-5.0404 ... N/A
! Configure failed for SNMP-5.0404. See /home/netdisco/.cpanm/work/1581654765.9961/build.log for details.
! Installing the dependencies failed: Module 'SNMP' is not installed
! Bailing out the installation for SNMP-Info-3.70.
! Installing the dependencies failed: Module 'SNMP::Info' is not installed
! Bailing out the installation for App-Netdisco-2.044015.
[netdisco@netengsrv01 ~]$ exit
exit
[root@netengsrv01 ~]# rpm -qa | grep snmp
pcp-pmda-snmp-4.3.2-2.el8.x86_64
[root@netengsrv01 ~]# `

all other version of snmp have been purged from the machine

I cant get the logfile at this time to export off but the only complaint is about the SNMP

cpanm (App::cpanminus) 1.7044 on perl 5.026003 built for x86_64-linux-thread-multi
Work directory is /home/netdisco/.cpanm/work/1581654765.9961
You have make /bin/make
You have LWP 6.34
You have /bin/tar: tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /bin/unzip
Searching App::Netdisco () on cpanmetadb ...
--> Working on App::Netdisco
Fetching http://www.cpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.044015.tar.gz
-> OK
Unpacking App-Netdisco-2.044015.tar.gz
Entering App-Netdisco-2.044015
Checking configure dependencies from META.json
Checking if you have ExtUtils::Install 1.46 ... Yes (2.14)
Checking if you have Module::Build 0.42 ... Yes (0.4224)
Checking if you have DBIx::Class 0.082810 ... Yes (0.082841)
Configuring App-Netdisco-2.044015
Running Build.PL
Checking prerequisites...
  requires:
    !  SNMP::Info is not installed
  test_requires:
    !  Env::Path is not installed
    !  Test::Compile is not installed
  recommends:
    *  Graph is not installed
    *  GraphViz is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'App-Netdisco' version '2.044015'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Pod::Usage 0 ... Yes (1.69)
Checking if you have AnyEvent::DNS::EtcHosts 0 ... Yes (0.0103)
Checking if you have NetAddr::MAC 0.93 ... Yes (0.96)
Checking if you have SQL::Abstract 1.85 ... Yes (1.86)
Checking if you have URL::Encode::XS 0 ... Yes (0.03)
Checking if you have Template::Plugin::Number::Format 1.02 ... Yes (1.06)
Checking if you have Template::AutoFilter 0 ... Yes (0.143050)
Checking if you have Regexp::Common 2017060201 ... Yes (2017060201)

**Comment by rc9000** [comment]
So the [installation instructions](https://metacpan.org/pod/App::Netdisco#Installation) say to install net-snmp-perl, but this does not seem to exist anymore in Centos 8:

```
[root@6468effe22ee /]# cat /etc/redhat-release 
CentOS Linux release 8.1.1911 (Core) 
[root@6468effe22ee /]# 
[root@6468effe22ee /]# yum install perl-core perl-DBD-Pg net-snmp-perl net-snmp-devel openssl-devel curl postgresql-server postgresql-contrib make automake gcc
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 6:35:06 ago on Fri Feb 14 06:59:33 2020.
No match for argument: net-snmp-perl
Package curl-7.61.1-11.el8.x86_64 is already installed.
Error: Unable to find a match: net-snmp-perl
```
Did you get it from somewhere else, and if so how exactly?

**Comment by tpolim008** [comment]
I was able to install with some research net-snmp and net-snmp-Util with
yum command which installs net-snmp 5 which generates errors.

I also installed CPAN which wouldn’t do the automatic folder so I the. With
“basic cpan” installed tiny::config which generated the perl5 folder cpan
calls for.

Once’s that was done I ran the cpan install which then linked to all the
proper folders.

Hope this helps answer your questions.


yum -y install net-snmp net-snmp-utils

dnf install perl-CPAN


cpan
[...]
CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] yes
[...]

Error perl5 folder not found installed to /home/xxxx/perl5


cpan[1]> install "Config::Tiny"
Fetching with HTTP::Tiny:http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/root/.local/share/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with HTTP::Tiny:http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/root/.local/share/.cpan/sources/modules/02packages.details.txt.gz'
[...]
Running make install
Manifying 1 pod documentInstalling
/usr/local/share/perl5/Config/Tiny.pmInstalling
/usr/local/share/man/man3/Config::Tiny.3pm
Appending installation info to /usr/lib64/perl5/perllocal.pod
  RSAVAGE/Config-Tiny-2.23.tgz
  /usr/bin/make install  -- OK

cpan[2]> o conf init

After the last line Which allows you to do the install of cpan again,
linked to the prob prel libraries.

**Comment by rc9000** [comment]
So the issue is exactly as Jirka Novak <j.novak@netsystem.cz> already mentioned on the mailing list:

This is with net-snmp-1:5.8-12.el8_1.x86_64 which has

```
$ grep memdup /usr/include/**/*.h
/usr/include/net-snmp/library/tools.h:    void           *netsnmp_memdup(const void * from, size_t size);
/usr/include/net-snmp/library/tools.h:    void *netsnmp_memdup_nt(const void *from, size_t from_len, size_t *to_len);

```
But the cpan module still uses memdup which is now undefined:

```
$ cpanm SNMP
... 

SNMP.xs: In function ‘XS_SNMP__new_v3_session’:
SNMP.xs:2756:20: warning: implicit declaration of function ‘memdup’; did
you mean ‘memcmp’? [-Wimplicit-function-declaration]
                    memdup(&session.securityAuthLocalKey,
                    ^~~~~~
                    memcmp
cc1: some warnings being treated as errors
make: *** [Makefile:338: SNMP.o] Error 1

I found discussions about changing name of memdup function to different
name as it is in collision with libc name which is root cause of the
compilation error. But I found no updated SNMP packaged.
```

The perl module is actually already fixed, just this version is not yet on CPAN. I'm asking there if they can publish it. For a current workaround, it should be possible to manually build the module from https://github.com/net-snmp/net-snmp/tree/master/perl/SNMP

**Comment by rc9000** [comment]
PS net-snmp-perl not being in Centos 8 is inconsequential, the package essentially contains this SNMP module which cpanm will install anyways as dependency. IMHO we could generally remove it from the Redhat install instructions.

**Comment by ollyg** [comment]
Seems we're not the only ones:
https://www.mail-archive.com/xcat-user@lists.sourceforge.net/msg07528.html

I am hesitant to suggest users download and install from a third party repo:
http://repo.okay.com.mx/centos/8/x86_64/release//net-snmp-perl-5.8-7.el8.2.x86_64.rpm
(via https://centos.pkgs.org/8/okey-x86_64/net-snmp-perl-5.8-7.el8.2.x86_64.rpm.html)

**Comment by tpolim008** [comment]
Thanks Oliver. I’m not all for using third party untrusted repos on this
server. If it was a tinker board or something not production I would take
my chance. I don’t want to risk any of the unknowns.

Do we know when cpan will be updates I did some digging but didn’t seem to
come across much of an answer.

**Comment by rc9000** [comment]
Unfortunately the net-snmp-perl module is poorly equipped to be distributed with CPAN, and it looks like the team has abandoned the idea in 2013 - so not much hope there.

We also can't help the situation much as the main culprit, Redhat not shipping net-snmp-perl anymore, is totally outside of our control. But asking about the how and why on their forums or even better via support contract would be greatly encouraged.

To run Netdisco on Centos 8 today the viable options are:

* build net-snmp-perl yourself, either by [building from source with configure & make](https://github.com/net-snmp/net-snmp/blob/master/INSTALL), by using the [spec file in the distribution to build RPMs](https://github.com/net-snmp/net-snmp/blob/master/dist/net-snmp.spec), or by rebuilding the Redhat source [RPM as described in the link Oliver posted](https://www.mail-archive.com/xcat-user@lists.sourceforge.net/msg07528.html)
* run [the docker distribution](https://github.com/netdisco/netdisco-docker) instead

**Comment by tpolim008** [comment]
That’s everyone I’ll report back see what I do. Maybe I’ll fire up a VM and
attempt the 3rd party module and see how it works or try compiling it
there. So from I take it this is more or less a redhat issue opposed to
netdisco type deal. Assuming netdisco coders will still use net-snmp as
this is the only impacted platform

**Comment by ollyg** [comment]
I wonder whether we could ship our own Alien:: net-snmp ....?

**Comment by ollyg** [comment]
> Assuming netdisco coders will still use net-snmp as this is the only impacted platform

Netdisco is using SNMP::Info for SNMP actions, and SNMP::Info is heavily tied to net-snmp. Well, perhaps a shim could be developed for Net::SNMP or an alternative but it would be a big piece of work. I would rather put cycles into Netdisco3 which will probably be in Python and not using net-snmp at all (pysnmp or similar instead).

**Comment by ollyg** [comment]
> I wonder whether we could ship our own Alien:: net-snmp ....?

Oh, looks like I already did. I wonder if we could use that. It would need to be SNMP::Info changing to us Alien::SNMP instead of SNMP. Or, perhaps could hack it from Netdisco side using the aliased pragma.

**Comment by ggmo** [comment]
> > Assuming netdisco coders will still use net-snmp as this is the only impacted platform
> 
> Netdisco is using SNMP::Info for SNMP actions, and SNMP::Info is heavily tied to net-snmp. Well, perhaps a shim could be developed for Net::SNMP or an alternative but it would be a big piece of work. I would rather put cycles into Netdisco3 which will probably be in Python and not using net-snmp at all (pysnmp or similar instead).

**Comment by ggmo** [comment]
Why consider abandoning perl development for netdisco? It sounds so frustrating，is it possible to use a front-end framework like VUE in the future?

**Comment by lrowen** [comment]
Rebuilding net-snmp-perl from the source isn't too difficult, but does require one to use git.centos.org.  This comment assumes some knowledge of basic rpm building processes, including satisfying build dependencies and iteratively building to deal with build errors.

First, clone the centos-git-common repo ( [https://git.centos.org/centos-git-common](url) ) then copy the shell scripts into ~/bin
Second, clone the net-snmp source from git.c.o ( [https://git.centos.org/rpms/net-snmp](url) cd into net-snmp, and checkout the c8 branch.
Third, run the 'get_sources.sh' script inside the net-snmp checkout.
Now, you can build the package with rpmbuild (dealing with dependencies as per Normal RPM Building Practice):
`rpmbuild --nodeps --define "%_topdir `pwd`" --define '%netsnmp_check 0' -ba SPECS/net-snmp.spec`

Use rpm to install it, and make sure to keep up to date on the source packages as updates come down.  This is essentially what the OKay third-party repo is doing.

I am most of the way through the process; I'll report back on the final result tomorrow.

**Comment by tpolim008** [comment]
Iran, this is huge!!! If you don’t mind when you have this fully done if
you can help me out step by step. I’m newer to the Linux world so I tiptoe
around with fear of breaking stuff. So any through instruction to help me
out would be awesome!

**Comment by lrowen** [comment]
Ok, so I haven't started oveer from a fresh C8 install, but it's pretty close.  I also have OpenNMS installed on this VM, so postgresql was already installed and initialized by that install.  I'm also not including the steps as documented in the netdisco installation guide; this is just a log of the steps that are different to get net-snmp-perl built and loaded so SNMP::Info is happy.  

So, I'm splitting this up into pieces; I'm also looking for feedback for the steps on a pristine C8 install....  First, do these steps as root or using sudo:
`dnf config-manager --set-enabled PowerTools
dnf group install "Development Tools"
dnf install rpmdevtools cmake expect rpmlint perl-Expect mariadb-devel perl-core perl-DBD-Pg  openssl-devel postgresql-server postgresql-contrib automake
`
Now, as the netdisco user (su - netdisco)  Note that I'm using rsync below, to preserve permissions on the scripts in centos-git-common; cp -a does the same thing, I'm just an rsync junkie, I guess.  I'm also skipping the tests by defining %netsmp_check 0 in the rpmbuild command line.
`
git clone https://git.centos.org/centos-git-common.git
git clone https://git.centos.org/rpms/net-snmp.git
mkdir bin
rsync -avHAX centos-git-common/ bin
cd net-snmp
git checkout c8
get_sources.sh
rpmbuild --nodeps --define "%_topdir ~/net-snmp" --define '%netsnmp_check 0' -ba SPECS/net-snmp.spec

`
Once the rpmbuild completes without error, go back to root or use sudo to:
`
cd /home/netdisco/net-snmp/RPMS/x86_64
yum install net-snmp-5.8*.rpm net-snmp-perl-5.8*.rpm net-snmp-devel-5.8*.rpm net-snmp-libs-5.8*.rpm net-snmp-agent-libs-5.8*.rpm

`
Then go back to the netdisco user (su - netdisco) and run the rest of the netdisco install.

I hope that's not skipping around too much; I had two ssh sessions to the server going, one as the root user and one as the netdisco user, so the command history is interleaved in my case.  I'm going to try again with a pristine minimal C8 install when I have the time to do so, maybe next week.  I'm mostly just evaluating netdisco right now in parallel with OpenNMS, and since the OpenNMS system was already on C8, that's where I started the netdisco install, which caused me to find this thread.....

As to why RH dropped net-nmp-perl from the distribution, it probably has a lot to do with the Modularity mechanism in RHEL8, and since perl is one of the packages that is fully modularized, each perl-dependent package could add significant complexity, and non-modular packages are being minimized.

**Comment by tpolim008** [comment]
Hello Irowen,
    I tried to follow this and on the git clon section everything seems to
work until I got the rpmbuild any chance you see if or what I did wrong
here?

[root@netengsrv01 ~]# su - netdisco
[netdisco@netengsrv01 ~]$ git clone
https://git.centos.org/centos-git-common.git
Cloning into 'centos-git-common'...
remote: Counting objects: 220, done.
remote: Compressing objects: 100% (216/216), done.
remote: Total 220 (delta 10), reused 207 (delta 0)
Receiving objects: 100% (220/220), 127.62 KiB | 4.12 MiB/s, done.
Resolving deltas: 100% (10/10), done.
[netdisco@netengsrv01 ~]$ git clone https://git.centos.org/rpms/net-snmp.git
Cloning into 'net-snmp'...
remote: Counting objects: 315, done.
remote: Compressing objects: 100% (282/282), done.
remote: Total 315 (delta 56), reused 220 (delta 0)
Receiving objects: 100% (315/315), 179.50 KiB | 3.99 MiB/s, done.
Resolving deltas: 100% (56/56), done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.

[netdisco@netengsrv01 ~]$ mkdir bin
[netdisco@netengsrv01 ~]$ rsync -avHAX centos-git-common/ bin
sending incremental file list
./
README.md
centos.git.repolist.py
get_sources.sh
into_srpm.sh
lookaside_upload
return_disttag.sh
rpm-tree-prep.sh
show_possible_srpms.sh
.git/
.git/HEAD
.git/config
.git/description
.git/index
.git/packed-refs
.git/branches/
.git/hooks/
.git/hooks/applypatch-msg.sample
.git/hooks/commit-msg.sample
.git/hooks/fsmonitor-watchman.sample
.git/hooks/post-update.sample
.git/hooks/pre-applypatch.sample
.git/hooks/pre-commit.sample
.git/hooks/pre-push.sample
.git/hooks/pre-rebase.sample
.git/hooks/pre-receive.sample
.git/hooks/prepare-commit-msg.sample
.git/hooks/update.sample
.git/info/
.git/info/exclude
.git/logs/
.git/logs/HEAD
.git/logs/refs/
.git/logs/refs/heads/
.git/logs/refs/heads/master
.git/logs/refs/remotes/
.git/logs/refs/remotes/origin/
.git/logs/refs/remotes/origin/HEAD
.git/objects/
.git/objects/info/
.git/objects/pack/
.git/objects/pack/pack-c195e652de77e0e2ceda5c3eedecbab122cceb41.idx
.git/objects/pack/pack-c195e652de77e0e2ceda5c3eedecbab122cceb41.pack
.git/refs/
.git/refs/heads/
.git/refs/heads/master
.git/refs/remotes/
.git/refs/remotes/origin/
.git/refs/remotes/origin/HEAD
.git/refs/tags/
mqtt/
mqtt/README.md
mqtt/example-safe-command.py
mqtt/listen-on-dbus-for-mqtt-signals.py
mqtt/listen-on-dbus-for-mqtt-signals.service
mqtt/send-mqtt-to-dbus.py
mqtt/send-mqtt-to-dbus.service
mqtt/send-mqtt-to-irc.py
mqtt/mosquitto_sub/
mqtt/mosquitto_sub/README.md

sent 225,909 bytes  received 871 bytes  453,560.00 bytes/sec
total size is 222,204  speedup is 0.98
[netdisco@netengsrv01 ~]$ cd net-snmp
[netdisco@netengsrv01 net-snmp]$ git checkout c8
Branch 'c8' set up to track remote branch 'c8' from 'origin'.
Switched to a new branch 'c8'
[netdisco@netengsrv01 net-snmp]$ get_sources.sh
Retrieving
https://git.centos.org/sources/net-snmp/c8/78f70731df9dcdb13fe8f60eb7d80d7583da4d2c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100 6437k  100 6437k    0     0  20.3M      0 --:--:-- --:--:-- --:--:--
20.3M
[netdisco@netengsrv01 net-snmp]$ rpmbuild --nodeps --define "%_topdir
~/net-snmp" --define '%netsnmp_check 0' -ba SPECS/net-snmp.spec
error: Bad source: ~/net-snmp/SOURCES/net-snmp-5.8.tar.gz: No such file or
directory

**Comment by lrowen** [comment]
Ok, so rpmbuild's %_topdir doesn't like ~..... sorry about that.  The actual command I used had a backtick (used here as the CODE delimiter) pair wrapping a pwd command; instead of '~/net-snmp-perl' try '/home/netdisco/net-snmp-perl' instead.  Using the tilde seems on confuse rpmbuild in a big way, and it creates a directory named ~ instead of going to the user's home.  Sorry about that.

**Comment by tpolim008** [comment]
So if I understand correctly replace the %_topdir portion with the
'/home/netdisco/net-snmp-perl'
if I follow...

**Comment by lrowen** [comment]
I posted this solution at the centos.org forums, too, and the backtick shows up there, so for comparison look at the post at [https://forums.centos.org/viewtopic.php?f=54&t=73376&p=314200#p314200](url)

You want the rpmbuild line to look like:
`
rpmbuild --define "%_topdir `pwd`" --define '%netsnmp_check 0' -ba SPECS/net-snmp.spec
`

**Comment by tpolim008** [comment]
Thank you I followed the link as well and here is what I am getting and
running into....

Checking for unpackaged file(s): /usr/lib/rpm/check-files
/root/net-snmp/BUILDROOT/net-snmp-5.8-14.el8.x86_64
Wrote: /root/net-snmp/SRPMS/net-snmp-5.8-14.el8.src.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-5.8-14.el8.x86_64.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-utils-5.8-14.el8.x86_64.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-devel-5.8-14.el8.x86_64.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-perl-5.8-14.el8.x86_64.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-gui-5.8-14.el8.x86_64.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-libs-5.8-14.el8.x86_64.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-agent-libs-5.8-14.el8.x86_64.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-debugsource-5.8-14.el8.x86_64.rpm
Wrote: /root/net-snmp/RPMS/x86_64/net-snmp-debuginfo-5.8-14.el8.x86_64.rpm
Wrote:
/root/net-snmp/RPMS/x86_64/net-snmp-utils-debuginfo-5.8-14.el8.x86_64.rpm
Wrote:
/root/net-snmp/RPMS/x86_64/net-snmp-perl-debuginfo-5.8-14.el8.x86_64.rpm
Wrote:
/root/net-snmp/RPMS/x86_64/net-snmp-libs-debuginfo-5.8-14.el8.x86_64.rpm
Wrote:
/root/net-snmp/RPMS/x86_64/net-snmp-agent-libs-debuginfo-5.8-14.el8.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.UbB40B
+ umask 022
+ cd /root/net-snmp/BUILD
+ cd net-snmp-5.8
+ /usr/bin/rm -rf /root/net-snmp/BUILDROOT/net-snmp-5.8-14.el8.x86_64
+ exit 0

when I try to cd into the noted file directory....
[root@netengsrv01 ~]# cd /home/netdisco/net-snmp/RPMS/x86_64
-bash: cd: /home/netdisco/net-snmp/RPMS/x86_64: No such file or directory


from above it looks like its placing it in
  /root/net-snmp/RPMS/x86_64

so when I cd here and try the yum command I get the following not sure what
I am doing wrong....

[root@netengsrv01 ~]# cd /root/net-snmp/RPMS/x86_64/
[root@netengsrv01 x86_64]# yum install net-snmp-5.8*.rpm
net-snmp-perl-5.8*.rpm net-snmp-devel-5.8*.rpm net-snmp-libs-5.8*.rpm
net-snmp-agent-libs-5.8*.rpm
Last metadata expiration check: 0:27:23 ago on Fri 19 Jun 2020 10:19:25 AM
EDT.
Package net-snmp-libs-1:5.8-14.el8.x86_64 is already installed.
Error:
 Problem 1: conflicting requests
  - nothing provides /bin/perl needed by net-snmp-1:5.8-14.el8.x86_64
 Problem 2: conflicting requests
  - nothing provides /bin/perl needed by net-snmp-perl-1:5.8-14.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to
use not only best candidate packages)
[root@netengsrv01 x86_64]#

it says that it is already installed but has conflicts.....

**Comment by lrowen** [comment]
Ok, you built it as root, and you found the packages.  It's usually recommended to build rpms as a normal user, not root, but you have the packages, now.  So, on my working netdisco and OpenNMS VM:
```
[root@opennms ~]# rpm -q --whatprovides /bin/perl
perl-interpreter-5.26.3-416.el8.x86_64
[root@opennms ~]#
```
So try installing the perl-interpreter package.

**Comment by ollyg** [comment]
Looks like net-snmp-perl is now available in CentOS 8:
https://rpmfind.net/linux/RPM/centos/8.3.2011/appstream/x86_64/Packages/net-snmp-perl-5.8-17.el8.x86_64.html

**Comment by tpolim008** [comment]
Awesome news, so removing the temp work around, and native install should
work.

Any word on using telnet/ssh for initial node discovery opposed to SNMP?
