### ISSUE TITLE
OUI update fails

### ISSUE THREAD

**Issue by zoeloe** [netdisco/netdisco#702]
## Expected Behavior
netdisco-deploy schould update the OUI in the database

## Current Behavior
neither netdisco-deployo or netdisco-deploy oui.txt seems to be able to aupdatae the Vendors in the databse

## Steps to Reproduce (for bugs)
1) answer yes if netdisco-deploy asks to update the OUI
2) netdisco-deply oui.txt fails also without any warning.

## Context
Found a device without vendor info and checked in the oui file from https://standards-oui.ieee.org/oui.txt where it exists.
Not in the outdated file which netdosco-deploy tries to download from raw.gitusercontent.com

## Your Environment

App::Netdisco | 2.44.15
SNMP::Info | 3.70

**Comment by zoeloe** [comment]
The exact form below seems to work, but it has to be exactly the same:
~/bin/netdisco-deploy ./oui.txt
The internally referenced download location raw.gitusercontent.com is outdated.

**Comment by ollyg** [comment]
I have updated the OUI file in the upstream-sources repo, thanks for the prod.

Should be 27547 rows in your oui table after this update, whereas before 25520.

**Comment by zoeloe** [comment]
The oui.txt I loaded from  https://standards-oui.ieee.org/oui.txt is also 27547 entries, so I guess that's OK for now. Isn't it adviced to directly use this URL in the netdisco-deploy script ? I remember vaguelly that a while ago there was a format error issue with the ieee version if my memory serves my right. 
Or maybe use the ieee version as extra option in the deploy script if it's parsable and more recent (more entries) than the one available on raw.gitusercontent.com ? Just a suggestion.
Thanks for the update.

**Comment by ollyg** [comment]
The IEEE site is quite often overloaded or down, so the download direct from there was failing. This is why I wanted to host our own copy.
