### ISSUE TITLE
Port status not included in CSV export from Device View

### ISSUE THREAD

**Issue by postilion** [netdisco/netdisco#705]
## Expected Behavior
When clicking the "Download as CSV" from the Device View, the resultant data file should include the port status.  This would be very useful for those of us using Netdisco as a data source for reporting into other systems.

## Current Behavior
All other columns of the Device View page are included in the data file, but not port status.

## Possible Solution
I believe this could be fixed in ajax/device/ports_csv.tt, but am not totally clear on that.

## Steps to Reproduce (for bugs)
1. Open a device view
2. Click on "Download as CSV" link
3. Examine CSV file

## Context
I often want to use Netdisco to produce reports which feed into other systems, but, lacking port status, must manually edit the resulting CSV to add this data.

## Your Environment
* Netdisco version used: 2.44.1 & 2.44.3
* SNMP::Info version used: 3.68 & 3.70

**Comment by rc9000** [comment]
Hi Nic

The CSV export contains the columns picked in the UI, if you select status beforehand it will be in the file:

<img width="1359" alt="scr 2020-03-12 at 16 25 38" src="https://user-images.githubusercontent.com/1247031/76537586-4553d400-647e-11ea-95ad-9e35a48f79e6.png">

I haven't tried this, but If you'd like the status to be there by default, you should be able to add the columns as described here: https://github.com/netdisco/netdisco/wiki/Web-Plugins#device-port-columns - the actual database columns are device_port.(up, up_admin)

For automated jobs between systems, I'd probably not bother with the UI but directly use `netdisco-do psql` to export stuff, if you tell us what you need somebody here can certainly come up with an SQL statement for you.

**Comment by postilion** [comment]
Oh, great; thanks!  I had never noticed Status in that list.  Guess I'd better RTF-screen more often. :)
-nic
