### ISSUE TITLE
Question: how to know a port is trunk or not

### ISSUE THREAD

**Issue by yimoucao** [netdisco/netdisco#706]
haven't found an easier way to know whether a port is trunk port or access port in ports table. Or is there any other indicator?

**Comment by rc9000** [comment]
Hi! I think you're right there is not quite a direct way, ie the `switchport mode trunk` setting or whatever your platform calls it is not stored. 

You can tell *active* trunk ports by looking at the VLAN membership in the ports table, if there's a whole list in there it's probably a trunk. But this does not work for ports with no or just a single forwarded VLAN.

Another way is to look at the Connected Devices column. An entry there means that on the other side, Netdisco found a device that's also speaking SNMP and that was successfully discovered. This will be a trunk port in many cases.

If you already have some config archive of your devices, I can recommend adding a link to this configuration as an additional ports column, then people can go look at the configuration with just an additional click. This is easy to do, see here: https://github.com/netdisco/netdisco/wiki/Web-Plugins#device-port-columns

**Comment by ollyg** [comment]
Agree with @rc9000 - it's not easy to know, because in essence the trunk or access mode is simply an implementation of a set of predefined policies such as handling VLAN tagging and BPDU filtering. I'm not aware that trunk and access are IETF defined states, which are standardised across vendors?
