### ISSUE TITLE
Problem after 2.45 upgrade

### ISSUE THREAD

**Issue by pilyon3** [netdisco/netdisco#716]
Hi,

After upgrading from 2.44 to 2.45 version, we can't access devices infos anymore.

[Steps done for upgrade](https://metacpan.org/pod/App::Netdisco#Upgrading-from-2.x)

## Expected Behavior
N/A

## Current Behavior
Accessing datas for any of one our device, errors are triggerd:

https://serveur/netdisco/device?q=<device_ip>

=> An internal error occured

Errors logged into netdisco-web.log file:

`[33253] 2020-04-27 12:24:23 error request to GET /device crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  column me.ports does not exist
LIGNE 1 : ...ime, me.contact, me.name, me.location, me.layers, me.ports, ...
                                                               ^ [for Statement "SELECT me.ip, me.creation, me.dns, me.description, me.uptime, me.contact, me.name, me.location, me.layers, me.ports, me.mac, me.serial, me.model, me.ps1_type, me.ps2_type, me.ps1_status, me.ps2_status, me.fan, me.slots, me.vendor, me.os, me.os_ver, me.log, me.snmp_ver, me.snmp_comm, me.snmp_class, me.vtp_domain, me.last_discover, me.last_macsuck, me.last_arpnip FROM device me WHERE ( ( host(me.ip) = ? OR me.dns = ? ) )" with ParamValues: 1='<deivce_ip>', 2='<device_ip>'] at /home/netdisco/perl5/lib/perl5/App/Netdisco/Web/Device.pm line 79
`

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
Problem occurs after upgrading from 2.44 to 2.45

## Your Environment
App::Netdisco | 2.45.2
SNMP::Info | 3.70
DB Schema | 62
PostgreSQL | 9.4.25
Perl | 5.28.1

**Comment by ollyg** [comment]
Hi @pilyon3 
Indeed the ports column was renamed num_ports. Have you applied the DB update with netdisco-deploy (I assume yes) and have you definitely restarted the web frontend ?

**Comment by pilyon3** [comment]
Thanks for the response. Yes, we've done all of these actions.

![image](https://user-images.githubusercontent.com/36040281/80376636-6a6b9d00-889a-11ea-8a31-9508dc3e572a.png)

**Comment by pilyon3** [comment]
It appears that some netdisco process didn't stops normaly during upgrade procedure and later restarts of the web service. After killing all processes manually, Netdisco tools is up and running well again.

Sorry for the disturbance.

Regards.

**Comment by ollyg** [comment]
no worries :-)
