### ISSUE TITLE
API endpoint not working

### ISSUE THREAD

**Issue by this-is-mihai** [netdisco/netdisco#718]
Hello. I'm trying to use the API but one endpoint is not working.
to be more specific this one

/api/v1/search/node

I'm using powershell to make web requests. I'm loading the API authorization key. I can successfully make other queries such as /api/v1/object/device/
but when i try the search/node i get an error saying :

> Invoke-RestMethod : 
> Error 404
> Error 404
> Unable to process your queryThe page you requested is not available
> Powered by Dancer 1.3500

my powershell code :

```
$postParams = @{username='user';password='password'}
$login = Invoke-WebRequest -Uri http://server:5000/login -Method POST -Body $postParams -Headers @{"accept"="application/json"}

$headers = @{}
$headers.Add("Accept","application/json" )
$headers.Add("Authorization","correct_api_key")
```
this works:
```
Invoke-WebRequest -Method get -Uri "http://server:5000/api/v1/object/device/172.99.199.99" -Headers $headers 
```
this does not work
```
Invoke-WebRequest -Method get -Uri 'http://server:5000/api/v1/search/node?q=172.99.160.160' -Headers $headers
```

Any thoughts?

## Your Environment

App::Netdisco | 2.45.2
SNMP::Info | 3.70
PostgreSQL | 9.6.10
Perl | 5.16.3

**Comment by ollyg** [comment]
[master 42bb6e54] #718 fix Node Search API endpoint

**Comment by ollyg** [comment]
thanks for the bug report @this-is-mihai and sorry about that
the fixed version will be on CPAN later today

**Comment by this-is-mihai** [comment]
Hey there @ollyg . No problem, just glad i could help. Also, thank you for your quick response and fix.
