### ISSUE TITLE
netdisco-web does not listen to IPv6 when using the installation instructons

### ISSUE THREAD

**Issue by ardje** [netdisco/netdisco#719]
## Expected Behavior
Install netdisco using the installation instructions using:
https://metacpan.org/pod/App::Netdisco
on a bare debian/buster installation from: http://images.linuxcontainers.org .
~/bin/netdisco-web start
and have netdisco listen to ipv4 as wel as ipv6.

## Current Behavior
Net::Server denies the existence of ipv6 due to the missing: "IO/Socket/INET6.pm" .

## Possible Solution
Update the installation instruction for debian users to also install:
libio-socket-inet6-perl .
Or in their case, just installing libnet-server-perl might also work, and might skip the cpan installation.
There is probably a CPAN solution too, but I am to noob to see what exactly.

**Comment by ollyg** [comment]
[master 49d4519e] fixes #719 include IO::Socket::INET6 in deps to ensure IPv6 support
