### ISSUE TITLE
Enhancement: make search more user-friendly

### ISSUE THREAD

**Issue by edo1** [netdisco/netdisco#721]
Often I use cut-n-paste to search information in NetDisco (by  MAC/IP).
IMO it is good idea to relax the search query requirements.

1. There are a lot of MAC address formats, why do not allow them all?
(01-02-03-04-05-06, 0102.0304.0506, 0102-0304-0506, 010203040506, etc)
2. Extra spaces in queries like " 10.0.0.1" or "10.0.0.1 " or " 01:02:03:04:05:06 " could be automatically removed.

**Comment by ollyg** [comment]
Hi @edo1 thanks for the suggestions!

Stripping whitespace is a good one - I can patch that in easily.
For the MAC addresses, we already use [NetAddr::MAC](https://metacpan.org/pod/NetAddr::MAC) which should accept most formats.

Ah, but looking more closely at the code, what we do is see if the search param looks like a number and then go to a VLAN search instead of a Node search. Some of the MAC formats you give will trigger that.

(the titlebar search tries to be smart and work out what's being put in and what the user wants... VLAN, port, node, or device)

I suppose the VLAN shortcut could be made smarter (positive integers only, between 1 and 4095) and then the param is tested with NetAddr::MAC.

**Comment by ollyg** [comment]
implemented in
[master 3662899e] #721 search will trim whitespace and handle more MAC formats

and new release on CPAN soon

**Comment by edo1** [comment]
@ollyg 
Thank you for the fast fix. One more thing: when searching by the MAC address of the switch, the `Port` tab is selected; nonstandard MAC format isn't handled there.

BTW, is it possible to search for a switch (`Device`) by MAC?

**Comment by ollyg** [comment]
@edo1 have you spotted that there's a little drop down arrow on the search button? You can select "Device" there to force a device search. Otherwise netdisco will see that the MAC matches an interface on a device and go to the Port tab instead.

**Comment by ollyg** [comment]
I will look into the MAC formats support on the Port tab (should indeed be same as NetAddr::MAC supports).

**Comment by edo1** [comment]
> @edo1 have you spotted that there's a little drop down arrow on the search button? 

Yes. This changes default tab only, right?
I meant that switch can be found by IP, location, etc. But `Search Devices` by MAC returns nothing.

Moreover, LLDP neighbor discovery by MAC doesn't work as well, I had to turn on announcing management IP address on all devices to make topology discovery feasible.

**Comment by edo1** [comment]
> Moreover, LLDP neighbor discovery by MAC doesn't work as well, I had to turn on announcing management IP address on all devices to make topology discovery feasible.

I found the previous discussion at https://github.com/netdisco/snmp-info/issues/340, but there is still no solution.

**Comment by zoeloe** [comment]
If I may comment here,.. e.g.
We have a case where switches have added info in the Name Field (Like: the IP address etc,.. for the device which should be connected there,.. but as we all know,... this is administratively not manageable)... anyway....
When searching via the title bar search box and NOT selecting e.g. Node specifically when searching an IP address,... the results are the "IP address" found in the Name fields even if an IP address can be found in e.g. IP inventory. The search doesn't "continue" to search for the "node".
BUT: the Search in the middle of the welcome screen DOES give the node as result when searching for the IP address. (Without specifying to explicitaly search for a Node)
(The searching doesn't continue to search the Name fields)
So, the behavior of both search fields differ.
Or am I seeing things here ?
My 2 cents

**Comment by ollyg** [comment]
@zoeloe you're probably right, it might not be consistent :-). worth looking into...

**Comment by ollyg** [comment]
@zoeloe the search on the title bar and the search on the welcome screen use the same /search web endpoint with the same fields, so should return the same

**Comment by ollyg** [comment]
fixed in [master f882f983] #721 redux - better MAC address support in searching

**Comment by zoeloe** [comment]
Some feedback. Yes, the behavior is consistent now for both search fields it seems. (I was looking before at 2.044015 I think.)
And if the "Name" field contains the data one is searching for, it delivers this as result and stops searching (not searching for IP address anymore.) It's not clear that other data exists and the result shown actually hides other results..
my 2 cents. Thanks for the fix !

**Comment by inphobia** [comment]
while @ollyg or @JeroenvIS  will most likely correct me, according to https://en.wikipedia.org/wiki/Virtual_LAN#IEEE_802.1Q the maximum number of vlans in 802.1q is 4096, but 0 & 4095 "reserved".

so perhaps all referenced to 4096 should be changes to 4095?
https://github.com/netdisco/netdisco/blob/b42493f1e8cb599ac623bb711d1d2694d685ce6a/lib/App/Netdisco/Web/Plugin/Search/Port.pm#L47
https://github.com/netdisco/netdisco/blob/f882f9831951654ba3ddd45a7116a11340d8c694/lib/App/Netdisco/Web/Search.pm#L35

or we could go for 802.1.aq support with 16 million vlans :)
