### ISSUE TITLE
Reporting issues.

### ISSUE THREAD

**Issue by pgo1** [netdisco/netdisco#723]
Good afternoon.

I've added a custom report to check devices uptime.

A very simple query like the one below was added to my configuration file:

- tag: dev_uptime
    label: 'Devices Uptime'
    category: Device
    columns:
      - {device: 'Device Name'}
      - {ip: 'Device IP'}
      - {uptime: 'Device Uptime'}

    query: |
      SELECT d.ip, d.name, d.uptime AS days FROM device d ORDER BY name

Since (what I think ) version 2.045002 it stopped working with and error "Search failed".

In netdisco-web we get the following  entry:

[9574] 2020-05-25 12:32:23 error request to GET /ajax/content/report/dev_uptime crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  column me.device does not exist
LINE 1: SELECT me.device, me.ip, me.uptime FROM (SELECT d.ip, d.name...
               ^ [for Statement "SELECT me.device, me.ip, me.uptime FROM (SELECT d.ip, d.name, d.uptime AS days FROM device d ORDER BY name
) me"] at /home/netdisco2/perl5/lib/perl5/App/Netdisco/Web/GenericReport.pm line 62

Seems that the schema name used is incorrect.

Quite weird as I've other custom queries and all are working correctly.
When using netdisco-do psql and run the query it works ok and I can see the data.

Version info below:
App::Netdisco	2.45.6
SNMP::Info	3.70

Can you please provide some assistance on this issue ?

Kind regards and thanks in advance.
PG

**Comment by rc9000** [comment]
Hi! In the `columns:` you say that there is a column named the device, but your SQL does not produce a column named device. You probably want:

    - {name: 'Device Name'}

**Comment by pgo1** [comment]
Hello Christian

Yes,you are right,  shame on me   as I didn’t correctly check the column name...

Thank you for your answer.
Regards
PG

**Comment by rc9000** [comment]
No worries typos happen!

**Comment by zoeloe** [comment]
@pgo1 I'm trying to use this report,... but it fails with the "AS DAYS" included in the query.
What works:
 - tag: dev_uptime
   label: 'Devices Uptime'
   category: Device
   columns:
     - {name: 'Device Name'}
     - {ip: 'Device IP'}
     - {uptime: 'Device Uptime'}
query: |
     SELECT d.ip, d.name, d.uptime
       FROM device d
     ORDER BY name

The result is uptime in presumably timeticks ?
Any hints here. psql noob here.
TIA

**Comment by rc9000** [comment]
Hi @zoeloe ! Hmm weird I didn't even notice the 'as days'. This just renames the column, so it should also be referred to as 'days' in the columns: definition.

But it's also not really days without any calculation, the field content is timeticks as you say - these are measured in 100th of a second. So to get days you'd need something like

    select ip, dns, uptime / 100 / 86400.0 as up_days from device 

There's more strange things that can go wrong regarding wraparound, operating system quirks etc.,  for a good headache read https://kb.paessler.com/en/topic/61249-why-does-the-snmp-system-uptime-sensor-report-wrong-values :)

**Comment by zoeloe** [comment]
@rc9000 
Some feebdback: I Think I got it now. But IMHO the divider should be 86400 insta=ead of 86400.0 to make sure that the result is an integer for the days.
This e.g. seems to work:

 - tag: dev_uptime
   label: 'Devices Uptime'
   category: Device
   columns:
     - {name: 'Device Name'}
     - {ip: 'Device IP'}
     - {dns: 'Device DNS'}
     - {up_days: 'Device Uptime in days'}
   query: |
     SELECT d.ip, d.name, d.dns, (d.uptime / 100 / 86400)  as up_days
       FROM device d
     ORDER BY name

Thanks for the hint.
I appreciate.

**Comment by rc9000** [comment]
Yeah both work , using .0 will just give you "fractional days" like 83.4. To get a nicely formatted timestamp. you can use the age() interval function as the UI does it: https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/DB/ResultSet/Device.pm#L52

**Comment by zoeloe** [comment]
Thanks for the code hint !
The SQL now:
select name, dns, age(timestamp 'epoch' + uptime / 100 * interval '1 second',timestamp '1970-01-01 00:00:00') as up_days from device;


The report works with: 
   query: |
     SELECT d.ip, d.name, d.dns, age(timestamp 'epoch' + d.uptime / 100 * interval '1 second',timestamp '1970-01-01 00:00:00')  as up_days
       FROM device d
     ORDER BY name
