### ISSUE TITLE
Is it possible to define hooks into Netdisco App ?

### ISSUE THREAD

**Issue by pilyon3** [netdisco/netdisco#726]
Hi,

I've read documentation, but nothing seems to do what I'm looking for: triggerd hooks on specific events/jobs. Is it possible ? A good example is what is possible to do with an another soft we're using: 
[https://github.com/ytti/oxidized/blob/master/docs/Hooks.md](https://github.com/ytti/oxidized/blob/master/docs/Hooks.md)

Maybe an enhancement ?

Regards.

**Comment by rc9000** [comment]
Hi @pilyon3 

You're right, there is currently zero infrastructure in Netdisco for this. It is a reasonable request so we can put it on the wishlist.

If you'd like to implement a home-grown solution for your needs, I'd recommend using triggers on the database tables. They'll require no code changes to Netdisco and will not interfere with updates.

**Comment by pilyon3** [comment]
Hi @rc9000 

Thanks for your response and your advice looking for implementing our own solution.

Regards.

**Comment by ollyg** [comment]
Hi @pilyon3 can you give any example(s) of what you might want to hook into and do?
I can imagine something like "node appears on the network, send an email alert" - is this along the right lines or did you have soemthing else in mind?

**Comment by ollyg** [comment]
or... simply do a follow on custom action at the end of the arpnip/macsuck/discover job

**Comment by pilyon3** [comment]
Hi,

Yes, our goal is to do an http request to a custom REST API in order to execute some routines: adding a new switch into our monitoring solution, configuring snmptrapd to allow the new engineID and other stuffs...

**Comment by ggmo** [comment]
Is there any plans to support  device arp scan ,also with configure backup ?

**Comment by ollyg** [comment]
just to let you know, I think I've worked out a neat way to do this, so as and when time permits, it will be the next thing I work on.

**Comment by pilyon3** [comment]
Hi,

Thx for your take our wish into account ! Very impatient to see that in action...

**Comment by ollyg** [comment]
Thanks for the poke, and sorry for the silence... busy life, but will be looking soon.

**Comment by ollyg** [comment]
@pilyon3 please can you take a look at this proposal and let me know feedback:
https://github.com/netdisco/netdisco/wiki/Hooks-DRAFT

thanks!

**Comment by pilyon3** [comment]
Very impressive, it seems you have thinked to whatever we wished to achieve (data into JSON flow or via urls, authentication via password or token, custom headers and so on).
Furthermore we have planned to use vendor's snmp trap for save config action on our devices. Instead of using two calls from our snmptrapd process (one for refresh netdisco's data, a another for trigger a backup), it could be more efficient that netdisco centralize all actions.
So here, the goal could be to trigger a immediate discover in order to renew database after receiving a such trap then, depend on configuration of deployment.yml file, trigger a backup of the target device with hook functionality. So, a another hook event could be "refresh_device" and be filtered on parameter like location,  model or other wished data.

**Comment by ollyg** [comment]
Thanks @pilyon3 

OK, so to be sure I understand properly the workflow here:

1. your snmptrapd process calls "netdisco-do discover -d 1.2.3.4"
2. Hook at the end of discover process (with filters) makes HTTP request to trigger device backup

Is that correct?

**Comment by ollyg** [comment]
Actually, I have also the idea for an "exec" action which will run a shell command, in case that is useful.

**Comment by pilyon3** [comment]
Hi ollyg,

You're right, that's the point. More exactly, at the end of netdisco's discover process, we call an external http webservice which execute:

1. retrieve some extra device's information via netdisco's API (because we were unable to call directly this webservice with these information)
2. create/update device into our monitoring environment (reference database, snmp EngineID, monitoring engine, etc)
3. backup the device or reload backup software process to take into account new device (the software has netdisco database as reference)

Referring to your draft, point 1 could be suppressed sending data directly via the hook. And the ability do separate a new discovery event from a refresh discovery event would be nice. Moreover, possibility of an "exec" event could be useful.

All that is obviously just an example of what could be done with a such hook functionality into Netdisco.

**Comment by ollyg** [comment]
OK thanks @pilyon3 I will get started soon on this.

First implementation will be basic like in the docs. After that I will add more features (commented out in the docs at the moment) allowing arbitrary SQL to be run and sent as the body, which should allow suppressing point 1 as you suggest, and after that I will implement the `exec` hook.

**Comment by ollyg** [comment]
implemented in
[master 669eec46] Implement Hooks per #726

**Comment by ollyg** [comment]
Hi @pilyon3 for info the `exec` hook is now implemented also (command line program to run).

**Comment by pilyon3** [comment]
Hi @ollyg, thanks for this great improvement for us ! All is working as expected, well done. However, do you think it could be possible to add a similar action when executing a device deletion from GUI ? Deletion seems not to be a job...

**Comment by ollyg** [comment]
@pilyon3 I'll create another ticket for it
