### ISSUE TITLE
Discovery partially fails on invalid indexes

### ISSUE THREAD

**Issue by rc9000** [netdisco/netdisco#729]
## Expected Behavior
Work around vendor quirks as usual.

## Current Behavior
Vendors invented yet unhandled quirks :) . As they are in device_port_properties or device_module, they will also prevent the rest of the batch not to be discovered. We have two categories of discovery crashes in our network:

### 1: invalid EMIB indexes on Nokia routers

    2020-06-25 17:15:46.901 CEST [32083] ERROR:  invalid input syntax for type integer: "1.100663297"
    
    [20603] 2020-06-25 15:15:46 debug bless( {'msg' => 'DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(): execute_for_fetch() aborted with \'ERROR:  invalid input syntax for type integer: "1.100663297"\' at populate slice:
    {
      class => "fan",
      description => "Chassis 1 Fan 1",
      fru => "true",
      fw_ver => "",
      hw_ver => undef,
      index => "1.100663297",
      ip => "192.168.8.251",
      last_discover => \\"now()",
      model => "",
      name => "Chassis 1 Fan 1",
      parent => undef,
      pos => 1,
      serial => "",
      sw_ver => "",
      type => undef
    } at /opt/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Entities.pm line 110
    '}, 'DBIx::Class::Exception' )
    
    
    PG=> select vendor, model, os, os_ver from device where ip = '192.168.8.251';
    -[ RECORD 1 ]------
    vendor | nokia
    model  | 7750 SRc12
    os     | TiMOS
    os_ver | B-16.0.R8
    
### 2: invalid ifindexes  on AIR-CT
    
    2020-06-25 16:12:49.928 CEST [32315] ERROR:  invalid input syntax for type bigint: "0.26.162.219.136.112.0"
    
    [21815] 2020-06-25 15:17:49 debug bless( {'msg' => 'DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(): execute_for_fetch() aborted with \'ERROR:  invalid input syntax for type bigint: "44.90.15.134.57.160.1"\' at populate slice:
    {
      ifindex => "44.90.15.134.57.160.1",
      ip => "192.168.128.7",
      port => "ff:ff:ff:86:39:a0.1",
      raw_speed => undef
    } at /opt/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/PortProperties.pm line 123
    '}, 'DBIx::Class::Exception' )
    
    
    PG=> select vendor, model, os, os_ver from device where ip = '192.168.128.7';
    -[ RECORD 1 ]---------
    vendor | cisco
    model  | AIR-CT8510-K9
    os     | cisco
    os_ver | 8.0.133.0

## Possible Solution
Verify for these values to be actual integers, otherwise skip the insert?

**Comment by ollyg** [comment]
fixed in [master 83de59fc] #729 Discovery partially fails on invalid indexes

**Comment by rc9000** [comment]
Thanks @ollyg! I had plans to look into this myself but you're too quick :)
