### ISSUE TITLE
Feature request: more control over backend log rotation

### ISSUE THREAD

**Issue by jrbinks** [netdisco/netdisco#731]
App::Netdisco 2.45.6

Can I request parameters in deployment.yml to control the number of logs and rotation size.

Current controls appear to be rotate at about 10M and keep 7 historical copies, as controlled directly in the netdisco-backend script in rotate_logs().

Or, can this be devolved to the usual operating system processes?

Jethro.

**Comment by ollyg** [comment]
Hi @jrbinks good to hear from you!
I don't think these *background* scripts have access to the app config, I'm afraid.

However the foreground scripts which they wrap do, so you could take the netdisco-backend-fg script and ask something like daemontools or systemd to run it and capture the STDERR and log it yourself?

**Comment by jrbinks** [comment]
I'm confused.  netdisco-backend goes to the trouble of looking to see if a config exists:

```
my $template_config = file($ENV{DANCER_CONFDIR}, 'environments', $config);
my $app_config = file($ENV{DANCER_ENVDIR}, $config);
```

etc, can we not have it parse out a parameter or two to control the rotation?
