### ISSUE TITLE
Slow web search in latest version

### ISSUE THREAD

**Issue by anp135** [netdisco/netdisco#735]
Hi. 
I found misunderstood behaviour. In latest Nedisco version we got very slow Web Search devices by name or ip.

Postgresql slow query found this:
`Aggregate  (cost=296468.94..296468.95 rows=1 width=8) (actual time=262620.332..262620.332 rows=1 loops=1)
  Buffers: shared hit=3836 read=64976, temp read=5730 written=5730
  ->  HashAggregate  (cost=296284.44..296366.44 rows=8200 width=373) (actual time=262620.255..262620.322 rows=2 loops=1)
        Group Key: me.ip
        Buffers: shared hit=3836 read=64976, temp read=5730 written=5730
        ->  Hash Right Join  (cost=3077.42..291540.03 rows=1897765 width=373) (actual time=63561.064..262619.632 rows=1719 loops=1)
              Hash Cond: (ports.ip = me.ip)
              Filter: ((me.contact ~~* '%hostname%'::text) OR (me.serial ~~* '%hostname%'::text) OR (me.location ~~* '%Bar-ATS367-c6506.mss.ab.ru%'::text) OR (me.name ~~* '%hostname%'::text) OR (me.description ~~* '%hostname%'::text) OR (hashed SubPlan 1) OR ((me.mac)::text ~~* '%hostname%'::text) OR ((ports.mac)::text ~~* '%hostname%'::text) OR (me.dns ~~* '%hostname%'::text) OR (device_ips.dns ~~* '%hostname%'::text) OR (me.ip <<= '192.168.0.1'::inet) OR (device_ips.alias <<= '192.168.0.1'::inet))
              Rows Removed by Filter: 35580857
              Buffers: shared hit=3836 read=64976, temp read=5730 written=5730
              ->  Seq Scan on device_port ports  (cost=0.00..79385.04 rows=1123004 width=13) (actual time=0.014..389.941 rows=1134461 loops=1)
                    Buffers: shared hit=3179 read=64976
              ->  Hash  (cost=1188.11..1188.11 rows=27689 width=413) (actual time=107.962..107.962 rows=27377 loops=1)
                    Buckets: 16384 (originally 16384)  Batches: 8 (originally 4)  Memory Usage: 3969kB
                    Buffers: shared hit=654, temp written=1007
                    ->  Hash Right Join  (cost=526.50..1188.11 rows=27689 width=413) (actual time=71.072..88.730 rows=27377 loops=1)
                          Hash Cond: (device_ips.ip = me.ip)
                          Buffers: shared hit=654
                          ->  Seq Scan on device_ip device_ips  (cost=0.00..588.89 rows=27689 width=47) (actual time=0.011..2.491 rows=27371 loops=1)
                                Buffers: shared hit=312
                          ->  Hash  (cost=424.00..424.00 rows=8200 width=373) (actual time=70.994..70.994 rows=8200 loops=1)
                                Buckets: 16384  Batches: 1  Memory Usage: 2549kB
                                Buffers: shared hit=342
                                ->  Seq Scan on device me  (cost=0.00..424.00 rows=8200 width=373) (actual time=62.792..66.846 rows=8200 loops=1)
                                      Buffers: shared hit=342
              SubPlan 1
                ->  Nested Loop  (cost=0.71..55.18 rows=5 width=7) (actual time=0.016..0.016 rows=0 loops=1)
                      Buffers: shared hit=3
                      ->  Index Scan using idx_device_module_serial on device_module modules  (cost=0.42..13.67 rows=5 width=7) (actual time=0.015..0.016 rows=0 loops=1)
                            Index Cond: (serial = '%hostname%'::text)
                            Buffers: shared hit=3
                      ->  Index Only Scan using idx_device_ip on device me_1  (cost=0.29..8.30 rows=1 width=7) (never executed)
                            Index Cond: (ip = modules.ip)
                            Heap Fetches: 0
Planning Time: 1.731 ms
JIT:
  Functions: 43
  Options: Inlining false, Optimization false, Expressions true, Deforming true
  Timing: Generation 8.525 ms, Inlining 0.000 ms, Optimization 3.343 ms, Emission 62.160 ms, Total 74.028 ms
Execution Time: 262629.214 ms
`
I tried add more indexes but have no success with make query faster. After rollback my docker installation to the 2.045004, All slow web searches is gone. 
2.045004 used DB version 62, but downgrade database schema impossible by netdisco-deploy. So right now I have 2.045004 with DB schema 63 and have no web search speed problems, at the same time another docker installation have latest docker image, DB schema 63 and very slow (query from example runs 4 minutes) web searching.

Device counts in the each installation from 3000 to 9000 devices, not so much for begin PostgreSQL optimization -).

Could you help with come back fast web searching in Netdisco?

**Comment by anp135** [comment]
The problems between 2.046000 (slow) and 2.045007 (fast)

**Comment by rc9000** [comment]
I had a quick look at this. The essential problem is that a very expensive merge left join is generated, it takes 99% of the time

    select
    	me.ip,
    	me.creation,
    	me.dns,
    	me.description,
    	me.uptime,
    	me.contact
    	-- ... many more fields
    from
    	device me
    left join device_ip device_ips on device_ips.ip = me.ip

    -- !!! the issue: current query in master, joins all ports and then the filter is only applied in the where condition
    -- left join device_port ports on ports.ip = me.ip                                                           

    -- !!! this would be a lot faster
    left join device_port ports on ports.ip = me.ip and ports.mac::text ilike '%searchterm%'                     

    -- !!! alternative variant of achieving the above
    -- left join (select * from device_port where mac::text ilike '%searchterm%' ) ports on ports.ip = me.ip    
   

    where
    	me.contact ilike '%searchterm%'
    	or me.serial ilike '%searchterm%'
    	or me.location ilike '%searchterm%'
    	or me.name ilike '%searchterm%'
    	or me.description ilike '%searchterm%'
    	or me.ip in (
    	select
    		me.ip
    	from
    		device me
    	left join device_module modules on
    		modules.ip = me.ip
    	where
    		modules.serial = 'searchterm' )
    	or me.mac::text ilike '%searchterm%'
        -- !!! this is the where generated in master, could be removed when using one of the other methods
    	or ports.mac::text ilike '%searchterm%'
    	or me.dns ilike '%searchterm%'
    	or device_ips.dns ilike '%searchterm%'
    	or me.ip::text ilike '%searchterm%'
    	or device_ips.alias::text ilike '%searchterm%';

In our largish DB with 400k ports the plain merge left join takes around 16 seconds, while both filtering join variants finish in 400ms ([explain from PG 12.x](https://explain.depesz.com/s/y7UJ))


Now this looks easy to fix in SQL, but unfortunately I'm a big n00b with DBIx::Class and didn't find a way yet to tell it to do what I want. [This seems to generally trouble people ](https://stackoverflow.com/questions/7760689/joining-on-a-subquery-with-dbix-class
).  If some DBIx::Class guru just sees a straight forward solution I'd be very happy, otherwise I'll try to look into it some more. Can't really promise an ETA though.

**Comment by tbcurtis** [comment]
How did you roll back to a previous version?

- Trent

**Comment by rc9000** [comment]
To install an older version, cpanm can be used with the ` @version` option, eg:

    cpanm App::Netdisco@2.045007
    # or
    curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco@2.045007

**Comment by anp135** [comment]
> To install an older version, cpanm can be used with the ` @version` option, eg:
> 
> ```
> cpanm App::Netdisco@2.045007
> # or
> curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco@2.045007
> ```

this is didn't help with downgrade DB Schema from 63 to 62 -(.


> How did you roll back to a previous version?

We use docker version of netdisco, so we change version tag and reload docker container. The DB Schema problems still because netdisco-do deploy does not help with downgrade. Suppose in next week or maybe later will look to schema and rollback to 62 by hands.

**Comment by rc9000** [comment]
@anp135 you can stay at schema 63. The diff is just a single added column, the older code will have no negative interaction with it.

But in general to undo a schema upgrade, you'd look into the file [App-Netdisco-DB-oldver-newver](App-Netdisco-DB-62-63), manually undo what's happening in there, and then execute

    delete from dbix_class_schema_versions where version = 63;

**Comment by anp135** [comment]
@rc9000, Christian, thanks a lot! I Undrestood about not major difference between schemes 62 and 63 and so nothing todo without that, but logs errors according scheme 63 with 45.007 version was a bit not pretty.

So now we will apply your instructions and get clear logs -), thanks!

**Comment by ollyg** [comment]
@rc9000 please can you take a look at 3aeed20b and see if it makes things better?

**Comment by rc9000** [comment]
@ollyg nice, looks pretty good here - around 400ms on a typical search string: https://explain.depesz.com/s/Sxg2

**Comment by ollyg** [comment]
version 2.046002 released to CPAN with a fix

**Comment by anp135** [comment]
@ollyg thanks o lot! Netdisco come back fast again _)))
