### ISSUE TITLE
crash on wildcard search

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#738]
## Expected Behavior

searching for '*' should return all results.

## Current Behavior

using '*' in search field crashed netdisco for some actions.

## Possible Solution

there would be a diff if i knew that :)
seems dancer stops at 10000 iterations? there are 16666 nodes in de the node table of this setup.

## Steps to Reproduce (for bugs)

1. upgrade netdisco to 2.046001
2. in the search field just type "*" & press search, ports are returned as expected:
![image](https://user-images.githubusercontent.com/39005454/88128591-9adf8080-cbd6-11ea-9016-ea77456a5d55.png)
3. now click device, no devices are returned:
![image](https://user-images.githubusercontent.com/39005454/88128671-c1052080-cbd6-11ea-9fd7-aed37be95c4b.png)
4. now click node
at first:
![image](https://user-images.githubusercontent.com/39005454/88128733-db3efe80-cbd6-11ea-9d5f-e8ccbd687a49.png)
then
![image](https://user-images.githubusercontent.com/39005454/88128765-e98d1a80-cbd6-11ea-80b5-305bd8f053ee.png)
5. logs say
```
[19286] 2020-07-22 02:46:13  warn App::Netdisco 2.046001 web
[19285] 2020-07-22 02:50:02 error request to GET /ajax/content/search/node crashed: core - template - undef error - WHILE loop terminated (> 10000 iterations)
 at /home/testdisc/perl5/lib/perl5/Dancer/Template/Abstract.pm line 91.
```

## Context

was trying to reproduce another issue

## Your Environment

* Netdisco version used: 2.046001
* SNMP::Info version used:  3.70

**Comment by ollyg** [comment]
Thanks, have applied a fix in
[master ef1e2616] #738 crash on wildcard search
