### ISSUE TITLE
netdisco do not support IP location search 

### ISSUE THREAD

**Issue by ggmo** [netdisco/netdisco#739]
In our DataCenter have many access switch for servers, but in netdisco not collect access mac .so can not locate the ip address with more details such as which access switch port | MAC-ADDR and so on . can add the feature in next version , thanks !

**Comment by inphobia** [comment]
would it be possible to fill out our "issue" form (the questionlist you get get when you click "new issue").

that info is crucial to to troubleshooting yr problem.
