### ISSUE TITLE
How to determine Cisco IOS interface uptime from MIBs?

### ISSUE THREAD

**Issue by jeremyschulman** [netdisco/netdisco#742]
As a member of a network infrastructure team saddled with legacy Cisco IOS equipment that does not offer interface "uptime" or "last flapped" as part of the CLI, I would like to understand how to obtain this information using SNMP MIB(s).  

As a follow-up from a [tweet](https://twitter.com/olwy/status/1296875881990950913), could you please explain this process algorithmically so that I can implement this solution in Python?

Thank you!
-- Jeremy

**Comment by jeremyschulman** [comment]
@ollyg - I am running the code in production now, and I am observing negative values for the link-uptime; which means the way I adapted the algorithm into python is not correct :-). 

I was wondering if you might have a few minutes to review the code and help me understand where I've gone wrong.

The code can be found here:
https://github.com/netpaca/netpaca-interfaces/blob/master/netpaca_interfaces/ios_snmp.py#L109

Thank you!

**Comment by jeremyschulman** [comment]
Ah, I _think_ I may have found the bug.  It has to do with the way I was interpreting the use of $dev_uptime vs. the value that was stored back.

**Comment by jeremyschulman** [comment]
Did some testing based on my hypothesis, and I believe I now have everything working as expected. 
(re)Closing.

**Comment by ollyg** [comment]
great to hear, many thanks
