### ISSUE TITLE
Network device serial numbers have trailing space

### ISSUE THREAD

**Issue by JustinYuYou** [netdisco/netdisco#744]
From the nit switch API: https://api.byu.edu:443/byuapi/network/v0/switches?source=Netdisco, the serial number in a list of switch have trailing space at the end of the serial number.
This is the example of the single device data
`"switches": [
    {
      "version": "WC.16.09.0004",
      "platform": "Aruba JL258A 2930F-8G-PoE+-2SFP+ Switch",
      "ip_address": "10.23.57.12",
      "hostname": "a51-101b-a1",
      "last_discover": "2020-08-26 18:42:37",
      "alias": null,
      "stacked": "chassis",
      "serial": "CN70HKZ0H0 ",
      "vendor": "hp",
      "physical_model": "2930F-8G-PoE+-2SFP+"
    },]`
As it can be seen, there is a trailing space appended to the end of the serial number.

**Comment by JeroenvIS** [comment]
This is the literal serial number as reported by the device; the device itself is appending the space.

I've seen it before on HP/Aruba switches, but never really dug into it. Just did a quick check over our installed base: 112 switches where a "trimmed" serial doesn't match the serial as stored, all HP/Aruba switches (formerly ProCurve), out of 572. Haven't found the exact pattern wrt model and firmware versions yet; for example, all our 2930F-8G switches run WC.16.02.0028 and report serials without traling space, our 2930M switches run WC.16.05.0007 and report serials without trailing space, but the rest of our 2930F switches on WC.16.05.0013 and higher do report trailing spaces in their serials.

In case you want to run a similar query against your database:
``netdisco-do psql -e "select os, model, count(*) from device where serial <> trim(serial) group by os, model;"``


So this is an issue on the device side (ie not in Netdisco or SNMP::Info). IMHO it's debatable whether eg SNMP::Info should fix it or not; as far as I know, there is no formal definition of what constitutes a valid serial number for a device. There would at least need to be some consensus about what is valid for a serial number and what not, as well as what should be done with "invalid" serials.

Side note: I temporarily changed the serial number in one of our "affected" switches (yes, there's a way to do that on these devices), but even when I explicitly change it to something without a space, when queried via SNMP the space is appended.

**Comment by jrbinks** [comment]
Hmm, I think a consensus that "A serial number would never end in a space, since it's clearly a mistake" would be easy to reach, that would solve the immediate issue.

**Comment by ollyg** [comment]
I'm happy for SNMP::Info to maintain the spaces, but also for Netdisco to strip them from start/end only, on storage. I think we already do some other similar munging.

**Comment by ollyg** [comment]
removed all whitespace, as we already do the same for Model

[master a146f53d] #744 remove whitespace from serial numbers

**Comment by jrbinks** [comment]
much appreciated

**Comment by ajw1980** [comment]
This change makes it so devices without a serial number can't be discovered. Previously, serial would be set to undefined. With this change, it is an empty string, so these devices get "failed to return valid serial". I changed line 51 in Properties.pm to this:
$device->set_column( serial => $serial || undef );

Which allows devices without a serial to be discovered. Not sure if this is the best change or not.

**Comment by ollyg** [comment]
Hi @ajw1980 

along with this change we also introduced a configuration setting (which is the one causing the log message you see)

https://github.com/netdisco/netdisco/wiki/Configuration#snmp_field_protection

the idea is that you can exclude a device or set of devices from this list and Netdisco will store the "empty" serial

actually, it catches you out because I guess the device existed in your Netdisco install before this change, so the database has a space character in the field, and then this setting is triggered

deleting the device and rediscovering might avoid the issue altogether (because it will clean the DB up)

or else trying this setting (as an example here, but change for your vendor/model/etc):

````
snmp_field_protection:
  device:
    serial: ['!model:DCS7508']
````

**Comment by ajw1980** [comment]
Ok, I made it like this to revert to the previous behavior for now:
```
snmp_field_protection:
  device:
    serial: ['!group:__ANY__']
```

Would it make sense to check if the existing value is empty in the database before failing this check?
