### ISSUE TITLE
snmp engine id error handling

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#747]
## Expected Behavior

failures on snmpengineid should be handled more gracefully.

## Current Behavior

i noticed this recently in my logs:
`Use of uninitialized value in unpack at /home/testdisc/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Properties.pm line 56.`

this seems to have been introduced in dc87a50076d7090d14ee7fb0ff42def63478cce1
#728

## Possible Solution

handle nosuchobject gracefully. can be set to null or an empty string perhaps.

## Steps to Reproduce (for bugs)

running discover on either esxi 6.7 or netscalers:
```
SNMP::Info::_global ports : IF-MIB::ifNumber.0 : .1.3.6.1.2.1.2.1.0
SNMP::Info::_global snmpEngineID : SNMP-FRAMEWORK-MIB::snmpEngineID.0 : .1.3.6.1.6.3.10.2.1.1.0
SNMP::Info::_global(snmpEngineID) NOSUCHOBJECT at /home/testdisc/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Properties.pm line 56.
Use of uninitialized value in unpack at /home/testdisc/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Properties.pm line 56.
[30614] 2020-10-10 22:57:21 debug -> run worker early/properties/100
```

## Your Environment

* Netdisco version used: 2.046002 (also seen in 2.046001)
* SNMP::Info version used: 3.70

## Device information

seen on both vmware esxi 6.7 with snmp v3 & citrix netscalers snmp v2.

**Comment by inphobia** [comment]
being lazy this is a small selection from the database:
![image](https://user-images.githubusercontent.com/39005454/95666853-393c0c00-0b5e-11eb-9237-5409702b57c3.png)

(the very last line in this output is a pseudodevice, which lacks an snmp_class)

**Comment by ollyg** [comment]
thanks, fixed in
[master 4cd0c3ee] #747 handle missing snmpEngineID
