### ISSUE TITLE
netdisco-web uninitialized mac errors

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#748]
## Current Behavior

getting this in my web log:
`Use of uninitialized value $args{"mac"} in pattern match (m//) at /home/testdisc/perl5/lib/perl5/NetAddr/MAC.pm line 128.`

## Possible Solution

i don't see this error in 2.044004, so it must be introduced recently.

## Steps to Reproduce (for bugs)

clicking on anything (vendor, model, os, version) in /inventory generates this error. 

side note: i ran netdisco-deploy & upgraded everything (schema, mibs & oui) as mentioned in the changelog

also, i have 2 devices in my db that don't report a mac address, might or might not be related.
first device is an asr1000 where we only have limited access, second in a netdisco pseudodevice:
![image](https://user-images.githubusercontent.com/39005454/95667036-bcf6f800-0b60-11eb-842d-01d6dc4c05aa.png)

## Context

at first glance does not seem to have any functional impact.

## Your Environment

* Netdisco version used: 2.046002
* SNMP::Info version used: 3.70
* db schema: 63
* net::macaddr: 0.96

**Comment by ollyg** [comment]
Can you try upgrading NetAddr::MAC ?

````
~/bin/localenv cpanm --notest NetAddr::MAC
````

**Comment by inphobia** [comment]
well, i was running netaddr::mac 0.96 & the release notes for .97 only mentioned perl 5.10 as min req chance.

just to be sure i updated everything with:
`cpan-outdated -p | cpanm` & restarted.
(made sure i was in localenv)

regretfully the error remains, though it has moved down a line (from 128 to 129):
`Use of uninitialized value $args{"mac"} in pattern match (m//) at /home/testdisc/perl5/lib/perl5/NetAddr/MAC.pm line 129.`
or
`Use of uninitialized value $args{"mac"} in pattern match (m//) at /home/testdisc/perl5/lib/perl5/NetAddr/MAC.pm line 129, <DATA> line 755.`

**Comment by JeroenvIS** [comment]
I believe that Muris/Alcatron also has this error, see mailing list thread "Netdisco 2.46.2 issues" (especially his addition at Tue, 13 Oct 2020 13:29:16 +1030) -> appears to cause crash in his case?

**Comment by ollyg** [comment]
Hmm well this is an attempt to fix:
[master c7b8c3bc] #748 always call NetAddr::MAC->new() with named mac param

**Comment by ollyg** [comment]
without a stack trace it's not easy to find where this is coming from in Netdisco, nor add debugging to show what args are being sent to NetAddr::MAC to make it die. do let me know if this patch fixes it.

**Comment by zoeloe** [comment]
running perl 5.22.1
Upgrade to netdisco 2.046005  leaves my netaddr::mac 0.95 in place.
Manual install of my netaddr::mac 0.97 needed. (with ~/bin/localenv cpanm --notest NetAddr::MAC)
FYI

**Comment by ollyg** [comment]
Thanks @zoeloe. Actually there is no difference between 0.95 and 0.97 other than documentation and tests, which is why I didn't bother to require an upgrade (but probably should have anyway).

Can you let me know if 2.046005 has removed the error/crash effect, though?

**Comment by zoeloe** [comment]
Ok, Thanks @ollyg  . Thanks for the followup.
For the 2.046005 error/crash effect. I'll post a followup after our Opsec team blasted my netdisco instance again. I'm "hoping" today seeing the logs (once a week).

**Comment by inphobia** [comment]
fixes the netdisco-web.log error in 2.046005.

still getting this in `netdisco-do discover` but seems harmless:
```
SNMP::Info::_global snmpEngineID : SNMP-FRAMEWORK-MIB::snmpEngineID.0 : .1.3.6.1.6.3.10.2.1.1.0
SNMP::Info::_global(snmpEngineID) NOSUCHOBJECT at /home/testdisc/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Properties.pm line 57.
```

only other remark i can give is that a netdisco pseudodevice uses sql null for snmp_engineid in the device table while devices with this issue return a blank string.

**Comment by zoeloe** [comment]
Followup regarding the error/crash effect: Our OpSec team hit the netdisco instance just now and this is what was logged:

::ffff:134.184.159.225 - - [20/Oct/2020:18:52:04 +0200] "GET /remote/fgt_lang?lang=/../../../..//////////dev/cmdb/sslvpn_websession HTTP/1.1" 200 7086 "-" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)"
Invalid boundary in content_type: '%{#context['com.opensymphony.xwork2.dispatcher.HttpServletResponse'].addHeader('X-Tenable','SKrAMVvK')}.multipart/form-data' at /home/netdisco/perl5/lib/perl5/Dancer/Request.pm line 144.
Invalid boundary in content_type: '%{(#_='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c','ipconfig','/all'}:{'bash','-c','id'})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}' at /home/netdisco/perl5/lib/perl5/Dancer/Request.pm line 144.
::ffff:134.184.159.225 - - [20/Oct/2020:18:52:04 +0200] "GET /QXSWYo1xjN58 HTTP/1.1" 200 7029 "-" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)"
::ffff:134.184.159.225 - - [20/Oct/2020:18:52:04 +0200] "GET / HTTP/1.1" 200 7026 "-" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)"
::ffff:134.184.159.225 - - [20/Oct/2020:18:52:04 +0200] "GET / HTTP/1.1" 200 7026 "-" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)"
Invalid boundary in content_type: '%{#context['com.opensymphony.xwork2.dispatcher.HttpServletResponse'].addHeader('X-Tenable','kzykSGon')}.multipart/form-data' at /home/netdisco/perl5/lib/perl5/Dancer/Request.pm line 144.
Invalid boundary in content_type: '%{(#_='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c','ipconfig','/all'}:{'bash','-c','id'})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}' at /home/netdisco/perl5/lib/perl5/Dancer/Request.pm line 144.

So, Yes, errors logged from Dancer/Request.pm in netdisco-web.log.

BUT: ip inventory seems to function OK at the moment.

Is it possible that 1 of the "netdisc-web-fg" running childs is stuck and that by chance the inventory request contacts a working child and sometimes the stuck child is contacted ?
Is there a way to check this behavior ? How can we test which child is malfunctioning ?

my 2 cents.

Regards,
TIA.

**Comment by zoeloe** [comment]
Our Opsec Team did it again today, and now netdisco the IP Inventory is broken.
The queries for the subnets CIDR subnet entry box work and give a result list to choose from while typing. So far OK.
But when hitting enter when a selected subnet the result is empty:

e.g. weblog:

::ffff:172.18.254.128 - - [29/Oct/2020:03:45:14 +0100] "GET /ajax/content/report/ipinventory?subnet=134.184.36.0%2F24&daterange=1970-01-01+to+2020-10-29&limit=2048 HTTP/1.1" 200 29944 "http://netdisco.vub.ac.be/report/ipinventory?subnet=134.184.36.0/24&daterange=1970-01-01+to+2020-10-29&limit=2048" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"
::ffff:172.18.254.128 - - [29/Oct/2020:03:45:15 +0100] "GET /javascripts/jquery-latest.min.js?_=1603939475989 HTTP/1.1" 200 92689 "http://netdisco.vub.ac.be/report/ipinventory?subnet=134.184.36.0/24&daterange=1970-01-01+to+2020-10-29&limit=2048" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"
::ffff:172.18.254.128 - - [29/Oct/2020:03:45:15 +0100] "GET /javascripts/jquery-ui.custom.min.js?_=1603939475990 HTTP/1.1" 200 33770 "http://netdisco.vub.ac.be/report/ipinventory?subnet=134.184.36.0/24&daterange=1970-01-01+to+2020-10-29&limit=2048" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"
::ffff:172.18.254.128 - - [29/Oct/2020:03:45:15 +0100] "GET /javascripts/jquery-history.js?_=1603939475991 HTTP/1.1" 200 14676 "http://netdisco.vub.ac.be/report/ipinventory?subnet=134.184.36.0/24&daterange=1970-01-01+to+2020-10-29&limit=2048" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"

Hope this helps
TIA

**Comment by LBegnaud** [comment]
i suggest making netdisco only listen locally, then setting up nginx to proxy it with some rate limiters and fail2ban to protect netdisco from scans/dos

**Comment by inphobia** [comment]
>  Is there a way to check this behavior ? How can we test which child is malfunctioning ?

while there are several options, perhaps the easiest way is to run only 1 web process and slow down the scan rate. while this can be timeconsuming it makes it a lot easier to correlate requests with errors. it's best documented here: https://github.com/netdisco/netdisco/wiki/Developing#tldr-i-just-want-to-clone-the-repo-and-get-started

`DBIC_TRACE=1 plackup -R share,lib,~/environments bin/netdisco-web-fg` or something close to that. do be aware that this will generate a lot of output.

**Comment by inphobia** [comment]
> i suggest making netdisco only listen locally, then setting up nginx to proxy it with some rate limiters and fail2ban to protect netdisco from scans/dos

hm, do you need to be logged in to make netdisco crash or can it be done without authentication?

**Comment by zoeloe** [comment]
Without being authenticated. The Nessus security scan has no knowledge off any login credentials.
It fires off several http requests, I guess, and some tests break something inside the netdisco webservice.
Thanks for the suggestions. I'll have to wait for the next nessus scan for more debug.
