### ISSUE TITLE
way to verbose logging in 2.046005

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#751]
somewhere between 2.046002 & 2.046005 my netdisco-web.log has become stupid verbose, even with the default log setting:
`log: 'warning'`

instead of logging errors in now logs every web request. this is not mentioned in the changelog/wiki.

i suspect this is due to https://github.com/netdisco/netdisco/commit/5839fd4404ce92d1553699a513b4c26f12621be6

it would be nice to either mention this change in the changelog, or better still, retain the default of only logging errors.

for more info: please check irc.

**Comment by ollyg** [comment]
I have reverted adding the ApacheLog Plack middleware which changed this

**Comment by inphobia** [comment]
just upgraded & can confirm the behaviour is no longer present
