### ISSUE TITLE
oui names incorrect in database

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#753]
## Expected Behavior

company names should be the same in the oui table as in the oui.txt file.

## Current Behavior

a select few companies that use non-ascii characters are inserted in the database incorrectly. here are a few examples:

```
00-0E-11   (hex)                BDT Büro und Datentechnik GmbH & Co.KG
000E11     (base 16)            BDT Büro und Datentechnik GmbH & Co.KG
                                Saline 29
                                Rottweil  Baden-Württemberg  D-78628
                                DE



60-89-B7   (hex)                KAEL MÜHENDİSLİK ELEKTRONİK TİCARET SANAYİ LİMİTED ŞİRKETİ
6089B7     (base 16)            KAEL MÜHENDİSLİK ELEKTRONİK TİCARET SANAYİ LİMİTED ŞİRKETİ
                                Atatürk Mah. 78 sokak ,No:10, Büyükalan Mevkii
                                Izmir  Aegean  35175
                                TR


48-91-53   (hex)                Weinmann Geräte für Medizin GmbH + Co. KG
489153     (base 16)            Weinmann Geräte für Medizin GmbH + Co. KG
                                Kronsaalsweg 40
                                Hamburg    D-22525
                                DE
```

the actual database (and as such node vendor report) looks like this:
![image](https://user-images.githubusercontent.com/39005454/97558378-51c07900-19dc-11eb-9826-d671a0106775.png)

manually changing the data in the database works which also fixes the node vendor report,, so it does not seem to be a database issue.

## Possible Solution

rework the regex in netdisco-deploy or some other magic to make utf8 work?

## Steps to Reproduce (for bugs)

1. run the following sql query:
```
SELECT * FROM public.oui
WHERE oui = '48:91:53' or oui = '60:89:b7' or oui = '00:0e:11'
ORDER BY oui ASC LIMIT 1000
```

## Your Environment

* Netdisco version used: 2.46.5
* SNMP::Info version used: 3:70
* db schema 63
* postgres 10.00.12

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
thanks for the report, fixed in
[master 84821f33] #753 fix UTF-8 handling of Company names in OUI

**Comment by inphobia** [comment]
perfect fix!
