### ISSUE TITLE
ASA 5585 - Multicontext support

### ISSUE THREAD

**Issue by MarcusCaepio** [netdisco/netdisco#754]
Hi all,
enjoying netdisco very much, but we have a problem with Cisco ASAs, with multiple contexts. When we connect to the "management" ip of the asa via snmp, we land on the "admin" context. But the really important things are stored in other contexts. So the main problem is theoretically not a netdisco problem. But I want to ask, if netdisco is able to detect, switch and scan all the 
 other contexts. Or do we have to configure a dedicated ip for SNMP in every context? I am curious, how you guys are managing such problems, as my core competence is **not** cisco :D 
Thanks in advance!
Cheers,
Marcus

**Comment by inphobia** [comment]
well, currently netdisco does not have support for most network virtualization stuff, be it vdc, vrf, vdom, ....

if you need the arp mappings https://metacpan.org/pod/App::Netdisco::SSHCollector::Platform::ASA might be the way to go. no idea if that supports multiple contexts, but if not it shouldn't be to hard to add.

if the asa contexts each have full snmp support you might get away with adding them as different devices. snmpv3 contexts could also be an option, but we only have an ios example of that: https://github.com/netdisco/netdisco/wiki/Vendor-Tips#snmpv3-support-on-cisco-ios

**Comment by MarcusCaepio** [comment]
Hi @inphobia 
arp mappings are already activated, but multi context is not supported- that's why I get 0 ARP entries back :)

**Comment by inphobia** [comment]
so i guess there's no equivalent of `show ip arp vrf all` on asas?

we've seen other devices with comparable issues.
for cisco ace loadbalancers we enumerate all contexts from the admin context & then build the arp tables:
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/SSHCollector/Platform/ACE.pm

another approach is what we do for voss, where you can specify the vrfs in the device_auth config:
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/SSHCollector/Platform/VOSS.pm

since i don't have asas anymore it's hard to say which is the best solution, but depending on how you can change contexts you should be able to use either of the above mentioned modules as a guide.

**Comment by ollyg** [comment]
Just to add that if the context prefix is not "vlan-" you can set it in
device_auth:

On some device platforms SNMPv3 contexts are used to macsuck each VLAN. For
> this you usually configure a common context "prefix", with Netdisco’s
> default being “vlan-” (i.e. vlan-1, vlan-2, etc). Add the context_prefix
> key to a stanza to override this default.

**Comment by ollyg** [comment]
Hi @MarcusCaepio I have reopened

**Comment by ollyg** [comment]
I think `context_prefix` is only used for SNMPv3 so far.

Yes, it looks like the ASA collector could be patched to support contexts as ACE does. Patches welcome! I don't have the hardware myself so cannot develop it here, sorry.

**Comment by inphobia** [comment]
https://github.com/netdisco/snmp-info/wiki/Simulating-Agents#snmpsim-snmprec-version has info on how to get the needed dumps to us to add support, but i it can take a while.

do read the privacy part:
https://github.com/netdisco/snmp-info/wiki/Simulating-Agents#%EF%B8%8F-privacy-and-sensitive-data-warning-%EF%B8%8F

**Comment by MarcusCaepio** [comment]
Hey all, sorry for late reply. I will clarify, if we can send you the asked information.

**Comment by haught** [comment]
For mac/arp suck try this - https://github.com/haught/netdisco/blob/ASAContext/lib/App/Netdisco/SSHCollector/Platform/ASAContext.pm

Wrote it quite a long time ago, and have been using it for a while.

**Comment by rc9000** [comment]
@haught I'm a bit late to the party but good stuff! It looks like this could fully replace the ASA.pm we have in stock netdisco now? Would you care to submit this as a PR?

**Comment by rc9000** [comment]
@haught @MarcusCaepio I have added ASAContext.pm. The forked version was a bit outdated, I have merged some improvements from ASA.pm into it. If somebody can give it a try once released that would be great, as I don't have access to a test device. If it works, we can propagate the new module to be the only ASA.pm - please let us know.

**Comment by ollyg** [comment]
Implemented in 2.052000 which has been released to CPAN, many thanks!

**Comment by MarcusCaepio** [comment]
@rc9000 @haught  Thanks a lot for your efforts. Unfortunately, I switched the team a few months ago and don't have access to ASAs anymore. So I cannot decide, if this issue can be closed or not (close it if you want :)  )
Cheers,
Marcus

**Comment by rc9000** [comment]
Well no worries, someone will probably try it at some point. Closing this for now.
