### ISSUE TITLE
Pb during install of Netdisco

### ISSUE THREAD

**Issue by Ben-49280** [netdisco/netdisco#759]
Hi everybody and happy new year !!!

During installation of Netdisco at this line: "curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco"

I have some errors: "Finding App:Netdisco on cpanmetadb failed" "Finding App:Netdisco () on mirror http://www.cpan.org failed"
"Couldn't find module or a distribution App:Netdisco"

Can everyone help me ?

TY.

Benoit.

**Comment by ollyg** [comment]
Unfortunately I cannot reproduce this issue

Can you try with another Perl module, such as:

`curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 Moo`

**Comment by Ben-49280** [comment]
No problem with this link, download OK...

**Comment by Ben-49280** [comment]
Can you help me ? Up !
Thank you ;)

**Comment by rc9000** [comment]
Hi Benoit 

I just tried and it works fine here as well. I assume you have some issues talking to the cpan.org servers. There is some  CDN stuff going on, including potentially going through IPv6 if your machine has a suitable interface.

     # host www.cpan.org
    www.cpan.org is an alias for cdn-fastly-sni.cpan.org.
    cdn-fastly-sni.cpan.org is an alias for dualstack.j.sni.global.fastly.net.
    dualstack.j.sni.global.fastly.net has address 151.101.194.132
    dualstack.j.sni.global.fastly.net has address 151.101.130.132
    dualstack.j.sni.global.fastly.net has address 151.101.66.132
    dualstack.j.sni.global.fastly.net has address 151.101.2.132
    dualstack.j.sni.global.fastly.net has IPv6 address 2a04:4e42::644
    dualstack.j.sni.global.fastly.net has IPv6 address 2a04:4e42:200::644
    dualstack.j.sni.global.fastly.net has IPv6 address 2a04:4e42:400::644
    dualstack.j.sni.global.fastly.net has IPv6 address 2a04:4e42:600::644 

Make sure that connecting to all of these works, or try by just putting a single IPv4 temporarily in /etc/hosts, e.g.

    151.101.66.132 www.cpan.org

Or test the basic connectivity to one of the IPv4 targets with curl like this:

    sdtest@ci03:~$ curl  -o test.tar.gz -H 'Host: www.cpan.org' http://151.101.130.132/authors/id/O/OL/OLIVER/App-Netdisco-2.047002.tar.gz
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 3896k  100 3896k    0     0  22.3M      0 --:--:-- --:--:-- --:--:-- 22.3M

If you're behind some kind of enterprise firewall/proxy, maybe check their logs as well.

**Comment by Ben-49280** [comment]
Hi Christian.

Result of host www.cpan.org command … Only IPV4 151.101.122.132. This is OK ?

Download of App-Netdisco-2.047002.tar.gz OK with IP 151.101.122.132 and all others IP of your host www.cpan.org command… 

Server Ubuntu : Firewall turned off and no proxy.

This command "curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco" :
=> Running on 14/12/2020 
=> KO on 23/12/2020

I install 2 servers on november with command "curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco" without problem.

Can you gimme an other command/link to download all installation elements for Netdisco ? (beginner on linux command…)

Thank you so much.

Regards,

Benoit.

**Comment by Ben-49280** [comment]
Can you help me more ?
TY

**Comment by ollyg** [comment]
I suspect the problem is access to the https://cpanmetadb.plackperl.org/ site, not CPAN itself

The https://cpanmetadb.plackperl.org/ site is used to gather metadata on modules and is needed by cpanm to work out the dependencies graph to install

Perhaps check you can access https://cpanmetadb.plackperl.org/v1.0/package/Plack ??

Or even https://cpanmetadb.plackperl.org/v1.0/package/App::Netdisco ??

**Comment by Ben-49280** [comment]
What's command line please ?
curl -L  https://cpanmetadb.plackperl.org/v1.0/package/ | perl - --notest --local-lib ~/perl5 App::Netdisco ?
Thanks.

**Comment by ollyg** [comment]
Hi @Ben-49280 no, I meant just check you can browse to that page from your computer's command line
