### ISSUE TITLE
Wide character error when running netdisco-deploy

### ISSUE THREAD

**Issue by brasswood** [netdisco/netdisco#762]
I am getting the following error when running netdisco-deploy:
```
{UNKNOWN}: Wide character at /home/netdisco/bin/netdisco-deploy line 253. at /home/netdisco/bin/netdisco-deploy line 259
```
It is an offline deployment, so I invoked the command like so: `~/bin/netdisco-deploy ~/oui.txt`
Is this a problem with `oui.txt`, or with `netdisco-deploy`?

**Comment by brasswood** [comment]
I have reverted the change from 84821f3, and the script finishes without the error.

**Comment by inphobia** [comment]
what kind of system are you running on? and do you have a utf-8 charset installed?

**Comment by ollyg** [comment]
thanks for the report - fixed in
[master 942e118e] #762 wide character error on deploy with local oui.txt
