### ISSUE TITLE
SVG export for neighbor map?

### ISSUE THREAD

**Issue by kkesper** [netdisco/netdisco#763]
This is a request for a new featuere.

## Expected Behavior
It would be very helpful for us, if there existed a way to export neighbor maps to SVG (or another vector graphics format).

## Current Behavior/Context
Currently it is only possible to print to PDF with the webbrowser. This produces a rendered graph which most often results in poor quality, if imported into other applications or documents.

I don't know if this is possible, but it seems as if the internal handling of maps is done as vectors anyway. So I hope for an easy solution :-) .

## Your Environment
* Netdisco version used: 2.47.2
* SNMP::Info version used: 3.70 

Thanks and best regards
Kurt

**Comment by inphobia** [comment]
hm, i see the issue but the current framework we use for the web part (d3 iirc) doesn't really have provisions for that.

we do provide graphviz export via the cli (`netdisco-do graph`), which - while very flexible and workable - could be easier. biggest issue is that d3 & graphviz use completely different options & syntax.

https://github.com/netdisco/netdisco/wiki/Network-Map & https://github.com/netdisco/netdisco/blob/416a6939ecce3dd0c0035d5d650a1bed04b0f1b6/share/config.yml#L430 have some info , but you'll most likely also need to read up on https://graphviz.gitlab.io/

stupid me forgot to document last time i tried it, but it can generate decents maps like
![image](https://user-images.githubusercontent.com/39005454/106061782-2857dc00-60f6-11eb-99c7-42853e95b239.png)

graphviz's .dot format lets you specify file types & presentation (it's just a format to descripe dependencies).
