### ISSUE TITLE
Storing of data for Port description, increase

### ISSUE THREAD

**Issue by Zapbam** [netdisco/netdisco#764]
## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
Is this ticket opened in error? I do not see any question or problem report.

**Comment by Zapbam** [comment]
Sorry hte info I typed when I opened the ticket did not remain.
however I wanted to find out if it is possible to increase field size that is stored for port description.
The database can stored up 254 characters for that field, but Netdisco must have a limit as it does not store the full port description.

is this an easy setting or is it a change request ?

thanks 

Andre

**Comment by Zapbam** [comment]
Sorry the info I typed when I opened the ticket did not remain.
however I wanted to find out if it is possible to increase field size that is stored for port description.
The database can stored up 254 characters for that field, but Netdisco must have a limit as it does not store the full port description.
is this an easy setting or is it a change request ?
thanks
Andre



[cid:Stemconnectlogoemailsign460x258px_e5b38617-4338-420d-9947-df6bcd14cdc9.png]
        ANDRE BAM
Chief Technical Officer

Telephone: 087 980 3003
Cellphone: 082 852 3761
Email: andre.bam@stem.co.za

www.stem.co.za<https://www.stem.co.za/>
[cid:Linkedin_5f78d6de-0d55-45b6-8f28-f618bfe63eb9.PNG]<https://www.linkedin.com/company/stem-the-origin-of-connectivity/>

_______________________________________________________________________________________________________

**Comment by ollyg** [comment]
Hi @Zapbam 

In fact the database field is type "text" which is of unlimited length in PostgreSQL.

So, perhaps the data returned from your device is truncated? You could run the following commands to see:

````
~/bin/netdisco-do show -d 1.1.1.1 -e interfaces
~/bin/netdisco-do show -d 1.1.1.1 -e i_description
~/bin/netdisco-do show -d 1.1.1.1 -e i_name
````

**Comment by rc9000** [comment]
@Zapbam the MIB definition for ifDescr and ifAlias says it's an OCTET STRING (0..255), so if it's not the device already also the SNMP libraries on the way might truncate the value. It's probably not safe to rely on the characters past 2^8 for anything, even if the cli/admin-ui on your device lets you set a longer string.

    .1.3.6.1.2.1.2.2.1.2
    ifDescr OBJECT-TYPE
      -- FROM	IF-MIB, RFC1213-MIB
      -- TEXTUAL CONVENTION DisplayString
      SYNTAX	OCTET STRING (0..255) 
      DISPLAY-HINT	"255a"
      MAX-ACCESS	read-only
      STATUS	current
      DESCRIPTION	"A textual string containing information about the
                interface.  This string should include the name of the
                manufacturer, the product name and the version of the
                interface hardware/software."
    ::= { iso(1) org(3) dod(6) internet(1) mgmt(2) mib-2(1) interfaces(2) ifTable(2) ifEntry(1) 2 }

**Comment by goncas23** [comment]
@Zapbam I just experienced the same issue: the port was being truncated to 64 characters, since it is the default size returned by the ifAlias OID.
If you run `snmp ifmib ifalias long` on the device(s) you are monitoring, the ifAlias OID will be able to return up to 256 characters.

Hope this helps!

**Comment by ollyg** [comment]
Thanks, have added this to the Vendor Tips page:
https://github.com/netdisco/netdisco/wiki/Vendor-Tips#truncated-short-interface-descriptions
