### ISSUE TITLE
Excluding all IPs from Reverse DNS lookups or disabling DNS

### ISSUE THREAD

**Issue by Cacha21** [netdisco/netdisco#767]
I would like to know if there is any way to 100% disable all Reverse DNS lookups for all devices in my network.

The vast majority of my devices are not in the DNS server and many of them even have what are usually public IP addresses that our DNS server resolves to domains in Japan, Argentina or Brazil amongst other countries.

I know that it is possible to exclude some networks or hosts by entering them under the "no" section here:

dns:
  max_outstanding: 50
  hosts_file: '/etc/hosts'
  no: ['group:__LOCAL_ADDRESSES__','169.254.0.0/16']

but if I want to exclude most of my subnets I have to add here over 30 subnets and even then Netdisco is still resolving my device's IP to a name and using such name for the device in the web interface. I'd rather always show the Sysname for a device.

Apparently excluding them in the config file only prevents the resolution of the IP addresses that are shown in the Addresses tab inside a device (DNS column).

I hope to be clear.

Thanks in advance!

**Comment by ollyg** [comment]
Hi @Cacha21 

Yes, the special group `__ANY__` will match any host:

````
dns:
  max_outstanding: 50
  hosts_file: '/etc/hosts'
  no: ['group:__ANY__']
````

I hope this helps!

**Comment by ollyg** [comment]
hmmm you are right there are cases in the codebase where reverse lookups happen anyway. I'll look into them!

**Comment by ollyg** [comment]
thanks, fixed in 74b9583f

**Comment by ollyg** [comment]
had to revert, so will revisit this with a fix not needing special dependency resolution order

**Comment by ollyg** [comment]
reimplemented in f1224b087c314f87d21768f815f88d71b0f0fbae
and will be in the next release
