### ISSUE TITLE
MAC address and connected host not show

### ISSUE THREAD

**Issue by gmourani** [netdisco/netdisco#768]
## Expected Behavior
On Cisco Sx220 series, the connected host and related MAC address doesn't show. Also, the uplink interface which is the onlt interface IP information returned is miss interpreted. On the switch, it's connected and configured on port 25 but appears as port 24 on Netdisco.

## Current Behavior
Nothing appear in the "Connected Nodes & Devices " Collunm.

## Steps to Reproduce (for bugs)
Try to add a Cisco SG220 switch into Netdisco.

## Your Environment
* Netdisco version used: 2.47.2
* SNMP::Info version used: 3.71

## Config info (deployment.yml)
discover_waps: true
discover_phones: false
no_auth: true
path: /netdisco

## Device information
[netdisco@Adm-Ss root]$ ~/bin/netdisco-do macsuck -d 10.1.11.50 -DI
[62272] 2021-02-15 12:43:17  info App::Netdisco version 2.047002 loaded.
[62272] 2021-02-15 12:43:17  info macsuck: [10.1.11.50] started at Mon Feb 15 07:43:17 2021
[62272] 2021-02-15 12:43:17 debug macsuck: running with timeout 600s
[62272] 2021-02-15 12:43:17 debug => running workers for phase: check
[62272] 2021-02-15 12:43:17 debug -> run worker check/_base_/0
[62272] 2021-02-15 12:43:17 debug Macsuck is able to run.
[62272] 2021-02-15 12:43:17 debug => running workers for phase: main
[62272] 2021-02-15 12:43:17 debug -> run worker main/nodes/100
[62272] 2021-02-15 12:43:17 debug snmp reader cache warm: [10.1.11.50]
[62272] 2021-02-15 12:43:17 debug [10.1.11.50:161] try_connect with ver: 2, class: SNMP::Info::Layer2::CiscoSB, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.71
SNMP::Info::device_type() layers:01001111 id:9 sysDescr:"Cisco Sx220 Series Switch Software, Version 1.1.2.1, RELEASE SOFTWARE Copyright (c) 2014-2017 by Cisco Systems, Inc. Compiled Thu Feb 23 10:42:03 UTC 2017"
SNMP::Info::_load_attr i_name : IF-MIB::ifName : .1.3.6.1.2.1.31.1.1.1.1
SNMP::Info::_load_attr qb_fw_port : Q-BRIDGE-MIB::dot1qTpFdbPort : .1.3.6.1.2.1.17.7.1.2.2.1.2

[62272] 2021-02-15 12:53:17 debug -> HASH(0x2749630)
[62272] 2021-02-15 12:53:17 debug {}
[62272] 2021-02-15 12:53:17 debug -> run worker main/wirelessnodes/100
SNMP::Info::_validate_autoload_method(cd11_txrate) Unable to resolve method.
[62272] 2021-02-15 12:53:17 debug => running workers for phase: late
[62272] 2021-02-15 12:53:17 debug -> run worker late/hooks/0
[62272] 2021-02-15 12:53:17 debug  [10.1.11.50] hooks - 0 queued
[62272] 2021-02-15 12:53:17 debug macsuck: timed out!
[62272] 2021-02-15 12:53:17 debug job timed out after 600 sec
[62272] 2021-02-15 12:53:17  info macsuck: finished at Mon Feb 15 07:53:17 2021
[62272] 2021-02-15 12:53:17  info macsuck: status info:  [10.1.11.50] hooks - 0 queued
[netdisco@Adm-Ss-Blesk root]$

[netdisco@Adm-Ss root]$ ~/bin/netdisco-do show -d 10.1.11.50 -e specify -DI
[47149] 2021-02-15 13:04:30  info App::Netdisco version 2.047002 loaded.
[47149] 2021-02-15 13:04:30  info show: [10.1.11.50]/specify started at Mon Feb 15 08:04:30 2021
[47149] 2021-02-15 13:04:31 debug show: running with timeout 600s
[47149] 2021-02-15 13:04:31 debug => running workers for phase: check
[47149] 2021-02-15 13:04:31 debug -> run worker check/_base_/0
[47149] 2021-02-15 13:04:31 debug Show is able to run
[47149] 2021-02-15 13:04:31 debug => running workers for phase: main
[47149] 2021-02-15 13:04:31 debug -> run worker main/_base_/100
[47149] 2021-02-15 13:04:31 debug snmp reader cache warm: [10.1.11.50]
[47149] 2021-02-15 13:04:31 debug [10.1.11.50:161] try_connect with ver: 2, class: SNMP::Info::Layer2::CiscoSB, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.71
SNMP::Info::device_type() layers:01001111 id:9 sysDescr:"Cisco Sx220 Series Switch Software, Version 1.1.2.1, RELEASE SOFTWARE Copyright (c) 2014-2017 by Cisco Systems, Inc. Compiled Thu Feb 23 10:42:03 UTC 2017"
SNMP::Info 3.71
SNMP::Info::device_type() layers:01001111 id:9 sysDescr:"Cisco Sx220 Series Switch Software, Version 1.1.2.1, RELEASE SOFTWARE Copyright (c) 2014-2017 by Cisco Systems, Inc. Compiled Thu Feb 23 10:42:03 UTC 2017"
SNMP::Info::specify() - Changed Class to SNMP::Info::Layer2::CiscoSB.
SNMP::Info::_validate_autoload_method(_data_printer) Unable to resolve method.
SNMP::Info::Layer2::CiscoSB  {
    Parents       SNMP::Info::Layer2, SNMP::Info::EtherLike, SNMP::Info::CiscoStats, SNMP::Info::CiscoConfig, SNMP::Info::CDP, Exporter
    Linear @ISA   SNMP::Info::Layer2::CiscoSB, SNMP::Info::Layer2, SNMP::Info, Exporter, SNMP::Info::Bridge, SNMP::Info::Entity, SNMP::Info::PowerEthernet, SNMP::Info::LLDP, SNMP::Info::DocsisHE, SNMP::Info::EtherLike, SNMP::Info::CiscoStats, SNMP::Info::CiscoConfig, SNMP::Info::CDP
    public methods (7) : i_duplex, interfaces, model, os, os_ver, serial, vendor
    private methods (0)
    internals: {
        args                {
            AutoSpecify         0,
            BulkRepeaters       20,
            BulkWalk            1,
            Community           "SNMpCsdP",
            Debug               1,
            DebugSNMP           0,
            DestHost            "10.1.11.50",
            IgnoreNetSNMPConf   1,
            MibDirs             [
                [0]  "/home/netdisco/netdisco-mibs/3com",
                [1]  "/home/netdisco/netdisco-mibs/adtran",
                [2]  "/home/netdisco/netdisco-mibs/aerohive",
                [3]  "/home/netdisco/netdisco-mibs/alcatel",
                [4]  "/home/netdisco/netdisco-mibs/allied",
                [5]  "/home/netdisco/netdisco-mibs/apc",
                [6]  "/home/netdisco/netdisco-mibs/arista",
                [7]  "/home/netdisco/netdisco-mibs/aruba",
                [8]  "/home/netdisco/netdisco-mibs/asante",
                [9]  "/home/netdisco/netdisco-mibs/avaya",
                [10] "/home/netdisco/netdisco-mibs/bluecoat",
                [11] "/home/netdisco/netdisco-mibs/bluesocket",
                [12] "/home/netdisco/netdisco-mibs/brother",
                [13] "/home/netdisco/netdisco-mibs/cabletron",
                [14] "/home/netdisco/netdisco-mibs/ceragon",
                [15] "/home/netdisco/netdisco-mibs/cern",
                [16] "/home/netdisco/netdisco-mibs/checkpoint",
                [17] "/home/netdisco/netdisco-mibs/ciena",
                [18] "/home/netdisco/netdisco-mibs/cisco",
                [19] "/home/netdisco/netdisco-mibs/ciscosb",
                [20] "/home/netdisco/netdisco-mibs/citrix",
                [21] "/home/netdisco/netdisco-mibs/clavister",
                [22] "/home/netdisco/netdisco-mibs/cloudgenix",
                [23] "/home/netdisco/netdisco-mibs/colubris",
                [24] "/home/netdisco/netdisco-mibs/cyclades",
                [25] "/home/netdisco/netdisco-mibs/d-link",
                [26] "/home/netdisco/netdisco-mibs/dell",
                [27] "/home/netdisco/netdisco-mibs/eaton",
                [28] "/home/netdisco/netdisco-mibs/efficientip",
                [29] "/home/netdisco/netdisco-mibs/enterasys",
                [30] "/home/netdisco/netdisco-mibs/etherwan",
                [31] "/home/netdisco/netdisco-mibs/exinda",
                [32] "/home/netdisco/netdisco-mibs/EXTRAS",
                [33] "/home/netdisco/netdisco-mibs/extreme",
                [34] "/home/netdisco/netdisco-mibs/extricom",
                [35] "/home/netdisco/netdisco-mibs/f5",
                [36] "/home/netdisco/netdisco-mibs/force10",
                [37] "/home/netdisco/netdisco-mibs/fortinet",
                [38] "/home/netdisco/netdisco-mibs/foundry",
                [39] "/home/netdisco/netdisco-mibs/gigamon",
                [40] "/home/netdisco/netdisco-mibs/h3c",
                [41] "/home/netdisco/netdisco-mibs/hirschmann",
                [42] "/home/netdisco/netdisco-mibs/hp",
                [43] "/home/netdisco/netdisco-mibs/hpe",
                [44] "/home/netdisco/netdisco-mibs/huawei",
                [45] "/home/netdisco/netdisco-mibs/ibm",
                [46] "/home/netdisco/netdisco-mibs/juniper",
                [47] "/home/netdisco/netdisco-mibs/lancom",
                [48] "/home/netdisco/netdisco-mibs/lantronix",
                [49] "/home/netdisco/netdisco-mibs/lenovo",
                [50] "/home/netdisco/netdisco-mibs/liebert",
                [51] "/home/netdisco/netdisco-mibs/mediant",
                [52] "/home/netdisco/netdisco-mibs/meraki",
                [53] "/home/netdisco/netdisco-mibs/meru",
                [54] "/home/netdisco/netdisco-mibs/microsens",
                [55] "/home/netdisco/netdisco-mibs/mikrotik",
                [56] "/home/netdisco/netdisco-mibs/moser-baer",
                [57] "/home/netdisco/netdisco-mibs/motorola",
                [58] "/home/netdisco/netdisco-mibs/moxa",
                [59] "/home/netdisco/netdisco-mibs/nateks",
                [60] "/home/netdisco/netdisco-mibs/net-snmp",
                [61] "/home/netdisco/netdisco-mibs/netapp",
                [62] "/home/netdisco/netdisco-mibs/netgear",
                [63] "/home/netdisco/netdisco-mibs/netonix",
                [64] "/home/netdisco/netdisco-mibs/netscreen",
                [65] "/home/netdisco/netdisco-mibs/nexans",
                [66] "/home/netdisco/netdisco-mibs/nortel",
                [67] "/home/netdisco/netdisco-mibs/northerndesign",
                [68] "/home/netdisco/netdisco-mibs/oneaccess",
                [69] "/home/netdisco/netdisco-mibs/opengear",
                [70] "/home/netdisco/netdisco-mibs/packetfront",
                [71] "/home/netdisco/netdisco-mibs/paloalto",
                [72] "/home/netdisco/netdisco-mibs/pica8",
                [73] "/home/netdisco/netdisco-mibs/pulsesecure-gateway",
                [74] "/home/netdisco/netdisco-mibs/rad",
                [75] "/home/netdisco/netdisco-mibs/redlionram",
                [76] "/home/netdisco/netdisco-mibs/rfc",
                [77] "/home/netdisco/netdisco-mibs/rittal",
                [78] "/home/netdisco/netdisco-mibs/riverbed",
                [79] "/home/netdisco/netdisco-mibs/ruckus",
                [80] "/home/netdisco/netdisco-mibs/schleifenbauer",
                [81] "/home/netdisco/netdisco-mibs/sentry",
                [82] "/home/netdisco/netdisco-mibs/siemens",
                [83] "/home/netdisco/netdisco-mibs/sixnet",
                [84] "/home/netdisco/netdisco-mibs/sonicwall",
                [85] "/home/netdisco/netdisco-mibs/teleste",
                [86] "/home/netdisco/netdisco-mibs/teltonika",
                [87] "/home/netdisco/netdisco-mibs/tplink",
                [88] "/home/netdisco/netdisco-mibs/trapeze",
                [89] "/home/netdisco/netdisco-mibs/vmware",
                [90] "/home/netdisco/netdisco-mibs/wipipe",
                [91] "/home/netdisco/netdisco-mibs/xirrus"
            ],
            NonIncreasing       0,
            RemotePort          161,
            Retries             0,
            Session             SNMP::Session,
            Timeout             3000000,
            Version             2
        },
        BulkRepeaters       20,
        BulkWalk            1,
        class               "SNMP::Info::Layer2::CiscoSB",
        debug               1,
        funcs               {
            bp_index                                   "dot1dBasePortIfIndex",
            bp_port                                    "dot1dBasePortCircuit",
            bs_mac                                     "dot1dStaticAddress",
            bs_port                                    "dot1dStaticReceivePort",
            bs_status                                  "dot1dStaticStatus",
            bs_to                                      "dot1dStaticAllowedToGoTo",
            cdp_addr                                   "cdpCacheAddress",
            cdp_capabilities                           "cdpCacheCapabilities",
            cdp_dev_id                                 "cdpCacheDeviceId",
            cdp_dev_port                               "cdpCacheDevicePort",
            cdp_domain                                 "cdpCacheVTPMgmtDomain",
            cdp_duplex                                 "cdpCacheDuplex",
            cdp_platform                               "cdpCachePlatform",
            cdp_power                                  "cdpCachePowerConsumption",
            cdp_pri_mgmt_addr                          "cdpCachePrimaryMgmtAddr",
            cdp_pri_mgmt_type                          "cdpCachePrimaryMgmtAddrType",
            cdp_proto                                  "cdpCacheAddressType",
            cdp_sec_mgmt_addr                          "cdpCacheSecondaryMgmtAddr",
            cdp_sec_mgmt_type                          "cdpCacheSecondaryMgmtAddrType",
            cdp_ver                                    "cdpCacheVersion",
            cdp_vlan                                   "cdpCacheNativeVLAN",
            ci_images                                  "ciscoImageString",
            cisco_flash_size                           "ciscoFlashDeviceSize",
            cisco_mem_free                             "ciscoMemoryPoolFree",
            cisco_mem_used                             "ciscoMemoryPoolUsed",
            config_copy_complete_time                  "ccCopyTimeCompleted",
            config_copy_start_time                     "ccCopyTimeStarted",
            config_copy_state                          "ccCopyState",
            config_dest_type                           "ccCopyDestFileType",
            config_fail_cause                          "ccCopyFailCause",
            config_filename                            "ccCopyFileName",
            config_notify_complete                     "ccCopyNotificationOnCompletion",
            config_password                            "ccCopyUserPassword",
            config_protocol                            "ccCopyProtocol",
            config_row_status                          "ccCopyEntryRowStatus",
            config_server_addr                         "ccCopyServerAddress",
            config_source_type                         "ccCopySourceFileType",
            config_username                            "ccCopyUserName",
            docs_cmts_cm_down_channel_if_index         "docsIfCmtsCmStatusDownChannelIfIndex",
            docs_cmts_cm_up_channel_if_index           "docsIfCmtsCmStatusUpChannelIfIndex",
            docs_if_cmts_cm_status_inet_address        "docsIfCmtsCmStatusInetAddress",
            docs_if_cmts_cm_status_inet_address_type   "docsIfCmtsCmStatusInetAddressType",
            docs_if3_cmts_cm_status_md_if_index        "docsIf3CmtsCmRegStatusMdIfIndex",
            e_alias                                    "entPhysicalAlias",
            e_class                                    "entPhysicalClass",
            e_descr                                    "entPhysicalDescr",
            e_fru                                      "entPhysicalIsFRU",
            e_fwver                                    "entPhysicalFirmwareRev",
            e_hwver                                    "entPhysicalHardwareRev",
            e_id                                       "entPhysicalAssetID",
            el_chipset                                 "dot3StatsEtherChipSet",
            el_coll_excess                             "dot3StatsExcessiveCollisions",
            el_coll_freq                               "dot3CollFrequencies",
            el_coll_late                               "dot3StatsLateCollisions",
            el_coll_mult                               "dot3StatsMultipleCollisionFrames",
            el_coll_single                             "dot3StatsSingleCollisionFrames",
            el_duplex                                  "dot3StatsDuplexStatus",
            el_error_alignment                         "dot3StatsAlignmentErrors",
            el_error_cs                                "dot3StatsCarrierSenseErrors",
            el_error_fcs                               "dot3StatsFCSErrors",
            el_error_frame                             "dot3StatsFrameTooLongs",
            el_error_mac_rec                           "dot3StatsInternalMacReceiveErrors",
            el_error_mac_xmit                          "dot3StatsInternalMacTransmitErrors",
            el_error_sqe                               "dot3StatsSQETestErrors",
            el_error_symbol                            "dot3StatsSymbolErrors",
            el_index                                   "dot3StatsIndex",
            el_xmit_defer                              "dot3StatsDeferredTransmissions",
            e_map                                      "entAliasMappingIdentifier",
            e_model                                    "entPhysicalModelName",
            e_name                                     "entPhysicalName",
            e_parent                                   "entPhysicalContainedIn",
            e_pos                                      "entPhysicalParentRelPos",
            e_serial                                   "entPhysicalSerialNum",
            e_swver                                    "entPhysicalSoftwareRev",
            e_type                                     "entPhysicalVendorType",
            e_vendor                                   "entPhysicalMfgName",
            flash_copy_address                         "ciscoFlashCopyServerAddress",
            flash_copy_cmd                             "ciscoFlashCopyCommand",
            flash_copy_dest                            "ciscoFlashCopyDestinationName",
            flash_copy_protocol                        "ciscoFlashCopyProtocol",
            flash_copy_row_status                      "ciscoFlashCopyEntryStatus",
            flash_copy_source                          "ciscoFlashCopySourceName",
            fw_mac                                     "dot1dTpFdbAddress",
            fw_port                                    "dot1dTpFdbPort",
            fw_status                                  "dot1dTpFdbStatus",
            i_alias                                    "ifAlias",
            i_bad_proto_in                             "ifInUnknownProtos",
            i_description                              "ifDescr",
            i_discards_in                              "ifInDiscards",
            i_discards_out                             "ifOutDiscards",
            i_errors_in                                "ifInErrors",
            i_errors_out                               "ifOutErrors",
            i_index                                    "ifIndex",
            i_lastchange                               "ifLastChange",
            i_mac                                      "ifPhysAddress",
            i_mtu                                      "ifMtu",
            i_name                                     "ifName",
            interfaces                                 "ifIndex",
            i_octet_in                                 "ifInOctets",
            i_octet_in64                               "ifHCInOctets",
            i_octet_out                                "ifOutOctets",
            i_octet_out64                              "ifHCOutOctets",
            ip_broadcast                               "ipAdEntBcastAddr",
            i_pkts_bcast_in                            "ifInBroadcastPkts",
            i_pkts_bcast_in64                          "ifHCInBroadcastPkts",
            i_pkts_bcast_out                           "ifOutBroadcastPkts",
            i_pkts_bcast_out64                         "ifHCOutBroadcastPkts",
            i_pkts_multi_in                            "ifInMulticastPkts",
            i_pkts_multi_in64                          "ifHCInMulticastPkts",
            i_pkts_multi_out                           "ifOutMulticastPkts",
            i_pkts_multi_out64                         "ifHCOutMulticastPkts",
            i_pkts_nucast_in                           "ifInNUcastPkts",
            i_pkts_nucast_out                          "ifOutNUcastPkts",
            i_pkts_ucast_in                            "ifInUcastPkts",
            i_pkts_ucast_in64                          "ifHCInUcastPkts",
            i_pkts_ucast_out                           "ifOutUcastPkts",
            i_pkts_ucast_out64                         "ifHCOutUcastPkts",
            ipr_age                                    "ipRouteAge",
            ipr_dest                                   "ipRouteNextHop",
            ipr_if                                     "ipRouteIfIndex",
            ipr_info                                   "ipRouteInfo",
            ipr_mask                                   "ipRouteMask",
            ipr_proto                                  "ipRouteProto",
            ipr_route                                  "ipRouteDest",
            ipr_type                                   "ipRouteType",
            ipr_1                                      "ipRouteMetric1",
            ipr_2                                      "ipRouteMetric2",
            ipr_3                                      "ipRouteMetric3",
            ipr_4                                      "ipRouteMetric4",
            ipr_5                                      "ipRouteMetric5",
            i_qlen_out                                 "ifOutQLen",
            is_edgeport_admin                          "dot1dStpPortAdminEdgePort",
            is_edgeport_oper                           "dot1dStpPortOperEdgePort",
            i_specific                                 "ifSpecific",
            i_speed                                    "ifSpeed",
            i_speed_high                               "ifHighSpeed",
            i_stack_status                             "ifStackStatus",
            i_type                                     "ifType",
            i_up                                       "ifOperStatus",
            i_up_admin                                 "ifAdminStatus",
            lldp_lman_addr                             "lldpLocManAddrIfId",
            lldp_lport_desc                            "lldpLocPortDesc",
            lldp_lport_id                              "lldpLocPortId",
            lldp_rem_asset                             "lldpXMedRemAssetID",
            lldp_rem_cap_spt                           "lldpRemSysCapSupported",
            lldp_rem_desc                              "lldpRemPortDesc",
            lldp_rem_fw_rev                            "lldpXMedRemFirmwareRev",
            lldp_rem_hw_rev                            "lldpXMedRemHardwareRev",
            lldp_rem_id                                "lldpRemChassisId",
            lldp_rem_id_type                           "lldpRemChassisIdSubtype",
            lldp_rem_media_cap                         "lldpXMedRemCapCurrent",
            lldp_rem_media_cap_spt                     "lldpXMedRemCapSupported",
            lldp_rem_model                             "lldpXMedRemModelName",
            lldp_rem_pid                               "lldpRemPortId",
            lldp_rem_pid_type                          "lldpRemPortIdSubtype",
            lldp_rem_serial                            "lldpXMedRemSerialNum",
            lldp_rem_sw_rev                            "lldpXMedRemSoftwareRev",
            lldp_rem_sys_cap                           "lldpRemSysCapEnabled",
            lldp_rem_sysdesc                           "lldpRemSysDesc",
            lldp_rem_sysname                           "lldpRemSysName",
            lldp_rem_vendor                            "lldpXMedRemMfgName",
            lldp_rman_addr                             "lldpRemManAddrIfSubtype",
            new_ip_index                               "ipAddressIfIndex",
            new_ip_prefix                              "ipAddressPrefix",
            new_ip_type                                "ipAddressType",
            old_ip_index                               "ipAdEntIfIndex",
            old_ip_netmask                             "ipAdEntNetMask",
            old_ip_table                               "ipAdEntAddr",
            peth_port_admin                            "pethPsePortAdminEnable",
            peth_port_class                            "pethPsePortPowerClassifications",
            peth_port_power                            "rlPethPsePortOutputPower",
            peth_port_status                           "pethPsePortDetectionStatus",
            peth_power_consumption                     "pethMainPseConsumptionPower",
            peth_power_status                          "pethMainPseOperStatus",
            peth_power_threshold                       "pethMainPseUsageThreshold",
            peth_power_watts                           "pethMainPsePower",
            qb_cv_egress                               "dot1qVlanCurrentEgressPorts",
            qb_cv_stat                                 "dot1qVlanStatus",
            qb_cv_untagged                             "dot1qVlanCurrentUntaggedPorts",
            qb_fw_port                                 "dot1qTpFdbPort",
            qb_fw_status                               "dot1qTpFdbStatus",
            qb_i_vlan                                  "dot1qPvid",
            qb_i_vlan_in_flt                           "dot1qPortIngressFiltering",
            qb_i_vlan_type                             "dot1qPortAcceptableFrameTypes",
            qb_v_egress                                "dot1qVlanStaticEgressPorts",
            qb_v_fbdn_egress                           "dot1qVlanForbiddenEgressPorts",
            qb_v_name                                  "dot1qVlanStaticName",
            qb_v_stat                                  "dot1qVlanStaticRowStatus",
            qb_v_untagged                              "dot1qVlanStaticUntaggedPorts",
            stp_i_mac                                  "dot1dBaseBridgeAddress",
            stp_i_ntop                                 "dot1dStpTopChanges",
            stp_i_priority                             "dot1dStpPriority",
            stp_i_root                                 "dot1dStpDesignatedRoot",
            stp_i_root_port                            "dot1dStpRootPort",
            stp_i_time                                 "dot1dStpTimeSinceTopologyChange",
            stp_p_bridge                               "dot1dStpPortDesignatedBridge",
            stp_p_cost                                 "dot1dStpPortPathCost",
            stp_p_id                                   "dot1dStpPort",
            stp_p_port                                 "dot1dStpPortDesignatedPort",
            stp_p_priority                             "dot1dStpPortPriority",
            stp_p_root                                 "dot1dStpPortDesignatedRoot",
            stp_p_state                                "dot1dStpPortState",
            v_name                                     "dot1qVlanStaticName"
        },
        globals             {
            b_mac                       "dot1dBaseBridgeAddress",
            b_ports                     "dot1dBaseNumPorts",
            b_type                      "dot1dBaseType",
            cat_cpu                     "cpmCPUTotal5sec.9",
            cat_cpu_1min                "cpmCPUTotal1min.9",
            cat_cpu_5min                "cpmCPUTotal5min.9",
            cdp_gid                     "cdpGlobalDeviceId",
            cdp_holdtime                "cdpGlobalHoldTime",
            cdp_interval                "cdpGlobalMessageInterval",
            cdp_run                     "cdpGlobalRun",
            contact                     "sysContact",
            descr                       "sysDescr",
            description                 "sysDescr",
            ent_physical_software_rev   "entPhysicalSoftwareRev.1",
            id                          "sysObjectID",
            ios_cpu                     "1.3.6.1.4.1.9.2.1.56.0",
            ios_cpu_1min                "1.3.6.1.4.1.9.2.1.57.0",
            ios_cpu_5min                "1.3.6.1.4.1.9.2.1.58.0",
            ipforwarding                "ipForwarding",
            layers                      "sysServices",
            lldp_sys_cap                "lldpLocSysCapEnabled",
            lldp_sysdesc                "lldpLocSysDesc",
            lldp_sysname                "lldpLocSysName",
            location                    "sysLocation",
            mac                         "rndBasePhysicalAddress",
            name                        "sysName",
            old_write_mem               "writeMem",
            old_write_net               "writeNet",
            ports                       "ifNumber",
            qb_next_vlan_index          "dot1qNextFreeLocalVlanIndex",
            qb_vlans                    "dot1qNumVlans",
            qb_vlans_max                "dot1qMaxSupportedVlans",
            rom_id                      "romId",
            serial1                     ".1.3.6.1.4.1.9.3.6.3.0",
            stp_priority                "dot1dStpPriority",
            stp_root                    "dot1dStpDesignatedRoot",
            stp_root_port               "dot1dStpRootPort",
            stp_time                    "dot1dStpTimeSinceTopologyChange",
            stp_ver                     "dot1dStpProtocolSpecification",
            uptime                      "sysUpTime",
            write_mem                   "writeMem"
        },
        IgnoreNetSNMPConf   1,
        init                \ 1,
        mibdirs             var{args}{MibDirs},
        mibs                {
            BRIDGE-MIB                        "dot1dBaseBridgeAddress",
            CISCO-CDP-MIB                     "cdpGlobalRun",
            CISCO-CONFIG-COPY-MIB             "ccCopyTable",
            CISCO-ENTITY-VENDORTYPE-OID-MIB   "cevChassis",
            CISCO-FLASH-MIB                   "ciscoFlashCopyTable",
            CISCO-IMAGE-MIB                   "ciscoImageString",
            CISCO-MEMORY-POOL-MIB             "ciscoMemoryPoolUsed",
            CISCO-PROCESS-MIB                 "cpmCPUTotal5sec",
            CISCO-PRODUCTS-MIB                "ciscoIGS",
            CISCOSB-DEVICEPARAMS-MIB          "rndBasePhysicalAddress",
            CISCOSB-POE-MIB                   "rlPethPsePortOutputPower",
            CISCO-STACK-MIB                   "wsc1900sysID",
            DOCS-IF-MIB                       "docsIfMib",
            DOCS-IF3-MIB                      "docsIf3Mib",
            ENTITY-MIB                        "entPhysicalSoftwareRev",
            EtherLike-MIB                     "etherMIB",
            IF-MIB                            "ifIndex",
            IP-MIB                            "ipAdEntAddr",
            LLDP-EXT-DOT1-MIB                 "lldpXdot1MIB",
            LLDP-EXT-DOT3-MIB                 "lldpXdot3MIB",
            LLDP-EXT-MED-MIB                  "lldpXMedMIB",
            LLDP-MIB                          "lldpLocSysCapEnabled",
            OLD-CISCO-SYS-MIB                 "writeMem",
            OLD-CISCO-SYSTEM-MIB              "writeMem",
            POWER-ETHERNET-MIB                "pethPsePortDetectionStatus",
            Q-BRIDGE-MIB                      "dot1qPvid",
            RSTP-MIB                          "dot1dStpPortOperEdgePort",
            SNMPv2-MIB                        "sysDescr"
        },
        munge               {
            b_mac                    sub { ... },
            bs_mac                   var{munge}{b_mac},
            cdp_capabilities         sub { ... },
            cdp_domain               sub { ... },
            cdp_ip                   sub { ... },
            cdp_platform             var{munge}{cdp_domain},
            cdp_power                sub { ... },
            cdp_ver                  var{munge}{cdp_domain},
            el_duplex                sub { ... },
            e_type                   sub { ... },
            fw_mac                   var{munge}{b_mac},
            i_mac                    var{munge}{b_mac},
            i_octet_in64             sub { ... },
            i_octet_out64            var{munge}{i_octet_in64},
            i_pkts_bcast_in64        var{munge}{i_octet_in64},
            i_pkts_bcast_out64       var{munge}{i_octet_in64},
            i_pkts_multi_out64       var{munge}{i_octet_in64},
            i_pkts_mutli_in64        var{munge}{i_octet_in64},
            i_pkts_ucast_in64        var{munge}{i_octet_in64},
            i_pkts_ucast_out64       var{munge}{i_octet_in64},
            i_speed                  sub { ... },
            i_speed_high             sub { ... },
            i_up                     sub { ... },
            ip                       var{munge}{cdp_ip},
            layers                   sub { ... },
            lldp_lport_desc          var{munge}{cdp_domain},
            lldp_lport_id            var{munge}{cdp_domain},
            lldp_rem_asset           var{munge}{cdp_domain},
            lldp_rem_cap_spt         var{munge}{cdp_capabilities},
            lldp_rem_fw_rev          var{munge}{cdp_domain},
            lldp_rem_hw_rev          var{munge}{cdp_domain},
            lldp_rem_media_cap       var{munge}{cdp_capabilities},
            lldp_rem_media_cap_spt   var{munge}{cdp_capabilities},
            lldp_rem_model           var{munge}{cdp_domain},
            lldp_rem_port_desc       var{munge}{cdp_domain},
            lldp_rem_serial          var{munge}{cdp_domain},
            lldp_rem_sw_rev          var{munge}{cdp_domain},
            lldp_rem_sys_cap         var{munge}{cdp_capabilities},
            lldp_rem_sysdesc         var{munge}{cdp_domain},
            lldp_rem_sysname         var{munge}{cdp_domain},
            lldp_rem_vendor          var{munge}{cdp_domain},
            lldp_sys_cap             var{munge}{cdp_capabilities},
            lldp_sysdesc             var{munge}{cdp_domain},
            lldp_sysname             var{munge}{cdp_domain},
            mac                      var{munge}{b_mac},
            qb_cv_egress             sub { ... },
            qb_cv_untagged           var{munge}{qb_cv_egress},
            qb_v_egress              var{munge}{qb_cv_egress},
            qb_v_fbdn_egress         var{munge}{qb_cv_egress},
            qb_v_untagged            var{munge}{qb_cv_egress},
            stp_i_mac                var{munge}{b_mac},
            stp_i_root               sub { ... },
            stp_p_bridge             var{munge}{stp_i_root},
            stp_p_port               sub { ... },
            stp_p_root               var{munge}{stp_i_root},
            stp_root                 var{munge}{stp_i_root}
        },
        nosuch              1,
        sess                var{args}{Session},
        snmp_comm           "SNMpCsdP",
        snmp_user           "initial",
        snmp_ver            2,
        store               {}
    }
}

**Comment by inphobia** [comment]
> [62272] 2021-02-15 12:53:17 debug macsuck: timed out!
> [62272] 2021-02-15 12:53:17 debug job timed out after 600 sec

that's strange, since it did return sysdescr so snmp must be working. the only thing i can think of is perhaps that the snmp view doesn't allow this. on ciscosb devices we use:
`snmp-server community XXX ro view DefaultSuper`



> On the switch, it's connected and configured on port 25 but appears as port 24 on Netdisco.

haven't seen this yet on our 300 & 350 series, perhaps it's specific to the 220 series. i should be able to troubleshoot this with the snmp data, see https://github.com/netdisco/snmp-info/wiki/Simulating-Agents#snmpsim-snmprec-version

**Comment by ollyg** [comment]
closing. please re-open if this is still a problem
