### ISSUE TITLE
Numeric sort error for netdisco-backend logfile rotation

### ISSUE THREAD

**Issue by jrbinks** [netdisco/netdisco#769]
Ref fix in #740 :

Now:
Argument "/home/netdisco/logs/netdisco-backend.log.3" isn't numeric in sort at /home/netdisco/bin/netdisco-backend line 171.

_Originally posted by @jrbinks in https://github.com/netdisco/netdisco/issues/740#issuecomment-784140470_

**Comment by ollyg** [comment]
oops, thanks, fixed in
[master 9816bb51] #769 Numeric sort error for logfile rotation
