### ISSUE TITLE
Issue with upgrading 

### ISSUE THREAD

**Issue by MickG72** [netdisco/netdisco#786]
Hi,

I have net disco server that has been turned off for 3-4 months 
Powered it on , and it looks to be polling fine. 
Trying to upgrade , and it fails with the below errors.
Any help would be great
Thanks

============================
netdisco@netdisco:~$ ~/bin/localenv cpanm --notest App::Netdisco
--> Working on App::Netdisco
Fetching http://www.cpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.047005.tar.gz ... OK

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
! Failed to unpack App-Netdisco-2.047005.tar.gz: no directory
! Failed to fetch distribution App-Netdisco-2.047005
netdisco@netdisco:~$ 
===============================

Built using Open Source
Software	Version
App::Netdisco	2.46.5
SNMP::Info	3.70
DB Schema	63
PostgreSQL	10.00.16
Perl	5.26.1

**Comment by rc9000** [comment]
Hi! Sounds like not enough disk space to unpack the .tar.gz, or some corruption while downloading it.

Can you check `df -h`, and if there's enough space maybe try 

    curl -o App-Netdisco-2.047005.tar.gz http://www.cpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.047005.tar.gz
    tar xvf App-Netdisco-2.047005.tar.gz

to see if the file arrives ok at your end without using cpanm.

**Comment by MickG72** [comment]
Working now for your help
