### ISSUE TITLE
netdisco-do renumber on pseudo removes name

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#788]
## Expected Behavior

using `netdisco-do renumber` on pseudodevice should not change device name.

## Current Behavior

pseudodevice name gets wiped if it has no reverse dns.

## Possible Solution

use device.name instead device.dns for pseudo devices.

working on some pseudo updates in https://github.com/inphobia/netdisco/tree/nn_pseudo

## Steps to Reproduce (for bugs)

1. create pseudo device
2. ![image](https://user-images.githubusercontent.com/39005454/119938405-a46f0d00-bf8c-11eb-8e99-6e8d16372761.png)
3. renumber with netdisco-do renumber, make sure new ip doesn't have a reverse dns.
```
netdisco-do renumber -d 169.254.61.111 -e 169.254.61.251
[21647] 2021-05-28 06:08:02  info App::Netdisco version 2.047005 loaded.
[21647] 2021-05-28 06:08:02  info renumber: [169.254.61.111] started at Fri May 28 08:08:02 2021
[21647] 2021-05-28 06:08:02  info renumber: finished at Fri May 28 08:08:02 2021
[21647] 2021-05-28 06:08:02  info renumber: status done: Renumbered device 169.254.61.251 to 169.254.61.251/32 ().
```
4. check /admin/pseudodevice
5. notice name is gone
![image](https://user-images.githubusercontent.com/39005454/119938453-b94ba080-bf8c-11eb-8a61-21e503fcfa02.png)

## Your Environment

* Netdisco version used: git master
* SNMP::Info version used: n/a

## Device information

pseudo device.

**Comment by ollyg** [comment]
thanks, fixed in 0d1dc39d
