### ISSUE TITLE
SQL problem with a new custom report.

### ISSUE THREAD

**Issue by ubzmrh** [netdisco/netdisco#792]
I'm trying to add a new custom report in Netdisco (version 2.047005), PostreSQL (12.5)
Here is the content of our deployment.yml file.
```
reports:
  - tag : ap_inventory
    label : "Inventaire Bornes par Site"
    category : Wireless
    columns:
      - {d.name: 'Name'}
      - {d.ip: 'IP'}
      - {b.port: 'Port'}
      - {b.remote_id: 'ID Borne'}
      - {b.remote_ip: 'IP Borne'}
      - {b.mac: 'MAC Borne'}
    query: |
      select d.name , d.ip, b.port, b.remote_id, b.remote_ip, b.mac from device d, device_port b where d.ip = b.ip and b.remote_id like '%-AP%' and d.name like ? order by d.ip, b.port
    bind_params: ['d.name']
```

When I try this query with `netdsico-do psql`, it's alright. 
```
<bilpimc001.dom101.prdres:1> (netdisco)/appli/netdisco $ netdisco-do psql -e "select d.name , d.ip, b.port, b.remote_id, b.remote_ip, b.mac from device d, device_port b where d.ip = b.ip and b.remote_id like '%-AP%' and d.name like 'BPOC-ALB1%' order by d.ip, b.port"
[3143] 2021-06-14 07:40:20  info App::Netdisco version 2.047005 loaded.
[3143] 2021-06-14 07:40:20  info psql:  started at Mon Jun 14 09:40:20 2021
       name       |     ip      | port |      remote_id      |  remote_ip  |        mac
------------------+-------------+------+---------------------+-------------+-------------------
 BPOC-ALB1-SWA100 | 5.249.0.100 | 1    | BPOC_Albi-A-7E-AP01 | 5.249.8.107 | 70:10:6f:da:ab:9f
 BPOC-ALB1-SWA100 | 5.249.0.100 | 24   | BPOC_Albi-A-1E-AP01 | 5.249.8.2   | 70:10:6f:da:ab:88
(2 rows)

[3143] 2021-06-14 07:40:20  info psql: finished at Mon Jun 14 09:40:20 2021
[3143] 2021-06-14 07:40:20  info psql: status done: psql session closed.
```

But when I try it in the web interface, I get that url `http://bilpimc001.dom101.prdres:5000/report/ap_inventory?firstsearch=on` instead of `http://bilpimc001.dom101.prdres:5000/report/ap_inventory?d.name=`
and this message `Search failed! Please contact your site administrator.`
In netdisco-web.log, I get 
```
[19906] 2021-06-11 14:56:39 error request to GET /ajax/content/report/ap_inventory crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  missing FROM-clause entry for table "d"
LINE 1: SELECT d.name, d.ip, b.port, b.remote_id, b.remote_ip, b.mac...
               ^ [for Statement "SELECT d.name, d.ip, b.port, b.remote_id, b.remote_ip, b.mac FROM (select d.name , d.ip, b.port, b.remote_id, b.remote_ip, b.mac from device d, device_port b where d.ip = b.ip and b.remote_id like '%-AP%' and d.name like ? order by d.ip, b.port
) me" with ParamValues: 1=''] at /appli/netdisco/perl5/lib/perl5/App/Netdisco/Web/GenericReport.pm line 62
```
I know the error isn't in the name of param, as I try without the param, with a fixed value.
I don't understand which is the error, as I don't speak Perl and as the query works !

**Comment by ubzmrh** [comment]
OK, 
I created a VIEW with my query (without the filter on name) and created the report with something like `select * from myview where name like ?` which works perfectly.

Strange !
Is there a SQL analyzer somewhere in Netdisco  which cannot handle queries other than very simple ?
Maybe the wiki should contain a warning about some a little complicated SQL queries ?

**Comment by rc9000** [comment]
From the error message, it looks like the query in the yaml gets wrapped again in another outer select, maybe for pagination?


    "SELECT d.name, d.ip, b.port, b.remote_id, b.remote_ip, b.mac FROM 
       (select d.name , d.ip, b.port, b.remote_id, b.remote_ip, b.mac 
            from device d, device_port b 
            where d.ip = b.ip and b.remote_id like '%-AP%' and d.name like ? 
            order by d.ip, b.port
       ) me" with ParamValues: 1=''] at /appli/netdisco/perl5/lib/perl5/App/Netdisco/Web/GenericReport.pm line 62

So the columns are no longer d.name and b.port but just name and port or maybe me.name and me.port. Just drop the prefixes in the columns: description and it should work. Like in the example here: https://github.com/netdisco/netdisco/wiki/Configuration#reports

**Comment by ubzmrh** [comment]
I tried the column names without prefixes first and that didn't work either.
But now, with this syntax, it works!
```
  - tag : ap_inventory
    label : "Inventaire Bornes par Site"
    category : Wireless
    columns:
      - {name: 'Name'}
      - {ip: 'IP'}
      - {port: 'Port'}
      - {remote_id: 'ID Borne'}
      - {remote_ip: 'IP Borne'}
      - {mac: 'MAC Borne'}
    query: |
      select d.name , d.ip, b.port, b.remote_id, b.remote_ip, b.mac from device d, device_port b where d.ip = b.ip and b.remote_id like '%-AP%' and d.name like ? order by d.ip, b.port
    bind_params: ['name']
```
Thanks for the help !
