### ISSUE TITLE
Feature Request: Separate Web Interface and Backend User for Granular Postgres Control

### ISSUE THREAD

**Issue by Trent-Curtis** [netdisco/netdisco#795]
## Current Behavior
Currently today, Netdisco only uses a single account for backend and web interface via the deployment.yml configuration.  I would like to separate these accounts to allow for different timeouts values on the postgres side. This would help reduce database locks. 

## Context
Backend poller user timeout should be reasonable.  I would think 1-5 minutes timeout for the backend and 1-2 minutes for the web interface.

**Comment by ollyg** [comment]
Hi @Trent-Curtis 
This is a great idea! Not a trivial implementation though, which I am sad about as I realised a while ago that it would be better to have more separation between frontend and backend (maybe even two installable packages with separate dependencies).

Anyway, there is a way to achieve this I think, using one of two options:
- run the frontend and backend in different server instances so they have different configuration files
- pass different configuration files to the frontend and backend daemons, using separate directories (DANCER_ENVDIR is "environments") or files (DANCER_ENVIRONMENT is "deployment")
- use environment variables to pass the database connection details (https://github.com/netdisco/netdisco/wiki/Environment-Variables#general-configuration)

The second of these I have not ever tried, to be honest. I think the last of these would work well to give separate accounts to frontend and backend database connections.

regards
Oliver.
