### ISSUE TITLE
Libernms integration

### ISSUE THREAD

**Issue by jacobghattas** [netdisco/netdisco#796]
Greetings,
I used both observium and librenms on my network In addition to netdisco.
For observiums, I installed the plugins and it works perfectly. 
Is there anyway to have it work also for librenms?

10xs.
Jacob

**Comment by inphobia** [comment]
well, we currently don't have a librenms plugin.

perhaps if you could elaborate on what exactly you expect we can give a more definitive answser. if it's just a link to the device in librenms that shouldn't be that hard ( https://github.com/netdisco/nd2-web-plugin-rancid does something like that). however if you want to show data from librenms in netdisco that could be more challenging.

**Comment by jacobghattas** [comment]
Thank u nick.
will look into it, basically what I wanted to do is point to the port traffic graphs in librenms as I have it with observium.
no data needed from librenms to netdisco.

will look into the rancid and the observium plugins.

10xs
Jacob
