### ISSUE TITLE
Device Name/DNS Mismatches report does not disregard domain name

### ISSUE THREAD

**Issue by jrbinks** [netdisco/netdisco#797]
Reports>Device>Device Name/DNS Mismatches report ostensibly seems like a good idea.

Unfortunately, in my scenario it's a bit useless, since it considers device name "xyz" to be different to DNS name "xyz.net.strath.ac.uk".  Technically that is correct of course, but since my domain suffix is set to '.strath.ac.uk' is doesn't match up.

I've also tried setting:

```
domain_suffix:
  - '.strath.ac.uk'
  - '.net.strath.ac.uk'
```

but not clear if a set is handled correctly in the code.

I would like it, possibly optionally, to ignore domain parts here.  However I realise people operating larger infrastruture particularly internationally may well have device names that incorporate some degree of hierarchy, as opposed to the flat naming I have (both in device name and in DNS).

Perhaps there could be an option to modify the report to specify the number of domain parts from the DNS name used for comparison purposes: either, zero (all domain parts ignored), or 1, 2, 3, etc parts to be used.

Alternatively, being able to list multiple in domain_suffix and have all used in testing the match also works for me.

App::Netdisco 2.47.4

**Comment by ollyg** [comment]
Hi, as far as I can tell, the code should handle this properly.

If you do:
`netdisco-do dumpconfig -e domain_suffix`

You will see a regexp of your list. And that is used in the SQL for the DNS mismatch report:

````
SELECT *
FROM device
WHERE dns IS NULL
  OR name IS NULL
  OR regexp_replace(lower(dns), ?, '')
    != regexp_replace(lower(name), ?, '')
ENDSQL
````

So, I really do not know why it's not working, sorry.
