### ISSUE TITLE
new releases not correctly tagged?

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#799]
it seems 2.047006 & 2.047007 aren't correctly tagged or somehow didn't go through the github release process completely.

README.md gives the correct cpan version but wrong github release date:
![image](https://user-images.githubusercontent.com/39005454/126049375-dbc16ccb-20cb-4f7e-9524-c4b206afa27a.png)

i guess since 47006 & 47007 where tagged but not "released"?

![image](https://user-images.githubusercontent.com/39005454/126049390-69f962b2-144c-45ea-bcf0-64709994b1cd.png)

**Comment by ollyg** [comment]
yes this is because of the infamous broken CircleCI stuff, as the releases happen here:
https://github.com/netdisco/netdisco/blob/master/.circleci/config.yml

and I guess this also breaks the docker releases consequently.

so it will be the next thing I look at!!

**Comment by ollyg** [comment]
OK this should be fixed with the exciting new GitHub Actions config!
https://github.com/netdisco/netdisco/blob/master/.github/workflows/release.yml
