### ISSUE TITLE
Feature Req: SNMP Chassis-ID

### ISSUE THREAD

**Issue by pidotgit** [netdisco/netdisco#800]
## Expected Behavior
When the SNMP chassis-id Entry is not empty or equals Serial-Number, this Feature returns the snmp-server chassis-id field on devices (Environment is Cisco) and makes this entry searchable

## Current Behavior
chassis-id field isn't searched for/returned

## Possible Solution
Use the chassis-id field to return the configured value and display for devices discovered in NetDisco

## Context
We use the chassis-id Entry to store out custom/company inventory ID and while some device-names change in time, the sticker with the inventory ID does not. This should help to identify devices in case when the only available information is the inventory ID.

Per default, the chassis-id is empty or equals to the Serial-Number **when not set**.
Information about the chassis-id OID can be found here:
https://oidref.com/1.3.6.1.4.1.9.3.6.3

This Feature was already requestested in https://github.com/netdisco/netdisco/issues/562 so this is partialy paste&copy with additional information

## Your Environment
App::Netdisco 	2.46.6
SNMP::Info 	3.70
DB Schema 	64
PostgreSQL 	12.00.7
Perl 	5.18.2

**Comment by ollyg** [comment]
I've about half implemented this, just working on how best to display it in search results without cluttering the interface

**Comment by pidotgit** [comment]
glad to hear it
thanks for the feedback & keep up the good work

**Comment by ollyg** [comment]
implemented in 2498d976 and will be in next release

**Comment by inphobia** [comment]
while i have to say i like the idea of having some object identifier, asset id, inventory tag. ...
i'm not sure if this is the right way to implement it. the oid provided is from `OLD-CISCO-CHASSIS-MIB` which states clearly:
`Starting with IOS 12.0, all objects defined in this mib have been deprecated.  They have been replaces with objects defined in the ENTITY-MIB.my document.`
it's also only available on ios it seems, i haven't found anything similar in other mibs. even nx-os doesn't support this.

after checking entity mib it `entPhysicalAssetID` seems to be the closest thing that could cover this, but also here there are next to no vendors i found which allow setting this, even though it's a read-write type.

we also use the function serial1() to get the chassis id:
https://github.com/netdisco/netdisco/blob/b0ea7bc0bd9865d592afd1f19d150f6a18138f54/lib/App/Netdisco/Worker/Plugin/Discover/Properties.pm#L50

while this is defined in snmp::info::layer2/3.pm as pointing to `OLD-CISCO-CHASSIS-MIB::chassisId.0`
https://github.com/netdisco/snmp-info/blob/afc8eefaf1ea91c2777541263bd239066e2c7826/lib/SNMP/Info/Layer3.pm#L88
it is still overwritten in several more specific modules and is in no way a standard.

i think the actual request could be formulated as having a freeform info field for a device, which i do like. if i'm dreaming out load perhaps this could be done by mapping acl's against functions in deployment.

so you could have a
```
host_groups:
  grp-chassisid:
   - 'class:SNMP::Info::Layer3::Cisco'
  grp-apc:
   - 'vendor:apc'

map_freeform:
  serial1:
   - 'group:grp-chassisid'
  upsBasicIdentName:
   - 'group:grp-apc'
```
(no idea if ` - 'class:SNMP::Info::Layer3::Cisco'` is valid syntax with all those colons, but you get the idea)

bonus points if the that freeform field can be written/set like location etc.... so it can be manually filled in for devices that can't provide useful info.

**Comment by ollyg** [comment]
I take your point that this is a very Cisco specific implementation, and
using a deprecated OID, but the principle was to get something implemented
(and arguably what a user asks for (two of them, actually) is most useful
compared to what no-one is asking for).

Anyway, thanks for finding the alternative in ENTITY-MIB, we could easily
gather from that as well. Also what's implemented is also not writable in
Netdisco, so not at all like Location/Contact/etc. I guess the ideal, if
someone finds time, would be to implement the writing features for the
not-deprecated targets.
