### ISSUE TITLE
After login, default page is Inventory

### ISSUE THREAD

**Issue by USQ-CJD** [netdisco/netdisco#801]
Hi All, I have configured Netdisco with LDAP authentication and after the client is authenticated, the next thing they see is the Inventory page.  As good as that is, I really would like them to see the Netdisco Search page as their on boarding page.
Is there away to change the behavior over to this?

Regards
Chris

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used: 

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by pidotgit** [comment]
Append the following String to your configuration (default-file: deployment.yml)
web_home: '/'

**Comment by USQ-CJD** [comment]
Thanks.

Regards

Chris Doolan
Network Engineer | Networking | YA102
T: +61 7 4631 1346
E: ***@***.******@***.***>
