### ISSUE TITLE
avoid DEPRECATED single warning from DBIC

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#81]
DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  SQL that returns multiple rows is DEPRECATED for ->find and ->single at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 235

Reported by: ollyg

Original Ticket: [netdisco/netdisco2/42](https://sourceforge.net/p/netdisco/netdisco2/42)

**Comment by taylor5042** [comment]
I'm seeing this over and over in my backend.log 
DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  SQL that returns multiple rows is DEPRECATED for ->find and ->single at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm line 192

Version: 2.44.2

**Comment by ollyg** [comment]
thanks @taylor5042 for the bug report. I've applied a patch which will be in the next release of Netdisco.

[master f7f2d208] #81 avoid DEPRECATED single warning from DBIC
