### ISSUE TITLE
Cisco WLC5508: duplicate key value violates unique constraint "device_port_ssid_pkey"

### ISSUE THREAD

**Issue by jkleinhans** [netdisco/netdisco#816]
## Current Behavior
Hello, Discovery of Cisco WLC 5508 or WLC 5520 stops because of the following error.

[113486] 2021-09-20 11:18:24 debug -> execute_for_fetch() aborted with 'ERROR:  duplicate key value violates unique constraint "device_port_ssid_pkey"
DETAIL:  Key (ip, bssid, port)=(172.30.16.6, 78:bc:1a:c0:e4:80, 78:bc:1a:c0:e4:80.1) already exists.' at populate slice:
{
  broadcast => 1,
  bssid => "78:bc:1a:c0:e4:80",
  ip => "172.30.16.6",
  port => "78:bc:1a:c0:e4:80.1",
  ssid => "xxxx",
} at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1118.
        DBIx::Class::Schema::throw_exception(App::Netdisco::DB=HASH(0x7ffff4eedd40), "execute_for_fetch() aborted with 'ERROR:  duplicate key value"...) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage.pm line 113
        DBIx::Class::Storage::throw_exception(DBIx::Class::Storage::DBI::Pg=HASH(0x7ffff4e55e28), "execute_for_fetch() aborted with 'ERROR:  duplicate key value"...) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 2536
        DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(DBIx::Class::Storage::DBI::Pg=HASH(0x7ffff4e55e28), DBIx::Class::ResultSource::Table=HASH(0x7ffff3f2a490), DBI::st=HASH(0x7fffeaf4d880), ARRAY(0x7fffd26a61c8), ARRAY(0x7ffff25a6b20), ARRAY(0x7fffd37babc8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 2422
        DBIx::Class::Storage::DBI::_insert_bulk(DBIx::Class::Storage::DBI::Pg=HASH(0x7ffff4e55e28), DBIx::Class::ResultSource::Table=HASH(0x7ffff3f2a490), ARRAY(0x7ffff25a6b20), ARRAY(0x7fffd37babc8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/ResultSet.pm line 2437
        DBIx::Class::ResultSet::populate(App::Netdisco::DB::ResultSet::DevicePortSsid=HASH(0x7ffff545d958), ARRAY(0x7ffff2600aa0)) called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Wireless.pm line 64
        App::Netdisco::Worker::Plugin::Discover::Wireless::__ANON__() called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/BlockRunner.pm line 130
        DBIx::Class::Storage::BlockRunner::try {...} () called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 102
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 93
        Try::Tiny::try(CODE(0x7fffebe287c0), Try::Tiny::Catch=REF(0x7ffff1f4a768)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/BlockRunner.pm line 134
        DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/netdisco/perl5/lib/perl5/Context/Preserve.pm line 23
        Context::Preserve::preserve_context(CODE(0x7fffec75e920), "replace", CODE(0x7fffeb05fff8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/BlockRunner.pm line 213
        DBIx::Class::Storage::BlockRunner::_run(DBIx::Class::Storage::BlockRunner=HASH(0x7fffeb0ccd50), CODE(0x7fffeb038c08)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/BlockRunner.pm line 105
        DBIx::Class::Storage::BlockRunner::run(DBIx::Class::Storage::BlockRunner=HASH(0x7fffeb0ccd50), CODE(0x7fffeb038c08)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage.pm line 187
        DBIx::Class::Storage::txn_do(DBIx::Class::Storage::DBI::Pg=HASH(0x7ffff4e55e28), CODE(0x7fffeb038c08)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 861
        DBIx::Class::Storage::DBI::txn_do(DBIx::Class::Storage::DBI::Pg=HASH(0x7ffff4e55e28), CODE(0x7fffeb038c08)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 654
        DBIx::Class::Schema::txn_do(App::Netdisco::DB=HASH(0x7ffff4eedd40), CODE(0x7fffeb038c08)) called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover/Wireless.pm line 67
        App::Netdisco::Worker::Plugin::Discover::Wireless::__ANON__(App::Netdisco::Backend::Job=HASH(0x7ffff305af38), HASH(0x7ffff2600b30)) called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin.pm line 88
        App::Netdisco::Worker::Plugin::__ANON__(App::Netdisco::Backend::Job=HASH(0x7ffff305af38)) called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Runner.pm line 102
        App::Netdisco::Worker::Runner::try {...} () called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 102
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 93
        Try::Tiny::try(CODE(0x7ffff545d718), Try::Tiny::Catch=REF(0x7ffff259f5d8)) called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Runner.pm line 106
        App::Netdisco::Worker::Runner::run_workers(MyWorker=HASH(0x7ffff4ee99b8), "workers_main") called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Runner.pm line 72
        App::Netdisco::Worker::Runner::__ANON__(MyWorker=HASH(0x7ffff4ee99b8), App::Netdisco::Backend::Job=HASH(0x7ffff305af38)) called at /home/netdisco/perl5/lib/perl5/Sys/SigAction.pm line 164
        eval {...} called at /home/netdisco/perl5/lib/perl5/Sys/SigAction.pm line 162
        eval {...} called at /home/netdisco/perl5/lib/perl5/Sys/SigAction.pm line 160
        Sys::SigAction::timeout_call(600, CODE(0x7ffff4ee32b0), MyWorker=HASH(0x7ffff4ee99b8), App::Netdisco::Backend::Job=HASH(0x7ffff305af38)) called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Runner.pm line 80
        App::Netdisco::Worker::Runner::run(MyWorker=HASH(0x7ffff4ee99b8), App::Netdisco::Backend::Job=HASH(0x7ffff305af38)) called at /home/netdisco/bin/netdisco-do line 162
        main::try {...} () called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 102
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 93
        Try::Tiny::try(CODE(0x7ffff30c5cd8), Try::Tiny::Catch=REF(0x7ffff305dea8)) called at /home/netdisco/bin/netdisco-do line 167

## Steps to Reproduce (for bugs)
netdisco-do discover::wireless -d 172.30.16.6 -DQ

## Context
We want to see the WIFI Networks and Clients in NetDisco

## Your Environment
* Netdisco version used: 2.49.5
* SNMP::Info version used: 3.78
* DB Schema: 66

## Device information
Cisco WLC 5508 or WLC 5520
Firmware: 8.5.161.0

~/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover $ netdisco-do show -d 172.30.16.6 -e specify -DI
[114357] 2021-09-20 11:23:48  info App::Netdisco version 2.049005 loaded.
[114357] 2021-09-20 11:23:49  info show: [172.30.16.6]/specify started at Mon Sep 20 11:23:49 2021
[114357] 2021-09-20 11:23:49 debug show: running with timeout 600s
[114357] 2021-09-20 11:23:49 debug => running workers for phase: check
[114357] 2021-09-20 11:23:49 debug -> run worker check/_base_/0
[114357] 2021-09-20 11:23:49 debug Show is able to run
[114357] 2021-09-20 11:23:49 debug => running workers for phase: main
[114357] 2021-09-20 11:23:49 debug -> run worker main/_base_/100
[114357] 2021-09-20 11:23:49 debug snmp reader cache warm: [172.30.16.6]
[114357] 2021-09-20 11:23:49 debug [172.30.16.6:161] try_connect with ver: 2, class: SNMP::Info::Layer2::Airespace, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.78
SNMP::Info::device_type() layers:00000111 id:9 sysDescr:"Cisco Controller"
SNMP::Info 3.78
SNMP::Info::device_type() layers:00000111 id:9 sysDescr:"Cisco Controller"
SNMP::Info::specify() - Changed Class to SNMP::Info::Layer2::Airespace.
SNMP::Info::_validate_autoload_method(_data_printer) Unable to resolve method.
SNMP::Info::_validate_autoload_method(as_string) Unable to resolve method.
SNMP::Info::_validate_autoload_method(stringify) Unable to resolve method.
SNMP::Info::_validate_autoload_method(to_string) Unable to resolve method.
SNMP::Info::Layer2::Airespace  {
    parents: SNMP::Info::Airespace, SNMP::Info::CDP, SNMP::Info::Bridge, Exporter
    linear @ISA: SNMP::Info::Layer2::Airespace, SNMP::Info::Airespace, SNMP::Info, Exporter, SNMP::Info::CDP, SNMP::Info::Bridge
    public methods (169):
        cd11_mac, cd11_txrate, i_mac, model, munge_cd11_proto, munge_cd11_rateset, munge_cd11n_ch_bw, os, vendor
        Carp:
            carp, confess, croak
        Data::Dumper:
            Dumper
        Exporter:
            as_heavy, export, export_fail, export_ok_tags, export_tags, export_to_level, import, require_version
        SNMP:
            RECEIVED_MESSAGE, SNMP_API_SINGLE, SNMP_API_TRADITIONAL, SNMP_DEFAULT_ADDRESS, SNMP_DEFAULT_COMMUNITY_LEN, SNMP_DEFAULT_ENTERPRISE_LENGTH, SNMP_DEFAULT_ERRINDEX, SNMP_DEFAULT_ERRSTAT, SNMP_DEFAULT_PEERNAME, SNMP_DEFAULT_REMPORT, SNMP_DEFAULT_REQID, SNMP_DEFAULT_RETRIES, SNMP_DEFAULT_TIME, SNMP_DEFAULT_TIMEOUT, SNMP_DEFAULT_VERSION, snmp_get, snmp_getnext, snmp_set, snmp_trap, SNMPERR_BAD_ADDRESS, SNMPERR_BAD_LOCPORT, SNMPERR_BAD_SESSION, SNMPERR_GENERR, SNMPERR_TOO_LONG, TIMED_OUT
        SNMP::Info:
            all, args, AUTOLOAD, bulkwalk, bulkwalk_no, c_cap, c_id, c_if, c_ip, c_platform, c_port, cache, can, cisco_comm_indexing, class, clear_cache, debug, DESTROY, device_type, error, error_throw, funcs, globals, has_layer, has_topo, i_speed, i_speed_raw, if_ignore, init, ip_table, load_all, loopdetect, mibs, modify_port_list, munge, munge_bits, munge_counter64, munge_dec2bin, munge_e_type, munge_highspeed, munge_i_up, munge_ip, munge_mac, munge_null, munge_octet2hex, munge_port_list, munge_prio_mac, munge_prio_port, munge_speed, new, nosuch, offline, resolve_desthost, session, set_multi, snmp_comm, snmp_connect_ip, snmp_ver, specify, store, update
        SNMP::Info::Airespace:
            at_netaddr, at_paddr, bp_index, dot11_cur_tx_pwr_mw, e_class, e_descr, e_fwver, e_index, e_model, e_name, e_parent, e_pos, e_serial, e_swver, e_type, e_vendor, fw_mac, fw_port, i_80211channel, i_description, i_duplex, i_duplex_admin, i_index, i_name, i_ssidbcast, i_ssidlist, i_ssidmac, i_type, i_up, i_up_admin, i_vlan, interfaces, ip_index, ip_netmask, layers, munge_64bits, serial
        SNMP::Info::Bridge:
            fw_status, i_stp_bridge, i_stp_id, i_stp_port, i_stp_state, i_untagged, i_vlan_membership, i_vlan_membership_untagged, qb_fdb_index, qb_fw_mac, qb_fw_vlan, qb_i_vlan_t, set_add_i_vlan_tagged, set_i_pvid, set_i_untagged, set_i_vlan, set_remove_i_vlan_tagged, v_index
        SNMP::Info::CDP:
            cdp_cap, cdp_id, cdp_if, cdp_ip, cdp_port, hasCDP, munge_power
    private methods (0)
    internals: {
        args                {
            AutoSpecify         0,
            BulkRepeaters       20,
            BulkWalk            1,
            Community           "xxx",
            Debug               1,
            DebugSNMP           0,
            DestHost            "172.30.16.6" (dualvar: 172.3),
            IgnoreNetSNMPConf   1,
            MibDirs             [
                [0]  "/home/netdisco/netdisco-mibs/3com",
                [1]  "/home/netdisco/netdisco-mibs/adtran",
                [2]  "/home/netdisco/netdisco-mibs/aerohive",
                [3]  "/home/netdisco/netdisco-mibs/alcatel",
                [4]  "/home/netdisco/netdisco-mibs/allied",
                [5]  "/home/netdisco/netdisco-mibs/apc",
                [6]  "/home/netdisco/netdisco-mibs/arista",
                [7]  "/home/netdisco/netdisco-mibs/aruba",
                [8]  "/home/netdisco/netdisco-mibs/asante",
                [9]  "/home/netdisco/netdisco-mibs/avaya",
                [10] "/home/netdisco/netdisco-mibs/bluecoat",
                [11] "/home/netdisco/netdisco-mibs/bluesocket",
                [12] "/home/netdisco/netdisco-mibs/brother",
                [13] "/home/netdisco/netdisco-mibs/cabletron",
                [14] "/home/netdisco/netdisco-mibs/ceragon",
                [15] "/home/netdisco/netdisco-mibs/cern",
                [16] "/home/netdisco/netdisco-mibs/checkpoint",
                [17] "/home/netdisco/netdisco-mibs/ciena",
                [18] "/home/netdisco/netdisco-mibs/cisco",
                [19] "/home/netdisco/netdisco-mibs/ciscosb",
                [20] "/home/netdisco/netdisco-mibs/citrix",
                [21] "/home/netdisco/netdisco-mibs/clavister",
                [22] "/home/netdisco/netdisco-mibs/cloudgenix",
                [23] "/home/netdisco/netdisco-mibs/colubris",
                [24] "/home/netdisco/netdisco-mibs/cumulus",
                [25] "/home/netdisco/netdisco-mibs/cyclades",
                [26] "/home/netdisco/netdisco-mibs/d-link",
                [27] "/home/netdisco/netdisco-mibs/dell",
                [28] "/home/netdisco/netdisco-mibs/eaton",
                [29] "/home/netdisco/netdisco-mibs/efficientip",
                [30] "/home/netdisco/netdisco-mibs/enterasys",
                [31] "/home/netdisco/netdisco-mibs/etherwan",
                [32] "/home/netdisco/netdisco-mibs/exinda",
                [33] "/home/netdisco/netdisco-mibs/EXTRAS",
                [34] "/home/netdisco/netdisco-mibs/extreme",
                [35] "/home/netdisco/netdisco-mibs/extricom",
                [36] "/home/netdisco/netdisco-mibs/f5",
                [37] "/home/netdisco/netdisco-mibs/force10",
                [38] "/home/netdisco/netdisco-mibs/fortinet",
                [39] "/home/netdisco/netdisco-mibs/foundry",
                [40] "/home/netdisco/netdisco-mibs/gigamon",
                [41] "/home/netdisco/netdisco-mibs/h3c",
                [42] "/home/netdisco/netdisco-mibs/hirschmann",
                [43] "/home/netdisco/netdisco-mibs/hp",
                [44] "/home/netdisco/netdisco-mibs/hpe",
                [45] "/home/netdisco/netdisco-mibs/huawei",
                [46] "/home/netdisco/netdisco-mibs/ibm",
                [47] "/home/netdisco/netdisco-mibs/intel",
                [48] "/home/netdisco/netdisco-mibs/juniper",
                [49] "/home/netdisco/netdisco-mibs/korenix",
                [50] "/home/netdisco/netdisco-mibs/lancom",
                [51] "/home/netdisco/netdisco-mibs/lantronix",
                [52] "/home/netdisco/netdisco-mibs/lenovo",
                [53] "/home/netdisco/netdisco-mibs/liebert",
                [54] "/home/netdisco/netdisco-mibs/mediant",
                [55] "/home/netdisco/netdisco-mibs/mellanox",
                [56] "/home/netdisco/netdisco-mibs/meraki",
                [57] "/home/netdisco/netdisco-mibs/meru",
                [58] "/home/netdisco/netdisco-mibs/microsens",
                [59] "/home/netdisco/netdisco-mibs/mikrotik",
                [60] "/home/netdisco/netdisco-mibs/moser-baer",
                [61] "/home/netdisco/netdisco-mibs/motorola",
                [62] "/home/netdisco/netdisco-mibs/moxa",
                [63] "/home/netdisco/netdisco-mibs/nateks",
                [64] "/home/netdisco/netdisco-mibs/net-snmp",
                [65] "/home/netdisco/netdisco-mibs/netapp",
                [66] "/home/netdisco/netdisco-mibs/netgear",
                [67] "/home/netdisco/netdisco-mibs/netonix",
                [68] "/home/netdisco/netdisco-mibs/netscreen",
                [69] "/home/netdisco/netdisco-mibs/nexans",
                [70] "/home/netdisco/netdisco-mibs/nortel",
                [71] "/home/netdisco/netdisco-mibs/northerndesign",
                [72] "/home/netdisco/netdisco-mibs/oneaccess",
                [73] "/home/netdisco/netdisco-mibs/openbsd",
                [74] "/home/netdisco/netdisco-mibs/opengear",
                [75] "/home/netdisco/netdisco-mibs/packetfront",
                [76] "/home/netdisco/netdisco-mibs/paloalto",
                [77] "/home/netdisco/netdisco-mibs/pica8",
                [78] "/home/netdisco/netdisco-mibs/pulsesecure-gateway",
                [79] "/home/netdisco/netdisco-mibs/rad",
                [80] "/home/netdisco/netdisco-mibs/redlionram",
                [81] "/home/netdisco/netdisco-mibs/rfc",
                [82] "/home/netdisco/netdisco-mibs/rittal",
                [83] "/home/netdisco/netdisco-mibs/riverbed",
                [84] "/home/netdisco/netdisco-mibs/ruckus",
                [85] "/home/netdisco/netdisco-mibs/schleifenbauer",
                [86] "/home/netdisco/netdisco-mibs/sentry",
                [87] "/home/netdisco/netdisco-mibs/siemens",
                [88] "/home/netdisco/netdisco-mibs/sixnet",
                [89] "/home/netdisco/netdisco-mibs/sonicwall",
                [90] "/home/netdisco/netdisco-mibs/teleste",
                [91] "/home/netdisco/netdisco-mibs/teltonika",
                [92] "/home/netdisco/netdisco-mibs/tplink",
                [93] "/home/netdisco/netdisco-mibs/trapeze",
                [94] "/home/netdisco/netdisco-mibs/ubnt",
                [95] "/home/netdisco/netdisco-mibs/vmware",
                [96] "/home/netdisco/netdisco-mibs/watchguard",
                [97] "/home/netdisco/netdisco-mibs/wipipe",
                [98] "/home/netdisco/netdisco-mibs/xedia",
                [99] "/home/netdisco/netdisco-mibs/xirrus"
            ],
            NonIncreasing       0,
            RemotePort          161,
            Retries             0,
            Session             SNMP::Session,
            Timeout             3000000,
            Version             2
        },
        BulkRepeaters       20,
        BulkWalk            1,
        class               "SNMP::Info::Layer2::Airespace",
        debug               1,
        funcs               {
            airespace_ap_ethermac     "bsnAPEthernetMacAddress",
            airespace_ap_fw           "bsnAPBootVersion",
            airespace_ap_ip           "bsnApIpAddress",
            airespace_ap_loc          "bsnAPLocation",
            airespace_ap_mac          "bsnAPDot3MacAddress",
            airespace_ap_model        "bsnAPModel",
            airespace_ap_name         "bsnAPName",
            airespace_ap_serial       "bsnAPSerialNumber",
            airespace_ap_status       "bsnAPAdminStatus",
            airespace_ap_sw           "bsnAPSoftwareVersion",
            airespace_ap_type         "bsnAPType",
            airespace_apif            "bsnAPIfOperStatus",
            airespace_apif_a_pwr      "bsnAPIfAbsolutePowerList",
            airespace_apif_admin      "bsnAPIfAdminStatus",
            airespace_apif_ch_num     "bsnAPIfPhyChannelNumber",
            airespace_apif_oride      "bsnAPIfWlanOverride",
            airespace_apif_power      "bsnAPIfPhyTxPowerLevel",
            airespace_apif_slot       "bsnAPIfSlotId",
            airespace_apif_type       "bsnAPIfType",
            airespace_bl_descr        "bsnBlackListClientDescription",
            airespace_bl_mac          "bsnBlackListClientMacAddress",
            airespace_bl_rstat        "bsnBlackListClientRowStatus",
            airespace_duplex          "agentPortPhysicalStatus",
            airespace_duplex_admin    "agentPortPhysicalMode",
            airespace_ess_aclname     "bsnDot11EssAclName",
            airespace_ess_bcast       "bsnDot11EssBroadcastSsid",
            airespace_ess_idx         "bsnDot11EssIndex",
            airespace_ess_ifname      "bsnDot11EssInterfaceName",
            airespace_ess_macflt      "bsnDot11EssMacFiltering",
            airespace_ess_qos         "bsnDot11EssQualityOfService",
            airespace_ess_radio_pol   "bsnDot11EssRadioPolicy",
            airespace_ess_sec_auth    "bsnDot11EssSecurityAuthType",
            airespace_ess_ssid        "bsnDot11EssSsid",
            airespace_ess_status      "bsnDot11EssAdminStatus",
            airespace_if_acl          "agentInterfaceAclName",
            airespace_if_ip           "agentInterfaceIPAddress",
            airespace_if_mac          "agentInterfaceMacAddress",
            airespace_if_mask         "agentInterfaceIPNetmask",
            airespace_if_name         "agentInterfaceName",
            airespace_if_rstat        "agentInterfaceRowStatus",
            airespace_if_type         "agentInterfaceType",
            airespace_if_vlan         "agentInterfaceVlanId",
            airespace_oride_id        "bsnAPIfWlanOverrideId",
            airespace_oride_ssid      "bsnAPIfWlanOverrideSsid",
            airespace_sta_delete      "bsnMobileStationDeleteAction",
            airespace_sta_ess_idx     "bsnMobileStationEssIndex",
            airespace_sta_ip          "bsnMobileStationIpAddress",
            airespace_sta_mac         "bsnMobileStationAPMacAddr",
            airespace_sta_slot        "bsnMobileStationAPIfSlotId",
            airespace_sta_ssid        "bsnMobileStationSsid",
            airespace_user_access     "bsnUserAccessMode",
            airespace_user_ess_idx    "bsnUserEssIndex",
            airespace_user_ifname     "bsnUserInterfaceName",
            airespace_user_name       "bsnUserName",
            airespace_user_pw         "bsnUserPassword",
            airespace_user_rstat      "bsnUserRowStatus",
            airespace_user_type       "bsnUserType",
            ap_if_mac                 "cLApIfMacAddress",
            bp_index                  "dot1dBasePortIfIndex",
            bp_port                   "dot1dBasePortCircuit",
            bs_mac                    "dot1dStaticAddress",
            bs_port                   "dot1dStaticReceivePort",
            bs_status                 "dot1dStaticStatus",
            bs_to                     "dot1dStaticAllowedToGoTo",
            cd11_proto                "cldcClientProtocol",
            cd11_rateset              "cldcClientDataRateSet",
            cd11_rxbyte               "bsnMobileStationBytesReceived",
            cd11_rxpkt                "bsnMobileStationPacketsReceived",
            cd11_sigqual              "bsnMobileStationSnr",
            cd11_sigstrength          "bsnMobileStationRSSI",
            cd11_ssid                 "bsnMobileStationSsid",
            cd11_txbyte               "bsnMobileStationBytesSent",
            cd11_txpkt                "bsnMobileStationPacketsSent",
            cd11n_ch_bw               "cldHtDot11nChannelBandwidth",
            cdp_addr                  "cdpCacheAddress",
            cdp_capabilities          "cdpCacheCapabilities",
            cdp_dev_id                "cdpCacheDeviceId",
            cdp_dev_port              "cdpCacheDevicePort",
            cdp_domain                "cdpCacheVTPMgmtDomain",
            cdp_duplex                "cdpCacheDuplex",
            cdp_platform              "cdpCachePlatform",
            cdp_power                 "cdpCachePowerConsumption",
            cdp_pri_mgmt_addr         "cdpCachePrimaryMgmtAddr",
            cdp_pri_mgmt_type         "cdpCachePrimaryMgmtAddrType",
            cdp_proto                 "cdpCacheAddressType",
            cdp_sec_mgmt_addr         "cdpCacheSecondaryMgmtAddr",
            cdp_sec_mgmt_type         "cdpCacheSecondaryMgmtAddrType",
            cdp_ver                   "cdpCacheVersion",
            cdp_vlan                  "cdpCacheNativeVLAN",
            client_txrate             "cldcClientCurrentTxRateSet",
            fw_mac                    "bsnMobileStationMacAddress",
            fw_port                   "dot1dTpFdbPort",
            fw_status                 "dot1dTpFdbStatus",
            i_alias                   "ifAlias",
            i_bad_proto_in            "ifInUnknownProtos",
            i_description             "ifDescr",
            i_discards_in             "ifInDiscards",
            i_discards_out            "ifOutDiscards",
            i_errors_in               "ifInErrors",
            i_errors_out              "ifOutErrors",
            (...skipping 81 keys...)
        },
        globals             {
            airespace_bssid_mode   "agentNetworkBroadcastSsidMode",
            airespace_lwapp_mode   "agentSwitchLwappTransportMode",
            airespace_mac          "agentInventoryBurnedInMacAddress",
            airespace_maint_ver    "agentInventoryMaintenanceLevel",
            airespace_mc_mode      "agentNetworkMulticastMode",
            airespace_model        "agentInventoryMachineModel",
            airespace_os           "agentInventoryOperatingSystem",
            airespace_prod_name    "agentInventoryProductName",
            airespace_serial       "agentInventorySerialNumber",
            airespace_type         "agentInventoryMachineType",
            airespace_ul_file      "agentTransferUploadFilename",
            airespace_ul_ip        "agentTransferUploadServerIP",
            airespace_ul_mode      "agentTransferUploadMode",
            airespace_ul_path      "agentTransferUploadPath",
            airespace_ul_start     "agentTransferUploadStart",
            airespace_ul_status    "agentTransferUploadStatus",
            airespace_ul_type      "agentTransferUploadDataType",
            airespace_vendor       "agentInventoryManufacturerName",
            b_mac                  "dot1dBaseBridgeAddress",
            b_ports                "dot1dBaseNumPorts",
            b_type                 "dot1dBaseType",
            cdp_gid                "cdpGlobalDeviceId",
            cdp_holdtime           "cdpGlobalHoldTime",
            cdp_interval           "cdpGlobalMessageInterval",
            cdp_run                "cdpGlobalRun",
            contact                "sysContact",
            description            "sysDescr",
            id                     "sysObjectID",
            ipforwarding           "ipForwarding",
            layers                 "sysServices",
            location               "sysLocation",
            name                   "sysName",
            os_ver                 "agentInventoryProductVersion",
            ports                  "ifNumber",
            qb_next_vlan_index     "dot1qNextFreeLocalVlanIndex",
            qb_vlans               "dot1qNumVlans",
            qb_vlans_max           "dot1qMaxSupportedVlans",
            stp_priority           "dot1dStpPriority",
            stp_root               "dot1dStpDesignatedRoot",
            stp_root_port          "dot1dStpRootPort",
            stp_time               "dot1dStpTimeSinceTopologyChange",
            stp_ver                "dot1dStpProtocolSpecification",
            uptime                 "sysUpTime"
        },
        IgnoreNetSNMPConf   1,
        init                \ 1,
        mibdirs             var{args}{MibDirs},
        mibs                {
            AIRESPACE-SWITCHING-MIB        "agentInventorySerialNumber",
            AIRESPACE-WIRELESS-MIB         "bsnAPName",
            BRIDGE-MIB                     "dot1dBaseBridgeAddress",
            CISCO-CDP-MIB                  "cdpGlobalRun",
            CISCO-LWAPP-AP-MIB             "cLApIfMacAddress",
            CISCO-LWAPP-DOT11-CLIENT-MIB   "cldcClientCurrentTxRateSet",
            CISCO-LWAPP-DOT11-MIB          "cldHtDot11nChannelBandwidth",
            IF-MIB                         "ifIndex",
            IP-MIB                         "ipAdEntAddr",
            Q-BRIDGE-MIB                   "dot1qPvid",
            RSTP-MIB                       "dot1dStpPortOperEdgePort",
            SNMPv2-MIB                     "sysObjectID"
        },
        munge               {
            airespace_ap_ethermac   sub { ... },
            airespace_ap_mac        var{munge}{airespace_ap_ethermac},
            airespace_bl_mac        var{munge}{airespace_ap_ethermac},
            airespace_if_mac        var{munge}{airespace_ap_ethermac},
            airespace_sta_mac       var{munge}{airespace_ap_ethermac},
            ap_if_mac               var{munge}{airespace_ap_ethermac},
            b_mac                   var{munge}{airespace_ap_ethermac},
            bs_mac                  var{munge}{airespace_ap_ethermac},
            cd11_proto              sub { ... },
            cd11_rateset            sub { ... },
            cd11_rxpkt              sub { ... },
            cd11_txpkt              var{munge}{cd11_rxpkt},
            cd11n_ch_bw             sub { ... },
            cdp_capabilities        sub { ... },
            cdp_domain              sub { ... },
            cdp_ip                  sub { ... },
            cdp_platform            var{munge}{cdp_domain},
            cdp_power               sub { ... },
            cdp_ver                 var{munge}{cdp_domain},
            fw_mac                  var{munge}{airespace_ap_ethermac},
            fw_port                 var{munge}{airespace_ap_ethermac},
            i_mac                   var{munge}{airespace_ap_ethermac},
            i_octet_in64            sub { ... },
            i_octet_out64           var{munge}{i_octet_in64},
            i_pkts_bcast_in64       var{munge}{i_octet_in64},
            i_pkts_bcast_out64      var{munge}{i_octet_in64},
            i_pkts_multi_out64      var{munge}{i_octet_in64},
            i_pkts_mutli_in64       var{munge}{i_octet_in64},
            i_pkts_ucast_in64       var{munge}{i_octet_in64},
            i_pkts_ucast_out64      var{munge}{i_octet_in64},
            i_speed                 sub { ... },
            i_speed_high            sub { ... },
            i_up                    sub { ... },
            ip                      var{munge}{cdp_ip},
            layers                  sub { ... },
            mac                     var{munge}{airespace_ap_ethermac},
            qb_cv_egress            sub { ... },
            qb_cv_untagged          var{munge}{qb_cv_egress},
            qb_v_egress             var{munge}{qb_cv_egress},
            qb_v_fbdn_egress        var{munge}{qb_cv_egress},
            qb_v_untagged           var{munge}{qb_cv_egress},
            stp_i_mac               var{munge}{airespace_ap_ethermac},
            stp_i_root              sub { ... },
            stp_p_bridge            var{munge}{stp_i_root},
            stp_p_port              sub { ... },
            stp_p_root              var{munge}{stp_i_root},
            stp_root                var{munge}{stp_i_root}
        },
        nosuch              1,
        sess                var{args}{Session},
        snmp_comm           "xxx",
        snmp_user           "initial",
        snmp_ver            2,
        store               {}
    }
}
[114357] 2021-09-20 11:23:49  info show: finished at Mon Sep 20 11:23:49 2021
[114357] 2021-09-20 11:23:49  info show: status done: Showed specify response from 172.30.16.6
~/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Discover $

**Comment by ollyg** [comment]
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Discover/Wireless.pm#L57

**Comment by ollyg** [comment]
fixed in 854f19d4

**Comment by jkleinhans** [comment]
Thanks for fixing the problem.
