### ISSUE TITLE
Create SECURITY.md for the repo

### ISSUE THREAD

**Issue by zidingz** [netdisco/netdisco#819]
Hey there!

I belong to an open source security research community, and a member (@ktg9) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ollyg** [comment]
Hi Ziding

Many thanks for raising this! I will look into it.

If you need to get in touch more immediately, you can email me at
***@***.*** for a discussion.

We can also open an issue and then mark it as security related which I
believe hides it from non-project-admin eyes.

regards
Oliver Gorwits.

**Comment by ollyg** [comment]
Hi @zidingz any follow up on this that you want to do? I am keen to address any found security issues!

**Comment by zidingz** [comment]
Hey @ollyg, so sorry for missing your message, and I appreciate your initiative! We just need to let the repository confirm your email as its security contact via merge. You'll receive an email shortly after that. Thanks!

**Comment by ollyg** [comment]
Thanks! I didn't realise that's what you were waiting for, so thank you for the patch :-)
It has been applied.
