### ISSUE TITLE
Internal Server Error after MAC Search

### ISSUE THREAD

**Issue by florianhahner84** [netdisco/netdisco#820]
Hi, 

after Update to the latest version i get a Internal Server Error 500 if i try to search after MAC addresses

Here my setup:
App::Netdisco | 2.47.5
Perl | 5.16.3

In netdisco-web.log i get 
`[16713] 2021-09-27 09:00:33 error request to GET /search crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: FEHLER:  Spalte me.chassis_id existiert nicht
LINE 1: ...tion, me.layers, me.num_ports, me.mac, me.serial, me.chassis...
                                                             ^ [for Statement "SELECT COUNT( * ) FROM (SELECT me.ip, me.creation, me.dns, me.description, me.uptime, me.contact, me.name, me.location, me.layers, me.num_ports, me.mac, me.serial, me.chassis_id, me.model, me.ps1_type, me.ps2_type, me.ps1_status, me.ps2_status, me.fan, me.slots, me.vendor, me.os, me.os_ver, me.log, me.snmp_ver, me.snmp_comm, me.snmp_class, me.snmp_engineid, me.vtp_domain, me.last_discover, me.last_macsuck, me.last_arpnip FROM device me LEFT JOIN device_port ports_by_mac ON ( ports_by_mac.ip = me.ip AND ports_by_mac.mac::text ILIKE ? ) LEFT JOIN device_ip device_ips_by_address_or_name ON ( ( device_ips_by_address_or_name.dns ILIKE ? OR device_ips_by_address_or_name.alias <<= ? OR device_ips_by_address_or_name.alias::text ILIKE ? ) AND device_ips_by_address_or_name.ip = me.ip ) WHERE ( ( me.contact ILIKE ? OR me.serial ILIKE ? OR me.chassis_id ILIKE ? OR me.location ILIKE ? OR me.name ILIKE ? OR me.description ILIKE ? OR me.ip IN ( SELECT me.ip FROM device me LEFT JOIN device_module modules ON modules.ip = me.ip WHERE ( modules.serial = ? ) ) OR ( me.mac::text ILIKE ? OR ports_by_mac.mac::text ILIKE ? ) OR ( me.dns ILIKE ? OR device_ips_by_address_or_name.dns ILIKE ? ) OR ( me.ip::text ILIKE ? OR device_ips_by_address_or_name.alias::text ILIKE ? ) ) ) GROUP BY me.ip, me.creation, me.dns, me.description, me.uptime, me.contact, me.name, me.location, me.layers, me.num_ports, me.mac, me.serial, me.chassis_id, me.model, me.ps1_type, me.ps2_type, me.ps1_status, me.ps2_status, me.fan, me.slots, me.vendor, me.os, me.os_ver, me.log, me.snmp_ver, me.snmp_comm, me.snmp_class, me.snmp_engineid, me.vtp_domain, me.last_discover, me.last_macsuck, me.last_arpnip) me" with ParamValues: 1='b4:8b:19:20:7a:95', 2='%B4:8B:19:20:7A:95%', 3='255.255.255.255/32', 4='%B4:8B:19:20:7A:95%', 5='%B4:8B:19:20:7A:95%', 6='%B4:8B:19:20:7A:95%', 7='%B4:8B:19:20:7A:95%', 8='%B4:8B:19:20:7A:95%', 9='%B4:8B:19:20:7A:95%', 10='%B4:8B:19:20:7A:95%', 11='B4:8B:19:20:7A:95', 12='b4:8b:19:20:7a:95', 13='b4:8b:19:20:7a:95', 14='%B4:8B:19:20:7A:95%', 15='%B4:8B:19:20:7A:95%', 16='%B4:8B:19:20:7A:95%', 17='%B4:8B:19:20:7A:95%'] at /home/netdisco/perl5/lib/perl5/App/Netdisco/Web/Search.pm line 48
Use of uninitialized value $server in concatenation (.) or string at /home/netdisco/perl5/lib/perl5/Dancer/Request.pm line 270.
Use of uninitialized value $port in concatenation (.) or string at /home/netdisco/perl5/lib/perl5/Dancer/Request.pm line 270.
`

**Comment by ollyg** [comment]
Hi Florian

I believe this was fixed in 2.049005 - would you please upgrade (with
netdisco-deploy) and try again?

regards
Oliver.

**Comment by florianhahner84** [comment]
I'm so sorry. I forgot the netdisco-deploy step to upgrade the database-schema. Now its working as it should. Thank you for your help.
