### ISSUE TITLE
DB Currently Unversioned error

### ISSUE THREAD

**Issue by altoidan** [netdisco/netdisco#823]
## Expected Behavior

Running command ~/bin/netdisco-deploy should not fail after DB Schema Update Complete message

## Current Behavior

~/bin/netdisco-deploy
This is the Netdisco 2 deployment script.

So, is all of the above in place? [y/N]: y

Would you like to deploy the database schema? [y/N]: y
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL:  Peer authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/bin/netdisco-db-deploy line 110 at /home/netdisco/perl5/bin/netdisco-db-deploy line 110
DB schema update complete.
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL:  Peer authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Statistics.pm line 37

When running DBIC_TRACE=1 ~/bin/netdisco-deploy, this is what I'm getting.

DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
DBI Connection failed: DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL:  Peer authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1118.
	DBIx::Class::Schema::throw_exception(App::Netdisco::DB=HASH(0x55b9ecb01dd8), "DBI Connection failed: DBI connect('dbname=netdisco','changem"...) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage.pm line 113
	DBIx::Class::Storage::throw_exception(DBIx::Class::Storage::DBI=HASH(0x55b9eee2afc0), "DBI Connection failed: DBI connect('dbname=netdisco','changem"...) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1680
	DBIx::Class::Storage::DBI::catch {...} ("DBI connect('dbname=netdisco','changeme',...) failed: FATAL: "...) called at /usr/share/perl5/Try/Tiny.pm line 123
	Try::Tiny::try(CODE(0x55b9efe08ce8), Try::Tiny::Catch=REF(0x55b9f0054e48)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1681
	DBIx::Class::Storage::DBI::_connect(DBIx::Class::Storage::DBI=HASH(0x55b9eee2afc0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1047
	DBIx::Class::Storage::DBI::_populate_dbh(DBIx::Class::Storage::DBI=HASH(0x55b9eee2afc0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 961
	DBIx::Class::Storage::DBI::dbh(DBIx::Class::Storage::DBI=HASH(0x55b9eee2afc0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema/Versioned.pm line 596
	DBIx::Class::Schema::Versioned::__ANON__() called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1635
	DBIx::Class::Storage::DBI::try {...} () called at /usr/share/perl5/Try/Tiny.pm line 102
	eval {...} called at /usr/share/perl5/Try/Tiny.pm line 93
	Try::Tiny::try(CODE(0x55b9efe139a8), Try::Tiny::Catch=REF(0x55b9f004d030)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1681
	DBIx::Class::Storage::DBI::_connect(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1047
	DBIx::Class::Storage::DBI::_populate_dbh(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1356
	DBIx::Class::Storage::DBI::_extract_driver_from_connect_info(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1300
	DBIx::Class::Storage::DBI::_determine_driver(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8)) called at (eval 348) line 37
	DBIx::Class::Storage::DBI::deployment_statements(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8), DBIx::Class::Version=HASH(0x55b9efe01940), undef, undef, undef, HASH(0x55b9efdf32e0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1173
	DBIx::Class::Schema::deployment_statements(DBIx::Class::Version=HASH(0x55b9efe01940), undef, undef, undef, HASH(0x55b9efdf32e0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 3277
	DBIx::Class::Storage::DBI::deploy(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8), DBIx::Class::Version=HASH(0x55b9efe01940), undef, undef, undef) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1147
	DBIx::Class::Schema::deploy(DBIx::Class::Version=HASH(0x55b9efe01940)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema/Versioned.pm line 260
	DBIx::Class::Schema::Versioned::install(App::Netdisco::DB=HASH(0x55b9ecb01dd8), 1) called at /home/netdisco/perl5/bin/netdisco-db-deploy line 110 at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1118.
	DBIx::Class::Schema::throw_exception(DBIx::Class::Version=HASH(0x55b9efe01940), "DBI Connection failed: DBI Connection failed: DBI connect('db"...) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage.pm line 113
	DBIx::Class::Storage::throw_exception(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8), "DBI Connection failed: DBI Connection failed: DBI connect('db"...) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1680
	DBIx::Class::Storage::DBI::catch {...} (DBIx::Class::Exception=HASH(0x55b9f0054638)) called at /usr/share/perl5/Try/Tiny.pm line 123
	Try::Tiny::try(CODE(0x55b9efe139a8), Try::Tiny::Catch=REF(0x55b9f004d030)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1681
	DBIx::Class::Storage::DBI::_connect(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1047
	DBIx::Class::Storage::DBI::_populate_dbh(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1356
	DBIx::Class::Storage::DBI::_extract_driver_from_connect_info(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1300
	DBIx::Class::Storage::DBI::_determine_driver(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8)) called at (eval 348) line 37
	DBIx::Class::Storage::DBI::deployment_statements(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8), DBIx::Class::Version=HASH(0x55b9efe01940), undef, undef, undef, HASH(0x55b9efdf32e0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1173
	DBIx::Class::Schema::deployment_statements(DBIx::Class::Version=HASH(0x55b9efe01940), undef, undef, undef, HASH(0x55b9efdf32e0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 3277
	DBIx::Class::Storage::DBI::deploy(DBIx::Class::Storage::DBI=HASH(0x55b9efe017a8), DBIx::Class::Version=HASH(0x55b9efe01940), undef, undef, undef) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1147
	DBIx::Class::Schema::deploy(DBIx::Class::Version=HASH(0x55b9efe01940)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema/Versioned.pm line 260
	DBIx::Class::Schema::Versioned::install(App::Netdisco::DB=HASH(0x55b9ecb01dd8), 1) called at /home/netdisco/perl5/bin/netdisco-db-deploy line 110

DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL:  Peer authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1118, <FIN> line 2.
	DBIx::Class::Schema::throw_exception(App::Netdisco::DB=HASH(0x55dd33a07048), "DBI Connection failed: DBI connect('dbname=netdisco','changem"...) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage.pm line 113
	DBIx::Class::Storage::throw_exception(DBIx::Class::Storage::DBI=HASH(0x55dd33a563d0), "DBI Connection failed: DBI connect('dbname=netdisco','changem"...) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1680
	DBIx::Class::Storage::DBI::catch {...} ("DBI connect('dbname=netdisco','changeme',...) failed: FATAL: "...) called at /usr/share/perl5/Try/Tiny.pm line 123
	Try::Tiny::try(CODE(0x55dd33a070d8), Try::Tiny::Catch=REF(0x55dd34cf5e88)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1681
	DBIx::Class::Storage::DBI::_connect(DBIx::Class::Storage::DBI=HASH(0x55dd33a563d0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1047
	DBIx::Class::Storage::DBI::_populate_dbh(DBIx::Class::Storage::DBI=HASH(0x55dd33a563d0)) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 961
	DBIx::Class::Storage::DBI::dbh(DBIx::Class::Storage::DBI=HASH(0x55dd33a563d0)) called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Statistics.pm line 37
	App::Netdisco::Util::Statistics::update_stats() called at /home/netdisco/bin/netdisco-deploy line 156
	main::deploy_db() called at /home/netdisco/bin/netdisco-deploy line 122

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Context

Install netdisco on Ubuntu.

The Ubuntu server is running on a Vcenter appliance and is solely being used for Netdisco deployment.
## Your Environment

* Netdisco version used: 2
* SNMP::Info version used: 

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
Hello, as you can see on the logs, the error is the connection to the
database is failing because the password is still “changeme”.

So I think you missed a step to copy and edit the deployment.yml file?

**Comment by altoidan** [comment]
Thanks for the quick response. My apologies for a dumb question!
