### ISSUE TITLE
FR Report - IP Subnets (with links to Inventory and Utilization)

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#830]
When looking at the IP Inventory view, a CIDR Prefix/Subnet needs to be specified in the text box.

This field will prompt autocomplete suggestions if you type in three digits, but in some situations you may not actually know all the IP ranges that are being used on your network.

If the autocomplete list could be made to appear just by clicking the text field I think it would be a significant usability improvement. 

I think it would also be of beneift if the default view had some placeholder text saying "Please enter a CIDR Prefix/Subnet to view" in the main report body, because at the moment it's just a white screen and at first glance it looks like something isn't working (until your're familiar with it).

**Comment by ollyg** [comment]
It should look like this, prompting you. But yes there's no auto showing of prefixes. I have an idea to try...

![image](https://user-images.githubusercontent.com/29653/144266118-ff570cdb-0857-450f-a67e-09cf480bfc70.png)

**Comment by ollyg** [comment]
improved in bf64f0f3
