### ISSUE TITLE
Feature suggestion - highlighting 'last seen' entry 

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#831]
When a node or IP address has been seen in multiple locations, it isn't immediately obvious which the most recent (i.e. most current) entry is for it in the node view.

If the most recent entry could be highlighted in some way (e.g. with an icon, or changing the row colour slightly) it would be an easy way of drawing the eye to what is (probably) the record you want.

**Comment by ollyg** [comment]
duplicate
