### ISSUE TITLE
Netdisco 2.050001 swagger api can't parse json result

### ISSUE THREAD

**Issue by prasertsook** [netdisco/netdisco#832]
I search the nodes on swagger api and found that the response can't parse json result.
<img width="1401" alt="Screen Shot 2564-10-19 at 08 49 48" src="https://user-images.githubusercontent.com/11386532/137834754-11b228ad-75a8-4990-b816-e65fa15ad10c.png">

**Comment by sibelle-labs** [comment]
Same problem after update, since about 1 week ago.

**Comment by prasertsook** [comment]
@ollyg Thank you for your help.
