### ISSUE TITLE
netdisco-do doesn't delete from discovery queue

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#833]
## Expected Behavior

deleting a once known device via netdisco-do delete should remove it from the discover queue

## Current Behavior

only deleting via the web gui seems to remove it from the discover queue

## Possible Solution

perhaps using `--enqueue` option could work?

## Steps to Reproduce (for bugs)

1. have a device that was once known but is offline
2. notice it's still queueing when using "discover all" from the web gui
3. try & delete it with netdisco-do
```
testdisc@linux002:~> netdisco-do delete -d 10.98.200.49
[23919] 2021-10-22 04:05:08  info App::Netdisco version 2.050003 loaded.
[23919] 2021-10-22 04:05:08  info delete: [10.98.200.49] started at Fri Oct 22 06:05:08 2021
[23919] 2021-10-22 04:05:08  info delete: finished at Fri Oct 22 06:05:08 2021
[23919] 2021-10-22 04:05:08  info delete: status done: Deleted device: 10.98.200.49
```
4. try it again
```
testdisc@linux002:~> netdisco-do delete -d 10.98.200.49
[23935] 2021-10-22 04:06:38  info App::Netdisco version 2.050003 loaded.
[23935] 2021-10-22 04:06:38  info delete: error - Don't know device: 10.98.200.49
```
5. notice it's still in the web gui job queue
6. deleting via the web gui does seem to work

## Your Environment

* Netdisco version used: 2.050003
* SNMP::Info version used: 3.81

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
Well, the web and the CLI use the same exact code which is `delete_device()` and the `delete()` method from the Device class:

https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Web/AdminTask.pm#L49
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Delete.pm#L15
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Util/Device.pm#L76
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/DB/ResultSet/Device.pm#L692

One thing I can think of is that the `delete()` routine does empty the job queue of jobs for the device *except* any which are actually running at the time. So you could have a discover running which will then repopulate the database. The way to tell, I think, might be to look at the `creation` field of the device in the database (or perhaps not, I'm not sure).

Other than that, no idea right now, sorry!
