### ISSUE TITLE
VLAN Mismatch report - add sysname, port comment, and vlan diff

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#834]
The 'Port VLAN Mismatches' report is proving extremely useful in resolving oddities, but in a very odd environment but it requires some wrangling. I've got some suggestions for cosmetic improvements which I hope would be feasible to implement.

- Device names show as IP address -- many of the entires in my list have an IP address instead of a device name. Many of our switches have multiple IP addresses, and not all of these have DNS entries. I think it woud be helpful if the device column could return system name in all cases.
- Port comments - it would be nice if the port column could also include port comments as well as iface names.
- Diff column for VLANs -- we have quite a lot of vlans and reconciling the entries to find the missing ones can be difficult. It would be really useful if there was a middle column that showed a diff of the left and right values, e.g. <130 (to show that 130 was on the left but not the right).

Thanks for considering!

**Comment by ollyg** [comment]
https://metacpan.org/pod/List::MoreUtils#listcmp-ARRAY0-ARRAY1-%5B-ARRAY2-...-%5D

**Comment by ollyg** [comment]
Add sysname below the dns/ip, and add comment below the port name

**Comment by ollyg** [comment]
now implemented
