### ISSUE TITLE
snmpretries setting doesn't work

### ISSUE THREAD

**Issue by rkerr** [netdisco/netdisco#835]
Regardless of what you set snmpretries to a value of 0 is passed to SNMP::Info. This is due to the code at line 129 in netdisco/lib/App/Netdisco/Transport/SNMP.pm:

`Retries => (setting('snmpretries') || setting('snmpretries') == 0 ? 0 : 2),`

Should probably be:

`Retries => (setting('snmpretries') || (setting('snmpretries') == 0 ? 0 : 2)),`

**Comment by rc9000** [comment]
Thanks for spotting this, fixed with a defined() ternary, this makes the default work but also allows 0 as actual value

    defined(setting('snmpretries')) ? setting('snmpretries') : 2
