### ISSUE TITLE
Feature Request: "Cloud-Managed" Devices

### ISSUE THREAD

**Issue by sempervictus** [netdisco/netdisco#839]
## Context
Vendors are disabling, eschewing, or just ignoring implementation of SNMP in an increasingly large number of model lines - Aruba InstantOn APs, Arista Wireless (they bought Mojo), etc. They are replacing these systems with proprietary WAN-based API endpoints permitting interrogation and management of device/cluster configuration.

## Possible Solution
The control APIs generally contain all of the data elements sought by SNMP interrogation today - names, serial #s, interfaces, VLANs, addresses, routes, etc. Interrogation of these control APIs in conjunction with adjacent SNMP-enabled equipment can help flesh out the network topology of heterogeneous environments utilizing these proprietary stacks.

**Comment by ollyg** [comment]
Hi @sempervictus thanks for the ticket. Netdisco already has a lot of the scaffolding required to get this working, and in fact the SSH-based ARP table retrieval is an example of non-SNMP replacement. What's missing are:

- an HTTP "Transport" (alongside the existing SSH and SNMP Transports) which is a reusable instance of HTTP Client which is configured via Netdisco's `device_auth` settings
- the non-SNMP worker tasks for the different things you mention such as interfaces, etc (what already exists for ARP via SSH, see: https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Arpnip/Nodes.pm)

However the main issue is any of the dev team having access to any of these APIs (which are usually only available via the vendor product, not openly documented or testable, not standardised, etc).

That is, it is not a case of coding or features in Netdisco, more a problem of access to the APIs for testing and development.

**Comment by ollyg** [comment]
Another headache is that vendors will implement even standard REST APIs slightly differently, including how to access the API itself. For SNMP this issue already existed and so SNMP::Info Perl module exists to mask the vendor differences and provide stable and consistent ABI. For REST API we would need just the same.
