### ISSUE TITLE
when searching IP or device it shows "Error 500 Internal Server Error"

### ISSUE THREAD

**Issue by DonaldSee** [netdisco/netdisco#841]
## Expected Behavior

Result return

## Current Behavior

![image](https://user-images.githubusercontent.com/95044201/143479795-b399f3b6-5f92-476a-861b-85fe4c365426.png)

**netdisco-web.log shows:**
[28546] 2021-11-25 16:48:06 error request to GET /device crashed: core - template - undef error - DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg:: st execute failed: ERROR:  relation "device_browser" does not exist
LINE 1: SELECT COUNT( * ) FROM device_browser me ^ [for Statement "SELECT COUNT( * ) FROM device_browser me"] at /home/netdisco/perl5/lib/perl5/App/Netdisco/Web/Plugin/Device/SNMP.pm line 18  at /home/netdisco/perl5/lib/perl5/Dancer/Template/Abstract.pm line 91.

**Database tables**
![image](https://user-images.githubusercontent.com/95044201/143488632-4e0ba9db-29c5-48c6-af0e-a4628dae6b08.png)

## Steps to Reproduce (for bugs)

1. Upgraded from 2.42.10 to 2.51.4
2. Applied database schema using netdisco-deploy
3. Restarted both web and backend services
4. Search the IP or Mac from the top searching bar
5. Error happened

## Your Environment

* Netdisco version used: 2.51.4
* SNMP::Info version used: 3.81

## Device information

App::Netdisco version 2.051004 loaded.

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
Hi @DonaldSee the error really does suggest that when you ran `netdisco-deploy` you did not apply the schema updates. Please would you re-run the command and try again?

Many thanks

**Comment by DonaldSee** [comment]
@ollyg thanks for your reply.

I did ran the command when I upgraded from 2.42.10 to 2.51.1 and from 2.51.1 to 2.51.4.
now I ran the 3rd time but still the same.
![image](https://user-images.githubusercontent.com/95044201/143492461-b6b99805-bfb6-438a-b0ac-beb6de95c888.png)

**Comment by DonaldSee** [comment]
@ollyg 
We fixed our problem by using `netdisco-db-deploy --redeploy-all` to rebuild the database.

Thanks for your kindly help and NetDisco is awesome!!
