### ISSUE TITLE
A user should have many api key stored

### ISSUE THREAD

**Issue by ArthurHlt** [netdisco/netdisco#843]
## Expected Behavior
When I login through api i have an API Key and i can use api.
when i login a second time without have first API Key expired, I could still use my first api key which is still valid

## Current Behavior
When I login through api i have an API Key and i can use api.
when i login a second time without have first API Key expired, my first api key become unusable.

## Possible Solution
Instead of linking only one api key to user, user can have multiple api key.

## Steps to Reproduce (for bugs)
1. Login Api First time
2. Test first api key on api
3. Login a second time
4. Test same verb with first api key

## Context
I'm currently doing this https://github.com/orange-cloudfoundry/netdisco-bridges which needs access to api.
If I simply running 2 instances, api key will get deleted by other instance like they are not aware of api used by instance or another.

More it will have clients connecting to the user more it could break requests.

For now my workaround is:
1. set `api_token_lifetime: 1576800000` in netdisco configuration, this will set expiration time to 50 years for a token
2. Produce an api key on https://my.netdisco.com/swagger-ui
3. Use the same api key everywhere 

But this is really weak, if someone or something do login or logout, api key will change (or getting deleted)

**Comment by ollyg** [comment]
Hi @ArthurHlt can I ask, if you have two instances of clients, why they are not using two different users in Netdisco? That would avoid the issue.

**Comment by ArthurHlt** [comment]
Well, if you create an account for an server, but you have multiple instances of your server for HA purpose. The first instance login or get a token (but need to be refreshed after amount of time), the second instance do the same, first token get removed and server in first instance will stop working.

On a cloud environment you don't want to be aware that you have N instances and N accounts associated on each instance, it's terrible for development of a server using api or running them in a multi-instantiated environment.

**Comment by ollyg** [comment]
Thanks, and I agree. It helps to know the scenario.

What I propose to implement is that subsequent logins will reissue the existing same API key if it is still valid, and reset the validity timer. This is a bit like GitHub's sudo mode, where each use of the service extends the access time.

**Comment by ArthurHlt** [comment]
this can be a good idea and simple to implements yes

**Comment by ollyg** [comment]
implemented in d57db8b1

**Comment by ollyg** [comment]
Hi @ArthurHlt this is implemented and will be in the next release, maybe tonight or tomorrow.
Many thanks for the suggestion for improvement, much appreciated.

**Comment by ArthurHlt** [comment]
Many thanks for this new behavior and even more, thanks for making netdisco
