### ISSUE TITLE
Initial Screen - List of Devices

### ISSUE THREAD

**Issue by cesacal** [netdisco/netdisco#848]
We have been using switchmap for quite a long time, with a home screen as the one shown below:

![image](https://user-images.githubusercontent.com/97600299/149129666-d9f6205c-acfa-429d-8fdf-46c4be81fbaf.png)

Is there a posibility to show the devices inventoried on Netdisco in a similar way on a home screen?
Thanks in advance.

pd. I´m new at github, sorry if I should post this request on any other place in the forum.

**Comment by rc9000** [comment]
Hi! Currently Netdisco has no such feature. But it would be quite easy to make such a page by yourself just for your organization, by either connecting to the [REST API](https://github.com/netdisco/netdisco/wiki/API) or [the Postgres database](https://github.com/netdisco/netdisco/wiki/Database-Tips) directly.

Custom tagging of devices (what I assume your *pal*, *vll* etc. columns basically are) has been requested before, so I'll tag this as a whishlist item that's also pointing in that direction.

We're also very open to contributions, in case you or anybody else wants to have a shot at implementing this themselves.

**Comment by cesacal** [comment]
No need to have this report, because with "port utilization" report, and the rigth assignment of DNS names I already have this report.
