### ISSUE TITLE
"Cost must be an integer between 5 and 31"

### ISSUE THREAD

**Issue by am0nrahx** [netdisco/netdisco#849]
I have a Ubuntu 20 server that I am trying to deploy NetDisco to. I have followed the instructions here and did not get any abnormal messages until I went to run `"~/bin/netdisco-deploy"`

When it gets to the password portion of the admin account, it gives me the following error no matter what kind of password string I use:
`Cost must be an integer between 5 and 31 at /home/netdisco/perl5/lib/perl5/Dancer/Plugin/Passphrase.pm line 415.`

I commented out all the options I set in the deployment.yml file and only left the database connector and still got the same error.

**Comment by am0nrahx** [comment]
Update: I found the script [listed here](https://github.com/netdisco/netdisco/issues/692) and started over, I got the same error message and also the following:

`DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121`

The following error continues DB version (1) thru (69)
`DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (1) is lower than the schema version (70). Attempting 
`

**Comment by danila1994** [comment]
Try to reinstall everything one more time. I made that today and everything is working.

**Comment by am0nrahx** [comment]
> Try to reinstall everything one more time. I made that today and everything is working. I had the same problem, now that is gone by magic.

Weird, I got the errors below but the deployment continued past where it got stuck last time.

`Would you like to deploy the database schema? [y/N]: y`

`DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121`

`DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL:  Peer authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/bin/netdisco-db-deploy line 110 at /home/netdisco/perl5/bin/netdisco-db-deploy line 110`

`DB schema update complete.`

`DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121`

`DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL:  Peer authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Statistics.pm line 37`

`Updating statistics... `

Despite the errors, it continued and I am able to login to the web interface now. Are those errors concerning? Can they be safely ignored? LOL

**Comment by danila1994** [comment]
Change in that file credentials for connection to DB

~/environments/deployment.yml

**Comment by danila1994** [comment]
> Change in that file credentials for connection to DB
> 
> ~/environments/deployment.yml

Change in that file credentials for connection to DB

~/environments/deployment.yml

**Comment by danila1994** [comment]
> > Try to reinstall everything one more time. I made that today and everything is working. I had the same problem, now that is gone by magic.
> 
> Weird, I got the errors below but the deployment continued past where it got stuck last time.
> 
> `Would you like to deploy the database schema? [y/N]: y`
> 
> `DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121`
> 
> `DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL: Peer authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/bin/netdisco-db-deploy line 110 at /home/netdisco/perl5/bin/netdisco-db-deploy line 110`
> 
> `DB schema update complete.`
> 
> `DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121`
> 
> `DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','changeme',...) failed: FATAL: Peer authentication failed for user "changeme" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1639. at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Statistics.pm line 37`
> 
> `Updating statistics... `
> 
> Despite the errors, it continued and I am able to login to the web interface now. Are those errors concerning? Can they be safely ignored? LOL

Change in that file credentials for connection to DB

~/environments/deployment.yml

**Comment by am0nrahx** [comment]
Oh yes, sorry, I fixed that. Got the errors below but everything worked:

`DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121`
`DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (1) is lower than the schema version (70). Attempting upgrade.`
`DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (2) is lower than the schema version (70). Attempting upgrade.`
`DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (3) is lower than the schema version (70). Attempting upgrade.`
`DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (4) is lower than the schema version (70). Attempting upgrade.`

**Comment by rc9000** [comment]
Hi @am0nrahx, glad you got it working! The `DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (3) is lower than the schema version (70). Attempting upgrade.` messages are just the progress that is always shown, and since the first number increases the updates succeed. So your installation should be fine now.
