### ISSUE TITLE
NETDISCO https configuration

### ISSUE THREAD

**Issue by snmsmanager** [netdisco/netdisco#850]
Does any have a step-by-step guide for setting up netdisco with https?

**Comment by rc9000** [comment]
The documentation has [some hints (ok it's generous to call this hints, it's basically "use a reverse proxy")](https://github.com/netdisco/netdisco/wiki/Install-Tips#ssl-support) and [snippets for Apache](https://github.com/netdisco/netdisco/wiki/Install-Tips#behind-a-proxy), but they just cover the reverse proxy part and gloss over installation, SSL setup etc.

Nowadays Nginx seems to be more popular though, I did some search and [this article](https://github.com/netdisco/netdisco/wiki/Install-Tips#behind-a-proxy) seems to cover pretty much everything you'd need to do.

**Comment by rc9000** [comment]
Sorry I pasted the wrong link, I meant [this article](https://www.linkedin.com/pulse/how-use-nginx-reverse-proxy-https-wss-self-signed-ramos-da-silva).
