### ISSUE TITLE
Issue with snmp information on Allied Telesis devices

### ISSUE THREAD

**Issue by Kalastat** [netdisco/netdisco#855]
Hi guys,

I'm working for the vendor Allied Telesis, and we got an issue regarding the snmp informations that Netdisco can be traced back.

I have deployed a netdisco by default, using the MIBs include in the soft.

We are not able to get all informations. 

About Vlans, addresses, ports, everything looks OK:

![image](https://user-images.githubusercontent.com/99013577/152503627-93df908b-c9c6-48b6-8356-61572cdf5dbe.png)

![image](https://user-images.githubusercontent.com/99013577/152503654-3ab68f0a-7d5c-4f53-8fde-4fc7b556ab60.png)

![image](https://user-images.githubusercontent.com/99013577/152503675-8d0a8f0a-aee2-4380-9f22-72d407583ec4.png)

However, we aren't able to get by snmp the model and the vendor of devices (OS/Version, S/N also):

![image](https://user-images.githubusercontent.com/99013577/152503842-7eb7bcbd-e8d4-4157-bff3-828fd796bb8a.png)

![image](https://user-images.githubusercontent.com/99013577/152503873-17b1d349-10a9-4433-9625-8f412fb5cdc0.png)

I tried to use the latest MIBs we have on our side but the result still the same. Anyway the new MIBs is working on the same OID.

Do you have any ideas about what we can do to solve that? I'm able to make tests for you if needed.

Kind regards,

**Comment by Kalastatelite** [comment]
Hi @ollyg ,

sorry for the dealy, i was out of office for the last month.
I'll make you a return during this week.

Kins regards,

**Comment by tony-vanderpeet** [comment]
Hi @Kalastat

On this site:

https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers

you can read this:

207
  Allied Telesis, Inc.
    Hermin Anggawijaya
      hermin.anggawijaya&alliedtelesis.co.nz

which is probably not too surprising. The netdisco-mibs (https://github.com/netdisco/netdisco-mibs) project has, under the "allied" directory, a snapshot of the Allied Telesis MIBs. The commit referenced above (@ruppo68) also has the MIBs.

Breaking it down, enterprises.207.1 is {products} (from at-smi.mib). {products 1} is {bridgeRouter} (at-product.mib). {products 14} is {routerSwitch} (same MIB). Then:

enterprises.207.1.1.85 is {atAR4050SRouter}
enterprises.207.1.14.109 is  {atx51028GTX}

These products should have been added to the MIBs quite a few years ago, and certainly the MIB revisions found in the netdisco-mibs repo has these devices. I am not familiar enough with netdisco to know how to add MIBs, but maybe this will help?

Regards
Tony

**Comment by ollyg** [comment]
should be fixed by [1a42221](https://github.com/netdisco/snmp-info/commit/1a42221e587b0dd1a776d259a97082c5bfb3f58e) which is merged now
