### ISSUE TITLE
Arpnip not working

### ISSUE THREAD

**Issue by gmourani** [netdisco/netdisco#857]
Hello,

Arpnip is not working and I'm having problem getting the IP address associated to devices. When looking into netdisco-backend.log, I can see the following appearing many time : "my" variable @arps masks earlier declaration in same scope at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin/Arpnip/Nodes.pm line 100, <__ANONIO__> line 2. 

* Netdisco version used: 2.052001
* SNMP::Info version used: 3.81

Regards,

**Comment by ollyg** [comment]
fixed in 19bfc090

**Comment by ollyg** [comment]
Hi @gmourani sorry about that, I've just released version 2.052002 which should be available in a few hours.
