### ISSUE TITLE
Feature suggestion - SAML authentication

### ISSUE THREAD

**Issue by Chromy29FR** [netdisco/netdisco#858]
Hello all,

Do you think it could be possible to add SAML authentication to netdisco for SSO ?

Thanks for your work !

Have a nice day.

**Comment by ollyg** [comment]
Hi @Chromy29FR 

Short answer: no, sorry, actually this is not really something implemented in the web framework which Netdisco uses.

However if you reverse proxy to Netdisco from Apache, you can install all the authentication you need, there, and this has been implemented by some sites.

This is covered in our docs, here: https://github.com/netdisco/netdisco/wiki/Install-Tips#behind-a-proxy

I hope that helps,
oliver.
