### ISSUE TITLE
discover_phones=false does not disable uplink detection

### ISSUE THREAD

**Issue by cesacal** [netdisco/netdisco#862]
We are detecting some problems while searching on searching bar by label or description.
We have all the ports of our devices labeled with a description, to identify the network plug.

When I search any label I´m finding two situations, depending on the number of MACs on the port (see image attached "description example"):

 - If I search a description on a port with just one MAC and IP, the search works fine: see attached image-1
 - If I search a description on a port with 2 or more MACs and Ips, the search doesn´t not work if I don´t click on "uplinks" checkbutton: see image-2 and image-3

But the port is not an uplink, it´s a access port connecting against a PC and a cisco IP phone.
Is it possible to solve this issue, or at least to make the "uplink" checkbutton to be set by default, not to lose any info on our searchs.

![Description Example](https://user-images.githubusercontent.com/97600299/160332949-65c72a2d-2909-46ea-bc50-189a31b2eddc.jpg)
![image-1](https://user-images.githubusercontent.com/97600299/160332957-dacbaf35-5ca3-40d6-9ddf-14b931b90e66.jpg)
![image-2](https://user-images.githubusercontent.com/97600299/160332967-4b7d826e-7d88-49cd-a272-5316b7a6c6b8.jpg)
![image-3](https://user-images.githubusercontent.com/97600299/160332979-98ec20c8-7153-4546-be30-acdd96d3cb49.jpg)

**Comment by ollyg** [comment]
Hi @cesacal 

I believe this is happening because the phones are running CDP or LLDP which is picked up by Netdisco and makes Netdisco think they are network devices and therefore the connected port is an uplink. 

Perhaps the easiest solution is to change the discover_phones setting in your configuration file to false: https://github.com/netdisco/netdisco/wiki/Configuration#discover_phones
(actually, if this doesn't work, then it's a bug, please let me know!), and then re-run all discover and macsuck jobs.

Hope this helps,
Oliver.

**Comment by rc9000** [comment]
We had similar issues with Filers, UPS, ILO boards and similar devices that we want to threat like an end node, but that are a bit too smart and thus turn ports into uplinks. In the end I came up with this hook that can unset the is_uplink flag after discovery: https://github.com/rc9000/netdisco_discover_hook

Maybe it can help here too.

**Comment by cesacal** [comment]
Thanks to you both for your quick replys.
@ollyg we already have the phones and APs set to disabled on the discover.
@rc9000 we are going to deploy a similar hook, but setting the description to "cisco AIR-" and "IP Phones". 
I will let you know if it works.

**Comment by ollyg** [comment]
@cesacal have reopened as this is not the way I'd like Netdisco to work!

**Comment by cesacal** [comment]
@ollyg thanks a lot... please keep me posted.
If you need more info, let me know.

**Comment by ollyg** [comment]
this is surprisingly tricky to fix, at least correctly. that's why it's been a quiet ticket.

**Comment by cesacal** [comment]
We have deployed the hook @rc9000 recommended us to use, but it doesn´t work properly.
@ollyg let me know if you find the solution for the bug ;)

**Comment by ollyg** [comment]
Oh, @cesacal can you elaborate on what doesn't work about the hook? It'll help me understand what you want to achieve.

**Comment by cesacal** [comment]
I have many switches with Wifi APs and CISCO IP phones connected on their interfaces.
I have a description on the interfaces, to identify the network plug, I this description is the one I use on my search.

I will try to explain all this in an example.
Here you can see on of our switches, on the interface fa0/7 we have an AP WiFi, on the interface fa0/13 we have an Cisco Ip Phone:

![AP + IP Phone](https://user-images.githubusercontent.com/97600299/168785409-95ee8bdf-223d-40a2-808b-a81434aa6bf9.jpg)

If I search by the label 4JB33, I can find the port of the Cisco IP Phone, without clicking UPLINK:
![Search by label 4JB33](https://user-images.githubusercontent.com/97600299/168785892-cbb0e2a5-40f0-4aed-aae5-3385507fc25c.jpg)

If I search by the label 4JC07, I cannot find anything without clicking UPLINK:
![Search by label 4JC07](https://user-images.githubusercontent.com/97600299/168786098-6140585c-df13-49b2-941a-c9dd10184603.jpg)


After that, I make a manual discovery of the switch:
![Forced discovery](https://user-images.githubusercontent.com/97600299/168786292-cdd1c44b-c1d5-4c14-ba21-6505abd8b678.jpg)

Then, the hook makes its magic, changing the UPLINK to false on "cisco ip phones" and "cisco AIR", and after that:

![Search after forced discovery 4JB33](https://user-images.githubusercontent.com/97600299/168786440-30ceb72c-7d47-41e5-b324-2b10bfe8319b.jpg)
![Search after forced discovery 4JC07](https://user-images.githubusercontent.com/97600299/168786444-12045c04-59a3-4ab0-8484-0a962f11892f.jpg)

**Comment by ollyg** [comment]
@cesacal I forgot to add, you should do the database schema update and after restarting daemons, a discoverall. After that it should change behaviour and be stable. Let me know.

**Comment by cesacal** [comment]
@ollyg I think we will not be able to use this new release, because we are using the docker release.
However I will speak with my colleague in charge of this deployement (i´m just a network technician who validates the data the tool netdisco is showing us).

**Comment by ollyg** [comment]
Hi @cesacal the docker containers are built and here for you:

https://github.com/netdisco/netdisco/pkgs/container/netdisco
(or on docker hub also)

**Comment by cesacal** [comment]
Thanks a lot for your support @ollyg but I have bad news from my side.
After deploying the new release, updating the database schema, restarting the daemon, and forcing a discoverall, we are still facing the same issue.

If I search a port description, without UPLINKS checked:
![Search without UPLINK checked](https://user-images.githubusercontent.com/97600299/170241469-161f65e1-23c5-4fe4-85c9-42dfdb07747b.jpg)

After that, if I check the UPLINK button:
![Search UPLINK checked](https://user-images.githubusercontent.com/97600299/170241553-40813fbf-98a2-4077-93fe-a04fe1887df9.jpg)

So, it still marks as UPLINKs the ports connecting against cisco APs and cisco IP phones.

**Comment by cesacal** [comment]
Hi @ollyg, 

I keep making some tests... give me some days to give you a proper reply.
Thanks a lot for your support.

Regards,

**Comment by cesacal** [comment]
Hi again @ollyg ,

After checking for 2 days, I can conclude that the behaviour with IP Phones is fine, but not with the APs:

![Ports for IP Phone and AP Wifi](https://user-images.githubusercontent.com/97600299/170677313-bba3ea94-fc45-41ba-99d0-f6751cf7bc69.jpg)

Search for the label of an IP Phone, working fine without checking UPLINK:

![Search for IP Phone - Working fine without checking UPLINK](https://user-images.githubusercontent.com/97600299/170676991-9dba0a9c-0981-4015-85a5-430c55046030.jpg)

Search for the label of an AP, not working without checking the UPLINK:

![Search for AP Wifi - NOT Working fine without checking UPLINK](https://user-images.githubusercontent.com/97600299/170677410-c4e8bfc7-7140-4085-b8b6-330e817a93b4.jpg)

![Search for AP Wifi - Working fine cheking UPLINK](https://user-images.githubusercontent.com/97600299/170677425-642fce91-a114-48e6-a73a-acc3f85468a2.jpg)

These are the lines we have configured on our deployment.yml:

![Config](https://user-images.githubusercontent.com/97600299/170678641-609ce321-6657-4b4e-a3fc-a629e2f86781.jpg)


Are these configs fine?
Thanks for your great support.

**Comment by ollyg** [comment]
Thanks @cesacal

On the one hand I'm glad to hear it works for phones! Okay, let's look at the WAPs too. The strange thing is that they both use almost entirely the same logic, just the different configuration parameters. So I do suspect your WAPs are somehow not matching wap_platforms or similar.

Anyway, I have released 2.052007 now which includes two things: an additional icon in the web view to show when discover_waps and discover_phones is being used, and additional debug at the command line to find out what Netdisco sees on a port.

The second is interesting, you can do something like:
`~netdisco/bin/netdisco-do discover::portproperties -d 10.216.174.165 -D`

You will see for each port the decisions Netdisco is making. Do let me know how you get on.

**Comment by cesacal** [comment]
@ollyg  thanks for your support with this bug.
We haven´t been able to test your last proposal, but we will do it ASAP and we´ll keep you informed.
