### ISSUE TITLE
EV: error in callback (ignoring): HASH(0x559ae27ab510) at /usr/lib64/perl5/vendor_perl/EV.pm line 1215.

### ISSUE THREAD

**Issue by gmourani** [netdisco/netdisco#864]
* Netdisco version used: 2.52.2
* SNMP::Info version used: 3.81
* DB Schema: 70
* PostgreSQL: 10.00.17
* Perl: 5.26.3

## Config info (deployment.yml)
schedule:
  discoverall:
    when: '5 7 * * *'
  macwalk:
    when:
      min: 20
  arpwalk:
    when:
      min: 50
  nbtwalk:
    when: '0 8,13,21 * * *'
  expire:
    when: '30 23 * * *'
  makerancidconf: null

dns:
  max_outstanding: 150

no_auth: true

path: /netdisco

Hello,

Getting the following error in netdisco-backend.log file:
EV: error in callback (ignoring): HASH(0x559ae27ab510) at /usr/lib64/perl5/vendor_perl/EV.pm line 1215.

Regards,

**Comment by ollyg** [comment]
Hi @gmourani 

This looks like our AnyEvent code is loading the EV code, which we don't ask it to do but it will do if the OS provides the module (and we can see that it does, by the vendor_perl in the message).

I wonder if you are able to run the following in your Netdisco installation (the netdisco user?) and see if the error goes away?

`~/bin/localenv cpanm --notest EV`

This will install another (newer?) copy of EV and if the error goes away then we might wish to do that ourselves, to avoid in future.

Oh, can you also let me know the operating system on the system, please?

thanks and regards
oliver.

**Comment by ollyg** [comment]
oh, you will need to restart the backend after that command

**Comment by gmourani** [comment]
[root@localhost logs]# su - netdisco
Last login: Wed Apr 13 16:39:59 EDT 2022 on pts/2
[netdisco@localhost ~]$ ~/bin/localenv cpanm --notest EV
--> Working on EV
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/EV-4.33.tar.gz ... OK
==> Found dependencies: Canary::Stability
--> Working on Canary::Stability
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/Canary-Stability-2013.tar.gz ... OK
Configuring Canary-Stability-2013 ... OK
Building Canary-Stability-2013 ... OK
Successfully installed Canary-Stability-2013
Configuring EV-4.33 ... OK
Building EV-4.33 ... OK
Successfully installed EV-4.33 (upgraded from 4.22)
2 distributions installed

Since now, no error message in netdisco-backend.log
My operating system is AlmaLinux 8.4

BTY, I can see this error in netdisco-web.log but not related : error bad config to register_admin_task

Regards,

**Comment by ollyg** [comment]
thanks for the feedback, this is fixed in 34307367

Not sure about the register_admin_task error ... assuming you're not messing about with this in your own config, I think it's probably a side effect of something else. if it continues, please open a separate ticket and we can look into it.
