### ISSUE TITLE
Upgrading 2.52.3 Device list empty

### ISSUE THREAD

**Issue by labtec6** [netdisco/netdisco#865]
Upgraded from 2.52.2 to .3 and my Inventory shows all my devices by platform but when I click on any of them, I get a blank entry.  None of the device groups I click on work. Installing from scratch does the same thing.

Ubuntu 20.04 LTS and Rocky Linux 8.5.

**Comment by jcz1** [comment]
Same on Debian 11. And same on demo server: https://netdisco2-demo.herokuapp.com/

**Comment by jouluz** [comment]
There is issue with IP inventory as well. Search does not suggest anything and if I manually add some subnet and hit enter netdisco gives following error.


Centos OS7 
App::Netdisco	2.52.3
SNMP::Info	3.82
DB Schema	70
PostgreSQL	9.2.24
Perl	5.16.3


![ip inventory](https://user-images.githubusercontent.com/32631332/164197759-28e85c74-92e9-401a-b589-08e996f53154.png)

**Comment by rc9000** [comment]
Seems to come from the moment.js upgrade:

    Uncaught TypeError: moment()._lang is undefined
        DateRangePicker https://netdisco2-demo.herokuapp.com/javascripts/daterangepicker.js:45
        daterangepicker https://netdisco2-demo.herokuapp.com/javascripts/daterangepicker.js:871

[Add a quick glance](https://momentjs.com/docs/#/i18n/changing-locale/), it looks like instead of e.g.

    daysOfWeek: moment()._lang._weekdaysMin.slice(),

we should now use 
     
    moment.locale('en').weekdaysMin.slice()

and that might be all that is needed, but some testing is required.

**Comment by luziol** [comment]
Same issue on latest Ubuntu LTS:

App::Netdisco	2.52.3
SNMP::Info	3.82
DB Schema	70
PostgreSQL	12.00.9
Perl	5.30.0

**Comment by rc9000** [comment]
Sorry for the trouble guys, I found some time to look into this and [015f910](https://github.com/netdisco/netdisco/commit/015f91077f8ce756d0db09a58df58c7dc1465d93) should fix it.

**Comment by luziol** [comment]
Hello, when will it be merged into new version?

**Comment by rc9000** [comment]
@luziol it's out already https://github.com/netdisco/netdisco/releases/tag/2.052005

**Comment by luziol** [comment]
Worked like a charm, thank you!
