### ISSUE TITLE
register_admin_task error

### ISSUE THREAD

**Issue by gmourani** [netdisco/netdisco#866]
## Expected Behavior
Not having the following message appearing all the time in netdisco-web.log.
error bad config to register_admin_task

## Current Behavior
All continu to work as expected even with the "error bad config to register_admin_task" message in netdisco-web.log.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. Define "no_auth: true" in deployment.yml
2. Define "path: /netdisco" in deployment.yml
3. Use the following Apache configuration for netdisco in proxy mode 
ProxyPreserveHost On
ProxyRequests Off
SSLProxyEngine On

<Location /netdisco>
  Options Indexes FollowSymLinks MultiViews
    <RequireAny>
     AuthName "netdisco Access"
     AuthType Basic
     AuthBasicProvider file
     AuthUserfile /etc/httpd/htnetdisco
     Require valid-user
     Require ip 127.0.0.1/32
    </RequireAny>
</Location>

  ProxyPass /netdisco http://localhost:5000/netdisco retry=0 timeout=60
  ProxyPassReverse /netdisco http://localhost:5000/netdisco

5. Give guest access in DB.
su - netdisco -c "psql -d netdisco" <<'EOF'
insert into users (username) values ('guest');
update users set port_control = true where username = 'guest';
update users set admin = true where username = 'guest';
\q
EOF

## Your Environment
Netdisco version used: 2.52.5
SNMP::Info version used: 3.81
DB Schema: 70
PostgreSQL: 10.00.17
Perl: 5.26.3

## Config info (deployment.yml)
database:
  name: 'netdisco'
  user: 'netdisco'
  pass: 'netdisco'

device_auth:
  - tag: 'default_v2_readonly'
    community: '1qaz-2wsx'
    read: true
    write: false
  - tag: 'default_v2_for_write'
    community: 'private'
    read: false
    write: true

domain_suffix: ['.domain.com']
no_auth: true
path: /netdisco

Regards,

**Comment by ollyg** [comment]
Hi @gmourani I have added some debug when this happens to hopefully show where the error is coming from (commit 96f3923a)

**Comment by ollyg** [comment]
closed pending response from user
