### ISSUE TITLE
Clicking a device on neighbours/netmap results in 'Sorry, no such device is known.' 

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#87]
Seems to be domain_suffix related - if no domain_suffix is set then everything works fine. I'd guess it's passing a suffix-stripped name somewhere that is expecting a full name?

Reported by: rkerr

Original Ticket: [netdisco/netdisco2/48](https://sourceforge.net/p/netdisco/netdisco2/48)

**Comment by romale** [comment]
Hi,
I've this issue in "App::Netdisco	2.36.8".
And, i've "domain_suffix:" configured in deployment.yml

**Comment by ollyg** [comment]
Hi romale, please open a new ticket. This ticket is four years old, so I think it's probably a different bug :-).

Here is the link: https://github.com/netdisco/netdisco/issues/new

regards
Oliver
