### ISSUE TITLE
Feature request - change to IP inventory report handling of DNS/NETBIOS

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#872]
At the moment, the IP inventory has a "DNS" column which contains either fully qualified domain name entries or, in some cases, short form NETBIOS entries.

I think it would be extremely useful if the DNS column contained only fully qualified domain names as obtained by resolving the IP address, with NETBIOS entries being in a seperate column.

NETBIOS is not DNS - in our organisation, the latter is authoratitive, whereas the former is largely arbitary. If we could see both side by side it would be extremely helpful in identifying systems which have been incorrectly named.

**Comment by ollyg** [comment]
I agree this should be done. When I have access to an environment I can dev/test in, I'll implement.

**Comment by ollyg** [comment]
thanks, implemented in ec4cf74c
