### ISSUE TITLE
Node Search - swap IP and DNS, add system name, highlight most recent, in the Switch Port rows

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#875]
At the moment, searching for a MAC address will usally return three results in the 'Node' report:
* MAC -> IP
* Switch Port
* NetBIOS

The entry for 'switch port' will be in the form

<link>$device_IP_address - $device_switchport</link> on vlan x

e.g. 

_192.168.55.6 - GigabitEthernet1/0/1_ on vlan 10

The problem for us is that most of our devices have more than a few IP addresses, and it seems fairly arbitary which one will get listed in this result. 

This means that from looking at the search result, it is not clear which device is being referred to - you need to click the link to get the device info to find this out.

I think it would be a significant improvement if instead of the device IP address, the device system name was displayed instead, as (so far) we've only managed to set one of these per device...

I think there would be an extra benefit in making this change, because it would mean that the only IP address shown in the results was that of the MAC->IP pairing. At the moment it is very easy to accidentally lift the IP address of the device rather than the IP address of the node if you're copying and pasting.

**Comment by ollyg** [comment]
Thanks @kingtrw 

In fact the app does try to display DNS names alongside, if it seems to be in the database:
https://github.com/netdisco/netdisco/blob/master/share/views/ajax/search/node_by_mac.tt#L51

But it could be that the check is a bit too strict. I'll leave this ticket open so it can be looked at.

**Comment by kingtrw** [comment]
Just as a minor update - I think the real benefit for us would be if we could actually remove the device IP entirely from the search result, as it's causing lots of confusion. The result is presented as

<hyperlink> $device_ip - $switchport </hyperlink> ($device_name - $port_description) on $vlan_id

the presence of the device IP is causing me much confusion at first glance, because it's often not meaningful - our devices have so many IPs.

what would be most preferable from my perspective would be if the result was in the form

<hyperlink> $device_name - $switchport </hyperlink> ($port_description) on vlan $vlan_id

**Comment by ollyg** [comment]
implemented
