### ISSUE TITLE
very very minor feature request - searching for DNS entries

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#876]
I have some devices that are in a vmware vcloud to which I do not have management access.

So that I can use netdisco's IP inventory tools, I have created a linux VM, configured as an SNMP layer 3 device. This machine runs a ping sweep of the network range regularly, and I have discovered it with netdisco so the arp information is being collected.

This works well, and I can see MAC->IP pairings listed under the MAC address of the virtual firewall as I expect to, e.g.

MAC: <$firewall MAC>
MAC-> IP        <$public IP> ($public.dns.entry)
MAC-> IP         <$another public IP> ($another.public.dns.entry) 
etc

I can search these entries by IP address, but I cannot search by dns entry - no results are returned.

Given that ND has recorded the DNS entry, is it possible that the search could be extended to cover it?

**Comment by ollyg** [comment]
Hi!

This may not actually be failing, it's just Netdisco assumes any plain text in this search should have the "domain_suffix" added, and I guess you have something other than '.public.dns.entry' configured there.

One option is to use "partial" tickbox in the search options. Let me know if that works.

Other option (better) is to use multiple domain_suffix, which is supported: https://github.com/netdisco/netdisco/wiki/Configuration#domain_suffix

You can have a list of domain_suffix or a regexp as in the doc example. Also let me know how that goes.

regards,
oliver.

**Comment by ollyg** [comment]
Oh, I think adding "*" at end of the search text will work too

**Comment by ollyg** [comment]
Hi! This may not actually be failing, it's just Netdisco assumes any plain
text in this search should have the "domain_suffix" added, and I guess you
have something other than '.public.dns.entry' configured there.

One option is to use "partial" tickbox in the search options. Let me know
if that works.

Other option (better) is to use multiple domain_suffix, which is supported:
https://github.com/netdisco/netdisco/wiki/Configuration#domain_suffix

You can have a list of domain_suffix or a regexp as in the doc example.
Also let me know how that goes.

Thanks,
oliver.
