### ISSUE TITLE
CSV export on device / ports view is missing mac adresses

### ISSUE THREAD

**Issue by thowo** [netdisco/netdisco#878]
Hello,

we noticed that we are missing mac adresses in the csv export on the device?tab=ports view. This issue occurs if the mac adress listed on the switchport does not resolve to an ip adress (i.e. device which hold the arp cache can not be fully discovered).  The mac adress is listed in the view, but the resulting csv export shows no node-mac entry. what do we miss here? 

## Expected Behavior
- MAC Adress of connected noded should be listed in the csv export with or without IP adress

## Current Behavior
- CSV Export does only contain node-mac adresses if the mac address resolves to an IP

## Possible Solution
- maybe the join in the csv export query is to tight...?

## Steps to Reproduce (for bugs)
- call csv export on device/node view and see if mac adresses are included in the export 

## Environment
Software	Version
[App::Netdisco](http://netdisco.org/)	2.47.5
[SNMP::Info](https://github.com/netdisco/snmp-info)	3.71
[DB Schema](https://metacpan.org/module/netdisco-db-deploy)	64
[PostgreSQL](http://www.postgresql.org/)	11.00.16
[Perl](http://www.perl.org/)	5.28.1

**Comment by ollyg** [comment]
fixed in 4cdf7823
thanks for the bug report!
