### ISSUE TITLE
feature request: automation of "pseudo device"

### ISSUE THREAD

**Issue by felixitc** [netdisco/netdisco#881]
## Expected Behavior
i can create or edit an "pseudo device" via some automatic process: api / commandline / config file

## Current Behavior
an pseudo device can be created only via webgui 

## Possible Solution
- add an function to netdisco-do
- allow to define pseudo devices in the config file

## Context
as my firewalls cant be used for layer 3 i use https://github.com/netdisco/netdisco/wiki/Node-names---NetBIOS for this.
the local monitoring nodes i use for this are created via automations. i can get their config (ip) via an api and would like to add them to netdisco. while i can configure the deploymant.yml for auth i would have to manually create the "pseudo device".

**Comment by felixitc** [comment]
Added to Wishlist in Wiki

**Comment by ollyg** [comment]
implemented in 07e8520b

**Comment by ollyg** [comment]
docs in 872a45bd

**Comment by ollyg** [comment]
Hi @felixitc new version is released - please test and let me know!
