### ISSUE TITLE
Feature request - NAC info

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#887]
I don't know how feasible this is because I don't know what info is exposed over SNMP, but we're in the process of enabling NAC across our estate.
It would be really handy if ND had some option for showing if NAC-related features (e.g. 8021x) were enabled on ports.

Edit: we've got Cisco ios 15, Cisco ios-xe 16, and Dell NOS 6.7 at the edge.

**Comment by ollyg** [comment]
hmm wonder if we need to add 1.0.8802.1.1 and 1.3.111.2.802 to the SNMP browser (which is only 1.3.6.1 today)

**Comment by ollyg** [comment]
Hi, please would you upgrade to latest Netdisco and take a snapshot of a device with NAC enabled and a logged in user. Could do Cisco and non Cisco both.

**Comment by rc9000** [comment]
I've merged rudimentary IEEE8021-PAE-MIB support in snmp-info: https://github.com/netdisco/snmp-info/pull/466

**Comment by rc9000** [comment]
@kingtrw This is already implemented since a while now, you can find the attributes in the Port properties. 

I'm closing this, but let us know if you have any issues or input -  I don't think there are many users so far except for me.
