### ISSUE TITLE
Feature req: renumber in web interface

### ISSUE THREAD

**Issue by ob1kenob** [netdisco/netdisco#889]
## Expected Behavior

Would be fantastic if users with admin role had an option to renumber a device from the web interface.

## Current Behavior

No option to renumber a device is present in the web interface, have to run netdisco-do with renumber option.

## Possible Solution

Possibly add a button next to "Delete" on the device details page that would prompt for new IP.  Ideally would be present only for users with Admin role.

## Steps to Reproduce (for bugs)

N/A

## Context

Have done this recently with equipment changes and it is less than optimal to setup everybody with a login so they can run the "netdisco-do" command.

## Your Environment

* Netdisco version used: 2.52.0
* SNMP::Info version used: 3.81

## Config info (deployment.yml)

N/A (that I'm aware of) - feature request for specific web interface change

## Device information

Not specific to any device, web interface feature request

**Comment by ollyg** [comment]
implemented in e290d352
