### ISSUE TITLE
Feature request - manual warranty info

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#891]
It would be awesome if every device had an option to enter a date for 'warranty expiry'
Then we could have a high-level report on warranty status

it would be very useful for us to provide management with a warranty report saying "this is the state of our network support" - at the moment we have to collate this via a very very manual process.

**Comment by ollyg** [comment]
Hi @kingtrw at the moment we don't really have "custom fields". However, many sites use the SNMP writeable fields location or contact for additional asset info.

**Comment by ollyg** [comment]
think this is a #wontfix sorry - please [ab]use the location or contact field
