### ISSUE TITLE
Feature request - STP info

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#892]
This is very very speculative - I know that A) it may not even be possible and B) even if it was, it would be a huge amount of work - but just to think about...

I've been having horrible problems diagnosing STP issues. Specifically:

* protocols are all over the place
* root bridges for vlans are all over the place
* the mac addresses of the root bridges are not always known to netdisco (sometimes they match all except the last two digits, so I'm assuming some switches have multiuple macs)
* I have no way of getting notified about STP topology changes

at the moment I run  show spanning-tree and then manually reconcile with some text replacement, but what would be amazing is if:

- we could get a list of what protocols are in use for devices/vlans
- what root bridges are known (with resolving mac addresses to their actual devices)
- visiblity of all mac addresses used by a device
- stp change monitoring?

just suggestions only, I know it's probably not viable

**Comment by ollyg** [comment]
Hi, please would you upgrade to latest Netdisco and take a snapshot of a device running STP.

**Comment by ollyg** [comment]
closed and moved to wishlist
