### ISSUE TITLE
Front Panel View

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#9]
Peter Ehlin developed some patches to display images of the front panel in the device view.

Hi

I have written a module that displays the switch graphically.

Right now it supports the following Cisco switches:
29408TF
29408TT
Cat295024G
Cat2950t24
Cat356024PS
Cat356048PS
Cat3560G48PS
Cat3750Ge12Sfp
Cat295012
Cat295024
Cat375024TS

There is a screenshot at: http://www.sics.se/~pelin/screenshot.PNG
Somehow I could not capture the mousepointer but it is hoovering over port
17

What is does:
It adds a graphical view of your switch to the device\_view page. The image is clickable
and onmouseover events displays popups via the excellent library overlib.

This module is by no means finished and I personally doubt that it will be.
I have not done anything with it for over a month. If you have any of these switches,
it might work for you. If you don't have any of these switches. You can add them
quite easily to the code, provided that you have the images.

You can download the patch from http://www.sics.se/~pelin/frontpanel.patch

You also need the overlib library downloaded from
http://www.bosrup.com/web/overlib/

TODO:
\* support more than just up/down as port status. disabled, stp block,
monitor, administrative down
\* support more switches
\* a better database format... \(I am just a beginner perl programmer\)
\* more information for the popup. connected hosts/switches, STP, bandwidth,
interface IP
\* support status leds
\* support modular switches

Good luck
Peter

Reported by: fenner

Original Ticket: [netdisco/nd2-features/9](https://sourceforge.net/p/netdisco/nd2-features/9)

**Comment by ollyg** [comment]
Moved to wishlist page in wiki

**Comment by inphobia** [comment]
none of the links in this issue seem to be working. checked archive.org but the pages are not archived (at least not the screenshot & diff), also checked sourceforge but that does not seem to include the patch, only links.
