### ISSUE TITLE
node_ip time_last can be significantly before time_first

### ISSUE THREAD

**Issue by rc9000** [netdisco/netdisco#901]
We've noticed that the time_first of arp entries can be significantly behind time_last:

    select *, time_first - time_last as diff from node_ip where time_first > time_last and time_first > '2022-07-27' order by time_last desc limit 5;
    
    
    |mac              |ip           |active|time_first             |time_last              |dns   |diff           |
    |-----------------|-------------|------|-----------------------|-----------------------|------|---------------|
    |2e:91:31:xx:xx:xx|10.192.xxx.xx|true  |2022-07-27 19:45:37.324|2022-07-27 19:45:37.205|[NULL]|00:00:00.118477|
    |b4:69:21:xx:xx:xx|10.237.xxx.xx|true  |2022-07-27 19:45:38.202|2022-07-27 19:45:37.205|[NULL]|00:00:00.996282|
    |4c:1d:96:xx:xx:xx|10.194.xxx.xx|true  |2022-07-27 19:45:38.994|2022-07-27 19:45:35.829|[NULL]|00:00:03.165168|
    |7e:44:5f:xx:xx:xx|10.190.xxx.xx|true  |2022-07-27 19:45:13.575|2022-07-27 19:45:13.246|[NULL]|00:00:00.329701|
    |f2:4d:8b:xx:xx:xx|10.190.xxx.xx|true  |2022-07-27 19:45:13.342|2022-07-27 19:45:13.246|[NULL]|00:00:00.096307|

This only happens on new entries in node_ip, sice time_first is the database current_timestamp but the time_last is precalculated in `Worker/Plugin/Arpnip/Nodes.pm->register_worker` as ` my $now = 'to_timestamp('. (join '.', gettimeofday) .')'`.

This gets worse the busier the database, under heavy load I can see differences of up to twenty seconds.

The code does not make very strong arguments for this behavior:

    # would be possible just to use now() on updated records, but by using this
    # same value for them all, we _can_ if we want add a job at the end to
    # select and do something with the updated set (no reason to yet, though)
    my $now = 'to_timestamp('. (join '.', gettimeofday) .')';

and in fact just not passing a `$now` seems to fix the issue - at the cost of having a different time_last for every row in the arpnip, and having last_arpnip be a different timestamp as well.

Is it ok if we remove this from the store_arp calls?

**Comment by ollyg** [comment]
Hi @rc9000 I'm OK with this, but what about going the other way and setting time_first for new entries to also be `$now` ?

For some reason I like the aesthetics of having the stamp the same for all entries stored in the same arpnip run. I don't know why 🤷🏻‍♀️

**Comment by rc9000** [comment]
Yes a matching time_first = time_last = last_arpnip would be nice for an entry that's seen for the first time. I'll try to come up with a PR.

**Comment by ollyg** [comment]
fixed in 4bb9b25a and verified that the SQL executed is the same

(works because DBIx::Class was already SELECT then UPDATE/INSERT so was possible to refactor and check if row is new and if so to set time_first before INSERT)
