### ISSUE TITLE
Minor: port duplex display improvements

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#902]
* When a port is free/down/disabled, I think it would be helpful if the duplex entry was "N/A" or similar rather than blank
* I think it would be preferable if the duplex column was listed directly after speed

And now the complicated one:
* For my Dell N2200 series switches (OS 6.7) there is no entry in the duplex field. (Ciscos display auto/full)
Looking at the switch, it appears that there is no supported operational link mode for half-duplex 1G:
the supported modes are: 2500f, 1000f, 100f, 100h, 10f, 10h

As far as I can tell, IEE 802.3 left in half-duplex gigabit to support gigabit hubs, but these are either non-existant or legendary in rareness (thank goodness)

I don't know if there's a way of querying supported modes via SNMP ( or if these switches would expose it anyway ) but maybe if would be useful if there was an "Assumed full" entry for 1/2.5/10G ports to avoid gaps in the details?

**Comment by ollyg** [comment]
Hi @kingtrw I agree with the column ordering and have changed it in a patch. BTW it is actually possible to change the column ordering and defaults even, via config, but it's undocumented ;-). I don't agree to replace blank with "n/a" as this is the standard behaviour all over Netdisco, and also "n/a" feels like it doesn't translate internationally very well.

For the 1000h what I understand from what you say is that you have a device with a port genuinely running in 1000h but Netdisco isn't displaying that (is it displaying the speed?). Please open a separate ticket. We need to do some troubleshooting commands on that to see what the device returns.
