### ISSUE TITLE
FR - Make port searching fuzzier

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#903]
At the moment when searching in the port view for a particular port, you need to match the name exactly.

E.g. if my switch has ports enumerated as "GigabitEthernetX/Y/Z" I have to search explictitly for "GigabitEthernetX/Y/Z" -- a search for "GiX/Y/Z" or "X/Y/Z" won't match.

I think it would be helpful if these did match, because we have a total hodgepodge of different switches and so there's no consistency, and I think in the majority of cases when you're searching for a port, X/Y/Z is a useful starting point.

I know that this means a search for 1/0/1 could for instance return
Gi1/0/1
Te1/0/1
Tw1/0/1
Fo1/0/1
and I think that's actually expected and useful behaviour.

**Comment by ollyg** [comment]
Hi @kingtrw the "Partial Match" tickbox does almost exactly this. Put "X/Y/Z" into the search and try.

Now, it does not do "Gi" to "GigabitEthernet" expansion automatically, but you can use "%" as the SQL wildcard.

So "Gi%1/0/1" will work, as will "Gi%1/0/1%".

Hope that helps,
