### ISSUE TITLE
make a way to examine snapshot via web

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#911]
currently taking the snapshot can be done via web but not importing it for examine
maybe also trigger loadmibs?

**Comment by rc9000** [comment]
+1, I think it took me a trip to the Wiki twice already to figure out that I have do it with netdisco-do to be able to look at it.

**Comment by ollyg** [comment]
implemented in latest release - snapshots created via web also load the browsing data (minor bug that user is not alerted to missing loadmibs step, will fix that)
