### ISSUE TITLE
FR - exclude an interface from connected nodes and devices

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#914]
We have multiple sites connected by a campus ISP, and they provide a pseudowire connection. This unfortunately means that any information on connected devices or neighbours on these ports is completely wrong.

Neighbour discovery is easy to fix by turning off cdp/lldp on the interface, but ND is picking up MAC addresses of other switches in other buildings.

It would be really handy if there was a way of putting in an exclusion in the config file to never retrain connected devices info for specified ports.

**Comment by ollyg** [comment]
Hi @kingtrw I've implemented macsuck_no_deviceport which allows suppression of macsuck gathering MACs on a port on a device. I have not implemented anything for connected devices, as I don't think it's as useful and you can use discover_no.
