### ISSUE TITLE
Feature suggestion - expand all vlans default config option

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#915]
At the moment in the ports view, interfaces with a significant number of vlans have the vlan ids collapsed behind a "show vlans" dropdown.

It would be very useful if there was a config option to make remove the collapse entirely and just have all vlans displayed always regardless of how many there are.

Line items in the ports view can get pretty big anyway due to large nubmers of connected nodes, and it would be useful to have the vlan numbers shown by default so that if you're trying to trace where they're presented, they'll show up in the browser text search.

Thanks!

**Comment by kingtrw** [comment]
actually I've realised I can just filter the search results by vlan. I still think it'd be useful to be able to turn off collapsing lists by default but its as minor as you can get.

**Comment by ollyg** [comment]
the feature is noted already, there's a comment in the code that we thought this might be needed some day :-)
https://github.com/netdisco/netdisco/blob/master/share/views/ajax/device/ports.tt#L226

But for now, given other work, we can keep this low priority if you have the VLAN search workaround for what you need.
