### ISSUE TITLE
discover_no regex not matching some devices

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#916]
In my deployment config I have

discover_no:
  - ip:10\.202\.\d+\.\d+

to exclude all 10.202.x ranges, which is where our meraki access points live.

However, I'm still seeing two of them show up in the undiscovered neighbour report:

10.202.16.94
Port 0

10.202.16.68
Port 0	

This has persisted across multiple discover all jobs and multiple version upgrades (currently 2.53.7)

Not major, just... odd.

**Comment by ollyg** [comment]
first thing, the "dot" is a special character in regexp so needs escaping:

`ip: "10\.202\.\d+\.\d+"`

second thing, can you check output of:

`~/bin/netdisco-do dumpconfig -e discover_no`

to be sure that the YAML is being parsed correctly

**Comment by kingtrw** [comment]
Ach, I screwed up the formatting because I always do

Config is

```
discover_no:
  # Estates switch
  - 10.101.123.253
  # Meraki MR33 APs
  - ip:10\.202\.\d+\.\d+
  # Cisco Prime
  - 10.202.19.229
  # AXIS PTZ Network Camera
  - 10.200.18.81
  - 10.200.18.82
  - 10.200.18.84
  - 10.200.18.85
```

and output is

```
[241107] 2022-08-09 17:29:08  info App::Netdisco version 2.053007 loaded.
[241107] 2022-08-09 17:29:08  info dumpconfig:  started at Tue Aug  9 17:29:08 2022
[
    [0] "10.101.123.253" (dualvar: 10.101),
    [1] "ip:10\.202\.\d+\.\d+",
    [2] "10.202.19.229" (dualvar: 10.202),
    [3] "10.200.18.81" (dualvar: 10.2),
    [4] "10.200.18.82" (dualvar: 10.2),
    [5] "10.200.18.84" (dualvar: 10.2),
    [6] "10.200.18.85" (dualvar: 10.2)
]

```

**Comment by ollyg** [comment]
Hi @kingtrw I cannot reproduce this, sorry.

When I add the config, and then run discover on a neighbour of the denied device, the logs show:
`[37052] 2022-08-16 05:05:30 debug is_discoverable: 172.16.224.10 matched discover_no`

And in the device ports view for the neighbor the denied device has the Neighbor Forbidden icon. The denied device does not show up in my Undiscovered Neighbors report.

Please could you do this test with a command line discover of the neighbour device to see what the log shows?

**Comment by inphobia** [comment]
while i haven't looked at your actual issue, if you want to exclude `10.202.x` you could also use 

```
discover_no:
  # Estates switch
  - 10.101.123.253
  # Meraki MR33 APs
  - 10.202.0.0/16
```

i also tend to use https://github.com/netdisco/netdisco/wiki/Configuration#devices_no instead of discover_no. macsuck & arpnip won't work on non discovered devices, and i have no interest in netbios info.
