### ISSUE TITLE
FR Report - orphan VLANs and unused VLANs

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#920]
I hope this is a relatively sane suggestion - I'm finding in my environment we have the following two situations occur often:

* A switch has multiple vlans assigned on its trunk port, but none of them are assigned to edge ports
* A switch has mutiple vlans assigned on its trunk port that are only on edge ports which havne't been used for yonks

I think it would be really useful if there was a report that could pick these up. As far as I can see it shouldn't be too difficult to do the logic:

Orphan VLAN - exists on trunk port only, not assigned to any edge ports
Stale VLAN - exists on trunk ports and edge ports, but edge ports haven't been seen active (for whatever the default period ND uses is)

**Comment by ollyg** [comment]
orphan vlans report implemented in ef2ab9b6

**Comment by ollyg** [comment]
unused VLANs implemented in da4657cf
