### ISSUE TITLE
FR Report - duplicate device IPs

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#921]
I've just found the same IP address assigned to multiple devices. 

I only found it by reviewing the "addresses without DNS entries report" - but if DNS addresses had been added (and I easily could have added an entry without thinking too hard) I'd never have spotted it.

Would it be possible to have a Device > "Address Summary" report with the same fields as the Address without DNS entries (Device/IP/Contact/Location) but that lists all addresses known for each device?

This would actually be an extremely useful tool for helping get devices with too many SVIs under control.

Thanks!

**Comment by ollyg** [comment]
Of course you have the Addresses tab on every device to show the interface addresses it has, so you can see the list there.

I think the idea of a duplicate device IPs report would be good.

**Comment by ollyg** [comment]
implemented in 02537fbf
Many thanks @kingtrw !
