### ISSUE TITLE
minor - not picking up changed DNS entries for device interfaces

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#922]
I'm trying to improve our DNS situation at the moment - and while using the 'discover' button will cause ND to instantly detect DNS entries that have been added for addresses that previously didn't have one, I'm finding that ND isn't detecting when existing DNS entries have been changed.

It looks like the discovery process is not re-checking DNS if an entry already exists - could it be tweaked so that it alwasy rechecks DNS?

Thanks!

**Comment by ollyg** [comment]
Hi @kingtrw I strongly suspect this is DNS caching if your records and if you try again after, say, four hours, it'll be fixed.

Netdisco doesn't use the stub resolver on the server, but does read /etc/resolv.conf to find servers and they're very likely to cache for TTL of the records, which might be four hours. You can check e.g. on Windows with `nslookup -debug google.co.uk` and look for the ttl lines (like coundown timers).
