### ISSUE TITLE
Broken "installation instructions" link in README.md

### ISSUE THREAD

**Issue by FabioPedretti** [netdisco/netdisco#923]
[README.md](https://github.com/netdisco/netdisco#readme) says:

> Please check out the [installation instructions](https://metacpan.org/pod/App::Netdisco) on CPAN.

The [installation instructions](https://metacpan.org/pod/App::Netdisco) link however gives a "Not Found" error page.

**Comment by ollyg** [comment]
Hi @FabioPedretti and thank you!

This looks like it was a temporary problem with metacpan.org as the link is working for me now.

To be sure, the link is this one: https://metacpan.org/pod/App::Netdisco

Many thanks

**Comment by FabioPedretti** [comment]
Confirmed working for me also now... thanks.
