### ISSUE TITLE
Interface ignore - Juniper update and new ignore_device_interfaces setting

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#925]
Juniper QFX10k has:
- lots of `.0` subinterfaces such as `ae1.0`
- `.16386` and `.32767` can be ignored per [this support doc](https://supportportal.juniper.net/s/article/MX-Purpose-of-automatically-created-interface-units-16386-and-32767?language=en_US)
- `bme0` (ethernetCsmacd), interestingly `bme0.0` (propVirtual) has prefix `128.0.0.0/2` running, with `.1`, `.4`, `.63`
- `cpb0` (other)
- `dsc` (other)
- `esi` (other)
- `fti0` (other)
- `gr-0/0/0` (tunnel)
- `gre` (tunnel)
- `ipip` (tunnel)
- `irb` (other) and `irb.<number>` (propVirtual) for every other subinterface, have `10.120.x.y/24` addresses and some of our public assigned IP space
- `jsrv` (other) and `jsrv.1` (propVirtual, `128.0.0.127`)
- `lo0.<number>` (softwareLoopback) up to 31 (but some are legitimately in use so need to differentiate?), have `10.127.0.x/32`
- `lsi` (mplsTunnel) and `lsi.<number>` (propVirtual) up to 29
- `mif` (other)
- `mtun` (tunnel)
- `pfh-0/0/0` (other)
- `pimd` (tunnel)
- `pime` (tunnel)
- `pip0` (other)
- `tap` (other)
- `vtep` (other) and `vtep.<number>` (propVirtual) for 32768 to 32795

**Comment by ollyg** [comment]
We have i_ignore() in SNMP::Info for enforcing ignored interfaces (eg CPU interface). We have interfaces_ignore setting in Netdisco which is global and includes similar. I wonder if we would benefit from a smarter version of this which can have interfaces to ignore per device match, using the full ACL syntax so can match vendor, model, etc at different granularity.

**Comment by ollyg** [comment]
Another feature could be a sidebar tickbox to hide "less interesting" interfaces. We have equivalent for hiding VLAN 1002-1005  so that Cisco users can remove it from web display but they are still in database.

**Comment by JeroenvIS** [comment]
Many of these can be useful for users to see, depending on their config (ie what features are actually in use). In our network, I would probably only want to hide the .16386 and .32767 interfaces.

**Comment by ollyg** [comment]
OK @JeroenvIS thanks! that's hopefully enough guidance for now

**Comment by ollyg** [comment]
implemented ignore_deviceports and hide_deviceports in 790c51b2

**Comment by inphobia** [comment]
for future reference:
i do feel that netdisco is where the call should be made what to accept & what to ignore.

this also opens up a clear path to get rid of netdisco/snmp-info#376
if_ignore() vs i_ignore() and if this is snmp::info's job or netdisco's

also updated the wiki for 2.056000 and made the change to ignore_interfaces incompatible - since for me it was :) 
(as in i had to update my config to make it act the same as older version)
https://github.com/netdisco/netdisco/wiki/Release-Notes/a299e1c608df091c22aaefcfb185ab58c657b8fd
