### ISSUE TITLE
Make it clear Netdisco runs in UTC

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#926]
What do web developers love the most? Timezone issues!

The web UI isn't using daylight adjusted timezones -- e.g. last discover/last arpnip/last macsuck info in device details is using UTC and not BST.

It might be enough to just specifyu the timezone - e..g. have it say UTC <timestamp>

**Comment by ollyg** [comment]
Hi @kingtrw fair point, it is not clear to the user what Netdisco is doing.

The system runs in UTC completely, and there is no facility to change this or present times in other zones in the web. One reason is that some installations have collectors/pollers in different time zones or web browsers in different time zones and it gets messy quickly.

**Comment by kingtrw** [comment]
I thought that might be the case! In that case would it be an option to have the UI display

"UTC <timestamp>" rather than "<timestamp">?

**Comment by ollyg** [comment]
I’ll have to close this. We only recommend the use of UTC but can’t tell what zone is actually configured in the system.
