### ISSUE TITLE
Wrong columns/label assignment on device ports View

### ISSUE THREAD

**Issue by sibelle-labs** [netdisco/netdisco#930]
Name with content for Duplex
Speed (Configured) with content for Name

![grafik](https://user-images.githubusercontent.com/65012538/190849192-9703e045-93f7-4f89-a7e8-16b0000b97aa.png)

**Comment by inphobia** [comment]
i'm seeing this too, #931 should make them match again

and while looking at this found a few other things that might need fixing...

**Comment by ollyg** [comment]
Hi @sibelle-labs I think we have fixed this now in the latest release. Sorry for the bug and thank you for the report.

**Comment by mikebutash** [comment]
Hi @ollyg, I tested this with an update as I was seeing this too, but noticed one of the jobs I have that downloads the csv files from the UI using the same ajax url for the download link, and look like the resulting output still has the column mismatches.  I'm presuming what you fixed probably needs added for using the ajax functions to output the csv too.  Thanks in advance!

**Comment by inphobia** [comment]
> the csv files from the UI

i'm aware of this, see #932 

but i'm stuck until we figure out #933 - i'll see if we can get a consensus about that soon.
