### ISSUE TITLE
Add clearbutton to searchbar

### ISSUE THREAD

**Issue by pioevogel** [netdisco/netdisco#943]
## Expected Behavior
A delete button (x) in the searchbar to clear previous searchterm

## Current Behavior
There is no deletebutton. A searchterm must be deleted by selecting the text and press delete. On linux systems this clears the copy buffer that can be pasted with middle mouse button.

## Possible Solution
Add simple [x] on the right in the searchfield that clears the box.

## Steps to Reproduce (for bugs)
1. Look at searchbar
2. Notice there is no deletebutton

## Context
I need to paste IP addresses/hostnames in this field that I selected in my terminal window. I work around it by copying it to the clipboard, but these are extra keystrokes. Another way is click right of the text and delete it with backspace.

## Your Environment
Netdisco 2.59.1
SNMP::Info 3.89
DB schema 76
PostgreSQL 9.14
Perl 5.34.0

**Comment by ollyg** [comment]
I wonder if we change the input type to "search" it will cause the browser to add the clearbutton automatically.

**Comment by ollyg** [comment]
here: https://github.com/netdisco/netdisco/blob/master/share/views/layouts/main.tt#L154

**Comment by ollyg** [comment]
Hi @pioevogel I have committed a small patch which changes the HTML5 type of the field from "text" to "search".

In some browsers this will add the little '[x]' to clear. In my macOS Chrome browser it does not but it does add the feature that hitting Escape key clears the box. So just by giving focus to the box and hitting Escape it is cleared.

Will this satisfy your request?

**Comment by pioevogel** [comment]
Hi Oliver,

I just made the change but noticed no difference in either firefox or chrome (on linux). Are these kind of changes also  received through ~/bin/localenv cpanm --notest App::Netdisco ? Or do I need to pull these from git?
Anyway, I made them by hand just to make sure.

**Comment by ollyg** [comment]
Hi @pioevogel at the moment the change is in git and not released to CPAN (so cpanm will not update).

Can you use the git version or patch manually to see if it works? Hitting Escape key should clear the box.

**Comment by rc9000** [comment]
Works for me in the git version with MacOS Chrome + Safari. In Firefox it does not seem to do anything. Well, two out of three, seems like a good effort/result ratio :)

**Comment by ollyg** [comment]
via this SO question: https://stackoverflow.com/questions/28114154/no-clear-button-in-firefox-for-input-type-search
I found this Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=558594
and this Mozilla doc: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#html

which suggests it is implemented in Firefox but disabled by default. I agree we have limits on our time and what is implemented is enough, so I'll close. Thanks all!
