### ISSUE TITLE
vlan query problem

### ISSUE THREAD

**Issue by ajw1980** [netdisco/netdisco#944]
I've got a custom script to query netdisco. I upgraded today and started getting this error:
```
DBIx::Class::ResultSet::related_resultset(): search_related: result source 'DevicePortVlan' has no such relationship vlan
```

I think it is a problem with the change from vlan to vlan_entry and fixed similar to commit f4fd9af70858e913ff5a5ceda0e26b16f04dc029. DevicePort.pm should use vlan_entry instead of vlan:

```
__PACKAGE__->many_to_many( vlans => 'port_vlans', 'vlan' );

__PACKAGE__->many_to_many( vlans => 'port_vlans', 'vlan_entry' );
```

**Comment by ollyg** [comment]
Hi @ajw1980 this is fixed and will be in the next release (out today)
