### ISSUE TITLE
bug: computing of port free

### ISSUE THREAD

**Issue by j2s2** [netdisco/netdisco#946]
Hello,

there are something strange in port free results. I found that a port was free for 5 month but not free for 3 month !!!

The request is (appears in different files but with the same meaning) :
```
"me.up_admin = 'up' AND me.up != 'up' AND "
."(me.type IS NULL OR me.type !~* '^(53|ieee8023adLag|propVirtual|l2vlan|l3ipvlan|135|136|137)\$') AND "
."((age(now(), to_timestamp(extract(epoch from device.last_discover) - (device.uptime/100))) < ?::interval "
."AND (last_node.time_last IS NULL OR age(now(), last_node.time_last) > ?::interval)) "
."OR age(now(), to_timestamp(extract(epoch from device.last_discover) - (device.uptime - me.lastchange)/100)) > ?::interval)"
```
The problem comes from this part : 
         ` ((age(now(), to_timestamp(extract(epoch from device.last_discover) - (device.uptime/100))) < ?::interval "`

What I understand is that the device must have started in the interval. So the greater the interval is, the more chance this condition is true and so the more chance the port is free, which seem illogical. I think that operator "<" should be ">".

Sincerly,

**Comment by ollyg** [comment]
Hi @j2s2 
Thanks for opening the issue. At the moment I think the SQL is correct, and I can explain below. But if you think there's a bug we can definitely look into it.

The pseudocode is as follows:

- the port is enabled and down
- AND is (probably) not a virtual/software interface
- AND (( the device has (re-)started within the is_free window
  - AND most recent node was before is_free window )
- OR (the port went down within is_free window) )

So the idea is that ideally we have the port simply go down within the is_free window, but if the device rebooted then instead we check the last time a node (workstation) was seen on the port.

I hope this makes sense. If you have a bug or strange effect, please do open another ticket!
