### ISSUE TITLE
Search failed! Please contact your site administrator (network error: TypeError: Failed to fetch). version 2.60.2

### ISSUE THREAD

**Issue by luduarte77** [netdisco/netdisco#950]
Hi, since a few days we got this error while trying to search or view queue :
[4774] 2022-12-14 08:08:35 error request to GET /ajax/content/admin/jobqueue crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERREUR:  la colonne target.custom_fields n'existe pas
LIGNE 1 : ..._arpnip, target.is_pseudo, target.pae_is_enabled, target.cus...
                                                               ^ [for Statement "SELECT me.job, me.entered, me.started, me.finished, me.device, me.port, me.action, me.subaction, me.status, me.username, me.userip, me.log, me.debug, me.device_key, to_char(entered, 'YYYY-MM-DD HH24:MI'), to_char(finished, 'YYYY-MM-DD HH24:MI'), to_char(started, 'YYYY-MM-DD HH24:MI'), target.ip, target.creation, target.dns, target.description, target.uptime, target.contact, target.name, target.location, target.layers, target.num_ports, target.mac, target.serial, target.chassis_id, target.model, target.ps1_type, target.ps2_type, target.ps1_status, target.ps2_status, target.fan, target.slots, target.vendor, target.os, target.os_ver, target.log, target.snmp_ver, target.snmp_comm, target.snmp_class, target.snmp_engineid, target.vtp_domain, target.last_discover, target.last_macsuck, target.last_arpnip, target.is_pseudo, target.pae_is_enabled, target.custom_fields FROM admin me LEFT JOIN device target ON target.ip = me.device WHERE ( ( ( me.log IS NULL OR me.log NOT LIKE ? ) AND me.action NOT LIKE ? ) ) ORDER BY entered DESC, device DESC, action DESC LIMIT ?" with ParamValues: 1='duplicate of %', 2='hook::%', 3='50'] at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 303

Thanks,

**Comment by rc9000** [comment]
This is due to [schema version 77](https://github.com/netdisco/netdisco/blob/master/share/schema_versions/App-Netdisco-DB-76-77-PostgreSQL.sql) not being installed. If you didn't yet, please execute `netdisco-deploy` to upgrade.

If you did, your Postgres version might be too old. On the first page of the UI, there is "System Information" box you can expand. If it's e.g. `PostgreSQL: 9.4` and written in red, you'll need to upgrade first.

**Comment by luduarte77** [comment]
Hi ollyg,
Thanks a lot ! After upgrading to version 13 of postrges, everything is now working you your command 
`~/bin/netdisco-db-deploy --redeploy-all`
