### ISSUE TITLE
Unable to access web interface

### ISSUE THREAD

**Issue by jonny190** [netdisco/netdisco#951]
## Expected Behavior
Id expect to be able to connect on http port 5000 as i have with previous deployments

## Current Behavior
Port 5000 is showing connection refused 

## Possible Solution
Not 100% but looks to be trying ipv6 over ipv4

## Steps to Reproduce (for bugs)
Downloaded the compose file
Setup the folders
Ran docker compose 
Tried adding: 
```
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
```
to the compose file for each service but nothing same results

## Context
Unable to access the server

## Your Environment
Running in PhotonOS (VMware's container os)
* Netdisco version used: Lastest from docker 

```
d6e97147bc0f   netdisco/netdisco:latest-backend                    "/home/netdisco/bin/…"   20 minutes ago   Up 20 minutes                                                                                                                root-netdisco-backend-1

cbbaf49aaf3a   netdisco/netdisco:latest-web                        "/home/netdisco/bin/…"   20 minutes ago   Up 20 minutes               0.0.0.0:5000->5000/tcp, :::5000->5000/tcp root-netdisco-web-1

113af3d56ffe   netdisco/netdisco:latest-postgresql                 "/usr/local/bin/netd…"   20 minutes ago   Up 20 minutes               5432/tcp  root-netdisco-postgresql-1
``` 

## Config info (deployment.yml)
Default file no changes made

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

[27] 2022-12-14 10:13:10  info App::Netdisco version 2.060002 loaded.
[27] 2022-12-14 10:13:10  info show: error - Don't know device: 1.1.1.1

**Comment by rc9000** [comment]
Should be fixed, please see https://github.com/netdisco/netdisco-docker/issues/50
