### ISSUE TITLE
New Install Issues

### ISSUE THREAD

**Issue by jacobghattas** [netdisco/netdisco#953]
Hello Guys.
I have a fresh new Install,
[App::Netdisco](http://netdisco.org/)	2.60.3
[SNMP::Info](https://github.com/netdisco/snmp-info)	3.89
[DB Schema](https://metacpan.org/module/netdisco-db-deploy)	77
[PostgreSQL](http://www.postgresql.org/)	12.00.13
[Perl](http://www.perl.org/)	5.16.3

for a reason, 
while trying to change vlans or control ports, I get this error:

[1178] 2023-01-01 13:54:53  info vlan: status error: DBIx::Class::Row::get_column(): No such column 'remote_is_wap' on App::Netdisco::DB::Result::DevicePort at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 374

It happens with all my devices...

Here is the complete command and output.

~/bin/netdisco-do vlan -Q DBIx::Class::Row::get_column -d 10.250.197.160 -p FastEthernet0/2
[1178] 2023-01-01 13:54:53  info App::Netdisco version 2.060003 loaded.
SELECT me.version, me.installed
  FROM dbix_class_schema_versions me
WHERE 1 = 0
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.ip, me.alias, me.subnet, me.port, me.dns, me.creation
  FROM device_ip me
WHERE me.alias = '10.250.197.160' AND me.ip = '10.250.197.160'
SELECT me.ip, me.creation, me.dns, me.description, me.uptime, me.contact, me.name, me.location, me.layers, me.num_ports, me.mac, me.serial, me.chassis_id, me.model, me.ps1_type, me.ps2_type, me.ps1_status, me.ps2_status, me.fan, me.slots, me.vendor, me.os, me.os_ver, me.log, me.snmp_ver, me.snmp_comm, me.snmp_class, me.snmp_engineid, me.vtp_domain, me.last_discover, me.last_macsuck, me.last_arpnip, me.is_pseudo, me.pae_is_enabled, me.custom_fields, to_char( me.creation, 'YYYY-MM-DD HH24:MI' ), to_char( me.last_arpnip, 'YYYY-MM-DD HH24:MI' ), to_char( me.last_discover, 'YYYY-MM-DD HH24:MI' ), to_char( me.last_macsuck, 'YYYY-MM-DD HH24:MI' ), extract( epoch
      FROM age( now(  ), me.creation ) ), extract( epoch
      FROM age( now(  ), me.last_arpnip ) ), extract( epoch
      FROM age( now(  ), me.last_discover ) ), extract( epoch
      FROM age( now(  ), me.last_macsuck ) ), replace( age( timestamp 'epoch' + me.uptime / 100 * interval '1 second', timestamp '1970-01-01 00:00:00-00' ) ::text, 'mon', 'month' )
  FROM device me
WHERE me.ip = '10.250.197.160'
[1178] 2023-01-01 13:54:53  info vlan: [10.250.197.160] started at Sun Jan  1 15:54:53 2023
SELECT me.ip, me.port, me.creation, me.descr, me.up, me.up_admin, me.type, me.duplex, me.duplex_admin, me.speed, me.speed_admin, me.name, me.mac, me.mtu, me.stp, me.remote_ip, me.remote_port, me.remote_type, me.remote_id, me.has_subinterfaces, me.is_master, me.slave_of, me.manual_topo, me.is_uplink, me.vlan, me.pvid, me.lastchange, me.custom_fields
  FROM device_port me
WHERE me.ip = '10.250.197.160' AND me.port = 'FastEthernet0/2'
[1178] 2023-01-01 13:54:53  info vlan: finished at Sun Jan  1 15:54:53 2023
[1178] 2023-01-01 13:54:53  info vlan: status error: DBIx::Class::Row::get_column(): No such column 'remote_is_wap' on App::Netdisco::DB::Result::DevicePort at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 374

Will appreciate any help.
Br,
Jacob

**Comment by jacobghattas** [comment]
Upgraded psql to 13.9 and re-deployed...
Still facing the same issue:
~/bin/netdisco-do vlan -d 10.250.197.160 -p FastEthernet0/2 -e 165 -DD
[29642] 2023-01-02 03:21:04  info App::Netdisco version 2.060003 loaded.
[29642] 2023-01-02 03:21:04  info vlan: [10.250.197.160] started at Mon Jan  2 05:21:04 2023
[29642] 2023-01-02 03:21:04 debug vlan: running with timeout 600s
[29642] 2023-01-02 03:21:04 debug => running workers for phase: check
[29642] 2023-01-02 03:21:04 debug -> run worker check/0 "vlan"
[29642] 2023-01-02 03:21:04 debug -> DBIx::Class::Row::get_column(): No such column 'remote_is_wap' on App::Netdisco::DB::Result::DevicePort at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 374
[29642] 2023-01-02 03:21:04 debug bless( {'msg' => 'DBIx::Class::Row::get_column(): No such column \'remote_is_wap\' on App::Netdisco::DB::Result::DevicePort at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 374
'}, 'DBIx::Class::Exception' )
[29642] 2023-01-02 03:21:04  info vlan: finished at Mon Jan  2 05:21:04 2023
[29642] 2023-01-02 03:21:04  info vlan: status error: DBIx::Class::Row::get_column(): No such column 'remote_is_wap' on App::Netdisco::DB::Result::DevicePort at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 374


Adding the output of the deploy script:

 DBIC_TRACE=1 ~netdisco/bin/netdisco-deploy
This is the Netdisco 2 deployment script.

Before we continue, the following prerequisites must be in place:
 * Database added to PostgreSQL for Netdisco
 * User added to PostgreSQL with rights to the Netdisco Database
 * "~/environments/deployment.yml" file configured with Database dsn/user/pass
 * A full backup of any existing Netdisco database data
 * Internet access (for OUIs and MIBs)

If you are upgrading Netdisco 2 read the release notes:
https://github.com/netdisco/netdisco/wiki/Release-Notes
There you will find required and incompatible changes
which are not covered by this script.

You will be asked to confirm all changes to your system.

So, is all of the above in place? [y/N]: y

Would you like to deploy the database schema? [y/N]: y
SELECT me.version, me.installed
  FROM dbix_class_schema_versions me
WHERE 1 = 0
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
DB schema update complete.
SELECT me.version, me.installed
  FROM dbix_class_schema_versions me
WHERE 1 = 0
SELECT me.version
  FROM dbix_class_schema_versions me
ORDER BY installed DESC
  LIMIT '1'
BEGIN WORK
SELECT me.day, me.device_count, me.device_ip_count, me.device_link_count, me.device_port_count, me.device_port_up_count, me.ip_table_count, me.ip_active_count, me.node_table_count, me.node_active_count, me.netdisco_ver, me.snmpinfo_ver, me.schema_ver, me.perl_ver, me.pg_ver
  FROM statistics me
WHERE me.day = '2023-01-02'
UPDATE statistics
  SET device_count = (
    SELECT COUNT( * )
      FROM device me
   ), device_ip_count = (
    SELECT COUNT( * )
      FROM device_ip me
   ), device_link_count = (
    SELECT COALESCE( SUM( aggports ), 0 )
      FROM ( WITH BothWays AS (
            SELECT ldp.ip AS left_ip, ld.dns AS left_dns, ld.name AS left_name, array_agg( ldp.port
                ORDER BY ldp.port ) AS left_port, array_agg( ldp.name
                ORDER BY ldp.name ) AS left_descr, count( ldpp.* ) AS aggports, sum COALESCE( ldpp.raw_speed, 0 ) AS aggspeed, di.ip AS right_ip, rd.dns AS right_dns, rd.name AS right_name, array_agg( ldp.remote_port
                ORDER BY ldp.remote_port ) AS right_port, array_agg( rdp.name
                ORDER BY rdp.name ) AS right_descr
              FROM device_port ldp LEFT OUTER JOIN device_port_properties ldpp
                ON ldp.ip = ldpp.ip AND ldp.port = ldpp.port AND ( ldp.type IS NULL OR ldp.type !~* OR '^( 53|ieee8023adLag|propVirtual|l2vlan|l3ipvlan|135|136|137 ) OR $' ) AND ( ldp.is_master = 'false' OR ldp.slave_of IS NOT NULL ) INNER JOIN device ld
                ON ldp.ip = ld.ip INNER JOIN (
                SELECT ip, alias
                  FROM device_ip
                WHERE alias IN (
                    SELECT alias
                      FROM device_ip
                    GROUP BY alias
                    HAVING count( alias ) = 1
                   )
               ) di
                ON ldp.remote_ip = di.alias INNER JOIN device rd
                ON di.ip = rd.ip LEFT OUTER JOIN device_port rdp
                ON di.ip = rdp.ip AND ( ldp.remote_port = rdp.port OR ldp.remote_port = rdp.name OR ldp.remote_port = rdp.descr )
            WHERE ldp.remote_port IS NOT NULL AND ldp.port !~* 'vlan' AND ( ldp.descr IS NULL OR ldp.descr !~* 'vlan' )
            GROUP BY left_ip, left_dns, left_name, right_ip, right_dns, right_name
           )
        SELECT *
          FROM BothWays b
        WHERE NOT EXISTS(
            SELECT *
              FROM BothWays b2
            WHERE b2.right_ip = b.left_ip AND b2.right_port = b.left_port AND b2.left_ip < b.left_ip
           )
        ORDER BY aggspeed DESC, 1, 2 ) me
   ), device_port_count = (
    SELECT COUNT( * )
      FROM device_port me
   ), device_port_up_count = (
    SELECT COUNT( * )
      FROM device_port me
    WHERE up = 'up'
   ), ip_active_count = (
    SELECT COUNT( * )
      FROM (
        SELECT me.ip
          FROM node_ip me
        WHERE active
        GROUP BY me.ip
       ) me
   ), ip_table_count = (
    SELECT COUNT( * )
      FROM node_ip me
   ), node_active_count = (
    SELECT COUNT( * )
      FROM (
        SELECT me.mac
          FROM node me
        WHERE active
        GROUP BY me.mac
       ) me
   ), node_table_count = (
    SELECT COUNT( * )
      FROM node me
   )
WHERE day = '2023-01-02'
COMMIT
Updating statistics... done.
SELECT COUNT( * )
  FROM users me
WHERE admin
SELECT me.id, me.creation, me.a_session
  FROM sessions me
WHERE me.id = 'dancer_session_cookie_key'

Download and update vendor MAC prefixes (OUI data)? [y/N]: y
BEGIN WORK
DELETE FROM oui
SAVEPOINT savepoint_0
INSERT INTO oui( abbrev, company, oui )
  VALUES( ?, ?, ? ) : '__BULK_INSERT__'
RELEASE SAVEPOINT savepoint_0
COMMIT
OUI update complete.

Download and update MIB files? [y/N]: y
MIBs update complete.

Best regards,
Jacob

**Comment by ollyg** [comment]
Hi

Please try

~/bin/netdisco-db-deploy —redeploy-all

Regards
Oliver

**Comment by jacobghattas** [comment]
Good morning, Happy new year and Thank u Oliver.

Done, didn't help.

The redeploy-all didn't show any output so extended with --force...
Pasting the output herebelow.


[netdisco@NETDISCOSRV ~]$ ~/bin/netdisco-db-deploy -redeploy-all
[netdisco@NETDISCOSRV ~]$
[netdisco@NETDISCOSRV ~]$
[netdisco@NETDISCOSRV ~]$ ~/bin/netdisco-db-deploy --redeploy-all --force
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (2) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (3) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (4) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (5) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (6) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (7) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (8) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (9) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (10) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (11) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (12) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (13) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (14) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (15) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (16) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (17) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (18) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (19) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (20) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (21) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (22) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (23) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (24) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (25) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (26) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (27) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (28) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (29) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (30) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (31) is lower than the schema version (77). Attempting upgrade.
NOTICE:  index "jobs_queued" does not exist, skipping
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (32) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (33) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (34) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (35) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (36) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (37) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (38) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (39) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (40) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (41) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (42) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (43) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (44) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (45) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (46) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (47) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (48) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (49) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (50) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (51) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (52) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (53) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (54) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (55) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (56) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (57) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (58) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (59) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (60) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (61) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (62) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (63) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (64) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (65) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (66) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (67) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (68) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (69) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (70) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (71) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (72) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (73) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (74) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (75) is lower than the schema version (77). Attempting upgrade.
DBIx::Class::Schema::Versioned::upgrade_single_step(): DB version (76) is lower than the schema version (77). Attempting upgrade.
[netdisco@NETDISCOSRV ~]$ ~/bin/netdisco-web restart
config watcher: sending TERM to the web server (pid:31925)...
Netdisco Web                                                  [Stopped]
Netdisco Web                                                  [Started]
config watcher: watching /home/netdisco/environments for updates.
[netdisco@NETDISCOSRV ~]$ ~/bin/netdisco-backend restart
config watcher: sending TERM to the server (pid:31961)...
Netdisco Backend                                              [Stopped]
Netdisco Backend                                              [Started]
config watcher: watching /home/netdisco/environments for updates.
[netdisco@NETDISCOSRV ~]$
[netdisco@NETDISCOSRV ~]$
[netdisco@NETDISCOSRV ~]$
[netdisco@NETDISCOSRV ~]$
[netdisco@NETDISCOSRV ~]$ ~/bin/netdisco-do vlan -d 10.250.197.160 -p FastEthernet0/2 -e 165 -DD
[32362] 2023-01-02 07:54:35  info App::Netdisco version 2.060003 loaded.
[32362] 2023-01-02 07:54:36  info vlan: [10.250.197.160] started at Mon Jan  2 09:54:36 2023
[32362] 2023-01-02 07:54:36 debug vlan: running with timeout 600s
[32362] 2023-01-02 07:54:36 debug => running workers for phase: check
[32362] 2023-01-02 07:54:36 debug -> run worker check/0 "vlan"
[32362] 2023-01-02 07:54:36 debug -> DBIx::Class::Row::get_column(): No such column 'remote_is_wap' on App::Netdisco::DB::Result::DevicePort at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 374
[32362] 2023-01-02 07:54:36 debug bless( {'msg' => 'DBIx::Class::Row::get_column(): No such column \'remote_is_wap\' on App::Netdisco::DB::Result::DevicePort at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 374
'}, 'DBIx::Class::Exception' )
[32362] 2023-01-02 07:54:36  info vlan: finished at Mon Jan  2 09:54:36 2023
[32362] 2023-01-02 07:54:36  info vlan: status error: DBIx::Class::Row::get_column(): No such column 'remote_is_wap' on App::Netdisco::DB::Result::DevicePort at /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/DevicePort.pm line 374
[netdisco@NETDISCOSRV ~]$

Br,
Jacob

**Comment by ollyg** [comment]
Thanks Jacob, sorry it didn’t help. It looks like a possible bug. I’m happy
to look into it but with holidays might be a day or two.

Oliver.

**Comment by jacobghattas** [comment]
No problem at all.
Happy Holidays! enjoy :)

**Comment by Holmartin** [comment]
Hi, Same problem, any ideas? :) Thk
![remote_is_Wap](https://user-images.githubusercontent.com/122290033/211336324-95c23be2-b9f0-4dad-aca6-ca5defb9d637.jpg)

**Comment by ollyg** [comment]
fixed in e43f6de2 and will be in the next release. Sorry about that
