### ISSUE TITLE
Minor UX request regarding serial numbers

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#964]
I'm currently having to rationalise our support contract against what switches we actually have, and so have been doing a lot of chasing down of serial numbers.

* If you view a device that is part of a stack, the device overview page will list one serial number - that of the stack master. It would be very helpful if it included the serial numbers of all stack members, perhaps in the form "sn_switch1 (sn_switch2, snswitch3, etc)". 

* When you look at the 'modules inventory' it would be very useful if there was a 'vendor' column you could search by (e.g. to only see cisco devices)

* device report by location would benefit from a serial number field containing sns of all stack members

* the serial number returned for all our Dell switches is not the service tag, which is to all intents and purposes the serial number that is relevant when talking about support or warranty. It would be very helpful if instead it used
.1.3.6.1.4.1.674.10895.3000.1.2.100.8.1.4
productIdentificationServiceTag
from Dell-Vendor-MIB which exposes the service tag as value "1".

Thanks!

**Comment by ollyg** [comment]
Hi @kingtrw 

Might be worth trying changing (reverting) this config if you can, to see if there's any useful change:
https://github.com/netdisco/netdisco/wiki/Vendor-Tips#report-cisco-as-single-device-instead-of-stacked-37xx29xxetc

Not sure it's going to be easy to get stack info into Netdisco given its current data model (assumes one device, one serial, and you ask for one device multiple serial?).

However you give me an idea for a cool feature request. To add to the custom_fields configuration with the name of a MIB leaf which could be directly put into it, i.e. your Dell boxes have a custom field which gets productIdentificationServiceTag.

**Comment by ollyg** [comment]
Sorry just to add I know you have Dell not Cisco, but perhaps it has the same report-as-stack-or-not config to fiddle with.

**Comment by kingtrw** [comment]
I don't know how accessible this info is, but it's all available under the 'modules' view; there's the stack primary and then the component units all listed under it.

ND is aware of the other serial numbers to some extent because if I search for the serial number of a stack member, it'll take me to the device page for the stack.

Maybe you could consider the serial number for a stack to be a concatenated comma seperated string of the serial numbers of all the stack components? That would _technically_ be one serial number per device, right?

**Comment by ollyg** [comment]
closing in favour of #973 and #974
