### ISSUE TITLE
FR: better job queue, sorting and filtering

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#969]

**Comment by NoifP** [comment]
It'd be awesome to see the following stats for the job queue:
* total jobs
* done jobs
* queued jobs (not started)
* in progress jobs (started but not finished)

Also, it'd be useful to be able to get a list of jobs that have been running for more than 5 minutes (or some appropriate amount of time).

Another useful thing would be to click on one of the queued (not started) jobs and prioritize it to run next.

**Comment by ollyg** [comment]
> 09:29 <Adminguy> users (network guys) don't have access to CLI they can only connect to the GUI. They have to launch large network discover (with /20 CIDR) several times a week, on the "job queue page" it's easy to see on which IP netdisco have found something (or not), but the record list is too short regarding the size of the network. So it would be nice to have
> 09:29 <Adminguy> a longer record list and having paging option (like in report pages for example).

**Comment by ollyg** [comment]
> the ability to choose how much records to display on a page (10,25,50 .. )

**Comment by kingtrw** [comment]
Couple of related ideas that I think could be very useful:

* if there was a search field that could be used to filter by type or address
* if there were buttons that could be used to filter type entries

My most common use case for looking at this page is when I manually discover a device - but at the moment it's very hard to keep track of it as it disappears quite quickly in amongst all the arpnips etc.

**Comment by ollyg** [comment]
implemented in 21bc8cf6 and ae3ad986 and b1e25346
