### ISSUE TITLE
Bug in the api

### ISSUE THREAD

**Issue by riccardo01luppi** [netdisco/netdisco#971]
bug, when i'm trying to get the json response at the endpoint of search node, i receive not a json file but i think a page html.
This behaviour happens always or sometimes. i'm making the request with curl, and i put all the header like Content-type: application/json, accept: application/json and authorization

if someone has the solution or there is something about that i don't know

Expected Behavior

i expect a response in json format

Current Behavior

the api give me a response in html

Steps to Reproduce (for bugs)

i make the request in a file php with the function exec like:

$resp=json_decode(exec('curl -X GET "[http://10.15.1.1:5000/api/v1/search/node?q='.$querymac.'&partial=false&deviceports=true&show_vendor=false&archived=false&daterange=1970-01-01%20to%20'.$year.'-'.$month.'-'.$day.'&age_invert=false](http://10.15.1.1:5000/api/v1/search/node?q=%27.$querymac.%27&partial=false&deviceports=true&show_vendor=false&archived=false&daterange=1970-01-01%20to%20%27.$year.%27-%27.$month.%27-%27.$day.%27&age_invert=false)" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: ' .$_SESSION['netdisco_apikey']. '"', $response));

**Comment by ollyg** [comment]
duplicate
