### ISSUE TITLE
FR: assign an SNMP leaf/OID to a custom field for automatic fill during discover/macsuck

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#973]
macsuck for ports, obvs

**Comment by ollyg** [comment]
could be per port daily on discover or hourly on macsuck and user could choose?

**Comment by rsuaver** [comment]
I'd love to add phone extensions or access point names mapped to a field. This information is available via LLDP as DeviceID.

**Comment by ollyg** [comment]
implemented in 2.079001

**Comment by ollyg** [comment]
as an aside, the request by @rsuaver for phone extensions or access point names retrieved via LLDP peer info is tricky to implement, as this is retrieved on one device but refers to the peer device on the port. would be better implemented as an external script, could be in a Hook, updating Netdisco device custom fields
