### ISSUE TITLE
IP address shows when searched but not in report IP Inventory

### ISSUE THREAD

**Issue by huntson** [netdisco/netdisco#976]
I am running Netdisco 2.58.3 and most things appear to be working quite well (I haven't tried all the features).  If I search for an IP address in the 'Find Anything' field such as 10.96.50.91, it shows me which switch it is connected to and all the normal info.  If I go to Reports -> IP -> IP Inventory and then put in 10.96.50.0/24, a small subset of the devices I can look up via the 'find anything' appear.  Any idea why?

**Comment by ollyg** [comment]
possible same is as #1039
