### ISSUE TITLE
Does the API support tenants?

### ISSUE THREAD

**Issue by dtuecks** [netdisco/netdisco#982]
Hi,

I'd like to pull some reports via API. Can I switch the tenant in an API request? I could not find this in the docs.

Thanks
Daniel

**Comment by ollyg** [comment]
Hi @dtuecks

Yes it works (or should work!) fine. Just add `/t/{tenantname}` at the base of the path, i.e. before `/api`.

The thing to note is that the login/logout endpoints are independent of the tenant (same as the web interface). So you log into the API using an account in your default tenancy, and then can call any other endpoint with tenant prefix, as above.
