### ISSUE TITLE
feature request: ssh support for discovery as already exists for arpnip

### ISSUE THREAD

**Issue by ncansado** [netdisco/netdisco#996]
Hi,

Actually im requesting for feature, not reporting any bug. Also not experienced developer at all.

My case:
Checkpoint VSX during snmp discovery interface ips returned are internal ips for vsx functionality which are not the ips that workloads uses.
eg: eth1: vsx internal ip 192.168.0.1 - data ip : 10.0.0.1
snmp ip info returns 192.168.0.1 instead 10.0.0.1
to get 10.0.0.1 is only possible via ssh.
Since this is information is only possible via ssh, is possible to extend discovery via ssh like arpnip?

**Comment by rc9000** [comment]
Hi! Currently there's no official support for SSH discovery. But what you can do is using a [discovery hook](https://github.com/netdisco/netdisco/wiki/Hooks). This will launch a script that you provide after discovery, with parameters to identify the device as arguments.

In the script, you can interact yourself with the netdisco database, in your case you would presumably just get your information an then add or change some records in the device or device_ip tables.

Here's an example that goes into a similar direction, modifying uplink properties of devices after discovery:
https://github.com/rc9000/netdisco_discover_hook

To make an SSH connection to your VSX, you can find some code to copy/paste in the modules for [SSH arpnip.](https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/SSHCollector/Platform/CPVSX.pm)

**Comment by ncansado** [comment]
> Hi! Currently there's no official support for SSH discovery. But what you can do is using a [discovery hook](https://github.com/netdisco/netdisco/wiki/Hooks). This will launch a script that you provide after discovery, with parameters to identify the device as arguments.
> 
> In the script, you can interact yourself with the netdisco database, in your case you would presumably just get your information an then add or change some records in the device or device_ip tables.
> 
> Here's an example that goes into a similar direction, modifying uplink properties of devices after discovery: https://github.com/rc9000/netdisco_discover_hook
> 
> To make an SSH connection to your VSX, you can find some code to copy/paste in the modules for [SSH arpnip.](https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/SSHCollector/Platform/CPVSX.pm)

Sounds a plan, let me spend some time on our suggestion, and if I can produce something that is worthy to share with group Ill do it.

Thanks and hopefully talk soon.

N
